### ISSUE TITLE
Sandbox code

### ISSUE THREAD

**Issue by laurentateegle** [Viglino/ol-ext#1002]
Sorry for my stupid question. I have discovered your work and find it incredible. 
I went through the different demos but would like to get the source code helping me to understand how to use this extension.
The API doc is well done but I can not find end-to-end samples of code. It would be very helpful to get the code under each demo tyou propose.

Thanks in advance and congrats once again

**Comment by Viglino** [comment]
All demos are a single page with sample code inside (one per feature).
Use right-click + show source code or https://github.com/Viglino/ol-ext/tree/master/examples
