### ISSUE TITLE
filter.mask not always looping

### ISSUE THREAD

**Issue by theheckwr** [Viglino/ol-ext#1008]
I'm sorry to bring this up again, but the looping of a mask / crop across multiple worlds seems to not work properly at all times:
![image](https://github.com/Viglino/ol-ext/assets/22587394/ae0b922a-e5c5-4b0c-93cb-3b16e7c265c8)
When the map is slightly offset, it however does work:
![image](https://github.com/Viglino/ol-ext/assets/22587394/19ca1ad2-ba41-4bb9-9084-213c6e665761)

To fix this, I'm proposing the following change (this fixed it for me, but I'm not sure whether this is the proper way to fix it):
`src/filter/Mask.js`, ln. 133+134:
```javascript
var start = Math.floor((extent[0] + fWidth - worldExtent[0]) / worldWidth) + 1;
var end = Math.floor((extent[2] - fWidth - worldExtent[2]) / worldWidth) - 1;
````

Thanks for this great library, let me know if I can be of any help when solving this issue.

**Comment by Viglino** [comment]
Should be fixed

**Comment by Viglino** [comment]
[ol-ext@4.0.12](https://www.npmjs.com/package/ol-ext) is out.

**Comment by theheckwr** [comment]
Sorry, for the delay.
I went straight to 4.0.13 and it looks like it's fixed.
Thanks a lot!
