### ISSUE TITLE
Popup Overlay getCoordinates()

### ISSUE THREAD

**Issue by shinjjo** [Viglino/ol-ext#101]
Hi, I found a problem in Popup overlay code and it is worth to report. 

In the code below, getCoordinates() should be amended to getFirstCoordinate() when the coordinates are polygons. The popup did not work with getCoordinates(), but works perfect with getFirstCoordinate().
I guess this is caused from the recent polygon support update. 

Appreciate for creating awesome library!

```
  // On selected => show/hide popup
  select.getFeatures().on(['add'], function(e)
  { var feature = e.element;
    var content = "";
    content += feature.get('name');
    popup.show(feature.getGeometry().getCoordinates(), content); 
  })
  select.getFeatures().on(['remove'], function(e)
  { popup.hide(); 
  })
```

**Comment by Viglino** [comment]
Hi,

The code is just an example that use point features. If you want to use it with other features types you'll have to adapt it. With polygons you would prefer use `getInteriorPoint()`. But if the polygon is to large this point can be outside the screen and the best way would to place the popup under the cursor itself.

Anyway I've changed the code to make it more generic.

@+
