### ISSUE TITLE
Photo shadow property is handled as number but declared as boolean

### ISSUE THREAD

**Issue by philzartis** [Viglino/ol-ext#1019]
The Photo style shadow property is [declared as boolean](https://github.com/Viglino/ol-ext/blob/0cf076cc0791d9bb4b28fdf0222ecf4a8ad9fd17/src/style/Photo.js#L21) but [handled as number](https://github.com/Viglino/ol-ext/blob/0cf076cc0791d9bb4b28fdf0222ecf4a8ad9fd17/src/style/Photo.js#L41). The example also uses it [as number](https://github.com/Viglino/ol-ext/blob/0cf076cc0791d9bb4b28fdf0222ecf4a8ad9fd17/examples/style/map.style.photo.html#L108). This issue extends into the [TS types declarations](https://github.com/Siedlerchr/types-ol-ext/blob/0a9d32240c5d0fd0bf5db0746e7f46603cf799ed/%40types/ol-ext/style/Photo.d.ts#L9) as well.

**Comment by Viglino** [comment]
Yes the shadow is a shadow width indeed... fixed in the last commit: https://github.com/Viglino/ol-ext/commit/3f866265676854726ea852669016276ba48f1935
