### ISSUE TITLE
error in using LayerSwitcher.js under typescript / angular 5

### ISSUE THREAD

**Issue by DSpada** [Viglino/ol-ext#102]
I am using ol-ext in a webpack, angular 5 / typescript application.
I found an error when use LayerSwitcher.js.

import LayerSwitcher from 'ol-ext/control/LayerSwitcher';
...
    var layerSwitcher = new LayerSwitcher();
    this.map.addControl(layerSwitcher);

ERROR:
ReferenceError: $ is not defined
    at new ol_control_LayerSwitcher (LayerSwitcher.js:56)

**Comment by Viglino** [comment]
Some ol-ext modules use jQuery ($). 
Look at [ol-ol-ext-webpack-example](https://github.com/darkscript/ol-ol-ext-webpack-example).

**Comment by DSpada** [comment]
thank you, I had forgotten jquery.
