### ISSUE TITLE
filter.Mask with large number of coordinates not working when zooming in on Android mobile devices

### ISSUE THREAD

**Issue by sasvb** [Viglino/ol-ext#1021]
In the screenshot below a gray mask is shown based on geometry with a large number of coordinates (see attachment array.txt).
Initially this works fine.
![before](https://github.com/Viglino/ol-ext/assets/135003993/a0c8a9d4-2c14-4d3c-9182-27cec42c7021)

However when zooming in on the map, the entire layer turns gray.
Problem only occurs on Android mobile devices, not reproducible on iPhone.
![after](https://github.com/Viglino/ol-ext/assets/135003993/5be0c3c0-5aed-4642-b2f1-f2a7f438b25b)

[array.txt](https://github.com/Viglino/ol-ext/files/13904847/array.txt)

**Comment by Viglino** [comment]
it's probably a canvas (and browser version) issue (see #1003).
NB: the mask is not very efficient with a large number of points maybe you could use a layer on top with an object that mask.
or filter the mask to have lesser points...

**Comment by sasvb** [comment]
I wanted to let you know that this issue was resolved with the Chrome update of January 23, 2024.
