### ISSUE TITLE
LayerSwitcher style can't be rendered

### ISSUE THREAD

**Issue by Inrap** [Viglino/ol-ext#1022]
I am using the latest versions of OpenLayers and ol-ext (4.0.13) in ES6.
I an trying to use the layerswitcher module.
  
 In my js file, despite a warning, the module seems to be imported.
    `import LayerSwitcher from "ol-ext/control/LayerSwitcher`
 
![image](https://github.com/Viglino/ol-ext/assets/32261793/66cad246-3e60-4781-94d2-db16e430f99e)
The layerswitcher is rendered outside the map object, but as you can see it is not the correct style.
I tried to import styles I saw in the ol-ext folder (ex : `@import "node_modules/ol-ext/control/LayerSwitcher.css";`) but obviously, that is not the way to do it.
How can I import the style(s) to have the layerswitcher like in the API doc ?

**Comment by Viglino** [comment]
I've updated the doc on the [main page](https://github.com/Viglino/ol-ext?tab=readme-ov-file#using-ol-ext-in-a-webpack).

**Comment by Inrap** [comment]
Thank you. I choose the css way becaue I began like this.
