### ISSUE TITLE
Calculated fields in PopupFeature not displaying

### ISSUE THREAD

**Issue by andresosorios23** [Viglino/ol-ext#1025]
When you try to calculate an attribute it does not display in the popup.  It also happens in the example in the webpage

![image](https://github.com/Viglino/ol-ext/assets/60591217/1572d4c9-825d-492d-aba3-c54523fda9a2)

![image](https://github.com/Viglino/ol-ext/assets/60591217/502594c9-d098-4a26-adf2-9ff729fa91a7)

Am I making a mistake? Thanks in advance.

**Comment by Viglino** [comment]
In the example there is no pop2 property in the data (only pop)...
You have to change switch pop and pop2 to make it run:
```javascript
'pop2': {
  title: 'Population',  // attribute's title
  before: '',           // something to add before
  format: ol.Overlay.PopupFeature.localString(),  // format as local string
  after: ' hab.'        // something to add after
 },
 // calculated attribute
 'pop': {
   title: 'Population (kHab.)',  // attribute's title
   format: function(val, f) {
     return Math.round(parseInt(f.get('pop'))/100).toLocaleString() + ' kHab.'
   }
 }
```
 

<br class="Apple-interchange-newline">
</body>
</html>
```

**Comment by andresosorios23** [comment]
Thanks for your answer. OH, I get it, it only shows attributes that are already in the properties.
Do you have any plans to include custom attributes in the future?

**Comment by Viglino** [comment]
> Do you have any plans to include custom attributes in the future?
No the PopupFeature is a popup dedicated to features attributes.
You can use a select interaction that call a simple popup with custom html in it on select if you want more options.
