### ISSUE TITLE
[PATCH] Add input placeholder options in SearchGeoportailParcelle

### ISSUE THREAD

**Issue by Zeworxx** [Viglino/ol-ext#1026]
Hello,
There are some input fields with missing placeholders options in SearchGeoportailParcelle.
I have added them in the attached patch, can you have a look?

Regards

[add-missing-placeholders-parcel-search.patch](https://github.com/Viglino/ol-ext/files/14178376/add-missing-placeholders-parcel-search.patch)

**Comment by Viglino** [comment]
The best way is to make a pull request. I'll check it and merge it and you will be credited for the job 😄

**Comment by Zeworxx** [comment]
Ok, I will submit a PR for this, thanks!

**Comment by Zeworxx** [comment]
#1028
