### ISSUE TITLE
[PATCH] add option to clear inputs when search is complete in SearchGeoportailParcelle 

### ISSUE THREAD

**Issue by Zeworxx** [Viglino/ol-ext#1027]
Hello, 

I have added an option to clear inputs fields when search is complete in SearchGeoportailParcelle (patch attached).
Would you consider adding this into a future version?

Regards

[add-autoclear-option-parcel-search.patch](https://github.com/Viglino/ol-ext/files/14179092/add-autoclear-option-parcel-search.patch)

**Comment by Viglino** [comment]
If you want to perform a special task on search, you have to do it in your own code using the `parcelle` event:
```javascript
search.on('parcelle', () => search.setInput(''))
```

**Comment by Zeworxx** [comment]
Hi,
Thanks for your answer.
Doing setInput('') as you suggest clears the input field, but does not hide/clear the autocomplete parcel list. This could be done by playing with css but seems better to do in SearchGeoportailParcelle itself.
What do you think?

**Comment by Viglino** [comment]
You can use `search._listParcelle([])`
I've added a new `search.clearParcelList` method, more explicit...

**Comment by Zeworxx** [comment]
Ok, thanks !
