### ISSUE TITLE
How to change the rotation axis

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#103]
Hello,

I'm new in ol and ol-ext ,but after bit of work a can say awesome library , awesome extensions. Thank You!!!

Now my questions are:

1.how I can change the axis of rotation? 
2. how I can change angle using input field?
For example I want to rotate relatively to triangle vertex (not the middle point ), or if I use line ,then the line start point will be my rotation axis.

BR,

**Comment by Viglino** [comment]
Hello,
Sorry, the `ol.interaction.Transform` rotation axis is fixed.
If you want to rotate an object you can use the [ol.geom.Geometry.rotate()](https://openlayers.org/en/latest/apidoc/ol.geom.Geometry.html#rotate) function with an anchor.

**Comment by Dkkemaries** [comment]
Ok , thanks . I thought the same.

**Comment by Viglino** [comment]
Hello,
I've added a new `setCenter` function to define the rotation center.
Look at the [example page](http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html) to see how it runs.
You can change this point on `select` to fit the rules you choose to apply on this behavior.
@+

**Comment by Dkkemaries** [comment]
Wow,great. Thanks a lot
