### ISSUE TITLE
How can i put layer switcher inside overlay menu

### ISSUE THREAD

**Issue by shym88** [Viglino/ol-ext#1031]
How can i put layer switcher inside overlay menu?

**Comment by Viglino** [comment]
As every [ol control](https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html) you can set the `target` option at creation to render it outside the map:
```javascript
var switcher = new ol.control.LayerSwitcher({target: menu.element})
map.addControl(switcher)
```
