### ISSUE TITLE
UndoRedo doesn't seem to support Vectorimages

### ISSUE THREAD

**Issue by bucengfangqi** [Viglino/ol-ext#1035]
openlayer renderMode: 'image' is deprecated . 
I had to use ol/layer/VectorImage, but UndoRedo doesn't seem to support VectorImage

`    // Handle undo/redo stack----------not working on VectorImage
    undoInteraction.on('stack:add', function (e) {
      console.log('====================================');
      console.log(e);
      console.log('====================================');
    });
`

https://github.com/Viglino/ol-ext/assets/22071679/85cf4dca-b339-4509-9b60-3076d16aff10

**Comment by Viglino** [comment]
Hey! nice map project you have!

You're right, there is a test on the layer class to check if it is cancellable. 
I fix it by testing the source instead.
