### ISSUE TITLE
Intermittent Update Behavior for Rotation Handle Position in OL-ext in Transform 

### ISSUE THREAD

**Issue by Iut57I** [Viglino/ol-ext#1037]
Hello!

I'm currently developing an application using OpenLayers ext and have encountered an issue with updating the position of rotation handles for a Transform interaction, particularly when zooming in or out (i.e., on change:resolution). While I've implemented logic to update the rotation handle's position based on the map's resolution, the updates appear intermittently, with noticeable "jumps" rather than smooth transitions.

Here's an overview of the implementation: 
```
// Code snippet to update rotation handle for a single feature
const updateRotateForSingleObject = (features) => {
  const rotateHandleStyle = new Style({
    // Style definition...
    geometry: () => {
      // Logic to calculate new position based on resolution
    },
  });
  console.log('rotate');
  transformInteraction.setStyle('rotate', rotateHandleStyle);
};

// Listening to resolution changes to update handle position
view.on('change:resolution', function(e) {
  const selectedFeatures = transformInteraction.getFeatures();
  if (selectedFeatures.getLength() > 0) {
    if (selectedFeatures.getLength() > 1) {
      updateRotateForManyObjects(selectedFeatures);
    } else {
      updateRotateForSingleObject(selectedFeatures);
    }
  }
});
```

Although the console.log('rotate') statement executes every time the resolution changes, indicating the function is indeed being called, the actual position update of the rotation handle does not always reflect immediately in the UI. It seems to update in "jumps" or sometimes requires additional interaction to display correctly.

I'm looking for guidance on the following:

Why might the rotation handle position updates not display smoothly or consistently upon resolution changes?
Are there any recommended practices or adjustments I can make to ensure the position updates more reliably and smoothly?
Any insights or suggestions on how to address this issue would be greatly appreciated. Thank you for your support
![AnimationGit](https://github.com/Viglino/ol-ext/assets/146338794/aab97116-4798-4c47-9d4c-ae2ad0c28d96)

**Comment by Viglino** [comment]
Maybe it's due to optimization while animating.
Try to set updateWhileAnimating in the overlay that contains the handles:
```javascript
transform.overlayLayer_.updateWhileAnimating_ = true;
// and maybe
transform.overlayLayer_.updateWhileInteracting_ = true;
```
Tell me if it runs, I'll add it on the overlay in constructor.

**Comment by Iut57I** [comment]
Yes, it worked (I added both : ```
transform.overlayLayer_.updateWhileAnimating_ = true;
 transform.overlayLayer_.updateWhileInteracting_ = true;
``` ), thank you very much. Hope for an update.

**Comment by Viglino** [comment]
Great, I'll add it in the constructor to have it work out of the box.

**Comment by Viglino** [comment]
My bad! I miss it! 😞 
I just push the fix.
