### ISSUE TITLE
FontSymbol Icon not showing only first letter

### ISSUE THREAD

**Issue by satisfazm2bezes** [Viglino/ol-ext#1038]
Hello,

I'm trying to use FontSymbol in an Angular 14 app but the fontawesome icons (fa-mobile) aren't displayed on the first letter (f).
I believe there is some sort of issue with FontSymbol.defs because I have none by default: 

![image](https://github.com/Viglino/ol-ext/assets/17852174/152ec363-a0d5-412e-96d0-055fdb44b64d)

I've tried everything you suggested in older issues but can't put this to work. Any clue?

Thanks!

**Comment by Viglino** [comment]
Do you import the font definition?
```javascript
import 'ol-ext/style/FontAwesomeDef'
```
or the Font Awesome 5 definition:
```javascript
import 'ol-ext/style/FontAwesome5Def'
```

**Comment by satisfazm2bezes** [comment]
Hello, 

Thank you for your reply. I was missing that import, added it and now I have defs populated but looks weird the char property:

![image](https://github.com/Viglino/ol-ext/assets/17852174/45928198-c4ce-42a7-9865-b1b2ef841a1a)

And on the map the icon is not rendered properly:
![image](https://github.com/Viglino/ol-ext/assets/17852174/15720229-851f-4299-8607-fb036aef6914)

I might be missing something here, no?
Thank you for your help.

**Comment by Viglino** [comment]
You also have to add the css to import the font...
```javascript
import '../fonts/font-awesome.min.css'
import '../fonts/FontAwesome.def'
```

You also have to check that the font is loaded before using it (or it may not be displayed correctly):
```javascript
import WebFont from 'webfontloader';

WebFont.load({
  custom: {
  families: ['FontAwesome'],
  // urls: ['./fonts/font-awesome.min.css'],
  testStrings: {'FontAwesome': '\uf240'}},
  classes: false,
  // Fonts are loaded
  fontactive: (f) => {
    // You can use the FontSymbol, clear cache or refresh layers
  },
  // oops
  fontinactive: (f) => {	
    console.warn ("Can't load font: "+f);
  }
});
```

**Comment by satisfazm2bezes** [comment]
Hello again,

Managed to make it work after using webfontloader. Guess I was using the font before it is completely loaded.

Thanks for you help and thank you for all the extensions!
