### ISSUE TITLE
Error while adding Transforminteraction to my map

### ISSUE THREAD

**Issue by SoroTrestal** [Viglino/ol-ext#104]
Hello all, I receive this weird error if i try to add a transform interaction to my map:

```
ol.js:194 Uncaught TypeError: b.S is not a function
    at Function.bj.handles (ol.js:194)
    at ij (ol.js:198)
    at kj.bh (ol.js:201)
    at K.k.pq (ol.js:131)
    at K.eval (ol.js:116)
```
I'm using webpack, 

`import ol_interaction_Transform from "ol-ext/interaction/Transform";`

````
//-- trans --
    me.interactions.trans.interaction = new ol_interaction_Transform({
      layers: [me.viewer.mapObject.editLayer],
      translateFeature: true,
      translate: true,
      scale: true,
      stretch: true
    });    
    me.interactions.trans.interaction.setActive(false);
    //me.interactions.trans.interaction.setDefaultStyle();
    me.interactions.trans.interaction.on(
      ["rotatestart", "translatestart", "scalestart", "stretchstart"],
      function(e) {}
    );
    me.interactions.trans.interaction.on(
      ["rotateend", "translateend", "scaleend", "stretchend"],
      function(e) {}
    );
````

to add the interaction:

me.map.addInteraction(me.interactions.trans.interaction);

Regards

**Comment by Viglino** [comment]
Hello,
I see no error while using the Transform interaction in a webpack (using this example: https://github.com/darkscript/ol-ol-ext-webpack-example).
Adding:
````javscript
import Vector from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import Feature from 'ol/Feature';
import Polygon from 'ol/geom/Polygon';
import ol_interaction_Transform from 'ol-ext/interaction/Transform';
````
and:
````javascript
const vector = new Vector({ source: new VectorSource() });
map.addLayer(vector);
vector.getSource().addFeature(new Feature(new Polygon([[[34243, 6305749], [-288626, 5757848], [210354, 5576845], [34243, 6305749]]])));

const transform = new ol_interaction_Transform({layers: [vector]});
map.addInteraction(transform);
transform.on(
  ["rotatestart", "translatestart", "scalestart", "stretchstart"],
  function(e) { console.log(e); }
);
````

**Comment by Abdullah0991** [comment]
Hi,

I have the same error in using the Transform interaction, I try to use the ol-ext in angular 5 and typescript and openlayers 4.6.

```
import Transform from 'ol-ext/interaction/Transform';
let transform = new Transform({layers: [layer]});
this.map.addInteraction(transform);
```
and the errors:

> TypeError: b.S is not a function
>     at Function.bj.handles (ol.js:198)
>     at ij (ol.js:202)
>     at kj.bh (ol.js:205)
>     at K.k.pq (ol.js:135)
>     at K.eval (ol.js:120)
>     at ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:3979)
>     at ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.runTask (zone.js:188)
>     at ZoneTask.invokeTask (zone.js:496)

> TypeError: d.c is not a function
>     at K.k.bi (ol.js:129)
>     at be.b (ol.js:46)
>     at be.Sc.b (ol.js:49)
>     at be.k.mq (ol.js:73)
>     at Xd.b (ol.js:46)
>     at Xd.Sc.b (ol.js:49)
>     at Od (ol.js:70)
>     at Nd.k.Lp (ol.js:59)
>     at Xd.c (ol.js:68)
>     at HTMLDivElement.b (ol.js:46)

**Comment by Viglino** [comment]
What is the version of your ol-ext package?
Can you try to update to the last version (2.0.3)

**Comment by Abdullah0991** [comment]
Hi, I have ol-ext 2.0.2. Ok I will update to 2.0.3 and try again.

**Comment by Abdullah0991** [comment]
Hi,
I tried the new version 2.0.3 and still the same error :(

**Comment by Viglino** [comment]
Well, this means you're using _Openlayers_ as a js library not as ES6 lib (you don't import ol modules).
So you have to use _ol-ext_ the same way and use the [openlayers-ext JS](https://www.npmjs.com/package/openlayers-ext) package instead of the [ol-ext ES6](https://www.npmjs.com/package/ol-ext) package.
Use `npm install openlayers-ext` and then link to it in your `.angular-cli.json` (you also have to link to jQuery).
````
"styles": [
  "../node_modules/openlayers/dist/ol.css",
  "../node_modules/openlayers-ext/dist/ol-ext.css"
],
"scripts": [
  "../node_modules/openlayers/dist/ol.js",
  "../node_modules/jquery/dist/jquery.min.js",
  "../node_modules/openlayers-ext/dist/ol-ext.js"
],
...
````
You can then access the lib as Openlayers classes:
````javascript
declare const ol: any;
````
and then:
````javascript
const transform = new ol.interaction.Transform({layers: [layer]});
this.map.addInteraction(transform);
````

You can also use ol (and ol-ext) modules as done [here](https://github.com/darkscript/ol-ol-ext-webpack-example/blob/master/main.js) but you can't mix.

**Comment by Abdullah0991** [comment]
Thanks sir, I did all the steps but not worked, it throw error:

> ol.interaction.Transform is not a constructor

And also the I the openlayers lib stopped working also.

**Comment by Abdullah0991** [comment]
Oh sir I am sorry, It's my fault. The extension is working now. I will give it a try.
Thanks very much sir.

**Comment by Abdullah0991** [comment]
Hi, can I import the `ol` lib the old way:  `import * as ol from 'openlayers';`
and have the `ol-ext` functionality too.

Because now the `ol-ext` is working but I got error when I try to create new `ol.Collection`:
`let result = new ol.Collection<ol.Feature>();`

the error says: 

> Untyped function calls may not accept type arguments

and as Google shows me, the problem may because we declare the `ol `variable as `any`:

> declare const ol: any;

Is there any suggestion?

**Comment by Viglino** [comment]
I think you can use:
````javascript
let result = new ol.Collection();
````

**Comment by Abdullah0991** [comment]
You'r right, but as I asked you can I declare ol variable like: `import * as ol from 'openlayers';` ?

And another question: What is the best for me to use the JS libs or ES2015 modules of both ol and ol-ext in my project (webpack,angular5,typescript)?

**Comment by Viglino** [comment]
You can try `import` but you also have to import openlayers-ext (I don't know if it runs).

You can use JS or modules but the syntax in not the same and you'll have to change existing code...
Modules may be more secure (and light) as you just import what you need.

**Comment by Abdullah0991** [comment]
Thanks Viglino, I switched to ES modules for both ol and ol-ext and they'r working fine until now.

But in [ol-ext documentations](http://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html) there no info about the events fired by the Transform interaction, where can I find like this info?

**Comment by Abdullah0991** [comment]
Hi, I have a little confusion about the events fired by the Transform interaction, when user clicks the selected feature -without changing the position of the feature- the interaction fires both 'translatestart' and 'translateend' events, how can I make sure that the feature had really changed(translated)?
