### ISSUE TITLE
Inconsistent naming of profiles

### ISSUE THREAD

**Issue by d-koppenhagen** [Viglino/ol-ext#1042]
The [Control Profile](https://viglino.github.io/ol-ext/examples/control/map.control.profil.html) is names "profile" and "profil" (without an "e") at some places.
The naming should be aligned.

- [x] Breaking Change

**Comment by Viglino** [comment]
There is a mix with profile (english) and profil (french)...
"profile" shoud be the rule...

**Comment by Viglino** [comment]
I've change the name to `ol/control/Profile` 
`ol.control.Profil` style exists for backward compatibility.
The only breaking change is in the css `ol-profil` class...
