### ISSUE TITLE
AnimatedCluster更新后动画消失？

### ISSUE THREAD

**Issue by stdue** [Viglino/ol-ext#1045]
我在使用`AnimatedCluster`的时候，在更新`source`时使用了`setSource`方法去更新数据，但是数据更新成功后动画的效果消失了，再次缩放只获得了僵硬的闪回，想问一下这属于bug吗？还是有更好的更新数据方法？

**Comment by stdue** [comment]
`^4.0.15`

**Comment by Viglino** [comment]
Hello,
There is a bug if you change the `ol/source/Cluster` (there is no events on trigger on the new cluster source)
I fix it in the last commit...

Meanwhile, if you want to update the data, you have to change the source of the `ol/source/Cluster`.
```javascript
clusterLayer.getSource().setSource(datasource)
```
