### ISSUE TITLE
Swipe does not work on two WebGLTile layers

### ISSUE THREAD

**Issue by znxd-wh** [Viglino/ol-ext#1047]
I create two WebGLTile layers with GeoTiff source,
When I use Swipe,left layer disapears. 

var source1 = new GeoTIFF({
      sources: [
        {
          url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/Q/WD/2020/7/S2A_36QWD_20200701_0_L2A/TCI.tif',
        },
      ],
    });
    var webglLayer1 = new WebGLTile({
      source: source1
    })
    var source2 = new GeoTIFF({
      sources: [
        {
          url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/Q/WD/2020/7/S2A_36QWD_20200701_0_L2A/TCI.tif',
        },
      ],
    });
    var webglLayer2 = new WebGLTile({
      source: source2
    })
    var map = new Map({
      target: 'map',
      view: source1.getView(),
      layers: [webglLayer1,webglLayer2]
    });
    var swipe = new Swipe({
      position: 0.5,
      orientation: 'vertical'
    });
    swipe.addLayer(webglLayer1,false)
    swipe.addLayer(webglLayer2,true)
    map.addControl(swipe);

**Comment by Viglino** [comment]
It's working for me...
Do you have a working example online?

**Comment by znxd-wh** [comment]
hey man

here is the example.Just copy the code into map.control.swipe.html in your ol-ext project examples template.
[map.control.swipe.zip](https://github.com/Viglino/ol-ext/files/14903470/map.control.swipe.zip)

**Comment by Viglino** [comment]
You have to set a className to the layers:
```
var webglLayer1 = new WebGLTile({
   className: 'layer1
   source: source1
})
var webglLayer2 = new WebGLTile({
   className: 'layer2
   source: source2
})
```

**Comment by znxd-wh** [comment]
well done man,
it works,
thanks a lot

**Comment by znxd-wh** [comment]
I still have a question,why TileLayer works well without className,but WebGLTileLayer needs a className otherwise it does not work?
