### ISSUE TITLE
Animation stopping when zoom or drag the map

### ISSUE THREAD

**Issue by petya0812** [Viglino/ol-ext#1055]
Hello. I'm beginner in ol-ext. I try to animate some features routes and make a track behind it.
So I create a map with:
1) default osm layer;
2) empty vector layer.

Then I create features, and add their into the layer.
Then for each feature I create animation from Path class and starting 
`vectorLayer.animateFeature(feature, animation)`
But when I drag the map or zoom it animation stopping. 
And when I leave drag features make teleport.

**Comment by Viglino** [comment]
It seems to work fine on the example page: https://viglino.github.io/ol-ext/examples/animation/map.featureanimation.path.html.
Do you have a example online to show the issue?

**Comment by petya0812** [comment]
Thank you for answer, i will do example and return with it

**Comment by petya0812** [comment]
I have some problems with implementation it into sandbox. Thats why i created the github repository: https://github.com/petya0812/map
If it is not hard for you, may you try it locale, please. It is important to me. 
Anyway, thank you so much!

**Comment by Viglino** [comment]
You have to add options `updateWhileAnimating` and `updateWhileInteracting` to your layer to fix it:
```javascript
const vectorLayer = new VectorLayer({
  source: new VectorSource({
    features: features.map(f => [f.baloon, f.track]).flat()
  }),
  updateWhileAnimating: true,
  updateWhileInteracting: true,
...
```

**Comment by petya0812** [comment]
You are the best. Thank you so much!
