### ISSUE TITLE
SelectCluster, changing style in open cluster

### ISSUE THREAD

**Issue by luzhskij** [Viglino/ol-ext#1063]
Hello!
Again I am asking for help.
I use 'ol-ext/interaction/SelectCluster' and 'ol-ext/layer/AnimatedCluster' in the project.

I can’t figure out how to change the style of an open cluster object.
  Those. what I want:
1. Click on the cluster
2. The cluster opened up and showed a spiral with objects
3. A button was pressed somewhere and the style of one of the objects on the spiral changed

Roughly speaking, I need to programmatically emulation a click on an object on an open cluster spiral.

**Comment by Viglino** [comment]
You just have to change the style of object and it will be used to draw the feature.
You can use a style on the object or a style function.

**Comment by luzhskij** [comment]
> You just have to change the style of object and it will be used to draw the feature. You can use a style on the object or a style function. You may have to refresh the cluster layer.
> 
> ```
> // Change a feature type (that code the style)
> feature.set('type', 3);
> // Refresh the layer to reflect the change
> selectCluster.getLayer().changed()
> ```
Thank you! With your help I achieved the desired effect.
Firstly, the style had to be specified in the “SelectCluster -> featureStyle” function.
And secondly, until the “selectCluster.getLayer().changed()” was called, redrawing did not occur.
