### ISSUE TITLE
Escaping characters in SearchField?

### ISSUE THREAD

**Issue by birdy-num-num** [Viglino/ol-ext#1066]
Is there a way to escape certain characters in the user input given to `ol-ext/control/SearchFeature`? My use case is searching for room identifiers that take the form '1.23' or '101'. Currently searching for '1.1' treats the dot as regex so returns 101, 111, etc. Searching for '1\.1' returns the desired results, e.g. 1.10, 1.11 etc but isn't terribly user-friendly. I'd like to escape the dot in the code if possible.

**Comment by Viglino** [comment]
You have to write your own control as a subclass of the auto `SearchFeature` and overwrite the `autocomplete` to escape char:
```javascript
class mySearchFeature extends ol.control.SearchFeature {
  autocomplete(s) {
     var s2 = escape(s)
     return ol.control.SearchFeature.prototype.autocomplete.call(this, s2)
  }
}
```
