### ISSUE TITLE
ol/style/Profile does not handle rotated map correctly

### ISSUE THREAD

**Issue by M393** [Viglino/ol-ext#1075]
When the map is rotated the profile no longer aligns with the line on the map.

![image](https://github.com/Viglino/ol-ext/assets/56256405/62cdad9b-0627-4a5a-b99b-917272dd01c4)
https://viglino.github.io/ol-ext/examples/style/map.style.profile.html

**Comment by Viglino** [comment]
It seems there is a bug with new ol version > 9.1
Fixed in the last commit

**Comment by M393** [comment]
Thank you!
