### ISSUE TITLE
interaction/Transform - Flashing screens on mobile devices

### ISSUE THREAD

**Issue by asrat-77** [Viglino/ol-ext#1077]
Hello,

this Transform interaction is not correct on mobile devices.
Tested.

Relevant error link:
https://github.com/zeppelin/ember-click-outside/issues/25

When the style.cursor value is changed in Transform.js, the wrapper content is flashed

I think the solution is something like this:
example code

if (! 'ontouchstart' in window){
...
element.style.cursor = c
}

**Comment by Viglino** [comment]
Fixed in the last commit
