### ISSUE TITLE
Strange effect when map gets rotated in a ol/layer/Vector3D

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#1079]
Taken this example:
https://viglino.github.io/ol-ext/examples/map/map.layer.3D.2.html

Rotate the map with Shift+Alt+Drag and see the "wrong" effect

Also in this example:
https://viglino.github.io/ol-ext/examples/map/map.layer.3D.html

**Comment by Viglino** [comment]
related to #1075

**Comment by Viglino** [comment]
It seems there is a bug with new ol version > 9.1
Fixed in the last commit

**Comment by 1Map** [comment]
Sorry, ignore my previous message.
