### ISSUE TITLE
Keep browser alive

### ISSUE THREAD

**Issue by RobertVogt** [Viglino/ol-ext#108]
How can I keep the browser/phone alive/active while GPS is in follow mode?

**Comment by Viglino** [comment]
There is no way to ensure the browser is still alive.
Web application lifecycle is hidden to browser application. And that means such app won’t be able to perform any actions while device is in sleep mode or run in background.
If you need this, you should consider native app. [Cordova ](https://cordova.apache.org/) has a [background-geolocation plugin](https://github.com/mauron85/cordova-plugin-background-geolocation) that should do the job.
