### ISSUE TITLE
ol.control.Button is missing disable property

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#1081]
By looking at the documentation I can see that ol.control.Toggle has a disable property, but not ol.control.Button

**Comment by Viglino** [comment]
Disable in Toggle control is mainly to disable the interaction associated with it.
I've added `setDisable` and `getDisable` methods to Button class in the last commit.

**Comment by 1Map** [comment]
Thanks, yes, I thought disable is to disable the button/toggle.  Sometimes there is not physical "control" linked to a button and just some custom functionality.  I needed a property like "disabled" that physically disable the button (greyed out) at runtime.  

Something like:

    const mapMapballButton = new ol.control.Button({
      html: '<div class="fal fa-futbol"></div>',
      className: '',
      tabindex: '-1',
      disabled: true,
      handleClick: (e) => {
        return false;
      }
    });

**Comment by Viglino** [comment]
> Did you update the version. I use 4.0.18 (from npm) and cannot see your change you did.
Not yet...
