### ISSUE TITLE
Magnify Overlay has bug

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#1084]
https://github.com/Viglino/ol-ext/blob/98d5dab3aa0e6b4c7e1f8a2544f9846fa4b38c50/src/overlay/Magnify.js#L83

Think it should be refresh

Also think the following should be refresh

https://github.com/Viglino/ol-ext/blob/98d5dab3aa0e6b4c7e1f8a2544f9846fa4b38c50/examples/style/map.style.pattern.html#L147
https://github.com/Viglino/ol-ext/blob/98d5dab3aa0e6b4c7e1f8a2544f9846fa4b38c50/examples/style/map.style.strokepattern.html#L147

**Comment by Viglino** [comment]
Fixed in last commits

**Comment by 1Map** [comment]
Thanks.  I see that the version is stuck on 4.0.18 for the last 3 months.  I always install through npm.

**Comment by Viglino** [comment]
ol@v4.0.19 is out !
https://www.npmjs.com/package/ol-ext
