### ISSUE TITLE
Reference error in ol-ext 4.0.19

### ISSUE THREAD

**Issue by SebastianBock83** [Viglino/ol-ext#1085]
Hello,

When using version `4.0.19` of ol-ext we got some reference errors when using the LayerSwitcher import.

The error message is that 
![image](https://github.com/user-attachments/assets/bc6a7201-821a-4cb7-b48a-05c619b4b145)

I am using webpack to compile my package and node version `20.11.1`.
Due to lack of access to some code online tools, I am not able to provide an example here. 

I only can say that ol-ext version `4.0.18` is working. 
Based on the semantic versioning specification the bugfix to `4.0.19` should not cause breaking changes, so that I think that this is a bug in the library.

If you need further information, don't hesitate to ask and I will provide you as much as I can.

Best Regards,
Sebastian

**Comment by SebastianBock83** [comment]
@Viglino of course we have Openlayers defined as dependency with version `^9.0.0`. As mentioned in my first post, with `4.0.18` everything worked fine and the update to `4.0.19` breaks our package builds.

**Comment by Viglino** [comment]
You're right the file extension was missing...
Fixed in the last commit

**Comment by SebastianBock83** [comment]
@Viglino thanks for fixing this so fast.
We are looking forward for the next release :-)

Best Regards,
Sebastian

**Comment by Viglino** [comment]
[ol@4.0.20](https://www.npmjs.com/package/ol-ext) is released.
