### ISSUE TITLE
getLastCoordinate doesn't return the last coordinate

### ISSUE THREAD

**Issue by RobertVogt** [Viglino/ol-ext#109]
I'm trying to keep the tool-tip I'm using with geoTrackActive.on("tracking")  when a ol.geom.Polygon but
getLastCoordinate() doesn't return the last coordinate placed on map.

Is there a way to get the last coordinate placed on the map while using GPS to draw a polygon?

**Comment by Viglino** [comment]
Just check the geometry of the tracking feature on `tracking`. Be aware the geometry may not be set on start (thus you have to check if it exists).
````javascript
geoTrackActive.on("tracking"), function(e) {
  var geom = e.feature.getGeometry();
  if (geom) {
    var pt = geom.getLastCoordinate();
    ...
  }
}); 
````
You can also use the `drawing` event that is triggered only when a new coord is added to the track.
````javascript
geoTrackActive.on("drawing"), function(e) {
  var geom = e.feature.getGeometry();
  var pt = geom.getLastCoordinate();
  ...
}); 
````
You also can check the current location (e.location) that may not be inserted on the tack.
