### ISSUE TITLE
When using the Path class, which inherits from FeatureAnimation, and setting the repeat property, it's not possible to get the state at the end of each playthrough.

### ISSUE THREAD

**Issue by starsyrt** [Viglino/ol-ext#1093]
When using the Path class, which inherits from FeatureAnimation, and setting the repeat property, it's not possible to get the state at the end of each playthrough.

**Comment by starsyrt** [comment]
在 animateFeature 函数中，每次动画结束时会调用 onAnimationEnd 方法，你可以在这个方法中获取和处理当前的状态信息。这样可以确保每次动画结束时你都能获取到最新的状态。

**Comment by Viglino** [comment]
I've added an `animationrepeat` event that is fired on every turn.
Use `animationend` for the last one.
