### ISSUE TITLE
Apply more style for AnimatedCluster & interact with PopupFeature

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#1094]
Good morning,
in my project I defined an `ol.layer.AnimatedCluster` without defining an `ol.interaction.SelectCluster`.
I would like your help on 2 issues:

1) Is it possible to define a style to apply when the cluster shows more than one feature on the screen and another style when it shows only one feature?

2) how does `ol.layer.AnimatedCluster` interact with `ol.Overlay.PopupFeature`, I would like to click on the cluster and show PopupFeature as always by browsing more features, but now I find myself in this situation:
First click (How to configure popup feature?)
![2024-08-05 16_14_21-Window](https://github.com/user-attachments/assets/83cde5a4-1013-4f00-a045-2d6e2baa7513)
When zoom in (I would like to select the current feature of the popup feature)
![2024-08-05 16_14_40-Window](https://github.com/user-attachments/assets/4e818a53-c830-4822-aa8d-bc9346e7b13d)

Thank you for your indispensable library

**Comment by Viglino** [comment]
> 1. Is it possible to define a style to apply when the cluster shows more than one feature on the screen and another style when it shows only one feature?
You have to define your own style function (getStyle in the [exemple](https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html). So you can return the style you want.

Also look at: https://viglino.github.io/ol-ext/examples/map/map.dbpedia.photo.html or https://viglino.github.io/ol-ext/examples/map/map.clustering.html

> 2. how does ol.layer.AnimatedCluster interact with ol.Overlay.PopupFeature, I would like to click on the cluster and show PopupFeature as always by browsing more features, but now I find myself in this situation:
First click (How to configure popup feature?)

PopupFeature display the properties of the selected feature ie. the list of features of the cluster when you click on it.
You have to define your own ol/control/Popup to display something else.

> When zoom in (I would like to select the current feature of the popup feature)

When zoom in, clusters change and the selected one is no more on the map.
You can't select a single feature because it may be clustered (thus not on the map).

**Comment by andreaordonselli** [comment]
Thanks, I solved the application of the style as you indicated.

For the selection I chose to exclude it completely in the case of clusters with more than 1 feature.
Therefore I wrote this code thinking of passing the single feature to the popup.
```javascript
selectInteraction.on('select', function(event) {
    selectInteraction.getFeatures().clear();
    var selectedFeatures = event.selected;
    selectedFeatures.forEach(function(feature) {
        if (feature.get('features')) {
            var clusterFeatures = feature.get('features');
            if (clusterFeatures.length === 1) {
                var singleFeature = clusterFeatures[0];
                selectInteraction.getFeatures().push(singleFeature);
            }
        } else {
            selectInteraction.getFeatures().push(feature);
        }
    });
});
```
I get the expected result as clusters containing more than 1 feature are not selected, but the single feature passed to the popup in case of cluster provides this error in the popup, can you tell me why?

```console
Cannot read properties of undefined (reading 'title')
    at olOverlayPopupFeature._getHtml (ol-ext.js:36313:18)
    at olOverlayPopupFeature.<anonymous> (ol-ext.js:36410:23)
```

The console log on singleFeature shows the feature correctly.
Thanks

**Comment by andreaordonselli** [comment]
Thanks Jean, it was the template definition, essentially in the function I find the layer that contains the features, starting from the feature, and I had to modify the search because in the ol.layer.AnimatedCluster there are no single feature but cluster features.
Thanks again.
