### ISSUE TITLE
CanvasScaleLine has an odd overlay or mask in PrintDialog

### ISSUE THREAD

**Issue by ElenaWu171** [Viglino/ol-ext#1096]
There is an odd overlay or mask on the right side of the scale bar, as seen in the attached image. 
When I disable the legend options, the strange overlay on the right side of the scale bar disappears
The overlay appears to be covering part of the scale bar, which is not the intended design. Could anyone please help me identify the cause of this issue and suggest a solution?

![image](https://github.com/user-attachments/assets/436a02a3-b8ea-4019-8542-550a7f283798)
![image](https://github.com/user-attachments/assets/44079851-0fe9-442b-b667-b644f08cd6eb)

```
import CanvasScaleLine from "ol-ext/control/CanvasScaleLine";
import CanvasAttribution from "ol-ext/control/CanvasAttribution";
import CanvasTitle from "ol-ext/control/CanvasTitle";
import PrintDialog from "ol-ext/control/PrintDialog";
import Legend from "ol-ext/legend/Legend";
import ControlLegend from "ol-ext/control/Legend";

const printControl = new PrintDialog({
    lang: "tw", 
  });
  printControl.setSize("A4");
  map.addControl(printControl); 
  map.addControl(
    new CanvasAttribution({
      canvas: true,
    })
  );

  // Add a title control
  map.addControl(
    new CanvasTitle({
      title: "title",
      visible: false,
      style: new Style({
        text: new Text({
          font: '20px "Lucida Grande",Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif',
        }),
      }),
    })
  );
  const PrintscaleLineControl = new CanvasScaleLine();
  map.addControl(PrintscaleLineControl); 


  // Define a new legend
  const legend = new Legend({
    title: "legend",

  });
  const legendCtrl = new ControlLegend({
    legend: legend,
    collapsed: false,
  });
  map.addControl(legendCtrl);

```

**Comment by Viglino** [comment]
It seems something override the legend control CSS when printing.
Make sure there is no CSS on the `.ol-control.ol-legend` class that should hidden.

**Comment by ElenaWu171** [comment]
Thank you for your response. I'd like to add a bit more detail.
When I'm on the map, the scale bar appears normal, but when I open the PrintDialog, the scale bar gets covered by a strange overlay.
![image](https://github.com/user-attachments/assets/9c600004-8d13-4d46-b063-92262e61c835)
![image](https://github.com/user-attachments/assets/e01e3ae1-c409-4f74-9176-cadcbea98584)

**Comment by Viglino** [comment]
The `.ol-control.ol-legend` shold have a `display: none` when inside the `.ol-ext-print-dialog` or it will appear on the map.
Something like:
```CSS
.ol-ext-print-dialog .ol-print-map .ol-control.ol-legend {
  display: none!important
}

**Comment by ElenaWu171** [comment]
I think I successfully removed the strange mask by switching the order of adding features and the scale, like this:
`map.addControl(legendCtrl); // add legend`
`map.addControl(PrintscaleLineControl); // add CanvasScaleLine`
