### ISSUE TITLE
Openlayers textbox tool

### ISSUE THREAD

**Issue by martinmcneela** [Viglino/ol-ext#110]
This is a feature request/enhancement.
first off I love the plugin and it has saved me a massive amount of time with Openlayers.

It would great to have a tool something similar to https://github.com/rumax/Leaflet.Editable.TextBox or https://www.scribblemaps.com/create/.

I am happy to help spec it out if required?

**Comment by Viglino** [comment]
Hy,
You can find an example here: https://codepen.io/viglino/pen/zjeWmG
It's just using the ol.Overlay.Popup to display a popup with an input to change the selected feature attribut.
The it's up to you to create a form in the pop up and choose what you want to do when filled.
@+

**Comment by martinmcneela** [comment]
This is awesome @Viglino, I think it will fit my purpose thanks again.
