### ISSUE TITLE
Add italian to ol/control/PrintDialog

### ISSUE THREAD

**Issue by chicoff** [Viglino/ol-ext#1107]
I @Viglino,  thanks a lot for your great work!

Can you please add italian to the ol/control/PrintDialog

it:{
  title: 'Stampa',
  orientation: 'Orientamento',
  portrait: 'Verticale',
  landscape: 'Orizzontale',
  size: 'Formato pagina',
  custom: 'Dimensione schermo',
  margin: 'Margini',
  scale: 'Scala',
  legend: 'Legenda',
  north: 'Freccia nord',
  mapTitle: 'Titolo della mappa',
  saveas: 'Salva con nome...',
  saveLegend: 'Salva legenda...',
  copied: '✔ Copiato negli appunti',
  errorMsg: 'Impossibile salvare la mappa',
  printBt: 'Stampa',
  clipboardFormat: 'Copia negli appunti...',
  jpegFormat: 'salva come jpeg',
  pngFormat: 'salva come png',
  pdfFormat: 'salva come pdf',
  none: 'nessuno',
  small: 'piccolo',
  large: 'grande',
  cancel: 'annulla'
}

**Comment by Viglino** [comment]
Added in the last commit. 
Meanwhile you can add it manually:
```javascript
PrintDialog.prototype._labels.it = {
  title: 'Stampa',
  orientation: 'Orientamento',
  portrait: 'Verticale',
  ...
}
```

**Comment by chicoff** [comment]
Thank you very much! 
Yes I had already added it in my code but I wanted to share it. 
And I also had to override this special German character (ß), which is not used in Switzerland
ol.control.PrintDialog.prototype._labels.de.custom = 'Bildschirmgrösse';
ol.control.PrintDialog.prototype._labels.de.scale ='Massstab';
ol.control.PrintDialog.prototype._labels.de.large ='gross';
