### ISSUE TITLE
HTTP Error 404 - Package @types/ol-ext Not Found

### ISSUE THREAD

**Issue by Alireezajb** [Viglino/ol-ext#1108]
I'm encountering an error when trying to update my angular version 13 to 14, specifically related to the package @types/ol-ext. The error message indicates that the package could not be found in the npm registry.

```
[error] HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@types%2fol-ext - Not found
    at C:\Users\...\node_modules\npm-registry-fetch\lib\check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ...

```
Expected Behavior:
The installation/update should complete successfully without any errors.

Actual Behavior:
The installation/update fails with a 404 error for @types/ol-ext.

**Comment by Viglino** [comment]
You have to install [ol-ext typescript package](https://github.com/Siedlerchr/types-ol-ext), it's a separate project.
```
# NPM
npm i -D @types/ol-ext@npm:@siedlerchr/types-ol-ext

# Yarn
yarn add -D @types/ol-ext@npm:@siedlerchr/types-ol-ext``# NPM
```
