### ISSUE TITLE
Transform interaction 'select' method not working

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#111]
Hi

I am trying to select a feature to transform using the `select(the)` method of the Transform interaction -using the [documentaion](http://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html#select__anchor)- but when the code is executed the transform interaction fires the 'select' event several times until it throws exception:

> RangeError: Maximum call stack size exceeded
>     at _ol_source_Vector_.boundListener (events.js:17)
>     at _ol_source_Vector_._ol_events_EventTarget_.dispatchEvent (eventtarget.js:86)
>     at _ol_source_Vector_._ol_Observable_.changed (observable.js:58)
>     at _ol_source_Vector_.clear (vector.js:373)
>     at ol_interaction_Transform.drawSketch_ (Transform.js:245)
>     at ol_interaction_Transform.select (Transform.js:304)

And it doesn't select the feature, the previous error happened just first time the code of calling 'select' method is executed.

The code:
```
this.transform = new olx_interaction_Transform({ layers: [layer], features: layer.getSource().getFeaturesCollection() });
this.transform.select(myFeature);
```

and also tried just pass the features option:
`this.transform = new olx_interaction_Transform({ features: layer.getSource().getFeaturesCollection() });
`

I use ol-ext v2.0.3 with Angular 5 and typescript and ol v4.6.

**Comment by Viglino** [comment]
I can't see any problem on the select function.
Be aware the select function will fire a select event ie. don't call it again when you catch the event.
Do you have an example showing the problem.
PS: if layers option is defined, the features option will not be used.

**Comment by Abdullah0991** [comment]
> Be aware the select function will fire a select event ie. don't call it again when you catch the event.

You'r right 👍!

Sorry it's my fault, thanks Viglino.
