### ISSUE TITLE
direct links that query features

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#1110]
I'm using [serch feature](https://viglino.github.io/ol-ext/examples/search/map.control.searchfeature.html) and I've configured it to select the feature and show the popup when I click in a search result.

I would like to create external links to my webgis so that by clicking the link that specific feature is queried, exactly as the search feature does now, do you have any advice for doing this?

I have already integrated [permalink control](https://viglino.github.io/ol-ext/examples/control/map.control.permalink.html?lon=2.431748&lat=48.839295&z=14) into my project, can we use this?

**Comment by Viglino** [comment]
You can use a permalink with an `id` as user parameter.
You can retrieve it with `ctrl.getUrlParam('id')` to select the feature with that id and open the popup.

**Comment by andreaordonselli** [comment]
Thanks,
I configured the reading of the find parameter, which I compose by writing: layer name, field1:value1, field2:value2 etc..
so I can locate the feature and then I pass it to the search.on already configured to select and open popups, this is the result.
Sincere thanks again.

Result:
https://www.opengis.it/ente/qgis2o.gis/?lon=12.950277&lat=43.695143&z=17.8&l=ComuniLimitrofi:1|Confini:1|Edifici:1|Stradario:1|ParticelleCensuario:1&find=Particelle+Censuario,FOGLIO:15,PARTICELLA:17
