### ISSUE TITLE
Search Features - search in multiple sources at the same time

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#1115]
Good morning,
[search features](https://viglino.github.io/ol-ext/examples/search/map.control.searchfeature.html) can be set to search in multiple sources at the same time showing a unique list of results?
I would like to search in multiple simultaneous layers by defining one or more fields to look for.
Thanks

**Comment by Viglino** [comment]
No, but you can create a source collection to concat sources on search (it just need to get features in the source): 
```javascript
class sourceCollection extends ol.source.Vector {
    constructor(opt) {
        opt = opt || {};
        super(opt);
        this._sources = opt.sources
    }
    getFeatures() {
        var a = [];
        this._sources.forEach(s => a = a.concat(s.getFeatures()))
        return a;
    }
}
```
then you can use it as a source:
```javascript
search.setSource(new sourceCollection ({ sources: [source1,source2] })
```

**Comment by andreaordonselli** [comment]
Thank you, this requires both sources to have the same property to search in right? and if the fields to search in were different between the two sources how could I set them?

**Comment by Viglino** [comment]
No, you can define a `getSearchString` function that will take a feature and returns a string to search in, instead of a property name.
```javascript
// Search in prop1 or prop2
var search = new ol.control.SearchFeature({
   source: vectorSource,
   getSearchString: function(f) {
     return (f.get('prop1') || '') + ' ' + (f.get('prop2') || '')
   }
});
```

**Comment by andreaordonselli** [comment]
Sorry but without defining the property value it seems that the `getSearchString:` has no effect

**Comment by Viglino** [comment]
You have to define your own `getSearchString` function.
The default one uses a property value but you can overwrite it.

**Comment by andreaordonselli** [comment]
I understood, thank you.
One last thing, if I enter the `getTitle` setting at a later time this has no effect, while if I write it at the creation of the `var` it works fine, how can I do that?

```javascript
search.set('getTitle', function(f) {
	var title = 'F' + f.get('FOGLIO') + ' ' + 'P' + f.get('PARTICELLA');
	return title;
});
```

**Comment by Viglino** [comment]
getTitle is a function, not a property of the objet: 
```javascript
search.getTitle = function(f) {
	var title = 'F' + f.get('FOGLIO') + ' ' + 'P' + f.get('PARTICELLA');
	return title;
});
```

**Comment by andreaordonselli** [comment]
Many thanks
