### ISSUE TITLE
DrawHole : Not working on MultiPolygon

### ISSUE THREAD

**Issue by marquetd** [Viglino/ol-ext#112]
The DrawHole interaction does not work with MultiPolygon.

I suggest to replace in "ol.interaction.DrawHole.prototype._startDrawing" function

`if (features[0].getGeometry().getType() !== "Polygon")`
by
`if (features[0].getGeometry().getType().indexOf('Polygon') === 0)`

Thanks

**Comment by Viglino** [comment]
To handle MultiPolygons we also have to check wich polygon is concerned to prevent going out of this polygon and to insert the hole in the right polygon of the MultiPolygon. 
Testing the geometry type is not enough.
@+

**Comment by marquetd** [comment]
OK great.

**Comment by Viglino** [comment]
Hello,
The interaction now handle MultiPolygon 😄 
See http://viglino.github.io/ol-ext/examples/style/map.style.scribblefill.html
@+

**Comment by marquetd** [comment]
Hi,

you are awesome !

Thanks !
