### ISSUE TITLE
Request add 'Multi-select' option to 'Transform' interaction

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#113]
Hi Viglino,

I want to request adding 'multi-select' option to the 'Transform' interaction if possible.

Thanks.

**Comment by Abdullah0991** [comment]
Great! when it will be ready to use?

**Comment by Viglino** [comment]
It has been commit and can be used if you link to the github repo.
If you're using npm you'll have to wait for a new version.

**Comment by Abdullah0991** [comment]
How long will it take to release the new npm version?

**Comment by Viglino** [comment]
It seems there is still a bug (see #118).
I'll to push a new version this week-end
@+

**Comment by Viglino** [comment]
The v2.0.4 is on npm.

**Comment by Abdullah0991** [comment]
Hello @Viglino  again,
Would you please add method to get the selected features array with the Transform interaction?

I think it's so easy ;)
```
ol_interaction_Transform.prototype.getSelection = function() {
	return this.selection_;
}
```

**Comment by Viglino** [comment]
You can allready access the selection when an event is triggered:
transform.on('translatestart', function(e) {
  var selection = e.features;
});

**Comment by Abdullah0991** [comment]
I know this trick! but I want to get the selection array directly from the interaction object if I can.

Thanks @Viglino

**Comment by Viglino** [comment]
Hello,
I've added a getFeatures() function to retrieve the features concerned by the transform.
@+
