### ISSUE TITLE
How to delete the split line between sectors？

### ISSUE THREAD

**Issue by dupeiduo** [Viglino/ol-ext#114]
![image](https://user-images.githubusercontent.com/15188363/40416928-27ba2df6-5eb1-11e8-9325-f50b27a0ab8b.png)

**Comment by Viglino** [comment]
There is a stroke option used to style the lines of the chart. 
Just use a style with a transparent color: 
```javascript
var style = new ol.style.Chart({
  stroke: new ol.style.Stroke({ color: 'rgba(0,0,0,0)', width:0 }),
  ...
});
```

**Comment by dupeiduo** [comment]
@Viglino Thanks.
