### ISSUE TITLE
Trigger are missing for transform interaction

### ISSUE THREAD

**Issue by dixitgoyal** [Viglino/ol-ext#115]
Is there trigger available in transform interaction to control the modification in feature. For example if i want to call some routine after completing transformation of feature, i can't right now.

**Comment by Viglino** [comment]
Interaction fires select | rotatestart | rotating | rotateend | translatestart | translating | translateend | scalestart | scaling | scaleend.
You can use the end events to do something after transformation ends:
````javascript
interaction.on(['rotateend', 'translateend', 'scaleend'], function (e) { 
  console.log(e)
});
````
The event will contains the feature and the original geometry.

**Comment by dixitgoyal** [comment]
Thanks, It's really helpful for me.
