### ISSUE TITLE
how best to use Transform interaction to modify geoimage?

### ISSUE THREAD

**Issue by allandaly** [Viglino/ol-ext#116]
Thank you for this excellent library.

I would like to use your Transform interaction to modify a GeoImage -- to place the image correctly on the map by transforming, rotating, and scaling (both x and y) to get it into the right location.

The Transform interaction is set up to work with features. Can you please suggest the best approach to using the Transform interaction with a GeoImage rather than a feature?

Thanks again for all the work you have put into this very useful library of OL extensions.

-Allan

**Comment by Viglino** [comment]
I think the best way is to create a feature on top of the map with a geometry that reflect the bounding box of the image an trigger events fired by the Transform interaction to reflect the changes on the GeoImage.

But if you're interesting in georefrencing images on a map, you can look at the [Viglino/Map-georeferencer](https://github.com/Viglino/Map-georeferencer) repo. It uses control points to calculate the best transform to use to place an image on the map. You can also clip the image with a polygon.
Then just click on the transform button (φ) to get the parameters for the GeoImage.
That's what I used to georeference the image of the example (just use http://viglino.github.io/ol-ext/examples/data/IGNF_PVA_1-0__1976-03-24_pt.jpg on the [demo page](http://viglino.github.io/Map-georeferencer/)).
The example use French Geoporail layers but you can use any other one as background layer.

**Comment by allandaly** [comment]
Thanks for your reply. I was also thinking of that approach and have given it a try.

The issue that I'm running into now is that I cannot find an easy way to access the geoImage extent in order to get the geometry I need to create a feature on top. If I call 'layer.getSource().getCrop()' on the geoImage layer then it gives me an array like this: [0, 0, 4319, 2904]. These are the pixel dimensions of my image. There is no getGeometry() or getExtent() method on the ol.source.GeoImage object that I can find.

How do I determine the extent of a GeoImage that has been placed on the map? How do the pixel dimensions and [x,y] scale translate into the map coordinates so I can use them with the center to figure out the extent of the image?

Thanks for your help.

-Allan

**Comment by allandaly** [comment]
By the way, your georeferencer is super cool(!), but for my app I need to allow users to add in multiple images and be able to push them around interactively to get them into the right configuration. Your Transform interaction is perfect for what I need to provide.

**Comment by Viglino** [comment]
If you want to get a polygon that fit the image:
````javascript
function getPolygonfromImage(layer) {
  var source = layer.getSource();
  var center = source.getCenter();
  var scale = source.getScale();
  var width = source.getGeoImage().width * scale[0];
  var height = source.getGeoImage().height * scale[1];
  var p1 = [ center[0]-width/2, center[1]-height/2 ];
  var p2 = [ center[0]+width/2, center[1]+height/2 ];
  var extent = ol.extent.boundingExtent([p1,p2]);
  var polygon = ol.geom.Polygon.fromExtent(extent);
  // The resulting polygon
  polygon.rotate(source.getRotation(), center);
  return polygon;
};
````
Then you can translate, rotate or scale the polygon and set the result in the source unsing the setScale, setRotation and setCenter functions.

**Comment by allandaly** [comment]
This was extremely  helpful. Thanks very much. -Allan

**Comment by mpickering** [comment]
The rotation in the code is the wrong way in https://github.com/Viglino/ol-ext/issues/116#issuecomment-391958921

The correct code is below, the only difference is a negative in front of the rotation when the polygon is rotated. 

```
function getPolygonfromImage(layer) {
  var source = layer.getSource();
  var center = source.getCenter();
  var scale = source.getScale();
  var width = source.getGeoImage().width * scale[0];
  var height = source.getGeoImage().height * scale[1];
  var p1 = [ center[0]-width/2, center[1]-height/2 ];
  var p2 = [ center[0]+width/2, center[1]+height/2 ];
  var extent = ol.extent.boundingExtent([p1,p2]);
  var polygon = ol.geom.Polygon.fromExtent(extent);
  // The resulting polygon
  polygon.rotate(-source.getRotation(), center);
  return polygon;
};
``
