### ISSUE TITLE
new ol.interaction.Transform() - Stopped working

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#118]
Hi,

From 4 days ago this stopped working:
new ol.interaction.Transform({});

Error:
Uncaught TypeError: Cannot read property 'getGeometry' of null
    at ol.interaction.Transform.select (ol-ext.min.js:9)

Is there a workaround or a fix comming?

KR,

**Comment by Viglino** [comment]
Hello,
Can you use the ol-ext.js file instead and tell me the line the error occurs?
The [example](http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html) seems still running ().
Thanks,

**Comment by rasa2k** [comment]
Hi Viglino,

Thanks for the quick reply.
Yeah I saw your example too and that still works:

ol-ext.js:9675 Uncaught TypeError: Cannot read property 'getGeometry' of null
    at ol.interaction.Transform.select (ol-ext.js:9675)

**Comment by Viglino** [comment]
Hi 
You can try adding on line 9673 of ol-ext.js
````javascript
if (!feature) return;
````
just after the select definition:
````javascript
ol.interaction.Transform.prototype.select = function(feature, add) {
````
@+
jmv

**Comment by rasa2k** [comment]
Hi again,

I tried adding the if statement after the select definition and that just spawned a new error.
Uncaught ReferenceError: interaction is not defined
    at ol.control.Toggle.onToggle (cbs.main.js:351)
    at ol.control.Toggle.options.handleClick (ol-ext.js:4499)
    at HTMLButtonElement.<anonymous> (ol-ext.js:1266)

**Comment by Viglino** [comment]
The code should look like this (line 9672+):
````javascript
ol.interaction.Transform.prototype.select = function(feature, add) {
//---- Add patch here
    if (!feature) return;
//---- 
    if (add) this.selection_.push(feature);
    ...
````
instead of:
````javascript
ol.interaction.Transform.prototype.select = function(feature, add) {
    if (add) this.selection_.push(feature);
    ...
````

**Comment by Viglino** [comment]
Here is a working example with the patch:
https://codepen.io/viglino/pen/MXYJwR
