### ISSUE TITLE
Set opacity level in LayerSwitcher control onload?

### ISSUE THREAD

**Issue by growe19** [Viglino/ol-ext#121]
In the LayerSwitcher control is it possible to set the opacity of a layer onload so that some layers start at 50% ?

**Comment by Viglino** [comment]
Hello,
The LayerSwitcher reflects the state of the layer itself. Just create your layer with [the opacity](https://openlayers.org/en/latest/apidoc/ol.layer.Layer.html) you want (opacity:0.5 option) or change it after creation ([layer.setOpacity](https://openlayers.org/en/latest/apidoc/ol.layer.Layer.html#setOpacity)(.5)).
@+
