### ISSUE TITLE
Error in DrawHole interaction: Uncaught ReferenceError on 'coord'

### ISSUE THREAD

**Issue by StijnVandermeulen1** [Viglino/ol-ext#122]
When importing the DrawHole interaction as following: 

`import olext_interaction_DrawHole from "ol-ext/interaction/drawhole"`

I receive an error on line 111 in file [ol-ext/src/interaction/DrawHole.js](https://github.com/Viglino/ol-ext/blob/master/src/interaction/DrawHole.js): 

```
coord = e.feature.getGeometry().getCoordinates()[0][0];
Uncaught ReferenceError: coord is not defined
```
I suggest to add `var` before the variable: `coord`.

**Comment by Viglino** [comment]
Thanks for the feedback

**Comment by Viglino** [comment]
Done in the last commit 😄

**Comment by StijnVandermeulen1** [comment]
Hi, do you know when this will be released? (npm) Multiple people are working with this and we still need to fix it manually 😄.
