### ISSUE TITLE
Transform interaction example possibly broken

### ISSUE THREAD

**Issue by bong0** [Viglino/ol-ext#124]
Transform interaction example seems to be broken:

See https://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html

![image](https://user-images.githubusercontent.com/179111/41784156-21d5ae88-763f-11e8-8e01-3a78b8ba990a.png)

but I couldn't spot the error right away...

**Comment by Viglino** [comment]
Yes the master full build (ol.js) seems to be buggy.
You have to move to latest build : https://openlayers.org/en/master/build/ol.js > https://openlayers.org/en/latest/build/ol.js
I'll try to change it asap...

**Comment by bong0** [comment]
Ah okay, sorry for bugging you. Meanwhile this pen should do it for testing: https://codepen.io/anon/pen/jKxRJV

**Comment by Viglino** [comment]
Examples are now running well !
Thanks for the feedback!
