### ISSUE TITLE
Split interaction and Polygons

### ISSUE THREAD

**Issue by AleMScof** [Viglino/ol-ext#125]
Hi Jean,

it's a pleasure for me to write you for the first time, i'd like to thank you for this repo. It's been  a very source of inspiration to me since a long.

I've noticed using Split interaction that if it's actived and meanwhile, on the used vector, there's some Polygon Geometry hovering on them generates ton of errors due to method "getNearestCoord" at the actual line 9367.

Here's attached a screen of it.
![code](https://user-images.githubusercontent.com/29773796/41804463-4c04d9a6-7697-11e8-9c8e-4eab6c8eabff.png)

Keep going,
thanks

A.

**Comment by Viglino** [comment]
Yes! the split interaction is not intended to be used with polygons.
There was a typo. Now  it's running without error (test if the geometry is a LineString).
Thanks for the feedback.
@+

**Comment by AleMScof** [comment]
Thanks,
working fine.
A.
