### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by martinmcneela** [Viglino/ol-ext#134]
I have just been checking the demo site and get console errors. See this for example: http://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html

`Uncaught TypeError: ol.Attribution is not a constructor
    at map.control.overlay.menu.html:132`

**Comment by Viglino** [comment]
Yes the latest ol release (v5) has broken some example.
The lib is still working using v4.6.5.
I'm working on corrections...

**Comment by emcastro** [comment]
An other kinf of error for some cluster related demos:
http://viglino.github.io/ol-ext/examples/geom/map.cluster.convexhull.html
http://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html

ol-ext.js:11544 Uncaught TypeError: Cannot read property 'clear' of undefined

**Comment by Viglino** [comment]
Demo are working again 😄
