### ISSUE TITLE
FYI: ol.Sphere is not a constructor

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#135]
http://viglino.github.io/ol-ext/examples/control/map.control.profil.html is broken as you properly know :)

**Comment by Viglino** [comment]
Yes ol.Sphere is no more available in ol5...
Have to be fixed

**Comment by Viglino** [comment]
The fix will be done in the next version (yet the ol-5 branch) as it will introduce breaking changes with the ol4.
The example is running with ol v4.6.5

**Comment by Viglino** [comment]
Done in the last commit. Available on npm ol-ext@3.0.0
