### ISSUE TITLE
Photo style with transparent images

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#137]
Hi @Viglino 

When use ol_style_Photo with 'png' images which have transparent background, it shows the images with black background like this photo:

Example: https://drive.google.com/open?id=19sa9wDyOkPzkrgFV3Ruu6ZzsBpKE4v94
Original photo: https://safoodbank.org/wp-content/uploads/2015/02/Apple-Map-Marker-e1485900448506.png

Is this a bug or normal behaviour?

**Comment by Viglino** [comment]
Hello,
The Photo style is more to use with photo (jpeg) and the background is fixed to black (choose an Icon style instead).
I'll try to add a new option to choose the background color ASAP, thus you'll could choose a transparent background.
@+
