### ISSUE TITLE
Feature Request: Transform interaction with points which have icon style

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#138]
HI @Viglino 

Using the transform interaction on non point geometries allow you to scale, stretch ... the geometry.

But in case the point geometry has icon style, can you make the transform interaction allow me to scale,stretch and rotate the icon of the point feature?

Something like [this](https://drive.google.com/open?id=1UWI5RIXSEiz8u2znEmPTyxxi4tMMYxlu)

It will be a great feature.

**Comment by Viglino** [comment]
Hi,
The problem with image style is that there is no real API to get the feature size/position. The style can be an array of images and anchor positions have to be taken into account to get the extent of the drawing.
I'll try to see what could be possible after we moved ol-ext to the last ol5 version.
@+

**Comment by Maroben** [comment]
Hi @Viglino ,

Is there an update on this feature or a known workaround?

Regards,
Maroben

**Comment by Viglino** [comment]
The tool only stretch geometry and the size of the point is a symbolization attribute...
So no fix yet...

**Comment by phxgbl** [comment]
hi .. any updates ?

**Comment by Viglino** [comment]
I've pushed a new commit that let's you handle scale on points.
You have to set a `pointRadius` function when creating the Transform interaction and listen to the `scaling` event to set the point radius.
See example: https://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html

**Comment by phxgbl** [comment]
@Viglino Thank you.
