### ISSUE TITLE
Ol5 and LayerSwitcher?

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#139]
Hi,

I'm running OL5 v. 5.0.2 and OL-EXT v.2.0.5

I know there have been some breaking changes with ol5 but looking at the example/demo page the LayerSwitcher seems to be working on lastet.ol.build.js which looks like ^ol5.

When I try to init layerSwitcher I get a "Cannot read property 'getView' of undefined at Map.ol_control_LayerSwitcher.viewChange"".

When I run the same code on OL v.4.6.5 every works again. 
When I run the same code again, but this time on the OL5 branch I get some Ol.Inherits issue.

What am I missing?

**Comment by Viglino** [comment]
Hi,
Ol-ext is not yet ready to use with the last ol5 modules.
Deprecated functions have been removed and the last build (except the [profile control](http://viglino.github.io/ol-ext/examples/control/map.control.profil.html)) runs with ol5 classes but changes on the ol5 modules have not yet been taken into account (see #123).
The `ol5-migration` branch is under construction and you can test it.
Thanks for your feedback.

**Comment by darkscript** [comment]
@rasa2k meantime you can use the ol5-migration branch as npm module, in your package.json, ``"ol-ext": "git+https://github.com/Viglino/ol-ext.git#ol5-migration",`` . Most of the changes are done but still few fixes to be done (**Note: the dist folder of ol5-migration is out of date, I assume you are using node modules**)

**Comment by rasa2k** [comment]
@darkscript I was actually trying to do that, but I keep getting this message: 

> ol-ext@2.1.0 prepack C:\Users\Me\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-b4cc670e
> gulp prepublish

module.js:540
    throw err;
    ^
package.json Non-registry package missing package.json: ol-ext@git+https://github.com/Viglino/ol-ext.git#ol5-migration.

**Comment by darkscript** [comment]
@rasa2k try clearing npm cache with ``npm cache clean --force``  if that doesnt work try manually clearing caching directory for npm, i think the issue is due to conflict in caching or something of the sort

**Comment by Viglino** [comment]
[test](url)

`toto```
**toto**

- 1
- 2
- 5

**Comment by rasa2k** [comment]
@darkscript Thanks for the help. Unfortunately it did'nt solve my problem. I tried the npm cache clean and manually deleting. I even tried it on another PC, but with the same outcome. :/ Do I need to have Bash or something like that installed.

**Comment by rasa2k** [comment]
Got it working but I had to add this to my package.json.
"devDependencies": {
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-clean": "^0.4.0",
    "gulp-concat": "^2.6.0",
    "gulp-cssmin": "^0.2.0",
    "gulp-header": "^1.8.8",
    "gulp-minify": "^2.1.0",
    "gulp-watch": "^5.0.0",
    "minimist": "^1.2.0",
    "plugin-error": "^1.0.1",
    "through2": "^2.0.3"
  },
"dependencies": {
    "ol": "^5.0.2",
    "ol-ext": "git+https://github.com/Viglino/ol-ext.git#ol5-migration",
}

**Comment by darkscript** [comment]
@rasa2k a little patience, we will soon have the npm version updated.

**Comment by rasa2k** [comment]
Don't know what happend but this stopped working since 3 days ago.
"ol-ext": "git+https://github.com/Viglino/ol-ext.git#ol5-migration"

Now I get the master branch and not the ol5-migration.

**Comment by Viglino** [comment]
The branch has merged to master.
Master will be more up to date.

**Comment by rasa2k** [comment]
Omg how did I miss that. :( Sorry
