### ISSUE TITLE
Show/hide ol.style.Photo

### ISSUE THREAD

**Issue by domenmali** [Viglino/ol-ext#140]
hi,

I'm using ol.style.Photo and I've noticed that when the feature is set as 'hidden' and back to 'visible', the image is not visible.

**Comment by Viglino** [comment]
Hello,
How to you hide a feature?

**Comment by domenmali** [comment]
hi,

I do it like this:

`feature.setStyle(new ol.style.Style({}))`

**Comment by Viglino** [comment]
It seems to run for me: https://codepen.io/viglino/pen/PBwOeo

**Comment by domenmali** [comment]
Hi,

sorry for my late response...

I've changed the code a little bit (https://codepen.io/anon/pen/YjXzad). Interesting is that is working....

maybe my problem is somewhere else.

thank you for your time.

Kind regards,

Domen
