### ISSUE TITLE
Error in DrawHole interaction: Cannot read property 'MultiPolygon' of undefined

### ISSUE THREAD

**Issue by StijnVandermeulen1** [Viglino/ol-ext#141]
Hello again!

When importing the DrawHole interaction as following:

import olext_interaction_DrawHole from "ol-ext/interaction/drawhole"

I receive an error on line 167 in file [ol-ext/src/interaction/DrawHole.js](https://github.com/Viglino/ol-ext/blob/master/src/interaction/DrawHole.js):
`var newGeom = new ol.geom.MultiPolygon();`
This should be imported at the start of the file by using the code:
`import ol_geom_MultiPolygon from 'ol/geom/multipolygon'`
Then line 167 should be changed to:
`var newGeom = new ol_geom_MultiPolygon();`

Would it be possible to change this?

Kind regards!

**Comment by Viglino** [comment]
You're right!
I'll try to fix it ASAP!

**Comment by Viglino** [comment]
Done in the last commit. Available on npm ol-ext@3.0.0

**Comment by StijnVandermeulen1** [comment]
Great, Thanks!
