### ISSUE TITLE
split interaction with measure

### ISSUE THREAD

**Issue by am2222** [Viglino/ol-ext#143]
Hi,
I wanted to check the possibility of having the measure while we want to use split interaction. for instance, I want to find out if there is any method to find distance over the line which we try to split. It seems if we can manage to find the nearest point to the mouse and calculate its distance to current mouse location we can achieve it. is it possible?

**Comment by am2222** [comment]
@Viglino  can't we calculate the distance from pixel coordinate into metric system? About the secound method can you please give me some hints?maybe I can add add it

**Comment by Viglino** [comment]
Hello,
In the last commit, I've added a new event to handle `pointermove`. You can access the `linkGeometry` (geometry from the cursor to the selected object) to calculate its length:
````javascript
interactions.split.on('pointermove', function(e) {
  if (e.linkGeometry) {
    // using ol < v5.0.0
    var geom = e.linkGeometry.clone().transform(map.getView().getProjection(), 'EPSG:4326');
    var d = ol.sphere.WGS84.haversineDistance(geom[0],geom[1]); 
    // using ol >= v5.0.0
    var d = ol.sphere.getLength(e.linkGeometry); 
    // do somthing with the dist.
   console.log(d);
  }
});
````
@+
