### ISSUE TITLE
How to use pictures in animation？

### ISSUE THREAD

**Issue by ALein** [Viglino/ol-ext#144]
in ol.featureAnimation.Path，the feature style is used in this way：
var style = 
	[	new ol.style.Style(
			{	image: new ol.style.Shadow(
				{	radius: 15,
				}),
				stroke: new ol.style.Stroke(
				{	color: [0,0,0,0.3],
					width: 2
				}),
				fill: new ol.style.Fill(
					{	color: [0,0,0,0.3]
					}),
				zIndex: -1
			}),
		new ol.style.Style(
			{	image: new ol.style.RegularShape(
				{	radius: 10,
					radius2: 5,
					points: 5,
					fill: new ol.style.Fill({ color: 'blue' })
				}),
			stroke: new ol.style.Stroke(
				{	color: [0,0,255],
					width: 2
				}),
			fill: new ol.style.Fill(
				{	color: [0,0,255,0.3]
				})
			})
	];
I changed to style for pictures，like this:
const  style = new ol.style.Style({
      image: new ol.style.Icon({
        src: url
      })
    })
But the picture can not be displayed. Why is this? thank you !

**Comment by Viglino** [comment]
Hello,
When you use an image with a `src` the image is not loaded and can't be drawn. 
Thus you have to load the image before and pass it to the constructor using the `img` option.
You can also force the image to load using the load method:
````javascript
const iconStyle= new ol.style.Icon({
  src: url
});
iconStyle.load();
const style = new ol.style.Style({
  image: iconStyle
});
````
@+
