### ISSUE TITLE
Selection fails when polygon translated into wrapped map space

### ISSUE THREAD

**Issue by mepiazza** [Viglino/ol-ext#146]
Many months ago I found your ol.transform.interaction demo which seemed to provide the exact functionality I needed to implement.  I used your demo as the foundation of highly interactive Area of Interest selection and manipulation application.  I have worked through a large number of issues and have the application working pretty solidly but I have now run into a brick wall with regards to a couple of items.  The polygon (feature) selection mechanism fails to work when the polygon is translated across the Dateline in either direction onto the wrapped map.   If the translated polygon happens to end up across the Dateline the portion of the polygon still in the original map space is selectable but the cursor hover change fails when over the portion of the polygon in the wrapped map space.

I finally decided to go back and retry your Transform Interaction demo (map.interaction.transform.html) to see if it exhibited the same behaviour as it is the basis for my application and as can be seen in the following attached screen captures, your demo exhibits the same behaviour.  I'm not sure where the problem is but since you have have provided this really useful library which clearly shows you have considerably more familiarity with OpenLayers than I do I am hoping you can help me narrow down the potential cause.  I can find nothing obvious that would limit the scope of the feature selection to just the original map instance but I am only really just starting to dig into ol.js file in depth to try and understand what is going on.

I am using two projections in my app.  I am using EPSG:4326 projection as my base map from a WMS Geoserver.  I use this as I need to deal in LON/LAT coordinate space and I am also using EPSG:3395 which I use to obtain meter coordinates as I have a need to calculate the actual selected area in square kilometres.  That is requiring me to include the proj4.js library as well in order to do the conversions.  I am also limiting my ol.js to the 4.6.5 version.  

But all that is irrelevant because your demo exhibits the same problem but contains none of that extra libraries and functionality I have added to my application.  So that means that there is something in OpenLayers or possibly in your ol3-ext library that is limiting the feature select capability.

I am hoping you can provide some enlightenment.  Thank you.

Mike Piazza

![image](https://user-images.githubusercontent.com/18179033/43812603-903f7f8e-9ab1-11e8-9c8e-b288eee40412.png)

![image](https://user-images.githubusercontent.com/18179033/43812612-9f88612c-9ab1-11e8-9361-c0da79a69e29.png)

**Comment by Viglino** [comment]
That's an issue. Reading the ol/source/Vector documentation it says:
> wrapX: `boolean` Wrap the world horizontally. For vector editing across the -180° and 180° meridians to work properly, this should be set to false. The resulting geometry coordinates will then exceed the world bounds.

The `wrapX` options of the overlay layer of the control should be set to `false`.
You can test if it runs for you adding `wrapX` to false in the constructor:
````javascript
this.overlayLayer_ = new ol_layer_Vector({
    source: new ol_source_Vector({
      features: this.handles_,
      useSpatialIndex: false,
     /* add wrapX to false */
      wrapX: false 
    }),
    name:'Transform overlay',
    displayInLayerSwitcher: false,
    // Return the style according to the handle type
    style: function (feature) {
      return (self.style[(feature.get('handle')||'default')+(feature.get('constraint')||'')+(feature.get('option')||'')]);
    }
});
````

**Comment by mepiazza** [comment]
Hi Jean-Marc,

Thank you for the very quick response.

I had only found a reference to wrapX for the base layer and that was by
accident.  In that regard if I change the baselayer wrapX to false I only
get one instance of the map with the EPSG:4326 projection.  I was
completely unaware that the wrapX would work for other layers as well until
your note above. Now after fighting with a self-induced system problem this
morning I finally managed to add your changes to my code and test it.

Good news and bad news.  The good news is that, due to this change, the
polygon is now selectable when translated past the Dateline as the hover
cursor shows over the whole polygon.  The selection handles all show up.
The bad news, however, is that only the handles on the polygon that remain
in the "main" world instance cause the cursor to change to indicate the
available functionality.   e.g. The cursor doesn't change from the hover
selection cursor to the stretch cursor or translate cursor or the stretch
with aspect ratio cursors.  I've disabled the rotation for this
application.  They only change on the section of the polygon still
remaining in the main world instance.  That was an unexpected
complication.  There must be another sub-hover mechanism, for lack of a
better term, that causes the hover cursor to change to its specific
function.  Is there another hidden layer used in your code for those extra
cursors?  I had thought they were all handled in your style definitions as
shown in the demo.

Thank you.

Regards,

Mike Piazza

**Comment by Viglino** [comment]
Hi,
The issue is also in the lib itself.  
In the overlay layer that contains the sketch (the handles) of the transform interaction, `wrapX` is missing and the selection handles are not selectable outside the "main" world instance. You have to add `wrapX` to true in the code for this layer in the lib (overlayLayer_) to make it work.

You can test it in setting wrapX in the source overlay of your interaction like this:
````javascript
myTransformInteraction.overlayLayer_.getSource().wrapX_ = false
````
I'll try to fix it in the lib ASAP.
@+

**Comment by mepiazza** [comment]
Hi Jean-Marc,

Whooo Hooo!  I located the structure in the library and added the wrapX and
it works like a champ.  Thank you.  I have attached a screen capture of the
form I am working on.  It shows the DragBox generated rectangle selected
but not the cursors.  We have tested it and they are working correctly.
This application form is an Area of Interest selection form that feeds
various weather prediction models based on the AOI size and the resolution
selected.  The polygon is in Red because it is exceeding the allowable size
for a 5 Km resolution model and your transformation library is used to
allow the user to manually resize the AOI rectangle to get it within
selected resolution limits where it will turn blue and the Submit button
will be enabled.

Currently the value shown next to the Selected Area: label is wrong.  It is
due to the fact that the underlying LAT/LON coordinates in the EPSG:4326
projection are not wrapping but continue to increase and decrease beyond
the normal -180 to 180 limits.  It was working when my main projection was
meter based as it wrapped correctly but I have had to change over to
working with a LAT/LON based projection and convert LAT/LON to meters where
needed.

This is a complete rewrite of the previous version as it was OpenLayers 2
based and had no interaction and no validation capability.  The users would
just enter coordinates to plot the rectangle and then submit the form.
Most of the time the modelers would have to send it back because the
request was too big for the requested resolution.  This wasted days in the
turnaround.  Now the users cannot submit the form unless it meets the
specifications and they have the tools to massage their selection to get it
within spec.

Thanks again and please let me know when you have distributed the update as
I want an 'official' version to be put under source control for this
application.

Regards,

Mike Piazza

**Comment by mepiazza** [comment]
Hi Jean-Marc,

I have been away from this specific problem for awhile as I had implemented
and tested your change and it was working.  I then got stuck into another
issue coming up with an algorithm to calculate the area of polygon that
gets moved over the International Date Line using your translation method
or gets initially drawn over the IDL as the result of a DragBox action by
the User.  I got that area calculation implemented and tested only to
suddenly find that this problem has reared its head again.

We just recently had a problem with the server I've been testing on so I
thought maybe an System Admin had overwritten the modified library with an
earlier backup copy but that is not the case.  I have verified that the
library I am using has the required change in it.  So I reached back to
look at our email conversation and I find myself a little confused.
Looking at the email it seems that there are two places that require the
WrapX fix but the library I've been using up until now, modified with your
suggestion, only has one additional WrapX statement in it.  I commented out
the line that includes the modified library and referenced your online
library and I still have the same issue.

Is there supposed to be a second place to add the WrapX parameter or are
both above statements you replied to me referencing the same section of
code?  I never did find your above referenced " lib (overlayLayer_) "
section except as shown in the first of your replies above.  I've looked
thru all the source online and I cannot find an overLayer library, just the
overlayLayer_ shown in the code snippet above.

In addition, It seems you have heavily modified your libraries to
accommodate version 5+ of OpenLayers.  We have to stay with 4.5.6 so all
the modifications you've made to support 5 are looking like Greek to me.

I am updating the coordinate values and the area dynamically in real-time
as the user moves or resizes the polygon.  I am also validating the size of
the polygon against the max size of the selected resolution to initiate or
maintain a style change in the color of the polygon outline and to do that
I delete the old polygon and create a new one in its place.  I have not
changed any of that functionality and it was working fine no matter which
map iteration the polygon was on after implementing your suggested fix
above.  Now, however, the original problem has come back and I am at a bit
of a loss as to what happened.

Would you maybe have any suggestions and is there another library I should
have implemented wrapx in as well?

Thank you.

Mike Piazza
