### ISSUE TITLE
LayerSwitcher: hidden layers 

### ISSUE THREAD

**Issue by computerchemist** [Viglino/ol-ext#147]
Hidden layers which are hidden - "greyed out" - with maxResolution are un-hidden when any mouse interaction takes place within the layer switcher, e.g. ticking a box of a non-hidden or hidden layer.
The layer switcher is only refreshed correctly on a pan or zoom change. 
I have put a hack in place by adding "this.viewchange();" to the last line of ol.control.LayerSwitcher.prototype.drawPanel_ which forces a redraw after interaction ensuring hidden group layers stay hidden, however I am sure there is a more elegant way of solving this.
Using ol-ext 3.0.0 with ol4.6.5 on firefox. 

You can replicate this effect when "pirate map" is hidden on the demo - https://viglino.github.io/ol-ext/examples/control/map.switcher.html - just click anywhere else on another item and "pirate map" is suddenly un-hidden, until a pan or zoom.

**Comment by Viglino** [comment]
Integrated in the v3.0.1 npm version
