### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by dramoturg** [Viglino/ol-ext#151]
Hi. Why need  jQuery dependency? May be worth removing it from the dependencies. All operations with dom can make with use vanilla js. What kind of browser support need?

**Comment by Viglino** [comment]
It could but I've used it for convenience first and it'll takes some time to remove it...

**Comment by dramoturg** [comment]
Thanks for info. I'll try to do this.  wait pull request.

**Comment by darkscript** [comment]
@dramoturg that would be great

**Comment by dramoturg** [comment]
What IE version supported?

**Comment by Viglino** [comment]
OL is intended to run on all modern browser and IE down to version 9 using polyfills (https://openlayers.org/en/latest/doc/tutorials/background.html). This polyfilsl includes `Element.prototype.classList`.:smiley:

**Comment by dramoturg** [comment]
IE down to version 9. seriously? 2018 on the street. )

**Comment by RalphLAtGitHub** [comment]
For example: IE9 compatibility is necessary to add a web browser functionality to a WinForms application via the .NET WebBrowser Class. Unfortunately, nothing has changed until today.

**Comment by dramoturg** [comment]
it's very sad ((

**Comment by Viglino** [comment]
Me too...

**Comment by cplasse** [comment]
Hi. I have this error when creating a button in an Anglar 6.1.0 project : 
ERROR ReferenceError: $ is not defined
    at new ol_control_Button (webpack-internal:///./node_modules/ol-ext/control/Button.js:22)

I am using JQuery in some type script files without problems but I put an instruction "import * as $ from 'jquery' in each file. Should this be added in ol-ext files using jQuery ?

**Comment by ThomasG77** [comment]
There are two types of dependencies:
* in the library itself for each components
* in the examples for the UI.

The list of examples using `$` is listed at https://gist.github.com/ThomasG77/740f90f2912b915c93b0c9a1c1597d71 (obtained through `ack-grep -rl --html "\$" examples/`)
I plan to remove jQuery dependency from the examples then go back to the library components. I will do some PRs for this intent.

**Comment by Viglino** [comment]
Hello,
Great job! with the pull request #186 #185 #184 !
I don't mind the dependencies with the example: it's just examples. In many cases the jQuery syntax is more readable.
I'd rather plane to add examples with [parcel-bundler](https://github.com/Viglino/ol-ext-parcel-bundler)  or [webpack](https://github.com/darkscript/ol-ol-ext-webpack-example).
@+

**Comment by ThomasG77** [comment]
Done a bunch of PRs.
FIY, I mainly figure out the change to apply using https://github.com/nefe/You-Dont-Need-jQuery
It could help if you need at a moment to dive more into jQuery removal

**Comment by ThomasG77** [comment]
State of the jQuery removal in core library using `ack-grep -rl --js "\\$\(" src/` is the following

- [x] `src/source/Delaunay.js` (OK because $ from jQuery commented) 
- [ ] `src/control/LayerPopup.js` (in progress but stuck due to issue on `src/control/LayerSwitcher.js`)
- [ ] `src/control/LayerSwitcher.js` (in progress but stuck due event management for opacity and dragging. Work in progress at https://github.com/webgeodatavore/ol-ext/tree/debug-layer-switcher-no-jquery
- [ ] `src/control/LayerSwitcherImage.js` (nothing done at the moment)

@Viglino Advice on `ol.control.LayerSwitcher` to tackle the change from `$(document).on("mouseup touchend mousemove touchmove touchcancel", drag, drag.self.dragOpacity_);` to a pure JavaScript `document.addEventListener(` would help. The use of `e.data` specific to jQuery bites me at the moment.

**Comment by Viglino** [comment]
ol.control.LayerSwitcher is the most comple x feature with the drag and drop in the layer list.

**Comment by ThomasG77** [comment]
@Viglino I didn't work since around 2 weeks on the LayerSwitcher.
It works except for the drag and drop part where it fails. I need to take some time to debug why the jQuery migration failed for this part of the code.

**Comment by Viglino** [comment]
@ThomasG77 Hello,
I've got some times to spend on this issue and I'll try to remove the last dependencies on the LayerSitchers asap...

**Comment by ThomasG77** [comment]
Sorry, I was too busy since november. Feel free to work on it as I'm not sure I will have enough time for Christmas.

**Comment by Viglino** [comment]
I've just removed the last jQuery dependencies 🎁
Thanks to @ThomasG77 PRs the library is now free from jQuery 🎅

**Comment by Lory1990** [comment]
Hi! I installed via NPM the 3.0.3 version and there is still a JQuery dependency on the layers switcher, have you published a newer version? Or, if not, when you will release the JQuery free version?

**Comment by Viglino** [comment]
jQuery dependencies will be removed in the 3.1.
I'll try to publish this week-end after removing a bug on the search tools.
@+

**Comment by Viglino** [comment]
Bye bye jQuery! The v3.1.0 is out on npm...

**Comment by Lory1990** [comment]
Thank you so much @Viglino, now component is JQuery free!
