### ISSUE TITLE
problems with "ol.featureAnimation.Path"

### ISSUE THREAD

**Issue by ALein** [Viglino/ol-ext#152]
Hi!
My map coordinate system is 'EPSG:4326'。The animation will not be executed, but it will not be wrong. How do I solve this problem? Thank you!!!

**Comment by Viglino** [comment]
Do you have an example (jsfiddle, codepen) to see what's wrong?

**Comment by ALein** [comment]
sorry,no examples are available for the time being. I only used "EPSG:4326" when creatiing maps,like this:
`this.map = new ol.Map({
      target: 'map',
      view: new ol.View({
        projection:ol.proj.get('EPSG:4326'),
        center: [x,y],
        zoom: 8,
        minZoom: 2
      })
    });`

**Comment by sign0** [comment]
I think it's a projection problem.
Setting the view in projection EPSG: 3857 + convert your coordinates with ol.proj.fromLonLat(), and your code works well : [https://codepen.io/sign0/pen/zJKwaV](https://codepen.io/sign0/pen/zJKwaV)

**Comment by sign0** [comment]
It's strange, but in fact it works in EPSG:4326...
In this case, the time scale (speed option) change : [https://codepen.io/sign0/pen/MqjvWj](https://codepen.io/sign0/pen/MqjvWj)

**Comment by Viglino** [comment]
The bug is in your image: http://img4.imgtn.bdimg.com/it/u=2659519208,2040552462&fm=27&gp=0.jpg return a 403 Forbidden @sign0 example use an other image.

**Comment by Viglino** [comment]
+ the speed parameters is in map unit (degrees) the speed=30 means very fast.
