### ISSUE TITLE
Icon fonts

### ISSUE THREAD

**Issue by am2222** [Viglino/ol-ext#153]
Hi,
Is there any limitations while we want to update fontawsome version 4.7.1 to the last version?I checked and it does not show any icons.

**Comment by Viglino** [comment]
Hi,
FontSymbol styles seem to work properly with FontAwesome v5.2: see https://codepen.io/viglino/pen/QVNpzm

Be sure to include the font definitions: 
````html
<script type="text/javascript" src="//cdn.rawgit.com/Viglino/ol-ext/master/dist/extra/FontAwesomeDef.js"></script>
````
In case you're using a different package, you'll have to specify the font name in the fontdef (the default is FontAwesome):
````javascript
ol.style.FontSymbol.prototype.defs.fonts.FontAwesome.font = "Font Awesome 5 Free";
````

NB: some new symbols may not be defined in the fontdefs and you'll have to add them:
````javascript
ol.style.FontSymbol.prototype.defs.glyphs['newGlyphName'] = new_code;
````
ie.
````javascript
ol.style.FontSymbol.prototype.defs.glyphs['fa-wheelchair'] = "\uf193";
````

**Comment by am2222** [comment]
@Viglino thanks very much, when I tried your example it does not show the icon and it only shows a blue rectangular (same as what happened to my code)

**Comment by jcachat** [comment]
Had the same issue and could not find a way to make Font Awesome 5/OpenLayers 5.2 work with FontSymbol.  But finally got it to work using a regular Text style like this:
```
            style: new ol.style.Style({
                text: new ol.style.Text({
                    text: '\uf3c5',     //  fa-map-marker-alt
                    font: '900 24px "Font Awesome 5 Free"',
                    textBaseline: 'bottom',
                    fill: new ol.style.Fill({
                        color: 'red',
                    })
                })
            })
```

The key here is that you must specify the font weight and you must quote the font name.  I suspect if FontSymbol did this when drawing the marker, it would work too.  (along with fixing the font name as described in a previous comment).

**Comment by am2222** [comment]
@jcachat you did not used the ol-ext fontstyle ?can you please share an example of your result?

**Comment by Viglino** [comment]
The font weight is not used with FontSymbol style. This could be added to make it run.
Do you have a working example to see what kind of font is used and why it doesn't runs?

**Comment by jcachat** [comment]
> @jcachat you did not used the ol-ext fontstyle ?can you please share an example of your result?

No, I ended up not using the ol-ext library because I could not get it to work at all - due to what I shared above.  I got the same default "square" icon you did.  The result is that it correctly shows the font awesome icon on the map.  It does not include the extra styling that ol-ext FontSymbol does, but it does at least show the font awesome icon.



> The font weight is not used with FontSymbol style. This could be added to make it run.
> Do you have a working example to see what kind of font is used and why it doesn't runs?

I don't have a "working" example - I could not get it to show anything other than the default square as shown in a comment above by am2222.  The only way I could get OpenLayers itself (directly) to show the font awesome icon was as I described.

**Comment by Viglino** [comment]
@jcachat thanks for your help.

**Comment by Viglino** [comment]
I've added a style parameter to the FontSymbol  style to reflect the font weight.

**Comment by am2222** [comment]
@Viglino Thanks very much

**Comment by abmohajeri** [comment]
hi
Do this ways to achieve this goal:
1- remove all spaces from font face names: e.g. Font Awesome 5 Pro -> FontAwesome5Pro
2- add this lines at the end of your all.min.css
`.fa,.fal,.far,.fas{font-family:FontAwesome5Pro !important;font-weight:normal !important;}.fab{font-family:FontAwesome5Brands !important;font-weight:normal !important;}.fad{font-family:FontAwesome5Duotone !important;font-weight:normal !important;}`
3- add this lins tinside of your codes: e.g.
`FontSymbol.addDefs(
    {
      "font": "FontAwesome5Duotone",
      "prefix": "fad"
    },
    {
      "fa-bells": "\uf77f"
    }
);`

this works for me, Hope you enjoy

**Comment by jeromeBor** [comment]
Review from all of this comments, I succeed making this all works by mixing text and image from FonySymbol : 
```
   image: new ol.style.FontSymbol({
        form: 'marker',
        offsetY: 3,
        radius: 25,
        fill: new ol.style.Fill({
          color: 'white'
        }),
        stroke: new ol.style.Stroke({
          color: 'orange',
          width: 2
        })
      }),
      text: new ol.style.Text({
        text: '\uF0D1',
        font: '900 22px "Font Awesome 5 Free"',
        // textBaseline: 'bottom',
        fill: new ol.style.Fill({
          color: 'orange'
        })
      })
```
I had hard times figuring out how to make this works, so I'm sharing my "solution", hope it helps.
Thanks you all.
