### ISSUE TITLE
Problem untoggle ol.control.Bar

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#157]
There is a problem with the "untoggle" of the control buttons.

Taken the example from:

https://viglino.github.io/ol-ext/examples/bar/map.control.subbar.html

1) Click on "0" - Sub menu is displayed with "1" checked
2) Now uncheck "1" - This creates a "Maximum call stack size exceeded" exception

There is also the problem where, when "toggleOne is true" or "autoActivate is true".  
The onToggle function only fires on the button that was clicked and not on other buttons that are toggled in code (when used with toggleOne is true or autoActivate is true)

**Comment by Viglino** [comment]
The last commit fix the bug!
