### ISSUE TITLE
No Animations

### ISSUE THREAD

**Issue by nathanashton** [Viglino/ol-ext#158]
I'm using ol-ext inside of an Angular application with OpenLayers Version 5.2.0. 

I am using the SelectCluster interaction and the AnimatedCluster similar to the Clustering example. Everything works fine but no animation is shown for either.  In the case of the SelectCluster the icons disappear and reappear at their end position. There is no animation in between.

The AnimatedCluster is the same. The icons flash for a second as if they will animate but they just reappear when the animation would have finished.

I have an example running at http://livestockmap.azurewebsites.net/

**Comment by Viglino** [comment]
What is the code for the style function?
Can you test it with the code in the example (http://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html).
I think the style is not rendered correctly.

@+

**Comment by nathanashton** [comment]
Will give it a try. 

This is the style for the AnimatedClusted:
`public ClusteredStyle(feature?: Feature): Style {
    let size = 0;
    if (feature) {
      const features = feature.get('features');
      for (const f of features) {
        size += +f.getStyle().getText().getText();
      }
    }

    return new Style({
      image: new CircleStyle({
        radius: 21,
        fill: new Fill({
          color: 'white'
        }),
        stroke: new Stroke({
          color: 'black',
          width: 3
        })
      }),
      text: this.headCountLabels(size)
    });
  }`

**Comment by Viglino** [comment]
I meant the style function that is passed the layer (or the SelectCluster interaction).
In your example, when drawing the cluster the number is not displayed in the circle. This means that the cluster (and its size) is not passed to the style?

**Comment by nathanashton** [comment]
Thanks. The circles are created using the style function below. I hope that is what you mean.

` public CowStyle(headCount?: number): Style {
    return new Style({
      image: new Icon({
        anchor: [0.5, 0.5],
        anchorXUnits: 'fraction',
        anchorYUnits: 'fraction',
        src: '/assets/cow.svg',
        scale: 0.65
      }),
      text: this.headCountLabels(headCount)
    });
  }`

These features are then added to the cluster layer.

**Comment by Viglino** [comment]
When creating the cluster layer you have to set a style function. 
Something like:
````javascript
const clusterLayer = new AnimatedCluster({ 
  name: 'Cluster',
  source: clusterSource,
  animationDuration: $("#animatecluster").prop('checked') ? 700:0,
  // Cluster style
  style: getStyle
});
````
where `getStyle()` is a function that return a style according to the cluster feature:
````javascript
function getStyle (cluster, resolution){
  const size = cluster.get('features').length;
  let style;
  if (size===1) {
    // get the style for the feature in the cluster
    const feature = cluster.get('features')[0];
    style = featureStyle(feature);
  } else {
   // Get the style for the cluster
    style = clusterStyle(size);
  }
  return [style];
}
````

**Comment by nathanashton** [comment]
Great, that works. Thanks for your help and a fantastic library!
