### ISSUE TITLE
Uncaught ReferenceError: ol_proj is not defined

### ISSUE THREAD

**Issue by ClemRz** [Viglino/ol-ext#159]
The graticule control is awesome! I'd like to implement it in the refactoring of one of my projects.

I'm facing an issue though. I'm using `browserify` to bundle up, and I obtained your code from `npm`:
`Uncaught ReferenceError: ol_proj is not defined
    at ol_control_Graticule.drawGraticule_ (map.bundle.js:1163)`
(the usage is actually in `Graticule.js:149`)

The way I import the module is like so:
`import Graticule from 'ol-ext/control/Graticule';`
Maybe I missed something?

Thanks!

**Comment by ClemRz** [comment]
I could fix it adding this import:
`import {get as ol_proj_get} from 'ol/proj.js';`

and changing `ol_proj.get(` with `ol_proj_get(`

**Comment by Viglino** [comment]
Add it in the last commit!
