### ISSUE TITLE
Example for featureAnimation with Webpack?

### ISSUE THREAD

**Issue by feketegy** [Viglino/ol-ext#164]
Can't seem to figure this one out. I'm using Openlayers 5 with Webpack.

I've added the Feature to the Map and View, but the animation doesn't work. The VectorLayer doesn't have any animateFeature() function...

The VectorLayer is imported like this: `import VectorLayer from 'ol/layer/Vector';`
And the Path from ol-ext like this: `import Path from 'ol-ext/featureAnimation/Path';`

Instantiated the VectorLayer: `const vl  = new VectorLayer({...});`

But this `console.log(vl.animateFeature)` throws back `undefined`

**Comment by Viglino** [comment]
Hello,
Have yous seen #158 or do you have an example?

**Comment by mosanerhao** [comment]
Hello,
I have the same problem.
`console.log(vectorLayerInstacne.animateFeature)`  throws back `undefined`.
I remove the whole node_modules folder and re-installed everything, but the `animateFeature` method is  also return undefined. @feketegy @Viglino

**Comment by Viglino** [comment]
Which animation are you using?

**Comment by mosanerhao** [comment]
I used ol.featureAnimation.Path to animate a feature along a path.

**Comment by Viglino** [comment]
Yes there was a bug in earlier version (see #158)

**Comment by dyh333** [comment]
> I used ol.featureAnimation.Path to animate a feature along a path.
> 
> ```
> import VectorLayer from 'ol/layer/Vector';
> import Path from 'ol-ext/featureAnimation/Path';
> const vl = new VectorLayer({...});
> console.log(vl.animateFeature);   // undefined
> ```
> 
> I just upgraded the ol version to 5.2.0, it works now.

hi, i met same problem, update ol to 5.2.0 not work, would you please show your code ? thanks

**Comment by dyh333** [comment]
![image](https://user-images.githubusercontent.com/1221313/59648722-aaf68680-91b2-11e9-9c78-5968cccf7d1e.png)
my version
