### ISSUE TITLE
Invalid CSS causing issues when bundling 'dist\ol-ext.css'

### ISSUE THREAD

**Issue by stomppah** [Viglino/ol-ext#166]
This is the offending line

https://github.com/Viglino/ol-ext/blob/7a14a1442a6d95bc267af0606bdcb6819d7f5d17/src/control/LayerSwitcher.css#L112

**Comment by Viglino** [comment]
It's a typo. Remove the # before border

**Comment by Viglino** [comment]
fix in #167
