### ISSUE TITLE
Can the crossover functionality in a Polygon Stretch interaction be disabled?

### ISSUE THREAD

**Issue by mepiazza** [Viglino/ol-ext#171]
I am using the transform, scale, translate and stretch vector interaction capabilities of the ol-ext library.  The stretch interaction gives the user the ability to take one edge of the polygon and shrink the polygon down to virtually nothing with both opposite edges cross over each other at the center of the polygon and then moving out in the opposite directions.  In most cases the resulting coordinates returned are benign and do not affect anything. However, over the International Date Line the reversing of the coordinates have a drastic effect on my application.  This crossover functionality is not needed but the basic stretching functionality is.  Is there a way to disable the crossover and just have the interaction stop when the polygon's opposite sides are moved together and it essentially becomes one line or two lines touching side by side?

**Comment by Viglino** [comment]
It can be. I'll try to add a `noFlip` option to prevent flip ASAP.

**Comment by Viglino** [comment]
The last commit adds a noFlip option to prevent feature to flip when stretch.

**Comment by mepiazza** [comment]
Jean-Marc,

I looked at the Github comments for the fix for #171 and it doesn't make
any sense to me.  The comment says you have added a noFlip option, however,
the code change shows the source shown below from the following listed
file: examples/interaction/map.interaction.transform.html
<https://github.com/Viglino/ol-ext/commit/19e0e815e5aa1fdc50a3a54f0c0a2842619b7550#diff-35bc0962f37d026fa56ab96a40a33e42>

   map.addLayer(vector);
-  vector.getSource().addFeature(new ol.Feature(new
ol.geom.Polygon([[[34243, 6305749], [-288626, 5757848], [210354, 5576845],
[34243, 6305749]]])));
+  vector.getSource().addFeature(new ol.Feature(new
ol.geom.Polygon([[[34243, 6305749], [-288626, 5757848], [210354, 5576845],
[300000, 6000000], [34243, 6305749]]])));
   vector.getSource().addFeature(new ol.Feature(new
ol.geom.LineString([[406033, 5664901], [689767, 5718712], [699551,
6149206], [425601, 6183449]])));
   vector.getSource().addFeature(new ol.Feature(new ol.geom.Point( [269914,
6248592])));

What does adding an extra polygon coordinate to an example demo file have
to do with the intended fix of adding a noFlip option?  I tried the updated
example and the stretching does the same thing it did before.  I have
searched thru the rest of the code on github and could find no other change
related to this effort.   I was expecting to find modifications to the
Transform.js file but the last mod it is showing is for the previous wrapX
issue.

Have I missed something somewhere because I'm feeling either really
confused or really dumb.

Thank you.

Mike Piazza

**Comment by Viglino** [comment]
:+1:  the real commit is here https://github.com/Viglino/ol-ext/commit/c15edefcf1fdb69eba8ca9aed6fe18d206c8c7da#diff-469782abf324fa2ce92b1176fcbc258e
It has been committed with an other issue and is not well tagged.
https://github.com/Viglino/ol-ext/commit/19e0e815e5aa1fdc50a3a54f0c0a2842619b7550#diff-35bc0962f37d026fa56ab96a40a33e42 only modify the polygon form to make it more clear when flipped.
I hope it's more clear :smiley:
