### ISSUE TITLE
PlaceMark Improvement: Ability to move it (Translate)

### ISSUE THREAD

**Issue by darkscript** [Viglino/ol-ext#172]
I like the PlaceMark, It would be good if the Placemark can be translated and one can maybe get coordinates of the new position, just a simple improve to add more functionality 😊😊😊

**Comment by Viglino** [comment]
What do you mean "translated"?
1. an interaction that translate the placemark? 
 a/ the placemark is an overlay and interactions apply on vector features
 b/ I think a layer with features and a Modify interaction is more appropriate in this case
2. a function to translate a placemark p.show(newPosition)?

To get the Placemark position you can use the placemark.getPosition() function

**Comment by Viglino** [comment]
In my mind, the Placemark is more a convenient way to display non permanent informations (you're here, you click here...) rather than real objects in the map (it's just a popup with custom CSS).

**Comment by darkscript** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13992858/46472797-016b9280-c7e7-11e8-8c12-75cb3e4f0c88.gif)

**Comment by Viglino** [comment]
Yes, for that, you can use a vector layer with a modify interaction and a [ol/style/FontSymbol ](http://viglino.github.io/ol-ext/examples/style/map.style.font.html)...

**Comment by Viglino** [comment]
Hello, 
if you're still interesting you can have a look at: 
http://viglino.github.io/ol-ext/examples/interaction/map.interaction.dragoverlay.html
