### ISSUE TITLE
Cursor states from Transform not reset after removeInteraction

### ISSUE THREAD

**Issue by megawac** [Viglino/ol-ext#177]
I looked into this a bit and wasn't sure how to fix this: if `Transform` is active on the map and the user activates any of the cursor states, if the transform interaction is removed via `map.removeInteraction(transformInteraction)` the cursor state will remain active.

Currently I get around this bug by resetting the viewports cursor whenever I remove the transform interaction.

Unfortunately openlayers doesn't seem to provide cleanup hooks for when a interaction is removed, perhaps it'd make sense to reset it in `setActive(false)`?

**Comment by Viglino** [comment]
Hello,
We have to handle the cursor state when removing interaction (ie. when changing the map in the setMap()).
At the top of the setMap function:
```javascript
var map = this.getMap();
// Reset the cursor
if (map && this.previousCursor_) {
  map.getTargetElement().style.cursor = this.previousCursor_;
  this.previousCursor_ = undefined;
}
````
I think, this also should be done in the setActive function...
@+
