### ISSUE TITLE
BSD dual licensing?

### ISSUE THREAD

**Issue by romanzoller** [Viglino/ol-ext#180]
I know the licensing has been discussed previously, e.g. in #1, but I wonder if it can be clarified further.

First of all, thank you for the amazing work, the reason I'm filing this issue is not to be pedantic, but to simplify using and contributing to ol-ext.

Would it be possible to dual-license ol-ext to BSD and CeCILL-B e.g. in one of the ways described [here](https://softwareengineering.stackexchange.com/questions/181040/how-to-document-a-dual-open-source-license)?

Basically, I'm suggesting the following modifications
- State in the README that ol-ext is dual licensed BSD / CeCILL-B
- Put both license texts in LICENSE.md, or state that ol-ext is dual licensed and have 2 more files for the license texts

I think there is already the intention to allow the BSD license as well, but it would be good to be absolutely clear about it, and also include the license text, so it is clear which BSD is meant (probably the [2-Clause](https://opensource.org/licenses/BSD-2-Clause)).

The reason that I'm interested in clarifying the BSD licensing is that CeCILL-B is not an OSI/FSF approved license (CeCILL has an approved license in version 2.1 but CeCILL-B is something different), and the problem with that is that it makes it more difficult to judge the consequences of using CeCILL-B-licensed code in another project. (The point of OSI/FSF approval is that they have already analyzed the consequences, so if we trust their judgement, we don't have to hire lawyers ourselves.)

**Comment by Viglino** [comment]
Hello,
The CeCILL-B (B for BSD) is a french BSD Licence and is fully compatible with BSD.
I only use it to promote the work done by translating the BSD licence in french law.
Any way, the project is published under the BSD-3-Clause [on npm](https://www.npmjs.com/package/ol-ext) and is distributed as is in the package.json.
I'll add a LICENCE-BSD.md file to clarify.
@+

**Comment by romanzoller** [comment]
Thanks! My understanding is that CeCILL-B is very similar to BSD in that it is also a permissive license, but it has some additional attribution requirements (see [FAQ](http://www.cecill.info/faq.en.html#bsd)), so IMHO it's important to distinguish the two.
