### ISSUE TITLE
Globe Control null

### ISSUE THREAD

**Issue by am2222** [Viglino/ol-ext#181]
Hi,
Some times I face this error which indicates that p is null in following function

``
ol.control.Globe.prototype.setCenter = function (center, show)
{	var self = this;
	this.pointer_.addClass("hidden");
	if (center)
	{	var map = this.ovmap_;
		var p = map.getPixelFromCoordinate(center);
		var h = $(this.element).height();
		setTimeout(function() {
			self.pointer_.css({ 'top': Math.min(Math.max(p[1],0),h) , 'left': "50%" } )
				.removeClass("hidden");
		}, 800);
		map.getView().animate({ center: [center[0],0] });
	}
};
``
it would be nice if add some checks it seems maps center is not defined yet

**Comment by Viglino** [comment]
This can occur when the control is inserted as the view is not fully initialiszed. I'll try to add a test...
