### ISSUE TITLE
layerswitchers improvment

### ISSUE THREAD

**Issue by am2222** [Viglino/ol-ext#182]
Hi,
It would be great if we can improve layer switcher. for example adding legend (for wms layers and vector layers) or some improvements in style.

**Comment by Viglino** [comment]
Hi,
`ol/control/LayerSwitcher` is fully customizable using CSS and you can add a `onInfo` function  to handle special task (such as displaying a legend).
Look at the [example here](http://viglino.github.io/ol-ext/examples/control/map.switcher2.html) with a blue style that displays a legend for the GEOLOGIE layer (click on the `i` at the right)...
You can also add your own buttons using the `drawlist` event or use the `seHeader` function to add a header  (see [example](http://viglino.github.io/ol-ext/examples/control/map.switcher.html)).
@+

**Comment by ThomasG77** [comment]
Not generic but could give you some ideas to get started https://bl.ocks.org/ThomasG77/c7d1d5ae918f168323f6b5c82059608c See also http://openlayers.org/en/latest/examples/render-geometry.html
In both cases, take input from style and generate a canvas. A canvas can be inserted or transformed to images you can use for your vector layers legend purpose

**Comment by am2222** [comment]
@ThomasG77 Hi,
Thanks very much. one of my main problems is style functions as they load style based on features fields, what options do you think we have in this case? looping over all features might give us all possible styles but not sure it has all of them or even I am not sure about its performance and accuracy

**Comment by am2222** [comment]
@Viglino wow thanks very much
