### ISSUE TITLE
Mention/add reference to polyfill.io mainly due to old IE JavaScript poor support

### ISSUE THREAD

**Issue by ThomasG77** [Viglino/ol-ext#192]
Inspecting browser compatibility, there are some issues for people using IE or Android.
For example, `Element.prototype.classList` is present in various files (some related to jQuery removal or already used before) whereas IE does not support it (https://polyfill.io/v2/docs/features/ then filter with keyword `classList`). We should mention in the doc that a polyfill is required and add in samples using `classList` the following:

    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>

**Comment by Viglino** [comment]
Yes it is!
ol is intended to run on all modern browser and IE down to version 9 using polyfills (https://openlayers.org/en/latest/doc/tutorials/background.html).
I've to add it in the example pages to make them run on all platforms...
