### ISSUE TITLE
Aborting a feature animation 

### ISSUE THREAD

**Issue by ulrikkold** [Viglino/ol-ext#213]
Hi, and thanks for a wonderful library.

I have a project in which I need to animate a series of LineStrings (`ol.animation.Path` together with `animateFeature` ), one after the other in sequence.

 I have provided the user with a collection of buttons to change between these linestrings, but when I change I would like to abort or remove the previous animation. Is this possible in some way?

I have tried attaching an event listener to my layer, but I am uncertain of how I would actually do what I would like to?

I did something along these lines:

```
animatedLayer.on('postcompose', event => {
  // if some conditions involving the animated feature are not right, then abort
  return false
})
```

I am not even sure, that what I am trying to do is possible? Could I get some guidance here?

/Ulrik H. Kold

**Comment by Viglino** [comment]
The `animateFeature` function returns a controler with a `start` and `stop`.
```javascript 
var c = animatedLayer.animateFeature(...);
// stop animation
c.stop ()
```

**Comment by ulrikkold** [comment]
Thanks. I have obviously been doing this too complicated (and wrong), because when I tried this earlier, it was not working for me.

**Comment by ulrikkold** [comment]
I made this work. Thanks for assuring me, that `.stop()` was actually the way to go.
