### ISSUE TITLE
Suggestion for popup: ESRI style popup for multiple feature results

### ISSUE THREAD

**Issue by alperdincer** [Viglino/ol-ext#214]
Hi, we have worked with ESRI JS before and ESRI style popups that includes multiple feature info can be a good enhancement for the OL-EXT library. As it is seen below, users can switch between the cards with arrows at the top-right position. This popup is showing two features info window in one popup.  

<img width="326" alt="screen shot 2018-11-06 at 22 21 36" src="https://user-images.githubusercontent.com/1174240/48088286-a5938f80-e212-11e8-9dd8-4dde4103afb4.png">

**Comment by Viglino** [comment]
Hi,
Popup content is a huge feature (application dependent) and third party libraries have mechanisms to handle paginations or tabs that can be included in the popup.
I'll try to see what can be done in case of popup applied on features selection...

**Comment by Viglino** [comment]
Hello,
I've commit f a PopupFeature overlay to show feature information in a popup.
see http://viglino.github.io/ol-ext/examples/popup/map.popup.feature.html
The template used in the popup can be refine to customize the information.

**Comment by alperdincer** [comment]
Just wow :) 

This is what we are looking for. We will implement the new feature as soon as possible and return if there are any issues. 

Thanks for this great extensions.

**Comment by Dkkemaries** [comment]
Hello , 
is it possible to modify feature using this popup?

Thanks,
