### ISSUE TITLE
Dijskra class not present in npm ?

### ISSUE THREAD

**Issue by hnfcha** [Viglino/ol-ext#216]
I didn't find Dijskra class in my latest ol-ext  node module. Is it implemented ?

**Comment by hnfcha** [comment]
My Bad, it's on ol node module ...

**Comment by hnfcha** [comment]
Ok thank, is there a reson why it's not inclued ?
Nice extensions by the way ;)

**Comment by Viglino** [comment]
It's a new feature. It will be include in the next version :smiley:
