### ISSUE TITLE
SVG style lost on animation

### ISSUE THREAD

**Issue by Forkinel** [Viglino/ol-ext#218]
Hi,

It seems that when i run animateFeature(feature, anim) where my feature is using the following style `let IconStyle = new ol.style.Style({
                        image: new ol.style.Icon({
                            src: 'data:image/svg+xml;utf8,' + SVGIcon,
                            rotation : radian * .Heading,
                            scale: 0.1,
                            anchor: [125,125],
                            anchorXUnits: 'pixel',
                            anchorYUnits: 'pixel',                                               
                            color: 'black',                            
                            crossOrigin: 'anonymous'
                        }),
                        text: createTextStyle(myFeature)
                    });`
when animating it shows the svg but its has ignored the paramters except src. Is this a bug? If not a bug then how can i stop is losing the parameters?

thanks

**Comment by Viglino** [comment]
Hi,
I don't have such issue on my code: see https://codepen.io/viglino/pen/WYjZKB
Which version of ol are you using?
