### ISSUE TITLE
Get changing coordinates of an animated feature

### ISSUE THREAD

**Issue by Forkinel** [Viglino/ol-ext#219]
Hi, 

Is it possible to get the coordinates of a feature as it is being animated? You currently have animationstart/end....is there an equivalant of this for whilst the animation is running. As I need to get the changing coordinates of a feature as it moves.

Thanks

**Comment by Viglino** [comment]
Hi,
You can listen to the change event on the geometry to get when the feature move:
````javascript
f.getGeometry().on('change', function(){ 
  // do something
});
vector.animateFeature ( f, anim );
````
Be aware the code will be run on each frame rendering and may cause lag.
NB: if you're lookin form ore control on the movement, you can also look at the [ol3-games examples](https://viglino.github.io/ol3-games/index.html) and specially the [sprite path example](https://viglino.github.io/ol3-games/examples/map.sprite.path.html)

**Comment by Forkinel** [comment]
Thanks for the reply, thats really helped :-)
