### ISSUE TITLE
extra parameters in nominatim url?

### ISSUE THREAD

**Issue by wendell-t** [Viglino/ol-ext#221]
First, thank you for the fine work on ol-ext!  It is a great extension to openlayers!

Is it possible to add extra parameters to the nominatim url?  I don't live in France, so I would like it to search different areas.  The parameter string would look similar to:
    ``` https:.../search?viewbox=-77.0,38.8,-77.2,38.99&bounded=1&format=json&...```
I can force that specific string by modifying the source:
```javascript
ol.control.SearchNominatim.prototype.requestData = function (s) {
            return {
            viewbox:  "-77.0,38.8,-77.2,38.99",   // my edit
            bounded: 1,      // my edit
            format: "json",
            ...
```
That is certainly not proper, but the url has the request parameters that I want and nominatim returns successfully.  I want to form the viewbox coordinates by using the bounds of the visible map area.

Is this a good suggestion?
Thanks again for the good work.
wendellwt

**Comment by Viglino** [comment]
Hello,
Yes its a good suggestion. 
I'll try to add it in the parameters of the SearchNominatim interaction to be more generic.
@+
