### ISSUE TITLE
OverviewMap?

### ISSUE THREAD

**Issue by mathe1** [Viglino/ol-ext#222]
Hi,

I'm very interested in use the Overview. 

Your online-demo _ol-ext: Overview map control_ works fine. 
But I can't adapt it. I use the ol and ol-ext distributions inside of an extension for Chrome.

Maybe anything seems wrong with the control, because click on button (for open the collapsed panel) doesn't work. It stay closed. It changes the classNames, but nothing happens.

Maybe I should set width and height of the overview-panel? But how?

This code works for OverviewMap of OL5 ... (a control "overview" like descripted at your demo seems not exists in OL5)

```
var ovmap = new ol.control.OverviewMap({ 
   className: 'ol-overviewmap olmustprint',
   layers: [MapSystem('osm'), vectorLayer]  , 
   //MapSystem calls the OSM, vectorLayer is a filled polygon
   minZoom: 11, maxZoom: 14
});

map.addControl(ovmap);
```

This is my try with ol-ext Overview in OL5, too...

```
   var ovmap_ext = new ol.control.Overview({ 
      layers: [MapSystem('osm'), vectorLayer]  ,
      rotation: false,
      minZoom: 11, maxZoom: 14,
      align: 'bottom-left',
      // bottom: '40px'
      //Overview-Button will create outside the map-view, don't know why. 
   });

   map.addControl(ovmap_ext);
```
This code then I find in HTML:
```
<div class="ol-overview ol-unselectable ol-control">
 <button type="button"></button>
 <div class="panel">
  <div class="ol-viewport" data-view="161" style="position: relative; overflow: hidden; width: 100%; height: 100%; touch-action: none;">
   <canvas class="ol-unselectable" style="width: 100%; height: 100%; display: none;"></canvas>
   <div class="ol-overlaycontainer"></div>
   <div class="ol-overlaycontainer-stopevent"></div>
  </div>
 </div>
</div>
```

What did I wrong?

**Comment by mathe1** [comment]
Oh...

I looked at the CSS... 
I forgot to add the ol-ext.css to content_scripts section of my manifest.

Now I see all... - but the Overview shows me a region of France... - why it isn't synchron with my map view?

**Comment by Viglino** [comment]
Hello,
The overview should synchronize with the map, but I found a bug: when the map is hidden it doesn't moves.
The bug is fixed in the last commit and the map synchronize on toggle.
@+
