### ISSUE TITLE
Get angle from transform interactions

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#223]
Hello,
how to get  real rotation angle (in degrees) from transform interactions. I found that for the calculations we use formula like this : e.angle*180/Math.PI -180)%360+180).toFixed(2)),
but  is this real rotation angle ?

BR,

**Comment by Viglino** [comment]
The angle is returned in radian you have to convert it to degree.
`PI rad. = 180 deg.`
So the angle in degree is (and this is the real rotation angle):
`a = e.angle*180/Math.PI`
Be aware this angle may be more than 360 deg. if you turn the feature more than one turn. Or less than -360 if you turn counter wise.
Thus you must use a % operator to have the angle from -360 to 360:
`a = (e.angle*180/Math.PI) % 360`
If you want an angle between -180 to 180 you have to use an other formula:
`a = (((e.angle*180/Math.PI - 180) % 360) + 180) % 360`

**Comment by Dkkemaries** [comment]
Thanks , for explanation
I think that my "rotation angle" means completely different than your:)

![azimuth](https://user-images.githubusercontent.com/20822365/49457799-25058600-f7f4-11e8-997e-a330c9877795.png)

, let's see attached image , in my case I thought about azimuth - az , but in Your case it is something like e.angle - difference between previous an current state.
I understand how I can calculate it mathematically , but when I tried to write my formula in js code , I got wrong values.
 May be You have an advice how to calculate azimuth ?

**Comment by Viglino** [comment]
The returned angle is the rotation angle provided by the transform, not the current angle of the object...
It is a trigonometric measure (counter clockwise).
If you want to calculate the angle of the objects you have to store it like it is done for the point feature:
````javascript
e.feature.set('angle', startangle - e.angle);
````

**Comment by Dkkemaries** [comment]
Ok, clear. Yes the problem was with the startangle value

Thanks

**Comment by provalinf** [comment]
Resurrect
Hello,
I use also this formula to convert radians to degrees : `(e.angle * 180 / Math.PI - 180) % 360 + 180`
My problem is that I'm trying to convert an angle from -180 to +180 degrees in radian and I can't find out how to invert the formula because of the modulo and thus the inversions I spotted :
```
//    deg  ->    rad
// -178.33 -> -3.112424297335325
//  178.69 -> -3.164490064610729

//  70.31  ->  1.22
//  71.62  -> -5.033133821377763

//  -1.15  -> -0.02002663689020867
//   1.24  ->  0.02167345873189741
```
I'm open to any suggestion  
Thank you very much.

**Comment by Viglino** [comment]
var arad = (angle * Math.PI / 180) % (2*Math.PI);
if (arad < -Math.PI) arad += 2*Math.PI
if (arad > Math.PI) arad -= 2*Math.PI

**Comment by provalinf** [comment]
Thank you @Viglino  
But here's the problem with what you're proposing:  
Here's a gif  
![XA1kgqv4nh](https://user-images.githubusercontent.com/15704455/78014487-49ba3100-7348-11ea-8718-3b06e34ad64b.gif)
```javascript
console.log("rad: " + e.angle);
let deg = (((e.angle*180/Math.PI - 180) % 360) + 180);
console.log("deg: " + deg.toFixed(2));
let arad = (deg * Math.PI / 180) % (2*Math.PI);
if (arad < -Math.PI) arad += 2*Math.PI;
if (arad > Math.PI) arad -= 2*Math.PI;
console.log("arad: " + arad);
```

**Comment by Viglino** [comment]
while (arad < -Math.PI) arad += 2 * Math.PI;
while (arad > Math.PI) arad -= 2 * Math.PI;

**Comment by provalinf** [comment]
Same result, no change because conditions are never right

**Comment by provalinf** [comment]
Okay, very strange, the radian in `interaction.on('rotating'` goes from 1.26xx to -5.xx but I can get a valid radian by going through a degree conversion and then using the formula you suggest.

Example :
```javascript
this.interaction.on('rotating', function (e) {
	e.feature.get('attributes')['angleRotActuRad'] = e.angle;
});
this.interaction.on('rotateend', function (e) {
	let deg = (((e.feature.get('attributes')['angleRotActuRad'] * 180 / Math.PI - 180) % 360) + 180);
	e.feature.getGeometry().rotate(-(deg * Math.PI / 180) % (2 * Math.PI), featureCenter);
	console.log(e.feature.get('attributes')['angleRotActuRad']+" => "+(deg * Math.PI / 180) % (2 * Math.PI));
});
```
`78.93deg`  
`-4.90566343308555 => 1.377521874094036`
This example shows that the calculation is correct by cancelling the rotation when the click is released.

Problem solved, although I don't understand why WHEN rotating the value doesn't go from PI to -PI.
