### ISSUE TITLE
Failed to install with npm from git

### ISSUE THREAD

**Issue by csabakeszegh** [Viglino/ol-ext#228]
Hi All,
I would like to use [PopupFeature](https://github.com/Viglino/ol-ext/commit/0b71467590df2052c4148885c6c71d0a58c1f11e) from ol-ext. It's not yet included in the latest release (3.0.2). Unfortunately I failed to install from git directly. It complains that can't find `gulp`, however it's available (installed globally).

- macos 10.13.6 (node installed with macports)
- gulp: CLI version 2.0.1
- npm: 6.4.1
- node: v8.11.4

<details><summary>npm install Viglino/ol-ext</summary>

```
> ol-ext@3.0.2 prepack /Users/csaba.keszegh/.npm/_cacache/tmp/git-clone-5210c811
> gulp prepublish

[17:59:09] Local gulp not found in ~/.npm/_cacache/tmp/git-clone-5210c811
[17:59:09] Try running: npm install gulp
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:Viglino/ol-ext.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/csaba.keszegh/.npm/_logs/2018-12-13T16_59_09_883Z-debug.log
```
</details>

Thanks in advance.

**Comment by Viglino** [comment]
Hello,

When publishing on npm a prepack script is run. It seems it can't run.
I've publish a v3.0.3, thus you can use it for you rproject.

@+
