### ISSUE TITLE
Style the transform rectangle

### ISSUE THREAD

**Issue by martinmcneela** [Viglino/ol-ext#231]
I have been trying and failing to style the rectangle that appears around a feature when it is being selected. 

I am using http://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html.

Ideally what I need to do is change the colour and thickness of the line, and also add some padding between the feature and the dashed rectangle with the handles.

Is this possible?

**Comment by ThomasG77** [comment]
It is possible. An example below,

Go to [official map.interaction.Transform example](http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html), then execute in the console the following:

```javascript

var stroke = new ol.style.Stroke({ color: [0,255,0,1], width: 1 });
var strokedash = new ol.style.Stroke({ color: [0,255,0,1], width: 1, lineDash:[4,4] });
var fill = new ol.style.Fill({ color:[255,255,255,0.8] });
var fill0 = new ol.style.Fill({ color:[0,255,0,0.01] });
var circle = new ol.style.RegularShape({
  fill: fill,
  stroke: stroke,
  radius: 6,
  points: 15
});
var bigpt = new ol.style.RegularShape({
  fill: fill,
  stroke: stroke,
  radius: 8,
  points: 4,
  angle: Math.PI/4
});

interaction.setStyle('default', [
  new ol.style.Style({image:bigpt, stroke:strokedash, fill:fill})
]);
```

The secret sauce comes from http://viglino.github.io/ol-ext/dist/ol-ext.js by searching `ol.interaction.Transform.prototype.setDefaultStyle` (also available at https://github.com/Viglino/ol-ext/blob/master/src/interaction/Transform.js#L159 before bundling)

**Comment by Viglino** [comment]
Hi,
All handles can be styled using ol styles.
You can change the anchor to offset the symbols.
NB: the `setAnchor()` method is only available on Icons style. 
If you use `RegularShape` you have to change the anchor using the `getAnchor()` method:
````javascript
var style = new ol.style.Style({
  image: new ol.style.RegularShape({
    points: 4,
    radius: 8,
    angle: Math.PI/4,
    fill: new ol.style.Fill({ color: 'rgba(255,0,0,.5)' })
  })
});
style.getImage().getAnchor()[0] = 16;
style.getImage().getAnchor()[1] = 0;
interaction.setStyle('scale', style)
````
@+
