### ISSUE TITLE
LayerSwitcher search layer

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#233]
Hello,
is it possible to create search box inside layer switcher ? The aim is to give possibility to filter out layer among  other layers (100-200 layers )  and enable/disable it. 
BR,

**Comment by Viglino** [comment]
Hello,

This can be done using:
* the `setHeader()` method to add a search input on the LayerSwitcher's header div
* the `drawlist` event to listen to LayerSwitcher drawing: the returned event has a `li` attribute you can use to hide or show the layer according to the search input

I'll try to make an example like this...

**Comment by Viglino** [comment]
Here is an example: https://codepen.io/viglino/pen/MLYGbE
I'll see if it could be a good feature to add in the LayerSwitcher control.
@+

**Comment by Dkkemaries** [comment]
Yep, 
this is similar what I tried to do, but is this filtering works with layer grouping ?
Let say we have group - region ,with sublayers region1,region2,region3 etc...
Each sublayer have a title:'region_1' (region_2,region_3)
var regions = new ol.layer.Group(
    {   title: 'region',
        openInLayerSwitcher: false,
        visible: false,
        layers:
            [
                region1_layer,
                region2_layer,
                region3_layer,
             
            ]
    });

is it possible to filter only region_2 ?I tried to rewrite  

// When switcher is drawn hide/show the list item
lswitcher.on('drawlist', function(e){
  var rex = new RegExp(search.val());
  if (rex.test(e.layer.get('title'))) {
    $(e.li).show();
  } else {
    $(e.li).hide();
  }
})

but unsuccessfully ...

**Comment by Viglino** [comment]
Hello,
I've created an example to filter layers in the repo: http://viglino.github.io/ol-ext/examples/control/map.switcher.filter.html

**Comment by Viglino** [comment]
As the test is done on a RegExp you can add the ì`flag to ignore case:
````javascript
var rex = new RegExp(search.val(), 'i');
````
See: https://codepen.io/viglino/pen/MLYGbE
