### ISSUE TITLE
unod redo problem

### ISSUE THREAD

**Issue by g-hawk** [Viglino/ol-ext#239]
Hi all,
I'm developing a typescript/angular 6 application that use ol and ol-ext (installed both via npm).
I added undo-redo interaction to map, but it's not working.
I debugged interaction and I saw that  getVectorLayers function return always an empty array;
the check l instanceof ol_layer_Vector is always false.
Can someone help me? Thanks a lot.
Giuseppe

function getVectorLayers(layers, init) {
    if (!init) init = [];
    layers.forEach(function(l) {
      if (l instanceof ol_layer_Vector) {
        init.push(l);
      } else if (l.getLayers) {
        getVectorLayers(l.getLayers(), init);
      }
    });
    return init;
  }

**Comment by Viglino** [comment]
Hello,
How do you insert a Vector in your app? 
Can you past the code in the issue?
@+

**Comment by g-hawk** [comment]
Hi,
thanks for the reply.
Briefly the code is (I have some functions that cycle on a array of layers configuration json object and builds layers and then add them to the map):

```
import Map                                from 'ol/Map.js';
import {Vector as VectorLayer}  from 'ol/layer.js';
import VectorSource                  from 'ol/source/Vector.js';

let layer = new VectorLayer({
  visible:true,
  extent: [...],
  source: new VectorSource({...})
});

let map = new Map({...});

map.addLayer(layer);
```

In another module I have:

```
import UndoRedo                from 'ol-ext/interaction/UndoRedo'
this.undoRedoInteraction = new UndoRedo();
this.map.addInteraction(this.undoRedoInteraction);

public undo()
  {
    this.undoRedoInteraction.undo();
  }

public  redo()
  {
    this.undoRedoInteraction.redo();
  }
```

undo and redo function are binded to two buttons.

**Comment by g-hawk** [comment]
Sorry,
I closed issue by mistake.
Giuseppe

**Comment by Viglino** [comment]
In the first file you don't include the right module:
````javascript
import {Vector as VectorLayer}  from 'ol/layer.js';
````
replace with:
````javascript
import VectorLayer from 'ol/layer/Vector';
````

**Comment by g-hawk** [comment]
No, I've modified according your suggest, but  if (l instanceof ol_layer_Vector)  is skipped ...

**Comment by Viglino** [comment]
Can you test in the second file:
````javascript
this.map.addInteraction(this.undoRedoInteraction);
// Add
import VectorLayer from 'ol/layer/Vector';
this.map.getLayers().forEach((l) => {
  console.log('test layer:', l instanceof VectorLayer );
});
````
One layer should be a VectorLayer and return true.

**Comment by g-hawk** [comment]
Strange....
now, with your code, I see true on all vector layer on the map.
Because into plugin isn't working?

**Comment by Viglino** [comment]
Try to clear the cache...

**Comment by g-hawk** [comment]
>If not the map has no VectorLayer yet.
Layers are on the map first getVectorLayers parameter is an array of 22 layers...

I added this code in second file (id is an attribute that I added to layer)
```
console.log(layer.constructor.name); 
console.log(VectorLayer.name); 
console.log('layer id:'+layer.get('id'),  layer instanceof VectorLayer );
```

On Chrome console I see:
VectorLayer
VectorLayer
layer id:9999 true

I added same code on UndoRedo.js of ol-ext

```
// Ges vector layers 
  function getVectorLayers(layers, init) {
    if (!init) init = [];
    layers.forEach(function(l) {
       if(l.get('id') == 9999){
          console.log('layer id '+l.get('id'), l instanceof ol_layer_Vector);
          console.log(l.constructor.name);
       }
      if (l instanceof ol_layer_Vector) {
        init.push(l);
      } else if (l.getLayers) {
        getVectorLayers(l.getLayers(), init);
      }
    });
    return init;
  }
```
On Chrome console now I see:
layer 9999 false
VectorLayer
VectorLayer

VectorLayer.js in ol module and VectorLayer.js in ol-ext node_modules are slightly different (package.json says version 5.3.0 for ol in ol-ext and 5.2.0 for ol in my app). 
Could this be the cause?

**Comment by Viglino** [comment]
You have to use the same module in the whole app... or you won't refere to the same objects.

**Comment by g-hawk** [comment]
Hi,
I have update my ol to version 5.3.0, that is the same of ol-ext plugin, but I have always false on instanceof check (output on chrome console is as in the previous post). Vector.js files are identic into the plugins ....

**Comment by Viglino** [comment]
Hi
You must have only one file for the whole project: if you import the VectorSource object from one file and from one other it will be different, even if the files are identical... The ES6 compiler will create two different objects (that pretty convenient to avoid variable collision but not in your case).

**Comment by g-hawk** [comment]
I'm a bit confused.
In my first post I say that I installed two package in my application: ol and ol-ext.
You say that I can use only ol-ext and its ol included package and uninstall ol?
So I must have:
`import VectorLayer from 'ol-ext/node_modules/ol/layer/Vector.js';`

Or I can use ol package and install ol-ext without dependecies?
In js mode I have to include in html both ol.js and ol-ext.js; and in Angular mode?
Thanks a lot.

**Comment by g-hawk** [comment]
Maybe I understood ...
When I installed ol-ext I have already installed ol 5.2.0.
So ol-ext has added ol 5.3.0 in own node_modules dir.
I have uninstalled both and I have installed only ol-ext.
Now, in node_modules dir of my application I have both ol and ol-ext and ol-ext hasn't it own node_modules dir. Now it's working.

One question: now update of ol is related at update of ol-ext, right? If I want update ol for a bug-fixing or for a new release I can't, right?
Thanks a lot.

**Comment by Viglino** [comment]
No you don't have to.
There is only one instance of node_module/ol in your project
I've put an Angular sandbox with undo/redo on ol here https://codesandbox.io/s/4qknm503zw

Doing this I've seen a problem in the EditBar.js (located in your `node_module/ol-ext/control/` folder) bbut you're not concerned till you use it.
If so you can change line 11:
````javascript
import ol_interaction_Select from './Select'
````
to 
````javascript
import ol_interaction_Select from 'ol/interaction/Select'
````

**Comment by g-hawk** [comment]
Well, 
thanks for the response.
Now I using undoRedo interaction in my application. I add it to the map when enable edit functions and remove at the end of editing.
When I remove interaction I have this errors:

```
ERROR TypeError: Cannot read property 'getLayers' of null
    at ol_interaction_UndoRedo.push../node_modules/ol-ext/interaction/UndoRedo.js.ol_interaction_UndoRedo._watchSources (UndoRedo.js:91)
    at ol_interaction_UndoRedo.push../node_modules/ol-ext/interaction/UndoRedo.js.ol_interaction_UndoRedo.setMap (UndoRedo.js:62)
    at Map.<anonymous> (PluggableMap.js:435)
    at Collection.boundListener (events.js:41)
    at Collection.dispatchEvent (Target.js:99)
    at Collection.removeAt (Collection.js:235)
    at Collection.remove (Collection.js:218)
    at Map.removeInteraction (PluggableMap.js:1151)
```

I remove also other interactions (draw, snap, modify, ...) and there aren't errors on these.
Debugging I see that map object passed to function
`ol_interaction_UndoRedo.prototype.setMap = function(map) { ..`
is null

**Comment by Viglino** [comment]
ol-ext is bound to a version of ol but should work on minor subversion. He might not run on the next v6 until some updates. 
There is actually a bug when removing the interaction from the map (setMap with null). 
I'll try to push a patch asap.

**Comment by Viglino** [comment]
A new version v3.1.1 is available on npm
