### ISSUE TITLE
Feature with FontSymbol not clickable

### ISSUE THREAD

**Issue by allartammik** [Viglino/ol-ext#240]
Hello,

I have a problem with clicking on features with style FontSymbol (using font awesome). It doesn't seem to hit features when I click on map.

I have a feature with description and style set like that
```
var awesomeFeature = new Feature({
  geometry: new Point([0, 0]),
  description: "my point"
});

awesomeFeature.setStyle(
  new Style({
    image: new FontSymbol({
      glyph: "fa-wheelchair",
      color: "red",
      radius: 15,
      anchor: [0.5, 1]
    })
  })
);
```
and I have registered an onClick event on map, that calls mapOnClick function, that should console.log the description (popoverContent) of the feature: 
```
function mapOnClick(evt) {
  const map = evt.map;
  console.log('mapOnClick received');
  map.forEachFeatureAtPixel(evt.pixel, (feature, layer) => {
    if (
      typeof feature.get("features") !== "undefined" &&
      feature.get("features").length > 1
    ) {
      return false;
    }

    const popoverContent = feature.getProperties().features[0].getProperties()
      .description;
    const coordinates = feature.getGeometry().getCoordinates();
    console.log(popoverContent + " @ " + coordinates);
  });
}
```
Expected behaviour is that when I click on a feature (wheelchair), `my point @ ...` is printed to the console.

I have also made a codesandbox example  https://codesandbox.io/s/oj25o8355

When I'm using OpenLayers' style Icon, then mapOnClick works as expected (unfortunately it does not show the icon svg in codesandbox for some reason):
```
iconFeature.setStyle(
  new Style({
    image: new Icon({
      anchor: [0.5, 1],
      color: "green",
      anchorXUnits: "fraction",
      anchorYUnits: "fraction",
      src: "pin.svg",
      scale: 0.5
    })
  })
);
```

Versions that I have:
```
"ol": "^5.3.0",
"ol-ext": "^3.1.0",
"font-awesome": "4.7.0",
```

Am I using it wrong or it is not implemented? Or is there a work-around for my issue?
Thanks in advance

**Comment by Viglino** [comment]
It seems you have to define a `fill` or `stroke` in the style to get it working. Otherwise the symbol seems to be transparent...
See https://codesandbox.io/s/7n25omjkx

**Comment by allartammik** [comment]
Adding `fill` element works. Adding `fill` AND `stroke` also works. Adding only `stroke` does not work though. 

For the record, correct solution is:
```
var awesomeFeature = new Feature({
  geometry: new Point([0, 0]),
  description: "my point"
});

awesomeFeature.setStyle(
  new Style({
    image: new FontSymbol({
      glyph: "fa-wheelchair",
      fill: new Fill({color: '#fff'}),
      color: "red",
      radius: 15,
      anchor: [0.5, 1]
    })
  })
);
```

Thanks!
