### ISSUE TITLE
EditBar doesn't work with Select enabled

### ISSUE THREAD

**Issue by annasimoniaine** [Viglino/ol-ext#241]
I'm trying to get the EditBar working. When I set Select: false, it works fine, but when I don't disable Select, I get the following TypeError:

> Uncaught TypeError: this.interaction_.setActive is not a function
    at ol_control_Toggle.setActive (Toggle.js?c50e:132)
    at new ol_control_Toggle (Toggle.js?c50e:55)
    at ol_control_EditBar._setSelectInteraction (EditBar.js?c516:138)
    at new ol_control_EditBar (EditBar.js?c516:46)
    at window.onload (index.vue?6ced:190)

My code for adding the EditBar:

    var map = new Map({
      interactions: defaultInteractions().extend([dragBox, dragRotate]),  
      layers: [raster, vectorLayer],
      target: 'map',
      view: new View({
        center: [-356000, 7547900],
        zoom: 19
      })
    });

    var mainBar = new Bar();
    map.addControl(mainBar);

    var editBar = new EditBar ({
      source: vectorLayer.getSource(),
      interactions: {
        Info: false,
        DrawHole: false,
        Split: false,
        Offset: false
      }
    });
    mainBar.addControl(editBar);

What's going wrong here?

**Comment by Viglino** [comment]
There is a bug in the last npm version, a correction is on the rails 35eb232. I'll try to push a new version on npm this week-end.

The select doesn't refer to the right module in the EditBar.js:
replace : `import ol_interaction_Select from './Select'`
to: `import ol_interaction_Select from 'ol/interaction/Select'`

Meanwhile you can:

1. patch the node_module/ol-ext/control/EditBar.js 
2. use your own select in the bar: 
````javascript
import ol_interaction_Select from 'ol/interaction/Select';
var editBar = new EditBar ({
  source: vectorLayer.getSource(),
  interactions: {
    Info: new Select({ layers: [vectorLayer] }),
    DrawHole: false,
    Split: false,
    Offset: false
  }
});
````

**Comment by annasimoniaine** [comment]
Great, thanks!
