### ISSUE TITLE
EditBar - Delete button doesn't work when there's a layer group in the map

### ISSUE THREAD

**Issue by wguilen** [Viglino/ol-ext#243]
Hello,

If there's a layer group (`ol.layer.Group`) in the map, the delete action for lines, polygons, etc. triggers an error in the function `ol.interaction.Delete.prototype._getSources`. It's due to the fact that layer groups don't have a method called `getSources`; maybe should the layers of the group be looped and used instead?

If there's another solution to this issue, please let me know.

Regards;

**Comment by Viglino** [comment]
OK the loop is done, but no test to check if there is a source in the layer...
I'll push a correction asap.

**Comment by wguilen** [comment]
Thanks!

**Comment by Viglino** [comment]
Done in the last version v3.1.1

**Comment by wguilen** [comment]
Thanks again!
