### ISSUE TITLE
Question: How to programmatically rotate selected feature(s) using ol.interaction.Transform

### ISSUE THREAD

**Issue by sukeshlaghate** [Viglino/ol-ext#244]
Hi ,
I am submitting a 

- [x] Question 
- [ ] Feature Request
- [ ] Bug

I browsed through ol.interaction.Transform example and found it to be useful. I would appreciate if you could point out how can I Programmatically rotate selected feature(s) instead of dragging them with mouse? 
Use case is I select feature(s) and press play button which will start rotating the feature(s) till I press stop button.

**Comment by Viglino** [comment]
Hello,

You don't need to use a transform interaction to rotate a feature programmatically.
Just use the rotate method of the geometry to do that  (see https://openlayers.org/en/latest/apidoc/module-ol_geom_Geometry-Geometry.html#rotate).

If you're looking to animate features with a rotate you should look at the [ol.featureAnimation](https://github.com/Viglino/ol-ext/blob/master/src/featureanimation/FeatureAnimation.js) (see examples here: http://viglino.github.io/ol-ext/?q=featureanimation)

There is no rotation animation but you can do your own one, here is a pen to show how: https://codepen.io/viglino/pen/jdgRRq

@+

**Comment by sukeshlaghate** [comment]
@Viglino Thank you for providing solution. Closing as answered 👍
