### ISSUE TITLE
define is not defined (ember-cli and IE11)

### ISSUE THREAD

**Issue by scwipkingen** [Viglino/ol-ext#245]
My ember-app is not working when I use the extension in IE11. Chrome is fine. In IE11 I get the error:
define is not defined

I import the ol-ext dist-files with app.import(...) in my Ember-App.

What is the proper way to use ol-ext with Ember.js? Btw, Openlayers is working fine in my app.

**Comment by Viglino** [comment]
Hello,
Sorry I've no idea on why it doesn't work.
Perhaps a polyfill is missing...

**Comment by scwipkingen** [comment]
It has something to do with polyfills not working correctly. Anyway it is not related to your code, so you could close this ticket.

Arrow functions are still present in the code despite using babel polyfills, so IE11 does not work. I translated your code with the babel io translator and now everything is working ok. It's a workaround, but OK for now.

Thank youl.
