### ISSUE TITLE
Help with ol.style.FontSymbol and Fortawesome 5.2 in Angular application 

### ISSUE THREAD

**Issue by sukeshlaghate** [Viglino/ol-ext#248]
Hi Jean-Marc,

I have set up angular application by following your Angular example. 
I have placed fontawesome css in the styles section of angular.json so that fontawesome css style is available to entire application 
```
 "styles": [
"node_modules/@fortawesome/fontawesome-free/css/all.css",
...]
```
I have imported Fontsymbol in the ts file and fontawesome definitions decalred in the constructor as follows 
```
import FontSymbol from 'ol-ext/style/FontSymbol';
...
...
constructor() {
....
 FontSymbol.addDefs(
      {	'font': 'Font Awesome 5 Free',
        'name': 'Font Awesome 5 Free',
        'copyright': 'SIL OFL 2.1',
        'prefix': 'fas'
      }, FA_DEFINITIONS);
....
....
}
```
FA-DEFINITIONS is defined as 
```
export const FA_DEFINITIONS = {
'fa-500px': '\uf26e',
...
'fa-video': '\uf03d',
...
}
```
In the application when I use Fontsymbol on point feature 

```
 this.cameraIconLayer = new VectorLayer({
      source: this.cameraIconSource,
      style: new Style({
        image: new FontSymbol( {
          glyph: 'fa-video',
          radius: 25,
          fill: new Fill(
            {	color: '#ffcc33'
            }),
          stroke: new Stroke(
            {	color: '#ffcc33',
              width: 1
            })
        })
      })
    });
``` 
I get square/rectangle glyph ( I guess when any glyph is not found it is replaced by square/rectangle glyph?) instead of expected symbol. Am I missing out anything?
Request you to help in resolving this issue.

**Comment by Viglino** [comment]
Hello,
The fontdef use fontawesome 4.7 
See #153 for more info
