### ISSUE TITLE
Block scaling/rotating when more than one feature is selected

### ISSUE THREAD

**Issue by annasimoniaine** [Viglino/ol-ext#249]
Hi. When using the transform interaction, is it possible to disable scaling and rotating when more than one feature is selected? Can those settings somehow be changed after initialising the interaction? I do still want to be able to translate the features together, so I don't want to disable selecting multiple altogether.

**Comment by Viglino** [comment]
You can change properties on the fly as you can see in the example.
You can listen to the `select` event to know how many features are selected:
````javascript
interaction.on('select', function(){
  // Remove scale and rotate if more than 1 feature selected
  interaction.set('scale', interaction.getFeatures().length<2)
  interaction.set('rotate', interaction.getFeatures().length<2)
});
````

**Comment by annasimoniaine** [comment]
Ah, thanks! I thought I'd tried that, but I checked interaction.getFeatures() < 2 instead of its length... It works perfectly now
