### ISSUE TITLE
Trigger popup feature without binding to a select interaction

### ISSUE THREAD

**Issue by RobotCaleb** [Viglino/ol-ext#250]
I've modified the popup feature display to handle a bit more of the data I'm trying to display, but I'd really like to open it by clicking an entry in a table elsewhere and not have my (non-cartography) map data covered up with selectable regions.

Is this possible? Could you possibly provide a bit of code to demonstrate?

Thanks

**Comment by Viglino** [comment]
You can use the `show()xx` method to display a popup on a map when click on a button or a line in a table.
Here is a working example: https://codepen.io/viglino/pen/wObwEw

**Comment by RobotCaleb** [comment]
Perfect! That's the bit I was missing. Thanks so much.
