### ISSUE TITLE
Event handling in LayerSwitcher

### ISSUE THREAD

**Issue by severinstrobl** [Viglino/ol-ext#252]
We use the ol-ext LayerSwitcher in our map application and are extremely happy with the provided functionality. There is, however, an issue when using layers where a large number of features are updated dynamically. In our case events ingested via a WebSocket connection modify the styling of individual features. Each of these changes triggers a `change` event for the corresponding layers. The LayerSwitcher in turn seems to subscribe to all `change` events on all layers of the map, leading to a complete regeneration of the entries in the layer list. For large numbers of events (we are talking several dozen events/s here), this constant regeneration of the layer list seems to become problematic and interacting with the layer controls becomes flaky. Is there any way to work around this problem in some way? Is it necessary for the LayerSwitcher to subscribe to all generic `change` events?

**Comment by Viglino** [comment]
The LayerSwitcher has to listen to changes on the LayerGroup of the map. Unfortunately this includes changes when adding features to a layer.
To avoid flickering the events are queued when adding many features but there is no delay available in the API. I've added a `drawDelay` option in the control to handle this (in the constructor or with the set function). This will delay the redraw that will be called once when no events are fired.
Using a large delay may cause bad user experience and you have to adjust the value to your data.
````javascript
// redraw every .1s
switcher.set('drawDelay',100);
````

**Comment by severinstrobl** [comment]
Thanks for the quick fix, this does indeed improve the behavior dramatically. I wonder whether it would be a viable option to register the event handler only for specific `change` events in OL5, such as, `change:layers` or `change:visible` of the layer group?
