### ISSUE TITLE
[v2] Split interaction ReferenceError

### ISSUE THREAD

**Issue by petrleocompel** [Viglino/ol-ext#253]
in interaction Split.js are 2 bugs, they are fixed in version 3 but not in version 2. (v3 is not compatibile with ol v3)

```
ReferenceError: features is not defined
    at new ./node_modules/openlayers-ext/dist/ol-ext.js.ol.interaction.Split (ol-ext.js:9411)
```

And if you fix this reference error then if you send emtpy collection is raised error in function getClosestFeature.

**Comment by petrleocompel** [comment]
Created fix https://github.com/petrleocompel/ol-ext/tree/v2.x
And asking for release

**Comment by Viglino** [comment]
Sorry I don't maintains v2.
You should consider switching to ol v4.6.5 the gap is not so important and you should succeed. The v4 is more stable and has more functionalities. The v6 is on the rail...

**Comment by petrleocompel** [comment]
Unfortunately It’s not possible to switch for our app. 😓 So if you wouldn’t release version for us we will have to make our own version release.

**Comment by petrleocompel** [comment]
No actual response. Closing issue.
Forked your project to maintain old version. It's not ideal solution but i had no other choice.
