### ISSUE TITLE
[IE11] Font style example doesn't work on IE11 envirionment

### ISSUE THREAD

**Issue by sanak** [Viglino/ol-ext#254]
Font style example (https://viglino.github.io/ol-ext/examples/style/map.style.font.html) doesn't work on IE11 environment.

The error happened at the following parts.  

1. SCRIPT1002: Syntax error
   ol-ext.js, line 22300 character 26
   ```
   geoms.forEach((g) => {
   ```

2. SCRIPT5007: Unable to get value of the property 'addDefs': object is null or undefined
   FontMakiDef.js, line 7 character 1
   ```
   ol.style.FontSymbol.addDefs ({
   ```

**Comment by Viglino** [comment]
Hello,
Thanks for the feed back: an arrow function remains in the code (IE is not ES6 compatible)
The example seems to work now.

**Comment by sanak** [comment]
@Viglino Thanks for quick fix!
I confirmed that the Font style example works on IE11 environment.
