### ISSUE TITLE
Later switcher with multiple headers

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#255]
Hello,
It is necessary to add some controls like filter  , show/hide opacity bar, show hide all layers etc. I found an example with show/hide all layers . 
In the same way I tried to add some new functions / checkboxes switcher.setHeader($('<div>').append(button1).get(0)).
switcher.setHeader($('<div>').append(button2).get(0)).
, but I think my headers conflicts with each other or I did it wrong.
Is it possible to create multiple headers for layer switcher ?
Is it possible to create the buttons inside layer switcher ?

BR,

**Comment by Viglino** [comment]
Hello,
The LayerSwitcher is fully customisable using css or js.
- the [example](http://viglino.github.io/ol-ext/examples/control/map.switcher.html) show how to hide the opacity. You can also add the the checkbox in the header.
- the [filter example](http://viglino.github.io/ol-ext/examples/control/map.switcher.filter.html) show how to filter layers dynamically
- you can add some button into the layer list using the `drawlist` event (see [example](http://viglino.github.io/ol-ext/examples/control/map.switcher.html)). The handler will be called each time the list is drawn so you can customize it on the fly.

You have to set the complete header in one shot: calling `setHeader` twice will remove the first header, but you can place a generic element in the header to handle it later:
````javascript
// Create a header
var header = $('<div>');
switcher.setHeader(header.get(0)) ;
// Add some stuff to the header
header.append(button1);
header.append(button2);
````

To add something into the list:
````javascript
switcher.on('drawlist', function(e) {
  // the current layer
  var layer = e.layer;
  // the current list element
  var li = e.li;
  // Add something to it
  $(e.li).append(element);
});
````
@+

**Comment by Dkkemaries** [comment]
Thanks. It works.

Just one "stupid" question : How remove default button style (layers switcher control icon)  for button1 and button2 ?
I tried to remove all styles for this buttons , but unsuccessfully

**Comment by Viglino** [comment]
It's a bug: the layerswtcher icons apply to all buttons in the switcher.
I've change to apply the icon only to the first control button in the last commit.

**Comment by Dkkemaries** [comment]
yes. it works 

Thanks!!!

**Comment by Dkkemaries** [comment]
Hello, 
I found that  there is no fixed positions for header , for example when the  user scrolls down the layer list , the search box slides up. May be it is possible to fix this?

I tried to change the header position to fixed ,but in this scenario the header located outside the switcher

,Br

**Comment by Viglino** [comment]
Fixed div in a div is quite tricky.
The container have to have a fixed size. If its possible to you, I think you can place the header as fixed in it.

**Comment by Dkkemaries** [comment]
Hello, yes I already made something like his. 
Thanks , for this great library  
BR,
