### ISSUE TITLE
Ability to select custom vectors

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#256]
Hello, 
is it possible to create dropdown list with vectors for select feature ? For example I have 5 vectors ,  with different attributes and it would be nice to switch between them to select features,  but in current demo I can use only one vector.
(http://viglino.github.io/ol-ext/examples/control/map.control.select.html)

BR,

**Comment by Viglino** [comment]
Hello,
You can use the ol/Overlay/PopupFeature that provide a popup with a list of selected features you can browse.
See example: http://viglino.github.io/ol-ext/examples/popup/map.popup.feature.html
@+

**Comment by Dkkemaries** [comment]
Hello, 
yes, this is a case .
 But I found that control select I can use for selecting multiple features,for example, if  I want to select  all features with height>50 . But  if I want to select another attributes form another vector , than I need to change source .

**Comment by Viglino** [comment]
Normally `ol/control/Select` accept an array of sources as as source option, thus you don't have to change the source the control will search inside all sources.
Anyway, if you want to change the source you can use the `setSource()` method of the control to set another source (or array of sources).
@+

**Comment by Dkkemaries** [comment]
Solved, thanks!!
