### ISSUE TITLE
Add layer to group

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#257]
Hello,
is it possible dynamically to add layer in layer group , that I created earlier? Something like 
var layerGroup=new ol.layer.Group({ title:'custom'})
layerGroup.addLayer() ?

BR,

**Comment by ThomasG77** [comment]
An answer

```javascript
var layerGroup = new ol.layer.Group({ title:'custom'})
var layerGroupCollection = layerGroup.getLayers();
// To add at the end
layerGroupCollection.extend(yourLayer);
// To add at a particular position if already other layers in the group
layerGroupCollection.insertAt(yourIndex, yourLayer);
// All other methods available from 'layerGroupCollection' are from https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html
```

Your question is not related to ol-ext but to Openlayers itself.
So, after answering, if it's OK for you, can I close the issue?

**Comment by Dkkemaries** [comment]
Sorry , my bad . I did't think about from this perspective . 
Thanks, for answer and link!
