### ISSUE TITLE
Hexbins "point" not working in example

### ISSUE THREAD

**Issue by Chris1234567899** [Viglino/ol-ext#259]
The hexbin example breaks if you choose "point" for the style function.
I digged into it and it seems the line:
`geometry: f.get("center")`
in the style function throws an error. Maybe this worked in an earlier openlayers version.

You could switch it to

```
import * as extent from "ol/extent";
...
 let _extent = f.getGeometry().getExtent()
        return	[ new Style({
          image: new RegularShape.default({
            points: 6,
              radius: radius,
              fill: new Fill({ color: [0,0,255,1] }),
            }),
            geometry: new Point(extent['getCenter'](_extent))
          })
...
```
to solve it.

**Comment by Viglino** [comment]
Thanks!
The center is already defined in the feature but as coordinate...
`geometry: new Point(f.get('center'))`do the trick 😄
