### ISSUE TITLE
Creating vector objects by coordinates.

### ISSUE THREAD

**Issue by slavas62** [Viglino/ol-ext#261]
Hello! I am going to use ol-ext to develop applications. Will the possibility of creating vector objects by coordinates entered manually or from a file be further implemented?

**Comment by ThomasG77** [comment]
You don't really need ol-ext for this intent. Normally, knowing OpenLayers, JavaScript and HTML is enough to do this but I don't know if it should be a dedicated component from @Viglino viewpoint

**Comment by Viglino** [comment]
Look at the [Openlayers example page](https://openlayers.org/en/latest/examples/).
The GeoJSON example show how to create vector with a [GeoJSON](https://en.wikipedia.org/wiki/GeoJSON) file : https://openlayers.org/en/latest/examples/geojson.html

**Comment by slavas62** [comment]
Thanks for the advice. But I keep in mind creating a new ol.control for manually entering coordinates and at the same time drawing an object on the map.
