### ISSUE TITLE
problems with "ol.filter.Mask and ol.featureAnimation.Fade"

### ISSUE THREAD

**Issue by zmdhfjj** [Viglino/ol-ext#264]
Use ol.filter.Mask and ol.featureAnimation.Fade . When the animation works,the mask fade together.

**Comment by Viglino** [comment]
Yes the animation is drawn on top of the layer and is not concerned by the mask (or by any other layer options such as opacity).
I'll try to see if I can add an option to take it into account when animating...

**Comment by Viglino** [comment]
Hello,
I've added a new parameter `useFilter` in `animateFeature` to apply the filter of the layer to the animation.
This should work now.
@+

**Comment by zmdhfjj** [comment]
> Hello,
> I've added a new parameter `useFilter` in `animateFeature` to apply the filter of the layer to the animation.
> This should work now.
> @+

Hello,thanks for reply.It works.However,the layerSwitcherImage's p element fades too.I am not a front-end engineer with limited ability to find out why.

**Comment by zmdhfjj** [comment]
> Hello,
> I've added a new parameter `useFilter` in `animateFeature` to apply the filter of the layer to the animation.
> This should work now.
> @+

Hello,thanks for reply.It works.However,the layerSwitcherImage's p element fades too.I am not a front-end engineer with limited ability to find out why.

**Comment by zmdhfjj** [comment]
> Hello,
> I've added a new parameter `useFilter` in `animateFeature` to apply the filter of the layer to the animation.
> This should work now.
> @+

Thanks for reply.It works.
