### ISSUE TITLE
Double selection in the transform 

### ISSUE THREAD

**Issue by byzheng** [Viglino/ol-ext#266]
Step to reproduce this problem.

Add codes to this example: http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html

```
$.each(vector.getSource().getFeatures(),function(k,v){
	   interaction.select(v, true);
	})
	interaction.select(vector.getSource().getFeatures()[0], true);
	map.addInteraction(interaction);
```
The first feature is selected twice. This situation could happen when user select feature in the map, and then call select function in the js script. 

Problem: The topology of all features are changed

Before move the centre of selection:

![image](https://user-images.githubusercontent.com/1657381/56225255-52bcde80-60b4-11e9-9064-a20844c10239.png)

After move the centre of selection

![image](https://user-images.githubusercontent.com/1657381/56225283-65371800-60b4-11e9-83a2-6624f70adac0.png)

**Comment by Viglino** [comment]
Yes, if a feature is selected twice the transform apply twice...
It's up to you to use a mechanism to select the features only once...

**Comment by byzheng** [comment]
Thanks @Viglino. Does it document in some place? It is confusing to me at the first time to use?
