### ISSUE TITLE
Show notification at the top right corner

### ISSUE THREAD

**Issue by byzheng** [Viglino/ol-ext#268]
Is it possible to change the position of notification? e.g. top right corner. 

I try to overwrite css, but seems can only put at the top center.

**Comment by Viglino** [comment]
Hello,
The css is a bit complicated due to the animation and transform operation to center the div.
Here is an example to put it on the top right corner: https://codepen.io/viglino/pen/MRPvwP

**Comment by byzheng** [comment]
@Viglino Thanks it is working for me now.
