### ISSUE TITLE
new line in ol.style.Text is ignored while zooming

### ISSUE THREAD

**Issue by 10lojzo** [Viglino/ol-ext#270]
When defining the text style with new line "\n" in text attribute, the text appears inline while zooming, both in cluster and original feature.

text: new ol.style.Text( {	text: size.toString() + "\nnew line", fill: new ol.style.Fill( {	color: '#fff' }) })

I tweaked this example changing just the code above.
http://viglino.github.io/OL3-AnimatedCluster/

**Comment by Viglino** [comment]
Hello,
The lib use the Openlayers drawFeature (ol/render/VerctorContext.drawFeature(feature, style)). It seems this function doesn't care the new line when drawing...
I'll try to investigate but the problem is more related to the core Openlayers function than to the lib itself.
@+

**Comment by novumcoder** [comment]
The vector label example seems to work. But i dont understand what is different there. https://openlayers.org/en/latest/examples/vector-labels.html

**Comment by Viglino** [comment]
The animation don't draw feature in a layer but uses a VectorContext to draw the text when animating.
It seems this don't car of the newline...

**Comment by 10lojzo** [comment]
Do you think it is possible to commit this to openlayers bugtracker?

**Comment by Viglino** [comment]
I don't know if it is an issue or if its up to the VectorContext to handle the \n.
I'll try to test if I can find workaround to do it...

**Comment by Viglino** [comment]
Hello,
I've added support for new lines when animating the cluster in the last commit.
There may be some offsets when rendering the but it will do the job in most cases.

**Comment by novumcoder** [comment]
Cool. That looks way better now. Thanks

**Comment by 10lojzo** [comment]
Perfect, works on example provided. 
When I update the new ol lib with animatedcluster in my project I will let you know.

Thanks very much.
