### ISSUE TITLE
ol.source.Overpass limit to an area?

### ISSUE THREAD

**Issue by damjang** [Viglino/ol-ext#271]
Is it  possible with ol.source.Overpass limit to an area and not view?
Something like this:
https://overpass-turbo.eu/s/IEU

Thank you

**Comment by Viglino** [comment]
The source is an [ol.source.Vector](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector.html) and you can use any loading strategy you want to load data in the source using the `options.strategy` in the constructor. 
Thus, you can use a fixed bbox to load only a particular area at ones, regardless of the current view.

````javascript
// Fixed bbox
var bbox = [259293, 6248822, 263115, 6251688]
// Overpass vector layer 
var vectorSource = new ol.source.Overpass({
  filter: [ 'highway=bus_stop' ], 
  // Limit to fixed bbox regardless of the current extent
  strategy: function(extent, resolution){ 
    return [ bbox ];
  }
});
````

**Comment by damjang** [comment]
Thank you for the answer. Yes, I know of bbox, but I need a not rectangle bounding box.

**Comment by ThomasG77** [comment]
I'm not sure using the component is the best way to achieve your goal https://codepen.io/anon/pen/EzYZjL
You can see a solution using only raw calls to Overpass API without the component. I do spatial filtering using a polygon here.

The current ol-ext component `ol.source.Overpass` would need changes to add a filter "poly" for each couple key value provided but I'm not sure @Viglino wants to head this way (!?)

PS: be careful, the poly filter in Overpass expect a `latitude1 longitude1 latitude2 longitude2 latitude3 longitude3 latitude4 longitude4 latitude1 longitude1` (couple of y x coordinates) so coordinates are inverted compared to Openlayers that used couple of x y coordinates.

**Comment by damjang** [comment]
I use your raw calls to Overpass API and work ok. Thank you!
