### ISSUE TITLE
Refresh LayerSwitcher 

### ISSUE THREAD

**Issue by skyval** [Viglino/ol-ext#272]
Hello,
Is it possible to refresh LayerSwitcher?
I have a service that dynamically append  baselayers through interval and ajax and put in layergroup, but LayerSwitcher does not understand that there is a new layers in the group until I press checkbox or until destroy LayerSwitch object and recrete it.

This is what I need for a map that is used for orienteering. Originally, it would not be possible to see the area, after a certain period of time.

Example:
```
  let source = JSON.parse(layer.base_layer_source);
        this._baseLayersGroup.getLayers().array_.push((new Tile({
                title: layer.base_layer_name,
                visible: layer.base_layer_default,
                baseLayer: true,
                source: new classes[source["class"]](...source["params"]),
            })
        ));

        this._map.removeControl(this._layerSwitcher);
        this._showLayerSwither(); // Create a new instance

```
Is there a better way?

**Comment by Viglino** [comment]
Hello,
You should not access private attribute of the LayerGroup (`array_`) but the `push()` method of the [Collection](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html) instead.
ie.
````javascript
this._baseLayersGroup.getLayers().push((new Tile({...
````
instead of
````javascript
this._baseLayersGroup.getLayers().array_.push((new Tile({...
````
The LayerSwitcher should catch the event fired by the `push` method to update the list.
@+

**Comment by skyval** [comment]
Thank you! That's my fall.
Now is workig well. I think I tested the push method, but maybe I was wrong somewhere else.
You do a great job!
