### ISSUE TITLE
Set modify the center when scaling as default [ol.interaction.Transform]

### ISSUE THREAD

**Issue by Giancarlo91** [Viglino/ol-ext#273]
Hello, instead to use Ctrl key, how could I set modify the center when scaling by default?

**Comment by Viglino** [comment]
You can use the [modifyCenter option](http://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html) at creation with a function (as [ol/events/condition](https://openlayers.org/en/latest/apidoc/module-ol_events_condition.html)) that takes an ol.MapBrowserEvent and returns a boolean to apply scale & strech from the center.
The default tests Ctrl key but you can create your one one.
ie.
````javascript
var isCorner = true; // use opposite corner to scale/stretch, (false = use center);
var modifyInteraction = new ol.interaction.Modify({
  modifyCenter: function(){ return isCorner; })
})
````

**Comment by Giancarlo91** [comment]
Thank you very much!!
