### ISSUE TITLE
ol.control.Print -> SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by damjang** [Viglino/ol-ext#274]
I'm trying to implement ol.control.Print to my map but got:
```
Error: SecurityError: The operation is insecure.
Source File: https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.js
Line: 6441
```

The example on ol-ext work ok, but my implementation is fault. Can someone take a look to my test [map](http://www.damjan.net/map3/index_v3a+mod.html)

 Thank you in advance!

**Comment by ThomasG77** [comment]
Not related directly to ol-ext. Trying to print from your example using Google Chrome Dev Tools, I got a more clear answer.

> Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
>     at HTMLCanvasElement.toDataURL (<anonymous>:209:23)
>     at ol.control.Print.<anonymous> (https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.js:6441:28)
>     at e (https://openlayers.org/en/latest/build/ol.js:1:22972)
>     at e.dispatchEvent (https://openlayers.org/en/latest/build/ol.js:1:24493)
>     at e.dispatchRenderEvent (https://openlayers.org/en/latest/build/ol.js:7:145963)
>     at e.handlePostRender (https://openlayers.org/en/latest/build/ol.js:7:92955)

You are trying to add a lot of layers. Some of them have issues with CORS. To debug, comment most of the layers in:

```
		new ol.layer.Group({
			title: 'Mappe base',
			layers: [
				hillshade_lidar,ortofoto_pc,ctrn5000c,ctrn5000g,
				mapbox_sat,
				googleLayerHybrid2,googleLayerSatellite,googleLayerRoadmap,//googleLayerRoadNames,googleLayerHybrid,googleLayerTerrain,googleLayerOnlyRoad,
				bing_road_st,bing_aerial,//bing_road_dy,bing_hybrid
				opentopo,osm
			]
		}),
		new ol.layer.Group({
			title: 'Sovrapposizione',
			layers: [
				hillshade_lidar_t,regione_fvg,comuni,qu5000,ctrn5000c_t,grotte,grotte_osm,grotte_nuove
			]
```
I would keep only OSM layer as I know it works and try again to print
then add each layer to troubleshot the issue. Then use a proxy for layers I don't manage to set CORS headers. Without this, you will not be able to print this way (using canvas at least)

**Comment by mike-000** [comment]
Even if the layers are CORS enabled the crossOrigin option will be needed in the sources, except for ol.source.OSM() or ol.source.Bing() which default to cross origin.
All the ol.source.XYZ ol.source.TileImage ol.source.ImageWMS and ol.source.TileWMS sources will need the crossOrigin: 'anonymous' option adding.  If any are not CORS enabled you will see a load error on the console and a proxy will be needed.  Also as you are running from https: all http: source urls must be changed to https: or you must use as proxy if https: isn't supported.
