### ISSUE TITLE
ol-ext Control Bar and function in the Controller

### ISSUE THREAD

**Issue by GianMen91** [Viglino/ol-ext#278]
I am using the ol.control.Bar() and I would like to give to my function the value that I have in html:

```
var mainbar = new ol.control.Bar();
var me = this;

var firstFloor = new ol.control.Button (
{
    html: '1',
    handleClick: function () {
          me.getController().updateImage();
    }
});
```

There is somehow a way to give to the function a value that is initialized in the button? or something like html.getValue?

**Comment by Giancarlo91** [comment]
Sorry I closed by mistake

**Comment by Viglino** [comment]
Hello,
The `handleClick` function is a classical function and can access every variable in the scope.
You can use the getter and setter to get information on the button as any ol control:
````javascript
var firstFloor = new ol.control.Button ({
    html: '1',
    handleClick: function () {
       // get var
      var i = firstFloor.get('my_var');
      // get inner text of the button (1)
      var content = firstFloor.element.innerText; // 1
      // do something
       me.getController().updateImage();
    }
});
firstFloor.set('my_var',1);
````

**Comment by GianMen91** [comment]
Ah ok, thank you! =D I just don't understand, why it doesn't work if I want to use in this kind of context:

```
 var indexFloor = 4;
 while(indexFloor > 0){
        var levelButton = new ol.control.Toggle({
                   html: indexFloor.toString(),
                   onToggle:  function () {
                        var content = levelButton.element.innerText;
                         me.getController().updateImage(content);
                    }
             });
             mainbar.addControl (levelButton);
             indexFloor--;
};

```
I want to create 4 buttons dinamically and each of them should have the function update the image. Update image should have as parameter the value of html of the relative button. So the four button with different html (1,2,3,4) are created without any problem but when I click on one of them  the function update image recevice only the value of the last button insert.  It should not receive a different value depending on the button I click, using "element.innerText"?

**Comment by Viglino** [comment]
In this context, the scope of levelButton variable is global and it is incremented in the while loop : at the end its value is the value of the last button. 
You have to use a function to create a scope for this variable (level in the example above).
````javascript
// Function with its level context
function addButton(level) {
  var levelButton = new ol.control.Toggle({
    html: level,
    onToggle:  function () {
      me.getController().updateImage(level);
    }
  });
  mainbar.addControl (levelButton);
}
// Insert buttons
var indexFloor = 4;
while(indexFloor > 0){
  addButton(indexFloor);
  indexFloor--;
};
````

**Comment by GianMen91** [comment]
Ah ok, I get it. Thank you very much!
