### ISSUE TITLE
EditBar cannot modify GeometryCollection

### ISSUE THREAD

**Issue by mattbuff** [Viglino/ol-ext#279]
ol.control.EditBar does not allow vertices within GeometryCollection features to be selected by mouse click so they cannot be modified. Vertices of features of all other geometry types can be selected and modified.

**Comment by Viglino** [comment]
The ol/contol/editBar uses the core [ol/interaction/ModifyFeature interaction](https://github.com/Viglino/ol-ext/blob/master/src/interaction/ModifyFeature.js). This is a cancelable interaction but it doesn't support GeometryCollection...

**Comment by mattbuff** [comment]
Hello,
Thank you for the explanation. Is there a possibility that the ModifyFeature interaction could be extended to support GeometryCollection?

**Comment by Viglino** [comment]
I'll try to see what can be done.

**Comment by Viglino** [comment]
In the last commit, ModifyInteraction now support GeometryCollection!
Tell me if it works for you...

**Comment by mattbuff** [comment]
It works. Thank you!
