### ISSUE TITLE
ol.control.Print: Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by quangtt2016** [Viglino/ol-ext#280]
When I call printControl.print({ imageType: 'image/jpeg'}), this error occured:

![image](https://user-images.githubusercontent.com/20198693/57587540-98908980-7530-11e9-9be7-194617bd44e5.png)

From Google, it is said that canvas must be set crossOrigin = "Anonymous".
Please help me resolve this.

**Comment by Viglino** [comment]
Hello,
The issue is on your layer itself: you have to make sure the sources are created with a `crossOrigin` option set to `"anonymous"` to let the browser get pixel on it.
See #274
See [ol doc](https://openlayers.org/en/latest/apidoc/module-ol_source_TileImage-TileImage.html).
@+
