### ISSUE TITLE
DBPedia layer (question)

### ISSUE THREAD

**Issue by SeussCZ** [Viglino/ol-ext#281]
Hello, i want to try your [ol-ext: DBPedia layer](http://viglino.github.io/ol-ext/examples/layer/map.dbpedia.html) in my country. Is there some guide for this, how to get GEOJSON ([your case](https://github.com/Viglino/ol-ext/blob/master/examples/data/dbpedia.json)) from SPARQL? Thank you

**Comment by Viglino** [comment]
Hello,
You have to find your DBPedia endpoint, something like : https://dbpedia.org/sparql or http://fr.dbpedia.org/sparqlEditor/index.html in my case. Then you can look and choose the output format (and the syntax to use).
NB: DBPedia is not concerned by GeoJSON, the best you can have is a JSON output. You have to transform it into GeoJSON.
PS: in the example you can use the `save()` function to download the layer content in geoJSON.

**Comment by Viglino** [comment]
PS you can use the example and the french endpoint to get inflammations as is:
1. open the developer tools in your browser
2. to change the language (and reload): tip in the console
````javascript
vectorSource._lang='en'; vectorSource.clear()
````
3. when loaded, tip
```javascript
save();
````
Not all languages are supported...

**Comment by SeussCZ** [comment]
Im sorry for my stupid question, but do you know any easy way (video tutorial or something else) how to transform generated JSON to geoJSON? 
I have this simple [JSON](https://pastebin.com/qY31ipc3) actually, but I have no idea how to tranform it to geoJSON. Thank you so much for answer.

**Comment by Viglino** [comment]
Formally a GeoJSON is already a JSON file, so there is little tools to do that (if you can manipulate GeoJSON you can manipulate JSON).
There are some utilities to convert to GeoJSON (see http://2geojson.com/) but not from JSON.
You can try converting JSON to CSV then CSV to GeoJSON.

**Comment by ThomasG77** [comment]
A recipe
```
var json = your_json_like_in_pastebin;
console.log({
  "type": "FeatureCollection",
  "features": json.results.bindings.map(el => {
    return {
      "type": "Feature",
      "properties": {
        s: el.s.value
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          +el.long.value,
          +el.lat.value
        ]
      }
    }
  })
})
```
