### ISSUE TITLE
Control buttons not showing correctly in Angular

### ISSUE THREAD

**Issue by ZinnerRep** [Viglino/ol-ext#282]
Hello,

I added ol-ext to my angular project and I imported the ol-ext style:
```
"styles": [
"node_modules/ol-ext/dist/ol-ext.css"
]
```
In my component.ts I imported Buttons and I adapted the buttons adding code for angular
```
import Button from 'ol-ext/control/Button';
...
// Add a custom push button with onToggle function
        const hello = new Button(
            {
                html: '<i class="fa fa-bookmark"></i>',
                className: "hello",
                title: "Hello world!",
                handleClick: function () {
                    info("hello World!");
                }
            });
        this.map.addControl(hello);
        
        // Add a save button with on active event
        const save = new Button(
            {
                html: '<i class="fa fa-bookmark"></i>',
                className: "save",
                title: "Save",
                handleClick: function () {
                    info("Center: " + this.map.getView().getCenter() + " - zoom: " + this.map.getView().getZoom());
                }
            });
        this.map.addControl(save);

        // Show info
        function info(i) {
            let selected = document.getElementById('info');
            
                selected.innerHTML = i;
        }

```
![image](https://user-images.githubusercontent.com/40530313/57774489-30959b00-770a-11e9-9811-05bec22512e9.png)

but in the map I see only the default ol buttons, the ol-ext buttons are hidden and can only be shown in the wrong position when searched from source code.

![image](https://user-images.githubusercontent.com/40530313/57774605-7eaa9e80-770a-11e9-98c9-26393b11a7ef.png)

**Comment by Viglino** [comment]
I think is about the Angular ViewEncapsulation. The imported css is scoped to the component to prevent css collisions (in your screenshot, the [_ngContent-xxx]). But the buttons are inserted without this mechanism and are not scoped.
You have to insert the ol-ext style as global without this encapsulation (the same way you've done for the ol style that seems to run).
In [this example](https://github.com/Viglino/ol-ext-angular) the style is added with `encapsulation: ViewEncapsulation.None` in the [map component](https://github.com/Viglino/ol-ext-angular/blob/master/src/app/map/map.component.ts).

**Comment by ZinnerRep** [comment]
Thanks for responding, I've already tried to add those buttons in [this example](https://github.com/Viglino/ol-ext-angular) and I've got the same result. And I've used the same method to import ol style and ol style are working fine. In [this example](https://github.com/Viglino/ol-ext-angular) the mark button is working fine but the ones I added are not:
```
  /** Add the control to the map
   */
  ngOnInit() {
    // Get the current map or get map by id
    const map: OlMap = this.mapService.getMap(this.mapidService || this.mapId);
    // Get the target if outside the map
    const target = this.elementRef.nativeElement.parentElement ? this.elementRef.nativeElement : null;
    // Create the control
    const mark = new BookmarkCtrl({ target: target });
    map.addControl(mark);
    // Add a custom push button with onToggle function
    const hello = new Button(
      {
        className: "hello",
        title: "Hello world!",
        html: '<i class="fa fa-bookmark"></i>',
      });
    map.addControl(hello);

    // Add a save button with on active event
    const save = new Button(
      {
        className: "save",
        title: "Save",
        html: '<i class="fa fa-bookmark"></i>',
      });
    map.addControl(save);
  }
```

**Comment by ZinnerRep** [comment]
The way I got around this problem was:
Copy/past ol-ext.css to a styles folder inside the pages folder (src/app/pages);
I changed the ol-ext.css file extinction from .css to .scss (ol-ext.scss);
I included the style as global in my component.ts file with the help of `encapsulation: ViewEncapsulation.None` :
```
// Include ol style as global
    encapsulation: ViewEncapsulation.None,
    templateUrl: './map.component.html',
    styleUrls: ['map.component.scss',
        '../styles/ol-ext.scss'],
```

**Comment by Viglino** [comment]
I think you can link directly to the node _module css.

**Comment by ZinnerRep** [comment]
Actually it's not possible in my case as I am using scss based angular, and I can't import css files I need to change the extension. And when you change the extensions of ol-ext.css to ol-ext.scss inside node_modules errors arise.

**Comment by reachnivi** [comment]
I am facing the exact same issue. Could not resolve it till now.
