### ISSUE TITLE
LayerSwitcher ['click','hide','show','toggle'] event ?

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#284]
i want use this way:

`            this.switcher.on(['click', 'toggle', 'hide', 'show'], (x: ol.control.LayerSwitcherEvent) => this.switcherClick(x));`

to implement this:

`        switcherClick(x: ol.control.LayerSwitcherEvent) {
            console.log('switcherClick ', x);
            if (this.contextmenu.isOpen())
                this.contextmenu.close();
        }`

;

but like it doesn't work;

so, i implement on this way:

`            this.switcher.button.addEventListener('click', (x: any) => this.switcherClick(x));`
;

it's work , but doesn't like what i thought.

**Comment by Viglino** [comment]
Hello,
The control doesn't implement such events but it could be a good enhancement.

**Comment by Viglino** [comment]
I've added a toggle event fired when the switcher is open/close. 
````javascript
  switcherCtrl.on('toggle', function(e) {
    console.log('Layerswitcher is '+( e.collapsed ? 'collapsed' : 'open'));
  });
````

**Comment by TownTowner** [comment]
Thank you!!!
