### ISSUE TITLE
Bar getBar() , getChildControlsByName() ??

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#287]
Hi,

it's likely the **ol.control.Bar** has no **getBar()** function and **getChildControlsByName()** or **getAllControlsByName()** witch could get children controls , 
like the jQuery's $('.class').find('div').

Thanks.

**Comment by Viglino** [comment]
Hi,
**ol.control.Bar** allready has a **getControls()** method to get all controls inserted in the bar, a **getActiveControls()** method to get the active controls (ie. controls associated with an active interaction) and a **getControlsByName()** method.
@+

**Comment by TownTowner** [comment]
Hi ,
i mean this:

`
var sub1Control=new ol.control.Toggle({
                    name:'**sub1C**',
                    html: "2",
                    onToggle: function(b) {
                        info("Button 2 " + (b ? "activated" : "deactivated"));
                    },
                });

var sub1 = new ol.control.Bar({
            toggleOne: true,
            controls: [sub1Control]
        });

var mainbar = new ol.control.Bar({
            controls: [
                new ol.control.Toggle({
                    name:'main',
                    html: '0',
                    bar: sub1,
                    onToggle: function() {
                    }
                })
            ]
        });
`
is it OK to get sub1Control like **mainbar.getControls()** or **mainbar.getControlsByName('sub1C')** ??

ol-ext @version v3.1.2.

**Comment by Viglino** [comment]
No mainba only access to its controls (sub1) you have to get sub1C from sub1.
`sub1C.getControlsByName('sub1C') `
This:
````javascript
var sub1 = new ol.control.Bar({
  name: 'sub1',
  toggleOne: true,
  controls: [sub1Control]
});

var mainbar = new ol.control.Bar({
  controls: [
    new ol.control.Toggle({
      name:'main',
      html: '0',
      bar: sub1,
      onToggle: function() {
      }
   })
  ]
});

// Get sub1C
mainbar.getControlsByName('sub1')[0].getControlsByName('sub1C') ;
````

**Comment by TownTowner** [comment]
OK.
Thank you !!
