### ISSUE TITLE
PopUpFeature - No support for Cluster

### ISSUE THREAD

**Issue by DebuggerAK** [Viglino/ol-ext#292]
Structure of cluster feature:
Attribute: 'features' <- array of features in feature attributes

Is it possible to hide attributes with no content or undefined attributes? 
Workaround (not nice):
```
template: {
        title:
          function(f) {
           if (f.get(FEATURE_FIELD.IDENTIFIER) === undefined) {
              f.set(FEATURE_FIELD.IDENTIFIER, '-');
            }
},
attributes: {
          'identifier': { title: 'Bezeichnung' }, // or callback function?
     }
}
```

Thank you!

Or I push some features? We do not want to create a copy but support the library!

**Comment by Viglino** [comment]
I'll try to add a value function to handle calculated attributes ASAP.
Something like:
````javascript
template: {
  title: 'name',
  attributes: {
    calculated_1: {
      title: 'my value',
      value: function(f) {
        return f.get('pop')/100;
      }
    }
  }
}
````

**Comment by Viglino** [comment]
Added in the last commit.

**Comment by DebuggerAK** [comment]
Thank you! When will always appear a release?

**Comment by Viglino** [comment]
I'll try to publish ASAP

**Comment by DebuggerAK** [comment]
Thank you!
