### ISSUE TITLE
DrawRegular interaction problem

### ISSUE THREAD

**Issue by g-hawk** [Viglino/ol-ext#293]
Hi,
I'm using drawRegular interaction in my project; I initialize it in this manner:
```
this.drawInteraction = new DrawRegular({
        features: this.editedFeatures,
        sides: 4,
        canRotate: false
      });
```
editedFeatures is a Collection.
I also have this drawend management to manage draw mode; I want give the chance to draw single or multiple features

```
this.drawInteraction.on('drawend', (event) =>
    {
      this.activeModification = true;

      let mode:AddMode = params['mode'];

      switch (mode)
      {
        case AddMode.MULTIPLE:
          // you do not have to do anything
          break;

        case AddMode.SINGLE:
        default:
          // remove previous feature from collection
          this.editedFeatures.clear();
          break;
      }
    });
```
At the end of drawing operation I invoke a callback to read editFeatures that is empty.
With the same code, if I substitute DrawRegular interaction with Draw interaction, all works normally.
Could someone help me?
Thanks a lot.

Giuseppe

**Comment by DebuggerAK** [comment]
```
const result = new DrawInteraction({
//...
    });

result.on('drawend', event => {

          console.log(event.feature);
cosnole.log(evt.feature.getGeometry().clone());

    });
```

That works for me.

**Comment by g-hawk** [comment]
Thanks for the response

I solved manage drawstart event rather than drawend.
With Draw interaction drawend works.

Giuseppe
