### ISSUE TITLE
LayerSwitcher no options.defaultOpen option?

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#294]
Hi,
like the title, like the options doesn't has any option param that could open the layerswitcher when the map is open firstly.

Thank you.

**Comment by Viglino** [comment]
Hi,
You can use the `show()` method to open it programmatically when you want:
````javascript
  var ctrl = new ol.control.LayerSwitcher();
  map.addControl(ctrl);
  ctrl.show();
````
@+

**Comment by TownTowner** [comment]
Yeah，i know the show function (and i'm using it currently) , but it is possible to add to the options ({defaultOpen:true}) ?

**Comment by Viglino** [comment]
I've added a collapsed option on the control, default is true. Just set it to false to have the control open.

**Comment by TownTowner** [comment]
Wow~
Thank you!
