### ISSUE TITLE
Dijkstra short path does not resume after no route found.

### ISSUE THREAD

**Issue by volcomk10** [Viglino/ol-ext#296]
I have a site that takes the users location as the start of the path and they can select features for the end or toggle a button with something like "Where to pay your taxes" and find the closest place to them. If the user is at or very close to the location so that path length is zero the code stops and will not resume even when they select a feature farther away. 
This can be seen on the examples page as well, if you select the end at or right by the start you only get the green flag and the not found warning never clears.
In 95% of cases it isn't a problem but I'm making a site for summer tourist that don't necessarily know they may be at the closest park. I have it display "You are here", I clear the selected features, result, end coordinate and make sure start is still there position. It only runs the "Finish" portion of the code. It will not run the "Start" portion.
If you never select a place you are currently at it runs like a charm.

**Comment by Viglino** [comment]
There is a bug in the lib: when the start and end points are the same the finish event is fired without resetting the running var... 
I'll try to push a correction asap.

**Comment by volcomk10** [comment]
Thank you!

**Comment by Viglino** [comment]
New release is out

**Comment by volcomk10** [comment]
Works perfectly, thank you!
