### ISSUE TITLE
transform circle - stretch

### ISSUE THREAD

**Issue by hswim** [Viglino/ol-ext#297]
When we enable stretch option for circle , 
the right & left points which use for stretch make the circle bigger or smaller,
but the Up and Down points  do nothing.

**Comment by Viglino** [comment]
Circle are of a particular geometry and can't be stretched. The behavior is the same as the scale + keepAspectRatio and is only available on the X axis.

**Comment by hswim** [comment]
So , why don't you remove these points? 
This behiour looks like a bug.

**Comment by Viglino** [comment]
Hello,
I've removed the handles to stretch and rotate a circle as there are not appropriate.
@+
