### ISSUE TITLE
FontSymbol question(s)

### ISSUE THREAD

**Issue by damjang** [Viglino/ol-ext#298]
Hi to all! I have a FontSymbol problem: I use and work ok, but only after reload of the page, in first load the fontmaki or fontawesom glyph is empty (not showed). Maybe a load time/cache problem?
I have a 
`
// Redraw layer when fonts are loaded
	$(window).on("load", function(){ console.log("loaded"); <layer-name>.changed(); });
`
at the end of the code, but seems not working...
How can I resolve this problem? Here a test page with the problem:
https://www.damjan.net/map3/test3.html

The second question is, since I use the circle for glyph and a circle is already defined for form, maybe instead of loading all maki or fontawesom for only a circle, can I use the symbol defined for form also in glyph?

Thank you

**Comment by Viglino** [comment]
Window `onload` event may be triggered before the fonts are loaded and you have to test the fonts one by one using a third party library like [webfontloader](https://github.com/typekit/webfontloader).

````html
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
````
````javascript  
<!-- @use https://github.com/typekit/webfontloader -->
WebFont.load( {
  custom: {
    families: ['FontAwesome'],
    urls: ['https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'],
    testStrings: { 'FontAwesome': '\uf240' }
  },
  classes: false,
  // Clear the cache and force redraw when fonts are loaded
  active: function() {
    <layer-name>.changed(); 
  }
});
````

**Comment by damjang** [comment]
Hm, thank you. I try this script but don't work. See the same page as before for example.

How about the second question? Is it possible?

**Comment by Viglino** [comment]
It's possible. You just have to know when the fonts are loaded to set your style.
You can also use a default symbol in the current font: https://www.w3schools.com/charsets/ref_utf_geometric.asp (● or ⚫ or any other symbol ❤ - ☺) but the result will depends on the current font used in the browser (not very important for a circle).
