### ISSUE TITLE
timeline widget mismatch between pointer position and returned date

### ISSUE THREAD

**Issue by sukeshlaghate** [Viglino/ol-ext#299]
Hi Viglino,
When using timeline I observed that the date returned by tline.getDate() and the actual pointer location are not in sync. Please see the image attached .

I am using Timeline control in angular app with graduation as day and start date as 23 Jan 2019 end date as 28 Feb 2019, min date as 31 Dec 2018 and max date as 28th march 2019 following is the setting borrowed from map.control.timequake.html example.

```
 this.tline = new Timeline({
      className: 'ol-pointer',
      features: [{
        text: 2019,
        date: new Date('2019/01/01'),
        endDate: new Date('2019/02/28')
      }],
      graduation: 'day', // 'month'
      minDate: new Date('2018/12/31'),
      maxDate: new Date('2019/03/28'),
      getHTML: function(f){ return 2019; },
      getFeatureDate: function(f){ return f.date; },
      endFeatureDate: function(f) { return f.endDate }
    });
```
After initialization when I get the date from timline widget it returns a date which doesnot match with the pointer is pointing to in the widget. In this example it returns 30/12/2018 and the pointer is on 05 Feb see image

Request you to help resolve this issue. 

![Capture](https://user-images.githubusercontent.com/25061957/59712932-e2554980-922b-11e9-9f18-4bf24ec6c4d0.PNG)

**Comment by Viglino** [comment]
Hi,
Calling `tline.getDate()` just after initializing the control will return the min date rounded at pixel (here 2018/12/30) and it is the normal behavior.
The date shown on the line is wrong. You may have change it after the `getDate` or there is something wrong in the css that display the timeline.

**Comment by sukeshlaghate** [comment]
Hi,
Thank you for responding.
 I am using default css and I am not making any changes to the timeline widget, after getDate. 
I too am suspecting that there is something wrong with CSS as on scroll events the dates returned are not matching with the date shown on the line (pointer). However as mentioned earlier I am not changing any css.

Here is the code excerpt

```
  ngAfterViewInit(): void {
    this.map.setTarget(this.id);

    this.map.once('postrender', () => { this.resize(); });

    // functionality related to weather filter we are creating a timeline widget
    this.tline = new Timeline({
      className: 'ol-pointer',
      features: [{
        text: 2019,
        date: new Date('2019/01/01'),
        endDate: new Date('2019/02/28')
      }],
      graduation: 'day', // 'month'
      minDate: new Date('2018/12/31'),
      maxDate: new Date('2019/03/28'),
      getHTML: function(f){ return 2019; },
      getFeatureDate: function(f){ return f.date; },
      endFeatureDate: function(f) { return f.endDate }
    });

    this.map.addControl(this.tline);

    console.log('timeline date is -> ', this.tline.getDate().toLocaleDateString('en-GB'));
    this.tline.on('scroll', this.timeFilter.bind(this));

    // Read the weather data from server based on the time value retrieved from time line widget's 
   // current date value
    this.readWeatherData();

  }

private timeFilter(event) {
    this.dateFilter = event.date.toLocaleDateString('en-GB') + ' 12:00 AM';
    console.log(this.dateFilter);
    this.readWeatherData();
  }
```
Looking forward to hear from you.

**Comment by Viglino** [comment]
If the dates are wrong on scroll event this is a css issue: the offset position of the time line is wrong.
Do you have an online example to test?
How do you place the map in the page DOM?

**Comment by sukeshlaghate** [comment]
Hi,

Apologies for responding late. It won't be possible to extract the code and create online example. The map is placed inside a UI library card which is responsive and changes size dynamically. Whenever layout changes it calls method to update the size of the map. I guess this could also be culprit for wrong values in Timeline widget?

Also would it be possible to have an event generated for "scroll end" as on changing of date data can be fetched from server. Calling fetch on scroll would result in continuous calls to server and if data is huge it would be very costly.

Rregards,
Sukesh.

**Comment by sukeshlaghate** [comment]
Hi,

Apologies for responding late. 

It won't be possible to extract the code and create online example. 

The map is placed inside a card ( a component from UI library which is responsive) and changes size dynamically. Whenever layout changes (that is the card is resized) it calls method to update the size of the map. I guess this could also be culprit for wrong values in Timeline widget?

Also would it be possible to have an event generated for "scroll end" . Calling fetch on scroll would result in continuous calls to server and if data is huge it would not be feasible to make such calls. however if "scroll end" event is available one can fetch data from server once user ends scrolling time line.

Regards,
Sukesh.
