### ISSUE TITLE
Unable to import HexBin from HexBin.js in React project

### ISSUE THREAD

**Issue by Levrum** [Viglino/ol-ext#302]
We noticed an issue in HexBin.js when attempting to use ol-ext in one of our projects and submitted a pull request with the fix. It should allow for people using React to implement the HexBin component.

Thank you for the wonderful library!

**Comment by Viglino** [comment]
PR accepted

**Comment by Levrum** [comment]
Hello sir,

If possible, can you please publish a new version of the NPM package with this fix?

Thank you again for all your hard work on the library

**Comment by Viglino** [comment]
I'll try to publish asap.

**Comment by Viglino** [comment]
ol-ext@.1.4 is out
