### ISSUE TITLE
Dijkstra algorithm precision

### ISSUE THREAD

**Issue by regiscamimura** [Viglino/ol-ext#303]
I'm looking at the example page for the dijkstra short path implementation, and I see that if I click on points that are very near to each other, it returns "You're already there!". As I understand, for using dijkstra, you need a graph with nodes and edges. In this case, the nodes are set as arbitraries points, I mean, whatever the point you click. But it seems that when you click in two points that would be in the very same route/path/edge, you'll get that message saying you're already there. Would that be the case? 

Anyway, what I'm trying to do is to use this script to find a path between any two points, even though they might be in the same edge and as close as 10m. Any ideas on how to achieve that?

**Comment by Viglino** [comment]
The algorithm calculates a path between nodes on the graph ie. between intersections. 
When you click on the map the clicked location will be projected on the nearest intersection. It will be the start/end point. 
If you click two nearest point they will be projected on the same node and the algorithm will stop as the points are the same.

**Comment by regiscamimura** [comment]
Ah, I see, thanks for the clarification! But does the nodes includes the start and end points, which are not really intersected by other paths?

**Comment by Viglino** [comment]
Nodes are all starting and ending points of the linestrings in the source.
