### ISSUE TITLE
How to catch `drawend` for control.Toggle:interaction ?

### ISSUE THREAD

**Issue by daboudii** [Viglino/ol-ext#304]
I'm trying to perform an action on [`drawend`](https://openlayers.org/en/master/apidoc/module-ol_interaction_Draw-DrawEvent.html#event:drawend) from a Toggle interaction.

How can I catch the `drawend` for this `new ol.interaction.Draw` ?

``` 
let pedit = new ol.control.Toggle({
         html: '<i class="fa fa-map-marker" ></i>',
          title: 'Point',
          interaction: new ol.interaction.Draw({
              type: 'Point',
               source: objectLayer.getSource()
            })
 });
```

Thank you for this amazing lib.

~label Question

**Comment by Viglino** [comment]
The drawend is triggered by the draw interaction, not the control, you have to listen to the interaction events.
````javascript
// Draw interaction
const drawInteraction = new ol.interaction.Draw({
  type: 'Point',
  source: objectLayer.getSource()
});
// Listen to drawend event
drawInteraction .on('drawend', (e) => {
  /* Do something */
})
// Add a control to handle the activation
let pedit = new ol.control.Toggle({
  html: '<i class="fa fa-map-marker" ></i>',
  title: 'Point',
  interaction: drawInteraction 
});
````

**Comment by daboudii** [comment]
Thank you for your quick answer, it seems that I was quite tired last week.
