### ISSUE TITLE
Type defintions for Typescript

### ISSUE THREAD

**Issue by Siedlerchr** [Viglino/ol-ext#305]
Hi,
first of all thanks for the great library. Already used it before, but now I'm using Angular/Typescript and it would be really awesome to have type definitions.

For OpenLayers 5.x they already exist:
https://github.com/hanreev/types-ol

As your library is already very well documented, it oculd be  possible to generate the typescript definitions from jsdoc. Might need some manual tweaking, tho.
https://github.com/englercj/tsd-jsdoc

**Comment by Viglino** [comment]
I've allready try some tools to generate ts from the doc but the result was poor and invalid.
I'll try to see if this one works better...

**Comment by ValResnick** [comment]
Do you have any results yet? We are also very interested in the typings.

**Comment by Viglino** [comment]
No time to test it...

**Comment by Siedlerchr** [comment]
@ValResnick  I started to generate typings automatically and then manually fixed most errors. See #314 . Any help for the rest would be appreciated.

**Comment by Viglino** [comment]
@Siedlerchr #314 pull request makes the construction of the distribution to use in a web page crash.
The lib has to be written using vanilla js (no class or so :cry:). 
I think description can be set using jsdoc syntax instead.

**Comment by Siedlerchr** [comment]
@Viglino  In the end it should be better to have the typings as a seperate repo. e.g. as the guy did for openlayers: https://github.com/hanreev/types-ol 
In the end it should be useful to have them at the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped
You can then simply revert my PR.  It was just to make testing easier having the original code side by side.
Regarding the "class" stuff. It was just a suggestion from VS-Code. Did not want to break the js-stuff.
I will setup a new repo and give you access.

**Comment by Siedlerchr** [comment]
I now created a new repository solely for the types and invited you as collaborator @Viglino 
https://github.com/Siedlerchr/types-ol-ext

**Comment by cplasse** [comment]
> 
> 
> I now created a new repository solely for the types and invited you as collaborator @Viglino
> https://github.com/Siedlerchr/types-ol-ext

@Siedlerchr Do you plan a release for this repository to be imported with NPM like hanreev/types-ol ? It would be easier to integrate with Angular projects.

**Comment by Siedlerchr** [comment]
Yes, ideally it woul dbe automatically generated in the future. However, I have not much experience with those Definitely Typed/Typings stuff. Any help is appreciated

**Comment by Siedlerchr** [comment]
Some updates on typings over https://github.com/Siedlerchr/types-ol-ext 
We are currently fixing/aligning the types to be equal with the latest release/master.
Any help appreciated, also with providing/testing the examples.

**Comment by Viglino** [comment]
> We are currently fixing/aligning the types to be equal with the latest release/master.
@Siedlerchr Great job!

**Comment by Siedlerchr** [comment]
I have just relased https://github.com/Siedlerchr/types-ol-ext/releases version 1.3.1 which is based on ol-ext 3.2.12

**Comment by Siedlerchr** [comment]
New release 2.0.0 which uses ol's inbuilt types: https://github.com/Siedlerchr/types-ol-ext/releases/tag/2.0.0

**Comment by Siedlerchr** [comment]
New version 2.1.0 is out, Compatibility with ol-ext 3.2.26  out https://github.com/Siedlerchr/types-ol-ext/releases/tag/2.1.0
