### ISSUE TITLE
canvas control

### ISSUE THREAD

**Issue by RKatarine** [Viglino/ol-ext#306]
Hello! Something was wrong with example canvas control. CanvasScaleLine overlays itself. Please, say how I can fix this bug.
![Снимок экрана от 2019-07-02 09-51-27](https://user-images.githubusercontent.com/30527539/60490446-37bf3b00-9caf-11e9-88b8-f7b84a915e1d.png)

**Comment by mike-000** [comment]
The example is using https://openlayers.org/en/master/build/ol.js which a beta version of OpenLayers 6.  Something in a recent update by OpenLayers is causing the problem.  The CanvasScaleLine still works correctly when using https://openlayers.org/en/latest/build/ol.js (OpenLayers 5).

**Comment by Viglino** [comment]
I'll remove the test with ol6 and link back to the stable version of ol (v.5)
The problem is the canvas overlay is not clear on redraw.

**Comment by RKatarine** [comment]
Thanks for your answers
