### ISSUE TITLE
hole interaction doubt

### ISSUE THREAD

**Issue by g-hawk** [Viglino/ol-ext#307]
Hi,

hole interaction allow to draw holes into polygon.
Is it possible remove existing or drawn holes from a polygon?
Thanks.

Giuseppe

**Comment by Viglino** [comment]
I don't know any control to remove hole on a polygon...

**Comment by Viglino** [comment]
Here is delete hole example: https://codesandbox.io/embed/delete-hole-lxihd
It create a select interaction and delete hole of the selected features when select...

**Comment by g-hawk** [comment]
Hi,

thanks for the response
