### ISSUE TITLE
[Request/Question] animateFeature (pause/continue/export)

### ISSUE THREAD

**Issue by erginduran** [Viglino/ol-ext#309]
Hey, thanks for this extension. i use it with OL3 in a tracking project.
If possible,

- Do you have any examples for pause/continue animation? play/stop/isPlaying works well but i also need pause/continue at this point. i've tried to slice a route and animate again for rest but i just failed. Hope there's a way to handle it.

- Do i have any chance to export an animation as video or gif format? Or should i use an extra screen recorder app for it?

Thanks a lot!

**Comment by Viglino** [comment]
The `featureAnimation` only animates the feature but don't change its position (coordinates) or so. Stopping the animation will draw it at its initial place (see https://viglino.github.io/ol-ext/examples/animation/map.featureanimation.select.html).
If you're looking for more options to animate points on a map, look at the [ol-games](https://viglino.github.io/ol-games/examples/map.sprite.path.html) package that animates sprites.
@+

**Comment by Viglino** [comment]
No chance to export animation, you should use a third party library ([webrtc](https://github.com/webrtc), [whammy](https://github.com/antimatter15/whammy), [CanvasRecorder](https://github.com/SMUsamaShah/CanvasRecorder)...).
Or use a screen recorder.

**Comment by erginduran** [comment]
Thank you @Viglino !! ol-games works great. Also i'll check those libraries you mentioned above.
