### ISSUE TITLE
Release 3.1.3 is not compatible with openlayers 5.3.3

### ISSUE THREAD

**Issue by yoshz** [Viglino/ol-ext#310]
I accidentally upgraded from 3.1.2 to 3.1.3 resulted in:
`./node_modules/ol-ext/layer/AnimatedCluster.js
Attempted import error: 'getVectorContext' is not exported from 'ol/render' (imported as 'ol_render_getVectorContext').`

Seems like the getVectorContext is a openlayers 6.0.0 feature and I am using 5.3.3.
I would suggest to update package.json dependency with `"ol": "^6.0.0"` or create a major release of ol-ext.

**Comment by Viglino** [comment]
Which bundler are you using?
The 3.1.3 is a transition version to ol5 and ol6.
For me: `import {getVectorContext as ol_render_getVectorContext} from 'ol/render';`
Poesn't trigger an error and will result in a `undefined` var that can be tested (using parcelJS).
Yet ol v6 is not stable and can't be used as reliable dependency...

**Comment by Viglino** [comment]
Hi,
I think I can add an explicit export (using import * before) to prevent error (see last commit).
````javascript
import * as render from 'ol/render';
export default render.getVectorContext;
````
This will preserve compatibility, exporting `undefined` using ol v5.3 and the `getVectorContext` function using ol v6+.
Can you test it on your project?

**Comment by yoshz** [comment]
I have missed about it being a transition release, so sorry about that.

I have tried it but it still results in the error:
```
./node_modules/ol-ext/util/getVectorContext.js
Attempted import error: 'getVectorContext' is not exported from 'ol/render' (imported as 'render').
```

I guess wildcard import doesn't work.
I am using create-react-app which uses Webpack. Not sure how to configure it to not fail on this import line.

**Comment by Viglino** [comment]
OK `render` seems to have been imported but it test the exported var.
Let's try to add our own test before returning the function... Can you change `ol-ext/util/getVectorContext.js` with:
````javascript
import * as render from 'ol/render';
var getVectorContext = null;
if (render.hasOwnProperty('getVectorContext')) {
  getVectorContext = render.getVectorContext;
}
export default getVectorContext;
````
@+

**Comment by yoshz** [comment]
Sorry that also doesn't work. I think there is some kind of babel plugin enabled that resolves wildcard imports. 
Don't bother too much though. I will lock the version to 3.1.0 for my project.

**Comment by Bulala-liu** [comment]
Hi, I also have the problem, has it been resolved?
"ol": "5.3.1",
"ol-ext": "^3.1.4",

**Comment by Viglino** [comment]
No 
I've push a new commit to export getVectorContext using  ol@5.3 to be compatible with new version ol@6.
Can you test it on your project ?
