### ISSUE TITLE
LayerSwitcher Control CustomButtom

### ISSUE THREAD

**Issue by GarridoM** [Viglino/ol-ext#313]
Hello,

I am testing the controls, specifically the Layer switcher control example: https://viglino.github.io/ol-ext/examples/control/map.switcher.html and I have two doubts about it:

Is possible to do custom buttons for the layer?
Is any way to do that extent part will be dynamic? Because what I would like to do It is to center it to the feature that i have in each layer.

Thanks in advance!

**Comment by Viglino** [comment]
You can add your own buttons in the switcher, either in the header or as layer buttons.
You can see it working in the example.

In the header, just add an element using setHeader function (this element can be a button or contain buttons):
````javascript
// Add myElement in the header
switcher.setHeader(myElement);
````

In the layers, use the `drawlist`event to add the button on the fly:
````javascript
// Add a new button to the list
switcher.on('drawlist', function(e) {
  // The current laer
  var layer = e.layer;
  // The current <li> element
  var li = e.li;
  // Add a [?] button using jQuery in .ol-layerswitcher-buttons div
  $('<div>').text('?')
     .click(function(){
       alert(layer.get('title'));
     })
     .appendTo($('> .ol-layerswitcher-buttons', li));
 });
````
You can control what you insert using this method as you want to make it responds using your context.

**Comment by GarridoM** [comment]
Hi! Thanks for the answer. I am going to try it.

**Comment by GarridoM** [comment]
I have other question around of it.

Is it possible to add more than one controller for layerSwitcher and said what layer goes for each one?

Thanks in advance.

**Comment by GarridoM** [comment]
Hi! I have found it! Thanks a lot! It is with displayInLayerSwitcher method. Now, I am trying to know how to set the position of the control, if someone knows I am getting crazy with that.
