### ISSUE TITLE
LayerSwitcher ownerDocument error

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#317]
Hi,

When i use the layerswitcher to show it after the map rendered ,there is an error happend occasionally , i don't know is it the reason i opened the chrome extention tool , and the map is deformation (yes , i closed the tool then the map is rendered normally ), should i **listen** a map event to **show** the Switcher ??

here is the  erroe message:

`Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
    at Object.ol.ext.element.getStyle (02.ol-ext.js:329)
    at ol.control.LayerSwitcher.overflow (02.ol-ext.js:1681)
    at ol.control.LayerSwitcher.show (02.ol-ext.js:1636)`

,

here is the error ext code :

`/**
 * Get style propertie of an element
 * @param {DOMElement} el the element
 * @param {string} styleProp Propertie name
 * @return {*} style value
 */
ol.ext.element.getStyle = function(el, styleProp) {
  var value, defaultView = (el.ownerDocument || document).defaultView;//<<<<--------  THIS LINE
  // W3C standard way:
  if (defaultView && defaultView.getComputedStyle) {
    // sanitize property name to css notation
    // (hypen separated words eg. font-Size)
    styleProp = styleProp.replace(/([A-Z])/g, "-$1").toLowerCase();
    value = defaultView.getComputedStyle(el, null).getPropertyValue(styleProp);
  } else if (el.currentStyle) { // IE
    // sanitize property name to camelCase
    styleProp = styleProp.replace(/-(\w)/g, function(str, letter) {
      return letter.toUpperCase();
    });
    value = el.currentStyle[styleProp];
    // convert other units to pixels on IE
    if (/^\d+(em|pt|%|ex)?$/i.test(value)) { 
      return (function(value) {
        var oldLeft = el.style.left, oldRsLeft = el.runtimeStyle.left;
        el.runtimeStyle.left = el.currentStyle.left;
        el.style.left = value || 0;
        value = el.style.pixelLeft + "px";
        el.style.left = oldLeft;
        el.runtimeStyle.left = oldRsLeft;
        return value;
      })(value);
    }
  }
  if (/px$/.test(value)) return parseInt(value);
  return value;
};`

Thank you!

(After serveral times trial : refresh the page...)
Yes , i listened the map rendercomplete event to show the switcher , the chrom extention tool is open and the map is rendered deformationly ,but there is no error any more ( why ??? ), i'll update this issue serveral days later.

**Comment by Viglino** [comment]
Hello,
I think this is because you are trying to show the LayerSwitcher before it has been inserted in the map: the render event (map draw) is called before you call addControl...
Try to call addControl for the layer switcher before adding the event to the map (map.on('render',...)
Ill try to add a test to prevent this in the lib...

**Comment by TownTowner** [comment]
I just updated the ol-ext version to show the switcher in the map when the page rendered at first ,
and i didn't get any error between changed the switcher showing way and i updated the version .
