### ISSUE TITLE
Map pointermove event triggered LayerSwitcher drawlist event ?

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#318]
Hi,

I'm both listening the map **pointermove** event and the layerSwitcher **drawlist** event , and i found the **pointermove** event **triggered**( i dont know is it the real) the **drawlist** event , and this makes the layerSwitcher click event several seconds delay , you should click several times to select a layer , i remove the pointermove event the LayerSwitcher responds smooth.

(Others : in the drawlist event i insert a radio button , you can see the button checked status is ...)

Here is the info:

![layerSwitcher_pointermove](https://user-images.githubusercontent.com/10682896/61925399-b5205780-af9e-11e9-90b7-43d422340a8a.gif)

My **pointermove** code:

`
pointerMove(e: ol.MapBrowserPointerEvent) {
            console.log(e.type);
            let data = this.map.forEachFeatureAtPixel(e.pixel, (feature, layer) => {
                return { feature, layer };
            });
            //清空承载层
            this.selectedLayer.getSource().clear();
            let fe = data ? data.feature : null;
            if (fe && fe instanceof ol.Feature) {
                if (data.layer)
                    console.log('pointer move layer,', data.layer.get('name'));
                let html: string = fe.get('checkhtml');
                let cor: ol.Coordinate = fe.get('checkcor');
                if (html && cor)
                    this.popup.show(cor, html);
                else
                    this.popup.hide();

                //let colne = fe.clone();
                ////标签加边框
                //let style = colne.getStyle();
                //console.log('pointermove style,',style);
                //if (style && style instanceof ol.style.Style) {
                //    let stroke = style.getStroke();
                //    if (stroke) {
                //        stroke.setWidth(5);
                //        this.selectedLayer.getSource().addFeature(colne);
                //    }
                //}
            } else
                this.popup.hide();
}
`;

My **drawlist** event code :

`
drawlistFn(x: ol.control.LayerSwitcher.Event) {
            console.log('switch drawlist,');

            let layerEntity: MapLayer = x.layer.get('layer');
            if (!layerEntity)
                return;

            if (layerEntity.canEdit && layerEntity.isDefault && !this.$scope.layerId)
                this.$scope.layerId = layerEntity.id;

            if (!this.$scope.layerEntities) {
                this.$scope.layerEntities = {};
                _.forEach(this.layers, x => {
                    this.$scope.layerEntities[x.id] = { id: x.id, name: x.name, load: false };
                });
            }
            let loadBtnHtml = '';
            //if (!layerEntity.hasLoadResource)
            //    loadBtnHtml = '<div class="li-content load" ng-if="!layerEntities[' + layerEntity.id + '].load"><input type="checkbox"  name="load" ng-model="layerEntities[' + layerEntity.id + '].load"/><label ng-click="layerEntities[' + layerEntity.id + '].load=true;loadResource(' + layerEntity.id + ')">加载</label></div>';
            let editBtnHtml = '';
            if (layerEntity.canEdit)
                editBtnHtml = '<div class="li-content edit"><input type="radio" name="layerId" ng-model="layerId" value="' + layerEntity.id + '" /><label ng-click="layerId=' + layerEntity.id + ';selectLayer()">编辑</label></div>';
            let html = loadBtnHtml + editBtnHtml;
            if (!html)
                return;
            let editBtn = angular.element(html);
            //this.$scope.layerId = layerEntity.id;
            if (this.$scope.selectLayer instanceof Function == false)
                this.$scope.selectLayer = x => this.selectLayer();
            //if (this.$scope.loadResource instanceof Function == false)
            //    this.$scope.loadResource = x => this.loadResource(x);

            let ele = this.$compile(editBtn)(this.$scope);
            angular.element($(x.li).children('.li-content')[0]).before(ele);
}`;

I found the issue:**[Event handling in LayerSwitcher](https://github.com/Viglino/ol-ext/issues/252)** ， but even i set the **drawDelay** to 100 , it doesn't likes become more better .

Any suggestion?

Thank you !

**Comment by Viglino** [comment]
The problem is you modify a layer on each pointermove : 
```javascript
this.selectedLayer.getSource().clear();
```
This will trigger a change on the layer group and refresh the LayerSwitcher.
Just test before if you have to clear:
````javascript
if (this.selectedLayer.getSource().getFeatures().length) {
  this.selectedLayer.getSource().clear();
}
````
Using a `drawDelay` will prevent too many draw events: https://codepen.io/viglino/pen/ZjMYyJ

**Comment by TownTowner** [comment]
Thank you!!! MUCH better!
