### ISSUE TITLE
External Layer Switcher 

### ISSUE THREAD

**Issue by davidpiedrarojas** [Viglino/ol-ext#319]
Hello, I´m trying to use the LayerSwitcher Control, the intention is using it the external way, but I can´t display it externally. It works but only inside the map, I copy the example code but still no luck. What can I be missing?

**Comment by Viglino** [comment]
Do you have a code snippet?
The control must be define with an existing target to put in and added in a map.
````javascript
// Place LayerSwitcher in <div id="switcher">
var myElement = document.getElementById('switcher'); // or get it another way
var ls = new ol.control.LayerSwitcher({
  target: myElement
});
map.addControl(ls)
````

**Comment by davidpiedrarojas** [comment]
Thank you, this worked.
