### ISSUE TITLE
[Question] How to change position of CanvasTitle and add an image/logo with text?

### ISSUE THREAD

**Issue by erginduran** [Viglino/ol-ext#320]
Hey @Viglino, 
 I am trying to change position of ol.control.CanvasTitle and i also need to put there a logo/image on OL3. I have tried below snippet but it's just failed.

.ol-control-title {
    width:300px;
    height:120px;
    bottom: .5em;
    left: .5em;
    text-align:center:
}
And added custom class to pull it to bottom. CanvasTtile({className:"customTitle"}). But it's been failed as well.
I am also using view.animate and export as video/webm and PNG so i need something like that ol.control.CanvasTitle (canvas makes trick for me). But i should change position and background color so i can make it suitable for my current project. Something pull this title top of map but i couldn't figure it out now. Maybe there's a very basic solution but i haven't found it yet.

(Or you may help me to show Legends on canvas so i can export it as PNG or video?)

I like your libraries (ol-ext, ol-games..). Thanks a lot for both!
Greetings!

**Comment by Viglino** [comment]
The CSS for the ol-control-title define a top at 0, you have to reset it if you want to use bottom:
````css
.ol-control-title {
  width:300px;
  height:120px;
  top: unset,
  bottom: .5em;
  left: .5em;
  text-align:center:
}
````
If you want to change the color, you have to define a `style` option when creating the control (or use the `setStyle` function).

**Comment by erginduran** [comment]
Thank you @Viglino !! "top: unset;" make trick really. Now, have any chance to add icon? I tried something below but i've just failed.

        var titleControl = new ol.control.CanvasTitle({ style: new ol.style.Style({
            image: new ol.style.Icon({
                opacity: 1,
                scale: 1,
                src: '../Content/img/logo.png'
            }),
            text: new ol.style.Text({
                offsetY: 20,
                text: "Dummy Titles",
                textAlign: 'center',
                padding: [3, 5, 3, 5]
            }),
            fill: new ol.style.Fill({color: 'rgba(255,255,255,.3)', opacity: '.2'}) /*background-color*/
        })});

**Comment by Viglino** [comment]
If you want to add an icon on the canvas map you can't use the title control that only draw text (except if your logo is a font).
Look at the [ol.control.Compass](https://viglino.github.io/ol-ext/examples/canvas/map.control.compass.html) to display an image on the map (designed to display a compass but use it with no lines and rotation to display your own logo).

**Comment by ergin-duran** [comment]
@Viglino 
Okey i'll check it. How about new lines in CanvasTitle? if i have long text, i couldn't go new line by css or overflow options. And i tried to use "\n" as well.
I tried ol.style.Text and ol.style.TextPath as well. But i still couldn't achieve it.

**Comment by Viglino** [comment]
The title is only one line up.
How do you capture your map? If you're using a screen capture, you don't have to add the title in the canvas and you can use a more classical [ol.control.Status](https://viglino.github.io/ol-ext/examples/control/map.control.status.html) to display information on top of the map...

**Comment by ergin-duran** [comment]
I use CanvasRecorder.js (that u suggested it to me before). Unfortunately, i don't know any screen recorder written by js w/o canvas. 
-I am manually trying to add text by ctx.fillText(line,x,y) but it doesnt appear on canvas in OL3 map.

Should i change screen recorder lib or have another alternative to show status on canvas?
@Viglino 
Thanks in advice!

**Comment by Viglino** [comment]
If you just want to have 2 lines, use 2 titles one above the other... the first line should have a bottom at 1em, the second at 0...

**Comment by ergin-duran** [comment]
Yeah i can do that. But the problem is that text size is not stable. it means i fetch data from db dynamically so it may overflow in the line. I googled about it and i think canvas drawText has no limitation in the line for text. I will split/fit text manually before setTtile.

Is there any difference between CanvasTitle and manually fillText on the map postcompose event?

Thanks a lot for quick replies! @Viglino
