### ISSUE TITLE
Select Cluster status

### ISSUE THREAD

**Issue by nathanashton** [Viglino/ol-ext#322]
Are there any properties or events that be used to determine if a cluster is in the expanded state or not?

**Comment by Viglino** [comment]
The SelecCluster interaction is a select interaction and you can listen to the `select` event or look into the 'getFeatures()` to know which one is selected.
````javascript
// Listen to selection
mySelectCluster.on('select', function(e) {
  var features = e.selected;
});
// Get current selection
var sel = mySelectCluster.getFeatures();
````
