### ISSUE TITLE
Suggestion for popup: Add function for bring to front a ovelay popup

### ISSUE THREAD

**Issue by amancini** [Viglino/ol-ext#323]
Hi, we have a map with popups overlay we want see on top a content of poup when mouse is over it

**Comment by Viglino** [comment]
The popups are standard `div` on the map, you can use a class on it and set a `z-index` in your CSS to have it on top.
You can also add the popup control at last to have it draw on top of the previous controls.

**Comment by amancini** [comment]
yes I know but to simplify it's nice to have it  on options (like brintTofront true / false)

thank
