### ISSUE TITLE
featureAnimation.path: Feature hide 

### ISSUE THREAD

**Issue by amancini** [Viglino/ol-ext#324]
Hi, I have an application that calls a javascript function with the index of the array for the coordinates of a linestring; one marker is drawned to this index or moved  via a featureAnimation.Path

if the function is called quickly the marker is no longer visible on the map

 example

```
			var CurrentPoint = iconCar.getGeometry().getLastCoordinate();
			var points = [];

			if (animmation !== undefined){
				if (animmation.isPlaying){
					animmation.stop;
					iconCar.setGeometry(new ol.geom.Point(convertToMapProjection(point)));
					return;
				}
			}

			points.push(convertToEPSG4326(CurrentPoint));
			points.push(point);

			var path = new ol.geom.LineString(points)
			path.transform('EPSG:4326', 'EPSG:3857');

			animmation = new ol.featureAnimation.Path(
				{	path: path,
					rotate: false,
					easing: 'linear',
					speed: 4,
					revers: false
				});

			vectorLayerGPS.animateFeature(iconCar, animmation);
```

what is wrong? I also check for status of animation and stop it if running

best regars

**Comment by Viglino** [comment]
isPlaying stop and start are functions:
````javascript
animmation.isPlaying();
animmation.stop();
````
Does the animation work if called only once?
Are you sure the marker is not drawn out of the visible map extent? 
Try to centre on it.

**Comment by amancini** [comment]
hi,

when try to call isPlaying() receive error The object does not support the 'isPlaying' property or method

the animation work if wait for the end of animation
without animationt the marke is always visible

**Comment by Viglino** [comment]
The function relies on the current animation that is playing on layer/feature not on the animation Object:
````javasctipt
var currentAnim =  vectorLayerGPS.animateFeature(iconCar, animmation);
currentAnim.isPlaying();
currentAnim.stop();
````
If you don't stop the current animation it will conflict with the new animation and finally break the feature style.

**Comment by amancini** [comment]
thanks it work's fine
