### ISSUE TITLE
[CanvasBase] draw function not implemented ol-ext.592

### ISSUE THREAD

**Issue by ergin-duran** [Viglino/ol-ext#325]
Hello!

 I was trying to add Compass to OL3 map then i got this warn on the console.. But image/logo already appeared successfully on the map canvas. 

var compass = new ol.control.Compass({
    className: 'bottom',
    src: '../Content/img/logo.png'
});
map.addControl(compass);

Does this warn make any sense ? Should i care about it? 
I just commented that line for now. But hope you clarify me! @Viglino 
NOTE: 
ol-ext.js v3.1.4
ol-games latest
Openlayers: V3.x

**Comment by Viglino** [comment]
It's just a warning.
It has been removed in https://github.com/Viglino/ol-ext/commit/bc1ac00df64af0f58e05b699e3485dfc1950cf4b and will be included in the next release.
