### ISSUE TITLE
SnapGuides problem

### ISSUE THREAD

**Issue by g-hawk** [Viglino/ol-ext#326]
Hi,
I try to use snapguides interaction in my application, but this doesn't work.
The error is:

> Cannot read property '2' of null
>     at ol_interaction_SnapGuides.push../node_modules/ol-ext/interaction/SnapGuides.js.ol_interaction_SnapGuides.addGuide (SnapGuides.js:169)

Debugging I see that this.projExtent_ variable is null. This variable is read as map.getView().getProjection().getExtent(). 
I create view setting projection option with its EPSG code and I see that extent attribute of projection is null.
I have to set the extents to use snapguides interaction?
Thanks.

Giuseppe

**Comment by Viglino** [comment]
Yes the snapguide interaction needs to know the map extent to draw the guide to that extent.
I think you have to add it manually if you want to have it run.
