### ISSUE TITLE
Toggle interactions

### ISSUE THREAD

**Issue by arszp10** [Viglino/ol-ext#327]
https://github.com/Viglino/ol-ext/blob/master/src/control/Toggle.js#L31

change to collection<interaction>

for example
```javascript
    import Collection from 'ol/Collection';

    const firstInteraction = new Select({
      layers: [lPoint],
    });

    const addInteraction = new Select({
      condition: pointerMove,
      filter: (feature, layer) => {
        return source.hasFeature(feature) && lLine === layer;
      },
    });

    const control = new Toggle({
      html: '<i class="fas fa-hand-pointer"></i>',
      title: 'save',
      interaction: new Collection([firstInteraction, addInteraction]) // new/change api option
    });
```

**Comment by Viglino** [comment]
Hello,
I don't know the usecase but I don't think it's the good way to do that.
The control is used to control an interaction.
If you have linked interactions that must be be activated/deactivated together you should make it explicitly to have a better control.
````javascript
interaction1.on('change:active', function() {
  interaction2.setActive(interaction1.getActive());
});
````

**Comment by arszp10** [comment]
@Viglino 

the example shows that one `Toggle` is responsible for more than one interaction.

as an example, we have three `Toggle` and each has two interactions. if you wrap them in a `new Collection()`, then you do not need to write additional code.
