### ISSUE TITLE
Layer Switch with Georeference image features - Is this possible?

### ISSUE THREAD

**Issue by growe19** [Viglino/ol-ext#329]
I'd like to add `imageCenter: [x,y]` and `imageRotate: Number($("#rotate").val()*Math.PI/180)` to my Layers that are controlled from the Layer Switcher Control. 

I don't need to control the values, just set them hard coded. 

Would this technically work?
```
source: new ol.source.XYZ(
{
url: 'https://............./{z}/{x}/{y}.png',
imageCenter: [x,y],
imageRotate: Number($("#rotate").val()*Math.PI/180),
})
```

**Comment by Viglino** [comment]
[ol.source.WYZ](https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html) doesn't support such options. 
The server should returns the tiles in the right geometry...

**Comment by growe19** [comment]
Is there a way that rotating and re-positioning tiles could be achieved?
I have two layers both processed from a drone and the alignment is off. So I'm hoping to add x, y and rotation offset to get the two layers to align with each other.

**Comment by Viglino** [comment]
ol.source.XYZ is a source for tiled layers. The tiles are calculated on the server side to map the all area and fit the request.
If you have individual images you can try [ol.source.GeoImage](https://viglino.github.io/ol-ext/examples/layer/map.geoimage.html) to rotate/center/scale the image on your map.
