### ISSUE TITLE
DragOverlay and OpenLayers 6

### ISSUE THREAD

**Issue by lhapaipai** [Viglino/ol-ext#331]
Hi,
Thank you, for your amazing library !
I found an issue with the DragOverlay interaction on OpenLayers 6.
Without modification my Overlay is no longer accessible for DOM mouse events.
the ol-overlaycontainer-stopevent and the ol-overlaycontainer contains both  : `width:100%, height: 100%, position: absolute, z-index: 0`

 [v5.3 PluggableMap.js](https://github.com/openlayers/openlayers/blob/272a3c6b11804f2721a0f3fef545d91d6ddf90b1/src/ol/PluggableMap.js#L263)
```javascript
    /**
     * @private
     * @type {!HTMLElement}
     */
    this.overlayContainer_ = document.createElement('div');
    this.overlayContainer_.className = 'ol-overlaycontainer';
    this.viewport_.appendChild(this.overlayContainer_);

    /**
     * @private
     * @type {!HTMLElement}
     */
    this.overlayContainerStopEvent_ = document.createElement('div');
    this.overlayContainerStopEvent_.className = 'ol-overlaycontainer-stopevent';

...

    this.viewport_.appendChild(this.overlayContainerStopEvent_);
```

[v6 PluggableMap.js](https://github.com/openlayers/openlayers/blob/v6.0.0-beta.12/src/ol/PluggableMap.js#L246)
```javascript

    /**
     * @private
     * @type {!HTMLElement}
     */
    this.overlayContainer_ = document.createElement('div');
    this.overlayContainer_.style.position = 'absolute';
    this.overlayContainer_.style.zIndex = '0';
    this.overlayContainer_.style.width = '100%';
    this.overlayContainer_.style.height = '100%';
    this.overlayContainer_.className = 'ol-overlaycontainer';
    this.viewport_.appendChild(this.overlayContainer_);

    /**
     * @private
     * @type {!HTMLElement}
     */
    this.overlayContainerStopEvent_ = document.createElement('div');
    this.overlayContainerStopEvent_.style.position = 'absolute';
    this.overlayContainerStopEvent_.style.zIndex = '0';
    this.overlayContainerStopEvent_.style.width = '100%';
    this.overlayContainerStopEvent_.style.height = '100%';
    this.overlayContainerStopEvent_.className = 'ol-overlaycontainer-stopevent';
    this.viewport_.appendChild(this.overlayContainerStopEvent_);
```

for the moment, I force the z-index
```javascript
.ol-overlaycontainer {
  z-index: 1 !important;
}
```
but I don't like that and especially I don't know the side effects of my action.
Am I using your component incorrectly or it is a true problem ?
Thanks

**Comment by lhapaipai** [comment]
for the moment I try to reproduce the openlayers 5.3 comportement with this : 
```javascript
.ol-layers {
  position: initial !important;
  z-index: initial !important;  
}

.ol-overlaycontainer {
  z-index: initial !important;
  position: initial !important;
  width: initial !important;
  height: initial !important;
}

.ol-overlaycontainer-stopevent {
  z-index: initial !important;
  position: initial !important;
  width: initial !important;
  height: initial !important;
}
```

**Comment by Viglino** [comment]
ol-ext is not yet compatible with ol6.
ol6 is not a stable version and implementation may change.
For now it seems the map DOM has changed and the stopevent overlay container catch click events before the  overlay container.
Just change your CSS to remove the position absolute of the ol-overlaycontainer-stopevent to have it run and wait for a more stable version of ol6.
````css
.ol-overlaycontainer-stopevent {
  position: initial !important;
}
````

**Comment by lhapaipai** [comment]
ok ! have a nice day

**Comment by pavelgdr** [comment]
> ol-ext is not yet compatible with ol6.
> ol6 is not a stable version and implementation may change.
> For now it seems the map DOM has changed and the stopevent overlay container catch click events before the overlay container.
> Just change your CSS to remove the position absolute of the ol-overlaycontainer-stopevent to have it run and wait for a more stable version of ol6.
> 
> ```css
> .ol-overlaycontainer-stopevent {
>   position: initial !important;
> }
> ```

this hack leads all controls to disappear
