### ISSUE TITLE
import getVectorContext error when build by rollup

### ISSUE THREAD

**Issue by DZG-MELODY** [Viglino/ol-ext#332]
Rollup exits with error Illegal reassignment to import module。
see https://github.com/rollup/rollup/issues/436

**Comment by Viglino** [comment]
Do you have a more complete example?
+ give version used (ol and ol-ext)

**Comment by DZG-MELODY** [comment]
version:
ol-ext: > v3.1.2
ol: v5.3.3

---

when my lib build by rollup, an error emit:

```
(!) Missing exports
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/ol-ext/util/getVectorContext.js
hasOwnProperty is not exported by node_modules/ol/render.js
5: import * as ol_render from 'ol/render';
6: 
7: if (!ol_render.hasOwnProperty('getVectorContext')) {
                  ^
8:   ol_render.getVectorContext = null;
9: }
node_modules/ol-ext/util/getVectorContext.js
getVectorContext is not exported by node_modules/ol/render.js
6: 
7: if (!ol_render.hasOwnProperty('getVectorContext')) {
8:   ol_render.getVectorContext = null;
               ^
9: }
[!] Error: Illegal reassignment to import 'ol_render'
node_modules/ol-ext/util/getVectorContext.js (8:2)
6: 
7: if (!ol_render.hasOwnProperty('getVectorContext')) {
8:   ol_render.getVectorContext = null;
     ^
9: }
Error: Illegal reassignment to import 'ol_render'
```

**Comment by Viglino** [comment]
This is a hack to make the lib compatible with ol5 and next version ol6.
See #310 fro more information.
I'll try to find a way to make it compatible with all bundler...

**Comment by Viglino** [comment]
Hello,
I've pushed a new commit to get ride of this.
`getVectorContext` is rewritten to make it compatible with ol5/6.
Can you try if it runs for you?

**Comment by DZG-MELODY** [comment]
> Hello,
> I've pushed a new commit to get ride of this.
> `getVectorContext` is rewritten to make it compatible with ol5/6.
> Can you try if it runs for you?

ok,I will try it

**Comment by DZG-MELODY** [comment]
Hi,I clone the repo and link the package. There is no error emit when build lib.
Thanks very much!

**Comment by Viglino** [comment]
@amarreropalomino You'll have to wait v4.1.6 or clone the master repo...
I'll try to publish asap
