### ISSUE TITLE
Linear Referencing 

### ISSUE THREAD

**Issue by karumbu97** [Viglino/ol-ext#333]
Is there any way to create functions for [**linear referencing**](http://desktop.arcgis.com/en/arcmap/10.3/guide-books/linear-referencing/what-is-linear-referencing.htm) as in the ArcGIS?. 
![linear referencing](https://user-images.githubusercontent.com/49720617/63168452-d03c2f80-c051-11e9-8bc6-017d66547e3f.gif)
![linear referencing2](https://user-images.githubusercontent.com/49720617/63168488-ec3fd100-c051-11e9-8990-7a168c9a8e5a.gif)

**Comment by Viglino** [comment]
I don't know the use-case but you can look at the [flowLine style](https://viglino.github.io/ol-ext/examples/style/map.style.gpxline.html) to display information along the line.
Using [ol-games getCoordinateAtRef()](https://github.com/Viglino/ol-games/blob/master/utils/geom.js#L63) lets you get a position along a LineString at a linear reference.
