### ISSUE TITLE
Remove dependency on ajax, a non-functional package that, so far as I can tell, is not used in the codebase.

### ISSUE THREAD

**Issue by minusworld** [Viglino/ol-ext#334]
ol-ext seems to have a dependency on ajax@0.0.4, which is not a functional package, does not seem to be used in the codebase, and is potentially dangerous.

The ajax package has the potential to eval(...) results from an arbitrary url. https://github.com/joehewitt/ajax/issues/4

**Comment by Viglino** [comment]
I think it's a relic of a previous test. I'll remove it from the package
