### ISSUE TITLE
Are TypeScript definition files available for ol-ext?

### ISSUE THREAD

**Issue by idevtech** [Viglino/ol-ext#335]
Are there TypeScript definitions available for ol-ext? If not, are there any plans to create them in the near future?

**Comment by Viglino** [comment]
Look at this project: https://github.com/Siedlerchr/types-ol-ext

**Comment by idevtech** [comment]
Thanks

**Comment by Siedlerchr** [comment]
I started working on type defintions, however there a couple of things which need to be fixed. Any help welcome
