### ISSUE TITLE
ol/source/OSM colour manipulation

### ISSUE THREAD

**Issue by RenoSun** [Viglino/ol-ext#336]
Hi All,

I would like to request a new feature allowing users to manipulate the colors of ol/source/OSM dynamically just like what we have for ol/source/Raster.

https://openlayers.org/en/latest/examples/color-manipulation.html

Thanks,
Reno

**Comment by Viglino** [comment]
Have you look at the [filter examples](https://viglino.github.io/ol-ext/examples/filter/map.filter.colorize.html) to change colors on the map? 
It uses canvas built in functions and is more efficient than pixel manipulation.

**Comment by RenoSun** [comment]
Thanks Viglino. I will give it a try!
