### ISSUE TITLE
Method 'setActive' of interaction in ol.control.Editbar doesn't work

### ISSUE THREAD

**Issue by SimHongSub** [Viglino/ol-ext#339]
I was using editbar like this.
```
var editbar = new ol.control.EditBar ({
    source: drawVector.getSource(),
    interactions: { Info: false }
});

editbar.getInteraction('Select').setActive(false);
```
This referred to example.

But now this doesn't work.

I got the following error message:
```
  Uncaught ReferenceError: ledit is not defined
      at wx.<anonymous> (ol-ext.min.js:9)
      at wx.b (ol.js:46)
      at wx.Sc.b (ol.js:49)
      at Yc (ol.js:51)
      at wx.k.set (ol.js:51)
      at wx.Jg.Ha (ol.js:152)
```
I could see the same error in the your example.
(https://viglino.github.io/ol-ext/examples/interaction/map.interaction.undoredo.html)

Why do I get the above error?

**Comment by Viglino** [comment]
It's a bug introduced in the last commit.
I'll fix it asap.
Use [npm package](https://www.npmjs.com/package/openlayers-ext) or a release distribution instead (https://github.com/Viglino/ol-ext/releases)
