### ISSUE TITLE
EditBar: Disallow Circle

### ISSUE THREAD

**Issue by m-mohr** [Viglino/ol-ext#340]
I'm trying to use the EditBar for a minimal GeoJSON Editor. Circles are not standardized in GeoJSON and therefore I'd like to disallow them. Is there a way to do so?

**Comment by Viglino** [comment]
What do you mean by "circle"?
In the [example](https://viglino.github.io/ol-ext/examples/bar/map.control.editbar.html) the RegularShape button creates regular shape, ie. a circle is a polygon with a set of circular points...
If you want to remove it from the bar, just pass `DrawRegular: false` as option when creating the bar.

**Comment by m-mohr** [comment]
Oh, I see. I thought they were real circles. Nevermind, thanks for your help.
