### ISSUE TITLE
Grid Reference doesn't display labels for grids that aren't 1:1 ratio.

### ISSUE THREAD

**Issue by volcomk10** [Viglino/ol-ext#341]
I'm using the grid reference to allow users to zoom to print certain parts of the county. Because we are a string of very thin islands running north south I am using a grid size of [15,40]. This is also to optimize the zoom and shape of the grid to provide the best look for printing each grid. The x-axis is labeled fine however the y-axis is not being labeled after 15. The index does show the proper grid number.
I have adjusted the extent to make that wider and that worked but I have to so many (useless) grid cells in order to have an entire grid cell at the zoom level I need, and then it also gets into symbols which is not ideal.
I can obviously see that they are being labeled for a 1:1 ratio, I've tested that much, can you point me in the right direction to what to edit in the js if you don't have time for  a fix or update.

**Comment by Viglino** [comment]
Ok, there is a typo in the source `src/control/GridReference.js`.
It calculate the index on the first size value (15) for both x-axis/y-axis it should use the second one (40) for the y-axis :grimacing: 
line 274, use size[0]:
```javascript
    for (i=0; i<size[0]; i++) {
````
should use size[**1**]:
```javascript
    for (i=0; i<size[1]; i++) {
````
I'll push a fix asap
