### ISSUE TITLE
"ol" should be a peer dependency of "ol-ext"

### ISSUE THREAD

**Issue by fjorgemota** [Viglino/ol-ext#342]
Hey.

I'm trying to use `ol-ext` with openlayers 6 beta to try to fix a memory leak problem. The problem is...when I install `ol-ext`, `npm` installs openlayers 5.3 on a `node_modules` folder inside the `node_modules/ol-ext` folder of the project, because the project I'm working on depends on openlayers 6 beta..

So..given the nature of this project (of being a plugin to openlayers), I guess a good idea would be to add `ol` as a [peerDependency on package.json](https://nodejs.org/es/blog/npm/peer-dependencies/). I think something like this is viable:

```
"peerDependencies": {
    "ol": "5.x"
}
```

Also, it would be better if there two major versions of `ol-ext`, one supporting openlayers 5 and one supporting openlayers 6. The peer dependency would be adjusted as such..and this could be two branches on this repository. This would avoid problems with "transient versions" supporting both openlayers versions, and would fix problems with `import` working on one openlayer version but not on another.

These two changes should fix #310 and related issues. What do you think?

**Comment by Viglino** [comment]
Yet ol-ext is not compatible with ol6 (just partially as beta).
I'm not sure the peer dependency will solve the problem.
I plane to use:
```
  "dependencies": {
    "ol": ">= 5.3.0"
  },
```
But I can use peerDependencies. Tell me if it suits you and I'll try to push a new version asap.

**Comment by fjorgemota** [comment]
Hey.

I understand that ol-ext isn't totally compatible with ol6 yet (even because ol6 is in beta and so it's not totally stable yet too...)

The peer dependency suggestion is so a user can try to use ol-ext with ol6 easily, just for testing or whatever. With peer dependency, npm just warns the user about the unmatched dependency, instead of downloading and installing the version specified by ol-ext, so, yeah, the use of peer dependencies here should at least fix this problem, given the ol-ext nature of just extending openlayers with new features.

About the ol's version supported, personally, I don't care a lot about it. I suggested `5.x` for this version because this way you could made a version that totally works with ol v5 and one that starts to work with ol v6 instead of adding hacks here and there to try to support both ol v6, and fixing, this way, the problems related to bundlers trying to statically analyze the code to try to detect what you really want there (for example, avoiding [warnings like this](https://github.com/Viglino/ol-ext/issues/332#issuecomment-525555102)).

What do you think?

**Comment by fjorgemota** [comment]
Hey.

I saw that you're already using  peer dependencies as per https://github.com/Viglino/ol-ext/commit/8bac5972d51bd5c60cfa9f963ef13f4960ea2bf6 (that was released on v3.1.6 and according to my tests it works really well, with just a warning being emitted by npm/yarn when the `ol` dependency doesn't match)...so..Should I close this issue already or do you have any other questions about peer dependencies being a good solution for ol-ext?

**Comment by Viglino** [comment]
I finally put ol as peer dependency. It should be more clear.
You can close.

**Comment by fjorgemota** [comment]
Nice! Thanks! :tada:
