### ISSUE TITLE
AnimatedClusters don't render initial set on openlayers 6

### ISSUE THREAD

**Issue by fjorgemota** [Viglino/ol-ext#343]
Hey.

I found a curious issue on openlayers 6 beta: Basically, the animated cluster layer only appears when the user zoom-in or zoom-out on the map...testing with `ol.layer.Vector` works natively since first-render (so I guess this isn't an openlayers 6 beta issue), and on openlayers 5 everything works fine.

**Comment by Viglino** [comment]
ol-ext is not yet fully compatible with ol6-beta.
Try to force rendering: apply `changed()` method on your layer (or source) after adding it to the map.

**Comment by fjorgemota** [comment]
I tried this..but in the end I discovered the problem isn't with this package (even throught `ol.layer.Vector` works OK with the same source)...but with the source: I'm using [ol-supercluster](https://github.com/fjorgemota/ol-supercluster) as source, and after looking into `ol.source.Cluster` latest commits I observed there were one commit (removing `super.refresh()` after `this.addFeatures()` call) that I haven't applied to ol-supercluster yet....After applying it everything worked successfully.

So now I'm not sure if I should close this issue given that this package works fine when `ol.source.Cluster` is used as source OR if this should in fact be considered a bug given that `ol.layer.Vector` works fine with the ol-supercluster source...what do you think?

**Comment by Viglino** [comment]
Let it open still offcial v6.
We'll see if it solves the issue.
I'll try to have a look at supercluster also.

**Comment by fjorgemota** [comment]
The ol-supercluster thing is just a integration between supercluster and openlayers, so I can have a cluster map with a LOT of points without performance being bad. It also resolves a few weird issues with cluster, where weird clusters appeared when zoom in on the map. I don't think you need to work on anything to support it because the idea is to have mostly the same API as `ol.source.Cluster`, only with a few extra features and faster speed.

Since 0.1.2 it works well again with both openlayers 5 and openlayers 6, and also with ol-ext's animated cluster. To use it on your actual example you can [replace these lines](https://github.com/Viglino/ol-ext/blob/e11aad84cc16ba2b8f7b0b6966fd8ff16062c3a9/examples/animation/map.animatedcluster.html#L134-L137) with something like:

```js
var clusterSource=new OLSuperCluster({
      radius: 40,
      source: new ol.source.Vector(),
      view: map.getView()
});
```

(you'll need some kind of bundler to work with it, tho, so you can do `import OLSuperCluster from 'ol-supercluster';` at the top of the file).

And it should work fine. 

Either way...I researched around a bit and seems like the `refresh()` method on OpenLayers 6 had a breaking change, where it now clears every element of the `ol.source.Vector` and request it again from the server. That caused the bug. So I think it's okay to close this issue now.

Sorry for bothering you with a issue not related to your project, tho. And keep the good work!
