### ISSUE TITLE
v3.1.6 isn't published on npm nor on git tags

### ISSUE THREAD

**Issue by fjorgemota** [Viglino/ol-ext#344]
Hey.

I see that there's a [commit updating version to 3.1.6](https://github.com/Viglino/ol-ext/commit/f240da4c058debc29efa0fbf178573720b3d9f75)....but that update isn't available on npm nor registered on git tags.

Can you publish that version soon, please? I need that update to fix a warning on webpack...

**Comment by Viglino** [comment]
ol-ext@3.16 is published 🎉

**Comment by fjorgemota** [comment]
Nice, thanks @Viglino! And sorry for the number of issues I opened last week. :)

**Comment by Viglino** [comment]
You're welcome
