### ISSUE TITLE
Is it possible to move rotation point from default location?

### ISSUE THREAD

**Issue by tesicg** [Viglino/ol-ext#345]
Hi,

First of all, your OL extensions are incredible. Thank you very much!

I have a question. When we use Transform interaction in order to change the size, position, rotation... of feature, the rotation point is placed a little bit out of selection square. In case of small circle, it looks as following:

![ScreenShot](https://user-images.githubusercontent.com/10287604/64325796-71733180-cfd1-11e9-828c-1b28b3b03cc4.png)

Is it possible to move the rotation point to the center of the circle?

Thank you in advance.

**Comment by Viglino** [comment]
The rotation point is a handle à the bottom-right corner of the bbox. It acts as a lever to rotate the object. A small link to the center of the object could make it more clear

**Comment by tesicg** [comment]
Excuse me, I haven't understood this: "A small link to the center of the object could make it more clear".

**Comment by Viglino** [comment]
No you can't as is. The handle is place on the bottom right corner.
