### ISSUE TITLE
Copy and Paste API docs

### ISSUE THREAD

**Issue by zac-robinson** [Viglino/ol-ext#347]
I was wondering if there are any plans to add API documentation to the Copy/Paste interaction.

There is the example here: https://viglino.github.io/ol-ext/examples/interaction/map.interaction.copypaste.html

But I can't see any API docs here: https://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.html

**Comment by Viglino** [comment]
Yes I have tout build the doc...
The [example](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.copypaste.html) lets you see how tout use it and shows the main options.
