### ISSUE TITLE
Transform getFeatures API change

### ISSUE THREAD

**Issue by zac-robinson** [Viglino/ol-ext#348]
In trying to update the version on `ol-ext` that we are using from `3.1.2` to `3.1.3` and above, there seems to have been an API change when calling `getFeatures()` on the `transform` interaction.

in version `3.1.2` this API returned an array of features, however from version `3.1.3` it now returns a collection with the array inside it.

Is this a desired change or is it a bug that has been introduced? Just wondering whether to change how we are using it or not depending on if it is something that needs to be "fixed" in the library.

**Comment by Viglino** [comment]
The selection is now a collection to solve #277 (multiple scaling)
Just use `getArray` function or Collection function (getLength, item, forEach...)
