### ISSUE TITLE
Usage of const hinders build

### ISSUE THREAD

**Issue by OsmHydrant** [Viglino/ol-ext#350]
Previously ol-ext was not using modern JavaScript like "const". With latest changes to [util/getVectorContext.js](https://github.com/Viglino/ol-ext/blob/master/src/util/getVectorContext.js#L9) this has changed.
Before, my build was working fine, since all node_modules were ES5. With introducing `const` I'd now also need to transform all external libraries.

Was this ES5-incompatibility a recent design decision? Besides [util/getVectorContext.js](https://github.com/Viglino/ol-ext/blob/master/src/util/getVectorContext.js#L9), [interaction/SnapGuides.js](https://github.com/Viglino/ol-ext/blob/master/src/interaction/SnapGuides.js#L277) is also affected.

**Comment by Viglino** [comment]
If you're using ol-ext as modules you also use ol as module and it uses modern JS with `class` and `const` [ol/render.js](https://github.com/openlayers/openlayers/blob/master/src/ol/render.js).
The ES5 script is still available in the dist: [dist/ol-ext.js](https://github.com/Viglino/ol-ext/blob/master/dist/ol-ext.js).
