### ISSUE TITLE
Bug: Timeline control not show the ticks on firefox

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#353]
Hi,

I tested the `Timeline` control on `FireFox v69.0 64bit` but it doesn't work properly since the date ticks not displayed correctly in the [example](https://viglino.github.io/ol-ext/examples/storymap/map.control.timequake.html) and in my project they not displayed at all.

Here is an example images for both the example and my project.

https://i.ibb.co/dPJHwVs/tm-bug1.png
https://i.ibb.co/9ZpHBdn/tm-bug2.png

**Comment by Viglino** [comment]
Hi,
There is a bug on Firefox :cry: 
I'll try to fix it asap.

**Comment by Abdullah0991** [comment]
Another problem, as I testing the control on `Chrome`, when play the timeline you will see the slider cursor not stop on the tick perfectly, it get shifted to the left as the timeline running.

[exmaple](https://i.ibb.co/ggqG0VB/ezgif-com-crop-4.gif)
