### ISSUE TITLE
GeoLocationBar fires drawstart and drawend events twice in succession without a convenient way to suppress second event

### ISSUE THREAD

**Issue by johnheenan** [Viglino/ol-ext#356]
GeoLocationBar registers an instance of GeoLocationDraw as an interaction instance and this instance is passed to a Toggle button. The Toggle button calls the setActive function of an interaction instance if it has an interaction instance

In the GeoLocationDraw interaction instance the setActive function calls 
```
ol_interaction_Interaction.prototype.setActive.call(this, active);
```
and either
```
this.dispatchEvent({ type:'drawstart', feature: this.sketch_[1]});
```
or
```
this.dispatchEvent({ type:'drawend', feature: f});
```
There is a problem with code above.

Following is how drawstart is called twice. A similar mechanism applies for drawend

Any interaction which has setActive(true) called will automatically dispatch its drawstart event, resulting in drawstart dispatched twice for the interaction instance of a GeoLocationDraw instance.

There is now a paradox. Openlayers wraps events in a higher level. One of the purposes of this is to avoid having to call functions like stopPropagation() on events. We cannot use this as a solution.

I used a clumsy solution to avoid changing ol-ext source code. In a drawstart or drawend event I ignored the event if
```
e.target.dispatching_['change:active']
```
tested true

John Heenan

**Comment by Viglino** [comment]
I've changed the `setActive` method of `GeolocationDraw` and verify the interaction state before activating or deactivating, ie. if the interaction is already activated it doesn't activated twice and doesn't fire events.
Tell me if it runs for you.

**Comment by johnheenan** [comment]
Thanks.

Confirmed drawstart and drawend events now called once instead of twice.
