### ISSUE TITLE
how to handle ol.control.LayerPopup on change?

### ISSUE THREAD

**Issue by ergin-duran** [Viglino/ol-ext#357]
[Question]
I add base layers to map (BTW, only default base layer's visibility is true.). And i'm also using ol.control.LayerPopup to choose one of them. 
Now i want to store selection (layer) in localStorage and later it'll remember selection so i can set it programmatically.
Is there any way to handle this? Such as, Get selected base layer id or name on change/select?

Openlayers: 3.x
ol-ext: latest

Thanks in advice!

**Comment by Viglino** [comment]
Try to look at the code of the [ol/control/Permalink](https://github.com/Viglino/ol-ext/blob/master/src/control/Permalink.js). 
You have to define a property to find the layer back (you can use the `name` but make sure it is unique). `ol/control/Permalink` use a `permalink` property to add in the url.
In the Permalink control the visibility of the layer (and map position) is store in the window location but you can store it in the locastorage as is.

**Comment by Viglino** [comment]
I've added a `localStorage` option in the `permalink` control.
This will save the position / layers visibility in the localStorage for the next run.
