### ISSUE TITLE
SearchNominatim needs "bounded" option.

### ISSUE THREAD

**Issue by brian32768** [Viglino/ol-ext#358]
I need to restrict results to my county.

From the Nominatim docs, "bounded=[0|1]
When a viewbox is given, restrict the result to items contained with that viewbox (see above). When viewbox and bounded=1 are given, an amenity only search is allowed. In this case, give the special keyword for the amenity in square brackets, e.g. [pub]. (Default: 0)"

I will try to do a PR for this if you think it's a good idea.

**Comment by Viglino** [comment]
Tell me if you push a PR. Otherwise I can try to add this option.

**Comment by Viglino** [comment]
I've added the options in the Nominatim search.
Tel me if it runs for you.
