### ISSUE TITLE
How to ensure translating/scaling of a box within a boundary

### ISSUE THREAD

**Issue by XuYan** [Viglino/ol-ext#359]
I'm using Transform interaction to scale/translate a polygon feature. After reading the documentation, I haven't found a good way to restrict the transformed polygon within a certain area. Specifically in my case, I want to achieve something like user can only move/scale a bounding box on top of a static image and cannot move the box out of the image. Is there a way to do this?
I found the "handleDragEvent_" and "handleMoveEvent_" promising. Am I on the right track?
If someone can help throw an example, that will be awesome. Thanks!!

**Comment by Viglino** [comment]
There is no restriction on the Transform interaction.
I can add a `condition` option to test if an event can be handled by the interaction.
This option will be a function that takes an `module:ol/MapBrowserEvent~MapBrowserEvent` and returns a boolean to indicate whether that event should be handled.
Thus you can test if the event coordinate is in your extent.
I'll try to push such a mechanism asap.

**Comment by XuYan** [comment]
That's awesome. THANK YOU Viglino!!

**Comment by Viglino** [comment]
I've added a `condition` option to test if the event must be handled.
Look at the example to limit mouse events in a `bbox`. Result is not perfect as it only test the mouse event (not the selection bbox).
It's up to you to make your own test to restrict the movement.
Tell me if it suites you.

**Comment by XuYan** [comment]
Thank you so much Jean! It'll be much helpful!

Jean-Marc Viglino <notifications@github.com> 于2019年9月29日周日 上午2:59写道：
