### ISSUE TITLE
Layer switcher alignment (ol-ext)

### ISSUE THREAD

**Issue by davidpiedrarojas** [Viglino/ol-ext#360]
Hello, I´ve been trying to align the layers inthe layer switcher, but no luck.

This is how it looks right now:
![image](https://user-images.githubusercontent.com/21229273/65898438-cc990980-e36e-11e9-8cce-3d7382e42deb.png)

To make the right alignment I should add many characters at the end of the small name layers, like this:
![image](https://user-images.githubusercontent.com/21229273/65898586-239ede80-e36f-11e9-955b-65dbf6fee805.png)

How can I make the alignment?

**Comment by Viglino** [comment]
Hello,
Do you have an online example (codepen, jsfiddle, etc...) ?
@+

**Comment by davidpiedrarojas** [comment]
No, I don´t have an online example. Is there any other way for you to help me?

**Comment by Viglino** [comment]
There may be a conflict in css. 
The label should align left... Try to see in the debugger what's wrong with the css.

**Comment by davidpiedrarojas** [comment]
I manage to create a jsfiddle, it´s my first time so I hope y make it right.
https://jsfiddle.net/davidpiedra/wmx05jpa/5/

As you see in the names of the base layers have dots after to align them, the rest no.

Hope you can help me.

**Comment by Viglino** [comment]
It seems there is a `text-align:center` somehow...
Change your CSS:
```css
#switcher .ol-layerswitcher {
  text-align: left;
}
```
See https://jsfiddle.net/Viglino/ejhp5q1r/

**Comment by davidpiedrarojas** [comment]
Thanks that solved the problem. 

Didn´t find that code in any of the CSS.

Thank you.
