### ISSUE TITLE
[Question] What's the best way to move features dynamically and smoothly in openlayers?

### ISSUE THREAD

**Issue by erginduran** [Viglino/ol-ext#365]
Hi @Viglino 
I know that this question is not related with ol-ext directly. But i've learnt lots of things about ol from you and your awesome libraries.

I have a socket server which takes/handles GPS devices and emit those geojson data to clients through websockets. And i am updating features' posion on the map. For testing, i show a thousand features on the map and i also use AnimatedCluster (from ol-ext). It shows without a problem. But when i zoom in max depth on the map, screen is getting stuck.
- How should i update features in cluster source? clear each time and add all features again OR find updated features by lots of loop in cluster and change geometry coordinates? 
- Is there a better solution to move features on the map smoothly? (someone told me that you can use overlays with animation instead features. I will try this.But do you recommend it? for performance improvements..)
- Features has an icon. But i want to show also alarm icon on it for a while (when it happens). Is it possible to add extra icons top of specific features? 

Hope i've explained my problems clearly. Thanks in advice!

**Comment by Viglino** [comment]
Hello,
* I also have some issue with large cluster sources on update.
The problem rely on refresh when features are updates that will calculate clusters and stuck.
One way to avoid this is to prevent source refresh on update. 
Just overwrite the to prevent refresh (you can also create your own child class):
```javascript
ol.source.Cluster.prototype.refresh() {
  /* Test if clusters must be calculated */
  if (this.get('preventRefresh')) return;
  /* endif */
  this.clear();
  this.cluster();
  this.addFeatures(this.features);
};
```
Then set the `preventRefresh` property before updating the source:
```javascript
clusterSource.set('preventRefresh', true);
// Update source
...
clusterSource.set('preventRefresh', false);
clusterSource.refresh();
```

* I don't think overlays would be a better solution.

* If you want animations on objects you have to use ol rendering mechanisms (prerender and postrender) to handle animationframes.
You can also have a look at [ol-games](https://viglino.github.io/ol-games/) but I don't know the real impact on large data sets.
