### ISSUE TITLE
Storymap with angular

### ISSUE THREAD

**Issue by tactusoft** [Viglino/ol-ext#370]
Congratulations for this great contribution. Do you have an example storymap with angular?

Thank you.

**Comment by Viglino** [comment]
No, I don't.
You can look at [the vanilla example](https://viglino.github.io/ol-ext/examples/storymap/map.control.storymap.html). 
I think you can create a component with a storymap as template and pass the nativeElement  to create the control on element initialization:
```javascript
new ol.control.Storymap({
  html: this.elementRef.nativeElement
});
```

**Comment by tactusoft** [comment]
Thanks that worked.
