### ISSUE TITLE
Is Cluster: convex hull interaction interferes with drawing interaction? OL6.0.1

### ISSUE THREAD

**Issue by RenoSun** [Viglino/ol-ext#371]
Is cluster: convex hull interaction interferes with drawing interaction?

I was able to use cluster: convex hull and drawing interaction together when I was using OL5.3 with OL-EXT2.0.7. 

However, it seems there are interference between these two interactions when using OL6.0.1 with OL-EXT3.1.7. When I was drawing line string or polygon on the map, the drawing features won't be displayed properly in the middle/end of drawing. The drawing feature will disappear, but appear when I click the next point or zoom in/out.
![ClusterAndDrawingIssueOL6](https://user-images.githubusercontent.com/5566783/67532815-7f157100-f67c-11e9-9ca2-c41839215d40.gif)

Does anyone have similar issue?

Thanks,
Reno

**Comment by Viglino** [comment]
Do you have console errors ?

**Comment by RenoSun** [comment]
I wish I had any console errors telling me what's wrong... 

When I was firstly using OL5.3 and OL-EXT2.0.7 for cluster, I had same issue without having console errors.

I resolve the issue with following logic:

Function Drawing on Map
If(clusterLayer is on)
{
Map removes cluster modify interaction
Map removes cluster select cluster interaction
}
...Other actions for drawing on the map, select drawing on the map, or measurement drawing on the map.


However, using OL6.0.1 with OL-EXT3.1.7...My fix is not working anymore.

Thanks,
Reno

**Comment by Viglino** [comment]
When you have many interactions on a map they will add up. Thus you have to deactivate ones you don't need at a time.
You don't have to remove interactions, just use `setActive(false)` to make sure the two interactions are not activated at ones.
```javascript
myInteraction.on('change:active', (e)=> {
  if (e.target.getActive()) {
   // deactivate incompatible interactions
   interaction2.setActive(false);
  }
});
```

In your case I think it is more a styling issue. ol6 now use a shared default style. Maybe an other interaction alter this style and makes it invisible.
Just add your own style when creating the Draw interaction (use the `style` option).

Not sure it is related to ConvexHull (try to remove it to see if it is the case).

**Comment by RenoSun** [comment]
Thank you so much @Viglino. I will use my own style for my drawing interactions. Will hopefully report if it's the case on Tuesday.

**Comment by RenoSun** [comment]
I found it's truly a issue regarding "Style". As long as I commented out the style to draw cluster when selected. I can perform other draw interactions without issues. Here is my codes.
`// Style for selection
                var img = new ol.style.Circle(
                    {
                        radius: 7,
                        stroke: new ol.style.Stroke(
                            {
                                color: "rgba(245, 230, 26,1)",
                                width: 1
                            }),
                        fill: new ol.style.Fill(
                            {
                                color: "rgba(245, 26, 26, 0.70)"
                            })
                    });
                var style0 = new ol.style.Style(
                    {
                        image: img
                    });
                var style1 = new ol.style.Style(
                    {
                        image: img,
                        // Draw a link beetween points (or not)
                        stroke: new ol.style.Stroke(
                            {
                                color: "#fff",
                                width: 1
                            })
                    });

                // Select interaction to spread cluster out and select features
                selectCluster = new ol.interaction.SelectCluster(
                    {	// Point radius: to calculate distance between the features
                        pointRadius: 7,
                        animate: true,
                        hitTolerance: 24,
                        // Feature style when it springs apart
                        featureStyle: function () {
                            return [style1]
                        },
                        //selectCluster: false,	// disable cluster selection
                        // Style to draw cluster when selected
                        //style: function (f, res) {
                        //    var cluster = f.get('features');
                        //    if (typeof cluster !== 'undefined') {
                        //        if (cluster.length > 1) {
                        //            //var s = getStyle(f, res);
                        //            if (ol.coordinate.convexHull) {
                        //                var coords = [];
                        //                for (i = 0; i < cluster.length; i++) {
                        //                    coords.push(cluster[i].getGeometry().getFirstCoordinate());
                        //                }
                        //                var chull = ol.coordinate.convexHull(coords);
                        //                //s.push(new ol.style.Style(
                        //                //    {
                        //                //        stroke: new ol.style.Stroke({ color: "rgba(245, 230, 26,1)", width: 2 }),
                        //                //        fill: new ol.style.Fill({ color: "rgba(245, 26, 26, 0.70)" }),
                        //                //        zIndex: 1
                        //                //    }));
                        //                var polygonExt = new ol.geom.Polygon([chull]).getExtent();
                        //                view.fit(polygonExt, animOption);
                        //            }
                        //            console.log('return1');
                        //            return [
                        //                new ol.style.Style(
                        //                    {
                        //                        image: new ol.style.Circle(
                        //                            {
                        //                                stroke: new ol.style.Stroke({ color: "rgba(245, 230, 26,1)", width: 2 }),
                        //                                fill: new ol.style.Fill({ color: "rgba(245, 26, 26, 0.70)" }),
                        //                                radius: 8,
                        //                                zIndex: -10
                        //                            })
                        //                    })];
                        //        }
                        //        else {
                        //            console.log('return2');
                        //            return [
                        //                new ol.style.Style(
                        //                    {
                        //                        image: new ol.style.Circle(
                        //                            {
                        //                                stroke: new ol.style.Stroke({ color: "rgba(245, 230, 26,1)", width: 2 }),
                        //                                fill: new ol.style.Fill({ color: "rgba(245, 26, 26, 0.70)" }),
                        //                                radius: 8
                        //                            })
                        //                    })];
                        //        }
                        //    }
                        //}
                    });
                modify = new ol.interaction.Modify({ features: selectCluster.getFeatures(), hitTolerance: 24 });`
