### ISSUE TITLE
How to create a custom div/panel with a toggle button on openlayers map?

### ISSUE THREAD

**Issue by asimus90** [Viglino/ol-ext#372]
I am trying to add a custom statistic panel with charts on map triggering w/ control button. I can create a custom ol.control.Toggle to trigger display panel. But i cannot put div/panel on the map properly. Map div is relative.

I checked your ol-ext library and i see that you use "ol_ext_element" to create custom div on map.
I have a div something like that below snippet:

```
<div id="map" style="position:relative"> </div>
<div id="statistics" style="background-color:white;bottom:.5em;left:.5em;top:unset;">
    <div id="speedGauge"></div> <!-- am4charts' using this div -->
    <div id="infoPanel">
        <div id="place" class="row">
            <img src="../place_32x32.png" />
            <p>Sample street</p> <!-- setting this value by javascript dynamically -->
        </div>
        <div id="distance">
            <img src="../distance_32x32.png" />
            <p>5 miles </p> <!-- setting this value by javascript -->
        </div>
    </div>
</div>
```
Should i use ol_ext_element to create div so i can put it on map where i placed a control button to toggle it? i see that you set "ol-collapsed, ol-uncollapsed, ol-unselectable ..." official style classes in your elements. So if i want to add a panel/div on map, i should set them as well?

I am just trying to make ['this profile'](https://viglino.github.io/ol-ext/examples/control/map.control.profil.html) or ['this legend'](https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html) style mechanism except panel. Because i want to show custom statistic panel in there (not profile or legend list). I wonder that how to make own panel to show it on map like you already achieved above.
Thanks!

**Comment by Viglino** [comment]
A div on the map is a ol/control. You can use a ol/contro/Control as parent to place it on the map: when the control is added to the map, the div will be placed onto the map. 

You can also use any div and control it's position using CSS as well...
ol_ext_element is a just shortcut to create/modify elements (you can also use jQuery as well).

You can also use an [ol/control/Overlay](https://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html) to place information on the map... use CSS to customize its position/appearance.

@+
