### ISSUE TITLE
Newbie question to integrate ol-ext with OL5

### ISSUE THREAD

**Issue by Kai-Behncke** [Viglino/ol-ext#374]
Dear community, I try to get ol-ext to run with OL5.

So far OL5 worked well. I installed it as a parcel bundle via "npm install ol" and can create applications easily. Now I also installed olext via "npm install ol-ext". But how can I integrate the ol-ext-functions in OL5?

In my OL5-index.js I integrate modules mainly via:

``  import Map from 'ol/Map.js';
      import View from 'ol/View.js';
      import {getCenter} from 'ol/extent.js'; ``

How can I e.g. integrate the nice Print-control (button)?
import ol_control_Print from ???

Could anybody give me a hint please?
Thank you very much, Kai

**Comment by Viglino** [comment]
Just as any module: 
1. import the module from the lib (here ol-ext)
2. then use it.

ol-ext use same convention as ol (import from ol-ext / namespace / Class)
```javascript
import ol_control_Print from 'ol-ext/control/Print'
...
const ctrlPrint = new ol_control_Print();
map.addControl(ctrlPrint);
```
See example with [Webpack](https://github.com/darkscript/ol-ol-ext-webpack-example) or [Parcel](https://github.com/Viglino/ol-ext-parcel-bundler)

**Comment by Kai-Behncke** [comment]
First of all thank you very much for your response.
But so far, I don`t get the print-button in my application. :-(
To get it to run might it be that I have to include some more code/modules/functions?

The only thing I imported from ol-ext is "now ol_control_Print".
Do I need some more?
In my index.js I have:

``
import Map from 'ol/Map.js';
import View from 'ol/View.js';
import {getCenter} from 'ol/extent.js';
import {transform} from 'ol/proj.js';
import TileLayer from 'ol/layer/Tile.js';
import OSM from 'ol/source/OSM.js';
import WKT from 'ol/format/WKT.js';
import {defaults as defaultControls} from 'ol/control.js';


import ol_control_Print from 'ol-ext/control/Print.js'



import {ScaleLine} from 'ol/control.js';
import ImageLayer from 'ol/layer/Image.js';
import ImageWMS from 'ol/source/ImageWMS.js';
import TileWMS from 'ol/source/TileWMS.js'; 
import Static from 'ol/source/ImageStatic.js';
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4.js';
import {get as getProjection} from 'ol/proj';
import BingMaps from 'ol/source/BingMaps.js';
import * as olProj from 'ol/proj';
import GeoJSON from 'ol/format/GeoJSON.js';
import VectorLayer from 'ol/layer/Vector.js';
import VectorSource from 'ol/source/Vector.js';
import {Circle as CircleStyle,Fill, Stroke, Style, Text} from 'ol/style.js';

proj4.defs('EPSG:25832', '+proj=utm +zone=32 +x_0=-32000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs');
register(proj4);

          var osm = new TileLayer({
        source: new OSM()
      });


    var view = new View({
	       center: [rechtswert,hochwert],
        zoom: mzoom,
        projection: 'EPSG:25832'
      });
      var map = new Map({
          
        layers: [osm],
        target: 'map',
        view: view
      });

         map.addControl(new ScaleLine({units: 'metric'}));

const printControl = new ol_control_Print();

map.addControl(printControl);





    printControl.on('print', function(e) {
      $('body').css('opacity', .1);
	  alert ("hello");
    });
    printControl.on(['print', 'error'], function(e) {
      $('body').css('opacity', 1);
	  alert ("hello2");
 ......

	 
    });
``

**Comment by Kai-Behncke** [comment]
Allright, I got it.
In the index.html I needed:


<!DOCTYPE html>
<html>
<head>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.2.61/jspdf.min.js"></script>

		   
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<link
rel="stylesheet"
href="https://viglino.github.io/ol-ext//dist/ol-ext.css"
/>
<meta charset="utf-8">
<title>k,ais test</title>
<style>
    #image {
      background-color: #eee;
      padding: 1em;
      clear: both;
      display: inline-block;
      margin: 1em 0;
    }

	  
</style>
....
......




In the index.js I use the file mentioned next:

import "ol/ol.css";
import Map from 'ol/Map.js';
import View from 'ol/View.js';
import {getCenter} from 'ol/extent.js';
import {transform} from 'ol/proj.js';
import TileLayer from 'ol/layer/Tile.js';
import OSM from 'ol/source/OSM.js';
import WKT from 'ol/format/WKT.js';
import {defaults as defaultControls} from 'ol/control.js';


import ol_control_Print from 'ol-ext/control/Print'



import {ScaleLine} from 'ol/control.js';
import ImageLayer from 'ol/layer/Image.js';
import ImageWMS from 'ol/source/ImageWMS.js';
import TileWMS from 'ol/source/TileWMS.js'; 
import Static from 'ol/source/ImageStatic.js';
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4.js';
import {get as getProjection} from 'ol/proj';
import BingMaps from 'ol/source/BingMaps.js';
import * as olProj from 'ol/proj';
import GeoJSON from 'ol/format/GeoJSON.js';
import VectorLayer from 'ol/layer/Vector.js';
import VectorSource from 'ol/source/Vector.js';
import {Circle as CircleStyle,Fill, Stroke, Style, Text} from 'ol/style.js';
        


proj4.defs('EPSG:25832', '+proj=utm +zone=32 +x_0=-32000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs');
register(proj4);

var osm = new TileLayer({
source: new OSM()
});

var view = new View({
center: [rechtswert,hochwert],
zoom: mzoom,
projection: 'EPSG:25832'
});
var map = new Map({
layers: [osm,wmsLayer3,wmsLayer2],
target: 'map',
view: view
});

var printControl = new ol_control_Print();

map.addControl(printControl);



    printControl.on('print', function(e) {
      $('body').css('opacity', .1);
	  alert ("hello");
    });
    printControl.on(['print', 'error'], function(e) {
      $('body').css('opacity', 1);
	  alert ("hello2");
    });
