### ISSUE TITLE
Issue on touch draw example

### ISSUE THREAD

**Issue by digoburigo** [Viglino/ol-ext#377]
Hello

The example of touch draw ([https://viglino.github.io/ol-ext/examples/mobile/map.interaction.drawtouch.html](url)) its not working properly at the moment.
The drawing part its working but the center overlay dont show up and there is the following error in the console:
```
ol-ext.js:12276 Uncaught TypeError: Cannot read property 'save' of undefined
    at ol.interaction.DrawTouch.ol.interaction.CenterTouch.drawTarget_ (ol-ext.js:12276)
    at e.dispatchEvent (Target.js:112)
    at e.dispatchRenderEvent (Composite.js:76)
    at e.renderFrame (Composite.js:128)
    at e.renderFrame_ (PluggableMap.js:1166)
    at e.<anonymous> (PluggableMap.js:186)
```
So, this is a issue with OL6?

Thanks

**Comment by Viglino** [comment]
It is an ol6 issue.
I've pushed corrections that should solve the issue.

**Comment by digoburigo** [comment]
Hello, its not related to the bug, but its a question about DrawTouch events, there is a 'drawend' event listener so i can do stuff after the draw is finished?

**Comment by Viglino** [comment]
No events are triggered...
I'll try to add it asap...
