### ISSUE TITLE
LayerSwitcherImage unnecessarily fetches preview tiles on every extent change or style update

### ISSUE THREAD

**Issue by geomC** [Viglino/ol-ext#383]
Hey there, thanks for this great lib!

We are using ol-ext together with `ol@6.1.0` to set up a baseLayerSwitcher using `ol-ext/control/LayerSwitcherImage`.
It gets added to the map controls like so:
```javascript
return new OlMap({
      view: new OlView({
        // some config
      }),
      layers: mapConfig.layers,
      controls: defaultControls({attribution: false})
        .extend([this.attribution, this.layerSwitcher]),
      target: elementId
    });
```

Switching the baselayers works like a charm. 
But I am noticing that on every map move and on every style update of a feature (triggered by a hover interaction), preview tiles for each baseLayer item get fetched. So we have a lot of unneccessary requests since the preview tiles are showing a random extent (Le Havre, France) and not the current map extent.

I tried to disable the behaviour by looking into the options provided by the class or its parent class [`LayerSwitcher`](https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.LayerSwitcher.html). There seems to be no suitable option.

Any idea how to prevent this behaviour?

**Comment by Viglino** [comment]
On layer changes the LayerSwitcher is redrawn and the preview is recalculated (as it is the same it should not been reloaded).
I con't notice it appends on map move... only the visibility is tested...
See #252 for more info.
