### ISSUE TITLE
Flashlight does not work on demo site

### ISSUE THREAD

**Issue by emcastro** [Viglino/ol-ext#384]
The demo for Flashlight does not work:
https://viglino.github.io/ol-ext/examples/misc/map.flashlight.html

It fails on `postcompose_` :
```js
ol.interaction.Flashlight.prototype.postcompose_ = function(e)
{	var ctx = e.context;  // e.context is undefined
	var ratio = e.frameState.pixelRatio;
	var w = ctx.canvas.width;   // Uncaught TypeError: Cannot read property 'canvas' of undefined
```

Note: 
The page https://openlayers.org/en/latest/apidoc/module-ol_render_Event-RenderEvent.html states that:
> `postcompose`
> Triggered after all layers are rendered. The event object will **not** have a **context** set.

**Comment by Viglino** [comment]
It seems there is still some issue with ol6.
I'll try to fix it asap...
