### ISSUE TITLE
Overview ol-ext 3.1.7 openlayers 6.1.1 (OlExtAngular)

### ISSUE THREAD

**Issue by tactusoft** [Viglino/ol-ext#385]
With this new version and I click on the overview the map disappears. If I pan on the map it returns to normal.

`export class OverviewComponent implements OnInit {

  /** Map id
   */
  @Input() mapId: string;

  /** Define the service
   */
  constructor(
    private mapService: MapService,
    @Host()
    @Optional()
    private mapidService: MapidService,
    private elementRef: ElementRef
  ) { }

  /** Add the control to the map
   */
  ngOnInit() {
    // Get the current map or get map by id
    const map: OlMap = this.mapService.getMap(this.mapidService || this.mapId);
    // Get the target if outside the map
    const target = this.elementRef.nativeElement.parentElement ? this.elementRef.nativeElement : null;
    // Create the control
    var overview = new Overview(
      {
        layers: this.mapService.getLayers(),
        minZoom: 8,
        maxZoom: 20,
        rotation: false,
        align: 'bottom-right',
        panAnimation: "elastic",
        target: target
      });
    map.addControl(overview);
  }
}`

**Comment by tactusoft** [comment]
I'm reviewing and the layer disappears @Viglino

**Comment by Viglino** [comment]
One breaking change of ol6 is that layers can only be added to a single map. Thus be sure `this.mapService.getLayers()` return a new set of layer to add to the Overview map.

**Comment by tactusoft** [comment]
I did not understand what a shame. :-(
