### ISSUE TITLE
Openlayers 6 printControl vector opacity

### ISSUE THREAD

**Issue by JNogueira92** [Viglino/ol-ext#387]
When printing the map with vector layers in it, they always appear with opacity as 1.
So this is a print screen of the window, as you can see it has a base layer only and no vector layer showing because has opacity 0.
![printscreen](https://user-images.githubusercontent.com/12235333/68964044-4e82ac00-07d0-11ea-971d-26e9c0285237.jpg)

And this is what I get when using the print control
![map](https://user-images.githubusercontent.com/12235333/68964098-68bc8a00-07d0-11ea-9c57-14ec6aa71af7.png)

**Comment by Viglino** [comment]
There was a bug when retrieving canvas opacity. 
Now it should work. 😃

**Comment by JNogueira92** [comment]
Correct me if I'm wrong but I believe the || operator sees 0 as a false statement making it return the next true value. So I believe on your code correction

ctx.globalAlpha = parseFloat(c.parentNode.style.opacity) || 1;

if c.parentNode.style.opacity is 0 the statement will return 1 which is incorrect as the alpha should be 0 making it show the layer. I would suggest this as fix:

ctx.globalAlpha = isNaN(parseFloat(c.parentNode.style.opacity)) ? 1 : c.parentNode.style.opacity;

If the value from opacity is not parsable return 1, if it is, return the value

**Comment by Viglino** [comment]
Right!
I'll try to push a fix asap.

**Comment by cimse-diego** [comment]
hi

**Comment by cimse-diego** [comment]
hola Viglino tengo un problema estoy trabajando con open layer 4.6.5 y utilizo ol-ext.js para impresion del map, pero me da un error en la funcion:  printControl.on(['print', 'error'], function(e) {    . no imprime el mapa y no me da algun error. mi pregunta es si es compatible ol 4.6.5 con esta libreria de impresion de mapas? gracias por tu ayuda.

**Comment by cimse-diego** [comment]
hello I have a problem I am working with open layer 4.6.5 and I use ol-ext.js to print the map, but it gives me an error in the function: printControl.on (['print', 'error'], function (e ) {. It does not print the map and it does not give me an error. My question is if it is compatible with the 4.6.5 ol 4.6.5 with this map printing library? Thanks for your help.

**Comment by Viglino** [comment]
Print control does not work with ol < 5 because there is no event to check if the map rendering is complete in these versions.
But there is a hack to make it work by using the `immediate` options when creating the control. Thus, printing will start immediately and print what you see on the screen, without waiting for all layers to load. It's not perfect as some tiles may be missing but runs.
```javascript
var printCtrl = new ol.control.Print({
  immediate: true
});
printCtrl.on('print', function(e) { console.log(e) });
```
