### ISSUE TITLE
SnapGuides interaction update to be in compliance to OpenLayers 6

### ISSUE THREAD

**Issue by wguilen** [Viglino/ol-ext#388]
Hello,

It seems that the overlay layer on [`SnapGuides`](https://github.com/Viglino/ol-ext/blob/master/src/interaction/SnapGuides.js) interaction needs to be updated to be in compliance with OpenLayers v6+. It uses a `Vector` layer with `renderMode` equaling to `image`, and I think it should be using a `VectorImage` layer, as stated in [this changelog](https://github.com/openlayers/openlayers/blob/master/changelog/v6.0.0.md#removal-of-the-rendermode-option-for-vector-layers).

Best regards.

**Comment by Viglino** [comment]
ol-ext is suitable with ol5/6 this means it can't use VectorImage that doesn't exist in ol5.
Maybe I can add a layer class as option.

**Comment by Viglino** [comment]
Use `ol/layer/VectorImage` as `vectorClass` option when creating the interaction to improve drawing performances.
```javascript
import VectorImage from 'ol/layer/VectorImage'
import SnapGuide from 'ol-ext/interaction/SnapGuides'

const snap = new SnapGuide({ vectorClass: VectorImage });
```

**Comment by wguilen** [comment]
Sure, thanks!
