### ISSUE TITLE
LayerSwitcher custom

### ISSUE THREAD

**Issue by GarridoM** [Viglino/ol-ext#392]
Hi! I think I saw that It is possible to write the porcentage of the opacity near the slider, How can I do this?

Other cuestion is that I would like to know if is it possible to remove the checkbox like an option?

Thanks in advance.

**Comment by Viglino** [comment]
The style of the control can be customize using CSS.
The layerswitcher-opacity-label is just hidden by default. You have to add this in your CSS:
```css
.layerswitcher-opacity-label {
  display: block;
}
```
For more info, see: https://viglino.github.io/ol-ext/examples/control/map.switcher2.html
