### ISSUE TITLE
Transform unexpected behavior at higher zoom level

### ISSUE THREAD

**Issue by mtburkett** [Viglino/ol-ext#393]
Hi
Thank you for writing this great extension. I am seeing an unexpected behavior with the transform interaction. When I attempt to scale or stretch a polygon feature the feature jumps off the map at the first slight movement and then moves around in strange ways. I am creating the interaction like the following:

`
self.transformInteraction = new ol.interaction.Transform ({
          enableRotatedTransform: true,
          layers: [self.drawLayer],
          hitTolerance: 2,
          keepAspectRatio: ol.events.condition.always,
          rotate: true,
          scale: true,
          stretch: true,
          translateFeature: false, 
          translate: false,
        });
self.map.addInteraction(self.transformInteraction);
`

When I select the item for transformation it looks like this:
![Image 023](https://user-images.githubusercontent.com/25694364/69578023-9c03d380-0f9d-11ea-9dbf-4eb1ef41c8d3.png)

As soon as I move the mouse a tiny bit the feature jumps beyond my viewport.
![Image 024](https://user-images.githubusercontent.com/25694364/69578096-bf2e8300-0f9d-11ea-88c9-ea987faf8581.png)

The map is at a zoom level of 16 in the first picture and at 14 in the second picture.

Am I missing something, or is this a bug?

Thank you

**Comment by mtburkett** [comment]
I have also observed that I do not see this issue if I set enableRotatedTransform to false.

**Comment by mtburkett** [comment]
Further investigation reveals that the farther from the center the transformed feature is, the more severe the unwanted behavior.

**Comment by Viglino** [comment]
It seems there is a bug. 
I'll try to investigate asap.

**Comment by mtburkett** [comment]
The last commit seems to have fixed the problem. Thank you very much!
