### ISSUE TITLE
MapZone issue

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#398]
Hey! I am working on the MapZone object. Actually I modified the style according to my requirements, but I am not able to understand how to use "my zones". I mean: 

```
  var zone = new ol.control.MapZone({
    layer: new ol.layer.Tile({
      source: new ol.source.XYZ({
        url: 'https://wxs.ign.fr/pratique/geoportail/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix={z}&TileCol={x}}&TileRow={y}'
      })
    }),
    zones: ol.control.MapZone.zones.DOMTOM
  });
  map.addControl(zone);
```

I would like to remove the default zones in order to use mine. Let's assume I have three zones in EPSG 4326: 
- Florence (lon: 11.255356, lat: 43.784579)
- Rome (lon: 12.492760, lat: 41.902073)
- Naples (lon: 14.270193, lat: 40.852202)

How can I create my array of zones? Thank you

**Comment by Viglino** [comment]
When creating a MapZone control you have to specify a layer and a list of zone you want to show.
There is a set of defined zone (ol.control.MapZone.zones) but you can set your own ones.
A zone is a { title: < string >, extent: < ol/extent > }  (see http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.MapZone.html)

```javascript
var zone = new ol.control.MapZone({
  layer: new ol.layer.Tile({
    source: new ol.source.OSM()
  }),
  zones: [{
    title: 'Rome',
    extent: [12.29, 41.79, 12.69, 41.99]
  },{
    title: 'Florence',
    extent: [11.15, 43.72, 11.34, 43.81]
  }]
});
map.addControl(zone);
```
See: https://codepen.io/viglino/pen/bGNdYWQ

**Comment by Teorizzi0** [comment]
Thank you so much! It works perfectly
