### ISSUE TITLE
Cannot read property 'addEventListener' of null on Synchronize.setMap

### ISSUE THREAD

**Issue by wondie** [Viglino/ol-ext#400]
So I was trying to synchronize maps but I got the error below. 
ol-ext - v3.1.7
ol - v4.6.5

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at ol.interaction.Synchronize.setMap (ol3-ext.min.js?_dc=20191107172247:9)
    at K.<anonymous> (ol.js?_dc=20191107172247:123)
    at B.b (ol.js?_dc=20191107172247:46)
    at B.Sc.b (ol.js?_dc=20191107172247:49)
    at B.k.Re (ol.js?_dc=20191107172247:53)
    at B.k.push (ol.js?_dc=20191107172247:53)
    at K.k.Nf (ol.js?_dc=20191107172247:124)
    at constructor.handler (ComparisonSelectorWindow.js?_dc=20191107172247:234)
    at Object.callback (Util.js?_dc=20191107172247:108)
    at constructor.fireHandler (Button.js?_dc=20191107172247:1648)
ol.interaction.Synchronize.setMap @ ol3-ext.min.js?_dc=20191107172247:9
(anonymous) @ ol.js?_dc=20191107172247:123
b @ ol.js?_dc=20191107172247:46
Sc.b @ ol.js?_dc=20191107172247:49
k.Re @ ol.js?_dc=20191107172247:53
k.push @ ol.js?_dc=20191107172247:53
k.Nf @ ol.js?_dc=20191107172247:124
handler @ ComparisonSelectorWindow.js?_dc=20191107172247:234
callback @ Util.js?_dc=20191107172247:108
fireHandler @ Button.js?_dc=20191107172247:1648
onClick @ Button.js?_dc=20191107172247:1626
fire @ Event.js?_dc=20191107172247:475
fire @ Dom.js?_dc=20191107172247:436
publish @ Dom.js?_dc=20191107172247:390
publishDelegatedDomEvent @ Dom.js?_dc=20191107172247:414
doDelegatedEvent @ Dom.js?_dc=20191107172247:466
onDelegatedEvent @ Dom.js?_dc=20191107172247:448
method @ Function.js?_dc=20191107172247:148
```

**Comment by Viglino** [comment]
This is because you insert the interaction before assigning a target to the map...
I'll try to prevent from crashing in such a case.

**Comment by wondie** [comment]
When I created the maps, I have already assigned target at the creation stage. Should I assign again when syncing?

**Comment by Viglino** [comment]
Can you place a code sandbox or jsfiddle example ?

**Comment by Viglino** [comment]
Seems to run here: https://codepen.io/viglino/pen/xxbZpPr

**Comment by wondie** [comment]
I don't know why but it is not running when I use for loop. This used to work in ol3 and earlier version of ol-ext. 
https://codepen.io/wondim/pen/dyPGJLq

**Comment by Viglino** [comment]
This runs: https://codepen.io/viglino/pen/rNaxJoZ

**Comment by wondie** [comment]
Unfortunately, I copy pasted your code but it is not working in my application.

**Comment by wondie** [comment]
I found the cause of the problem. Running the syncronization code after the map window is shown fixed the problem. I think even though the maps are created and they had target, it considered it as not having target because it is not shown in the interface. By the way, I use ExtJS.
