### ISSUE TITLE
Heatmap or HexBin is good choice to show crowded areas by color in OL?

### ISSUE THREAD

**Issue by asimus90** [Viglino/ol-ext#401]
Hey, i am confused. 
I have a lot of Points to show users history on map. I already show them by LineString on map but now i should create colored areas and i can show that where do you travel mostly and where  do you travel less. (could be like that yellow to pink and then red which is mostly travelled area.)
I was lookin for heatmap that shows vector source colored on the map. But i just met with hexbin but i don't really know if it is good for me. Can i choose circle or rectangle instead hexagonal?
Is there a solution for something like that in openlayers and in this awesome lib ol-ext? i couldn't find any example by googling.

Hope you help me @Viglino !
Thanks in advice.

**Comment by Viglino** [comment]
Binning is a convenient way to display large sets of points on a map.

See [MapBox article Binning: An Alternative to Point Maps](https://blog.mapbox.com/binning-an-alternative-to-point-maps-2cfc7b01d2ed) or [How to use spatial binning for complex point distribution maps](https://www.tableau.com/about/blog/2017/11/data-map-discovery-78603). You can also look at [ESRI blog](https://www.esri.com/arcgis-blog/products/data-management/mapping/strategies-to-effectively-display-large-amounts-of-data-in-web-apps/).

You can use [hexagon](https://viglino.github.io/ol-ext/examples/layer/map.layer.hexbin.html) or [square grid](https://viglino.github.io/ol-ext/examples/layer/map.layer.gridbin.html) or even [any polygonal partition](https://viglino.github.io/ol-ext/examples/layer/map.layer.featurebin.html).
It depends on what you want to show. Ideally you should use [equal area bins](https://viglino.github.io/ol-ext/examples/layer/map.layer.insee.html).

You can't use circle as it is not a partition (circles will overlap). Hexbin are a good approximation to circle.

PS: you can also show the result [using 2.5D style](https://viglino.github.io/ol-ext/examples/map/map.layer.3D.2.html) to display accumulation more effectively...

@+

**Comment by asimus90** [comment]
i've tried ol.layer.heatmap and hexgrid from ol-ext. both of them been just freezed with over 20k points.
In normal case, i have a LineString (has ~20k coordinates in) and i am trying to show the area or points with density. Such as you drive all day but you visit some street/place/mall more so i want to show these area darker(darken red or smth). There are already hundreds of points on there. 
Heatmap looks fine for me but if i play with a few number of points/coordinates.

i see a solution that rid of LineString to 3 (started point, mid-linestring and end point) and solve this problem with three points. But it doesn't handle ~20k points density at all.

Do you know any solution for something like this? Thanks @Viglino

**Comment by Viglino** [comment]
Hi,
Handling huge number of data is quite tricky and you have to use different strategy depending on the map resolution to make sure your browser can render it, ie. the number of data should not exceed the limit it can draw without freezing. This will include pre-calculating grids for scale ranges.
As an example, this repo handles 2.3 millions squares: https://github.com/Viglino/insee-map
