### ISSUE TITLE
Can not unsync maps?

### ISSUE THREAD

**Issue by kambeel** [Viglino/ol-ext#402]
Hello,

I tried syncing multiple maps using your example......no problem at all!
When I try to unsync them they are still synced. 
(btw I'm using OL 6.1.1)

```
function syncMaps(MAPnr){ 
        allMaps = [];

        $.each(MAParray, function (index, nr) {
            if (nr !== MAPnr) {
                allMaps.push(window['map-' + nr]);
            }
        });
        window[('map-'+MAPnr)].addInteraction( new ol.interaction.Synchronize({maps: allMaps}) );
    };


function unsyncMaps(MAPnr){
       window[('map-' + MAPnr)].removeInteraction(new ol.interaction.Synchronize({maps: null}));
    });
```

What am I doing wrong?

**Comment by kambeel** [comment]
Also tried to unsync by setting maps to null using your setMap function.......not working either (probably because I did not use it correctly?)........

`ol.interaction.Synchronize.setMap(null)`

(btw I'm using the latest version of ol-ext (3.1.8))

**Comment by Viglino** [comment]
You have to remove the interaction you put in the map not a new one...
```javascript
var sync = new ol.interaction.Synchronize({maps: allMaps});
// Add the interaction to the map
map.addInteraction(sync);
// then remove the interaction you've added first
map.removeInteraction(sync);
```

**Comment by kambeel** [comment]
Thx a lot........working now ;-) !!
