### ISSUE TITLE
Interference between two cluster interaction.select events

### ISSUE THREAD

**Issue by GianMen91** [Viglino/ol-ext#404]
I have a problem with cluster interactions: on click on the cluster the map should zoom in to the cluster unless that the cluster contains 2 objects with the same latitude and longitude.
In this last case, it should spread the cluster with an animation.

The 2 interactions, separately, are working perfectly, my problems start when I have to mix them, so to obtain the behaviour mentioned before. 

My last result is that on clicking on the cluster the map doesn't zoom in to it if the cluster contains objects with the same latitude and longitude BUT it is not spread the cluster.
If, instead, I comment the code line concern the zoom (//this.map.addInteraction(clusterClick);), the cluster spreading works.

This is my code:

            // Select interaction to spread cluster out and select features
            this.selectCluster = new ol.interaction.SelectCluster({
              // Point radius: distance between the features
              pointRadius:37,
              animate: true,
              style: this.selectedClusterStyle,
            });
            this.map.addInteraction(this.selectCluster);
    
             var clusterClick = new ol.interaction.Select({
                  layer: this.clusterLayer,
                  style: this.selectedClusterStyle
              });
    
             clusterClick.on('select',function(event) {
               var eventFeature = event.selected[0];
               var features = eventFeature.get('features');
               if (features.length>1){
    
                   var extent = ol.extent.createEmpty();
                   var i = 1;
                   var twoExtentWithSameCoordinate = false;
    
                   lat = parseInt(features[0].getGeometry().flatCoordinates[0],10);
                   long = parseInt(features[0].getGeometry().flatCoordinates[1],10);
                   ol.extent.extend(extent, features[0].getGeometry().getExtent());
    
                   while(i<=features.length){
                        if(features[i]){
                            ol.extent.extend(extent, features[i].getGeometry().getExtent());
                            if((parseInt(features[i].getGeometry().flatCoordinates[0],10) == lat) && (parseInt(features[i].getGeometry().flatCoordinates[1],10) == long)){
                                    twoExtentWithSameCoordinate = true;
                            }
    
                        }
                        i++
                   }
                   if(twoExtentWithSameCoordinate == false){
                        //CASE A
                        this.getMap().getView().fit(extent, {padding: [150, 150, 150, 150]});
                   }else{
                        //CASE B
                        //it should spread the cluster
                        clusterClick.getFeatures().clear();
                        this.selectCluster.getFeatures().push(features);
                   }
               }else{
                    clusterClick.getFeatures().clear()
                    var record = eventFeature.values_.features[0].values_.record;
                    var dialog = Ext.create('Traccar.view.dialog.Beacon');
                    dialog.objectStore = Ext.getStore('Beacons');
                    dialog.down('form').loadRecord(record);
                    dialog.show();
               }
             });
             this.map.addInteraction(clusterClick);

to me seems that the 2 select interactions interfere with each other compromising the behaviour.
But I can't figure out how to handle it

**Comment by Viglino** [comment]
If you're using 2 interaction at one time they will interfere. 
Only one should be activated at a time.
Try to deactivate the cluster interaction `this.selectCluster.setActive(false);` 
and use it as a container for rendering cluster (push or remove features at will).
If you don't, when selecting a feature both interaction will catch the event and the second one will overwrite what is done by the first one.

**Comment by GianMen91** [comment]
but so I should make clusterClick.setActive(false) inside clusterClick itself:
because here (in clusterClick) should be something like that:

 }else{
   //it should spread the cluster
   clusterClick.getFeatures().clear();
   this.clusterClick.setActive(false);
   this.selectCluster.setActive(true);
   this.selectCluster.getFeatures().push(features);
}

but of course, I can not. Maybe there is a way to spread the cluster pragmatically directly from clusterClick so to avoid to use selectCluster and use only one interaction?

**Comment by Viglino** [comment]
You can't have 2 interactions active at a time (or they will both select features at one time).
Deactivate one just after you create it and let the other interaction drive the click.
The second interaction will only be used to

**Comment by GianMen91** [comment]
In case I want to delete completely  "this.selectCluster" there is a way to spread the Cluster pragmatically? Because I am using selectCluster only for the purpose of spread the cluster with animation, but if I can do the same directly in clusterClick without use selectCluster would be better I think.

**Comment by Viglino** [comment]
You can simulate a selection:
```javascript
// Select a cluster feature (f)
this.selectCluster.selectCluster({ selected: [ f ] })
```

**Comment by GianMen91** [comment]
Unfortunately it gave me this error:

**Comment by GianMen91** [comment]
I also found out here https://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.SelectCluster.html#toc4__anchor that 

> animateCluster_(the): animate the cluster and spread out the features

 so I tried to do ` clusterClick.getFeatures().animateCluster_(coordinate);`

but also in this case I had the error `clusterClick.getFeatures(...).animateCluster_ is not a function`

**Comment by Viglino** [comment]
In your code `clusterClick` is a standard Select interaction that has no animation function.
`this.selectCluster` is a SelectCluster interaction (with animation. You have to use this to animate the cluster feature.

**Comment by GianMen91** [comment]
True! I edited my code like that and now it works! 

```
 var clusterClick = new ol.interaction.SelectCluster({
              layer: this.clusterLayer,
              style: this.selectedClusterStyle,
              pointRadius:37,
        });

        clusterClick.on('select',function(event) {
           var eventFeature = event.selected[0];

           if(eventFeature != null){
               var features = eventFeature.get('features');
               if (features.length>1){
                   var extent = ol.extent.createEmpty();
                   var i = 1;
                   var twoExtentWithSameCoordinate = false;
                   lat = parseInt(features[0].getGeometry().flatCoordinates[0],10);
                   long = parseInt(features[0].getGeometry().flatCoordinates[1],10);
                   ol.extent.extend(extent, features[0].getGeometry().getExtent());
                   while(i<=features.length){
                        if(features[i]){
                            ol.extent.extend(extent, features[i].getGeometry().getExtent());
                            if((parseInt(features[i].getGeometry().flatCoordinates[0],10) == lat) && (parseInt(features[i].getGeometry().flatCoordinates[1],10) == long)){
                                    twoExtentWithSameCoordinate = true;
                            }
                        }
                        i++
                   }
                   if(twoExtentWithSameCoordinate == false){
                        clusterClick.getFeatures().clear();
                        this.getMap().getView().fit(extent, {padding: [150, 150, 150, 150]});
                   }
               }else{
                    clusterClick.getFeatures().clear()
                    var record = eventFeature.values_.features[0].values_.record;
                    var dialog = Ext.create('Traccar.view.dialog.Beacon');
                    dialog.objectStore = Ext.getStore('Beacons');
                    dialog.down('form').loadRecord(record);
                    dialog.show();
               }
           }
        });
        this.map.addInteraction(clusterClick);
```

Thank you very very much for all the tips and your help!!!

**Comment by cazacugmihai** [comment]
@Viglino: It would be nice if this behavior could be activated by using an option (clicking a cluster it will expand it if there are at least two markers with different coordinates; otherwise it will fit the markers' geometry into the view and spread the cluster out). 
Isn't it a typical usage of clusters? 

Thank you!

**Comment by Viglino** [comment]
@cazacugmihai a select interaction is an interaction to select. With a cluster it spread out to allow selection in it. It's up to the app to know what to do with this selection... 
If you zoom in, the clusters will change and you can't spread the initial one out. 
If you have many feature really near (or even superimposed) you will zoom to much and you may want to limit the zoom.
...
One way would be to add an helper function to get the cluster extent to help zoomin to this extent on click...

**Comment by Viglino** [comment]
I've added `getClusterExtent` to the SelectCluster interaction, you can use it to zoom on select:
```javascript
selectCluster.on('select', function(event) {
  var feature= event.selected[0];
  var extent = selectCluster.getClusterExtent(feature);
  if (extent) {
    map.getView().fit(extent);
  } else {
    // do something
  }
})
```

**Comment by cazacugmihai** [comment]
What a great job! It works perfectly! Thank you!
