### ISSUE TITLE
Support for PopupFeature attribute highlighting and copying?

### ISSUE THREAD

**Issue by vitale232** [Viglino/ol-ext#405]
First off, ol-ext is great, so thanks!

I've integrated the `PopupFeature` into an Angular 8 application that's using OpenLayers 6 for mapping. Once it was up and running in my app, I noticed that you can't highlight/copy values out of the popup table using the browser cursor. This behavior is also present in the live example that I based my code off of, which is here: https://viglino.github.io/ol-ext/examples/popup/map.popup.feature.html (tested on Chrome and Firefox)

Is there a way to allow users to copy and paste attributes out of the Popup Feature's table?

Thanks!

**Comment by Viglino** [comment]
ol6 add a `user-select: none` to the map viewport to avoid selection on map features.
You have to add your own `user-select` property to your CSS to let select information in popups.
```css
.ol-popupfeature {
  user-select: text;
}
```

**Comment by vitale232** [comment]
Thanks @Viglino! That fixed the issue for me.
