### ISSUE TITLE
ol.filter unexpected behaviour when rotating the map

### ISSUE THREAD

**Issue by majkshkurti** [Viglino/ol-ext#408]
Hi
I upgraded to the last version of ol-ext which supports ol6, but noticed a strange behaviour with the ol.filter when rotating the map. 
It seems that the mask area doesn't follow up with the map rotation.
Thanks

![gif](https://user-images.githubusercontent.com/32641116/71713670-fd278e00-2e0a-11ea-90db-077694dd685f.gif)

**Comment by Viglino** [comment]
Try to see what's up asap...

**Comment by Viglino** [comment]
Fix in last commit
