### ISSUE TITLE
How to get features' id in current view's extent? (ol-ext cluster is on!)

### ISSUE THREAD

**Issue by asimus90** [Viglino/ol-ext#409]
I am just stucked while updating features through socket. When too many (hundreds of features) updated one by one, the map freezes.
I thought that if i send features' ids to socket those are in current extent, it doesn't make too much weight on map while updating.

So, is there any way to get features' ids from current extent?
Thanks in advance!

**Comment by Viglino** [comment]
Use [getFeaturesInExtent()](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#getFeaturesInExtent) to get all features whose bounding box intersects the provided extent. Note that this returns an array of all features intersecting the given extent in random order (so it may include features whose geometries do not intersect the extent).

**Comment by asimus90** [comment]
İ use it now. But updating features one by one is still hard in openlayers.  Data comes from socket asynchronously. 
First way: I update features as below:

`feature.getGeometry().setCoordinates(ol.proj.transform([data.longitude, data.latitude], 'EPSG:4326', 'EPSG:3857'));`

in clusterSource. For 10 to 20 features  i see no problem on the map. But with hundreds of features or more  it freezes the map.

Second way: I have tried also put all features in a global array and update them as below:

```
    // @data: is an updated feature here. (updates are for position,direction and a custom state)
    var index = globalFeaturesArray.findIndex(feature => feature.getId() == data.getId());
    globalFeaturesArray[index] = data; // new features' been set in global array
```
in parallel, setIntervals is running it clears cluster source and add globalFeaturesArray to cluster again. It works good but not with 1k features. When you send 1k updated features to this update mechanism(find in array and replace it. you can see in above code snippet) again about one second from socket server. The replace period is not finished yet before the new updates come. Because finding and replacing/updating in array takes much time and map is unresponsive along this period.

Do you know any better solutions than updating features from a websocket one by one or cache them and update them with an interval. I don't know real-world use case of openlayers but it doesn't support updating/moving features on the map "fluently/efficiently".

Thanks in advance.

**Comment by asimus90** [comment]
Someone told me that you can make a geoserver and update features in there and send them to openlayers client with WFS ? Do you think that solves my problem? Should i create a geoserver and update coordinates and send features back to openlayers clients and style in there? I have features those are moving on the map in a realtime. But this moving things are too many and that's the problem show them all on the map.

**Comment by Viglino** [comment]
The problem is that the cluster will be calculated on each modification and there is no way to tell the cluster to stop this. If you add / modify 100 features the cluster will be calculated 100 times.
You can either:
- overwrite the layer source to prevent refresh (see code below).
I think you just have to overwrite the refresh function and test if the source has to refresh or not.
Then: set a property (stopRefesh) on the cluster source, update your features, set the property back to false and refresh the source...
You can also create your own class from the parent Cluster source.
```javascript
// overwrite cluster source refresh function
var __saveClusterRefresh = ol.source.Cluster.prototype.refresh;
ol.source.Cluster.prototype.refresh =  function() {
  // don't refresh
  if (this.get('stopRefresh')) return;
  // refresh
  __saveClusterRefresh.call(this):
}
```
- switch the cluster source.
Create a new source, add features in it and switch the cluster source. The cluster will be calculated once on this source.
```javascript
myLayer.getSource().setSource(newSource);
```

**Comment by Viglino** [comment]
I don't think WFS will solve the problem as it won't refresh the source once loaded: there is no sockets mechanisms.

**Comment by asimus90** [comment]
Thanks @Viglino . I'll check both of them but i think i already tried that add features again after clear source. The problem is that queue and caching features. 
A new json object (include coordinates, direction, feature_id, state etc) comes from socket server to listener client. And i make it feature and replace it in globalArray or getFeatureById and update properties by this json object and setCoordinates re-calculate the cluster.

So they come one by one but constantly. (setTimeout 1ms delay). Creating an alternative source and add features there and switch source freeze the map for a while in this situation? or no difference than clearing old source and addFeatures?

I'll check all of your suggestions. Because you are really expert in openlayers world that i know!
Thanks again!!!

**Comment by Viglino** [comment]
Try to use a second source to store feature during load and switch sources at a larger interval to prevent freeze.

**Comment by asimus90** [comment]
`myLayer.getSource().setSource(newSource);`

i was trying to switch source on ol.layerAnimatedCluster with ol.source.cluster i've failed.
i have also tried set ol.source.vector on ol.source.cluster. But both of them just fail.
Am i missing something while switching?

**Comment by Viglino** [comment]
Here is an example to update features and only refresh the source once every 2s: https://codepen.io/viglino/pen/qBEKRmm
- The features are stored in an array with there coordinates (when changed).
- `updateFeature` will update one coordinate each 10ms
- `updateSource` will stop cluster refresh, change features coordinate (when changed) and force refresh every 2s
