### ISSUE TITLE
layerswitcher cant select a option when drawed

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#410]
Hi,

I set a select element in layerswitcher and the switcher always triggered 'drawlist' event , that makes me cant select it . 

Is it a html element original event problem or ...??

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10682896/72492472-47bbf800-3858-11ea-8194-bb0d2fe8a9cb.gif)

And i'll use a input (yeah , its behavior is lose focus .) instead of select as a temprary solution.

Do you have any better solutions?

Thank you!

**Comment by Viglino** [comment]
Can't see any issue here: https://codepen.io/viglino/pen/MXYmxZ
Make sure an other input take the click event
