### ISSUE TITLE
DayNight example

### ISSUE THREAD

**Issue by sign0** [Viglino/ol-ext#411]
Hi, I would like to use your DayNight module soon. Unfortunately, the documentation and its example do not seem to have been pushed on the master or in the latest npm release.

Can you give an example to make it work ?

Thanks,
Adrien

**Comment by Viglino** [comment]
OK it seems the example file is missing 😢 
I'll push it asap.
You can find the doc in the js: https://github.com/Viglino/ol-ext/blob/master/src/source/DayNight.js
You just have to create a source with a date time:
```javascript
var layer = new ol.layer.Vector({
  source: new ol.source.DayNight ({ time: new Date() })
}
```
You can use `setTime` method to change the date.
You can also pass a `step` option on creation to have a higher coord precision (default 1 degree). Set it to .5 to have a point each .5 degree.

**Comment by Viglino** [comment]
Example is now online: https://viglino.github.io/ol-ext/examples/layer/map.daynight.html

**Comment by TagLoomis** [comment]
How can we change the Grayline to civil, nautical and/or astronomical ?
