### ISSUE TITLE
Layer Switcher group's visibility

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#412]
Hi! 

I am troubling with a layer switcher inspired by the ol-ext: LayerSwitcher. I do not understand how to realise the following task: I would like that if the "parent" layer ("Pineta Park" in pic 1) is not checked, then the "sons" layers ["Info Point" and "Area" layers] should be unclickable (maybe written in different transparency). 

Otherwise, if the "parent" layer is checked, the sons must become clickable as in the pic 2

pic 1:  
![Screenshot (290)](https://user-images.githubusercontent.com/44029782/73553733-bac59100-444a-11ea-8cdd-3ccf2bfce2af.png)

pic 2: 
![Screenshot (292)](https://user-images.githubusercontent.com/44029782/73553192-cbc1d280-4449-11ea-9cf1-e62be60d99e9.png)

I tried to make some changes on the ol-ext.js to reach the result mentioned above, but I didn't achieve anything of relevance. 
Could you please suggest me something? Do you have any ideas? 

Thank you so much!

**Comment by Viglino** [comment]
Hello,
Use the `drawlist` event to add a class to the list and use the CSS to style the sublist:
```javascript
layerSwitcher.on('drawlist', function(e) {
  if (e.layer instanceof ol.layer.Group) {
    e.li.className = e.layer.get('visible') ? 'visible': 'hidden';
  }
})
```
See example: https://codepen.io/viglino/pen/MWYMqoj

**Comment by Teorizzi0** [comment]
That's exactly what I needed! Thank you so much ;)
