### ISSUE TITLE
MapZone Control over Sidebar Menu

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#413]
Hi!

I troubled by a few days because of the following issue with MapZone and Sidebar. Firstly, let's say that when the MapZone Control is placed outside the sidebar, all works fine. Otherwise, when it is inside, this happens: when the page is loaded (pic 1), the three map zones are not visible. Then, after whatever resizing of the browser window (decreasing or increasing), the zones appear (pic2). 

- pic 1: 
![Screenshot (293)](https://user-images.githubusercontent.com/44029782/73934152-2b066380-48de-11ea-947b-e9d62239a7e7.png)

- pic 2: 
![Screenshot (295)](https://user-images.githubusercontent.com/44029782/73934161-32c60800-48de-11ea-8f7f-91581cf29eb7.png)

I tried to set the "display" of the div #zone to "block", and it worked (they were visible from the beginning) but the problem was they were blocked (and visible) in their position also in the other sidebar tabs. 

I hope the chrome dev tool screenshots I attached can help you to help me in solving this problem. Thank you so much!

**Comment by Viglino** [comment]
The images in the zones are maps and they are not rendered when the container is hidden...
When the window is resized a render event is fired to the map and the maps are drawn.
You have to tell the maps to render when the SideBar is open.
There is no function to force the maps to draw in the MapZone. I'll try to add one asap.
Yet, you can fire a resize event when the panel open.

**Comment by Viglino** [comment]
I've added a map update when control is set visible.
You can use `mapZonControl.setVisible(true)` to render the maps.
