### ISSUE TITLE
Import filters to an angular project

### ISSUE THREAD

**Issue by thiagocavaloti** [Viglino/ol-ext#414]
Hi @Viglino exists a way to dynamic import filters classes on an existing angular8 project ?

**Comment by Viglino** [comment]
Import should do it 
```javascript
import ol_filter_Colorize from 'ol-ext/filter/Colorize'
```

**Comment by thiagocavaloti** [comment]
@Viglino i got a new error when try to instantiate Colorize: 
`` ERROR TypeError: Class constructor BaseObject cannot be invoked without 'new'
    at ol_filter_Colorize.ol_filter_Base [as constructor] (Base.js:30)
    at new ol_filter_Colorize (Colorize.js:27)``

**Comment by Viglino** [comment]
I've no issue creating a filter using ES6 modules:
```javascript
import ol_filter_Colorize from 'ol-ext/filter/Colorize'
const filter = new ol_filter_Colorize();
console.log('FILTER', filter)
```

**Comment by thiagocavaloti** [comment]
Unfortunatly i call the new constructor on my angular 8 component class and the error is the same :

``ERROR Error: Uncaught (in promise): TypeError: Class constructor BaseObject cannot be invoked without 'new'
TypeError: Class constructor BaseObject cannot be invoked without 'new'
    at ol_filter_Colorize.ol_filter_Base [as constructor] (Base.js:30)
    at new ol_filter_Colorize (Colorize.js:27)``

**Comment by Viglino** [comment]
Can I have an example of your code ?

**Comment by thiagocavaloti** [comment]
```javascript
import { Component, OnInit } from '@angular/core';
import ol_filter_Colorize from 'ol-ext/filter/Colorize';
@Component({
  selector: 'app-colorize',
  templateUrl: './colorize.component.html',
  styleUrls: ['./colorize.component.scss']
})
export class ColorizeComponent implements OnInit {

  filter = new ol_filter_Colorize();
  enhance = new ol_filter_Colorize({ operation: 'enhance'});
  ngOnInit() {
      console.log(this.filter);
  }
}
```
`ERROR Error: Uncaught (in promise): TypeError: Class constructor BaseObject cannot be invoked without 'new'
TypeError: Class constructor BaseObject cannot be invoked without 'new'
    at ol_filter_Colorize.ol_filter_Base [as constructor] (Base.js:30)
    at new ol_filter_Colorize (Colorize.js:27)
    at new ColorizeComponent (colorize.component.ts:10)
    at NodeInjectorFactory.ColorizeComponent_Factory [as factory] (colorize.component.ts:8)`

**Comment by Viglino** [comment]
Seems to work for me on https://codesandbox.io/s/test-ol-ext-filter-angular-37gfw
```javascript
export class AppComponent implements OnInit {
  title = "ol-ext";

  ngOnInit() {
    const layerOSM = new TileLayer({
      source: new OSM()
    });

    const map = new Map({
      target: "map",
      controls: [],
      layers: [layerOSM],
      view: new View({
        center: [247044, 6549736],
        zoom: 8
      })
    });

    const filter = new Colorize({
      operation: "grayscale"
    });
    layerOSM.addFilter(filter);
    console.log("ok", filter, map);
  }
}
```

**Comment by thiagocavaloti** [comment]
@Viglino although it works on sandbox still not working on my project.
On sandbox that you posted above has a warning on line 6:

`Cannot find module 'ol-ext/filter/Colorize'`
 
I am using `angular 8.2.14 ` with ivy compiler activated.

**Comment by Viglino** [comment]
I think the warning is because there is no .d.ts file on ol-ext.

**Comment by Viglino** [comment]
Are you sure you install ol on your project?

**Comment by thiagocavaloti** [comment]
yes, the version is  `"ol": "^6.2.0"`
