### ISSUE TITLE
Can't display fontawesome icons using ol-ext FontSymbols

### ISSUE THREAD

**Issue by viviendehorta** [Viglino/ol-ext#415]
I'm trying to display markers with Fontawesome icon on an openlayer map in a react application but cannot succeed. I'm seeing rectangle instead of the icon.

My code :

```
import {Fill, Stroke, Style, Text} from 'ol/style';
import Feature from 'ol/Feature';
import FontSymbol from 'ol-ext/style/FontSymbol';
import Point from 'ol/geom/Point';

const style = new Style({
        image: new FontSymbol({
            glyph: 'fa-map',
            radius: 20,
            fill: new Fill({
                color: 'blue'
            }),
            stroke: new Stroke({
                color: 'red',
                width: 1
            })
        })
    });

    const feature = new Feature({
        geometry: new Point([4500000, 4500000])
    });
    feature.setStyle(style);

```

Lib versions :
react-fontawesome : 5.2.0
ol-ext : 3.1.9

I saw some examples on this github issue board but all also display rectangles.

Has someone any idea about what I am doing wrong ?

**Comment by Viglino** [comment]
ol-ext use FontAwesome 4.7. 
If you want to use a different one you have to create your own font definition file (as https://github.com/Viglino/ol-ext/blob/master/src/style/FontAwesomeDef.js) 
See https://github.com/Viglino/ol-ext/issues/153
