### ISSUE TITLE
Broken links on http://viglino.github.io/ol-ext/

### ISSUE THREAD

**Issue by ThomasG77** [Viglino/ol-ext#416]
While browsing some samples, I've seen broken links. Using online tools, I've made a list of broken links below.

| Result                  | URL                                                                                 | 
|-------------------------|-------------------------------------------------------------------------------------| 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/style/map.geom.cspline.html~~            | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/misc/csv2GeoJSON.html~~                  | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/control/map.preview.html~~               | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/control/map.control.toggle.html~~        | 
| Timeout                 | http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txtOutbound                  | 
| Timeout                 | http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.txtOutbound                  | 
| 404 Not found           | http://viglino.github.io/ol-ext/doc/doc-pages/namespaces.html                       | 
| 404 Not found           | https://openlayers.org/en/master/apidoc/module-ol_source.htmlOutbound               | 
| 404 Not found           | https://openlayers.org/en/master/apidoc/module-ol_style.htmlOutbound                | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/search/map.dbpedia.html~~                | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/search/map.wikicommons.html~~            | 
| ~~404 Not found~~       | ~~https://adresse.data.gouv.fr/static/images/logos/OSM.png~~                        | 
| 404 Not found           | http://viglino.github.io/ol-ext/doc/doc-pages/ol.source.Vector.html                 | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map.control.geobookmark.html~~           | 
| 404 Not found           | http://viglino.github.io/ol-ext/doc/doc-pages/ol.layer.html                         | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/routing/map.control.search.html~~        | 
| ~~404 Not found~~       | ~~https://viglino.github.io/ol3-games/examples/map.hexmap.html~~                    | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/layer/map.switcher.image.html~~          | 
| 404 Not found           | http://viglino.github.io/ol-ext/doc/doc-pages/ol.geom.html                          | 
| 503 Service unavailable | https://emergency.copernicus.eu/mapping/georss-feeds-aggregatedOutbound             | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/layer/map.style.font.html~~              | 
| 404 Not found           | http://viglino.github.io/                                                           | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/mobile/map.control.bar.html~~            | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/mobile/map.control.toggle.html~~         | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.filter.colorize.html~~           | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.filter.texture.html~~            | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.control.compass.html~~           | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.control.graticule.html~~         | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.dbpedia.html~~                   | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/map.style.photo.html~~               | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map/animation/map.animatedcluster.html~~ | 
| 400 Bad request         | https://en.wikipedia.org/wiki/Dijkstra%27s_algorithmOutbound                        | 
| ~~404 Not found~~       | ~~http://viglino.github.io/ol-ext/examples/map.style.chart.html~~                   | 
| 404 Not found           | http://viglino.github.io/ol-ext/doc/doc-pages/ol.style.Image.html                   | 
| 404 Not found           | https://viglino.github.io/                                                          | 

PS: I've updated the list due to PR #417 (waiting for review)

**Comment by Viglino** [comment]
I'll try to fix it asap.

**Comment by Viglino** [comment]
I've updated and rebuild the doc.
Wait for cache refresh to see remaining broken links.

**Comment by Viglino** [comment]
Seems to work now. ⭐️ 
Only one link is missing (generated by the doc) but doesn't seems to be clicked ?
