### ISSUE TITLE
Render3D

### ISSUE THREAD

**Issue by DeManHemZelfe** [Viglino/ol-ext#418]
Hello,

I use the render3D function :

`
  r3D = new render3D({
    source: this.pandSource,
    maxZoom: 15,
    height: 0,
    zIndex: 2,
    maxResolution: 0.5,
    defaultHeight: 0,
    style: this.drawFunction()
  });`
everithing works fine and i can load all the buildings. But i want to make walls because now you can see in the buildings. Does anyone know how i can make walls?

![2020-02-27](https://user-images.githubusercontent.com/42802392/75565035-89da7b00-5a4d-11ea-8703-c246ea68494b.png)

Regards, 
Niels Martens

**Comment by Viglino** [comment]
Render3d has no such functionality. 
To do this you have to use a real 3d lib such as Cesium https://openlayers.org/ol-cesium/
