### ISSUE TITLE
Make a layer unselectable

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#419]
Hi! 
I have control-select functionality active on the map and it works fine. Together with this, there is also a Popup system (through the popup.show method). 

The problem is that in this way every layer is selectable and clickable, even if I would like to have the popup just for some specific layers on the map. Is it possible to do it?

In the following lines you can find the code I'm using for the select and popup functions:
```
var select = new ol.interaction.Select({
  style: new ol.style.Style({
    image: new ol.style.RegularShape({
            fill:  new ol.style.Fill({color: 'red'}),
            stroke: new ol.style.Stroke({color: 'white', width: 2}),
            points: 4,
            radius: 6,
            angle: Math.PI / 4
          })
    })
});
map.addInteraction(select);

select.getFeatures().on(['add'], function(e)
{	var feature = e.element;
  var content = "";
  content += "Name:" + feature.get("name");
  popup.show(feature.getGeometry().getCoordinates(), content); 
  }
})

select.getFeatures().on(['remove'], function()
{	popup.hide(); 
})
```

**Comment by Viglino** [comment]
You have to tell the Select interaction which layers are concerned by setting the `layers` options on creation.
```javascript
var select = new ol.interaction.Select({
  layers: [ layer1, layer2 ],
  style: ...
});
map.addInteraction(select);
```
You can also use a function instead an array of layers or use the `filter` option if you want more functionalities.
See https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html

**Comment by Teorizzi0** [comment]
Thank you!
