### ISSUE TITLE
Is there a way to maintain the aspect ratio of a drawn box or square when stretching with the transform interaction?

### ISSUE THREAD

**Issue by mtburkett** [Viglino/ol-ext#422]
Hi
Thanks again for this great addition to OpenLayers. I am trying to find a way to stretch drawn boxes without distorting the shape into a parallelogram. Is this possible and I have just missed something, or is this a feature that could be added?

Before:
![image](https://user-images.githubusercontent.com/25694364/76432927-00e70c00-638a-11ea-8f2c-c090959a6b29.png)

After:
![image](https://user-images.githubusercontent.com/25694364/76432965-0b090a80-638a-11ea-9b39-b7643687c732.png)

I am currently using this code:
`self.transformInteraction = new self.ol.interaction.Transform ({
        enableRotatedTransform: true,
        // addCondition: self.ol.events.condition.shiftKeyOnly,
        filter: function(f,l) { return f.getGeometry().getType()==='Polygon'; },
        layers: [self.drawLayer],
        hitTolerance: self.hitTolerance,
        keepAspectRatio: self.ol.events.condition.always,
        noFlip: true,
        rotate: true,
        scale: true,
        stretch: true,
        translateFeature: true, 
        translate: true,
      });
      self.olMap.addInteraction(self.transformInteraction);`

**Comment by Viglino** [comment]
The stretch depends on the XY axis...
It can handle the map rotation but nothing else.
To handle your case the former angle of the shape should be know first...

**Comment by mtburkett** [comment]
I will check into that. Thank you.

**Comment by mtburkett** [comment]
Do you have any suggestions how I might accomplish this? I am getting the angle of the shape on transformation select, but I don't really know what to do with it after I have it. Do I apply it to the styling handles? The vector layer? The I am getting the angle like: 

`startAngle = Math.atan2(coords[1][1] - coords[0][1], coords[1][0] - coords[0][0]) * 180 / Math.PI;`

I appreciate any point in the right direction.

Thanks

**Comment by Viglino** [comment]
You can set this angle to the map view to have the handles parallel to border of the map.
```javascript
map.getView().setRotation(angle);
```
Use the `enableRotatedTransform` to force the transform to be parallel to the border of the map.

See example: https://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html
1. rotate the map
2. select an object
3. check/uncheck 'force matching the map rotation'

**Comment by mtburkett** [comment]
Thank you for the suggestion. This does work - it's a bit ugly, but it does work.
