### ISSUE TITLE
ol/interaction/UndoRedo marked as experimental

### ISSUE THREAD

**Issue by martinmcneela** [Viglino/ol-ext#423]
ol/interaction/UndoRedo is marked as experimental, is this far from being stable?

**Comment by Viglino** [comment]
I didn't test it on all the cases...
There is no limits on undo and it can increase memory if you don't clear the interaction...
For me it does the job on features I've tested... but I didn't test it on large datasets.
Test it and tell me what's missing to make it more reliable.
