### ISSUE TITLE
DrawHole support for circles?

### ISSUE THREAD

**Issue by sdfricke** [Viglino/ol-ext#430]
Hello, I would like to be able to cut a circle out of a feature.  When trying to use the DrawHole interaction, I pass type: 'Circle' as one of the options, as you would in the ol Draw interaction, but it still seems to draw a polygon so that doesn't seem to be supported.  Is there any way to get it to work to draw a circle?

**Comment by Viglino** [comment]
Hello,
DrawHole only applies on Polygons.
Using ol, Circle has no hole, it's just a center and a radius. You have to transform Circle to Polygon.
Use [ol/geom/Polygon.fromCircle](https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html#.fromCircle)
@+

**Comment by sdfricke** [comment]
Hey thanks for getting back! I’m not sure how your solution would be applied. I have a polygon and I want to draw a hole in it. I want the hole to be circle shaped. When using the DrawHole interaction I see that the type is hardcoded as Polygon. Wondering if this could be made dynamic so that a circle could be drawn?
