### ISSUE TITLE
ol_featureAnimation_Bounce problem

### ISSUE THREAD

**Issue by linrong** [Viglino/ol-ext#432]
```bash            
           // animation
            // eslint-disable-next-line new-cap
            let animStatus = true
            const anim = new ol_featureAnimation_Bounce({
                duration: 800
            })
            vectorLayer.animateFeature(endMarker, anim)
            anim.on('animationend', function(e) {
                if (animStatus) vectorLayer.animateFeature(e.feature, anim)
            })
            setTimeout(function() {
                animStatus = false
                const endMarker1 = vectorSource.getFeatureById('endMarker')
                endMarker1.getGeometry().setCoordinates(fromLonLat(lonlat[1][0]))
                animStatus = true
                vectorLayer.animateFeature(endMarker1, anim)
            }, 3000)
```

I created a Feature ‘endMarker’ and added it to the vectorSource and then to the vectorLayer. This worked successfully  and execute the animation successfully, but after I stopped the animation and updated the coordinates of the endMarker, the endMarker was no longer displayed and the animation was not displayed
I use ol5.3.3
what should I do？ 
thx

**Comment by Viglino** [comment]
You have to stop animation before starting a new one or it will interfere:
```javascriot
  var animation = vectorLayer.animateFeature(endMarker, anim)
  anim.on('animationend', function(e) {
    animation = vectorLayer.animateFeature(e.feature, anim)
  })
  setTimeout(function() {
    // Stop animation
    animation.stop();
    const endMarker1 = vectorSource.getFeatureById('endMarker')
    endMarker1.getGeometry().setCoordinates(fromLonLat(lonlat[1][0]))
    // Start new one
    animation = vectorLayer.animateFeature(endMarker1, anim)
  }, 3000)
```

**Comment by linrong** [comment]
Thank you, I can run on the demo according to your method, but it still doesn't work in my project, I need to keep looking

**Comment by linrong** [comment]
I found that the stop() function did not work on the demo, and it can run normally without stop(), but in my project, the feature is not displayed with and without stop (). I compared the code. But didn't find the problem, don't know if you have other suggestions

**Comment by linrong** [comment]
If I don't update the Coordinates of the feature, the animation can be displayed normally, but after I update it, it can't.
i use ol-ext：
```bash
import ol_featureAnimation_Bounce from 'ol-ext/featureanimation/Bounce'
```

**Comment by linrong** [comment]
I found that when I zoomed out the map, the moving points appear to be animated in the world next door, but when I move past, I find that they disappear again and continue to appear in the world next door. What is the problem?

**Comment by Viglino** [comment]
What do you mean the world next door?

**Comment by Viglino** [comment]
Try to create a new point when animating:
```javasript
  animation = vectorLayer.animateFeature(feature.clone(), anim)
```

**Comment by linrong** [comment]
Sorry, my English is not very good,I don't know how to describe it, like below
![Gny0SK.png](https://s1.ax1x.com/2020/03/30/Gny0SK.png)

**Comment by Viglino** [comment]
The animation displays only once on the main map (-180°,180°] and doesn't wrap the dateline...
Actually, I think it uses the coordinates passed to the animated feature.

**Comment by linrong** [comment]
I need to show in multiple worlds, do you have any good suggestions?

**Comment by Viglino** [comment]
You can test to add an animation per world...
