### ISSUE TITLE
Move print functionalities to a button

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#433]
Hi! Each functionality of the print button works great. I have just a question: can I "replicate" what happens by clicking on the print ol-button to a simple HTML button on the website? 

In a few word I would like that this:
```
var printControl = new ol.control.Print();
map.addControl(printControl)

printControl.on('print', function(e) {
|
|
|
}
```

is triggered by clicking on this:
`<button class="button" id="printbutton" >Print</button>`

I hope I was clear.

Thank you in advance

**Comment by Viglino** [comment]
The `print()` method can be used to get an image programmatically.
```javascript
var printControl = new ol.control.Print();
map.addControl(printControl)
printControl.on('print', function(e) {
...
}
// Print the map
printControl.print({ imageType: 'image/jpeg'})
```
or in your html
```html
<button class="button" id="printbutton" onclick="printControl.print({ imageType: 'image/jpeg'})">
  Print
</button>
```
See example https://viglino.github.io/ol-ext/examples/canvas/map.control.print.html
