### ISSUE TITLE
Layer Switcher parent/child relationship

### ISSUE THREAD

**Issue by johnlus87** [Viglino/ol-ext#434]
I am woking on a WebGIS and your library is very useful! Thanks for that. 

Actually, I have an issue about the Layer Switcher. I don't know how (and even if) it is possible to improve the relationship between parent layer and children. In fact, I would like to prevent situation like this:
![Screenshot (319)](https://user-images.githubusercontent.com/62894111/77927159-4884f780-72a7-11ea-8861-d13cd6271e23.png)
in which a parent layer is disabled but the children are still selected. 

Is there a way to uncheck all the children if the parent is unchecked and viceversa (check all the children if the parent is checked) like in the following pic:
![Screenshot (320)](https://user-images.githubusercontent.com/62894111/77927473-8d109300-72a7-11ea-8a2d-463b84e7cb9e.png)

I didn't poste code because it is the more or less equal to the ol-ext.js.

Thank you

**Comment by Viglino** [comment]
Hello 
It's not a LayerSwitcher issue. The LayerSwitcher only reflects the layers status.
You have to check changes on the layers to know when to show/hide them.
There is a `change:visible` event to listen to handle your layers.
```javascript
function listenVisible(layer, group) {
  layer.on('change:visible', function(e) {
    // LayerGroup
    if (layer.getLayers) {
      layer.getLayers().forEach( function(l) { 
        l.setVisible(layer.getVisible());
      });
    }
    // if inside a group, check visibility of layers in it
    if (group) {
      var vis = false;
      group.getLayers().forEach( function(l) { 
        if (l.getVisible()) vis = true;
      });
      if (group.getVisible() !== vis) group.setVisible(vis);
    }
  });
  // Listen to layers in it
  if (layer.getLayers) {
    layer.getLayers().forEach( function(l) { 
       listenVisible(l, layer);
    });
  }
}
listenVisible(map.getLayers().getArray());
```

**Comment by johnlus87** [comment]
So basically the listenVisible function should take in input each group I have on the map? Because actually I used the function you wrote here but it doesn't work, I mean: nothing it was change

**Comment by Viglino** [comment]
There was a bug with an infinite loop in the code.
Use `set('visible', vis, true)` to prevent event propagation
This should run:
```javascript
  layer.on('change:visible', function(e) {
    // LayerGroup
    if (layer.getLayers) {
      var vis = layer.getVisible();
      layer.getLayers().forEach( function(l) { 
        if (l.getVisible() !== vis) {
          // Prevent infinite loop
          l.set('visible', vis, true);
        }
      });
    }
    // if inside a group, check visibility of layers in it
    if (group) {
      var vis = false;
      group.getLayers().forEach( function(l) { 
        if (l.getVisible()) vis = true;
      });
      if (group.getVisible() !== vis) group.setVisible(vis);
    }
  });
  // Listen to layers in it
  if (layer.getLayers) {
    layer.getLayers().forEach( function(l) { 
       listenVisible(l, layer);
    });
  }
}
map.getLayers().getArray().forEach(function(l) {
  listenVisible(l);
});
```
See example: https://codepen.io/viglino/pen/MWYMqoj

**Comment by johnlus87** [comment]
Thank you very much! Now it works perfectly ;)
