### ISSUE TITLE
Feature Request : animated fonts

### ISSUE THREAD

**Issue by levinzz** [Viglino/ol-ext#437]
On my project I often use [fontawesome spinners](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) as loading icons.

Since you have a way to style fontawesome icons on a map, do you think it would be possible to animate them as well ?

Thanks.

**Comment by Viglino** [comment]
Look at this repo: https://viglino.github.io/ol-games/examples/map.sprite.html

**Comment by levinzz** [comment]
This looks a bit overkill, just for a spinner. To use your solution I would need to get a spinner sprite sheet, right ? Besides, my spinner is overlayed on my icon and when the spinner is not active, I need to display text instead.

Just FYI, my current code : 

```
this.iconStyle = new Style({
	image: new Icon( /** @type {olx.style.IconOptions} */({
		anchor: [0.5, 46],
		anchorXUnits: IconAnchorUnits.FRACTION,
		anchorYUnits: IconAnchorUnits.PIXELS,
		opacity: 0.95,
		src: 'assets/images/cursor/my-icon.png'
	}))

});

//Only this would need to spin
this.loadingStyle = new Style({
	text: new Text({
		text: '\uf251', //Hourglass icon
		font: '900 18px "Font Awesome 5 Free"',
		offsetY: -28,
		scale: 1,
		fill: new Fill({
			color: '#fff'
		})
	})
});

this.textStyle = new Style({
	text: new Text({
		text: '',
		font: '16px "Poppins"',
		offsetY: -28,
		scale: 1,
		fill: new Fill({
			color: '#fff'
		})
	})
});

//When loading
this.feature.setStyle(
	[this.iconStyle, this.loadingStyle]
);
//When not loading
this.feature.setStyle(
	[this.iconStyle, this.textStyle]
);
```

**Comment by Viglino** [comment]
Il you just want a css spinner, use an [ol/Overlay](https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html) instead. An Overlay is a HTML div on top of the map and you'll get all css animations.
NB: don't use too many Overlays or you'll get performance issues.
