### ISSUE TITLE
Popupfeature strange positioning.

### ISSUE THREAD

**Issue by GrandStick** [Viglino/ol-ext#439]
Hello and thank you for this awesome ol-ext.
Since a few days, the popup.feature has a strange positioning on most browser (edge, Firefox, even Chrome on phone). If I fix the popup it goes outside the view. Is it due to a change in ol or ol-ext version? It was working fine before.

**Comment by Viglino** [comment]
Yes it's due to a change in the last version.
I've made a change that fix it.
@+

**Comment by GrandStick** [comment]
Thank you for the fix :). The positionning is good now.
However there is still a problem with the position when the popup is fixed.

Kind regards,

**Comment by Viglino** [comment]
It should be fixed 😄
