### ISSUE TITLE
Syntax Error (arrow function) in IE 11

### ISSUE THREAD

**Issue by MarkH817** [Viglino/ol-ext#442]
I was doing some testing on IE 11, and had a syntax error when loading the package. I did some digging around to see that it was just because of an arrow function in the build.

https://github.com/Viglino/ol-ext/blob/f3a2fbeab44dce8884598db0cc6ad47d7a654b07/src/interaction/Transform.js#L415-L419

Could this be changed to pass in `this` to the `forEach` method like below to support older browsers?

```javascript
features.forEach(function(feature)  { 
  this.selection_.push(feature); 
}, this);
```

As far as I'm aware, this is the only spot an arrow function is used.
Thank you for your time!

**Comment by Viglino** [comment]
Done in last commit 👍
