### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by strarsis** [Viglino/ol-ext#443]
Up to which (or in what range) of versions is this extension library (`ol-ext`) compatible with OpenLayers? Current OpenLayers version is 6.x, would `ol-ext` be compatible with it?

**Comment by Viglino** [comment]
Yes ol-ext is compatible with the last version.
[Example pages](https://viglino.github.io/ol-ext/index.html) use the latest (or master) version of ol.
I try to keep compatibility with olv4.6 but mainly with olv5 and up.

**Comment by strarsis** [comment]
@Viglino: That's great! I want to sync multiple views for a single map (but with center offsets). Currently I use some own custom code. Using a library instead would be much better and simpler.
