### ISSUE TITLE
[Question] Synchronize multiple views (offset)

### ISSUE THREAD

**Issue by strarsis** [Viglino/ol-ext#444]
Four views should show the same map, synchronized, but with specific center offsets.
E.g. first view should have 0 center offset, 2nd view should have 20px offset, 3rd view 40px and so on.
The synchronize class seems to synchronize not the views but whole maps, wouldn't it be better for performance to synchronize only the views and reuse the same map?

**Comment by Viglino** [comment]
You can't reuse the map. A Map is linked with a View.
The [Synchronize interaction](https://viglino.github.io/ol-ext/examples/misc/map.interaction.synchronize.html) is an interaction and it is set to a Map. You can't set an interaction to a View. 
Actually the interaction listen the events on the map view:
```javascript
this.getMap().getView().on('change:center', this.syncMaps.bind(this));
```
You can override the syncMap function to handle different maps with special behavior...

**Comment by strarsis** [comment]
@Viglino: Right, now I reuse the layer source among maps, it seems to work, but there is no explicit statement in the documentation that this indeed the same source can be reused without issues.

**Comment by Viglino** [comment]
It is an Openlayers feature.
Layers can share the same source...

**Comment by strarsis** [comment]
@Viglino: Alright, so reusing the same source among maps (and its layers) will save network bandwidth because downloaded tiles can be reused.
