### ISSUE TITLE
ol.Overlay.Placemark error position in Perspective Map

### ISSUE THREAD

**Issue by duongnv1989** [Viglino/ol-ext#445]
Hello and thank you for this awesome ol-ext.
Since a few days, position error displaying ol.OverLay.Place in Perspective Map. 
Example https://viglino.github.io/ol-ext/examples/map/map.perspective.html
It was working fine before.
Thanks.
![error](https://user-images.githubusercontent.com/15391082/79033306-64f22f80-7bd7-11ea-9b9a-345899d5aa40.png)

**Comment by Viglino** [comment]
Overlay positioning have changed in the last version... and perspective transform is not applied on the Placemark.

**Comment by duongnv1989** [comment]
I'm using the version 3.1.10 but still the error. Overlay positioning have changed in Perspective Map:
`
/* Overwrited Overlay function to handle overlay positing in a perspective map */
(function() {
    var _updatePixelPosition = ol_Overlay.prototype.updatePixelPosition;

    /** Update pixel projection in a perspective map (apply projection to the position)
     * @private
     */
    ol_Overlay.prototype.updatePixelPosition = function () {
      var map = this.getMap();
      if (map && map instanceof gclient_Map && map.perspective == true) {
        var position = this.getPosition();
        if (!map || !map.isRendered() || !position) {
          this.setVisible(false);
          return;
        }
        // Get pixel at screen
        var pixel = map.getPixelScreenFromCoordinate(position);
        var mapSize = map.getSize();
        // Offset according poqsitioning
        var pos = this.getPositioning();
         if (/bottom/.test(pos)) {
           pixel[1] += mapSize[1]/4
         } else {
          pixel[1] -= mapSize[1]/4
         }
         if (/right/.test(pos)) {
           pixel[0] += mapSize[0]/4
         } else {
          pixel[0] -= mapSize[0]/4
         }
        // Update
        this.updateRenderedPosition(pixel , mapSize);
      } else {
        _updatePixelPosition.call(this);
      }
    };
})();`

I try to comment your code to run ok:
`// if (/bottom/.test(pos)) {
        //   pixel[1] += mapSize[1]/4
        // } else {
          pixel[1] -= mapSize[1]/4
        // }
        // if (/right/.test(pos)) {
        //   pixel[0] += mapSize[0]/4
        // } else {
          pixel[0] -= mapSize[0]/4
        // }`
:) :)

**Comment by BrianAguilar** [comment]
when create a Perspective map and magnify it(enlarge the zoom), its position has changed. Why? How to correct it? Thanks

**Comment by Viglino** [comment]
Perspective distorts the projection to fit the map area: the foreground is larger than the background and the focus point (center of the map) is shifted upwards.
The shift depends on the tilt angle (17% at 30 deg).

**Comment by Viglino** [comment]
NB this feature is experimental. Not sure it's the best way to achieve it.

**Comment by BrianAguilar** [comment]
> Perspective distorts the projection to fit the map area: the foreground is larger than the background and the focus point (center of the map) is shifted upwards.
> The shift depends on the tilt angle (17% at 30 deg).

in your this example, when magnify the map, the focus point doesn't shift. I create a new map of Perspective, even though not shift the tilt angle(keep it always shift 0 degree), then magnify it, the focus point(center) will moves toward left-up direction. Could you help explain it? Thanks

**Comment by Viglino** [comment]
Do you have an only example?
