### ISSUE TITLE
ol.control.Profil for speed

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#448]
Hi, is possible to build Profil for speed of activity tracked in gpx?

**Comment by Viglino** [comment]
It could be but not really relevant.

**Comment by vsevjednom-cz** [comment]
I'm sad :(. I'm doing my own tracked GPS app in my free time. Like Strava or Sports Tracker. And Sports Tracker has speed profil on their web. But I can only calculate and show actual speed when mouse over.

**Comment by vsevjednom-cz** [comment]
I'm sad :(. I'm doing my own GPS tracking app in my free time. Like Strava or Sports Tracker. And Sports Tracker has speed profil on their web. But I can only calculate and show actual speed when mouse over.

**Comment by vsevjednom-cz** [comment]
So... I'm generating "speed profil" in PHP and set this: `this.bar_.style.height = (this.canvas_.height-this.margin_.top-this.margin_.bottom+500)/ratio+"px";`

This works as I want. Screenshot: https://images.megaupload.cz/Screenshot_20200424_123218.png

**Comment by vsevjednom-cz** [comment]
So... I'm generating "speed profil" in PHP and set this: this.bar_.style.height = (this.canvas_.height-this.margin_.top-this.margin_.bottom+500)/ratio+"px";

This works as I want. Screenshot: https://images.megaupload.cz/Screenshot_20200424_123218.png

**Comment by vsevjednom-cz** [comment]
... and can I do it somehow? I can do it for you too - as contributor 🍕. If yes please write me which code I must edit for "speed profil".

**Comment by vsevjednom-cz** [comment]
... and can I do it somehow? I can do it for you too - as contributor pizza. If yes please write me what part of code I must edit for "speed profil".

**Comment by vsevjednom-cz** [comment]
... and can I do it somehow? I can do it for you too - as contributor 🍕. If yes please write me which code I must edit for "speed profil".

**Comment by vsevjednom-cz** [comment]
... and can I do it somehow? I can do it for you too - as contributor 🍕. If yes please write me what part of code I must edit for "speed profil".

**Comment by Viglino** [comment]
Hello,
The problem is the control doesn't use a GPX file but an `ol/Feature` to draw the profil and the speed is not recorded on the points: only x,y,z,t are set according to the [ol/geom/GeometryLayout](https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryLayout.html) and the speed is lost...
One way could be to recalculate the speed according distance / time but not sure it will be accurate.

**Comment by Viglino** [comment]
An other way would be to overwrite the `ol/format/GPX` to read and store speed instead of Z...

**Comment by vsevjednom-cz** [comment]
Yep, GPX doesn't contain speed. I count speed for mouseover. And I want to do new profil from this count.
```
	var div_speed = document.createElement("td");
	div_speed.innerHTML = (this.info.speed||"Rychlost")+': <span class="speed">';
	secondTr.appendChild(div_speed);
```

```
speed = ((((p[0]-last_p[0])/1000) / (p2-last_p2) )*3600 ).toFixed(1);

if(speed == Infinity) { var speed = '???'; }

this.element.querySelector(".point-info .speed").textContent = (Math.floor(last_p[1]) == Math.floor(p[1]) ? 'rovina ⭢' : (last_p[1] < p[1] ? 'do kopce ⭜' : 'z kopce ⭝')) + ' ' + speed + ' ' + this.info.speedUnit;
```
Is possible to create profil from this count? If yes how? :)

**Comment by vsevjednom-cz** [comment]
Yep, GPX doesn't contain speed. I count speed for mouseover. And I want to do new profil from this count.
```
	var div_speed = document.createElement("td");
	div_speed.innerHTML = (this.info.speed||"Speed")+': <span class="speed">';
	secondTr.appendChild(div_speed);
```
```
		for (var i=1, p; p=this.tab_[i]; i++)
		{	if (p[0]>=d)
			{	var last_p = this.tab_[i-2];
				if (d < (p[0]+p0[0])/2) p = p0;
				break;
			}
		}
```
```
if (typeof last_p !== 'undefined') {

var InputString = JSON.stringify(p[3]);
var Array = InputString.split(",");
var p2 = Array[3].replace(/^\]+|\]+$/g, '');

var lastInputString = JSON.stringify(last_p[3]);
var lastArray = lastInputString.split(",");
var last_p2 = lastArray[3].replace(/^\]+|\]+$/g, '');

speed = ((((p[0]-last_p[0])/1000) / (p2-last_p2) )*3600 ).toFixed(1);

if(speed == Infinity) { var speed = '???'; }

this.element.querySelector(".point-info .speed").textContent = (Math.floor(last_p[1]) == Math.floor(p[1]) ? 'rovina ⭢' : (last_p[1] < p[1] ? 'do kopce ⭜' : 'z kopce ⭝')) + ' ' + speed + ' ' + this.info.speedUnit;

}
```
Is possible to create profil from this count? If yes how? :)

**Comment by vsevjednom-cz** [comment]
Yep, GPX doesn't contain speed. I count speed for mouseover. And I want to do new profil from this count.
```
	var div_speed = document.createElement("td");
	div_speed.innerHTML = (this.info.speed||"Speed")+': <span class="speed">';
	secondTr.appendChild(div_speed);
```
```
		for (var i=1, p; p=this.tab_[i]; i++)
		{	if (p[0]>=d)
			{	var last_p = this.tab_[i-2];
				if (d < (p[0]+p0[0])/2) p = p0;
				break;
			}
		}
```
```
if (typeof last_p !== 'undefined') {

var InputString = JSON.stringify(p[3]);
var Array = InputString.split(",");
var p2 = Array[3].replace(/^\]+|\]+$/g, '');

var lastInputString = JSON.stringify(last_p[3]);
var lastArray = lastInputString.split(",");
var last_p2 = lastArray[3].replace(/^\]+|\]+$/g, '');

speed = ((((p[0]-last_p[0])/1000) / (p2-last_p2) )*3600 ).toFixed(1);

if(speed == Infinity) { var speed = '???'; }

this.element.querySelector(".point-info .speed").textContent = (Math.floor(last_p[1]) == Math.floor(p[1]) ? '⭢' : (last_p[1] < p[1] ? 'up ⭜' : 'down ⭝')) + ' ' + speed + ' ' + this.info.speedUnit;

}
```
Is possible to create profil from this count? If yes how? :)

**Comment by vsevjednom-cz** [comment]
I can do it 🙃. Please write me which part of code does profil. Where is the source of height (altitude) of profil? I can't find it in code. I want to replace this source by calculation of speed. (I'll do second profil for speed next to altitude profil, of course.)

**Comment by vsevjednom-cz** [comment]
I can do it 🙃 Please write me which part of code does the profil. Where is the source of height (altitude) of profil? I can't find it in code. I want to replace this source by calculation of speed. (I'll do second profil for speed next to altitude profil, of course.)

**Comment by vsevjednom-cz** [comment]
I can do it 🙃. Please write me which part of code does the profil. Where is the source of height (altitude) of profil? I can't find it in code. I want to replace this source by calculation of speed. (I'll do second profil for speed next to altitude profil, of course.)

**Comment by Viglino** [comment]
The control use the Z in the geometry: each points are in [[XYZM layout](https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryLayout.html).
You just have to set the speed instead of the Z in your geometry (as 3rd coordinate).
The Z is the 3rd measure in the points [X, Y, Z, t] you have to create the geometry using points with a speed [X, Y, Speed, t] instead.
```javascript
// Create a geometry
var g = new ol.geom.Polyline([[x0,y0,speed0], [x1,y1,speed1], /*etc.*/]);
profil.setGeometry(g)
```

Here is an example that transform a GPX to set the speed as 3rd parameters in points (calculating speed using distance and dt between points).
https://codepen.io/viglino/pen/ExVGprQ

@+

**Comment by vsevjednom-cz** [comment]
Thaaanks! Amazing! Nice! But it doesn't work together with default profil :(. I want to show both - altitude profil and speed profil (using "target"). I tried many and many ways but still not works both together.

And drawPoint not works when mouse fly over profile.
Trying this:
`	speedprofil.on(["over","out"], function(e)
		{	if (e.type=="over") speedprofil.popup(e.coord[2]+" km/h");
			drawPoint(e);
		});`

Can you write me what I must do?

**Comment by vsevjednom-cz** [comment]
Thaaanks! Amazing! Nice! But it doesn't work together with default profil :(. I want to show both - altitude profil and speed profil (using "target"). I tried many and many ways but still not works both together.

And drawPoint not works when mouse fly over profil.
Trying this:
`	speedprofil.on(["over","out"], function(e)
		{	if (e.type=="over") speedprofil.popup(e.coord[2]+" km/h");
			drawPoint(e);
		});`

Can you write me what I must do?

**Comment by vsevjednom-cz** [comment]
I got it! Solution both things: first in code must be speed profil.

`map.addControl(speedprofil);`

**Comment by vsevjednom-cz** [comment]
I got it! Solution of both things: speed profil must be in code like first.

`map.addControl(speedprofil);`

**Comment by vsevjednom-cz** [comment]
I must reopen this issue :(.

Profil shows altitude as speed in speedprofil. p[1] is speed, there isn't altiude and I don't know why.

I use something like it:
this.element.querySelector(".point-info .z").textContent = (this.info.speedprofil == 0 ? p[1] : "???") +" "+this.info.altitudeUnits;

**Comment by vsevjednom-cz** [comment]
I must reopen this issue :(.

Profil shows altitude as speed in "speedprofil". `p[1]` is speed, there isn't altitude nowhere. How can I get altitude? 

I use something like this:
`this.element.querySelector(".point-info .z").textContent = (this.info.speedprofil == 0 ? p[1] : "???") +" "+this.info.altitudeUnits;`
