### ISSUE TITLE
Print control never ends

### ISSUE THREAD

**Issue by labronico0586** [Viglino/ol-ext#449]
When there is an animation on map and the animation lasts for a very long period (or never ends) the print control does not work, as it never gets the '_rendercomplete_' event (line 80) from ol map (the render never completes actually).
The control calls the onPrinting callback and wait for the map rendering completion till the animation completes (or forever).
The solution could be to register for '_postrender_' event instead of for '_rendercomplete_'.

**Comment by Viglino** [comment]
You have to stop your animations when printing.
```javascript
printControl.on('printing', () => {
  // Stop all animations
  ...
});
printControl.on('print', () => {
  // Resume all animations
  ...
});
```

**Comment by Viglino** [comment]
Hello,
I've added a new options `immediate` to force print even if the render is not complete.
This should work in your case:
```javascript
const printControl = new ol_control_Print({ immediate: true });
mapp.addControl(printControl);

printControl.on('print', () => {
  console.log('ok');
});
@+
```
