### ISSUE TITLE
Circle in ol.interaction.TouchDraw

### ISSUE THREAD

**Issue by optsano** [Viglino/ol-ext#450]
Hello
I'm not good at English.
I want to draw a circle on the touchpad. Is DrawTouch not supported?
DrawTouch is a great feature!
Is there any way?

**Comment by Viglino** [comment]
I've added the Circle geometry type on DrawTouch.
Now it should work!

**Comment by optsano** [comment]
Great thanks!!
I didn't expect the program to be fixed.
I am grateful.
I'll try!

**Comment by optsano** [comment]
I didn't expect the program to be fixed.
I am grateful.
I'll try!
