### ISSUE TITLE
using ol-ext with openlayers 6

### ISSUE THREAD

**Issue by bnping** [Viglino/ol-ext#451]
I need to use ol-ext with openlayers 6, can we?, if yes do you have any example please ? .

I tried to add geo image inside map openlayers 6 but nothing is showing. My code is like this:
var geoimg = new GeoImage({
    name: "Georef",
    opacity: .7,
    visible: true,
    source: new GeoImageSource({})
  });
  map.addLayer(geoimg)

**Comment by Viglino** [comment]
ol-ext is ol 6 compatible. All examples are using the last version of ol.
in your code, you have to set the image options (url, center, etc.) in the GeoImageSource...

**Comment by bnping** [comment]
Ok, it is working but the GeoImage is missing the imageSize parameter, is their any method to replace imageScale by image size in pixel ?.

**Comment by Viglino** [comment]
Hello,
You can calculate imageScale if you have imageSize (you just need to know the size on the map).
Use the [Map-georeferencer tool](http://viglino.github.io/Map-georeferencer/) to generate the position and get the parameters (using the button φ).
@+

**Comment by userAdi** [comment]
How could I import 'new ol.control.Compass' in ol6 ? I want to include compass in ol6

**Comment by Viglino** [comment]
@userAdi 
```javascript
import Compass from 'ol-ext/control/Compass'

const compas = new Compass(...);
```

**Comment by userAdi** [comment]
> ```js
> import Compass from 'ol-ext/control/Compass'
> ```

thanks it worked. :+1:  My all other controls like layerswitcher,zoombar,overview,etc has gone when I added this compass. Do I need to use all controls from ol-ext ?
