### ISSUE TITLE
Wrong swipe layer displaying on mobile devices

### ISSUE THREAD

**Issue by adamsss92** [Viglino/ol-ext#453]
Hello,

Under the link below you will find a map in which I use swipe. 

[http://mapy.fotoraporty.pl/Lomianki_testy/](url)

The map works correctly on the computer, but on mobile devices the left layer rectangle clip is incorrect. In my opinion, the coordinates of the rectangle are calculated incorrectly? Do you have an idea where the problem may be?

![96878841_583967828888583_4124955757231734784_n](https://user-images.githubusercontent.com/38074065/81924332-42d93c00-95df-11ea-8de9-8be5a216fba3.png)

PS. I test your swipe example on mobile devices and it works fine.

**Comment by Viglino** [comment]
Hello
can you link to the non minify version of the lib (ol-ext.js instead of ol-ext.min.js) to see what went wrong?

**Comment by adamsss92** [comment]
Hi,

I made the changes you requested.

**Comment by Viglino** [comment]
Hello,
There was a bug on retina device (with pixel ratio) corrected in last commit.
@+
