### ISSUE TITLE
ol.control.LayerSwitcher renders unneccesary multiple times

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#454]
You have a "drawPanel Function" on your "ol.control.LayerSwitcher".  This is ok.  The problem is that this code fires on each and every layer change event.  Take for example a simple "ol.interaction.Select" will internally fire a change event on the feature and in turn will fire a change event on the layer and finally this is then getting picked up by your "ol.control.LayerSwitcher" control which then fires the drawPanel function (Not needed here).  Even by doing a simple addInteraction / removeInteraction will do the same.

Note:  I did have a look at ticket https://github.com/Viglino/ol-ext/issues/252, but unfortunately the drawDelay does not fix this problem as the layerSwitcher still gets redrawn everytime.  You should only redraw the layerSwitcher if one of the layers gets a physical change (Opacity, Visibility, Order, etc) and not on each and every change event.

**Comment by Viglino** [comment]
The LayerSwitcher has to listen to changes on the LayerGroup of the map. Unfortunately this includes changes on the layers.
There is no event to listen to change order in the LayerGroup this means all changes will be fired...
I don't know a clever way to do this...

**Comment by 1Map** [comment]
You must listen to changes on the layers / layer groups that will **only** affect your layer control.  Changes like, for example:

- change:opacity
- change:visible
- change:zIndex <-- maybe no need to check on this

And not for "general overall" changes.

I presume you are checking for changes on the map in "**change:layerGroup**"

You can maybe keep your code like it is, but in your **change:layerGroup** you should actually detect if a layer was added and then do the checks (opacity, visibile, zIndex, etc) on the added layer.

There is also no need to redraw the layer control all over from scratch, but only change what is needed on the layer control.  For example, in a layer "change:visible" you would just modify the div/layer that changed in your layer control.  For example, maybe a greyed-out style when invisible, etc. and not re-render the whole control.

**Comment by 1Map** [comment]
You can listen for add and remove on the layers collection.

**Comment by Viglino** [comment]
I'll try to have a look

**Comment by Viglino** [comment]
I finally listen to listen to `change:length` in the layers collection that handle both add and remove.
This should work now.

**Comment by 1Map** [comment]
Thanks, what I noticed now is that the collapse/expand button does not work anymore on the layerswitcher control.

**Comment by Viglino** [comment]
Solve in the last commit
