### ISSUE TITLE
Switcher buttons

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#455]
Hello, 
is it possible to change default trash button position in layerswitcher ? 
Of course I can define my own button using 'drawlist' event,but may be it is possible to reuse existing

![image](https://user-images.githubusercontent.com/20822365/82289234-00cc4380-99ad-11ea-9e68-5a17c6d98050.png)

**Comment by Viglino** [comment]
You can use css to place it. If it's not possible you have to define your own one...

**Comment by Dkkemaries** [comment]
Changing trash button position  by css does not work.  As a result I have shifted  trash button  over the refresh button.

Another option is to create my own trash button. But in this case ,when I try to remove layer , nothing happens. 

switcher.on('drawlist', function(e) {
    let layer = e.layer;
    let li = e.li;
    let lyr_class = layer.values_.title
    if (['testLayer'].indexOf(layer.values_.title)>=0) {
                    $('<div class = "switcherCustomButton fas fa-trash ' + lyr_class + '">')
                        .click(function () {
                         map.removeLayer(layer)
                        })
                        .appendTo($('> .ol-layerswitcher-buttons', li));
                }
});
