### ISSUE TITLE
Feature's image is transformed  in Perspective Map

### ISSUE THREAD

**Issue by foolseafish** [Viglino/ol-ext#457]
Hello and thank you for this awesome ol-ext.
I’m get in trouble when add a feature on the perspective Map, it seem like this:
![image](https://user-images.githubusercontent.com/51291517/82990380-b000be80-a02e-11ea-98cd-fc072013f1d6.png)
But i really want is like this:
![image](https://user-images.githubusercontent.com/51291517/82991190-e4c14580-a02f-11ea-969d-28abc5ad1705.png)
any solution will be grateful
Thanks.

**Comment by Viglino** [comment]
The image is on the map and the map is skewed thus the image is transformed too.
Use a popup overlayer or a Placemark.
NB: the feature is experimental and may be buggy with the last ol version (better use ol < 6).

**Comment by foolseafish** [comment]
Thank you for reply.
I have thought about this solution，but in fact the feature will have lot of styles. 
For example the sector one of the styles which will be changed by resolution changes as a polygon 
The feature like this:
![image](https://user-images.githubusercontent.com/51291517/83090234-e5f38080-a0ca-11ea-95c3-0c9ebc476404.png).
I also want to operate feature by using openlayers cluster and interactions e.g. translate,click,hover etc.

> The image is on the map and the map is skewed thus the image is transformed too.
> Use a popup overlayer or a Placemark.
> NB: the feature is experimental and may be buggy with the last ol version (better use ol < 6).

**Comment by foolseafish** [comment]
Hey Viglino.
I try to use popup overlayer. it has anohter problem:
When i drag the map, the popup overlay is on the wrong position.
The position i add the overlay:
![snipaste_20200529_172232](https://user-images.githubusercontent.com/51291517/83244105-77e5b100-a1d1-11ea-9384-8e1af4ef6206.png)
The position finally:
![snipaste_20200529_172256](https://user-images.githubusercontent.com/51291517/83244174-8f249e80-a1d1-11ea-9753-1c81da727fe9.png)

**Comment by Viglino** [comment]
Which version of ol are you using?
It only works with ol<6 and perspective maps.

**Comment by foolseafish** [comment]
I choose the version 5.3.3 but it still has the wrong position problem.
