### ISSUE TITLE
Change fill color in Profil

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#460]
Hi,
where/how can I change fill color like this
![Filled Profil](https://user-images.githubusercontent.com/56153843/83974621-0c959080-a8ef-11ea-9fc9-7d019a6e9221.png)
?

**Comment by vsevjednom-cz** [comment]
... and I don't know how to change blue color of Profil :(.

**Comment by Viglino** [comment]
You can't change colors: color is hard encoded...

**Comment by vsevjednom-cz** [comment]
Is it hard encoded in "ol-ext.js"? I can change it 🙃. What is a hexa code of the blue color? I can't find it.

**Comment by Viglino** [comment]
Hello,
I'll try to add a paramter to handle colors when creating the control to make it more reusable...

**Comment by Viglino** [comment]
Hello,
I've added a style option to change colors when creating the control.
I've updated the example to show how to.

**Comment by vsevjednom-cz** [comment]
You are so fast! **It's amazing!** Fill looks great! **Thank you!** And can I change color of Profil? I'm trying for example: `new ol.control.Profil({
		color: "green"
});`
or
`new ol.control.Profil({
	style: new ol.style.Style({
      color: new ol.style.Fill({ color: "green" })
    })
});`
but without success.

**Comment by vsevjednom-cz** [comment]
You are so fast! **It's amazing!** Fill looks great! **Thank you!** And can I change color of Profil? I'm trying for example: `new ol.control.Profil({
		color: "green"
});`
or
`new ol.control.Profil({
	style: new ol.style.Style({
      color: color: "green" 
    })
});`
but without success.

**Comment by Viglino** [comment]
Style is an ol Style, with text, fill, stroke, etc.
```javascript
new ol.control.Profil({ 
  style: new ol.style.Style({ 
    stroke: new ol.style.Stroke: ({ 
        width: 1.5, 
        color: "green" 
    }),
    fill: new ol.style.Fill: ({ 
        color: "yellow" 
    })
  }) 
});
```

**Comment by vsevjednom-cz** [comment]
It's perfect! Thaaanks!
