### ISSUE TITLE
Pause and resume a geoMarker in path

### ISSUE THREAD

**Issue by MateoParodi** [Viglino/ol-ext#462]
Hello!! First of all, thanks for this great library!

I have a vectorLayer as a Path and a geoMarker Point that simulates a truck on a route.
Like this example: [Animated Marker on Path](https://viglino.github.io/ol-ext/examples/animation/map.featureanimation.path.html)
I added some controls to play and stop this animation, but I'm not able to resume the animation from the paused (stop) point.

Is there a way to achieve this? Maybe by reducing the speed to 0 when its being animated? Or is a great idea to develop 😄

**Comment by Viglino** [comment]
There is no way to handle with a feature animation: the animation is played at ones.
If you want to want to move features on the map and have control on it, look at this example: https://viglino.github.io/ol-games/examples/map.sprite.path.html

**Comment by MateoParodi** [comment]
Awesome! I just achieved my goal thanks to an **ol-game**, thank you very much sr!
