### ISSUE TITLE
How to redo/undo merging multiple polygons operation?

### ISSUE THREAD

**Issue by kgloveyou** [Viglino/ol-ext#465]
I have written a control to merge multiple polygons (delete multiple polygons and add the union polygon)at a time.How to redo/undo this operation？
The current Redo/Undo interaction does this one by one,not synchronized.
I also have other controls  needing to keep the default actions of the redo/undo interatcion.

**Comment by Viglino** [comment]
Undo can be stacked in a block to make them undoing at one time. 
Just enclose operations between a `blockStart()` and `blockEnd()`.
```javascript
undoInteraction.blockStart();
// Make some stuff 
....
undoInteraction.blockEnd();
```

**Comment by Viglino** [comment]
In case you don't have access to the undo interaction, I've just pushed a new version to handle `undoblockstart` / `undoblockend` event on a map.
Thus you don't need to know the interaction but only the map it is on (the map of your control):
```javascript
this.getMap().dispatchEvent('undoblockstart');
// Do some stuff
...
this.getMap().dispatchEvent('undoblockend');
```
PS: keep in mind the block needs a end after a start to prevent error when undoing.

**Comment by kgloveyou** [comment]
> Undo can be stacked in a block to make them undoing at one time.
> Just enclose operations between a `blockStart()` and `blockEnd()`.
> 
> ```js
> undoInteraction.blockStart();
> // Make some stuff 
> ....
> undoInteraction.blockEnd();
> ```

Thanks，I have got it!
