### ISSUE TITLE
Enable and disable Transform interaction

### ISSUE THREAD

**Issue by GeorgeCodeHub** [Viglino/ol-ext#466]
I'm trying to add in my app the ability for the user to resize the elements drawn on it but only when the user opens a window to load them. I tried controlling that functionality with:

```
if( value === true) {
map.addInteraction(interaction)
else
{
map.removeInteraction(interaction)
}

```
However, when I try to remove the interaction I get an error `TypeError: this.getMap() is null`

I tried using `map.getInteractions().pop()` but it didn't seem to work.

Is it an internal bug or I'm I doing something wrong?

**Comment by Viglino** [comment]
If you want do activate/deactivate an interaction for a while, better use `setActive()` method:
```javascript 
interaction.setActive (value);
```

**Comment by GeorgeCodeHub** [comment]
That did the trick. Thank you so much! Is remove and add Interaction, not a recommended method?

**Comment by Viglino** [comment]
You can also remove the interaction but you don't have to if you have to reuse it after.
