### ISSUE TITLE
 ol-ext: Split interaction not works with GPX source

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#468]
Hi,
I want to create the segment from measured GPX (like you can know from Strava):
Click the mouse at the start/end of the segment (for example: my way to the store). And I want to save all these measured points (lon+lat) of this segment to MySQL or file (for example export these lon+lat to html tag input - and submit).

Your Split feature is amazing and I want to use it for creating segments. But it works only with vector.getSource().addFeature source and not works with GPX source. My code:

`var source = new ol.source.Vector( { url: '/gpx....', format: new ol.format.GPX() });
var vector = new ol.layer.Vector( { source: source,`

 ...

`map.addLayer(vector);`

 and I can't split it.

**Comment by Viglino** [comment]
You can use the split interaction to split your lines then select the segment you want to save.
http://viglino.github.io/ol-ext/examples/interaction/map.interaction.split.html

**Comment by vsevjednom-cz** [comment]
Look at this example: https://jedu.vsevjednom.cz/test.html

It's your code from http://viglino.github.io/ol-ext/examples/interaction/map.interaction.split.html with GPX file source. Split not works :(.

**Comment by Viglino** [comment]
Your "line" is a `MultiLineString`. Split only apply on `LineString`.
You have to convert the features to `LineString` first.
```javascript
vector.getSource().getFeatures().forEach(function(f) {
  if (f.getGeometry().getType()==='MultiLineString') {
    var geom = f.getGeometry().getCoordinates();
    var coords = geom.pop();
    var features = [];
    f.setGeometry(new ol.geom.LineString(coords));
    geom.forEach(function(c) {
      var fi = f.clone();
      fi.setGeometry(new ol.geom.LineString(coords));
      features.push(fi);
    });
    vector.getSource().addFeatures(features);
  }
})
```

**Comment by vsevjednom-cz** [comment]
Thank you! But where exactly must be this code? This code not works for me.

Example is here again: https://jedu.vsevjednom.cz/test.html

**Comment by Viglino** [comment]
Just convert features when they are added to the source (insert the code below after the source creation):
```javascript
source.on('addfeature', function(e) {
  var f = e.feature;
  if (f.getGeometry().getType()==='MultiLineString') {
    var geom = f.getGeometry().getCoordinates();
    var coords = geom.pop();
    var features = [];
    f.setGeometry(new ol.geom.LineString(coords));
    geom.forEach(function(c) {
      var fi = f.clone();
      fi.setGeometry(new ol.geom.LineString(coords));
      features.push(fi);
    });
    vector.getSource().addFeatures(features);
  }
});
```

**Comment by vsevjednom-cz** [comment]
Yes, it works, thanks! And last thing: how to get lon+lat (or something similar) of start and end of selected segment?

**Comment by Viglino** [comment]
Listen  to the `aftersplit` event to get the result:
```javascript
interactions.split.on('aftersplit', function(e) {
  // original feature geometry
  var c1 = e.original.getGeometry().getCoordinates(); 
  // first splitted feature
  var c2 = e.features[0].getGeometry().getCoordinates();
  // Get split point
  if (ol.coordinate.equal(c1[0], c2[0])) console.log(ol.proj.toLonLat(c2[c2.length-1]));
  else if (ol.coordinate.equal(c1[c1.length-1] === c2[c2.length-1])) console.log(ol.proj.toLonLat(c2[0]));
})
```
