### ISSUE TITLE
Get error when  clone a FontSymbol in a pointmove event

### ISSUE THREAD

**Issue by TownTowner** [Viglino/ol-ext#469]
Hi , 

I got an error when i clone a FontSymbol style in a pointmove event . 

FontSymbol init code:

`let style = this.getResourceStyle();

                if (style.getText())
                    style.getText().setText(text);
                let img = style.getImage();
                if (img instanceof ol.style.FontSymbol) {
                    img.getFill().setColor(color);//--------------------->this triggered error
                    img.renderMarker_();
                }
    fe.setStyle(style);`

pointmove clone code:

`let cloneStyle: ol.style.Style | ol.style.Style[];

                    let stroke: ol.style.Stroke;
                    if (style instanceof ol.style.Style) {
                        cloneStyle = style.clone();//--------------->got error
                        stroke = cloneStyle.getStroke();
                    } else if (style instanceof Array) {
                        let filterS = _.filter(style, s => !!s);
                        cloneStyle = _.map(filterS, x => x.clone());
                        let one = _.find(cloneStyle, x => !!x.getStroke());
                        if (one)
                            stroke = one.getStroke();
                    }`

yes ,  the page runs normally when i remove the `img.getFill().setColor(color)`;

i did the wrong way to set the symbol fill color ???

error msg:
angular-bundle.js:2 TypeError: Cannot read property '0' of null
    at yr (0.ol.js:7)
    at Object.dr [as asString] (0.ol.js:7)
    at ol.style.FontSymbol.drawMarker_ (02.ol-ext.js:9)
    at ol.style.FontSymbol.renderMarker_ (02.ol-ext.js:9)
    at MapLayerHandlerTrace.initFeature2 (MapLayerHandlerTrace.ts:302)
    at MapLayerHandlerTrace.ts:226

**Comment by Viglino** [comment]
I think a test is missing when there is no fill in the style.
There should be a test before setting the color:
```javascript
   if (img.getFill()) img.getFill().setColor(color);
```

**Comment by TownTowner** [comment]
Hi , 
Thank you for apply.

The test code didnt work . And I dubug it on the chrome . It showed errors below . 

![chrome_debug_drawMarker_fill](https://user-images.githubusercontent.com/10682896/85390335-461afc80-b57b-11ea-97bb-883f69a963f0.png)

but the getFill function return correctly...

![chrome_debug_getFill_](https://user-images.githubusercontent.com/10682896/85390574-95f9c380-b57b-11ea-8519-d37a297f268c.png)

**Comment by Viglino** [comment]
DO you have an online example?

**Comment by TownTowner** [comment]
Oh~~~~~~

IT WAS **MY FAULT**, 

I didnt **TEST the 'color' param** before set the Fill color...

Sorry to waste your time . . .
