### ISSUE TITLE
Transform style selection and change position handles

### ISSUE THREAD

**Issue by GeorgeCodeHub** [Viglino/ol-ext#470]
Is it possible to highlight the selection you make on the Transform Interaction and also change the position of the handles? Below a visual example on what I'm trying to accomplish:

_Not Selected_
![Unselected](https://user-images.githubusercontent.com/54906099/85277588-4ee0d500-b48c-11ea-915f-8fbdf0e5fd40.png)
_Selected_
![Selected](https://user-images.githubusercontent.com/54906099/85277586-4dafa800-b48c-11ea-92f5-723a8c7951b4.png)

**Comment by Viglino** [comment]
You can listen to the `select` event to add the selection to your own select interaction.
You can also prevent the interaction to select features (using selection:false option) and use your own selection. You have to add new selection programmatically `transformInteraction.select(feature, true/false)`
Handles can be styled using the `setStyle`method or the `style` option (see example).

**Comment by GeorgeCodeHub** [comment]
Thank you for the response. Is it also possible for someone to create their own handler? For instance, I want to set up an extra rotation handle where the user is able to turn an item by 45 degrees only.

**Comment by Viglino** [comment]
You have to dig in the code to do that...

**Comment by GeorgeCodeHub** [comment]
Oh, I see. Thank you for the quick response!
