### ISSUE TITLE
Clustering on existing vector layer

### ISSUE THREAD

**Issue by Teorizzi0** [Viglino/ol-ext#471]
Hi! 

First of all, excellent job with the Clustering Map (http://viglino.github.io/ol-ext/examples/map/map.clustering.html) it looks very helpful and useful!

I am trying to use the same animation on an already existing vector layer (a simple GeoJSON taken from GeoServer), so basically I won't use any function to create random feature because I have already them. 

Is it possible to make the clusters (and of course the chart) according to different value of an attribute field like "category" of the overstated vector layer? 

I hope I was clear,
Thanks in advance

**Comment by Viglino** [comment]
Hello,
You have to look at the `getStyle` function in the example to create your own style.
The chart in the example depends on the number of feature based on a `type` property. You have to calculate your own `data`.
```javascript
// Calculate a list of value based on feature type
var data = [0,0,0,0];
for (var i=0, f; f=features[i]; i++) data[f.get('type')]++;
```
