### ISSUE TITLE
Can't apply offset to ol.style.Photo

### ISSUE THREAD

**Issue by xuko** [Viglino/ol-ext#472]
I'm trying to apply offset in a ol.style.Photo to make it get over another ol.style.Icon in an especific area with no success.

I saw in [Doc ](https://viglino.github.io/ol-ext/doc/doc-pages/ol.style.Photo.html)there is an offsetX, offsetY but nothing happens.
I saw in Doc too that it extends from [ol.style.RegularShape](https://openlayers.org/en/latest/apidoc/module-ol_style_RegularShape-RegularShape.html) and I tried the displacement option, but nothing :(

this is my Styles:

```javascript
[
      new ol.style.Style({
        image: new ol.style.Icon({
          anchor: [iconX, iconY],
          size: [size, size],
          color: 'blue',
          src: `../../../../assets/icons/mtx/svg/person.svg`,
        }),
        zIndex: 100,
      }),
      new ol.style.Style({
        image: new ol.style.Photo({
          src: avatar,
          radius: 8,
          crop: true,
          kind: 'circle',
          displacement: [0, -30],
          offsetX: -30,
          offsetY: -30,
        }),
        zIndex: 101,
      }),
    ]
```

**Comment by Viglino** [comment]
The offset is not taken into account in the code...

**Comment by Viglino** [comment]
Now it is 😄

**Comment by Viglino** [comment]
I've also added a `setOffset()` method...
