### ISSUE TITLE
mask feature cant set feature is Circle

### ISSUE THREAD

**Issue by macheteHot** [Viglino/ol-ext#473]
set mask feature is Circle don't work

**Comment by macheteHot** [comment]
may be i can use createRegularPolygon get MultiPolygon
has any ohter solution ?

**Comment by Viglino** [comment]
Mask only handles polygons. 
You have to transform the feature geometry to polygon using [`fromCircle`](https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html#.fromCircle) to get it work.

```javascript
f.setGeometry(ol.geom.Polygon.fromCircle(f.getGeometry());
var crop = new ol.filter.Crop({ feature: f, inner:false });
```

**Comment by macheteHot** [comment]
> Mask only handles polygons.
> You have to transform the feature geometry to polygon using [`fromCircle`](https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html#.fromCircle) to get it work.
> 
> ```js
> f.setGeometry(ol.geom.Polygon.fromCircle(f.getGeometry());
> var crop = new ol.filter.Crop({ feature: f, inner:false });
> ```

thank you
