### ISSUE TITLE
"Popup function" in Profil

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#477]
Hi,
I'm looking for "reverse" of popup function. Example: mouse flies over GPX source line and shows this point in Profil.

What do you think about it?

**Comment by Viglino** [comment]
I've added a function to handle that:
```javascript
// Show profil at coord
profil.showAt(coord);
// Show profil at a distance (1km)
profil.showAt(1000);
```
See example online: https://viglino.github.io/ol-ext/examples/control/map.control.profil.html

**Comment by vsevjednom-cz** [comment]
You're so speed! Thanks! But I've got weird problem. It not works between some random kilometers depending on the zoom of the map. Here between 2,4 and 4.3 km: https://jedu.vsevjednom.cz/activity/2044

**Comment by Viglino** [comment]
You're using a Flowline style that doesn't impress the hit-detection map and make the line not selectable (and thus no hover on it). You have to double its style as in this example, using a transparent style: https://viglino.github.io/ol-ext/examples/style/map.style.flowline.html
Alos see  #420 
```javascript
// Transparent style to make the feature selectable
var transparentStyle = new ol.style.Style({
  stroke: new ol.style.Stroke({ color: [255, 255, 255, .1], width: 1 })
});
// Flow style
var flowStyle = new ol.style.FlowLine({
...your definition
});
var linestyle = [ transparentStyle, flowStyle ];
```
The transparentStyle will be drawn under the flowStyle and not visible but make the line selectable.

**Comment by vsevjednom-cz** [comment]
Yes, it works!

But I can't set transparentStyle to transparent. I still see 1px green line.
`var transparentStyle = new ol.style.Style({
  stroke: new ol.style.Stroke({ color: [255, 255, 255, .1], width: 1 })
});`
I tried to change color to red, black, white - without success. Also tried to change ".1" to 0, 10, 100 - again without change.

And what do you think about show ol.geom.Point in the map when mouse flies over GPX..?

**Comment by vsevjednom-cz** [comment]
Yes, it works!

And what do you think about show ol.geom.Point in the map when mouse flies over GPX..?

**Comment by Viglino** [comment]
That's on your side. You have to place a point on the map on hover.
I've modify the exemple, you can see howto: https://viglino.github.io/ol-ext/examples/control/map.control.profil.html

**Comment by vsevjednom-cz** [comment]
Yes! One last thing: altitude/speed popup text in Profil isn't changing while I'm flying with mouse at the map - as you can see here https://jedu.vsevjednom.cz/activity/2028 (first you must fly over the Profil and then at the map)
I know you haven't got this popup text at your example here https://viglino.github.io/ol-ext/examples/control/map.control.profil.html - so can I somehow fix this popup?
And Profil shows altitude as speed in speedprofil).

**Comment by vsevjednom-cz** [comment]
Yes! One last thing: altitude/speed popup text in Profil isn't changing while I'm flying with mouse at the map - as you can see here https://jedu.vsevjednom.cz/activity/2028 (first you must fly over the Profil and then at the map)
I know you haven't got this popup text at your example here https://viglino.github.io/ol-ext/examples/control/map.control.profil.html - so can I somehow fix this popup?

**Comment by Viglino** [comment]
You have to show the popup using the `profil.popup()` method.
The `profil.showAt()` method now return the point you are pointing at to be use in the popup to show informations.
The example use it with the profil on the map to show altitude (line 183-184): https://viglino.github.io/ol-ext/examples/control/map.control.profil.html
