### ISSUE TITLE
Endless loop in Search* controls

### ISSUE THREAD

**Issue by labronico0586** [Viglino/ol-ext#482]
When options.maxHistory is set to a negative value (-1 should mean no history) and options.reverse is set to true (reverse geo coding enabled) the _handleSelect function never ends due to infinite loop at line 329
```
while (hist.length > (this.get('maxHistory')||10)) {
    hist.pop();
  }
```

as it is `hist.length >maxHistory` forever.

**Comment by Viglino** [comment]
Done in the last commit
