### ISSUE TITLE
Search Feature Usage

### ISSUE THREAD

**Issue by xdursoc** [Viglino/ol-ext#484]
Hi,

I have a question regarding the SearchFeature tool. 

I defined my vector source like:
```javascript
      vm.vectorSource = new VectorSource({
        features: vm.accumulo
      });
```

and for the search feature:
```javascript
          // Set the control grid reference
	        vm.search = new SearchFeature(
		        {	//target: $(".options").get(0),
			        source: vm.vectorSourceComments,
			        property: "text"  //---> PROBLEM
		        });
	        vm.map.addControl (vm.search);
```

in the source I have my features :
```javascript
        vm.iconFeature = new Feature({
          geometry: new Point([project.coordinateTx[0], project.coordinateTx[1]]),
          nature: "project",
          projectFeatures: project
        });
```
project is an object with an attribute "name", in which way I need to define my property to search on project.name feature?

**Comment by Viglino** [comment]
Hello,
If your search attribute is not a feature property, you have to défine a `getTitle` and `getSearchString` option to return the string displayed in the index menu and the string to search on.
If `getSearchString` is not defined `getTitle`is used (but you can concatenate many attribute to search on and display only one in the menu).
```javascript
vm.search = new SearchFeature({
   source: vm.vectorSourceComments,
   getTitle: function(feature) { 
     // Title to display in the index
     return feature.project.name;
   },
   getSearchString: function(feature) {
     // Search string
     return feature.project.name;
   }
});
```

**Comment by xdursoc** [comment]
Thanks @Viglino, it works!

**Comment by xdursoc** [comment]
Hi, @Viglino I have another question: It is possible to use more than 1 source for the search tool?

**Comment by JURASINTERGEO** [comment]
Hi @Viglino. First - great extension for OL!!! I use your search feature control to search some features in WFS GeoGJSON. It works perfectly, I wander is there any chance to list more properties meybe comma separated in the index? I have many features with the same value of property and it's hard to choose which is the correct one. Here is my code:

var search = new ol.control.SearchFeature(
  { source: searchSource,
    property: 'numer',
  });
map.addControl (search);

the result is: 
![image](https://user-images.githubusercontent.com/58595797/96997010-37e0eb00-1531-11eb-93ef-785cf471e91c.png)

**Comment by Viglino** [comment]
You have to define the `getTitle` and `getSearchString` options to let the control know what you want to display and what you want to search in...
```javascript
@param {function} options.getTitle a function that takes a feature and return the name to display in the index, default return the property 
@param {function | undefined} options.getSearchString a function that take a feature and return a text to be used as search string, default geTitle() is used as search string
```
```javascript
var search = new ol.control.SearchFeature({ 
  source: searchSource,
  getTitle: function(feature) {
    return feature.get('name') +'('+ feature.get('numer') +')'
  },
  getSearchString : function(feature) {
    return feature.get('numer')
  },
});
```

**Comment by JURASINTERGEO** [comment]
Thank You @Viglino very, very much it works!!! :)

**Comment by JURASINTERGEO** [comment]
Is there any way to search exactly the string for example : 123, now when I'm searchnig 123 I have 123/1, 123, 1123 etc. 

getTitle: function(feature) {
      return feature.get('numer') + ', obręb:'+ feature.get('obręb') +''
    },
autocomplete: function (s) {	
      var result = [];
      // regexp
      s = s.replace();
      var rex = new RegExp(s);
      // The source
      var features = searchSource.getFeatures();
      for (var i=0, f; f=features[i]; i++) {
        if (rex.test(f.get('numer'))) {	
          result.push(f);
          if ((35)<=0) break;
        }
      }
      return result;
    },

Should I modify regexp?

**Comment by Viglino** [comment]
You can use regex syntax...
\b123\b should work...

**Comment by JURASINTERGEO** [comment]
Yes, I tried both s = s.replace("^$")  and s = s.replace("\b^\$\b") or s = s.replace(/^\$/g,'') - still it doesn't do what I would like it to do :(

**Comment by Viglino** [comment]
working for me on https://viglino.github.io/ol-ext/examples/search/map.control.search.html
- searching `l` gets 3 entries: `London, Bruxelles, Berlin`
- searching `^l` gets only one: `London`
- searching `a` gets 3 entries: `Paris, Madrid, Roma`
- searching `a$` gets only one: `Roma`

```javascript
autocomplete: function (s, cback){
  var result = [];
  // New search RegExp start (^) and end ($) with
  var	rex = new RegExp(s ? '^'+s+'$' : '\.*', 'i');
  for (var i=0; i<positions.length; i++) {
    if (rex.test(positions[i].name)) result.push (positions[i]);
  }
  /* Return result directly... */
  return result;
}
```

**Comment by JURASINTERGEO** [comment]
Thank You very much! It works :)
