### ISSUE TITLE
Popup Overlay example does not work on UXP, FF52.x or Webkit

### ISSUE THREAD

**Issue by g4jc** [Viglino/ol-ext#485]
Example Page: https://viglino.github.io/ol-ext/examples/popup/map.popup.html

Expected Result: Should be able to click on the cameras to see popups.

Actual Result: Nothing happens.

Originally suspecting a Polyfill problem, I appended `&flags=always` to script on each HTML page, as such: `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL,Object.assign&flags=always"></script>`

However, forcing a polyfill still resulted in no affect.

Tested against the following browsers:
* [Pale Moon](http://www.palemoon.org/) and other [UXP](http://thereisonlyxul.org) applications
* [Firefox 52](https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/)
* webkit-gtk-2.26 ([surf](https://surf.suckless.org/), etc.)

While backwards compatibility is needed for these browsers, I would also be interested in a detailed description of which function or element is being used that all of these browsers are missing so that I can try and get a bug filed in UXP for it's implementation.

Thanks for your time and the library.

**Comment by Viglino** [comment]
Hello,
It's an Openlayers issue. 
Openlayers removed Pointer events polyfill since [v6.4.0](https://github.com/openlayers/openlayers/releases/tag/v6.4.0).

> If you are targeting older browsers that do not support Pointer events, you now need to include a pointer events polyfill ([elm-pep](https://npmjs.com/package/elm-pep) or [pepjs](https://www.npmjs.com/package/@openlayers/pepjs)) in your application.

@+

**Comment by damjang** [comment]
Thank you! Yes, I can confirm that adding elm-pep or pepjs to the page work ok.
