### ISSUE TITLE
How to display pie chart for custom vector layer from GeoServer?

### ISSUE THREAD

**Issue by Spatialghost** [Viglino/ol-ext#486]
Hi. I try to use diagrams in my application and i need help. Samples http://viglino.github.io/ol-ext/examples/style/map.style.chart.html , http://viglino.github.io/ol-ext/examples/style/map.style.chart+text.html not working. How to display pie chart for custom vector layer from GeoServer?

**Comment by Viglino** [comment]
It seems some example are not working on the last ol version (#483). But I can't see why as there are working on my side.
Try to use a lower version of ol (ol@6.3.1 or ol@5.3.0).

To display pie charts, you have to create your own style function and add it to the layer style (or pass the style function on layer creation :
```javascript
function getFeatureStyle (feature) {
  var style = new ol.style.Style({
    image: new ol.style.Chart({
      type: 'pie',
      radius: 15,
      data: feature.get("data") // an array of data to display as chart
    }),
    stroke: new ol.style.Stroke({
      color: "#fff",
      width: 2
    }),
  });
  return [style];
}

layer.setStyle(getFeatureStyle)
```

**Comment by Spatialghost** [comment]
> 
> 
> It seems some example are not working on the last ol version (#483). But I can't see why as there are working on my side.
> Try to use a lower version of ol (ol@6.3.1 or ol@5.3.0).
> 
> To display pie charts, you have to create your own style function and add it to the layer style (or pass the style function on layer creation :
> 
> ```js
> function getFeatureStyle (feature) {
>   var style = new ol.style.Style({
>     image: new ol.style.Chart({
>       type: 'pie',
>       radius: 15,
>       data: feature.get("data") // an array of data to display as chart
>     }),
>     stroke: new ol.style.Stroke({
>       color: "#fff",
>       width: 2
>     }),
>   });
>   return [style];
> }
> 
> layer.setStyle(getFeatureStyle)
> ```

Thank You for callback, but im new in JS and OL. Explane me please, how to make pie char. At the GeoServer i have vector layer with name "Cities", in this layer i have next fields: city, lawyers, doctors, economists. I need create pie charts for every city. Please help.

**Comment by Viglino** [comment]
You have to know what to put in the charts, ie. which properties contains the values to put in the data array of the Chart style.
Let suppose lawyers, doctors, economists are properties with a number of lawyers, doctors, economists, etc. you have to put this values in the data array (using `feature.get` to get the value of the feature propertie):
```javascript
function getFeatureStyle (feature) {
  var style = new ol.style.Style({
    image: new ol.style.Chart({
      type: 'pie',
      radius: 15,
//>>> an array of data to display as chart
      data: [ feature.get('lawyers'), feature.get('doctors'), feature.get('economists') ]  
//<<<
    }),
    stroke: new ol.style.Stroke({
      color: "#fff",
      width: 2
    }),
  });
  return [style];
}

layer.setStyle(getFeatureStyle)
```

**Comment by Spatialghost** [comment]
> 
> 
> You have to know what to put in the charts, ie. which properties contains the values to put in the data array of the Chart style.
> Let suppose lawyers, doctors, economists are properties with a number of lawyers, doctors, economists, etc. you have to put this values in the data array (using `feature.get` to get the value of the feature propertie):
> 
> ```js
> function getFeatureStyle (feature) {
>   var style = new ol.style.Style({
>     image: new ol.style.Chart({
>       type: 'pie',
>       radius: 15,
> //>>> an array of data to display as chart
>       data: [ feature.get('lawyers'), feature.get('doctors'), feature.get('economists') ]  
> //<<<
>     }),
>     stroke: new ol.style.Stroke({
>       color: "#fff",
>       width: 2
>     }),
>   });
>   return [style];
> }
> 
> layer.setStyle(getFeatureStyle)
> ```

Thank You!
Its working perfect!
