### ISSUE TITLE
Customizing the style of the search box in nominatim

### ISSUE THREAD

**Issue by psilvao** [Viglino/ol-ext#487]
First of all, thank you very much for your effort in publishing the extension library for OpenLayers.

My query is as follows, as you can see I'm working on a PWA using your library and other additions, but I need to customize the nominatim search box. To do this, I have tried unsuccessfully to find the parameters to adjust the width and height that configure the search box.

Could you please give me a hand?

![image](https://user-images.githubusercontent.com/2114081/89413256-859a4400-d6f6-11ea-8827-b5235e326681.png)

**Comment by Viglino** [comment]
The control is a classical DOM element. 
You can access its characteristics through css. Just overwrite the with / height / max-width etc. in your css.

**Comment by jerto** [comment]
Per your example, your search box is inside a control bar. So you just have to traverse the DOM from the bar and set the css you want.
Here is an example I've just tried with Jquery on a demo app and that you can adapt :
$(".ol-bar").first().find('ul').parent().css({"width":"500",'border':'1px solid red'});

**Comment by Viglino** [comment]
To create a PWA with a search box, you can also put it in a panel using an [overlay](https://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html) or [Sidebar](https://github.com/Turbo87/sidebar-v2)
Here is an example with Sidebar that [include a layerswitcher and a search control](https://codepen.io/viglino/pen/vxGOQN?editors=0010)
