### ISSUE TITLE
How to capture click event on placemark?

### ISSUE THREAD

**Issue by costales** [Viglino/ol-ext#488]
Hi,

Please, in [this example](https://viglino.github.io/ol-ext/examples/popup/map.placemark.html), how can I detect a click on the icon itself?

Thanks in advance!

**Comment by jerto** [comment]
As you need JQuery to use the popup, I would try and find something in the DOM to identify the popup and then trigger a function on click. The popup as the ol-popup-content class so you could try something like the following 👍 

$(document).off('click').on('click','.ol-popup-content',function(){
       doSomething()
    })

**Comment by costales** [comment]
Thank you, but I was thinking in a event triggered from openLayers, because I could have multiple markers... any idea please?

**Comment by jerto** [comment]
I guess it's not working because you are trying to select an overlay the way you select a feature.
An overlay is a plain DOM element so you have to use JQuery or Vanilla JS to select it.
Maybe someone else will be able to help you.

**Comment by Viglino** [comment]
Has @jerto says the icon is a popup on top of the map, not a feature.
It's a convenient to display information on top of the map not to deal with features. 
You can't select it using Openlayers, you have to deal with jQuery or JS to attach a click event on it...

**Comment by Viglino** [comment]
Using jQuery you can do something like:
```javascript
$('body').on('click', '.placemark', function(e) { 
  console.log('click');
})
```
