### ISSUE TITLE
Font style - shadow

### ISSUE THREAD

**Issue by cazacugmihai** [Viglino/ol-ext#489]
Selecting `shadow` in [Font Style](https://viglino.github.io/ol-ext/examples/style/map.style.font.html) page doesn't change the marker's style.

**Comment by jerto** [comment]
Actually it does. If you select offset as well, you'll notice that the shadow is applied to the point, not the icon.

**Comment by cazacugmihai** [comment]
Without shadow:
![without-shadow](https://user-images.githubusercontent.com/89212/89766514-efed2300-db00-11ea-8af2-b452b50eea44.png)

With shadow:
![with-shadow](https://user-images.githubusercontent.com/89212/89766525-f7acc780-db00-11ea-91d7-6b4a97356d6b.png)

**Comment by cazacugmihai** [comment]
I thought I'd see something like [this](http://viglino.github.io/OpenLayers-ext/examples/map.popup.html).

**Comment by jerto** [comment]
I guess it is another  problem due to some changes in Openlayers.
Once more, it works fine form me in Brave but not in Chrome.
![Capture](https://user-images.githubusercontent.com/109032/89767955-350e5680-dafb-11ea-8dd0-4f50a953704d.JPG)

**Comment by Viglino** [comment]
Yes! the shadow style has to deal with pixel ratio too...  #483

**Comment by Viglino** [comment]
Fixed in the last commit

**Comment by cazacugmihai** [comment]
Thank you!
