### ISSUE TITLE
Clustering map - markers are shown with ~1sec delay

### ISSUE THREAD

**Issue by cazacugmihai** [Viglino/ol-ext#491]
After clicking a cluster in [Clustering map](https://viglino.github.io/ol-ext/examples/map/map.clustering.html) page, there is ~1 second delay until the markers are shown (`animation` is not selected).

**Comment by Viglino** [comment]
That's the standard behavior of the [ol/interaction/Select](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select.html) as the default value for the `condition` option is `singleClick`.
`singleClick` will wait for a second click and is fired only if none.
To prevent this you have to use the [ol/events/condition.click](https://openlayers.org/en/latest/apidoc/module-ol_events_condition.html#.click) condition that will be fired as soon as the user clicks (and fired twice on double click).
I've modified the example to reflect this.

**Comment by cazacugmihai** [comment]
Thank you @Viglino for the explanation! It was really helpful!

From my point of view, the behavior of `singleClick` condition is very subtle and gives the users (the ones that are using OpenLayers for the first time) the impression of a non-performing library (compared with the alternatives).

Thank you once again for your help!
