### ISSUE TITLE
Snap Guide not working when map view uses EPSG:3949 projection

### ISSUE THREAD

**Issue by magnet31** [Viglino/ol-ext#493]
At last line of ol.interaction.SnapGuides.prototype.setMap 
 projExtent is set to null because EPSG:3949 projection has a null extent
later this will cause an error in ol.interaction.SnapGuides.prototype.addGuide when trying to compute guideLength

**Comment by Viglino** [comment]
You have to define the projection extent to let the guide draw. 
Use (https://epsg.io/3949):
```javascript
  ol.proj.get('EPSG:3949').setExtent([616075.94, 7417071.95, 2211465.79, 8509711.64]);
```
