### ISSUE TITLE
FontAwesomeDef is displaying the code instead of its image

### ISSUE THREAD

**Issue by cazacugmihai** [Viglino/ol-ext#494]
Modifying [Font style](https://viglino.github.io/ol-ext/examples/style/map.style.font.html) page by adding this code (just before [getFeatureStyle](https://github.com/Viglino/ol-ext/blob/master/examples/style/map.style.font.html#L302) method):

```
var cachedFeatureStyle = new ol.style.Style({
  image: new ol.style.FontSymbol({
    form: 'marker',
    glyph: 'fa-circle',
    fontSize: 0.5,
    radius: 20,
    rotation: 0,
    rotateWithView: false,
    offsetY: -20,
    color: '#FFF',
    fill: new ol.style.Fill({
      color: '#0000FF'
    }),
    stroke: new ol.style.Stroke({
      color: '#0000FF',
      width: 1
    })
  }),
  stroke: new ol.style.Stroke({
    width: 2,
    color: '#f80'
  }),
  fill: new ol.style.Fill({
    color: [255, 136, 0, 0.6]
  })
});
```

and modifying the `getFeatureStyle` in order to return the `cachedFeatureStyle`:
```
// Style function
function getFeatureStyle (feature) {
  if (true) {
    return cachedFeatureStyle;
  }
  ...  
```
results in:

![image](https://user-images.githubusercontent.com/89212/90669305-1e35d580-e25a-11ea-9a79-807138f4c168.png)

The marker's image appears after pressing `F5` (most likely because the stylesheet is already in cache).

Thank you!

**Comment by Viglino** [comment]
The font have to be loaded before the style creation.
If you create your cache before the font load the cache won't contains the font symbol.
You have to use a third party library such as [WebFontLoader](https://github.com/typekit/webfontloader) to get events to control the font loading.
See [map.dbpedia](http://viglino.github.io/ol-ext/examples/layer/map.dbpedia.html) for a full implementation.
