### ISSUE TITLE
Issue in OpenLayer 6.3.1

### ISSUE THREAD

**Issue by somasekhar233** [Viglino/ol-ext#498]
**ERROR in ./node_modules/ol-ext/featureanimation/FeatureAnimation.js
Module not found: Error: Can't resolve 'ol/source/vector' in '/home/somu/newDev/narmada/ui/node_modules/ol-ext/featureanimation'**
ol: '6.3.1',
ol-ext: '3.1.12'

are this two versions compactable if yes it's trying to find out vector source form small **vector** instead of ### Vector
if no can you please provide me with the proper version for the ol 6.3.1

**Comment by cazacugmihai** [comment]
Please take a look at this [PR](https://github.com/Viglino/ol-ext/pull/475). You have to use `ol-ext@3.1.14`.
