### ISSUE TITLE
Multi Layer PopupFeature

### ISSUE THREAD

**Issue by alessiodl** [Viglino/ol-ext#499]
Hi, 
i really appreciate this fantastic library!

It would be very useful in my opinion if the PopupFeature could operate on more than one layer at the same time, using an array of templates. So, clicking on a point, the user could extract attributes from each feature of each layer under that point. 

Is this feasible?

**Comment by Viglino** [comment]
On a more generic way the popup template should depends on the feature itself (its properties, or its layer or anything else).
I think a better approach should be to let the user choose which template to use according the feature with a template function: 
```javascript
var popup = new ol.Overlay.PopupFeature({
  ...
  template: function(feature) { 
    return mytemplate
  }
);

**Comment by alessiodl** [comment]
yes, it should work well.
The idea is to have the possibility to define multiple templates, one for each selectable layer.

I created a custom popup a couple of years ago and used it for some applications with openlayers frontend and esri backend. 
It launches and identify request passing the click coordinates and the layer id to the rest api. The returned array of object is displayed as a paginated result in the popup using a different template for each layer. 

``` 
var popup = new ol.Overlay.PopupFeature({
  ...
  template: function(feature, layer) { 
      if (layer && layer.get('name')=='mylayer')
        return mytemplate
      } else {
        // different template or even nothing 
      }
  }
); 
```

In my case, the function retrieves data from the server-side rest api, but I think this mechanism should be implemented in a pure client-side solution also.

**Comment by alessiodl** [comment]
Hi, having different template objects, it is pretty easy to set the right one with the setTemplate method. Just use the 'click' event on the map object to check to which layer the clicked feature belongs. 
It to would be grate to have an event associated with the forward and backward arrows of the paging element in the PopupFeature, making it possible to set the right template "on the fly" for every page, by conditions (i.e. use template A or template B on the base of the layer or a particular attribute in the feature). 
Grate job, anyway!

**Comment by Viglino** [comment]
@alessiodl 
You can know set the template options as a function that returns a template to let the user choice its template depending on the current feature...
```javascript
var popup = new ol.Overlay.PopupFeature({
  popupClass: 'default anim',
  select: select,
  canFix: true,
  // Choose our own template
  template: function(f) {
     if (f.get('type')===1) return template1;
     else return template2;
  }
});
```
Features are not associated with a layer as they can be put in multiple source/layer, but you can set the layer as a feature's property using `addfeature` event:
```javascript
// Set layer template
layer.set('template', myTemplate);
// Set layer property
layer.getSource().on('addfeature', function(f) {
  f.set('layer', layer)
});
// Popup
var popup = new ol.Overlay.PopupFeature({
  popupClass: 'default anim',
  select: select,
  canFix: true,
  // Get layer template
  template: function(f) {
     return f.get('layer').get('template');
  }
});
```

**Comment by alessiodl** [comment]
Great! Many thx!

**Comment by shitathakin** [comment]
when i use 
```
layer.getSource().on('addfeature', function(f) {
f.set('layer', layer)
});
```
it treats as f as a VectorSourceEvent instead of a feature meaning f.set is not a function. Do you have an idea of why this might be?
