### ISSUE TITLE
More GPXs in one map depending on the time

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#501]
New idea: is possible to create something like Strava flybys? Example: I rode at my bike yesterday from 10 to 12 hour and my friend rode his bike from 10 to 12 hour too - but 1 km far from me. I've got two GPXs and I want to see at map our positions depending on the time - when my mouse fly over the "timeprofil".

**Comment by Viglino** [comment]
You have to use 2 profiles and sync them together.
Something like this:
```javascript
profile1.on('over', function(e) {
  var time = e.coord[3];
  // Look where is the time on profil2
 // use profile2.showAt to set the profile on this point
}
```
I'll have a look to see if its possible to add a `showAtTime` to help this and show a point on a profile at a given time.

@+

**Comment by Viglino** [comment]
I've added a `pointAtTime` method to get the point at a given time on the profile:
```javascript
profile1.on('over', function(e) {
  var time = e.coord[3];
  // Look where is the time on profile 2
  var pt = profile2.pointAtTime(time);
  // Show point on profile 2
  profile2.showPointAt(pt);
}
```

**Comment by vsevjednom-cz** [comment]
You are so speed again, thanks! Can you show me page with this example? I've got two GPXs with same time but I can't show point of profile2 in the map.
`Uncaught TypeError: profile2.pointAtTime is not a function`
What is the source of profile2 variable?

**Comment by vsevjednom-cz** [comment]
You are so fast again, thanks! Can you show me page with this example? I've got two GPXs with same time but I can't show point of profile2 in the map.
`Uncaught TypeError: profile2.pointAtTime is not a function`
What is the source of profile2 variable?

**Comment by vsevjednom-cz** [comment]
I'm doing this:
`profile1.on(["over","out"], function(e)
		{	if (e.type=="over") profile1.popup(e.coord[2]+" "+profile1.info.altitudeUnits);
			drawPoint(e);
			if(typeof e.coord[3] !== "undefined") { var time = e.coord[3]; var pt = profile2.pointAtTime(time); profile2.showPointAt(pt); }'
		});`

Variable `profile2` is this: `new ol.control.Profil(`...

**Comment by vsevjednom-cz** [comment]
I'm doing this:
```
	profile1.on(["over","out"], function(e)
		{	if (e.type=="over") profile1.popup(e.coord[2]+" "+profile1.info.altitudeUnits);
			drawPoint(e);
			if(typeof e.coord[3] !== "undefined") { var time = e.coord[3]; var pt = profile2.pointAtTime(time); profile2.showPointAt(pt); }'
		});
```

Variable `profile2` is this: `new ol.control.Profil(`...

**Comment by vsevjednom-cz** [comment]
When I use profile2.showAt(pt) instead of profile2.showPointAt(pt) - error is gone but it still doesn't work.

**Comment by vsevjednom-cz** [comment]
When I use `profile2.showAt(pt)` instead of `profile2.showPointAt(pt)` - error is gone but it still doesn't work.

**Comment by vsevjednom-cz** [comment]
You are so fast again, thanks! Can you show me a page with this example? I've got two GPXs with same time but I can't show point of profile2 in the map.

When I use `profile2.showAt(pt)` instead of `profile2.showPointAt(pt)` - JS error is gone but it still doesn't work.

**Comment by Viglino** [comment]
Do you have an example online?

**Comment by vsevjednom-cz** [comment]
Yes, look at this here: https://jedu.vsevjednom.cz/activity/2188?flybys

Horizontal line at the "flybysprofil" works when I fly with my mouse over the "profil2". But vertical line at the "profil2" is weird when I fly with my mouse over the "flybysprofil". And point in the map of second profil not works in both.

**Comment by vsevjednom-cz** [comment]
Yes, look at this here: https://jedu.vsevjednom.cz/activity/2188?flybys

Vertical line at the "flybysprofil" works when I fly with my mouse over the "profil2". But vertical line at the "profil2" is weird when I fly with my mouse over the "flybysprofil". And point in the map of second profil not works in both.

**Comment by Viglino** [comment]
line 119: 
```javascript
flybysprofil.setGeometry(flybyssource.getFeatures()[0]);
```
`flybyssource.getFeatures()[0]` is null and fire an error thus `profil2.setGeometry` is never reached...

**Comment by vsevjednom-cz** [comment]
I'm trying and trying... You're right but I absolutely don't know hot to solve it. Could you help me?

Source of "source" ("profil2") is first GPX and source of "flybyssource" ("flybysprofil") is second GPX.

**Comment by vsevjednom-cz** [comment]
Can you show me an example? Pleeease 🙃.

**Comment by Viglino** [comment]
The example is in the code above.
line 1117 of your page (https://jedu.vsevjednom.cz/activity/2188?flybys) your looking for the loading of `source` but not `flybyssource`.
Instead you have to look for loading of booth sources and set the profil geometry only when booth sources are populated (`loadProfil` in the code obove)...

**Comment by vsevjednom-cz** [comment]
I understand, finally! So I changed the code but the result is still the same - not works 🤪.

**Comment by Viglino** [comment]
It seems to work for me on the laptime common to both tracks.

**Comment by vsevjednom-cz** [comment]
But you see one point in the map, right? I need to see at the map both position points depending on the time - when my mouse fly over "profil2" or "flybysprofil".

**Comment by Viglino** [comment]
If you want 2 points, you have to deal with 2 points. 
Actually you only have one line 1111 (pt) for both profile draw using `drawPoint()` function.
You have to define and display 2 points for each track using the coordinates given by `pointAtTime`...

**Comment by vsevjednom-cz** [comment]
I'm trying, example:
```
flybysprofil.on(["over","out"], function(e)
		{	if (e.type=="over") flybysprofil.popup(e.coord[2]+" "+profil2.info.altitudeUnits);
				drawPoint(e); //standard DrawPoint
			if(typeof e.coord !== "undefined") { var time = e.coord[3]; var pt = profil2.pointAtTime(time); profil2.showAt(pt); } // this line is for show the second point
		});
```
Do you see some mistake? 🙃

**Comment by Viglino** [comment]
`drawPoint(e)` draw a point on the map corresponding to the position of the flybysprofil.
`profil2.showAt(pt)` draw the point on profil2, not on the map.
You have to draw a second point on the map corresponding to the point on profil2 at the given time, using a drawPoint2 similar to drawPoint but with an other `ol.Feature` than pt defined line 1125:
```javascript
if(typeof e.coord !== "undefined") { 
  var time = e.coord[3]; 
  var pt = profil2.pointAtTime(time); 
  // show point on profil2
  profil2.showAt(pt);
  // Show point on the map
  drawPoint2({ coord: pt,  type:'over' })
}
```

**Comment by vsevjednom-cz** [comment]
Trying but "Profil2" doesn't draw point in the map right now :(.

**Comment by vsevjednom-cz** [comment]
Trying but "profil2" doesn't draw point in the map right now :(.

**Comment by Viglino** [comment]
You have to use 2 points (pt & pt2) if you want 2 points on the map:
```javascript
var pt2;
function drawPoint2(e){	
  if (!pt2) {
    pt2 = new ol.Feature(new ol.geom.Point([0,0]));
    pt2.setStyle([]);
    overlay.getSource().addFeature(pt2); // Hvězdička jedoucí po naměřené trase
  }
  if (e.type=="over"){
    // Show point at coord
    pt2.setGeometry(new ol.geom.Point(e.coord));
    pt2.setStyle(style);
  } else {
    // hide point
    pt2.setStyle([]);
  }
};
```

**Comment by vsevjednom-cz** [comment]
Yes! It works! Amazing! And one last thing: "profil2" point at map blinks and vertical line at "profil2" moves between two places when I fly with mouse over "flybysprofil". Do you know why?

**Comment by Viglino** [comment]
That's because of gaps in the time line (16:28 - 17:00 on track 1).
There is also a part of the first track that is followed back and forth that can explain the jump.

**Comment by vsevjednom-cz** [comment]
I understand but pause during measure is normal. So: is possible to let point at the time 16:28 when I fly with mouse at second profil in for example 16:30, 16:50 or 16:59?

**Comment by vsevjednom-cz** [comment]
I'm looking at 3.1.15.

How to display a point in the map in the last existing time?

It's here in code I think.
`    // Look for closest the point
    for (i=1; p=this.tab_[i]; i++) {
      var d = ol.coordinate.dist2d(p[3], where);
      if (d<d0) {
        p0 = p;
        d0 = d;
      } 
    }`

**Comment by vsevjednom-cz** [comment]
I'm looking at 3.1.15.

How to display a point in the map in the last existing time?

It's here in code I think.
```
    // Look for closest the point
    for (i=1; p=this.tab_[i]; i++) {
      var d = ol.coordinate.dist2d(p[3], where);
      if (d<d0) {
        p0 = p;
        d0 = d;
      } 
    }
```

**Comment by vsevjednom-cz** [comment]
I commented some lines. That works ok.

```
  // Look for closest the point
  for (i=1; p=this.tab_[i]; i++) {
    var t = p[3][3];
    if (t >= time) {
      // Previous one ?
      var pt = this.tab_[i-1][3];
/*      if ((pt[3]+t)/2 < time) */ return pt;
  //    else return p;
    }
  }
```
