### ISSUE TITLE
Search Feature usage for few GeoJSON layers

### ISSUE THREAD

**Issue by Spatialghost** [Viglino/ol-ext#502]
Hi, 
I have a question, is it possible use Search Feature for few GeoJSONs with different attribute fields?

`var search = new ol.control.SearchFeature(`
		`{`
			`source: injSource,`
			`property: "Object"`
		`});`
	`map.addControl (search);`

**Comment by Viglino** [comment]
You can use `getSearchString` option to create your own string to search in, depending on the feature passed as parameter.
But all GeoJSON must be loaded in the same source.

**Comment by Spatialghost** [comment]
> 
> 
> You can use `getSearchString` option to create your own string to search in, depending on the feature passed as parameter.
> But all GeoJSON must be loaded in the same source.

Thank You!
Its working!
