### ISSUE TITLE
GeoImage scale

### ISSUE THREAD

**Issue by mdellanave** [Viglino/ol-ext#505]
I'm trying to use GeoImage to set on a map an img previously aligned with distortableImage (https://github.com/publiclab/Leaflet.DistortableImage)
The problem is that distortableImage uses the image corners instead of the scale factor used by ol-ext GeoImage.

Assuming that distortAction will be disabled, is there a way to get the scale factor from the distortableImage corners coordinates?
Am I on the right way?

here the test app
https://codesandbox.io/s/suspicious-engelbart-xiv31
the img corners should match the circle features

the actual value of scale are generated using http://viglino.github.io/Map-georeferencer/ but I need a way to generate them from the distortableImage corners coordinates 

@Viglino do you think it's possible?

thank you

**Comment by Viglino** [comment]
Look at this repo: https://github.com/Viglino/Map-georeferencer
It lets you get the transform parameters: http://viglino.github.io/Map-georeferencer/

**Comment by carlosjpr-collab** [comment]
@Viglino  your solution is not specific.

**Comment by Viglino** [comment]
The Helmert transform implemented in the repo lets you get all the parameters giving a set of control points which is a good solution to the issue...
https://github.com/Viglino/Map-georeferencer/blob/gh-pages/helmerttransform.js
