### ISSUE TITLE
Cluster chart disapear when browser zoom is not 100%

### ISSUE THREAD

**Issue by natalidedik** [Viglino/ol-ext#506]
Cluster chart (donut, pie3D, etc.) disapear, when browser zoom is not 100%. Have a look to the gif I've created below
![bug](https://user-images.githubusercontent.com/9339886/91981199-20576400-ed31-11ea-87b4-3be683aa3c12.gif)

It is reproducible on your website http://viglino.github.io/, and also on my project, where I use AnimatedCluster for my purposes and cluster chart disapear when I change browser zoom. 
Just navigate to http://viglino.github.io/ol-ext/examples/style/map.style.chart.html and change the browser zoom to 125% or 150%, reload the page, change the width of #map to 50% (so you can see both map and right side) and try to switch between chart type options on the right. Some of them disapear all the time, so of them not always, but behaviour is quite strange. It is not always reproducible, I can reproduce from time to time, but still. 

That also reproducible when changing the windows zoom other then 100%
Any ideas on how to fix that?

**Comment by Viglino** [comment]
Using ol6, images are calculated once using the current pixel ratio. 
Changing this pixel ratio (or browser zoom) after this calculation will point to non existing images...
I'll try to see what can be done...
