### ISSUE TITLE
Can you show one example of using ol-ext with React. show pie charts on map

### ISSUE THREAD

**Issue by MadikMayCry** [Viglino/ol-ext#513]

**Comment by Viglino** [comment]
You can use `ol-ext` as any module (such as `ol`) in a React project.
Just look at examples using `ol` in React (https://dominoc925.blogspot.com/2019/10/simple-example-of-reactjs-and.html) ans import `ol-ext` classes as ol classes (just point to the `ol-ext` lib).
```javascript
// Import ol classes
import { 
    Map,
    View
 } from 'ol'
// Import ol-ext classes
import LayerSwitcher from 'ol-ext/control/LayerSwitcher'
```
