### ISSUE TITLE
How I can update getfetureinfo query based on changes in ol-switcher?

### ISSUE THREAD

**Issue by Navid61** [Viglino/ol-ext#514]
When I uncheck my layer in ol-layerswitcher or even when I did remove my layer from layers tree but I still able get info from removed or unchecked layer!, How I can update getfutureinfo based content of switcher?

**Comment by Viglino** [comment]
Which version of ol-ext are you using?
When you remove a layer from the map or when you change its visibility the layer switcher should reflect the state...
You can update the layer switcher using the `drawPanel` method.

**Comment by Navid61** [comment]
I am using version 3.1.12, thank you so much
