### ISSUE TITLE
Swipe is not swiping Point features on MVT layers in openlayers v6.0.0 and up

### ISSUE THREAD

**Issue by NicolasDiab** [Viglino/ol-ext#515]
Hi,

Starting from Openlayers v6.0.0 and up, Swipe is not working anymore on features Point geometry for MVT Tile layers. It works nicely for normal layers.

Reproduction :
[Codesandbox](https://codesandbox.io/s/swipe-example-forked-7t1e5?file=/src/index.js)
To see it fail, upgrade ol dependency version to 6.1.1 for instance. Transpile. Then when swiping, right layer will display points from left layer (only points - other geometries work as expected).
![not working](https://user-images.githubusercontent.com/7815347/94267870-99b33280-ff3c-11ea-9a36-8610bf6a0a5a.PNG)

Expected behaviour :
Points from left layer should be hidden from right layer when swiping. (set ol dependency to 5.3.3 for instance)
![expected](https://user-images.githubusercontent.com/7815347/94267821-7be5cd80-ff3c-11ea-8840-b84cb13a1467.PNG)

Thank you

**Comment by Viglino** [comment]
Hello,
I don't know why but the MVT layer is drawn in 2 separate canvas and I can only access one using the ol `prerender` event...
Let's me know if the same bug appears using the ol official example: https://openlayers.org/en/latest/examples/layer-swipe.html
If so it's an ol bug as I use the same mecanism to cliip the layer...

**Comment by mike-000** [comment]
It is due to decluttering, see https://github.com/openlayers/openlayers/issues/10096 - and even with a separate className the decluttered items are rendered after the layer's postrender event so a timeout is needed before restoring the context.  If using two MVT layers you will probably need to use two stacked synchronised maps (with the background set in the layer canvas, not the map div) as the top layer declutters icons and text from the bottom layer regardless of the position of the swipe. https://codesandbox.io/s/throbbing-mountain-emydk?file=/main.js

**Comment by NicolasDiab** [comment]
Hello, thank you for your quick replies !

I tried adding a className to the MVT layer but nothing changed.

To be sure, is ol-ext internally adding 2 layers to the map when we add 1 layer to the swipe control with `ctrl.addLayer(tileLayer)`? Should I create the 2 maps architecture in my project or is it a bug for ol-ext?

**Comment by Viglino** [comment]
ol-ext don't add any layer to the map it only uses the ones of the map to clip them.
In your example, moving to ol@6.4.3 and adding a delay in the `postcompose` method seems to solve the issue.

Just overwrite the postcompose method to add a delay to take into account the declutterring:
```javascript
Swipe.prototype.postcompose = function(e) {
  // restore context when decluttering is done
  setTimeout(function () {
    e.context.restore();
  }, 0);
};
const ctrl = new Swipe();
```
See: https://codesandbox.io/s/swipe-example-forked-k70xl
Fuulscreen: https://k70xl.csb.app/

I'll try to publish a fix to handle this case asap.

**Comment by mike-000** [comment]
I found that with a fast moving slice the next prerender can fire before the timeout, and if no check is made the clipping sometimes doesn't align with the slice.  The event counter used in my example is excessive, a simple boolean is sufficient (and there must be no delay with earlier single canvas versions of OpenLayers)


```
var pending = false;

layer.on('prerender', function (event) {
  var ctx = event.context;
  if (pending) {
    ctx.restore();
    pending = false;
  }

  ....
  ....

});


layer.on('postrender', function (event) {
  var ctx = event.context;
  pending = true;
  setTimeout(function(){
    if (pending) {
      ctx.restore();
      pending = false;
    }
  }, 0);
});
```

**Comment by NicolasDiab** [comment]
Viglino, your solution works like a charm for 1 MVT layer! Thanks!

However for multiple layers, with 1 MVT layer in map but not in swipe, the layer is swiped as if in left side of swipe.
See: [https://codesandbox.io/s/swipe-example-forked-66ozw?file=/src/index.js](https://codesandbox.io/s/swipe-example-forked-66ozw?file=/src/index.js)
Normal layer1 is in map but not in swipe -> works fine. MVT tileLayer2 is in map but not in swipe too -> doesn't work.

Is there a way to make it work for multiple MVT layers without using multiple ol maps as mike said?

**Comment by mike-000** [comment]
If you change the className of tileLayer2 to `"otherLayer2"` you should see a difference.

If the top MVT layer is not included in the swipe you should not need multiple maps, but with a top MVT layer in a swipe any items in lower layers which are overlapped by items in the top layer might be decluttered and would not appear even when the swipe reveals the lower lower.
