### ISSUE TITLE
DragRotateAndZoom and EditBar - Align rectangle to rotated map

### ISSUE THREAD

**Issue by NewToStuff** [Viglino/ol-ext#516]
Hi,

First of all thanks for your work on these extensions. I am new to using them but they look really cool:

I am in an Angular/ Typescript environment (but I don’t think that’s relevant) and I am wanting to combine the ability to DragRotateAndZoom from "ol/interaction/DragRotateAndZoom)" and then subsequently draw a rectangle based on the orientation of the rotated map. The default seems to be to draw on the aligned to the axes of the coordinate system. Ideally I want this to be a separate button but, not knowing how to do this, I have beend trying to use the DrawRegular.

I have found I can adhust the configuration of the DrawRegular interaction using code like that below: I can definitely adjust some elements like the start number of sides and set to false to disable. Once this is done though the tooltip hovering over the button shows ‘[object Object]’. It displays this also itf I remove the title: ‘New Draw’ issue.

```
  // Add the editbar
    var edit = new EditBar({ source: vector.getSource() ,  
      interactions: {
       DrawRegular:     new olext_interaction_DrawRegular ({
         source: vector.getSource(),
         type: "Circle",
         sides: 4,
         title: 'New draw',
         geometryFunction: geometryFunction
        })
      }
    });
```

with a Geometry Function as follows;

```
function geometryFunction(coordinates, geometry) {
  console.log('Geometry function tunning', coordinates,geometry);
  if (!geometry) {
      geometry = new Polygon(null);
  }

  var firstCorner = coordinates[0];
  var thirdCorner = coordinates[1];

  var currentViewRotation = this.map.getView().getRotation();

  var secondCorner = [thirdCorner[0], firstCorner[1]];
  var forthCorner = [firstCorner[0], thirdCorner[1]];

  if (currentViewRotation != 0) {
      var verticesToRotate = new MultiPoint([secondCorner, forthCorner]);
      var anchor = getCenter(verticesToRotate.getExtent());
      verticesToRotate.rotate(2 * currentViewRotation, anchor);
      secondCorner = verticesToRotate.getCoordinates()[0];
      forthCorner = verticesToRotate.getCoordinates()[1];
  }

  var newCoordinates = [firstCorner, secondCorner, thirdCorner, forthCorner, firstCorner];
  geometry.setCoordinates([newCoordinates]);
  return geometry;

}

```

The Geometry Function part of this came from another (rather old) question and was a bit of code offered to rotate the drawn rectangle. This does not seem to be having an effect and the rectangle continues to align to the coordinate system axis and not the rotated map. I picked up that 

`geometry = new Polygon(null); `

might need to be expressed as 

`geometry = new Polygon([]);`

but this did not seem to give any adjustment.

Am I approaching this in an incorrect way or is the functionality no longer available. Any help/ pointers greatly appreciated.

Thanks

Paul

**Comment by Viglino** [comment]
Seems to work for me using this code:
```javascript
function geometryFunction(coordinates, geometry) {
  console.log('Geometry function tunning', coordinates, geometry);
  if (!geometry) {
      geometry = new ol.geom.Polygon([]);
  }

  var firstCorner = coordinates[0];
  var thirdCorner = coordinates[1];

  var currentViewRotation = map.getView().getRotation();

  var secondCorner = [thirdCorner[0], firstCorner[1]];
  var forthCorner = [firstCorner[0], thirdCorner[1]];

  if (currentViewRotation != 0) {
      var verticesToRotate = new ol.geom.MultiPoint([secondCorner, forthCorner]);
      var anchor = ol.extent.getCenter(verticesToRotate.getExtent());
      verticesToRotate.rotate(2 * currentViewRotation, anchor);
      secondCorner = verticesToRotate.getCoordinates()[0];
      forthCorner = verticesToRotate.getCoordinates()[1];
  }

  var newCoordinates = [firstCorner, secondCorner, thirdCorner, forthCorner, firstCorner];
  geometry.setCoordinates([newCoordinates]);
  return geometry;

}

var draw = new ol.interaction.Draw ({
  source: vector.getSource(),
  type: "Circle",
  sides: 4,
  title: 'New draw',
  geometryFunction: geometryFunction
})

map.addInteraction(draw)
```
You have to use `ol/interaction/Draw` not ol-ext one.

**Comment by NewToStuff** [comment]
Thanks - That is excellent to know that code works. I am still not able to get it to work my end --- Maybe because I am getting confused about using Javascript in an Angular environment.

I wonder whether its the integration with the EditBar which is tripping me up. Some of me thinks it is about the adding it in the interactions object - The fact that the title is not picked up seems to be telling me something. I will continue to look and report back if I can figure it out. Scratching my head at the moment though !

Thanks

Paul

**Comment by NewToStuff** [comment]
Hi,
Still struggling: I think my issue is the EditBar is not running the interactions geometry function. If I try to log to the console it shows that the Geometry function is not running.

I have tried to run it separate to the EditBar as I think your example indicated. Doing that I think I have discovered that  

`var currentViewRotation = this.map.getView().getRotation();`

should read the following to read the map in the function
`var currentViewRotation = this.map_.getView().getRotation();`

But if I just apply the interaction as per your example I then cannot rotate the map to see the rotation change from zero. 
Any ideas?

Thanks

**Comment by NewToStuff** [comment]
UPDATE: I can get it to work with your example - Seemed to be something about the order in which I was creating things giving me the problem. 
Unfortunately I cannot get it to run the geometryFunction from the edit toolbar so think that may be my problem.
