### ISSUE TITLE
PopupFeature problem 

### ISSUE THREAD

**Issue by shitathakin** [Viglino/ol-ext#519]
Hi! 
Amazing library!
I am trying to use the popup feature with code following this logic 

    var popup = new PopupFeature({
        popupClass: 'default anim',
        select: select, //is a basic ol/interaction
        canFix: true,
        template: {...}
map.addOverlay(popup);

However when i click a feature it does not respond (ie, change from display: none to blocl. 
I am wondering if maybe I need jquery or something.
Please help !!!  

(I have imported popup.css)

**Comment by Viglino** [comment]
`select` must be an ol/interaction/Select and must be added to the map.
Does the feature select (change style to selected)?

**Comment by shitathakin** [comment]
The select works as expected :/

**Comment by Viglino** [comment]
Have you inserted the ol-ext.css in your page?
Do you have an example online?

**Comment by shitathakin** [comment]
yep got the css

packages ive imported: 

 import PopupFeature from 'ol-ext/overlay/Popup';
import Select from 'ol/interaction/Select';
import { singleClick } from 'ol/events/condition';
//import 'ol-ext/overlay/Popup.anim.css';
//import 'ol-ext/overlay/Popup.css';
import 'ol-ext/dist/ol-ext.css';

select block: 

var select = new Select({
        hitTolerance: 1,
        multi: true,
        condition: singleClick
    });
    map.addInteraction(select);

then in a loop over a config file with info for the vector layers: 

for (var vl of config.dataLayers) {
        addVectorLayer(vl, config, map, legend); //just creates a new VectorLayer
        addInfoBox(map, vl, select); //as i want to create different overlays for different layers
    }

informationbox: 

 var prop = vl.popupInfo.property1;
    var popupext = new PopupFeature({
        popupClass: 'default anim',
        select: select,
       // visible: true,
        canFix: true,
        template: {
            title:

                function (f) {
                    ' (' + f.get('id') + ')';
                },
            attributes:
            {
               prop: { title: 'beast' },

            }
        }
    });
    map.addOverlay(popupext);

At the moment, the new overlay is read in the console and is in the viewport as display: none, but does not respond to a feature being clicked. 
I appreciate the help as this would be a great tool!

**Comment by Viglino** [comment]
Use `PopupFeature` not `Popup` class that doesn't link popup to feature selection...
```javascript
import PopupFeature from "ol-ext/overlay/PopupFeature";
```

**Comment by shitathakin** [comment]
so silly. that was it
thankyou !
