### ISSUE TITLE
Show length of current section whilst drawing polygons

### ISSUE THREAD

**Issue by NewToStuff** [Viglino/ol-ext#520]
Hi,
I am using the awesome editBar to DrawPolygons on the map. When drawing the polygon the area inside the polygon is displayed within the tooltip. Is it possible to add details about the length of the current line section as well as the area whilst drawing. I can see form the examples that the text of the tooltip can be modified using logic like that below but cannot see how this can be used to add the length.

```
        edit.getInteraction('DrawPolygon').on('drawstart', function(e){
          console.log('Draw shape',e);
          tooltip.setFeature(e.feature);
          tooltip.setInfo('Click to continue drawing shape...');
    
        });
```

Many thanks for any clues.

Paul

**Comment by Viglino** [comment]
You have to add the length by yourself in the tooltip:
```javascript
import getLength from 'ol/sphere'
 edit.getInteraction('DrawPolygon').on('drawstart', function(e){
     console.log('Draw shape',e);
     tooltip.setFeature(e.feature);
     const geom = e.feature.getGeometry();
     const length = tooltip.formatLength(getLength(geom, { projection: map.getView().getProjection() }));
     tooltip.setInfo(length+'<br/>Click to continue drawing shape...');
});
```

**Comment by NewToStuff** [comment]
Thanks @Viglino that is most helpful. I am in an Angular environment and I seemed to have to change map.getView().getProjection() to this.map.getView().getProjection(). 

When running the app I  get "ERROR TypeError: Cannot read property 'getView' of undefined" so I must need another way to access the map object? Any thoughts?


```
        edit.getInteraction('DrawPolygon').on('drawstart', function(e){
          console.log('Draw shape',e);
          tooltip.setFeature(e.feature);
          const geom = e.feature.getGeometry();
          const length = tooltip.formatLength(getLength(geom, { projection: this.map.getView().getProjection() }));
          tooltip.setInfo(length+'<br/>Click to continue drawing shape...');
        });
```

**Comment by NewToStuff** [comment]
For now I have manually put in the Projection and got the tooltip to change. However I seem to have two difficulties;

1) The length is reporting as 0. I think this is because it is the length at drawstart and not a "live" value
2) I think the getLength section will give the total length - Is there an easy way to get the length of the last section?

I am presuming I need to get the Projection from the MapService function from your ol-ext-angular example? Not 100% sure how to get it though as I still need the mapId.


Thanks in advance

**Comment by NewToStuff** [comment]
Hi,
I am not sure I have tackled this the right way but what I found could work is to modify the Tooltip.js to add the following. I was thinking that it could be an optional parameter (hence the if statement). The solution needs some error trapping but looks like it will produce the desired result. Any comments welcome. Thanks

```
      if (true) {
       
        var lastCoord = new ol_geom_Point([geom.flatCoordinates[geom.ends_[0]-5],geom.flatCoordinates[geom.ends_[0]-6]]);
        var liveCoord = new ol_geom_Point([geom.flatCoordinates[geom.ends_[0]-3],geom.flatCoordinates[geom.ends_[0]-4]]);
        
        var latestLine = new ol_geom_LineString([[liveCoord.flatCoordinates[0],liveCoord.flatCoordinates[1]],[lastCoord.flatCoordinates[0],lastCoord.flatCoordinates[1]]]);
        console.log(lastCoord,liveCoord,latestLine);
        var distance = this.formatLength(ol_sphere_getLength(latestLine, { projection: this.getMap().getView().getProjection() }))
        measure  = measure + '<br/> ' + distance
      }
```

**Comment by Viglino** [comment]
Here is an example to calculate your own tooltip measures on geometry modification:
https://codepen.io/viglino/pen/NWrqLdZ

**Comment by NewToStuff** [comment]
Hi @Viglino ,

This is an awesome example and much better than the way I tried to tackle the problem! 
I am struggling how to put this in my Angular App - Probably not thinking about it in the right way. The way I have it at the moment the edit.getInteraction code sits within an Angular Class built for my component. 

I have tried a few approaches for the calculateMeasure function without much look: I firstly tried putting it outside the Angular class but get an error about not being able to access the map object. My next approach was to put it in the class as follows;

`calculateMeasure = function(e) {................}
`
and then call it as follows from within the class. Following this approach I don't think the function gets executed (tested by inserting a console.log)

Thanks for any clues you may have..
 

```

edit.getInteraction('DrawPolygon').on('drawstart', function(e){
  tooltip.setFeature(e.feature);
  e.feature.getGeometry().on('change', this.calculateMeasure);
  tooltip.setInfo('Click to continue drawing shape...');
});
edit.getInteraction('DrawPolygon').on('drawend', function(e) {
  e.feature.getGeometry().un('change', calculateMeasure);
  tooltip.setFeature();
  tooltip.setInfo();
})
```

**Comment by NewToStuff** [comment]
Hi @Viglino ,

I got some joy in Angular by changing the code to the following; 
`
  let calculateMeasure = (e, map,tooltip ) => {.................................}
`
and then changing the edit.getInteraction to run the function as follows:
`
e.feature.getGeometry().on('change', calculateMeasure(e, e.target.map_, tooltip));
`

This seems to have got me a few steps forward but now I error with;

TypeError: geometry.getType is not a function

The console entry below shows that I have access to the objects now but it errors in the getLength function within sphere.js. 


```
CalculateMeasure DrawEvent {type: "drawstart", target: Draw, feature: Feature} Map {disposed: false, eventTarget_: undefined, pendingRemovals_: {…}, dispatching_: {…}, listeners_: {…}, …} ol_Overlay_Tooltip {offsetBox: undefined, content: div.ol-popup-content, closeBox: undefined, onclose: undefined, onshow: undefined, …}
map-edit-openlayers.component.ts:878 Projection EPSG3857Projection {code_: "EPSG:3857", units_: "m", extent_: Array(4), worldExtent_: Array(4), axisOrientation_: "enu", …}
core.js:4002 ERROR TypeError: geometry.getType is not a function
    at getLength (sphere.js:74)
    at calculateMeasure (map-edit-openlayers.component.ts:880)
    at Draw.<anonymous> (map-edit-openlayers.component.ts:614)
    at Draw.push.../../node_modules/ol/events/Target.js.Target.dispatchEvent (Target.js:114)
    at Draw.push.../../node_modules/ol/interaction/Draw.js.Draw.startDrawing_ (Draw.js:707)
    at Draw.push.../../node_modules/ol/interaction/Draw.js.Draw.handleUpEvent (Draw.js:568)
    at Draw.push.../../node_modules/ol/interaction/Pointer.js.PointerInteraction.handleEvent (Pointer.js:144)
    at Draw.push.../../node_modules/ol/interaction/Draw.js.Draw.handleEvent (Draw.js:524)
    at Map.push.../../node_modules/ol/PluggableMap.js.PluggableMap.handleMapBrowserEvent (PluggableMap.js:860)
    at MapBrowserEventHandler.push.../../node_modules/ol/events/Target.js.Target.dispatchEvent (Target.js:114)
```


I have also tried going back to the ol-ext-angular-master example and tried to add the EditBar there to show you but I ran into an error with finding Popup. I will ask in the other repository for this. 

Any help really appreciated.

Thanks,
Paul

**Comment by Viglino** [comment]
It seems that the geometry used in the getLength in thecalculateMeasure is not a geometry... but the feature
```javascript
e.feature.getGeometry().on('change', calculateMeasure(e, e.target.map_, tooltip));
```
You have to declare your own function to get the correct event...
```javascript
e.feature.getGeometry().on('change', (e) => { 
  calculateMeasure(e, e.target.map_, tooltip)
});
```

**Comment by NewToStuff** [comment]
Hi @Viglino ,

Thanks for your reply. I really appreciate you spending some of your time. I could not work out why your fix should work but tried it (or at least what I think your suggestion is) and I couldn't get it to work.

I did however manage to get a stackblitz working with the Angular example, removing the syncronisation between maps and then adding the EditBar. All worked good.

I then tried to add the CalculateMeasure functionality and I ran into runtime errors again. Hopefully this link makes it easy for you to see what is causing the problem.

https://stackblitz.com/edit/ol-ext-angular


Many thanks,

Paul

**Comment by Viglino** [comment]
The issue is the map is undefined line 118 in control.component.ts:
```javascript
    e.feature.getGeometry().on('change', (e) => {calculateMeasure(e, e.target.map_, tooltip)});
```
use instead: 
```javascript
    e.feature.getGeometry().on('change', (e) => {calculateMeasure(e, edit.getMap(), tooltip)});
```

**Comment by NewToStuff** [comment]
Hi,

Yes I can confirm that works perfectly now. I have updated the StackBlitz if anyone else wants to see a working example.

Paul
