### ISSUE TITLE
LayerSwitcher (stop propagation)

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#521]
ol-ext 3.1.14 and 3.1.15 
I get not planned effect with propagation event from top to bottom.
When moving mouse over LayerSwitcher (all area)
and under there are some features with event, them get fire by pointing mouse 
despite there is covered by upper overlay LayerSwitcher.
![ls_propagation](https://user-images.githubusercontent.com/8928341/95321643-a2402d00-089b-11eb-850e-c5a446fee6ad.jpg)

And question how to stop propagation from LayerSwitcher to element of map  witch event?

```
map.on("click", OpenPopup);
map.on("pointermove", ShowTooltip);
```

**Comment by Viglino** [comment]
The control should be set inside the `ol-overlaycontainer-stopevent` div of the map when added using map.addControl and the event should be stopped...
Do you have the same issue with other controls (zoom, attribution...)?

I suppose you can stop event propagation when click on the element:
```javascript
layersSwitcher.element.addEventListener('click', function(e) { e.stopPropagation(); })
```

**Comment by Bear4** [comment]
Yes indeed! I have -> Do you have the same issue with other controls (zoom, attribution...)?

Exelent, Your tips stoped propagation on my map. 
Huge thanks!
