### ISSUE TITLE
Size, color and image of "arrow"

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#524]
New version 3.1.16 is amazing. I've got some ideas of `ol.style.FlowLine` for improvement.

1. Option for size (width and height) of the arrow.
2. Option for color of the arrow for better visibility.
3. Option for image of the start and the end. I'm using `lineStrings.forEach` and `new ol.style.Style({ geometry: new ol.geom.Point(lineString.getCoordinateAt(0/1)) ...` right now but possibility of setting directly in ol.style.FlowLine would be better.

**Comment by Viglino** [comment]
Hello @vsevjednom-cz

1- You can already set the arrow size using `setArrowSize()` method using a number or an array [height,width]!
2- The color is the color of the line start/end but a color could be set for the arrows...
3- For arrow at start/end I also use the style geometry function to show a point at start and that can set any image...

@+

**Comment by vsevjednom-cz** [comment]
I'm using this:

`function styleFn(f) {
    return new ol.style.FlowLine({
...`

So when FlowLine is return in function how can I use setArrowSize?

**Comment by vsevjednom-cz** [comment]
Arrow colors:
```
function styleFn(f) {
...
        if(step == 0){
        	return "#fff";
        }
        else if(step == 1){
        	return "#000";
        }
        else{
	        var h = (seg[0][2]+seg[0][2])/2;
        	var dh = 255*(h-min)/(max-min);
        	return getColor(dh);
        }
...
}
```

🙃
And there is bug sometimes, I think. Look at this: https://jedu.vsevjednom.cz/activity/2249 - there's weird line at the end of the route.

**Comment by Viglino** [comment]
Are you using the last code on Github?
 I've done a patch in the last commit to enhance the style and add a arrowColor option.

**Comment by vsevjednom-cz** [comment]
You're right. Bug is fixed in Github's version 🙃. Thanks!
arrowColor works, thanks! Is possible to set different color of the start and of the end? Like in my post here?

**Comment by vsevjednom-cz** [comment]
You're right. Bug is fixed in Github's version 🙃. Thanks!
arrowColor works, thanks! Is possible to set different color for the start and for the end? Like in my post here?

**Comment by vsevjednom-cz** [comment]
You're right. Bug is fixed in Github's version 🙃. Thanks!
arrowColor works, thanks! Is possible to set different color for the start and for the end? Like in my post above?
