### ISSUE TITLE
SearchFeature || Search [question]

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#525]
I would like set target in SearchFeature
and couldn't figure out how to proper add geom to target option.
Trying like this: 
```
const search = new SearchFeature({
  source: vSourceSearch,
  property: "nazwa",
  target: "2568084.6, 7013519.5, 2586926.4, 7000315.1", // or "[2568084.6, 7013519.5, 2586926.4, 7000315.1]" or "[23.04, 53.17, 23.29, 53.06]" 
  minLength: 2,
  maxItems: 40,
  placeholder: "Pokaż obiekt...",
  label: "szukaj"
});
```
and without success.
My native projection is ESPG:3857

Thanks for valuable library!

**Comment by Viglino** [comment]
The target is a DOM Element to put control in... if you don't want it on the map.
See https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html#setTarget
```javascript
const search = new SearchFeature({
  source: vSourceSearch,
  property: "nazwa",
  target: document.getElementById('mydiv')
...
})
```

**Comment by Bear4** [comment]
Ok. it's misunderstanding on my part.
Thanks
