### ISSUE TITLE
The same measured places repeatedly are problem in Profil

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#526]
Look at my measured activity at velodrome in Brno this week: https://jedu.vsevjednom.cz/activity/2260

Vertical line jumps to another places in other Profiles when I fly with my mouse at profil (or profil2 or speedprofil). The "problem" is that showAt(e.coord) contains only lon+lat but not time of activity, I think.

**Comment by Viglino** [comment]
I've added a showAtTime method to place the cursor at a time on the profile.

**Comment by vsevjednom-cz** [comment]
Yes, it works amazingly! Thaaanks!
