### ISSUE TITLE
Search Nominatim icons missing.

### ISSUE THREAD

**Issue by gregordavid** [Viglino/ol-ext#528]
I reported this issue to them, but they redirected here. I tought it's their bug.
I'm quite new in the industry, so i don't know how is it wired. But thanks for your' work! 
"The icons have moved to https://nominatim.openstreetmap.org/ui/mapicons/. This is correctly reported by our API, e.g. see the icon field in https://nominatim.openstreetmap.org/search.php?q=london&format=json.

If there is an API response that returns an invalid link, please provide an example. If openlayers-ext uses hardcoded links to these icons, then you should indeed report this to them."

**Comment by Viglino** [comment]
Hello,

I don't understand the problem. Icons are showing right on this page: https://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html
and URI are red from the API at  https://nominatim.openstreetmap.org/ui/mapicons/

@+

**Comment by AleMScof** [comment]
Hi there,

following the op question, i got somehow matching a similar 404 icon url.

the object `ol.control.Search.drawList_` is firing the following URL:`https://nominatim.openstreetmap.org/images/mapicons/poi_peak.p.20.png`.
which instead should be `https://nominatim.openstreetmap.org/ui/mapicons/poi_peak.p.20.png`

Using ol-ext 3.1.16--

**Comment by Viglino** [comment]
The icon path comes from the Nominatim API. If there is an API response that returns an invalid link, please provide an example to [Nominatim](https://nominatim.org/)...
