### ISSUE TITLE
LayerSwitchImage

### ISSUE THREAD

**Issue by xdursoc** [Viglino/ol-ext#531]
Hi, I have  a question about the LayerSwitchImage (LSI). At the begin I have  a LayerGroup with 3 layers that are correctly visualized into the LSI; After that I add 1 more layer dinamically in this way:

layerSwitchGroup.values_.layers.array_.push(layerToBeAddedtoGroup);

The layer has benn added to group but not showed in LSI, it is not updated, why? In which way can I update the LSI control?

**Comment by Viglino** [comment]
Use the `getLayers` method to add new ones and don't use private properties.
`layerSwitchGroup.getLayers().push(newLayer)`
This will send message to let the switcher update.

**Comment by xdursoc** [comment]
Thanks a lot
