### ISSUE TITLE
showAtTime in animateFeature

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#532]
Hi,
I want to do `profil2.showAtTime(e.geom.getCoordinates());` while animateFeature is running. But I can't get original time from GPX. There is the same problem as here: https://github.com/Viglino/ol-ext/issues/526 when I use showAt.

Is possible to get real time from e variable?
`anim.on('animating', function(e) {`

**Comment by Viglino** [comment]
You can use `e.elapsed` to get the position on the line : 0: start, ..., .5:middle, ....,1: end.
Then you have to retrieve the point on the line at this fraction using `profil.showAt(e.elapsed*track.getLength)`.
NB `animateFeature` doesn't use the speed/time to display the position on the map
You should try to use your own function to move along the track...

**Comment by vsevjednom-cz** [comment]
Thank you! But what is the source of the "track" variable? I'm trying and trying but without success.

**Comment by Viglino** [comment]
The track is your feature on the map (the linestring)

**Comment by vsevjednom-cz** [comment]
Yes! Thank yoooou.

Here is the code:
`p = profil.showAt(e.elapsed*ol.sphere.getLength(lineString)); profil.popup(p[2]+" "+profil.info.altitudeUnits);`

🙃
