### ISSUE TITLE
FeatureAnimate doesn't work on OL 6+

### ISSUE THREAD

**Issue by Frank3030** [Viglino/ol-ext#533]
I recently updated to OL 6.4.3 and feature animation doesn't work because OL changed the 'postcompose' on layers to 'postrender'.

https://github.com/openlayers/openlayers/releases?after=v6.1.0

**Comment by Viglino** [comment]
You also have to update ol-ext. Last version use postrender...

**Comment by Frank3030** [comment]
Yes. Sorry for the lack of investigation.
I am using the latest,
    "ol": "^6.4.3",
    "ol-ext": "^3.1.2",
 and I see in FeatureAnimation.js you are looking at both postcompose and postrender.

Adding console output on my layer,
            this.layer.on('postrender', (e) => {
                console.debug('postrender', e);
            });
            this.layer.on('postcompose', (e) => {
                console.debug('postcompose', e);
            });
and I'm not seeing these.
I've been looking through the example code again and I don't see any difference that would cause the layer to not dispatch one of these events.

Adding these on the map object,
            this.mapData.olmap.on('postrender', (e) => {
                console.debug('map postrender', e);
            });
            this.mapData.olmap.on('postcompose', (e) => {
                console.debug('map postcompose', e);
            });
I do see these outputs

**Comment by Viglino** [comment]
The lib listen to both post compose and postrender to be compatible with both version of ol.
Using ol<6 the postcompose est fired and using ol>6 use the postrender.

**Comment by Frank3030** [comment]
Yes, I knew that.

The issue is mine. I use a world map and in my example the focus (map placement and zoom level) is over the US. This:
            const f = new Feature({geometry: new Point([0, 0])});
As in your example, places the feature over the ocean outside my map extent. The change to OL 6 now prevents 'postrender' events when the feature is outside the map extent.

Thanks for responding and sorry to waste your time.

**Comment by Viglino** [comment]
Yes, the feature must be in the displayed area or optimation prevent from drawing the layer when nothing on it...
