### ISSUE TITLE
Status Display

### ISSUE THREAD

**Issue by aimdev** [Viglino/ol-ext#534]
This feature is becoming quite useful, and therefore I request that the following modification be considered.
Size modification via css.
Colour modification by css.
Addition of data by additional methods on the class.
Ability to minimise/maximise

**Comment by Viglino** [comment]
The feature is a DOM element fully customisable via CSS: use `.ol-control.ol-status` to change size/color/position/...
The class can be extended to add your own data, or use the `status` method to display what you want...
You can use an [`ol/control/Toggle`](https://viglino.github.io/ol-ext/examples/bar/map.control.toggle.html) to show/hide the control (I've changed the example to reflect this: https://viglino.github.io/ol-ext/examples/control/map.control.status.html)

**Comment by aimdev** [comment]
Hi

The correct address fixed it !!  .ol-control.ol-status

Thanks
