### ISSUE TITLE
ol.interaction.DrawTouch - Snap not snapping

### ISSUE THREAD

**Issue by bojanbizjak** [Viglino/ol-ext#536]
When I use ol.interaction.Draw (ol 6.4.3) the snap works, but when I use ol.interaction.DrawTouch (ol-ext 3.1.16), the snap circle appears but does not stick to nodes or objects. Can I ask for a hint? In ol 5x there were no problems with this.

**Comment by Viglino** [comment]
The example https://viglino.github.io/ol-ext/examples/mobile/map.interaction.drawtouch.html seems to work and snap properly...
NB: check the order you add the interaction on your map as DrawTouch use the same mechanism to snap to the center of the screen and the snap interaction must be added after the DrawTouch to snap at last.

**Comment by bojanbizjak** [comment]
It works now. Great plugin. Thanks.
