### ISSUE TITLE
Show tooltip in combination with cluster

### ISSUE THREAD

**Issue by dbretschneider** [Viglino/ol-ext#537]
The animated cluster support works great with my map implementation. 
Question from my side:
I've several clusters with e.g. 4 or more features with further information and with equal coordinates. The information of the feature will displayed as a tooltip (OL Overlay) while hover over the feature.
The tooltip position of each feature is centered always in the middle of the cluster.

How can I centered the tooltip of the feature directly over the marker?

Actual behavouir:
![marker-hover-tooltip](https://user-images.githubusercontent.com/3016561/100599381-3eb50780-3300-11eb-9dd4-3a1d617e57dc.png)

**Comment by Viglino** [comment]
You have to show the popup on the selected feature position.
Using a SelectCluster interaction will make the features spread apart and you can select them at the position on the spiral...

**Comment by dbretschneider** [comment]
Sometimes the answer is quite simple :man_facepalming:
Thanks for your help.

Instead of using the feature geometry, I used the geometry/flat coordinates from the event.

```
- feature.getGeometry().getCoordinates();
+ e.element.values_.geometry.flatCoordinates;
```

![2020-11-30 15_57_30-Beteiligung NRW](https://user-images.githubusercontent.com/3016561/100625478-e17f7d00-3324-11eb-8e87-c830d2baf3b5.png)
