### ISSUE TITLE
ModifyFeature does not work with `GeometryCollection`

### ISSUE THREAD

**Issue by daboudii** [Viglino/ol-ext#538]
#### Describe the bug:

When using ModifyFeature intercation it is not possible to use a GeometryCollection

#### Possible fixes:

By removing the comment line 435 in [src/interaction/ModifyFeature.js](https://github.com/Viglino/ol-ext/blob/master/src/interaction/ModifyFeature.js#L441)
It comes from this commit: https://github.com/Viglino/ol-ext/commit/e2899d88303f030ccf390cc93f452f5cb2165477#

**Comment by Viglino** [comment]
👍 I don't know why the line is commented 😞

**Comment by daboudii** [comment]
Do you know when you will make the next release ?

**Comment by Viglino** [comment]
I'll try to publish a new release asap...

**Comment by Viglino** [comment]
v3.1.17 is out https://www.npmjs.com/package/ol-ext

**Comment by daboudii** [comment]
Thank you very much !
