### ISSUE TITLE
Enhancement of ol.interaction.Split

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#539]
My idea: show splitted part of GPX track in Profil after I split it.

Similar like this in Strava: https://www.sportigo.cz/wp-content/uploads/2020/05/strava-segment3.jpg

What do you think?

**Comment by Viglino** [comment]
You have to create a splitted LineString and use it in your profile using `setGeometry` method...
Something like this:
```javascript
var geom = feature.getGeometry().getCoordinates()[0];
geom = geom.slice(200,500);
profil2.setGeometry(new ol.geom.LineString(geom));
```

**Comment by vsevjednom-cz** [comment]
Thanks! But I'm trying your code without success. Profil disappears when I run `profil2.setGeometry(new ol.geom.LineString(geom));` 🤪.

**Comment by Viglino** [comment]
Hello, I've pushed a new version to let you select part of the track on the profil (just drag and drop the start/end on the chart).
See online: https://viglino.github.io/ol-ext/examples/control/map.control.profil.html

You can listen to `dragstart`, `dragend`, `dragging` events to handle dragging. 
Use `getSelection(start,end)` method to get the selected coordinates...

**Comment by vsevjednom-cz** [comment]
Wow 🙃.
I thought of it this way: someone use `interactions.split.on("aftersplit"...` - and Profil shows the part of selected tracked-line. But your idea is great too! Unfortunately, it does not work if `source.on ("addfeature", function (e)...` is used for select of part of the route. When I commented it, it works - I found it after a few hours of trying.

**Comment by vsevjednom-cz** [comment]
Can I set a color of selected part of track? It's using color of last layer but sometimes it's unusable when layer is visible before select part of track.

**Comment by Viglino** [comment]
You can use the `selectStyle` option of the Profil control to change the part of the profile that is selected.

**Comment by vsevjednom-cz** [comment]
It works in Profil, thanks! But how can i set the color of selected part in the map?

**Comment by Viglino** [comment]
To change feature style on the map you have to [set a style function on your layer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#setStyle) or use [setStyle](https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html#setStyle) method on the feature...

**Comment by vsevjednom-cz** [comment]
Can you show me some example? I can use setStyle but this function set a color for the full layer but I need only color for the selected part. I think I'm only bad thinking about it. I will solve all when I see an example, I hope.

**Comment by vsevjednom-cz** [comment]
I finded where's the problem.

I'm using this code for split:
`source.on("addfeature", function(e) {
  var f = e.feature;
  if (f.getGeometry().getType()==="MultiLineString") {
    var geom = f.getGeometry().getCoordinates();
    var coords = geom.pop();
    var features = [];
    **f.setGeometry(new ol.geom.LineString(coords));**
    geom.forEach(function(c) {
      var fi = f.clone();
      fi.setGeometry(new ol.geom.LineString(coords));
      features.push(fi);
    });
    vectorStartEnd.getSource().addFeatures(features);
  }`

I see selected part in the map without this code - but split not works 🙃.

**Comment by vsevjednom-cz** [comment]
Why closed? :-1: 

My problem is maybe simple for solve, I hope. Please, look at this webpage: https://jedu.vsevjednom.cz/activity/2350?seg=1

I can see selected part of profil at the map - that's ok. But I can't see splitted part when I use split with my mouse.

**Comment by Viglino** [comment]
The split works indeed, just look at features in the console: `source.getFeatures()` returns a new feature at each split...
You have to display the features with a new style to display.

**Comment by vsevjednom-cz** [comment]
I understand. But how?

```
split: new ol.interaction.Split (
				{	sources: source,
```

There's only source. But I must create new layer, or..?

**Comment by Viglino** [comment]
You have to get the features after split and choose what to do with them:
```javascript
interactions.split.on('aftersplit', function (e) {
  var features = e.features;
  // Do something
  features[0].setStyle(redStyle)
  features[1].setStyle(blueStyle)
})
```

**Comment by vsevjednom-cz** [comment]
Yes! It works! 🙃
Is also possible to show only splitted part in some color?

I'm trying something like this:
```
    features[0].setStyle(defaultStyle["splitbefore"]);
    features[1].setStyle(defaultStyle["splitafter"]);
    features[2].setStyle(defaultStyle["splittedpart"]);
```
... but `features[2]` doesn't exist.
