### ISSUE TITLE
Speedprofil shows lower time

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#541]
`Speedprofil` shows about 1 minute lower time of activity than `Profil` when I fly with my mouse over the `Profil`/`Speedprofil`. It's bug maybe.

It looks like a problem with `ti` variable here: `this.element.querySelector(".track-info .time").textContent = ti;`

🙃

**Comment by Viglino** [comment]
How do you calculate your speed profile ?

**Comment by vsevjednom-cz** [comment]
Look here for example: https://jedu.vsevjednom.cz/activity/2331

`time` and `dist` are lower at Speedprofil when you fly with mouse over the map or over the Profil or over the Speedprofil.

**Comment by Viglino** [comment]
Looking at your code: 
- you set a profil using a geometry with 527 points (coords) line 1290
- but you set a speedprofil with a geometry with only 525 points (coords) line 1323
It seems the geometry of profil and speedprofil is not the same...
You have to have the same points in the profil and speedprofil to have the same correspondence between points / measure.
Only the Z (the 3th coordinate using XYZM) should differ... X, Y and M (time) should be the same for each points...

Using something like that seems to work for me:
```javascript
var c0 = coords[0];
c0[2] = 0
coords2 = [ c0 ];
for (var i=1, c; c = coords[i]; i++) {
  coords2.push(c);
  var d = ol.sphere.getDistance(ol.proj.toLonLat(c0), ol.proj.toLonLat(c)); 
  var dt = (c[3]-c0[3]); 
  if (dt) c[2] = Math.round(d/dt*3600)/1000;
  else c[2] = 0;
}
```

**Comment by vsevjednom-cz** [comment]
Yes! That's it! Thaaanks.

🙃
