### ISSUE TITLE
Trigger selection of cluster breaks setting empty style

### ISSUE THREAD

**Issue by dbretschneider** [Viglino/ol-ext#543]
If I click on a cluster, the map is zooming to cluster extent. Getting extent with:
```javascript
extent = selectCluster.getClusterExtent(feature)
```
If the extent can't passed, I use the feature geometry extent:
```javascript
extent = feature.getGeometry().getExtent()
```

Zooming to the cluster works fine with the extent above - but I have to do a further click to spread out the cluster. While the cluster is spread out, I set an empty style (```feature.setStyle(new Style({}));``` - cluster should be invisible if cluster is spread out).

To avoid a further click I trigger a cluster selection:

```
selectCluster.selectCluster({
    selected: [feature]
});
```

But in this case the cluster is still visible. The left picture shows the actual behavoir and the right the expected one, after trigger a selection.

![2020-12-16 08_17_58-Window](https://user-images.githubusercontent.com/3016561/102320450-97310980-3f7c-11eb-8cd8-9453f1d30536.png)

```javascript
    selectCluster.on('select', (e) => {
        const features = e.selected;

        if (Array.isArray(features) && features.length > 0) {
            const feature = features[0];

            if (feature.get('features').length > 1) {
                let extent = selectCluster.getClusterExtent(feature);
                if (!extent) {
                    extent = feature.getGeometry().getExtent();

                    setTimeout(() => {
                        // Trigger cluster selection after zoom to extent (timeout = 100ms)
                        selectCluster.selectCluster({
                            selected: [feature]
                        });
                    }, 100);
                }

                map.getView().fit(extent, {
                    size: map.getSize(),
                    padding: [
                        4 * MARKER_SIZE,
                        2 * MARKER_SIZE,
                        2 * MARKER_SIZE,
                        2 * MARKER_SIZE
                    ]
                });

                // Blende Cluster-Darstellung aus
                feature.setStyle(new Style({}));
            }
        }
    });
```

**Comment by Viglino** [comment]
Do you have a working example? on codepen or so?

**Comment by dbretschneider** [comment]
I've create a JSFiddle: https://jsfiddle.net/bretsch/jc7orkxa/1/

I recognize a strange behavoir. After zoom to and spreading out the cluster, deselect and select the cluster again, the cluster style is not visible (as I expected).

**Comment by Viglino** [comment]
When zooming, the clusters change and new clusters appear. You can't just change the style of the old cluster that is no more in the layer. You have to find the new cluster (if one) to select it (and hide it).

**Comment by dbretschneider** [comment]
Thanks for the hint and the explantation how clusters works 😜 
Working example: https://jsfiddle.net/bretsch/jc7orkxa/6/
