### ISSUE TITLE
CopyPaste example not working with ctrl characters

### ISSUE THREAD

**Issue by enorton** [Viglino/ol-ext#545]
In this example, [CopyPaste](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.copypaste.html) the buttons function as expected, but if you try and use ctrl-x, ctrl-c and ctrl-v it does not. I've tried on Firefox and Chrome and same behavior.

Inside CopyPaste.js the handleEvent doesn't seem to get hit with keyboard events.
```
// Create intreaction
    ol.interaction.Interaction.call(this, {
      handleEvent: function(e) {
        if (e.type==='keydown' && !/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) {
            debugger;
          switch (condition(e)) {
            case 'copy': {
              this.copy({ silent: false });
              break;
            }
            case 'cut': {
              this.copy({ cut: true, silent: false });
              break;
            }
            case 'paste': {
              this.paste({ silent: false });
              break;
            }
            default: break;
          }
        }
        return true;
      }.bind(this)
    });
```

**Comment by Viglino** [comment]
Keyboard event are handled in the condition function:
```javascript
    condition = function (e) {
      if (e.originalEvent.ctrlKey) {
        if (/^c$/i.test(e.originalEvent.key)) return 'copy';
        if (/^x$/i.test(e.originalEvent.key)) return 'cut';
        if (/^v$/i.test(e.originalEvent.key)) return 'paste';
      }
      return false;
    }
```
It seems that keyboard events are not trigger any more in olv6. 
Even [ol/Map pan](https://openlayers.org/en/latest/apidoc/module-ol_interaction_KeyboardPan-KeyboardPan.html) doesn't run anymore...
It's working with ol v5.3.0

**Comment by Viglino** [comment]
I've change the way to handle keyboard events to make it work on CopyPaste interaction...

**Comment by enorton** [comment]
You are a fine gentleman and a scholar. Works as expected now. Thanks for fixing!

One thing I did notice in your commit was changing the ol version in the example html for copy paste to 5.3.0. I wondered if that was unintentional.

**Comment by Viglino** [comment]
It was just for testing. I've put it back to latest ol version...
