### ISSUE TITLE
Legend.getStyleImage() rendering incorrect when device pixel ratio != 1

### ISSUE THREAD

**Issue by richard-thomas** [Viglino/ol-ext#547]
When rendering ol/layer/Vector styles, Legend.getStyleImage() produces canvas images that are different to those rendered in the map itself if device pixel ratio is not 1.0. This is most easily demonstrated using the example page, viewed on a device with Device Pixel Ratio > 1.0, or in Chrome/Edge/Firefox with Developer Tools set to device "iPhone X" (ratio = 3.0):
    https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html
If you select the cyan triangle in the bottom left (with a dashed border), then click "Add to Legend", the dashed border is rendered with a very different mark-space ratio.

The issue is much worse on some of the other styles I am using (e.g. a dotted border appearing as a solid border in the Legend). This could be a bug with the underlying OpenLayers drawGeometry() method, though nothing relating to that is currently registered as an OpenLayers issue.

**Comment by Viglino** [comment]
It seems the pixel ratio is not taken into account on dash...

**Comment by Viglino** [comment]
It seems the issue is on ol [setStyle](https://openlayers.org/en/latest/apidoc/module-ol_render_canvas_Immediate-CanvasImmediateRenderer.html#setStyle) or [drawGeometry](https://openlayers.org/en/latest/apidoc/module-ol_render_canvas_Immediate-CanvasImmediateRenderer.html#drawGeometry) function...

**Comment by richard-thomas** [comment]
I've been playing around with it and I agree there is a problem with OpenLayers - specifically I think with the Canvas Immediate API drawing for pixel ratio > 1.0, which I can't figure out. However, I noticed that there is a (no doubt related) problem with ol-ext Legend that causes multi-rule linestring types to be rendered with different line widths for ratio>1. (I have a line with a dashed line on top to give alternating colours). Removing the ctx.save() at line 280 of Legend.js (and its corresponding ctx.restore()) fixes that.

It seems that moving the clipping out of the rule "for" loop might be a good idea, so for example placing it before the for loop at line 268:
```
  if (typeGeom == 'LineString') {
    ctx.rect(this.get('margin') * ratio, 0, size[0] *  ratio, canvas.height);
    ctx.clip();
  }
```
Have you considered clipping the height of the rendered symbol as well? I have a line styling that has its width dynamically adjusted to be a fixed number of metres (not pixels) - so when I zoom in it overwrites adjacent symbols in the legend.

**Comment by Viglino** [comment]
The last commit should fix the issue.
