### ISSUE TITLE
Title (tooltip) missing for GeoBookmark button

### ISSUE THREAD

**Issue by labronico0586** [Viglino/ol-ext#549]
It is not possible to set a title (tooltip) for the button used to activate the geo bookmark button, as in other controls, using `options.title` in constructor.

![image](https://user-images.githubusercontent.com/62011737/104355434-f564f400-550a-11eb-9acc-e908b4f9e87c.png)

A possible workaround is to set title accessing the internal button, but this ties the user code to the internal implementation and should be avoided.

**Comment by Viglino** [comment]
👍 I've added the option.
