### ISSUE TITLE
Title (tooltip) for Search button use different option

### ISSUE THREAD

**Issue by labronico0586** [Viglino/ol-ext#550]
To set the title for the Sercah button, it needs to set `options.label` in options constructor parameter.
Suggested change are:

- change it in `options.title` as for all other controls (for example GeoBoomark, Toggle, and ol ones)
- use a capitalized default (ie 'Search' instead of 'search')

![image](https://user-images.githubusercontent.com/62011737/104356578-6658db80-550c-11eb-85eb-2e280aad8743.png)

**Comment by Viglino** [comment]
You'r right its more in the line with others buttons

**Comment by birbilis** [comment]
just mentioning for reference:

openLayers default buttons seems to use "tipLabel" for naming tooltips and "xxTipLabel"
e.g.
FullScreen/Attribution/ZoomToExtent standard buttons have tipLabel option
the Zoom control has two buttons so it uses zoomInTipLabel and zoomOutTipLabel instead

which can cause some confusion to people expecting to have such (hopefully they'll find this thread when searching)
