### ISSUE TITLE
Incompatibility between ol-ext@3.1.17 and ol@6.5.0

### ISSUE THREAD

**Issue by cazacugmihai** [Viglino/ol-ext#551]
Using `ol-ext@3.1.17` and `ol@6.5.0`, the map cannot be moved on [Modify interaction for touch device](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.modifytouch.html) page. There are no errors using `ol@6.4.3`.

Env:
```
OS: Ubuntu
Browsers: 
- Firefox 84.0.2
- Chrome 87.0.4280.141 
- Chromium 87.0.4280.141
- Opera 73.0.3856.329
- Brave 1.18.78
```
Thank you!

**Comment by Viglino** [comment]
It seems something has changed...
Fixed in the last commit

**Comment by cazacugmihai** [comment]
Thank you!
