### ISSUE TITLE
LayerSwitcher control - how to listen for layer visibility changes?

### ISSUE THREAD

**Issue by mperdikeas** [Viglino/ol-ext#555]
I am using the [LayerSwitcher control](https://viglino.github.io/ol-ext/examples/control/map.switcher.html). Is there an API to listen for changes to a layer's visibility that are explicitly, manually triggered by the user through that control? Listening to layer visibility changes directly on the OL layer or the OL map object won't work in my case as I only need certain actions to fire ONLY when the layer visibility change happened because the user interacted with the LayerSwitcher control. I looked into both the online example (posted above) and the source code for that component but am unable to figure how to accomplish this.

**Comment by Viglino** [comment]
There is no event fired when LayerSwitcher buttons are clicked.
You can use the `drawlist` event to attach you own listener on the label:
````javascript
switcher.on('drawlist', (e) => {
  var layer = e.layer;
  e.li.querySelector('label').addEventListener('click', () => {
    console.log(layer.get('title') +' visible: '+ layer.getVisible());
  });
});
 ```
