### ISSUE TITLE
Using with OSMNames

### ISSUE THREAD

**Issue by RadekHavelka** [Viglino/ol-ext#556]
Hi,
  just in case you are using docker from OSMNames https://github.com/klokantech/osmnames-sphinxsearch and you are wondering, why nothing shows up in search box. It says to be compatible with Nominatim format, but the JSON produced by OSM names is bit different. So if you want to use your own, or switch back to Nominatim, back and forth, you can easily fix that by adding

```
/**
 * Handle server response to pass the features array to the list
 * @param {any} response server response
 * @return {Array<any>} an array of feature
 */
ol.control.SearchNominatim.prototype.handleResponse = function (response) {
    var features = [];
    if (response.results) {
        for (var i = 0; i < response.results.length; i++) {
            features.push(response.results[i]);
        }
    }
    else
    {
        features = response;
    }
    return features;
};
```
to your ol-ext.js file. If you use original Nominatim, it returns the original response, if you use OSM Names, it gets the "results" and return them. Rest is mostly compatible and search box is workin.

**Comment by Viglino** [comment]
Last commit should do the trick!

**Comment by RadekHavelka** [comment]
cool!
