### ISSUE TITLE
SelectCluster - Circle issue

### ISSUE THREAD

**Issue by butilka123** [Viglino/ol-ext#557]
Hi there,
I have some issues with the SelectCluster. I only want circles instead of a spiral. To do that I am adding the following to the SelectCluster:

`circleMaxObject: 40,
      spiral: false,
` (https://i.imgur.com/kkAJzAg.png)

I have edited this in the demo: https://codepen.io/viglino/pen/KGdbjM

The results are this:
https://i.imgur.com/2d3FQ9t.png - Here only 10 features are being shown
https://i.imgur.com/U44LqXR.png - And if there are many features in 1 cluster the lines are way to big

Am I missing something? Thank you in advance!

**Comment by Viglino** [comment]
Use `circleMaxObjects` (with an s at the end) option : https://codepen.io/viglino/pen/KGdbjM

**Comment by butilka123** [comment]
Ah okay, ty! You should update this in the API (http://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.SelectCluster.html)

**Comment by butilka123** [comment]
https://i.imgur.com/9lA5u5I.png - Is there a way to reduce the line size and the space between the features? 
`circleMaxObject: 40` Does not decrease it.

**Comment by Viglino** [comment]
It's running for me on https://codepen.io/viglino/pen/KGdbjM
Line size depends on the pointRadius that determines the angle to prevent points to touch each others. 
You can decrease it but the symbols will overlaps.

**Comment by butilka123** [comment]
I mean the 40 features can fit in a much smaller circle. But i think in my case thats not the problem because the arrows melt into each other.

Anyways ty for your help and for your great libary :)

**Comment by Viglino** [comment]
Add a s at circleMaxObjects
```
circleMaxObjects: 40
               ^
```

**Comment by butilka123** [comment]
I have that. If you scroll in your example all the way out and click the cluster the effect is the same.

click the cluster with 1902 features
https://i.imgur.com/EbupJw5.png
https://i.imgur.com/mKRKOqv.png

**Comment by Viglino** [comment]
👍 the radius calculation didn't take into account the circleMaxObjets option 😢 
It should run now!

**Comment by butilka123** [comment]
I guess i have to wait for the next release since i am using Angular

**Comment by Viglino** [comment]
You can import directly the Github repo the for your test (not recommended for production)...
```
"dependency": "git+https://github.com/username/git-repository.git"
```
I'll try to publish asap.

**Comment by butilka123** [comment]
I havent quite figured out how to import the repo but it is not urgent, i can wait. Also take your time, ur doin a great job!

I have 2 other things (also not urgent):

### first one
`new SelectCluster({
      spiral: false,` 
 creates following Error in the Browser Console: `TypeError: Cannot read property 'getImage' of undefined
`
### second one
The Feature Style function
```
featureStyle (f) {
features = f.get('features');
```
returns if you click a **cluster**, following:
```
OBJ Feature
undefinded
OBJ Feature
undefined
... (and so on)
```

but if you click a **feature** from the cluster (after clicking the cluster) you get following:
```
OBJ Feature
undefinded
OBJ Feature
undefinded
undefinded
OBJ Feature
undefinded
OBJ Feature
...
```
here you get somehow 2x undefined which kinda destroys the pattern to give each single feature a custom style

**Comment by Viglino** [comment]
I think the style you define on your layer has an error (not defined or no image).
Try to remove style function and see which one is buggy.

**Comment by butilka123** [comment]
Only if i do `spiral: false` i get the getimage error. If it is on true (default) there is no error.

**Comment by butilka123** [comment]
```
featureStyle (f) {
features = f.get('features');
if (features) {...}
else {
// Line style
}
```
I managed to get rid of the get style error. Apprereantly you have to define the style where `// Line style` is. You cant do it in  if or smth else.

Now i only have the issue with the 2x undefined. In other words i cant define the line style for each single feature

**Comment by butilka123** [comment]
Question: Does `selectclusterlink` and `selectclusterfeature` have an id together that connects / relates them to each other?

**Comment by Viglino** [comment]
No links are just for drawing purposes...

**Comment by butilka123** [comment]
I want to give a feature a custom link style based of the features value. Since i only get undefined for a feature link its kinda hard without bugs

**Comment by butilka123** [comment]
The original issue is fixed, thank you.
