### ISSUE TITLE
Undocumented parameter used at SearchNominatim control page

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#558]
at:
https://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html
I see

// Set the search control
```
  var search = new ol.control.SearchNominatim (
   {	//target: $(".options").get(0),
     polygon: $("#polygon").prop("checked"),
     reverse: true,
     position: true	// Search, with priority to geo position
   });
   map.addControl (search);
```
but the position parameter doesn't seem to be documented at
https://github.com/Viglino/ol-ext/blob/master/src/control/SearchNominatim.js
neither at
https://github.com/Viglino/ol-ext/blob/master/src/control/Search.js
it extends from

no info at the API doc either
http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.SearchNominatim.html
http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Search.html

**Comment by Viglino** [comment]
There is no position parameter with Nominatim its a copy/paste remainder from the [SeachPhoton control page](https://github.com/Viglino/ol-ext/blob/master/src/control/SearchPhoton.js).
Nomiatim uses [`viewbox` and `bounded` options](https://nominatim.org/release-docs/latest/api/Search/#result-limitation)

**Comment by birbilis** [comment]
Thanks for clarifying that, will remove it from my code (it's live at http://minedu.gov.gr/covid19-schools.html, see Map button)

I had tried bounded=true and viewbox=defaultExtent where
defaultExtent = [1980051.958309263, 3958088.1085884026, 3251964.1089745956, 5342515.564889515];
for a bounding box containing Greece (for my use-case) which is a variable I already had for use with the "Home" icon button on that map (set default extent button) and it didn't work (wasn't fethcing any results). Should I pass a string instead there with the 4 values? I expected it would take an array so that I could reuse the extent array

**Comment by Viglino** [comment]
It seems the viewbox have to be as:
> viewbox=x1,y1,x2,y2
> The preferred area to find search results. Any two corner points of the box are accepted as long as they span a real box. x is longitude, y is latitude.
```javascript
  var search = new ol.control.SearchNominatim ({
      bounded: true, // or maybe 1
      viewbox: [20.15, 34.92, 26.6042, 41.827] // or maybe '20.15,34.92,26.6042,41.827'
   });
   map.addControl (search);
```
bbox from https://gist.github.com/graydon/11198540

**Comment by birbilis** [comment]
thanks for the tip about the bboxes, it seems the extent is "projected bounds", judging from the terminology at
https://spatialreference.org/ref/epsg/gda94-australian-albers/
and
https://gis.stackexchange.com/questions/274670/finding-correct-extent-of-projection
where I see similar big numbers used

I just remembered I had found the extent numbers by printing it out to the browser console (they're probably tied to a specific projection too), I'll try with lat/lon instead for the bounding box
