### ISSUE TITLE
Add accept-language parameter for nominatim search

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#559]
see discussion at
https://help.openstreetmap.org/questions/38202/is-it-possible-to-specify-a-language-for-results-in-reverse-geocoding

tried to use
            url: "https://nominatim.openstreetmap.org/search?accept-language=el"
but it won't work probably since it doesn't expect parameters to be in that URL

btw, also some CustomParameters param (name/value pairs) would be handy to have to cover nominatim parameters that you haven't wrapped

**Comment by Viglino** [comment]
You can overwrite the requestData function to add your own parameters to the request:
```javascript
var search = new ol.control.SearchNominatim();
search.requestData = function(s) {
  var data = ol.control.SearchNominatim.prototype.requestData.call(this, s);
  data['accept-language'] = 'el';
  return data
}
```
