### ISSUE TITLE
what exactly is the `translateFeature` option in the `ol-ext/interaction/Transform` interaction?

### ISSUE THREAD

**Issue by mperdikeas** [Viglino/ol-ext#562]
Not sure if this is a bug or something not very clearly documented. I am puzzled by the `translateFeature` option.
By experimenting I have discovered that I must set it to `false` to ensure that the center-handle for moving the feature around is displayed. If, instead, I set it to `true`, then the center handle is not displayed at all but I can still move the feature around if I manage to click at the center (with no visual cues). E.g. the following code:

    this.transform = new Transform ({
      features: // some features
      enableRotatedTransform: false,
      addCondition: never,
      hitTolerance: 2,
      translateFeature: false,
      scale: true,
      rotate: true,
      keepAspectRatio: shiftKeyOnly,
      translate: true,
      stretch: true
    });

displays a square "handle" at the center of the feature. If I set the `translateFeature` to `true`, no square "handle" is displayed. I feel this is confusing.

**Comment by Viglino** [comment]
Its a but confusing but:
- the `translate` options (without feature) lets you translate or not the feature (as `stretch`, `rotate `or `scale`).
- `translateFeature` option lets you translate by pointing on the feature and thus has no the handle...
