### ISSUE TITLE
TypeError: AnimatedCluster_1.AnimatedCluster is not a constructor in Angular

### ISSUE THREAD

**Issue by sivakanesh** [Viglino/ol-ext#563]
Hello
I'm using npm versions of "ol": "^6.3.1", and "ol-ext": "^3.1.17".
Using this with Angular 7 and trying to replicate one of the existing [animatedcluster]( https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html) in Angular.  

Keep on getting `ERROR TypeError: AnimatedCluster_1.AnimatedCluster is not a constructor`
I'm importing the ol-ext classes as `import { AnimatedCluster } from "ol-ext/layer/AnimatedCluster";`

[Here is the codesandbox I'm working on](https://codesandbox.io/s/olangular-undoredo-interaction-forked-6qoc9?file=/src/app/app.component.ts:404-467).  
Any ideas what I might be doing wrong?  Thank you.

**Comment by Viglino** [comment]
```import AnimatedCluster from "ol-ext/layer/AnimatedCluster";```
Without  { } it's the default export...
