### ISSUE TITLE
SearchNominatim and GeoJSON

### ISSUE THREAD

**Issue by hk298** [Viglino/ol-ext#566]
A question: The sample code at
https://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html
contains a statement that checks "if we get a geojson to describe the search". In what cases does Nominatim return such an object? I haven't seen that in my searches yet.

**Comment by Viglino** [comment]
This is when you make a request with a polygon argument (polygon_geojson), when you check the checkbox in the example.
Then Nominatim will return a polygon as GeoJSON you have to format to set in the result. 
You'll get it when you search for a large place (town, state, river...)

**Comment by hk298** [comment]
Thank you for the explanation.
