### ISSUE TITLE
Perspective map does work fine on latest Firefox on Win10

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#568]
https://viglino.github.io/ol-ext/examples/map/map.perspective.html
says "not working on Firefox", but on latest FF on Win10 seems to work ok

**Comment by Viglino** [comment]
Perspective map is experimental and doesn't work on FF 😢

**Comment by birbilis** [comment]
have you checked with most recent FF? Works fine on my machine

**Comment by Viglino** [comment]
On my FF 86.0, ol pointer is not under the mouse pointer...
![image](https://user-images.githubusercontent.com/7868217/109381011-05c50880-78d8-11eb-8306-195d6fb907ff.png)

**Comment by birbilis** [comment]
Indeed, that movement seems to become more erratic the more one increases the perspective
Could be something related to order of transformations (some FF bug? ) or related to floating-point (rounding or truncation) maybe, just guessing

**Comment by Viglino** [comment]
Chrome or Edge have a reverse transform to get event on a div with a css tranform.
FF has not such mechanism and I can't get the cursor in the screen coordinate system to place it on the map...
The more the map is tilde the more coordinates diverge...
