### ISSUE TITLE
Not clear how one can change the radius of the GeolocationDraw

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#570]
At both 
https://viglino.github.io/ol-ext/examples/mobile/map.control.geolocationbt.html
and
https://viglino.github.io/ol-ext/examples/mobile/map.interaction.geolocationdraw.html
the GeolocationDraw seems to draw a circular radius where it isn't obvious how it can be changed (in color and width)

Copy-pasted the code from the 1st url to add an geolocation button but it seems to flash red the whole map and not show the you're here popup, just the dot for the location found. Don't mind the popup, but the red circle would be nice to know how to configure (must be showing up huge on my map, not sure why)

**Comment by Viglino** [comment]
The radius depends on the location precision and you can change it...

**Comment by birbilis** [comment]
Oh, sorry, just realised what you meant with "Accuracy" when I noticed the accuracy bar at the 2nd link above. I'm using the location provided by Windows on a desktop machine without a GPS device. Probably on a mobile phone it works differently
