### ISSUE TITLE
tipLabel missing from Search control (and descendents) and GeoLocationButton

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#571]
Controls that have a single visible button should have a "tipLabel" option to set their tooltip. Those that are conprised of more buttons should use button-specific options names for the respective tooltips (see zoom control mentioned below)

e.g.
- FullScreen/Attribution/ZoomToExtent standard buttons have tipLabel option
- the Zoom control has two buttons so it uses zoomInTipLabel and zoomOutTipLabel instead

Currently:
Search button seems to show "Search"
GeoLocationButton shows no tooltip

**Comment by Viglino** [comment]
You can use `title` (or `label`) to change the search tooltip.
I've added title to the GeoLocationButton

**Comment by birbilis** [comment]
thanks, I guess GeoLocationButton will only support "title" whereas Search seems to support both "label" and "title" to set the title

note that in SetExtent default button of OpenLayers one can use "Label" to change the image icon of the button (providing a span via HTML markup), whereas they generally use "tipLabel" for the tooltip (with exception of the zoom one that has two subbuttons and thus two such properties with respective name variants of "tipLabel")

**Comment by Viglino** [comment]
Use `title` as it is the HTML global attribute name to set extra information shown as a tooltip: https://www.w3schools.com/tags/att_title.asp
See #550

**Comment by birbilis** [comment]
just for reference to others in the future, how to set tooltip for reverse search inner button of search control
https://github.com/Viglino/ol-ext/issues/610
