### ISSUE TITLE
SearchNominatim control shows "undefined" search result (and blank map) when clicking the sea

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#572]
Latest changes probably introduced a bug (don't think it was occuring before) with SearchNominatim when clicking in the seas: it says undefined on the search box and map goes blank

**Comment by Viglino** [comment]
There was a bug when there is no response on reverse geocoding (when click in a no man's land).
Yet it will do nothing instead of zooming to a null position 😄
