### ISSUE TITLE
GeolocationButton issues

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#573]
Regarding GeoLocationButton
1) it doesn't seem to do anything when map is inside an IFRAME, no errors thrown in the browser console either. 
2) when browser permission dialog is shown and user presses Allow it does nothing till you click it again. In Firefox the browser has a checkbox remember this decision on the permission dialog. Obviously if it's not ticked then the user will never achieve to use the button since everytime they click it it will be like the first time a permission is asked where the control doesn't seem to do something (timesout while waiting for the user to give permission maybe? can't it listen for some event that the permission was granted? )

**Comment by Viglino** [comment]
Permission depends on the brother and is done to protect your data.
There is nothing to do to skip the brother alert...
You can check `window.isSecureContext` before adding the control...

Inside an iFrame, you have to use the [allow parameter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) to get it work.
```html
<iframe src="https://MyChildSite.com" allow="geolocation 'self' https://MyParentSite.com"></iframe>
```
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/geolocation
> By default, the Geolocation API can be used within top-level documents and their same-origin child frames. This directive allows or prevents cross-origin frames from accessing geolocation. This includes same-origin frames.

**Comment by birbilis** [comment]
Thanks for the info, it works fine by just specifying allow="geolocation" in my case (since user can't navigate away from the map in that iframe by accident). 

1) Btw, I think the allow in your example need https://MyChildSite.com (not https://MyParentSite.com) from what I understand, meaning that the hosting parent page says that only pages in that iframe from https://MyChildSite.com should be allowed to use geolocation - if user goes elsewhere then don't allow.

2) It is also strange that windows.isSecureContext doesn't take any parameters to specify the aspect under which it is secure. Aka I'd expect window.isSecureContext("geolocation"), aka take a param (or more)

3) Regarding doing the action after the user gives the permission instead of having to repeat it after the permission is given (which would fail always if user didn't tick the "remember this choice" in Firefox), probably there's a way for it. See discussion here: https://stackoverflow.com/questions/65222980/attach-event-listener-on-geolocation-permission-granted
