### ISSUE TITLE
How to set the style of 3D building ？

### ISSUE THREAD

**Issue by q77322708** [Viglino/ol-ext#574]
Take this example：
http://viglino.github.io/ol-ext/examples/map/map.layer.3D.html
![image](https://user-images.githubusercontent.com/47692690/109268866-a4a12480-7846-11eb-89f4-e50c6372cd26.png)

How to set the style of 3D building ？
Line and surface style setting of  3D building .

**Comment by Viglino** [comment]
When creating your vector3D there is a style param, 
see [doc](http://viglino.github.io/ol-ext/doc/doc-pages/ol.render3D.html)

**Comment by Viglino** [comment]
The is also a `setStyle` method...

**Comment by q77322708** [comment]
Line style is OK.
Top surface style  is OK.

question:
1、How to set the styles of 4 side surfaces ?
![微信图片_20210301112726](https://user-images.githubusercontent.com/47692690/109448727-99860880-7a81-11eb-8e27-9ce15382d7f1.png)

2、The current 3D building data is  GeoJSON format .
Does 3D building data support MVT format ?

**Comment by q77322708** [comment]
var r3D = new ol.render3D({ 
    height:0, 
    maxResolution:0.6, 
    defaultHeight:3.5 ,  
    // ghost : true,
      style: new ol.style.Style({

      fill: new ol.style.Fill({ 
        color: '#ff2d237d' 
      }) ,

      stroke:new ol.style.Stroke({ 
        color: '#79fe4d'  ,
        width: 2
      }) ,

      }),

     });

**Comment by Viglino** [comment]
The floor style is the one of the layer...

**Comment by Viglino** [comment]
render3D only apply to vector layer for MVT, you have to look at MapBox or MapLibre solution, see ol integration https://openlayers.org/en/latest/examples/mapbox-layer.html (experimental)

**Comment by q77322708** [comment]
OK，OK~~
Thank you very much.

**Comment by remotesc2** [comment]
@q77322708 请问，你提到的这个问题解决了吗？
