### ISSUE TITLE
DrawHole interaction fails if style is supplied on the Vector layer

### ISSUE THREAD

**Issue by mperdikeas** [Viglino/ol-ext#576]
This is something very strange I stumbled upon almost by accident.

Use the exact same code as in the [official DrawHole example](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.drawhole.html).

Then perform the following simple change at the point where the Vector layer is defined. Instead of:

     // New vector layer
     var vector = new ol.layer.Vector(
       {	name: 'Vecteur',
	source: new ol.source.Vector()
     })

write:

     // New vector layer
     var vector = new ol.layer.Vector(
       {	name: 'Vecteur',
	source: new ol.source.Vector(),
        style:  new ol.style.Style({
          stroke: new ol.style.Stroke({width: 3})
        })
     });

I.e. simply add a `Style` with a `stroke` property only. This causes the `DrawHole` interaction to fail. What's more, by attaching a listener for the `drawstart` event you'll see that the event fires on every click as the hole is drawn:

    drawhole.on('drawstart', () => {console.log('drawstart');});

Curiously, if the Style also includes a `fill` property like below:

     // New vector layer
     var vector = new ol.layer.Vector(
       {	name: 'Vecteur',
	source: new ol.source.Vector(),
        style:  new ol.style.Style({
          fill: new ol.style.Fill({color: 'rgb(255, 0, 0)'}),
          stroke: new ol.style.Stroke({
            width: 3
          })
        })
     });

... then the `DrawHole` interaction works again as intended.

What's more alarming is that when the `DrawHole` interaction fails, no error message gets printed on the console. What is the cause of this weird behavior and what can a developer do to prevent problems of the same type in this or other interactions? I think an error message had to be printed on the console at least!

**Comment by Viglino** [comment]
The interaction test if the point is inside the polygon. If you remove the fill style the polygon is no more selectable on click on its surface and it fails... and prevent from adding a new point as it believes the pointer is outside the polygon...

You have to add a fill to your style even if the fill is quite transparent:
```javascript
new ol.style.Style({
    fill: new ol.style.Fill({ color: [255,255,255,.001] }),
    stroke: new ol.style.Stroke({
    width: 3
  })
})
```
NB: if you fill with a fully transparent color, it will fail to... but you can use a very small opacity to get it work and make the fill invisible....
