### ISSUE TITLE
(question) how to constraint the DrawHole interaction on one feature only?

### ISSUE THREAD

**Issue by mperdikeas** [Viglino/ol-ext#577]
I see that the `DrawHole` interaction provides an option to constraint its operation to a single layer. But is it possible to accomplish the same thing for a single feature only (or a set of features) that don't reside on a layer of their own ? My use case is the following: I would like the user to use a `Select` interaction to pick up a feature to edit, and then allow `DrawHole` to only operate on that specific feature. This is possible using the `filter` function of other ol-ext Interactions such as `Transform` or by instantiating the `Transform` interaction in the following way:

    this.transform = new Transform({
      features: this.select.getFeatures(),
      ..

But the above is not possible with the `DrawHole` interaction as far as I can tell by reading the sources. Any thoughts on how to accomplish that? E.g. I could try to abort the interaction if I realize it is operating on a feature I don't want it to but I don't see an API for that. The only solution I can imagine would be to place the selected feature on a separate layer on its own and allow `DrawHole` to operate on that layer. Is there a simpler way?

In the meantime the below code is what I am currently using but feels ugly and accesses a private property (`_select`) on the interaction.

        const f = this.drawHole!._select.getFeatures().item(0);
        if (this_is_not_the_feature_we_want(f)) {
              // alert the user somehow
              // set the drawHole interaction to false and back to true; this seems to clear up the currently drawn hole
             this.drawHole!.setActive(false);
             this.drawHole!.setActive(true);
        }

**Comment by Viglino** [comment]
Hello,
There is no option to do that but I can add some like one of the select interaction.

**Comment by mperdikeas** [comment]
> There is no option to do that but I can add some like one of the select interaction.

I *think* you mean the `Transform` interaction? Anyways, some filter function that would allow one to filter specific features instead of entire layers would be awesome!

**Comment by Viglino** [comment]
Hello,
I've added a `features` option to let you choice the features the interaction applies to.
It can be an array of features, a collection of features or a function that takes a feature and a layer and returns true if the feature is candidate...
Choice what you like...

**Comment by Viglino** [comment]
NB: remember its just a helper to click inside polygons, you also have to test if the resulting polygon is valid using topological tools (jsts).
