### ISSUE TITLE
Popup: "spinning effect" on first click

### ISSUE THREAD

**Issue by cap-ricci** [Viglino/ol-ext#578]
Hello,

I have a layer with several points. When I click on a point, a popup (Overlay.Popup) opens. 

The issue is that the first time I click on a point (any point), the view flies to the popup with a kind of "spinning effect around the world", as if the point was very far from the center, even if it is e.g. already at the center.

Any idea on what could be the cause?

Thank you for the support and all the great work on the extensions!

**Comment by Viglino** [comment]
I think your center your map outside the current world (outside the -180° and 180° meridians) or your data are outside.
When you open a popup (with a autoPan options set to true) it will pan to make it visible to the position you specify (making a 360° around the world).
Look at the center of the map (`map.getView().getCenter()`) and the position you specify to the popup to compare.

**Comment by cap-ricci** [comment]
Thank you for the answer! I solved the problem.
