### ISSUE TITLE
Problem with OL3 Feature Animation

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#58]
By looking at your demo at:
**http://viglino.github.io/ol3-ext/examples/map.featureanimation.html**

**Problem 1:**
1) Select "Drop" as Animation 1 and then 
2) Rotate your map (Shift + Alt + mouse drag) and then
3) Click on the map to create and animate a feature.
The problem is here that the feature always "drop" from the "north" and not from the "top", which is not a true "drop".

**Problem 2:**
By taking the same example above and working with:
`image: new ol.style.Icon` 
in place of 
`image: new ol.style.RegularShape`
creates a bug...

**Comment by Viglino** [comment]
Hy,

- Yes the drop animation "drops" from the north, not from the top of the map if it is rotated...
- The problem with the Icon style is that the image is not loaded and thus it can't be drawn. 
You can test it by using the load function of the ol.style.Icon.
I'll try to catch it to prevent crash...

@+

**Comment by 1Map** [comment]
Thanks, the example at:
http://viglino.github.io/ol3-ext/examples/map.featureanimation.select.html

still shows problem when you rotate the map and click on a feature...

**Comment by 1Map** [comment]
The example at:
http://viglino.github.io/ol3-ext/examples/map.featureanimation.html

now works 100% if animation 1 = Drop

But, it still does not work when animation 2 = Bounce

The Drop works when map is rotated, not the bounce...

**Comment by Viglino** [comment]
Yes all other animation don't check the map angle :-(
