### ISSUE TITLE
DrawTouch tap functionality not working in latest versions (Angular)

### ISSUE THREAD

**Issue by digoburigo** [Viglino/ol-ext#583]
I make a example on stackblitz with the latest versions of Openlayers, OL-EXT and Angular and the DrawTouch interaction it's not working properly. So I tried to investigate whats the problem but without success. I'm thinking about the possibility of Angular in the recent version change something about the touch functionality related to HammerJS, but it's just a guess.

Can you help me why it's not working?

Thanks

https://stackblitz.com/edit/angular-ivy-pyjaex?file=src/app/app.component.ts

**Comment by Viglino** [comment]
It seems the `tap` option is ignored on init.
You have to add it manually : `drawTouch.set('tap', true);`
I'll fix it in the next version.

**Comment by Viglino** [comment]
Have you tried `ol/interaction/TouchCursor` to draw features on touch devices ?
> http://viglino.github.io/ol-ext/examples/mobile/map.interaction.touchcursordraw.html
