### ISSUE TITLE
How to get a circle radius and center coordinates when ol.interaction.DrawRegular drawends?

### ISSUE THREAD

**Issue by busraa26** [Viglino/ol-ext#584]
I am trying to store circle with center coordinates and radius. But with this example you show area of the circle.
"e.feature.getGeometry().getRadius()" and "getCenter()" fails.

I need to detect it's a circle then store center coordinates and radius in DB. But if it's a polygon then i need to store codes with its type such as triangle then i shouldn't check its center coordinates or radius as expected.

`var` view = new ol.View({
    center: ol.proj.fromLonLat([35.14, 38.81]),
    zoom: 7,
    projection: 'EPSG:900913',
    displayProjection: 'EPSG:4326',
    units: "m",
    crossOrigin: "anonymous"
})
var attr = new ol.control.Attribution({
    collapsible: true,
    label: "A",
    collapsed: true,
    tipLabel: "TEST"
});

var map = new ol.Map({

    controls: ol.control.defaults({ attribution: true }).extend([
        new ol.control.Attribution({
            collapsible: true,
            label: "i",
            collapsed: true,
            tipLabel: "TEST",
            collapseLabel: "T"

        }),
        new ol.control.FullScreen({
            source: 'fullscreen',

        })
    ]),
    layers: [
        new ol.layer.Tile({
            source: new ol.source.OSM()
        })
    ],
    target: 'map',

    view: view

});

// New vector layer
var vector = new ol.layer.Vector({
    name: 'Vecteur',
    source: new ol.source.Vector()
});
map.addLayer(vector);

var interaction = new ol.interaction.DrawRegular({
    source: vector.getSource(),
    sides: 2, // this value will come from page after i fixed this problem.
    canRotate: true 
});
map.addInteraction(interaction);
interaction.on('drawstart', function (e) {
    // e.feature.on('change', function (){console.log('change');})
});

// Events handlers
interaction.on('drawing', function (e) {
    if (e.feature.getGeometry().getArea)
        var alan = (e.feature.getGeometry().getArea() / 1000000).toFixed(2); // km'2 cinsinden
        
});

interaction.on('drawend', function (e) {
// I need to check type of geometry too. it's a circle or triangle etc.
    if (e.feature.getGeometry().getArea) {

        var geometry = e.feature.getGeometry();
        var radius = geometry.getRadius(); // !!FAIL HERE!!
        var center = geometry.getCenter();
        console.log("radius:" + radius);
        console.log("center coordinatesı:");
        console.dir(center);
    }
});
// I'll draw circles on the map with coordinates which come from DB.
//var circle = new ol.geom.Circle(ol.proj.transform([-73.5971431341708, 45.5323780468158], 'EPSG:4326', 'EPSG:3857'), 1000);

//var CircleFeature = new ol.Feature(circle);

This library is awesome. Please help me to solve this problem.

Openlayers version: 3
ol-ext: latest

**Comment by Viglino** [comment]
DrawRegular interaction only draws regular polygons, no circles...
When you choose less than 3 points it will draw a polygon with many points (according to the view resolution) such that it looks like a circle...
You have to use a [ol/interaction/Draw](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html) with a `Circle` type option to create a real circle.
