### ISSUE TITLE
Last version of fontAwesome

### ISSUE THREAD

**Issue by damjang** [Viglino/ol-ext#585]
Is it possible to support last version of fontAwesome? I try to change to 5.15.3 but for me don't work...

Used this: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css

Thank you

**Comment by Viglino** [comment]
fontAwesome 5.15.3 seems to work properly: https://codepen.io/viglino/pen/QVNpzm?editors=1010
See #153 for more info (or #523)

**Comment by damjang** [comment]
Hmmm... in the bottom of the map yes, work, but the icon on the map no, I can't see the correct icon: [https://ibb.co/BB9CdnC](https://ibb.co/BB9CdnC)

**Comment by Viglino** [comment]
Working for me:
![image](https://user-images.githubusercontent.com/7868217/111965868-86051500-8af6-11eb-90cb-49f6165923a9.png)
NB: fonts have to load before drawing.
Depending on your network the map may render before it loads and you have to move the map to render again.

**Comment by damjang** [comment]
Also if I move the map, zoom or reload page, is always the same: no icon

**Comment by flucciarini** [comment]
I have the same problem square canvans instead of icon

My app i angular9
import FontSymbol as module as you suggest 

I have added all.min.css in component styleUrls, in constructor I write  
_FontSymbol.addDefs(
      {	"font":"FontAwesome",
        "name":"FontAwesome",
        "copyright":"SIL OFL 1.1",
        "prefix": "fa"
      },
      {	"fa-glass": "\uf000",
        "fa-music": "\uf001",
        "fa-search": "\uf002",
        "fa-envelope-o": "\uf003",
.....
FontSymbol.prototype.defs.fonts.FontAwesome.font = "Font Awesome 5 Free"; //map to new FA_

in my getStyle 
_new Style({
          image: new FontSymbol({
            form: 'none', //"hexagone", 
              gradient: false,
              glyph: 'fa-tree',//car[Math.floor(Math.random()*car.length)], 
              fontSize: 3,
              fontStyle: '',
              radius: 15, //serve per offsetY
              //offsetX: -15,
              rotation: 0*Math.PI/180,
              rotateWithView: false,
              offsetY: false ? -20:0 ,
              color: 'white',
              fill: new Fill({
                color: '#601f32'
              }),
              stroke: new Stroke({
                color: '#601f32',
                width: 4
              })
            }),
            stroke: new Stroke({
              width: 2,
              color: '#f80'
            }),
            fill: new Fill({
              color: [255, 136, 0, 0.6]
            })
          })_

**Comment by ngoloc10796** [comment]
![image](https://user-images.githubusercontent.com/28887448/159449217-de85faa8-2ce5-4ed7-b562-5b8ae46f3e3d.png)
https://codepen.io/viglino/pen/QVNpzm?editors=1010
i am getting the same error. Please check! Thank you

**Comment by Viglino** [comment]
Now it's working!
You have to use the FontAwesome 5 defs:
```html
<script type="text/javascript" src="//cdn.rawgit.com/Viglino/ol-ext/master/dist/extra/FontAwesome5Def.js"></script>
```
and use a `fontStyle: '900'` when creating the symbol: 
```javascript
  var img = new ol.style.FontSymbol({
    glyph:"fa-wheelchair",
    fontStyle: '900',
    radius: 20, 
    fill: new ol.style.Fill({
      color: "#369"
    }),
    stroke: new ol.style.Stroke({
      color: "#fff",
      width: 2
    })
  })
```

**Comment by ngoloc10796** [comment]
it's working verry good! Thank you so much!
