### ISSUE TITLE
Changing the Transform Box Color - Not Working

### ISSUE THREAD

**Issue by quanc** [Viglino/ol-ext#586]
I have a transform interaction that works great, but I want to change the default red/white box style. The following code is not working for me:

```
 var style = [
   new Style({
     image: new RegularShape({
       points: 4,
       fill: fill,
       stroke: stroke,
       radius: 5
     }),
     fill: fill,
     stroke: stroke
   })
 ];
 interaction.setStyle("default", style);
```

I'm not getting any errors from this code but the style is not applied. Is there a correct way to override this style? I want the red border to be white and I want the stroke to be larger. Any help would be appreciated.

**Comment by Viglino** [comment]
You have to define the style for all handles to get it work.  
`default` only applies style to the  rectangle border...
```javascript
["default","translate","rotate","rotate0","scale","scale1","scale2","scale3","scalev","scaleh1","scalev2","scaleh3"].forEach(s => {
  interaction.style[s][0].getImage().getStroke().setColor('#0ff');
  interaction.style[s][0].getImage().render()
});
```
I've added a helper in the last commit to let you change colors more simply:
```javascript
interaction.setDefaultStyle({
  stroke: new Stroke({ color: [0,0,255,1], width: 1 }),
  fill: new Fill({ color:[255,0,0,0.1] }),
  pointStroke: new Stroke({ color: [0,0,255,1], width: 1 }),
  pointFill: new Fill({ color:[0,0,255,0.1] })
})
```

**Comment by quanc** [comment]
The following does not work for me either:

      var interactionOptions: any = {
        enableRotatedTransform: false,
        layers: [vector],
        hitTolerance: 2,
        scale: true,
        rotate: false,
        translate: true,
        stretch: true,
      };
      interaction = new Transform(interactionOptions);

      [
        "default",
        "translate",
        "rotate",
        "rotate0",
        "scale",
        "scale1",
        "scale2",
        "scale3",
        "scalev",
        "scaleh1",
        "scalev2",
        "scaleh3",
      ].forEach((s) => {
        interaction.style[s][0].getImage().getStroke().setColor("#0ff");
        interaction.style[s][0].getImage().render();
      });

      this.interaction = interaction;

      map.addInteraction(interaction);
