### ISSUE TITLE
Icon rendering in Legend

### ISSUE THREAD

**Issue by shitathakin** [Viglino/ol-ext#588]
not really an issue so i understand if you don't have time, but wondering if there would be a good way to render an icon in the legend as opposed to the classic geometry types.

**Comment by Viglino** [comment]
You can display an icon using an [ol/style/Icon](https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html).
```javascript
var style = new ol_style_Style({
   image: new ol_style_Icon({
     ...
   })
 });
legend.addItem ({
  title: 'icon',
  typeGeom: 'Point',
  style: style
});
```
NB: the image must be loaded to display in the legend. You have to check it and render the legend when done.
```javascript
var style = new ol_style_Style({
   image: new ol_style_Icon({
     ...
   })
 });
// Check if image is loaded
style.getImage().getImage().addEventListener('load', function() {
  setTimeout(function() { legend.render(); }, 200);
});
style.getImage().load();
// Add Item
legend.addItem ({
  title: 'icon',
  typeGeom: 'Point',
  style: style
});
```
NB2: It seems there is a bug in the lib when image is not loaded (I've just pushed a fix)
NB3: I'm working on refactoring legend and it may changed to add an image legend (ie. an image for the whole legend when defined in a layer, [see here](https://wxs.ign.fr/static/legends/CADASTRALPARCELS.PARCELLAIRE_EXPRESS.png)) but I don't think it's your request.

**Comment by shitathakin** [comment]
working absolutely perfectly. Only weird thing is I get this error (doesn't effect a y functionality that i am aware of)

Legend.js:600 Uncaught TypeError: Cannot read property '0' of null
    at Il.getStyleImage (Legend.js:600)
    at Il.refresh (Legend.js:512)
    at Il.addRow (Legend.js:172)
    at e.<anonymous> (map.js:400)

**Comment by Viglino** [comment]
It is solved in the last commit (https://github.com/Viglino/ol-ext/blob/master/src/legend/Legend.js#L213) but not published yet.
