### ISSUE TITLE
ol is not defined

### ISSUE THREAD

**Issue by moxiaobei2** [Viglino/ol-ext#592]
npm install ol and then npm install ol-ext ，in index.html i got it with jquery.js. But when i run the service,webpack,it send error.it mains "ol is not defined" in .../node-modules/ol-ext/dist/ol-ext.js ,just like window.ol is undefiend ,ol is undefiend.
how i  can fix it?

**Comment by Viglino** [comment]
Ol-ext is an extention of Openlayers (ol).
You have to add the module as you do for Openlayers, ie. import it as a module... 
Don't include the dist/ol-ext.js file but use import to get new functionalities:
```javascript
import LayersSwitcher from 'ol-ext/control/LayersSwitcher'
// Create layer switcher control
const switcher = new LayerSwitcher();
```

**Comment by flucciarini** [comment]
I have same issue with FontSymbol.
My app angular 9, ol 6.4.3 and ol-ext 3.1.19
if I import FontSymbol as 
_import { FontSymbol } from 'ol-ext';_
I haven't error at compilation time but at runtime have this issue
_**Uncaught ReferenceError: ol is not defined
    at Object../node_modules/ol-ext/dist/ol-ext.js (ol-ext.js:23)
    at __webpack_require__ (bootstrap:79)**_

if I change import definition as you suggest I obtain this error
**_error TS2307: Cannot find module 'ol-ext/style/FontSymbol;'.
import { FontSymbol } from 'ol-ext/style/FontSymbol;_**

Can someone help me?

**Comment by Viglino** [comment]
If you use ol-ext as a module, you have to import the module without `{}` as it is the default class of the module:
```javascript
import FontSymbol from 'ol-ext/style/FontSymbol'
```

**Comment by flucciarini** [comment]
> ```js
> import FontSymbol from 'ol-ext/style/FontSymbol'
> ```

Thank you

**Comment by flucciarini** [comment]
How can I use FontAwesome as Module in angular 9 app?

**Comment by Viglino** [comment]
Fontawesome is a font you have to import the css.
