### ISSUE TITLE
doc/doc-pages/ol.control.Legend.html

### ISSUE THREAD

**Issue by butilka123** [Viglino/ol-ext#593]
Hello,
the documentation for the Legend is outdated. Can you please update it?
http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Legend.html

 Thank you in advance!

**Comment by Viglino** [comment]
I'm refactoring the legend. I'll update the doc when published.

**Comment by Viglino** [comment]
I've updated the doc
