### ISSUE TITLE
ol/interaction/TouchCursor on iOS

### ISSUE THREAD

**Issue by 321thomas** [Viglino/ol-ext#594]
It seems as ol/interaction/TouchCursor (Select, Modify, Draw) doesn't work on iOS devices. Cursor is not visually moving, except when finished move.

**Comment by Viglino** [comment]
It's working for me on iPad...

**Comment by 321thomas** [comment]
Thx, I've tested with Sauce labs iPad device and had the described problem...so it must be a problem there. Thank you for verifying.
