### ISSUE TITLE
ol.legend.Legend how to use it in separate index.js

### ISSUE THREAD

**Issue by tongji1984** [Viglino/ol-ext#603]
I split map.control.legends.html  to index.html and index.js in my program. But in index.js Legend is not defined as the error. So Can you tell me how to use it in this case.

**Comment by Viglino** [comment]
What is your code like?
Using JS directly in .html or in .js files has no effect on it.

**Comment by tongji1984** [comment]
// Define a new legend
  var legend = new Legend({ 
    title: 'Legend',
    margin: 5
  });
  var legendCtrl = new Legend_ctrl({
    legend: legend,
    collapsed: false
  });
  map.addControl(legendCtrl);
  //legend.on('select', function(e){ console.log(e) });
  
  // Add a new one
  var legend2 = new ol.legend.Legend({ 
    title: ' ', // no title
    margin: 5
  });
  map.addControl(new Legend_ctrl({
    legend: legend2,
    target: legendCtrl.element
  }));

  var form = { Trianle:3, Square:4, Pentagon: 5, Hexagon: 6 };
  for (var i in form) {
    legend.addItem({ 
      title: i, 
      typeGeom: 'Point',
      style: new Style({
        image: new RegularShape({
          points: form[i],
          radius: 15,
          stroke: new Stroke({ color: [255,128,0,1 ], width: 1.5 }),
          fill: new Fill({ color: [255,255,0,.3 ]})
        })
      })
    });
    legend2.addItem({ 
      title: i, 
      typeGeom: 'Point',
      style: new Style({
        image: new RegularShape({
          points: form[i],
          radius: 15,
          radius2: 7,
          stroke: new Stroke({ color: [0,128,255,1 ], width: 1.5 }),
          fill: new Fill({ color: [0,255,255,.3 ]})
        })
      })
    });
  }

**Comment by tongji1984** [comment]
import 'ol/ol.css';
import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';
import {transform} from 'ol/proj';
import {defaults as defaultControls, FullScreen, Rotate, ScaleLine} from 'ol/control';

import GeoJSON from 'ol/format/GeoJSON';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import {Fill, Stroke, Style, Text, Circle, RegularShape} from 'ol/style';

import 'ol-ext/dist/ol-ext.css';
import Legend_ctrl from 'ol-ext/control/Legend';

This program can not find ol.legend.

**Comment by tongji1984** [comment]
Could you tell me how I can use it in the index.html and index.js mode?

**Comment by Viglino** [comment]
If you use ol-ext as a module, you have to import the module (as you do for the first legend):
```javascript
import Legend from 'ol/legend/Legend'
var legend2 = new Legend ({
...
})
```

**Comment by tongji1984** [comment]
Dear Sir. Thank you for your suggestion. 
I can not find ol/legend/Legend in the module folder.
Is there any previous manipulation for this class?

**Comment by Viglino** [comment]
😢 It's a typo in my last comment Legend is a ol-ext class... in ol-ext/legend/Legend
```javascript
import Legend from 'ol-ext/legend/Legend'
```

**Comment by tongji1984** [comment]
Dear Sir 
In the ol-ext folder, I can not find the class of legend/Legend.

I only found control/Legend in my local folder.

**Comment by tongji1984** [comment]
Should I import some module before this?

**Comment by Viglino** [comment]
You have to upgrade to the last version (added in ol-ext@3.1.18)
> https://github.com/Viglino/ol-ext/tree/master/src/legend

**Comment by tongji1984** [comment]
Dir Sir. Can you tell me how to find the classname of legend in ol-ext.css, if I want to change the color of its background?

What is the difference of control.legend and legend in the CSS file?

**Comment by Viglino** [comment]
Just use the debugger to get look into the DOM (ctrl+shift+i on chrome or firefox).

**Comment by EircYangQiXin** [comment]
ol-ext@3.1.19 version not find legend.js, Can you answer that?
English is not my native language.

**Comment by Viglino** [comment]
`import Legend from 'ol-ext/legend/Legend'`
or 
`import LegendControl from 'ol-ext/control/Legend'`
Here: 
https://github.com/Viglino/ol-ext/tree/master/src/legend
or 
https://github.com/Viglino/ol-ext/blob/master/src/control/Legend.js

**Comment by tongji1984** [comment]
Please download it from master file directly, and copy it to your ol-ext folder.

**Comment by EircYangQiXin** [comment]
Does the package obtained from NPM install ol-ext not include the file legend.js?

**Comment by tongji1984** [comment]
No. please download it manually.

**Comment by Viglino** [comment]
OK there is a bug on the npm script and it seems the legend directory is not exported...
I'll try to publish a new one asap
Sorry for the trouble 😞

**Comment by EircYangQiXin** [comment]
So... can you let me know when it's published?

**Comment by tongji1984** [comment]
Please copy the folder https://github.com/Viglino/ol-ext/tree/master/src/legend
to your \node_modules\ol-ext\legend.

It can be used.

**Comment by Viglino** [comment]
I've just published a new version ol-ext@3.2.1 on npm 🚀

**Comment by EircYangQiXin** [comment]
use new version, the  new problem is not find ol/ol_Object.
Is that my problem? 
my ol version is ```ol@6.5.0```

**Comment by tongji1984** [comment]
Hello. Please change ol/ol_Object into ol/Object.

As a programmer, it is better to find library by yourself.

**Comment by EircYangQiXin** [comment]
Well, I'm just not used to modifying other lib because it causes a lot of unnecessary trouble

**Comment by Viglino** [comment]
ol-ext@3.2.2 should fix it

**Comment by tongji1984** [comment]
Thank you for your contribution!

**Comment by Viglino** [comment]
@tongji1984 OpenSource is a common business...

**Comment by EircYangQiXin** [comment]
Thank you for your contribution!
