### ISSUE TITLE
Export Map

### ISSUE THREAD

**Issue by shukla2103** [Viglino/ol-ext#604]
While exporting the map on different devices why the map is stretching. I am using that exported map base64 of image in pdf report. 

Need help in this.

**Comment by Viglino** [comment]
What are you using to export the map?
The image has a height and width you have to set on the pdf to prevent drawing stretched...

**Comment by shukla2103** [comment]
I am using the dom to image library to capture the image and convert it into base64 then while exporting it into pdf using jspdf library.

How can i set the height and image if the image has different size on different resolution machines.

**Comment by mike-000** [comment]
domtoimage is only needed if you want to include non-canvas controls or overlays.  In which case put the map div inside a wrapper div, when you want to export set the map div width and height as needed for export and call updateSize() before rendering for domtoimage (also set the resolution depending on whether you want a specific scale or extent for the output).  When domtoimage has completed clear the div width and height and call updateSize() again to return to the original size determined by the css.  See https://openlayers.org/en/latest/examples/print-to-scale.html

**Comment by shukla2103** [comment]
I have used domtoimage as i need legend along with map otherwise what you have discussed was fine for me but when exporting the map along with legend things become difficult

**Comment by Viglino** [comment]
The legend can be drawn on the canvas using ol-ext (see [legend example](https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html) + check `draw in map`) and you just have to export the resulting canvas.
You can also use the [new PrintDialog control](https://viglino.github.io/ol-ext/examples/canvas/map.control.printdialog.html) that will do it for you...

**Comment by shukla2103** [comment]
Thanks for the help now got it
