### ISSUE TITLE
Legend - Remove Item

### ISSUE THREAD

**Issue by butilka123** [Viglino/ol-ext#605]
Hi there,
in ol.legend. Legend is a method called "addItem(item)"

before the legend update there was also an remove. Could you maybe please also add an remove method? If not how can i remove  items from an exsisting Legend without creating a new one?

Thank you in advance :)

**Comment by Viglino** [comment]
Hello,
`addItem` is just a helper to let you enter either an ol/legend/Item or options as argument.
If you want to handle items in the legend, just use the `getItems()` method to retrieve the item collection and manipulate its content:
```javascript
legend.getItems().remove(item);
legend.getItems().removeAt(index);
legend.getItems().push(item); // similar as legend.addItem(item)
legend.getItems().pop();
legend.getItems().setAt(index, item);
legend.getItems().insertAt(index, item);
legend.getItems().clear();
```
