### ISSUE TITLE
Reverse geocoding button issues

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#610]
I'm using SearchNominatim and noticed the folloring regarding the reverse geocoding button:
![image](https://user-images.githubusercontent.com/3461504/120036401-c312e980-c008-11eb-917c-4b5de7a19663.png)

1) not sure how the tooltip for that inner button is set (want to localize it)
2) the search box could be longer and the button could move more to the right so that the reverse geocoding button is right-aligned to the dropdown menu
3) the icon of that button looks too much alike the one of the GeolocationButton which is confusing when both the Search and that button are on the same map UI

**Comment by Viglino** [comment]
Hello,
The tooltip is hard encoded... I've added a `reverseTitle` option in the last commit to lets you change it on creation.
The two other points are CSS encoded and you can overwrite the CSS in your app to correct it as you wish...
