### ISSUE TITLE
Geolocation button not showing tooltip

### ISSUE THREAD

**Issue by birbilis** [Viglino/ol-ext#611]
I'm using

    var geoloc = new ol.control.GeolocationButton({
      title: "Εμφάνιση τρέχουσας θέσης",
      delay: 1000 // 1s
    });
    map.addControl(geoloc);

to show Greek tooltip, but no tooltip seems to appear on hover (nor some English one so I wonder if that control has / allows to set a tooltip at all)

**Comment by Viglino** [comment]
The title seems to work correctly for me (https://viglino.github.io/ol-ext/examples/mobile/map.control.geolocationbt.html)

**Comment by birbilis** [comment]
not working for me at https://covid19-schools.cti.gr/map.html (it's at bottom right). Probably I did something wrong, works at your link

**Comment by Viglino** [comment]
Are you using the last version?

**Comment by birbilis** [comment]
Indeed, it was version-related, was on ol-ext 3.1.18, openlayers 6.4.3
At ol-ext 3.2.2, openlayers 6.5.0 the toolips for Geolocation button shows fine
