### ISSUE TITLE
Interruption of Speedprofil

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#613]
There's interruption of Speedprofil. I don't know why. There's not an error in GPX. I tried to edit GPX source. Without success. Maybe bug?

Example here: https://jedu.vsevjednom.cz/activity/2629

**Comment by Viglino** [comment]
Looking at your code it seems that the coords and coords2 array don't have the same number of points. coords: 6564 points, coords2: 6294 points...
Some points are missing in the speed profile...
You should add an extra `else` line 1352 to add the point in the profil anyway...

**Comment by vsevjednom-cz** [comment]
I understand. Do you know reason why there's not the same number of points?

**Comment by vsevjednom-cz** [comment]
Uaaa, I see it! My fault. Sorry.
