### ISSUE TITLE
professionnels.ign.fr/route120 No longer available (ol-ext: Dijkstras short path

### ISSUE THREAD

**Issue by charlesdwright** [Viglino/ol-ext#614]
![Screen Shot 2021-06-06 at 4 05 28 PM](https://user-images.githubusercontent.com/71340308/120938523-2378e980-c6e1-11eb-8edd-68dd3ac86f84.png)

alternatives? (no speaky Francois).

https://geoservices.ign.fr/documentation/diffusion/data/ROUTE120.geojson

![Screen Shot 2021-06-06 at 4 11 52 PM](https://user-images.githubusercontent.com/71340308/120938669-f7119d00-c6e1-11eb-8dcb-ad6581ef32d6.png)

**Comment by Viglino** [comment]
There is a copy of the data into the repo (https://viglino.github.io/ol-ext/examples/data/ROUTE120.geojson).
All IGN's data are available here: https://geoservices.ign.fr/documentation/diffusion/telechargement-donnees-libres.html
or here: https://www.data.gouv.fr/fr/datasets/route-120/
But you can use any geojson as graph source. You just have to define the weight and direction method...

**Comment by Viglino** [comment]
I've changed the link in the example page...
