### ISSUE TITLE
Disable hover interaction on (Custom) Controls

### ISSUE THREAD

**Issue by dbretschneider** [Viglino/ol-ext#615]
Hover interaction is also fired, if the feature is covered by a (custom) control. In my case, the polygon is covered by the zoom controls. 

Behaviour can be reproduced with the ol ext example [hover interaction](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.hover.html).

Steps to reproduced:
* Drag polygon feature under the zoom controls
* Hover over zoom controls ("Feature is: polygon" appears under options on the right side)

![hover_interaction](https://user-images.githubusercontent.com/3016561/122164764-8b64c800-ce77-11eb-9fdb-233c4339c356.png)

Limiting hover interaction on specific features / layers or return false in handleEvent does not bring any improvement.

It would be great to get an enhancement.

**Comment by Viglino** [comment]
This is a normal behavior of Openlayers interactions. 
See [Mouse-position example](https://openlayers.org/en/latest/examples/mouse-position.html): the position is updated when the cursor hover the zoom buttons.
One way would be to send the original mouse event with the hover interaction event to let you test the original target.

**Comment by Viglino** [comment]
I've added originalEvent to Hover interaction event to let you check the original target.

**Comment by dbretschneider** [comment]
Thanks for your quick reply. Checking the original target on hover event works on my dev env.
