### ISSUE TITLE
Pie chart symbology

### ISSUE THREAD

**Issue by berkayoruc** [Viglino/ol-ext#616]
Hello @Viglino. Your extensions are really good and helpful first of all thanks. A notch appears when defining stroke in the pie chart view.

![Inkeda_LI](https://user-images.githubusercontent.com/22800134/122176121-ef45bb80-ce8c-11eb-89ba-cc2b3f3a8b7c.jpg)

Here is chart configuration:

new ol.style.Chart({
          type: "pie", // pie pie3D donut bar
          radius: Math.min(size + 7, 50),
          data: data,
          rotateWithView: true,
          stroke: new ol.style.Stroke({
            color: "#fff",
            width: 2,
          }),
        })

Is there a way to remove this notch? I want to render stroke.

**Comment by Viglino** [comment]
Actually the Chart is drawn with all sector drawn, event null sector and thus a notch is drawn corresponding to null .
I can see to test if all values are null but one to have a plain chart...

**Comment by berkayoruc** [comment]
For that chart' data are like [0, 10, 0, 0]. I understood what you are saying.

**Comment by Viglino** [comment]
Using an other library will have the same render: https://codepen.io/viglino/pen/ZEewOOq?editors=0010

**Comment by berkayoruc** [comment]
I have handled it with using multiple styles. If there is single type data like [0, 0, 10, 0], circle type symbolgy is rendering.
