### ISSUE TITLE
Legends setting style  Icon image with src and typeGeom as Point not displaying

### ISSUE THREAD

**Issue by VandanaAwasthi** [Viglino/ol-ext#622]
I have an SVG image that I would like to use in legend.
I try to add to legend
typeGeom: 'Point',
  title: 'some icon'
      style: new Style({
        image: new Icon({
          src: '/assets/icons/abc.svg',
          
        })

the above gives errors looks like I need to specify size. so  I send size: [56,56] (size of image) but it doesn't display shows blank ?

any ideas what I am doing wrong?

**Comment by Viglino** [comment]
The style must be a valid Openlayers style... look at https://www.google.com/search?q=openlayers+svg+icon+style

Your svg must have a size (width and height attributes) or you have to set the imgSize in the style itself.
See ol example https://openlayers.org/en/latest/examples/icon-color.html

**Comment by VandanaAwasthi** [comment]
I was using src and it didn't work, changed it to use img, and set imgSize and also preloaded the svg..and that works.
was hoping it to work with just src and size and without preload.  
(I use the icon styling on maps too with just src, size and scale and that works without having to preload the images.)

**Comment by Viglino** [comment]
Are you using the last version ?
I've added a function to test SVG loading in the example: https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html
Just type `addSVG()` in the debugger console to add a SVG item in the control...
