### ISSUE TITLE
Feature Request MGRS for Openlayers

### ISSUE THREAD

**Issue by Kobrairaq** [Viglino/ol-ext#623]
i want to convert lonlat to MGRS in the mouse.Position.control if some one can help ?

**Comment by Viglino** [comment]
To convert lonlat to MGRS you have to use a third party library such as [proj4js/mgrs](https://github.com/proj4js/mgrs).
Then use mgrs.forward([lon,lat], accuracy) to get the MGRS coord.
See here: https://stackoverflow.com/questions/68184040/how-to-convert-openlayers-6-5-mouse-position-control-from-lonlat-to-mgrs
