### ISSUE TITLE
Profil tool graduation and rounding for displayed labels

### ISSUE THREAD

**Issue by sebbelese** [Viglino/ol-ext#624]
Hello,

I use the profil tool in my web-gis application to display raster profiles along polylines. It works quite well, but I have an issue with graduations.

I try to obtain a generic scaling of the y axis, working at any scale:
```
let zmin = feature.get('zmin');
let zmax = feature.get('zmax');
let graduation = Number(((zmax-zmin)/20).toPrecision(2));

profil.setGeometry(feature, {"graduation":graduation});
```
where zmin and zmax are features properties defining the z data range.

It works quite well in some cases:
![image](https://user-images.githubusercontent.com/16559668/123939584-8f750780-d998-11eb-97c8-e01ed1fa545a.png)

But sometimes, the labels are not rounded adequately, leading to unreadable values:
![image](https://user-images.githubusercontent.com/16559668/123939629-99970600-d998-11eb-9eb9-fe816271fc7e.png)

Would it be possible to round these labels for readability, for example by using ".toPrecision(...)" with a max number of digits? Or is there any alternative way of doing it?

Another issue: I am not sure why the number of graduations is so different between the two plots with similar ranges. I was expecting ~20 graduations for each plot. A difference between the two situations is that the graduation value is 0.93 (<1)  for one plot and 1.1 (>1) for the other one.

Thanks for any help!

**Comment by Viglino** [comment]
Hello,
I've added a zDigits option to let you set the number of digit in the profile.

**Comment by sebbelese** [comment]
Waw, it was fast!

Thanks, it works.

![image](https://user-images.githubusercontent.com/16559668/123951922-9b1afb00-d9a5-11eb-9e74-5e242727221d.png)
![image](https://user-images.githubusercontent.com/16559668/123951963-a5d59000-d9a5-11eb-9241-b5f2ec15c79c.png)

**Comment by rasa2k** [comment]
Is it possible to override the y,x labels in the chart? I can only get it to write "Altitude".-
