### ISSUE TITLE
URL issue with WMSCapabilities

### ISSUE THREAD

**Issue by jakwarrior** [Viglino/ol-ext#625]
Hello @Viglino,

I have an issue when I use that kind of url with the WMS Capabilities control :
- http://mymachine:8080/wms/
- http://192.168.10.20:8080/wms/
The regex at line 408 in WMSCapabilities.js doesn't handle url without ".com" like extension. I always have the message : "The input value is not a valid url..."

Moreover, would it be complicated to add the management of WMTS requests to this control?

**Comment by Viglino** [comment]
Hello,
I've add a `testUrl` method you can overwrite to let it run on your data.
I've also added ipv4 address but others formats are quite tricky.
Using this mechanism you can also limit url to a set of addresses/pattern.
You just have to overwrite the method:
```javascript
var cap = new ol.control.WMSCapabilities({ ... });
// enable all url string
cap.testUrl = function() { return true }
```

WMTS is quite different and will need an other control I think...

**Comment by Viglino** [comment]
Hello
I've started a new WMTSCapabilities control. 
Not sure it's working on all services and interactive form is not fonctional.
Let me know if it works for you.
http://viglino.github.io/ol-ext/examples/layer/map.wmtscapabilities.html
