### ISSUE TITLE
PopupFeature associated features navigation not showing

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#627]
Hi,

I was playing around ol/Overlay/PopupFeature, and I think I found a bug.
I can reproduce it here: https://viglino.github.io/ol-ext/examples/popup/map.popup.feature.html

If I click one of the first two feature in the top of the feature-collection "Hauts-de-France" for example. The two features should be associated with each-other by region, and the navigation bar should show up to jump to the next associated feature, but every second/third click back and forth it disappears. I looked in the dom for "ol-count" but it doesn't get rendered. 
![Capture](https://user-images.githubusercontent.com/33285536/124397279-55e12b00-dd0f-11eb-85a9-6c9cd9cf0e16.PNG)

**Comment by rasa2k** [comment]
It actually depends on if I click on the border where the two associated features meet, then I see the navigation, but not by clicking in the middle of the feature. Is that by design?

**Comment by rasa2k** [comment]
How does this work, maybe it's my savior "You can use the show() to show the popup associated to a feature." It's not in the example nor the documentation.

**Comment by rasa2k** [comment]
Since the example is based of ol.interaction.Select the behavior makes sense.

**Comment by Viglino** [comment]
The example use `multi: true,` as option in the Select interaction with a large `hitTolerance` (=5) to show the behavior of the popup on multi selection.
Just use `multi: false` to have only one object selected at ones.
