### ISSUE TITLE
Disable cluster selection

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#628]
Hi,

I can't seem to be able to disable cluster selection new ol.interaction.SelectCluster.
I used this example https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html

`var selectCluster = new ol.interaction.SelectCluster({
       selectCluster: false, // disable cluster selection
})`

**Comment by Viglino** [comment]
The `selectCluster` option only prevents cluster to be included in the selection list:
```javascript
  selectCluster.on('select',  () => {
    const n = selectCluster.getFeatures().getLength();  // n==0 when click on the cluster and selectCluster=false
  })
```

As any ol interaction, use setActive to activate/deactivate it.
```javascritp
selectCluster.setActive(false)
```
