### ISSUE TITLE
path animation geoCollection support

### ISSUE THREAD

**Issue by rtmzshw** [Viglino/ol-ext#629]
is it possible to animate a geoCollection? 
it is not working for me and im not finding any information in the docs.

after diving to the source code im seeing that the geometry is missing the function "setCoordinates" in line 86 in "ol-ext/Path.js" file.
` e.geom.setCoordinates(p);`
i guess its because the gemoetry have many coordinates hence it cant have a single setter. 
thank you.

**Comment by Viglino** [comment]
Actually the Path animation is only designed to move Points along the path. 
Other geometries are not taken into account by the animation...
