### ISSUE TITLE
WebJar not accept CeCILL-B licence

### ISSUE THREAD

**Issue by isoum2** [Viglino/ol-ext#63]
I tried to add a WebJar (https://www.webjars.org/) from the NPM package but the CeCILL-B licence is not accepted.

This is the deployment log:

Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/Viglino/ol3-ext.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: CECILL-B
This problem will likely need to be resolved by working with the library maintainers directly.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Deploying org.webjars.npm ol3-ext 1.0.1
Starting Deploy

The accepted licences are:
AFL-2.1, AFL-3.0, AGPL-V3, Apache-1.0, Apache-1.1, Apache-2.0, APL-1.0, APSL-2.0, Artistic-License-2.0, Attribution, Bouncy-Castle, BSD, BSD 2-Clause, BSD 3-Clause, BSL-1.0, CA-TOSL-1.1, CC0-1.0, CDDL-1.0, Codehaus, CPAL-1.0, CPL-1.0, CPOL-1.02, CUAOFFICE-1.0, Day, Day-Addendum, ECL2, Eiffel-2.0, Entessa-1.0, EPL-1.0, EUDATAGRID, EUPL-1.1, Fair, Facebook-Platform, Frameworx-1.0, Go, GPL-2.0, GPL-2.0+CE, GPL-3.0, Historical, HSQLDB, IBMPL-1.0, ImageMagick, IPAFont-1.0, ISC, IU-Extreme-1.1.1, JA-SIG, JSON, JTidy, LGPL-2.1, LGPL-3.0, Libpng, LPPL-1.0, Lucent-1.02, MirOS, MIT, Motosoto-0.9.1, Mozilla-1.1, MPL-2.0, MS-PL, MS-RL, Multics, NASA-1.3, NAUMEN, Nethack, Nokia-1.0a, NOSL-3.0, NTP, NUnit-2.6.3, NUnit-Test-Adapter-2.6.3, OCLC-2.0, Openfont-1.1, Opengroup, OpenSSL, OSL-3.0, PHP-3.0, PostgreSQL, Public Domain, Public Domain - SUN, PythonPL, PythonSoftFoundation, QTPL-1.0, Real-1.0, RicohPL, RPL-1.5, Scala, SimPL-2.0, Sleepycat, SUNPublic-1.0, Sybase-1.0, TMate, Unlicense, UoI-NCSA, VIM License, VovidaPL-1.0, W3C, WTFPL, wxWindows, Xnet, ZLIB, ZPL-2.0

**Comment by Viglino** [comment]
Yes the CeCILL-B licence is a French licence not referenced. As it is BSD compatible you can use this licence in replacement.

**Comment by isoum2** [comment]
Thanks!

Could you please republish the npm package so I can create the WebJar?.
The last package version was published 5 months ago (https://www.npmjs.com/package/ol3-ext).

**Comment by Viglino** [comment]
ol3-ext change is name and is now available on npm: https://www.npmjs.com/package/ol-ext.
I'll try to keep the package alive
