### ISSUE TITLE
Title parameter in ol.control.Print

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#633]
I need something like this: `var printControl = new ol.control.Print({imageType: "image/png",title: "Save as img"});`

Parameter `title` works with `ol.control.Button` but no with `ol.control.Print`. `title` is good for page visitors.

Or there's another way to set `title`? [I can't find it](https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Print.html).

**Comment by vsevjednom-cz** [comment]
Great would be the same thing for `ol.control.Profil` button in the map.

**Comment by Viglino** [comment]
Added in the last commit!
