### ISSUE TITLE
Little question about ol.style.Photo

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/ol-ext#634]
I have a little request for you.
Look at this: https://jedu.vsevjednom.cz/activity/2677
Do you know why there's small photos in the right corner of a squares and I can't click on them (I need to call function `ZobrazFotku`: `if(match) { ZobrazFotku(`)? It worked before. I tried to use [your example](http://viglino.github.io/ol-ext/examples/style/map.style.photo.html) but with same result. I tried disable some CSS styles but without success. So I'm confused. It will be some small thing, but I can't figure out what. Can you help me? Pleeease!

**Comment by vsevjednom-cz** [comment]
Oh, there's some problem in my "ol-ext.js" (little edits). It  works ok when I trying original ol-ext. Sorry for this opened issue.You can delete it 🙃.

**Comment by vsevjednom-cz** [comment]
Hmm, problem is somewhere here: https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.min.js
Everyhing works ok with this source file: https://viglino.github.io/ol-ext/dist/ol-ext.min.js
🤪 🤪 🤪

**Comment by Viglino** [comment]
It's a bug that appears with ol v6.
Fixed in the last commit but not yet published...
