### ISSUE TITLE
Graticule is not displayed

### ISSUE THREAD

**Issue by Tillo2** [Viglino/ol-ext#639]
I want to use the ol-ext graticule but it wont show up on the map. I installed openlayers with npx create-ol-app and ol-ext with npm install ol-ext. This is my code:

```ruby
import 'ol/ol.css';
import { Map, View } from 'ol';
import TileLayer from 'ol/layer/Tile';
import OSM from 'ol/source/OSM';
import Graticule from 'ol-ext/control/Graticule'

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
  ],
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
  control: [
    new Graticule({ projection: "EPSG:4326" })
  ],
})
```
Thanks for your help.

**Comment by Viglino** [comment]
Map option to add a control is `controls` with a 's'...
```javascript
  controls: [
    new Graticule({ projection: "EPSG:4326" })
  ],
```
...but you will loose the default controls.
Use `map.addControl(new Graticule({ projection: "EPSG:4326" }))`instead...

**Comment by Tillo2** [comment]
Thank you, now the graticule shows up but for some reason its below the map. If I drag the map around I can see the graticule in parts where the map is still loading. How can I display the graticule above the map?

**Comment by Viglino** [comment]
Are you sure you include ol-ext css?

**Comment by Tillo2** [comment]
Yes the ol-ext css was missing. I included it and it works now thank you
