### ISSUE TITLE
SearchFeature - undefined coordinate

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#64]
I have problem with ol.control.SearchFeature

Seems to link souce is ok, have list of features but select - enter (on)
doesn't work.

Issue:
`Uncaught TypeError: Cannot read property 'coordinates' of undefined
    at ol.control.SearchFeature.ol.control.Search.select (ol3-ext.js:4187)
    at HTMLLIElement.<anonymous> (ol3-ext.js:4014)
    at HTMLLIElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLLIElement.q.handle (jquery-3.1.1.min.js:3)`
version:
OL 4.6.2, ( at lower ol too doesn't work)
jQuery 3.1.1  (jQuery 1.11.0 so doesn't work)

Coordinates are ok, I get sourceVector from GeoServer.
my code 
`	var select_wezly = new ol.interaction.Select({});
`

`	var search_wezly = new ol.control.SearchFeature(
		{	source: vS_wezly,
			property: "adr_adm"
		});`

`	search_wezly.on('select_wezly', function(e)
		{	select_wezly.getFeatures().clear();
			select_wezly.getFeatures().push (e.search_wezly);
			var p = e.search.getGeometry().getFirstCoordinate();
			map.getView().animate({ center:p });
			map.getView().setZoom(18);
		});`

and one more issue on loading map:
`Uncaught ReferenceError: $ is not defined
    at ol3-ext.js:13811`

**Comment by Viglino** [comment]
Hi,
You're right! there is a bug: the ol.control.SearchPhoton override a search function :-(
To prevent it, you have to insert the control/searchcontrol.js file after the ol3-ext.js.
I'll commit a new asap.
@+

**Comment by Bear4** [comment]
Changed scripts linking (without ol3-ext.js):
```
   <link rel="stylesheet" href="control/searchcontrol.css" /> 
   <script type="text/javascript" src="control/searchcontrol.js"></script> 
   <script type="text/javascript" src="control/searchfeaturecontrol.js"></script> 
```

And with **var** named **`search`** works proper 
...but when trying implement searching on a few layers
eg named **var searchK** got error:

```
    ol-debug.js:3422 Uncaught TypeError: Cannot read property 'ol_uid' of undefined
    at Object.ol.getUid (ol-debug.js:3422)
    at ol.source.Vector.addFeatureInternal (ol-debug.js:59937)
    at ol.source.Vector.addFeature (ol-debug.js:59926)
    at ol.source.Vector.<anonymous> (ol-debug.js:60082)
    at ol.Collection.boundListener (ol-debug.js:7277)
    at ol.Collection.ol.events.EventTarget.dispatchEvent (ol-debug.js:7697)
    at ol.Collection.insertAt (ol-debug.js:8341)
    at ol.Collection.push (ol-debug.js:8368)
    at ol.control.SearchFeature.<anonymous> (main_refresh_popup.js:1000)
    at ol.control.SearchFeature.boundListener (ol-debug.js:7277)
```
 **_It's possible set a few search source?_**
My code:
**var searchK** - not works
```
       var selectK = new ol.interaction.Select({});
       map.addInteraction(selectK);

	var searchK = new ol.control.SearchFeature(
		{	
			source: vS_komory,
			property: "nazwa"
		});
	// Select feature when click on the reference index

	searchK.on('select', function(e)
		{	console.log('run search_on K...');
			selectK.getFeatures().clear();
			selectK.getFeatures().push (e.searchK);
			var p = e.searchK.getGeometry().getFirstCoordinate();
			map.getView().setZoom(18);
			map.getView().animate({ center:p });
		});
```

**var search** - works

```
	var select = new ol.interaction.Select({});
	map.addInteraction(select);
	
	var search = new ol.control.SearchFeature(
		{	source: vS_wezly,
			property: "adr_adm"
		});
	// Select feature when click on the reference index

	search.on('select', function(e)
		{	console.log('run search_on...');
			select.getFeatures().clear();
			select.getFeatures().push (e.search);
			var p = e.search.getGeometry().getFirstCoordinate();
			map.getView().setZoom(18);
			map.getView().animate({ center:p });
		});	
```

**Comment by Viglino** [comment]
There is an error in your code: the 'on select' event returns a search attribute (`e.search` which is the searched feature) and don't car about the name of the search control.
You have to replace `e.searchK` by `e.search` in your on select function.
@+
