### ISSUE TITLE
WMTSCapabilities control - No TileMatrixSet supported...

### ISSUE THREAD

**Issue by rasa2k** [Viglino/ol-ext#642]
Hi, 

Cool ideer regarding the wmts lookup and choosing a service-layer.
I'm getting some "No TileMatrixSet supported..." when using https://api.dataforsyningen.dk/dhm_flow_ekstremregn. If I look in the console I do see a TileMatrixSet, but maybe the type is not supported?

KR.

**Comment by Viglino** [comment]
The only tileMatrix supported is PM.
I don't know how to decode others. Actually it only supports EPSG:3857 tilegrids...
