### ISSUE TITLE
Render special characters in ol legend Item

### ISSUE THREAD

**Issue by phelanHayes** [Viglino/ol-ext#644]
This is more of a feature request.  

I would like to request that the legend item option 'title' property be placed in the innerHtml of the child 'div' inside the 'li' element instead of inside the 'alt' property of the 'li' tag.  This would allow special characters such as '&le;' to used.  Perhaps there is another way for special characters to be used that I'm unaware of?

Earlier versions worked this way before the refactor of the ol_control_legend.

v3.1.19, Legend.js, line 154
col.innerHTML = str || '';

**Comment by Viglino** [comment]
Last version render legend in a canvas to let it overlay the map canvas and make it printable.
The overlapping list (li) is only to handle interactions on the map (row hovering, clicks, information) and doesn't contains any html.
Special char however can be used as long as the font permits.

Use: "😀 Title ≤ 0" on the example page:  https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html

![image](https://user-images.githubusercontent.com/7868217/129716315-cde3bca1-9de6-4ed2-b017-7efcb569fa9f.png)

**Comment by phelanHayes** [comment]
Thank you for the reply and explanation.  I did notice the canvas element addition, but now the overlapping list (li) makes more sense.  In my instance, I am using html entity codes such as '&le; 50&deg;F' that come from my data feed which before the intro of the canvas element, were rendered in html.  I'm uncertain I'll be able to find a work around for this using the canvas element solution.

The introduction of the canvas element is however very useful for other context such as printing.  Currently I take extra steps to extract the legend, convert it to canvas and add it to a custom  canvas element.  Thank you for the ol-ext library!

**Comment by Viglino** [comment]
You can convert your special char using html interpretor:
```javascript
function convert(t) {
  var d = document.createElement('DIV')
  d.innerHTML = t;
  return d.innerText;
}
legend.addItem({
  title: convert('&le;50&deg;F'),
});
```

**Comment by phelanHayes** [comment]
Thank you! I will try this solution.
