### ISSUE TITLE
Popup anchor issue since OL 4.5.0

### ISSUE THREAD

**Issue by pjmeier** [Viglino/ol-ext#65]
The anchor for the popup overlay is not positioned correctly when used with OL 4.5.0 or greater.
You can see the issue in the demo as it's using the latest OL : http://viglino.github.io/ol3-ext/examples/map.popup.html

**Comment by Viglino** [comment]
Yes there is an issue on the anchor position. I think it's just a CSS issue...

**Comment by pjmeier** [comment]
That's what I thought. The ol.css hasn't changed since the issue though. I did have a look hoping it would be an easy fix but ran out of time. I've rollback to using a previous version of OL in the meantime and may look at it again after the festive season.

**Comment by Viglino** [comment]
OK, it's not just a CSS issue.
The last commit solve the issue.

**Comment by pjmeier** [comment]
Fantastic work. 
I noticed that stop event is set to false on line 28 of the popupoverlay.js whereas previously it was true. Having it false causes some issues on my popup that has buttons and tooltips. Should it be true or is there a reason it's set to false?

**Comment by Viglino** [comment]
I put the option back to true (I think it was just a test).
