### ISSUE TITLE
LayerSwitcher Checkbox layer Setting

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#656]
Currently i have a Car Layer and inside car Layer there are 3 sub car brand layers

Car
- BMW
- Audi
- Honda

currently if i check the Car Layer i does disappear all the car layer but in layerswitch the checkbox for (BMW,Audi,Honda) are checked despite the Car checkbox is uncheck.

can i do it if 

1.  car layer checkbox is uncheck , all the sub layer of car is also uncheck,
2. if all the sub layer of car is uncheck, the car layer checkbox will be unchecked also

it is the same as labels under http://viglino.github.io/ol-ext/examples/control/map.switcher.filter.html

if uncheck labels, both terrian-labels and toner-labels are not uncheck. another situation is i uncheck both terrian-labels and toner-labels, but the labels are not uncheck.

Thanks You

**Comment by Viglino** [comment]
Sub layers in a group have there own visibility.
If you want them to reflect the parent visibility you have to do it by your own...
```javascript 
grouLayer.on ('change:visible', function(e) {
  // change Sub layers visibilité
  groupLayer.getLayers().forEach (l) {
    L.setVisible (groupLayer.getVisible ())
  }
})
```

**Comment by ngjiajunsg** [comment]
Thanks Viglino.

i manage to do it with the help of your help :)
