### ISSUE TITLE
Photo Style OL 6.7.0

### ISSUE THREAD

**Issue by All4Gis** [Viglino/ol-ext#661]
Hi,

First of all, congratulations on this amazing extension.

I am testing ol-ext 3.2.6 with the openlayers version 6.7.0.

I can't see the photos, and I don't get any error in the console.
That part works with the latest version of Openlayers?,
```
export const getPhotoStyle = (image: string): Style => {
  return new Style({
    image: new Photo({
      src: image,
      radius: 85,
      crop: true,
      shadow: true,
      crossOrigin: 'anonymous',
      stroke: new Stroke({
        color: 'fff',
        width: 2
      }),
      kind: 'round',
      onload: () => {
        return true
      }
    })
  })
}
```

I can do if you want a complete example

**Comment by Viglino** [comment]
Try to remove the `crossOrigin` param or make sure your images have CORS.
Do you have errors in the console?
Or give a complete example...

**Comment by All4Gis** [comment]
No console errors. I will make a complete example
