### ISSUE TITLE
Problem adding padding by view.fit into my ol-ext map

### ISSUE THREAD

**Issue by peteresteris** [Viglino/ol-ext#663]
Hello pals
I have an app with a perspectiveMap from ol-ext; that I want to change between 0 to 30 in perspective. But, when I have perspective 30 my map center left in projection at top of the map. I correct that adding padding in the view on map initialization. But when I change perspective the offset is applied and my center left to much below. This is the way my original map is looked like:
![imagen](https://user-images.githubusercontent.com/53539821/133909642-b8cf90d2-1986-4c68-8d2d-8eb6291a334e.png)

When I applied padding: [700,0,200,0] in this way:

```
this.view = new View({
    center: location,
    zoom: this.zoom,
    padding: [700, 0, 200, 0],
    constrainResolution: true
  })
```

I obtained what I wanted:
![imagen](https://user-images.githubusercontent.com/53539821/133909607-e44f4b5d-ccf4-4f27-b53b-27fc0981f88c.png)

However, if I change perspective to 0; all the offset is applied too.
![imagen](https://user-images.githubusercontent.com/53539821/133909647-450291a7-0ae8-4c83-9854-969c9f00014c.png)

I tried this code:

```
this.pMap.on('change:perspective', (e) => {
        if (this.tilt === 0){
          this.view.fit(this.centeredIcon.getGeometry(), {
            padding: [0, 0, 0, 0],
            size: this.pMap.getSize(),
            callback: (complete)=>{
              if (complete) {
                this.view.animate({
                  zoom: this.zoom,
                  duration: 300
                })
              }
            }
          })
        } else {
          this.view.fit(this.centeredIcon.getGeometry(), {
            padding: [700, 0, 200, 0],
            size: this.pMap.getSize(),
            callback: (complete)=>{
              if (complete) {
                this.view.animate({
                  zoom: this.zoom,
                  duration: 300
                })
              }
            }
          })
        }
      })
```

But nothing happened. Could anyone has used view's fit with padding successfully?
Thanks in advanced

**Comment by Viglino** [comment]
That's a consequence of the perspective...
The first plan (map bottom) is more enlarge than the top of the map... en thus a shift is made on the top...

**Comment by peteresteris** [comment]
I did that in the beginning but I had a performance issue in the phone. The map's performance decrease a lot and sometimes son tiles left empty when the map suddenly rotate or pan with the geolocation. Also, it works well padding above but not the same below.
I calculated it dinamically. Android Studio log me about a performance trouble. Once I removed all over enlarges, map moves fluidly.
