### ISSUE TITLE
ol.style.FlowLine works Not as expected when zoomed the map

### ISSUE THREAD

**Issue by PongChen** [Viglino/ol-ext#664]
http://viglino.github.io/ol-ext/examples/style/map.style.gpxline.html

for example this ，i can see the line  is composed of many little segments actually，with the basemap as the reference，when i zoomed the map， the position of Connection point of these segments changed，so，how dose it display elevation color accurately。
 looking forward to your reply，thanks

**Comment by PongChen** [comment]
![image](https://user-images.githubusercontent.com/21305978/134293524-43433fc9-6a07-423f-a862-421c07caee11.png)
![image](https://user-images.githubusercontent.com/21305978/134293581-38d540f2-4264-404b-bc19-22422ce8a065.png)
![image](https://user-images.githubusercontent.com/21305978/134293635-1c4f223b-65ff-48f0-bbd5-bcfaa66c5696.png)
zoom Increasing
color display different

**Comment by Viglino** [comment]
The length of the segments composing the line depends on the resolution of the drawing (the more you zoom the smaller the segments).
The color depends on the altitude of the center of the line segments, thus when you zoom the color may change and be more accurate...

In addition the color function doesn't take into account the real coordinate of the segment but the elevation of the center of the line segments (that my differ from the current point and swap due to threshold effect). This function could be enhance to compute the real height along the line...

**Comment by PongChen** [comment]
other question for help

the position where every two segments connection,  at the beginning and endingof the segement will be coverd ，can it be avoided？

![image](https://user-images.githubusercontent.com/21305978/134303143-ae118564-489d-44ee-8b67-2e1fa2f2129e.png)

<!DOCTYPE html>
<html>
<head>

  <title>ol-ext: GPX flow style</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  
  <meta name="description" content="Draw flow maps or Sankey maps with Openlayers." />
  <meta name="keywords" content="ol, openlayers, vector, style, stroke, width, color, variable, gpx, flow" />

  <link rel="stylesheet" href="../style.css" />

  
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  
  <link rel="stylesheet" href="https://openlayers.org/en/latest/css/ol.css" />
  <script type="text/javascript" src="https://openlayers.org/en/latest/build/ol.js"></script>
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL,Object.assign"></script>
  
  
  <link rel="stylesheet" href="../../dist/ol-ext.css" />
  <script type="text/javascript" src="../../dist/ol-ext.js"></script>
  
  <script src="https://unpkg.com/elm-pep"></script>

  <style>
    .ol-control.ol-legend {
      background-color: #fff;
    }
  </style>
</head>
<body >
  <a href="https://github.com/Viglino/ol-ext" class="icss-github-corner"><i></i></a>

  <a href="../../index.html">
    <h1>ol-ext: GPX flow line style</h1>
  </a>
  <div class="info">
    <p>
      This example show how to use a <i>ol.style.FlowLine</i> to display elevation color along a GPX track.
      <br/>
      You have to set the <i>visible</i> option to false to calculate the values on the whole line and not only on the visible part of it.
    </p>
    <p>
      Look at <a href='map.style.flowline.html'>this example</a> for more information.
    </p>
  </div>

  
  <div id="map" style="width:600px; height:400px;"></div>

  <div class="options" style="min-width:300px;">
  </div>

<script type="text/javascript">
	// Layers
	var layer = new ol.layer.Geoportail({ layer: 'ORTHOIMAGERY.ORTHOPHOTOS' });

	// The map
	var map = new ol.Map({
    target: 'map',
    view: new ol.View({
      zoom: 21,
      //center: [740741, 5776642]
      center: [11536302.33, 4320426]
    }),
    layers: []
  });

  // Calculate the min/max elevation on the line
  var min, max;
  function getMinMax (feature) {
    max = 40;
    min = 0;
  }
  // Get the line color at dh
  function getColor(dh) {
       return [ 255, dh, dh ];
  }
  // The style function
  function styleFn(f) {
    return new ol.style.FlowLine({
      visible: false,
      arrow: 1,
    //   lineCap: 'round',
      color: function(f, step){
        var seg = [];
        var line = f.getGeometry()//d.getLineString(0);
        line.getCoordinateAtSeg(step*line.getLength(), seg);
        if (seg[0][2] === null || seg[1][2] === null) {
        return 'rgba(0,0,0,0.5)'
      }
        var h = (seg[0][2]+seg[0][2])/2/40*255;
        return getColor(h);
      },
      width: 5,
      geometry: function (f) {
        if (f.getGeometry().getType() === 'MultiLineString') {
          return f.getGeometry().getLineString(0);
        } else {
          return f.getGeometry();
        }
      }
    })
  }const aa= [[
        11536312.94964732,
        4320424.748478653,
        105,
        5,
        "2021-09-12 21:04:24",
        "134260006",
        null
    ],
    [
        11536309.70462389,
        4320425.258524554,
        10,
        5,
        "2021-09-12 21:04:27",
        "134260006",
        null
    ],
    [
        11536302.958662746,
        4320425.672075299,
        105,
        5,
        "2021-09-12 21:04:30",
        "134260006",
        null
    ],
    [
        11536295.811951436,
        4320426.140766162,
        10,
        5,
        "2021-09-12 21:04:33",
        "134260006",
        null
    ],
    [
        11536289.177309785,
        4320426.871372549,
        105,
        5,
        "2021-09-12 21:04:36",
        "134260006",
        null
    ],
    [
        11536260.898890506,
        4320427.395203576,
        null,
        null,
        "2021-09-12 21:04:39",
        "134260006",
        null
    ],
    [
        11536257.898890506,
        4320427.395203576,
        10,
        null,
        "2021-09-12 21:04:39",
        "134260006",
        null
    ],
    [
        11536255.898890506,
        4320427.395203576,
        5,
        null,
        "2021-09-12 21:04:39",
        "134260006",
        null
    ]
]
const feature = new ol.Feature({ geometry: new ol.geom.LineString(aa) })
	var source = new ol.source.Vector({
    //url: '../data/192553.gpx',
    features: [feature]
  });
	var vector = new ol.layer.VectorImage({
    source: source,
    style: styleFn
	});
  map.addLayer(vector);
  
  // Profil control
  var profil = new ol.control.Profil({
    target: $('.options').get(0)
  });
  map.addControl(profil);
  
	// Show feature profile when loaded
  var pt = new ol.Feature(new ol.geom.Point([0,0]));
  var style = new ol.style.Style({
    zIndex:1,
    image: new ol.style.RegularShape({
      radius: 10,
      radius2: 5,
      points: 5,
      fill: new ol.style.Fill({ color: 'blue' })
    })
  });
  var overlay = new ol.layer.Vector({ source: new ol.source.Vector() });
  overlay.getSource().addFeature(pt);
  overlay.setMap(map);


	source.once('change',function(e) {
    if (source.getState() === 'ready'){
      getMinMax (source.getFeatures()[0]);
      createLegend ();
      profil.setGeometry(source.getFeatures()[0]);
		}
  });
  // Show a popup on over
	profil.on(["over","out"], function(e){
    if (!pt) return;
		if (e.type=="over"){
      // Show point at coord
			pt.setGeometry(new ol.geom.Point(e.coord));
			pt.setStyle(style);
		} else {
      // hide point
			pt.setStyle([]);
		}
  });

  /** Get the coordinate at a distance from the start
   * @param {number} r distance from the start
   * @param {Array<Array<coordinate>>} seg if provided fill the segment concerned
   * @return {ol.coordinate}
   */
  ol.geom.LineString.prototype.getCoordinateAtSeg = function (r, seg) {
    var c, d;
    if (r < 1e-10) {
      if (seg)  {
        c = this.getCoordinates();
        seg[0] = c[0];
        seg[1] = c[1];
      }
      return this.getFirstCoordinate();
    }
    if (this.getLength()-r < 1e-10) {
      if (seg) {
        c = this.getCoordinates();
        seg[0] = c[c.length-2];
        seg[1] = c[c.length-1];
      }
      return this.getLastCoordinate();
    }
    if (!seg) seg=[];
    var s = 0;
    var coord = this.getCoordinates();
    for (var i=1; i<coord.length; i++) {
      d = ol.coordinate.dist2d(coord[i-1], coord[i]);
      if (s+d >= r) {
        var p0 = seg[0] = coord[i-1];
        var p1 = seg[1] = coord[i];
        d = ol.coordinate.dist2d(p0,p1)
        return [
          p0[0] + (r-s) * (p1[0]-p0[0]) /d,
          p0[1] + (r-s) * (p1[1]-p0[1]) /d
        ];
      }
      s += d;
    }
  };

  // Define a new legend
  function createLegend () {
    var legend = window.legend = new ol.legend.Legend({ 
      style: function(f) {
        var dh = f.get('dh');
        return [ new ol.style.Style({
          fill: new ol.style.Fill({
            color: getColor(dh)
          })
        })];
      },
      textStyle: new ol.style.Text({
        font: '12px sans-serif',
      }),
      margin: 0,
      size: [10, 5]
    });
    map.addControl(new ol.control.Legend({ legend: legend, collapsible: false }));

    legend.addItem();
    legend.addItem( { title: ' Altitude ' } );
    legend.addItem();
    legend.addItem();
    legend.addItem();
    legend.addItem({ title: '  '+ max+'m', properties: { dh: 255 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 224 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 192 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 160 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 128 }, typeGeom: 'Polygon'});
    legend.addItem({ title: '', properties: { dh: 96 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 64 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'  '+ min+'m', properties: { dh: 32 }, typeGeom: 'Polygon'});
    legend.addItem({ title:'', properties: { dh: 0 }, typeGeom: 'Polygon'});
  }
</script>

</body>
</html>
