### ISSUE TITLE
PhotonSearch is not running under IE9. Any idea?

### ISSUE THREAD

**Issue by RalphLAtGitHub** [Viglino/ol-ext#67]
Ajax seems to be the issue. Replacing  the Ajax call at line 4203 by

`getRequest(url, 'q=' + data.q + '&limit=' + data.limit, function (r) { cback(r.features); }); `

with

    function getRequest (url, data, callBack) {
      var xRequest = new window.XDomainRequest();    
      xRequest.onload = function () { callBack(xRequest.responseText) };
      xRequest.onerror = function () { };
      xRequest.onprogress = function () { };
      xRequest.ontimeout = function () { };
      setTimeout(function () { xRequest.send(); }, 0);
      xRequest.open("GET", url);
      try { xRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded"); } catch (e) { }
      xRequest.send(data);
    };

doesn't solve the problem. The open request throws an "access denied" exception.

**Comment by Viglino** [comment]
Hi ,
It's a known bug on IE9. Just add this code in your HTML right after including jquery.
```
<!--[if lte IE 9]>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.3/jquery.xdomainrequest.min.js'></script>
<![endif]-->
```
I'va added the code on the example and it seems to work on IE9 (emulator).

**Comment by RalphLAtGitHub** [comment]
Hi Jean-Marc,
unfortunately your suggestion it is not running under my environment (AjaxTransport also uses XDomainRequest an this is not running as commented before). In my application I use a WinForms WebBrowser control and I am forced to establish the IE9 emulation to maintain the full functionality of the WebBrowser control. To solve the issue I handle the server request outside the browser in .NET via WebClient.DownloadString(uri) and give the result back to JS:

    searchResult = window.external.SearchPhoton(url + '?q=' + data.q + '&limit=' + data.limit);
    cback(JSON.parse(searchResult).features);

That works fine.
Thank a lot you for your efforts!
Ralph
