### ISSUE TITLE
DrawRegular condition option like in the ol.Interaction.Draw?

### ISSUE THREAD

**Issue by DmitrySavritsky** [Viglino/ol-ext#670]
Hello, is there any possibility to not handle some events in the DrawRegular interaction? There is a 'condition' option in the ol.interaction.Draw class, with the help of which I can indicate whether that event should be handled. For an example, I can skip the handle of the right click event on a map. Is there any possibility to do something similar for the DrawRegular interaction?

**Comment by Viglino** [comment]
There is no such option now.
I can see how to add it...

**Comment by DmitrySavritsky** [comment]
It will be very useful option, at least for me)

**Comment by Viglino** [comment]
I've pushed a new option to let you customize a condition on click event...

**Comment by DmitrySavritsky** [comment]
Thank you! And how can I get the updated version of DrawRegular? I need only to update package with "npm update ol-ext"? Or something else?

**Comment by Viglino** [comment]
It's not published yet...
To test it you can copy the Github ./src directory content in your node_module/ol-ext

**Comment by Viglino** [comment]
I've just published 3.2.7 on npm https://www.npmjs.com/package/ol-ext
You can now `npm update ol-ext`
