### ISSUE TITLE
Hpw to set the background of Multi Legend control

### ISSUE THREAD

**Issue by tongji1984** [Viglino/ol-ext#674]
Dear Sir:

Since the default background of the Multi Legend control is transparent, how can I set it into a while one?

Best regards,

**Comment by Viglino** [comment]
Hello
You just have to set it to the desired color in your css: 
```CSS
.ol-control.ol-legend {
  background-color: #fff;
}
```
If you want to modify the background of the legend on the canvas (when draw on map or print), you have to define a background color when creating (`textStyle` option, with a backgroundFill to the desired color)
```javascript
  var legend = new ol.legend.Legend({
    title: 'Legend',
    style: getFeatureStyle,
    textStyle: new ol.style.Text({
      font: '16px sans-serif',
      fill: new ol.style.Fill({
        color: '#333'
      }),
      backgroundFill: new ol.style.Fill({
        color: 'rgba(255,255,255,1)'
      })
    })
  })
  var legendCtrl = new ol.control.Legend({ 
    legend: legend
  });
```

**Comment by tongji1984** [comment]
Thank you! I have done!
