### ISSUE TITLE
PrintDialog + multi legend

### ISSUE THREAD

**Issue by MouradDz77** [Viglino/ol-ext#675]
I need help with multi legened + printdialog
![image](https://user-images.githubusercontent.com/40025893/136477772-741a3560-8d15-4d9a-8980-98681095bb05.png)

![image](https://user-images.githubusercontent.com/40025893/136477798-4ba6e92b-6971-4227-b9f7-654e826ab738.png)

**Comment by Viglino** [comment]
PrintDialog only use one legend, this means multi legend example that use more than one legend only print the first one...
