### ISSUE TITLE
SearchControl: avoid duplicate entries in the search results.

### ISSUE THREAD

**Issue by RalphLAtGitHub** [Viglino/ol-ext#68]
Just an idea for improvement of the drawList_ function:

    ol.control.Search.prototype.drawList_ = function (auto) {
    var ul = $('ul.autocomplete', this.element).html('');
    if (!auto) return;
    var self = this;
    var max = Math.min(self.get('maxItems'), auto.length);
    for (var i = 0; i < max; i++)
    {
        var newItem = self.getTitle(auto[i]);  
        if (i > 0 && newItem == self.getTitle(auto[i-1])) return;
        $("<li>").html(newItem)
            .data('search', auto[i])
            .click(function (e)
            {
            self.select($(this).data('search'));
            })
            .appendTo(ul);
    }
    };

**Comment by Viglino** [comment]
Hi,
I've added a function ol.control.Search#equalFeatures to test if 2 features are equal and remove duplicated consequential features.
@+
