### ISSUE TITLE
How to transform the GeoImage from 'EPSG:3857' to 'EPSG:4326'?

### ISSUE THREAD

**Issue by Liuzhizhiooo** [Viglino/ol-ext#683]
Following the [example](http://viglino.github.io/ol-ext/examples/layer/map.geoimage.html), I have finished my work.
The image could be shown correctly if I set the map view like this:
```js
new view({
  projection: "EPSG:3857",
  center: fromLonLat([104, 30])
})
```
And the GeoImageLayer is defined like this(transformPara contains the corresponding parameters):
```js
var imgLayer = new GeoImageLayer({
  name: "imageLayer",
  source: new GeoImageSource({
    url: imgPath,
    imageCenter: transformPara[0],
    imageScale: [transformPara[1], transformPara[2]],
    imageMask: imageCornerPnts.slice(0, 4),
    imageRotate: transformPara[3],
    projection: 'EPSG:3857',
  })
});
```
but how could I transform the GeoImageLayer from 'EPSG:3857' to 'EPSG:4326'?

**Comment by Viglino** [comment]
There is no reprojection. The image is supposed to be in the same projection as the view.
Image center and scale should be set in the view projection...

**Comment by Liuzhizhiooo** [comment]
> There is no reprojection. The image is supposed to be in the same projection as the view. Image center and scale should be set in the view projection...

Thanks for your reply sincerely.
So I have to define the reprojection by myself and add the reprojection hook?

**Comment by Liuzhizhiooo** [comment]
> Here is an example: https://codepen.io/viglino/pen/LYjZZBO

I have tried this solution, but it seems it doesn't work well.
Here is the condition:
Given the `EPSG:4326` coordinates of a satellite image‘s four corner points, it's easy to get define the corresponding Polygon and draw it on the map whose projection is `EPSG:4326` as well.
Then, calculate the transform parameters (i.e. `imageCenter`, `imageScale` and `imageRotate`) and define the GeoImageLayer.
But the result shows that these three parameters are not enough to depict the affine transformation from pixel coordinate system to `EPSG:4326` coordinate system. Maybe this transform need a `shear` parameter?
Here is the results(the GeoImageLayer is narrowed  a bit to show the difference)
![GeoImage](https://user-images.githubusercontent.com/51073637/137907807-2e5ec6c2-2300-41e0-92ab-828e047a4d92.png)

**Comment by Liuzhizhiooo** [comment]
> EPSG:4326 is a spherical system (lon/lat are in degree, not meter)... This causes huge surface deformations on our latitude... Mercator also has deformations but the scale x /scale y is the same on small surfaces, which makes it more suitable to place images on it...
> 
> ## Mercator
> ![image](https://user-images.githubusercontent.com/7868217/137940311-1b1dd353-3e79-46e3-924f-fba3d3a4cd4b.png)
> 
> ## EPSG:4326
> ![image](https://user-images.githubusercontent.com/7868217/137940077-fd6e6286-e6b9-4d9a-92f6-0358c0230daa.png)

Thank you very much for your prompt reply!
I'll try something else to fix it!
