### ISSUE TITLE
Cannot resolve dependency 'ol-ext/filter/Crop'

### ISSUE THREAD

**Issue by vijaygrg27** [Viglino/ol-ext#684]
I am getting this error. How to resolve it?

**Comment by Viglino** [comment]
If you want to import classes from ol-ext, you have to use the module version of the lib (not the js version).
1. Remove the js version from the index.html
2. install the module version `npm install ol-ext`
3. keep the css directly in your html or better import it in the main js file from the module `import 'ol-ext/dist/ol-ext.css'`
4. import ol-ext classes in your js `import Crop from 'ol-ext/filter/Crop'`

**Comment by Viglino** [comment]
It seems you have an error with python:
![image](https://user-images.githubusercontent.com/7868217/138224294-946d1b88-9df7-412b-a221-f852cc1ed43a.png)
Try to install it using https://github.com/nodejs/node-gyp#on-windows

**Comment by vijaygrg27** [comment]
There was a dependencies issue. I have changed ol version 5.0.3. Now it's working fine.

Thanks a lot for your support. 

![image](https://user-images.githubusercontent.com/77456706/138226472-c5a51171-34f4-4538-ba3a-906a45b9d49d.png)
