### ISSUE TITLE
error in cdn file ol-ext.min.js

### ISSUE THREAD

**Issue by 3rm4c** [Viglino/ol-ext#687]
Hi,
when used cdn linked ol-ext.min.js create error in LayerSwitcher button else when use download version it's ok

<script type="text/javascript" src="https://cdn.rawgit.com/Viglino/ol-ext/master/dist/ol-ext.min.js"></script>

**Comment by Viglino** [comment]
The file is used in the example page and I don't notice any such a behavior.
