### ISSUE TITLE
control.dialog missing closeBox and buttons

### ISSUE THREAD

**Issue by ahaufstop** [Viglino/ol-ext#689]
Between version 3.2.13 and version 3.2.14 the closeBox and the labelled button no longer appear on the control.Dialog.

I tried 3.2.15 and the problem still exists.
The form displays but i cannot then hide the form.

Here is the code i am using;
 ```
    var dialogPrompt= new ol.control.Dialog();
     dialogPrompt.setContent({
       content: helpStr + imgStr, 
       title: '0 (1761x2159)',
       closeBox: true, buttons:{ cancel:'Close' }
     });
     map.addControl(dialogPrompt);
     map.addControl( new ol.control.Button ( {html: '<i class="fa fa-question "></i>', className: "help", title: "Help", handleClick: function(){dialogPrompt.show()} }));
```
<3.2.13 
![Screenshot from 2021-11-08 10-24-55](https://user-images.githubusercontent.com/15824933/140725666-5cd8cabe-3b88-4d68-9814-216f2b558d8c.png)
> 3.2.13
![Screenshot from 2021-11-08 10-24-12](https://user-images.githubusercontent.com/15824933/140725669-6f223846-ebb9-4b18-959b-f3bba4bb0ad2.png)

**Comment by Viglino** [comment]
The last commit should fix the bug.

**Comment by ahaufstop** [comment]
Copid the min.js locally and tested.
All looks good .
Thank you
