### ISSUE TITLE
map.style.chart+text.html can not support bar chart type

### ISSUE THREAD

**Issue by dyh333** [Viglino/ol-ext#69]
![image](https://user-images.githubusercontent.com/1221313/34591626-df74a23e-f1f9-11e7-907c-838951eb571b.png)

as the picture, the bar chart type show text is not in right position. hope fix it. thanks.

**Comment by Viglino** [comment]
Hi,
The text is not intended to be used with bar chart but with pie chart thus the text is placed around a circle.
On bar chart the placement is quite more difficult to not overwrite the labels.
@+
