### ISSUE TITLE
ol-ext Control Legend display

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#694]
Currently the Legend display is using the feature to add and display

but i was wonder if i want to display instead of the feature that is added to map, i wish to do another legends that is found on https://www.openstreetmap.org/key.

wonder how to put the subset of the key above of the url to display?

**Comment by Viglino** [comment]
It's not possible yet but I plan to add possibility to set legend items such as images or other legends associated to a layer.
No time to do it yet but I'll try to implement it asap.

**Comment by ngjiajunsg** [comment]
ok thanks.

**Comment by jamador-usgs** [comment]
Great to hear. I was just working on upgrading our library from 3.1.14 to 3.2.4 but was having issues with the legend component.

**Comment by Viglino** [comment]
@ngjiajunsg I've added an ol/legend/Image item to add a legend image
See: https://viglino.github.io/ol-ext/examples/legend/map.control.legend.image.html

You can also link the legend to a layer to have it visible when the layer is.
See: https://viglino.github.io/ol-ext/examples/legend/map.control.legend.layer.html
