### ISSUE TITLE
popup.feature

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#696]
Hi,

i have two questions on current popup.feature 

1. does it has an ability to display only certain feature information. (Example: i want only to display **Name and Owner** information for feature 1, while Feature 2 will display **Name, Owner and Area**)

2. if feature 1 and feature 2 has the some same feature information, it will display only display the same feature information instead of the full feature information. (Example: i Click Feature 1, it will display (**ID, Name, Color, Owner**), after that i click on Feature 2, it only display (**Name, Owner**) not sure why it this like that?)

example:
Feature 1:  **ID, Name, Color, Owner**
Feature 2: **Name, Owner, Area**

Code that i use

// Select  interaction
  var select = new ol.interaction.Select({
    hitTolerance: 5,
    multi: true,
    condition: ol.events.condition.singleClick
  });
  map.addInteraction(select);

var popup = new ol.Overlay.PopupFeature({
    popupClass: 'default anim',
    select: select,
    canFix: true,
    template: {
        title: 
          // 'nom',   // only display the name
          function(f) {
            return f.get('name');
          }
    }
  });
  map.addOverlay (popup);

**Comment by Viglino** [comment]
You have to use the `template` option as a function: 
```javascript
var popup = new ol.Overlay.PopupFeature({
  popupClass: 'default anim',
  select: select,
  canFix: true,
  template: function(f) {
    // Test feature
    if (...) {
      return {
        title:  function(f) {
          return f.get('name');
        },
        attributes: ['ID', 'Name', 'Color', 'Owner']
      }
    } else {
      return {
        title: function(f) {
          return f.get('name');
        },
        attributes: ['Name', 'Owner', 'Area']
     }
  }
});

```

**Comment by ngjiajunsg** [comment]
hi Viglino,

i try the above code but i only can display the 'Name' only the rest of the information is not display

**Comment by Viglino** [comment]
Actually, the attributes option must be an object: 
```javascript
var popup = new ol.Overlay.PopupFeature({
  popupClass: 'default anim',
  select: select,
  canFix: true,
  template: function(f) {
    // Test feature
    if (...) {
      return {
        title:  function(f) {
          return f.get('name');
        },
        attributes: { ID: true, Name: true, Color: true, Owner: true }
      }
    } else {
      return {
        title: function(f) {
          return f.get('name');
        },
        attributes: { Name: true, Owner: true, Area: true }
     }
  }
});
```

**Comment by ngjiajunsg** [comment]
Thanks Viglino, 

can i check for the attributes are we able to change the Display Name?


For example : 

Feature 1: ID, Name, Color, Owner
Feature 2: Name, Owner, Area

i want to display the Name for Feature 1 to **Company Name** instead of **Name** and display Area for Feature 2 as **States** instead of **Area**

**Comment by Viglino** [comment]
Use TemplateAttributes to customize the attributes: see http://viglino.github.io/ol-ext/doc/doc-pages/global.html#TemplateAttributes
```javascript
  template: function(f) {
    // Test feature
    if (...) {
      return {
        title:  function(f) {
          return f.get('name');
        },
        attributes: { 
           ID: true, 
           Name: { title: 'Company Name' }, 
           Color: true, 
           Owner: true 
        }
      }
    } else {
      return {
        title: function(f) {
          return f.get('name');
        },
        attributes: { 
          Name: { title: 'Company Name' }, 
          Owner: true, 
          Area: { title: 'States ' }
        }
     }
  }
```

**Comment by ngjiajunsg** [comment]
Hi Viglino,

Sorry to ask what if i have attributes list how should i do it??

Feature 1: ID, Name, Color, Owner.Address, Owner.Country
Feature 2: Name, Owner, Area.Name, Area.PostalCode

Data As below
Feature 1: {ID:1, Name: 'Facebook', Color: 'Blue', Owner: {Address:'1 Hacker Way Menlo Park', Country: 'US'}
Feature 2: {Name: 'Home To Facebook', Owner: 'NGJIAJUNSG', Area {Name:'CA', PostalCode: '92025'}

base on the above example the Owner in Feature 1 is a array list and Area also too

i not sure issit like this

template: function(f) {
    // Test feature
    if (...) {
      return {
        title:  function(f) {
          return f.get('name');
        },
        attributes: { 
           ID: true, 
           Name: { title: 'Company Name' }, 
           Color: true, 
           **Owner.Address: true, 
           Owner.Country: { title: 'Country' }** 
        }
      }
    } else {
      return {
        title: function(f) {
          return f.get('name');
        },
        attributes: { 
          Name: { title: 'Company Name' }, 
          Owner: true, 
          **Area.Name: { title: 'Area Name' },
          Area.PostalCode: { title: 'Area PostalCode' }**
        }
     }
  }

**Comment by Viglino** [comment]
Attribute as objects are not supported.
You can format an attribute to show what's in but only one at time:
```javascript
attributes: {
  Name: { title: 'Company Name' },
  Owner: true,
  Area: { title: 'Area', format: function(att) { return att.Name + ' ('+att.PostalCode+')'} },
}
```

**Comment by ngjiajunsg** [comment]
> ```js
> format: function(att) { return att.Name + ' ('+att.PostalCode+')'}
> ```


i try this seem does not work..
anyway i work around this code and create individual variable to store and display it
