### ISSUE TITLE
Question/ address Search

### ISSUE THREAD

**Issue by Shion1314** [Viglino/ol-ext#697]
Hi, I'm trying to add the address search option for the open layer, not just typing in address but also allowing address search using latitude and longitude. Is there any advice?  
PS.  I am using multiple OSM base maps.

**Comment by Viglino** [comment]
Have you tried SearchGPS control?
> https://viglino.github.io/ol-ext/examples/search/map.control.searchgps.html

**Comment by Shion1314** [comment]
Thank you for answering, I figure it out. Also, how would I use the draw interaction in the open layer using javascript?
I am trying to allow users to draw a certain shape area and allow them to download the data within that shape area.
