### ISSUE TITLE
Make edit handles in transform parallel to the box

### ISSUE THREAD

**Issue by vijayprwyd** [Viglino/ol-ext#699]
First of all thanks very much for this amazing library. This is not an issue but a question.

I render some shapes in the image . Viewport would be initially rotated by some angles based on the API response . 
Now to edit these shapes I am using `Transform from 'ol-ext/interaction/Transform';`

And I have set the `enableRotatedTransform` property to `true` . Initially the handles are located at the four corners of the rectangle which is what I wanted. But when I rotate the image ( loading is exactly similar to a ,map ) through Alt + shift + click the handles are now not located at the rectangle cordinates. The handles are based on upright rotation .  What should we do so that the handles are always located at the four corners of the rectangle? 

I went through this documentation and tried several attributes but couldn't solve it. https://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html

![translate-and-scale-3](https://user-images.githubusercontent.com/57066740/141963841-c008f529-b4ee-498e-bb9e-fb7bd44e535a.gif)

**Comment by Viglino** [comment]
Default behavior (`enableRotatedTransform` = false) keep the box orientation to the view axes (and rotate with the view)
Setting `enableRotatedTransform` to true will force the box to keep window orientation (and rotate counterwise with the view).
You should use true to keep transform to the view axes.
You can also try the new `keepRectangle` option set to true to enable rectangle transform even when the rectangle itself is rotated (only avaliable for rectangles).

**Comment by vijayprwyd** [comment]
Thanks very much . Exactly what I was looking for . Closing the issue .
