### ISSUE TITLE
Modify, Delete, Move, Rotate existing features

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#70]
By Looking at the example at:
http://viglino.github.io/ol-ext/examples/map.interaction.drawtouch.html

it only does adding of new features.  How would I handle modifying (Modify, Delete, Move, Rotate, Clone, etc. etc.) existing features by using it on a Touch  Device?
  
Also, is this compatible with Openlayers 4?

**Comment by Viglino** [comment]
Hi,
The interaction only handle the drawing. You can use the default ol interactions for modifying or develop a new one. I've got one to move points but it's quite simple as you just have to push a button to say "move here" to place the point on the crosshair.
All function are compatible with ol4, if not it's a bug 😄.
