### ISSUE TITLE
Html form 'breaks' enter key for GeoBookmark

### ISSUE THREAD

**Issue by Ben3d1k7** [Viglino/ol-ext#700]
Hey,
my second issue today :)
I experienced a potentially unwanted behaviour in GeoBookmark when an ol.Map is nested within a html form.
I created a [jsfiddle](https://jsfiddle.net/Ben3d1k7/7gLxb3ta/21/) for you with a minimal example which is based on your [GeoBookmark example](https://viglino.github.io/ol-ext/examples/control/map.control.geobookmark.html).
If one adds a new Bookmark via pressing the enter key the first entry in the bookmark list is being deleted. If the bookmark list is empty it is impossible to add a new bookmark (with the enter key) due to the newly added bookmark being deleted right after adding it. The issue seems to be that pressing enter while being in html form triggers the delete button in the bookmarks list. Adding a hidden submit button to the form which is doing nothing prevents this behaviour.

(Also it would be nice to be able to customize the text for the delete button which currently is 'Suppr.')

Thanks!

**Comment by Viglino** [comment]
Last commit should prevent default behavior on forms.

**Comment by Viglino** [comment]
I've also added a `deleteTitle` option to let you customize the delete button title...
