### ISSUE TITLE
Edited shape disappears in keepRectangle mode after dragging the corner handles

### ISSUE THREAD

**Issue by vijayprwyd** [Viglino/ol-ext#701]
My  transform interation :

```js

    const newTransformInteraction = new Transform({
      enableRotatedTransform: true,
      hitTolerance: 2,
      translateFeature: true, // Enables translation whem mouse drag on the shape, if false translation can be done only by dragging the center point
      scale: true,
      rotate: true,
      translate: true,
      stretch: true,
      selection: true,
      keepAspectRatio: () => true,
      keepRectangle: true,
    });

```

When i drag along one of the four corners of the rectangle , after the drag shape gets deleted . I haven't added any interactions or logic for listeners . This issue doesn't happen when `keepRectangle` is `false` or i stretch the rectangle not through the corners

![openlayers-bug](https://user-images.githubusercontent.com/57066740/142595756-6b8d14d8-4062-478e-bde7-d8bdddd0964c.gif)

**Comment by vijayprwyd** [comment]
@Viglino  I definitely don't have an idea behind the Math of the transformation. Just out of curioisity cloned this repo and tried to recreate the behaviour to ensure that I am not doing anything wrong in my project .This is reproducible in the examples 
`examples\interaction\map.interaction.transform.html` as well. 
https://github.com/Viglino/ol-ext/blob/master/src/interaction/Transform.js#L743
Here pointA1 was passed as `[undefined, undefiend]` due to which the `movePoint` function returned `[NaN, NaN]`
When I wrap that condition with :  
```js
    if(pointA1[0] !== undefined && pointA1[1] !== undefined) {
        [g2[8], g2[9]] = movePoint(pointA1, displacementVector);
      }
```
this issue is resolved . Again this is not the solution I propose :) but just to notify you if that helps to save some of your time by any chance.

**Comment by Viglino** [comment]
I think your rectangle polygons are not closed (5 points withe the last one = first one).
That's why coordinates are undefined.
I've added a test to verify the rectangles have 5 points (otherwise use standard transform).

Setting scale to false will also prevent scaleX / scaleY (stretch)...
Ii have no use case when you want to allow scaleX and scaleY but not scaleX+scaleY...

**Comment by vijayprwyd** [comment]
Yeah correct 👍🏻  The issue was that I was sending only four cordinates whereas it expects 5 ( where 1st coordinate = last ). Closing the issue . Thanks very much for the help.
