### ISSUE TITLE
 How do I calculate geopointResolution in pixels?

### ISSUE THREAD

**Issue by alenigrelli** [Viglino/ol-ext#702]
I'm guiding myself from issue #650 . I also want to calculate imagescale automatically.
 ```
// Pixel resolution 1px = res meter
var res = ol.proj.getPointResolution (map.getView (). getProjection (), 1, imageCenter, 'pixels'); 
```
It returns "NaN". What am I doing wrong?
I attach some screenshots

This is my projection.
![projection](https://user-images.githubusercontent.com/15861031/142643257-b5b83c30-ed4c-43ec-a018-2134fe3a1678.png)

**Comment by Viglino** [comment]
Why do you use 'pixels' in the function?

**Comment by alenigrelli** [comment]
https://openlayers.org/en/latest/apidoc/module-ol_proj_Units.html
https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.getPointResolution
the documentation allows to use it.
