### ISSUE TITLE
LayerSwitcher select Group recursive

### ISSUE THREAD

**Issue by luzhskij** [Viglino/ol-ext#703]
Hi! ol-ext - cool stuff.

But I got a problem. Partially, the issue is resolved using the code from this issue: https://github.com/Viglino/ol-ext/issues/434.

But here's the situation. There are several nested ol.layer.Group.
Group1, Group2, Group3. And some children: child1, child2.
![image](https://user-images.githubusercontent.com/7203449/143234859-d330f731-64be-4da3-bcdf-86a5482e218e.png)

If you select Group3, then Group2 will be selected, but not further.
If you select Group2, then Group1 and Group3 will also be highlighted.
At the same time, children do not stand out.
When Group1 is selected, everything will be highlighted (this is the behavior that should be when Group3 or Group2 is selected).

When selecting any child, everything is selected, even the second child (this is not good, the second child should not stand out).

Actually:
1) I do not understand how to make sure that when selecting any group (or child), all nested groups and children are selected (except for the case with children).
2) respectively, also when removing the selection.

https://codepen.io/luzhskij/pen/qBXzRLv

***
And the second moment, when I use the code from the question on the server, when selecting / deselecting the checkboxes are not updated until you collapse and expand the tree.
And the same is when using hiding fields (li.hidden), there is no update of the tree if it is not expanded / collapsed.
***
Thank you for the attention!

**Comment by Viglino** [comment]
Do you mean something like that ?
https://codepen.io/viglino/pen/PoKrmoR

**Comment by luzhskij** [comment]
> Do you mean something like that ?
> https://codepen.io/viglino/pen/PoKrmoR

This is great!
You are amazing:)
