### ISSUE TITLE
Set modify the center when scaling as default and the default behaviour as secondary option? [ol.interaction.Transform] 

### ISSUE THREAD

**Issue by DmitrySavritsky** [Viglino/ol-ext#704]
Hello, I'd like to know, how can I swap the default behaviour of the ol.interaction.Transform with the modifyCenter behaviour? For example, if I want to use current interaction default behaviour  when I press ctrl key and to apply scale & strech from the center as a default?

**Comment by Viglino** [comment]
There is no option to set the default behavior yet...
