### ISSUE TITLE
Options from TouchCursorSelect should be more openlayers like

### ISSUE THREAD

**Issue by domiSchenk** [Viglino/ol-ext#705]
We noticed that the options naming from TouchCursorSelect are not like standard openlayers.
It would be nice if the naming of the available options are the same (doesn't mean it should have all params like ol)
(public naming not the internal!).

```
options._filter           should be          options.filter


```

also if I'm correct, there is not filter parameter on getFeaturesAtPixel at least not public:
https://github.com/Viglino/ol-ext/blob/1de6e48aa8e9bb68f3fe84874618098cd42936b7/src/interaction/TouchCursorSelect.js#L76
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getFeaturesAtPixel

**Comment by Viglino** [comment]
Fixed in the last commit

**Comment by domiSchenk** [comment]
perfect, thank you
