### ISSUE TITLE
PopupFeature onshow 

### ISSUE THREAD

**Issue by alessiodl** [Viglino/ol-ext#707]
Hi, 
it would be useful to return something in the onshow function of the popup feature.
For instance the template object and the current feature with it attributes and geometry.

**Comment by alessiodl** [comment]
Little work-around found for this:

`
![Schermata 2021-12-01 alle 19 16 03](https://user-images.githubusercontent.com/6825193/144291002-e8736b71-2188-4cfb-9433-547dfb3f8084.png)
`
not exactly what I was looking for, but works quite well for my purposes. 
It would be nice if the function could access the data of the clicked feature without having to pass it through a 'fake' attribute. Something like 

`onshow: (layer, feature) => { ... }`

**Comment by Viglino** [comment]
There is a `select` event to be aware of current feature shown in the popup:
```javascript
popup.on('select', (e) => console.log(e.feature));
```

**Comment by alessiodl** [comment]
Hi, 

Using the "on select" event requires that the select option is enabled. It is a valid option in many cases, but sometimes I prefer to manage the feature selection differently.

Thank you for your answer :-)
