### ISSUE TITLE
PopopFeature buttons 

### ISSUE THREAD

**Issue by alessiodl** [Viglino/ol-ext#708]
Hi,

By default, at the bottom of the popup, the zoom to feature button is created.
Is it possible to define custom buttons and functions in this position?

**Comment by Viglino** [comment]
You can add your own html in the popup element using the `getElement()` method:
```javascript
const btn = document.createElement('BUTTON');
btn.innerText = 'hello';
popup.getElement().appendChild(btn);
```

**Comment by alessiodl** [comment]
Thank you, very helpful!
