### ISSUE TITLE
Update Doc Class Transform

### ISSUE THREAD

**Issue by aparzi** [Viglino/ol-ext#709]
Hello to all,
Documentation for the Transform class is missing documentation for the getActive method.
Can I open a pull request?

Thanks

**Comment by Viglino** [comment]
GetActive is an interaction method inherited from the ol lib and is documented in [ol doc](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Interaction-Interaction.html#setActive)
ol-ext only documents his own methods.

**Comment by aparzi** [comment]
@Viglino Perfect, thanks.
