### ISSUE TITLE
Disable ol.control.Button

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#71]
How would we go about to disable a `ol.control.Button` during runtime?

**Comment by Viglino** [comment]
Hi,
There is a `setDisable` method on [ol.control.Toggle](http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Toggle.html#setDisable__anchor) but not on the [ol.control.Button](http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Button.html).
It's up to you to know what to do in the handleClick function.
@+
