### ISSUE TITLE
Trying to use cspline() method 

### ISSUE THREAD

**Issue by espejor** [Viglino/ol-ext#710]
Hello:
I am trying to use the ol-ext cspline () method but I am not able to understand how to include it in my project.
I have done npm ol-ext and have the files in node_modules folder but cspline () does not belong to a module.
How does it work?

**Comment by Viglino** [comment]
You have to import CSpline.js then the functions are available 
- on coordinates using the imported function 
- or directly on geometry:
```javascript
import cspline from 'ol-ext/render/Cspline'

// Calculate cspline on coordinates
const spline = cspline(coords);
// or get a new spline geometry 
const splineGeom = geom.cspline();
// or using a feature geometry
const splineGeom = feature.getGeometry().cspline();
```

**Comment by espejor** [comment]
Thank you very much for answering so quickly.
When I introduce that import line I get this warning message 

(sorry for the spanish language of the message)
_No se encontró ningún archivo de declaración para el módulo 'ol-ext/render/Cspline'. 'c:/Users/espej/OneDrive/Documents/Angular/OpordEasy/node_modules/ol-ext/render/Cspline.js' tiene un tipo "any" de forma implícita.
  Pruebe "npm i --save-dev @types/ol-ext" si existe o agregue un nuevo archivo de declaración (.d.ts) que incluya "declare module 'ol-ext/render/Cspline';"_

and the 
_feature.getGeometry().cspline ()_ 
instruction gives an error _"La propiedad 'cspline' no existe en el tipo 'Geometry'.ts(2339)"_

**Comment by Viglino** [comment]
That's a typescript issue...
You can try to add typescript definition: https://www.npmjs.com/package/@siedlerchr/types-ol-ext
Using the imported function should work: `const spline = cspline(coords);`
Or perhaps you can use @ts-expect-error to prevent the error on the line
```javascript
// @ts-expect-error
feature.getGeometry().cspline ()
```

**Comment by espejor** [comment]
Thanks.
I have reinstalled in the @types folder and precisely the Cspline.d.ts file is the only one that does not appear in the list of files in the render folder.
There is also no installation error for that file.
I do not know what is the problem

**Comment by Siedlerchr** [comment]
I  now remember why these types were missing... 
The problem is that I have to augment (declaration merging) the existing geometry types and I am not yet getting the example to work. Any help appreciated
https://github.com/Siedlerchr/types-ol-ext/pull/71

**Comment by espejor** [comment]
Thanks for your concern. Unfortunately, I am not prepared to offer my help as I do not have enough knowledge of TS.
I'll wait for your next code update

**Comment by Viglino** [comment]
@Siedlerchr Have you tried this ? 
https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by Siedlerchr** [comment]
Yes. And I got it to compile now. but now I still the runtime error..
eomType.cspline is not a function
```ts
    const geomType = f.getGeometry() as Geometry;
    console.log(geomType?.getType()) //returns LineString
    //cspline is not a function runtime error
    const csp = geomType.cspline(opt) as LineString;

```

**Comment by Siedlerchr** [comment]
With help from @sanak the types are now implemented
