### ISSUE TITLE
Problem with DrawRegular when custom geometry name 

### ISSUE THREAD

**Issue by nicolo73** [Viglino/ol-ext#711]
Hi Jean-Marc,
I think there is a problem when we have custom geometry name.
https://github.com/Viglino/ol-ext/blob/66aee1c92768a0fe2483ef7ed75fafd1b6195a05/src/interaction/DrawRegular.js#L247

```
if (this.geometryName_) f.setGeometryName(this.geometryName_)
  //f.setGeometry (g);
  if (g.getType()==='Polygon') f.getGeometry().setCoordinates(g.getCoordinates());
```      

In my case, I have a exception because `setCoordinates` is called on `undefined`.
Indeed `f.getGeometry()` return undefined after the geometryName is updated.
I think the comment should be removed to update the geometry after geometryName  is changed.
I'm using:
"ol": "6.9.0",
"ol-ext": "3.2.16",

Thanks again for this great lib I'm using massively !
Regards,
Nicolas

**Comment by Viglino** [comment]
I've fixed the issue in the last commit to take the geometry name into account when the feature is created.

**Comment by nicolo73** [comment]
Great thanks!
Nicolas
