### ISSUE TITLE
Cannot collapse LayerSwitcher if collapsed:false on Android Chrome

### ISSUE THREAD

**Issue by computerchemist** [Viglino/ol-ext#712]
OL 6.9.0, OL-EXT 3.2.16
Cannot collapse LayerSwitcher if collapsed:false on Android Chrome 96.0.4664.92 running on Huawei 30 (MAR-LX1A) Android 10.0.0.491.
If I set collapsed:true then I can click on the layer icon and expand/collapse with no problems, but if set to false it starts as expanded and will not collapse. 
This affects the examples in the demos too. I am not sure if this is just an issue with this phone but I seem to recollect it with previous phones too.

**Comment by Viglino** [comment]
I've pushed a fix in the last commit.
It should work now...

**Comment by computerchemist** [comment]
Thanks, I can confirm this has fixed the problem, that was fantasticality quick turnaround!
