### ISSUE TITLE
Node-sass 7.0.0 error on compile

### ISSUE THREAD

**Issue by mdellanave** [Viglino/ol-ext#713]
If I try to import ol-ext.css in my own style.scss I have an 
_Internal Error: Incompatible units: 'em' and '%'._

due to the min function of this class

```
.ol-wmscapabilities .ol-url input {
  width: calc(100% - 10em);
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  min-width: min(100%, 20em);
}
```

resolved using Min with the first char upper case

**Comment by Viglino** [comment]
It seems the css value is min()
See: https://www.w3.org/TR/css-values-4/#comp-func
or https://developer.mozilla.org/fr/docs/Web/CSS/min()

**Comment by mdellanave** [comment]
Yes it is, sass has its own min and max functions that override the min and max css standard functions.
Unlike the latter, the sass functions fails if there are mixed units.

Sass is case sensitive but css not so using Min insteaf of min will make the sass compiler happy and the css still works.
