### ISSUE TITLE
Importing Profile control into Angular application

### ISSUE THREAD

**Issue by NevenD** [Viglino/ol-ext#714]
Hi,

I have an question regarding ol-ext package, to be more precise I'm interesting in integrating **Profile map control** into current Angular project but to be honest I don't know how should I import?

Should I start like this ?

```
import Profile from 'ol-ext/control/Profile';
reliefeProfile!: Profile = new Profile()
```

or should I take another approach? Can you please provide me some short example of implementation

**Comment by Viglino** [comment]
You can import the control as any other ol control to add it to the map:
```javascript
import Profile from 'ol-ext/control/Profile';
const reliefeProfile : Profile = new Profile();
map.addControl(reliefeProfile);
```

**Comment by NevenD** [comment]
Thank you :)
