### ISSUE TITLE
SearchGPS target

### ISSUE THREAD

**Issue by MouradDz77** [Viglino/ol-ext#715]
var searchGPS = new ol.control.SearchGPS({
    className:'ol-searchgps',
    target:$("#SearchGPS > div").get(0)
});
map.addControl(searchGPS);

searchGPS.on('select', function (e) {
    // console.log(e);
    map.getView().animate({
        center: e.search.coordinate,
        zoom: Math.max(map.getView().getZoom(), 18)
    });
});
if i specifed target in searchgps i have this message :
"Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at ol.control.SearchGPS._createForm (ol-ext.js:12818)
    at new ol.control.SearchGPS (ol-ext.js:12734)"

**Comment by Viglino** [comment]
Fixed in the last commit...

**Comment by MouradDz77** [comment]
thank you

**Comment by MouradDz77** [comment]
i changed this  : 
// DMS switcher
  ol.ext.element.createSwitch({
    html: 'decimal',
    after: 'DMS',
   change: function(e) {
      if (e.target.checked) this.element.classList.add('ol-dms');
      else this.element.classList.remove('ol-dms');
    }.bind(this),
    parent: this.element
  });
in this : 
// DMS switcher
  ol.ext.element.createSwitch({
    html: 'decimal',
    after: 'DMS',
    on: { change: function(e) {
      if (e.target.checked) this.element.classList.add('ol-dms');
      else this.element.classList.remove('ol-dms');
    }.bind(this) },
      parent: this.element
  });
