### ISSUE TITLE
How to animate feature in TypeScript?

### ISSUE THREAD

**Issue by logue** [Viglino/ol-ext#719]
I'm trying to animate a feature using TypeScript, but I get an error saying that animeteFeature doesn't exist in VectorSource and the build doesn't work.

As far as I can see from the manual, the following TypeScript seems to be the following source, but in reality it does not work because there is no method called animateFeature in ol.layer.vector (or ol.Map).

https://viglino.github.io/ol-ext/examples/animation/map.featureanimation.html

```
import Map from 'ol/Map';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';

const map = new Map({
 ...
});

const vector = new VectorLayer({
   source: new VectorSource()
});
vector.setMap(map);

map.on('singleclick', e => {
  let f: FeatureLike;
  let revers = false;
  map.forEachFeatureAtPixel (e.pixel, feature => {
    f = feature;
      return true;
    });
   if (!f) {
     return;
   }
   vector.animateFeature(f, [some Animation]);
});
```

How should I write it in TypeScript?

**Comment by Siedlerchr** [comment]
You need to impot the additions for module + interface merging:
```
import 'ol-ext/render/AnimExtent';
import featureAnimation from 'ol-ext/featureanimation/FeatureAnimation'; 
```

**Comment by logue** [comment]
I get the following error:
```
Porperty 'animateFeature' does not exists in 'VectorLayer<VectorSource<Geometry>>'
```
I can't find a method called animateFeature by looking at the documentation on the ol side, but I don't know what's wrong.

**Comment by Siedlerchr** [comment]
Hi, if you install the type definitions from here https://www.npmjs.com/package/@siedlerchr/types-ol-ext it should work

**Comment by logue** [comment]
@Siedlerchr
I've tried it, but it's a bit difficult to use because ts2345 is occurring frequently (eg autoPan and autoPanAnimation are not in the Popup options), probably because some properties are not supported.

**Comment by Siedlerchr** [comment]
@logue  I am preparing a fix.  Can you please open an issue here with any other things you encounter ? https://github.com/Siedlerchr/types-ol-ext

**Comment by Siedlerchr** [comment]
I've just pushed 1.6.1 to npm which fixes the popup options
