### ISSUE TITLE
Grid Reference is broken in OpenLayers6.10

### ISSUE THREAD

**Issue by logue** [Viglino/ol-ext#721]
After upgrading to OpenLayers 6.10, the drawing of the Grid Reference has become strange.
The display order is in the back, and the scale is also strange.

Also, the position of the scale slider etc. will be incorrect and will not be displayed.

It is also reproduced on the demo site.
https://viglino.github.io/ol-ext/examples/canvas/map.control.gridreference.html

By the way, is it possible to change the start character?
Starting from minus like "-C -B -A A B C", starting from the middle like "7 8 9", etc.

**Comment by Viglino** [comment]
It seems ol v6.10 has broken css for the FixedOverlays...
Last commit should fix the bug.

**Comment by Viglino** [comment]
By the way I've added a getHIndex and getVIndex to let you set your own index function...
```javascript
var ref = new ol.control.GridReference({
  extent: [ -550000, 5250000, 850000, 6650000 ],
  size: [10,12],
  target: document.querySelector(".options div"),
  source: vectorSource,
  property: "commune",
  sortFeatures: sort,
  indexTitle: title
});
// Default index
ref.getVIndex = function (index) {
  return index;
};
ref.getHIndex = function (index) {
  return String.fromCharCode(65 + index);
};
// add control
map.addControl (ref);
```
