### ISSUE TITLE
Canvas ol-fixedoverlay behave strange in Openlayers v6.10.0

### ISSUE THREAD

**Issue by regita96** [Viglino/ol-ext#722]
The previous Ol-ext @3.2.13 has been deleted from GitHub repository. 
Now using Ol-ext @3.2.19 with Openlayers v6.10.0 or whatever version doesn't show all the features above the map canvas.
Every time, 'canvas.ol-fixedoverlay' is created, all the controls are disappear.
If 'canvas.ol-fixedoverlay' is deleted, then the controls start appear.

**Comment by Viglino** [comment]
It seems ol v6.10 has broken css for the FixedOverlays...
Last commit should fix the bug.

**Comment by regita96** [comment]
it works now, thanks
