### ISSUE TITLE
ol.ext FontSymbol offset X & Y not working

### ISSUE THREAD

**Issue by jeromeBor** [Viglino/ol-ext#724]
I'm trying to make an offset icon on my regular icon, like a status bullet on my style of my feature.

```
  this.iconStyle = [
      new ol.style.Style({
        image: new ol.style.FontSymbol({
          form: 'marker',
          radius: 25,
          fill: new ol.style.Fill({
            color: 'white'
          })
        }),
        text: new ol.style.Text({
          text: '\uF0D1',
          font: '900 22px "Font Awesome 5 Free"',
          offsetY: -2,
          fill: new ol.style.Fill({
            color: '#06305c'
          })
        })
      }),
     
      new ol.style.Style({
        image: new ol.style.FontSymbol({
          form: 'circle',
          radius: 10,
          offsetX: 17,
          offsetY: -20,
          fill: new ol.style.Fill({
            color: 'green'
          })
        }),
        text: new ol.style.Text({
          text: '30m',
          offsetY: -20,
          offsetX: 17,
          fill: new ol.style.Fill({
            color: 'white'
          })
        })
      })
    ]
```

 [Here is result  of what my app show](https://i.stack.imgur.com/ETZB4.png)

As you can see, the text of openlayer Style is correctly displayed with the good offest, but the fontSymbol circle doesnt seems to get the offset I wrote.

Here is the API for fontSymbol of ol.ext : https://viglino.github.io/ol-ext/doc/doc-pages/ol.style.FontSymbol.html

What am I doing wrong ?

NB : https://viglino.github.io/ol-ext/examples/style/map.style.font.html the "offset" tickbox also seems not to work.

**Comment by Viglino** [comment]
It seems something has change in the and ol@v6 use a displacement.
The last commit should fix the bug. 
Now FontSymbol offset use the displacement with ol>v6.
