### ISSUE TITLE
ol-ext: Edit bar active button

### ISSUE THREAD

**Issue by dmrdeveloper** [Viglino/ol-ext#725]
Is it possible on the Edit bar, Select button not to be active when window loads? Default state would be edit bar with no button activated.

**Comment by Viglino** [comment]
When created the Edit bar has a default Select control active with an autoActivate option, ie. it will activate when no other active.
You have to change this behavior :
```javascript
var editBar = new ol.control.EditBar(();
// Get the selection control (current active control)
var select = editBar.getActiveControls()[0];
// Remove autoActivate option
select.set('autoActivate', false);
// De-activate it
select.setActive(false);
// Add control to the map
map.addControl(editBar);
```

**Comment by dmrdeveloper** [comment]
That works. Thank you very much for your helpful answer!
