### ISSUE TITLE
Notification documents hideOnClick and closeBox params do not work

### ISSUE THREAD

**Issue by alexgao1** [Viglino/ol-ext#731]
According to the [documentation](https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Notification.html), Notification can receive `hideOnClick` and `closeBox`.  

The class does [not appear to accept those as options](https://github.com/Viglino/ol-ext/blob/master/src/control/Notification.js) unlike [Dialog](https://github.com/Viglino/ol-ext/blob/master/src/control/Dialog.js) for example.

**Comment by Viglino** [comment]
It's a typo... It's a copy/paste of the Dialog code...

**Comment by alexgao1** [comment]
Will you add support for those options for Notification if this is the case?

**Comment by Viglino** [comment]
Added in the last commit...

**Comment by alexgao1** [comment]
Thank you!
