### ISSUE TITLE
Feature Popup with WMS IMAGE LAYERS

### ISSUE THREAD

**Issue by JURASINTERGEO** [Viglino/ol-ext#732]
Hi.
All ol-ext library is absolutely great and I like FeaturePopup in your style very much.
I noticed that it works perfectly with vector layer. My question is: Can I use it for WMS layers?
Maybe WMS layer will only show in the map but we ask WFS features to have their attributes in FeaturePopup?
Can we do this?
I use geoserver so I have WMS, WFS, WMTS etc.
I can't make it to work together when I use this code:

import PopupFeature from "ol-ext/overlay/PopupFeature";

var wmsSource = new ol.source.ImageWMS({
  url: "http://localhost:8080/geoserver/wms",
  params: { LAYERS: "", VERSION: "1.1.0" },
  serverType: "geoserver",
  crossOrigin: "anonymous",
});

map.on("singleclick", function (evt) {
  var popup = new Overlay({
    element: document.getElementById("popup"),
  });
  popup.setPosition(evt.coordinate);
  map.addOverlay(popup);
  document.getElementById("popup").innerHTML = "";
  var view = map.getView();
  var viewResolution = view.getResolution();
  var url = wmsSource.getFeatureInfoUrl(
    evt.coordinate,
    viewResolution,
    "EPSG:3857",
    {
      INFO_FORMAT: "application/json",
      LAYERS: "dw",
      QUERY_LAYERS: "dw",
      FEATURE_COUNT: 1,
    }
  );
  if (url) {
    fetch(url)
      .then(function (response) {
        return response.text();
      })
      .then(function (html) {
        document.getElementById("popup").innerHTML = html;
      });
  }
});

Popup shows as json on the map but I would like to have info in FeaturePopup is it possible?

**Comment by Viglino** [comment]
FeaturePopup is designed to display feature information. You have to create a feature to use and show in the popup.
```javascript
if (url) {
  fetch(url).then(function (response) {
    var feature = new Feature(new ol.geom.Point(evt.coordinate));
    feature.set('attribute 1', getAttribute(response));
    popup.show(evt.coordinate, feature)
  })
}
```
If the result is a GeoJSON you can parse it with ol GeoJSON format:
```javascript
import GeoJSON from 'ol/format/GeoJSON'

....
if (url) {
  fetch(url).then(function (response) {
    const format = GeoJSON()
    features = format.readFeatures(response);
    popup.show(evt.coordinate, features);
  })
}
```

**Comment by JURASINTERGEO** [comment]
Hello Jean Marc.
I'm still trying and trying. I'm  not a javascript expert :(
What I want to do is:
1. Associate Feature Popup with WMS layer (when I click on wms layer Feature Popup show attributes of feature, when I turn off wms layer Feature Popup doesn't show anything) It works fine when layer is an vector layer but vector layers have bigger size so application works slower.
2. Remove null values of layer attributes in Feature Popup or showing only attributes which have different value than null.
3. Have a button to activate Feature Popup.

What I did:
import GeoJSON from 'ol/format/GeoJSON'

I created vector source and vector layer:

var vectorSource = new ol.source.Vector({
  format: new ol.format.GeoJSON(),
  url: "http://localhost:8080/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=dw&outputFormat=application/json&srsName=EPSG:3857",
  FeatureType: 'GeoJSON',
});

map.addLayer(new ol.layer.Vector({
    name: 'dw',
    source: vectorSource,
    style: function(f) {
      return new ol.style.Style({ 
        image: new ol.style.RegularShape({
          radius: 5,
          radius2: 0,
          points: 4,
          stroke: new ol.style.Stroke({ color: "#000", width:1 })  
        }),
        text: new ol.style.Text ({
          text: f.get('id').toString(),
          font: 'bold 11px sans-serif',
        }),
        stroke: new ol.style.Stroke({
          width: 1,
          color: [255,128,0]
        }),
        fill: new ol.style.Fill({
          color: [255,128,0,.2]
        })
      })
    }
  }));

WMS layer in layerswitcher:

new ol.layer.Image({
          
          title: "dw",
          visible: true,
          zIndex: 0,
          source: new ol.source.ImageWMS({
            ratio: 1,
            params: { LAYERS: "dw", VERSION: "1.3.0" },
            url: "http://localhost:8080/geoserver/wms",
            tiled: "true",
            projection: "EPSG:2177",
            crossOrigin: "anonymous",
            serverType: "geoserver",
          }),
        }),

I added select interaction and Feature Popup:

 var select = new ol.interaction.Select({
    hitTolerance: 5,
    multi: true,
    condition: ol.events.condition.singleClick
  });
  map.addInteraction(select);

var popup = new ol.Overlay.PopupFeature({
    popupClass: 'default anim',
    select: select,
    canFix: true,
templete: ................

And It works but when I turn off wms layer, Feature Popup obviously still show information from vector layer. I was looking for any solution in other topics but I couldn't find it.

**Comment by Viglino** [comment]
When you turn the layer off, the feature keep being selected and the popup shows.
You have to listen to layer's visibility change to turn it off manually:
```javascript
layer.on('change:visible', function() { popup.hide() })
```
