### ISSUE TITLE
Creating legend not working

### ISSUE THREAD

**Issue by NicolasTsc** [Viglino/ol-ext#733]
Hello,
I am currently trying to add a legend to my map and found about this library.
I tried to use https://github.com/Viglino/ol-ext/blob/master/examples/legend/map.control.legends.html as a preset for my code but that didn`t work. 

I tried to create the legend using a minimal example ( https://codesandbox.io/s/attributions-forked-08s2p?file=/main.js) but neither the legend nor the default map controls ( like to +/- in the top left) are rendered once I add the line 
"map.addControl(legendCtrl);"

Hopefully someone can help me solving this problem.

Thanks in advance

**Comment by Viglino** [comment]
You have to add the ol-ext CSS in addition to ol one:
```javascript
import "ol/ol.css";
import "ol-ext/dist/ol-ext.css"
```
