### ISSUE TITLE
Swipe: Layers of type Vector Tile not working properly

### ISSUE THREAD

**Issue by digoburigo** [Viglino/ol-ext#734]
There is a bug when the layer of any geometry type has a text style associated with it and if is a point geometry with a Circle style.
Images below.
point:
![image](https://user-images.githubusercontent.com/28462822/152425062-c33693bb-4f7e-4d32-8194-a71952ecce57.png)

![image](https://user-images.githubusercontent.com/28462822/152425189-b8a41df3-4a25-4e64-bfd2-978b9c930c42.png)

line:
![image](https://user-images.githubusercontent.com/28462822/152424799-b81484b1-673a-447a-9747-192765bc9e6d.png)
polygon:
![image](https://user-images.githubusercontent.com/28462822/152424984-99ba9156-2ddc-4802-9831-3eb7bb9c4756.png)

**Comment by mike-000** [comment]
See the description of `declutter` in https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html  So for decluttered features from Vector and VectorTile layers to be included in a swipe the layers will need a `className`.

**Comment by digoburigo** [comment]
I tried this property and worked exactly like expected. Thank you for the explanation! I'm closing this issue.
