### ISSUE TITLE
Animated Clusters Android

### ISSUE THREAD

**Issue by Dirk951** [Viglino/ol-ext#735]
ol 6.12.0
ol-ext 3.2.22
While animation all icons (cluster and single markers) will ignored the image style settings for scale. Before and after animation all looks fine.  That means, while animation the symbols get to small. 
The only case, where happens this, is in a android webview (Andoid  Hybrid App). No problems with desktop browsers.

All works fine in an android app with ol 6.1.1. and ol-ext 3.1.8

Sourcecode:
function getStyleDoCTarget(feature){
	return new ol.style.Style({
			image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
					anchor: [0.50, 53], 
					**scale: 1.60,                <- dont work while animation**
					anchorXUnits: 'fraction',
					anchorYUnits: 'pixels',
					opacity: 1,
					src: 'images/doc_target.png'
				}))
		   });
}

**Comment by Viglino** [comment]
It seems there is an issue on last ol versions with pixel ratio when animating.
The last commit should fix it!

**Comment by Dirk951** [comment]
YES, work perfectly now. Thank you for your help.

Your extensions are a highlight in my mobile map apps!
