### ISSUE TITLE
when i am trying to print google satellite image shows this message : Can't save map canvas...

### ISSUE THREAD

**Issue by psujjainkar** [Viglino/ol-ext#736]
when i am trying to print google satellite image shows this message : Can't save map canvas...

here is my code snippet  :
 // Google Satelite Image
                    var googleLayerSatellite =new ol.layer.Tile({
                  
                    title: "Google Satellite",
                    
                    source: new ol.source.TileImage({ url: 'http://mt1.google.com/vt/lyrs=s&hl=pl&&x={x}&y={y}&z={z}' }),
                    crossOrign: 'anonymous',
                    visible: false,
                  
                });

i have added   crossOrign but stil
![Screenshot 2022-02-04 151415](https://user-images.githubusercontent.com/16004804/152506669-bbbfc89c-48c2-4a02-914a-c292702c055e.png)
l showing this, plz help me

**Comment by Viglino** [comment]
crossOrign is a source attribute not layers ones...
```javascript
map.addLayer(
  new ol.layer.Tile({
    title: "Google Satellite",
    source: new ol.source.TileImage({ 
      crossOrigin: 'anonymous',
      url: 'https://mt1.google.com/vt/lyrs=s&hl=pl&&x={x}&y={y}&z={z}' 
    }),
  })
)
```

**Comment by psujjainkar** [comment]
Thank You Very Much , 
I got where i made a mistake .
its working now :) really very thank you :)

**Comment by psujjainkar** [comment]
> crossOrign is a source attribute not layers ones...
> 
> ```js
> map.addLayer(
>   new ol.layer.Tile({
>     title: "Google Satellite",
>     source: new ol.source.TileImage({ 
>       crossOrigin: 'anonymous',
>       url: 'https://mt1.google.com/vt/lyrs=s&hl=pl&&x={x}&y={y}&z={z}' 
>     }),
>   })
> )
> ```

**Comment by psujjainkar** [comment]
> Thank You Very Much ,
> I got where i made a mistake .
> its working now :) really very thank you :)

Thank You Very Much ,
I got where i made a mistake .
its working now :) really very thank you :)
