### ISSUE TITLE
ol.control.Profile

### ISSUE THREAD

**Issue by GastonZalba** [Viglino/ol-ext#738]
Hi, i'm working on some improvements in the Profile control (and one minor fix), and i would like to known what do you think and, if it's all ok, how many PullRequests would you recommend me to make. All modifications were made to avoid breaking changes and to obtain the same output with the default options.

**Enhancements**
In the `constructor` class:
- Added parameter `units`: enables selectable `'imperial'` or `'metric'` as System of Measurement (only for display/graph, the input format persists the same). Default is `'metric'`.
- Added parameter `numberFormat`: enables language-sensitive number formatting using locales with browser native method toLocaleString. This is useful to change the decimals separator as well as to add/change the thousands separator. By default is empty and not used.
- Added parameters `decimalsDistance` y `decimalsAltitude` to allow customizable decimals numbers in the altitude and distance (the values that are rendered outside the canvas/graph). The previous hardcoded values ​​1 and 2 are the default.
- To enable support of different units/systems, some default values in property `info` where modified so there is no need to change the labels and modify the desire unit manually. `altitudeUnits`, `distanceUnitsM` and `distanceUnitsKM` were discarded and are now generated dynamically using the unit symbols: 'm', 'km', 'ft' and 'mi'. The old `replace("km")` method is mantained as a fallback, so the default behavior stills the same.

In `setGeometry` method:
- Added imperial units `ft` and `mi` as options in `zunit` and `unit` props. For long distances (>1000 in 'metric' or >1609.344 in 'imperial'), the behavior stills the same: meters are converted to kilometers and, in the same logic, foots to miles.
- Improved `zDigits`:  if not set, the value it's calculated automatically to allow distinguishable numbers even in small range values by enabling some decimals. Today, if the range values are less than one meter apart (between `zmin` and `zmax`), the same rounded numbers are repeated in each step. If it's set, the zDigits are forced as previously. *In this case, the default behavior is changed a little to fix the "same number is repeated" problem in these small range values*
- Added parameter `xsteps`: allows customizable number of steps at the x-axis in the graph. In current version, theses steps where always fixed to 10 (the default value now), and in some measurements the numbers could be overlapping each on another and/or very difficult to read.
- Added parameter `zsteps`: allows customizable number of steps at the y-axis in the graph. In current version, the steps were calculated dinamycally using `graduation`, `zmin` and `zmax` values. Now, if `zsteps` was set, `graduation` parameter is not used, and it's calculated to mantain the desired number of steps.
 
**Fixed bug**
- Added the ol function [asString](https://openlayers.org/en/latest/apidoc/module-ol_color.html#.asString) to convert `options.style` and `options.selectStyle` colors, otherwise correct format colors (like an array `[0,10,10]`) were discarted in the canvas.

**Sorry if my english is a bit rubbish

**Comment by Viglino** [comment]
That seems to be a good PR/improvement to use other metrics!
You can make a single PR...
