### ISSUE TITLE
Trouble combining Splitter with Undo/Redo

### ISSUE THREAD

**Issue by Merlo17** [Viglino/ol-ext#742]
Hello,
I'm currently having troubles implementing the [Splitter](https://viglino.github.io/olext/examples/interaction/map.interaction.splitter.html) interaction with the [Undo/Redo](https://viglino.github.io/ol-ext/examples/interaction/map.interaction.undoredo.html) interaction. 
I suspect this is because under the hood the splitter is cloning features and adds unwanted undoable interactions on the stack after every split and this invalidates the entire stack.
For example, when crossing two straight lines I get 8 additional undo "addfeature" actions added to the stack.
Is there any way to implement this or filter out interactions coming from the splitter? I would like to keep the splitter but also be able to undo the last line drawn using the undo feature.
Thanks for your time, sorry if this is not the place to ask these types of question.

**Comment by Viglino** [comment]
The trouble with the Splitter interaction is it performs a set of creation / destruction after the action on the feature.
I've tried to take it into account in the last commit to make a single action that groups the action on the feature and the split.
This should work now.

Be aware that the Splitter interaction **must not be active when undoing / redoing** or it will try to split features while undoing.
You have to deactivate it before undo:
```javascript
splitter.setActive(false);
undo.undo();
splitter.setActive(true);
```
