### ISSUE TITLE
How can I get right/left layer size using swipe control

### ISSUE THREAD

**Issue by rdrmartin-afk** [Viglino/ol-ext#743]
Hi, 
I´m using the swipe control and I´m wondering if there´s any way to get the visible size of the right and left layer when you resize using the control.
Thanks for your time, sorry if this is not the place to ask these types of question.

**Comment by Viglino** [comment]
There is a `moving` event you can listen to get the size of the left side.
You can also get the left rectangle: `ctrl.getRectangle()`. It's pixel extent but you can convert it to get map projection.
