### ISSUE TITLE
Add chart to multipolygon feature

### ISSUE THREAD

**Issue by Swapss** [Viglino/ol-ext#744]
How can I add a chart to a Multipolygon type of geometry?

**Comment by Swapss** [comment]
Can I replace chartStyle with 
new Chart({
                        type: "pie",
                        radius: radius,
                        data: data,
                        rotateWithView: true,
                        stroke: new Stroke({
                            color: "#fff",
                            width: 2
                        })

**Comment by Swapss** [comment]
Getting an error
TypeError: feature.getGeometry(...).getInteriorPoint is not a function

**Comment by Swapss** [comment]
Geometry type is MultiPolygon
![image](https://user-images.githubusercontent.com/99646105/155335555-ae9246e4-9c0f-4bd6-b5f4-e774fcdff77f.png)
This is the preview I can see on map. Pie chart is not viewed on map, only % values are shown on map
![image](https://user-images.githubusercontent.com/99646105/155335363-f1166387-becf-493e-9b05-9f224b220c2a.png)

I tried this piece of code. Added a sample data and sum.
````
var features = new VectorLayer({
                name: 'Vector',
                source: new VectorSource({
                    format: new GeoJSON(),
                    url: dataUrl
                }),
                style: function (f) { return getFeatureStyle(f, [4, 1, 8, 2], 15); }
            })
map.addLayer(features);
````

````
        // Style function
        var styleCache = {};
        function getFeatureStyle(feature, data, sum, sel = true) {
            var k = data
            var style = styleCache[k];
            if (!style) {
                var radius = 50;
                // area proportional to data size: s=PI*r^2
                radius = 8 * Math.sqrt(sum / Math.PI);
                radius *= (sel ? 1.2 : 1);
                // Create chart style
                style = [new Style({
                    image: new Chart({
                        type: "pie",
                        radius: radius,
                        data: data,
                        stroke: new Stroke({
                            color: "#fff",
                            width: 2
                        }),
                    }),
                    geometry: function (feature) {
                        switch (feature.getGeometry().getType()) {
                            case 'Polygon': return feature.getGeometry().getInteriorPoint();
                            case 'MultiPolygon': return feature.getGeometry().getInteriorPoints()[0];
                            default: return feature.getGeometry().getFirstCoordinate()
                        }
                    }
                })];
                // Show values on select
                if (sel) {
                    console.log(sel)
                    var s = 0;
                    for (var i = 0; i < data.length; i++) {
                        var d = data[i];
                        var a = (2 * s + d) / sum * Math.PI - Math.PI / 2;
                        var v = Math.round(d / sum * 1000);
                        if (v > 0) {
                            style.push(new Style({
                                text: new Text({
                                    text: (v / 10) + "%", /* d.toString() */
                                    offsetX: Math.cos(a) * (radius + 3),
                                    offsetY: Math.sin(a) * (radius + 3),
                                    textAlign: (a < Math.PI / 2 ? "left" : "right"),
                                    textBaseline: "middle",
                                    stroke: new Stroke({ color: "#fff", width: 2.5 }),
                                    fill: new Fill({ color: "#333" })
                                })
                            }));
                        }
                        s += d;
                    }
                }
            }
            styleCache[k] = style;
            return style;
        }
````

**Comment by Viglino** [comment]
Seems working for me...
Do you have a working example inline?
https://codepen.io/viglino/pen/QWOxZpV

**Comment by Swapss** [comment]
Code is working for most of the polygons in the sample code but some of them have the above issue

https://codepen.io/swapss/pen/GROGPGZ

**Comment by Swapss** [comment]
The issue is only with MultiPolygon it seems

**Comment by Viglino** [comment]
Well, you've got 3 issues:
1. feature.getGeometry().getInteriorPoints() is not an array but a MultiPoint. You have to use getPoint method to get them: feature.getGeometry().getInteriorPoints().getPoint(0)
2. Doing this, the interior point of the MultiPolygon is the one of the first polygon (ie. not the main or largest one but maybe only an island)
3. The interior point is not the one used for drawing the text...

You have to make your own interior calculation to get the interior point and use it as geometry for Chart and Text
See: https://codepen.io/viglino/pen/VwrBjYM that use the polygon with the largest number of point to drawing the chart in.

**Comment by Swapss** [comment]
This is working. Thank you so much.

**Comment by Swapss** [comment]
Need one help related to the issue raised above. After the pie or any other fill method applied to each polygon on the map, is there any way to remove the styling from all the polygons?

**Comment by Viglino** [comment]
You can set a new style function to the layer: `layer.setStle([])`
