### ISSUE TITLE
How to set scale for print dialog? 

### ISSUE THREAD

**Issue by palur76** [Viglino/ol-ext#747]
Hi, 

I try to set some defaults for the print dialog. 
```
var printControl = new ol.control.PrintDialog();
printControl.setSize("A3");
printControl.setMargin(5);
printControl.setScale("1/1000000");			
map.addControl(printControl);
printControl.on("print", function(e) {
	[...]
}
```
`setSize()` and `setMargin()` are working perfectly, but `setScale()` not, I can't set scale, and the submitted value in the scale dropdown isn't set, too. How can I set scale for printing? 

Thanks.

**Comment by Viglino** [comment]
The scale is the one of the map. 
You have to set the map zoom or resolution to the one you want.
```javascript
const scale = 25; // 1/25000
const scaleResolution =
      scale /
      ol.proj.getPointResolution(
        map.getView().getProjection(),
        96 / 25.4,
        map.getView().getCenter()
      );
map.getView().setResolution(scaleResolution );
```
You can also use the [ol/control/scale](https://viglino.github.io/ol-ext/examples/control/map.control.scale.html).
