### ISSUE TITLE
Profile tool : wrong display for large z number 

### ISSUE THREAD

**Issue by sebbelese** [Viglino/ol-ext#748]
Hi,

I am using the profile control tool to display different types of data along lines.

However, for large values, the display is wrong with hidden digits, some of which are also placed under the vertical label.

I think that this behaviour could be easily improved by switching to floating point notation when the numbers are too large, i.e. modifying line 705:

```    
             if (this.get('zunit') != 'km') ctx.fillText(i.toFixed(fix), -4*ratio, i*scy+dy);
```

Maybe linked with #738 

![image](https://user-images.githubusercontent.com/16559668/156772073-cda88886-87e4-4aae-a12b-1f37cf362730.png)

**Comment by Viglino** [comment]
Profile control is mainly designed to display altitude (at least 4 digits) and there is no origine offset.
Using zunit = 'km' lets you divide values Z value by 1000 (kilo units) for more visibility (floating point), use zDigits to set the number of digit you want (default is 0).
Graduations are rounded for display, you have to set the graduation option to fit a round coordinate on the Z axis.

I think you can try setting:
zunit: 'km',
graduation: 1000,
zDigits: 1
