### ISSUE TITLE
FontSize of FontSymbol not as expected

### ISSUE THREAD

**Issue by ngoloc10796** [Viglino/ol-ext#752]
https://codepen.io/viglino/pen/QVNpzm?editors=1010

i have add `FontSize: 20` then view as image: 

![image](https://user-images.githubusercontent.com/28887448/159618278-31921aa1-d599-447f-ace2-d01146994495.png)

Please check! thank you!

**Comment by Viglino** [comment]
The `fontSize` is the size of the font compare to the symbol `radius`...
20 means the glyph will be 20*radius size and it will be cropped.
`fontSize` greater than 1 may exceed the symbol extent and is cropped.

You have to use the `radius` option instead if you want to size the symbol.
