### ISSUE TITLE
How to display full legend on the print dialog

### ISSUE THREAD

**Issue by regita96** [Viglino/ol-ext#753]
Hello, i have a question.
I have built a legend that have a lot of features in it.
when i use print dialog, however, i couldn't see all the features inside my legend in the preview.
what should i change to make the print dialog able to show my entire features on my legend
Thank you

**Comment by Viglino** [comment]
There is no pagination for legend.
You can use a larger page size or copy/paste the legend as an image to crop...

**Comment by regita96** [comment]
Could you explain, where to put that image crop ?

**Comment by andreaordonselli** [comment]
maybe this conversation can help:
https://github.com/Viglino/ol-ext/issues/755

in any case I suggest you to report your js code so maybe we understand how to help you. I had to add the variable size
