### ISSUE TITLE
Using ol-ext with qgis2web static openlayers export - printdialog

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#755]
I would like to implement ol/control/PrintDialog published [here](https://viglino.github.io/ol-ext/examples/canvas/map.control.printdialog.html) in my project published entirely [here](https://drive.google.com/drive/folders/1v7Lf0JTcv_4Vo1_gQbYGPEKNOlUcx60a?usp=sharing)

I have added in the head of **index.html** this:

```
<link rel="stylesheet" href="ol-ext-master/dist/ol-ext.css"/>
		<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
		<script type="text/javascript" src="https://openlayers.org/en/latest/build/ol.js"></script>
		<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL,Object.assign"></script>
		<script type="text/javascript" src="ol-ext-master/dist/ol-ext.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
		<script type="text/javascript" src="https://cdn.rawgit.com/eligrey/FileSaver.js/aa9f4e0e/FileSaver.min.js"></script>
```

I have added in **qgis2web.js** this:

```
map.addControl(new ol.control.CanvasAttribution({ canvas: true }));
// Add a title control
map.addControl(new ol.control.CanvasTitle({ 
  title: 'my title', 
  visible: false,
  style: new ol.style.Style({ text: new ol.style.Text({ font: '20px "Lucida Grande",Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif'}) })
}));

// Legend
var legend = new ol.legend.Legend({ 
  title: 'Legend', 
  margin: 5,
  items: [{
	title: 'Church', 
	typeGeom: 'Point', 
	style: new ol.style.Style({ 
	  image: new ol.style.Icon({ 
	  src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Eglise_icone_2.svg/30px-Eglise_icone_2.svg.png',
	  crossOrigin: 'anonymous' // Enable print
	})})
  }, { 
	title: 'Photo', 
	typeGeom: 'Point', 
	style: new ol.style.Style({ 
	  image: new ol.style.Icon({ 
	  src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Icone_appareil_photo.svg/30px-Icone_appareil_photo.svg.png',
	  crossOrigin: 'anonymous' // Enable print
	})})
  }, {
	title: 'Line', typeGeom: 'LineString', style: ol.style.Style.defaultStyle() 
  }, {
	title: 'Polygon', typeGeom: 'Polygon', style: ol.style.Style.defaultStyle() 
  }]
});

// Add a legend to the print
var legendCtrl = new ol.control.Legend({ legend: legend });
map.addControl(legendCtrl);

// Add a ScaleLine control 
map.addControl(new ol.control.CanvasScaleLine());

// Print control
var printControl = new ol.control.PrintDialog();
printControl.setSize('A4');
map.addControl(printControl);

/* On print > save image file */
printControl.on(['print', 'error'], function(e) {
  // Print success
  if (e.image) {
	if (e.pdf) {
	  // Export pdf using the print info
	  var pdf = new jsPDF({
		orientation: e.print.orientation,
		unit: e.print.unit,
		format: e.print.size
	  });
	  pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0], e.print.imageWidth, e.print.imageHeight);
	  pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
	} else  {
	  // Save image as file
	  e.canvas.toBlob(function(blob) {
		var name = (e.print.legend ? 'legend.' : 'map.')+e.imageType.replace('image/','');
		saveAs(blob, name);
	  }, e.imageType, e.quality);
	}
  } else {
	console.warn('No canvas to export');
  }
});
```

But I have this errore in Console:
![image](https://user-images.githubusercontent.com/89784373/160815883-d72c69ec-dca0-492a-81f6-fef723b745b9.png)

What am I doing wrong?
The error is repeated in cascade also for the other ol.control

**Comment by Viglino** [comment]
The lib ol-ext is not loaded. Check the lib path.

**Comment by andreaordonselli** [comment]
now i think it loads fine, but i get the same error, can you help me again?
the entire project, updated, is published [here](https://drive.google.com/drive/folders/1v7Lf0JTcv_4Vo1_gQbYGPEKNOlUcx60a?usp=sharing)

![image](https://user-images.githubusercontent.com/89784373/160916824-50c90b00-5221-4128-ac06-27740c6c5e0a.png)

**Comment by andreaordonselli** [comment]
I understand the problem. Within the index.html file, multiple ol.js files were recalled which conflicted with the one provided in the code strings above. I commented on the other ol.js and fixed the css for my project.
The print button and all its functions are now active and the legend printing works. However I get this error when printing the map in various formats.
![image](https://user-images.githubusercontent.com/89784373/161017199-eb48a4c1-9683-4acf-bcd6-73eea2dab770.png)

The console gives this error:
![2022-03-31 11_11_10-Riserva Furlo WebMap](https://user-images.githubusercontent.com/89784373/161021992-b6c6801e-feaf-4bd2-8573-0ae46de42e5d.png)

Can you tell me where do you check to make this download work?
Entire project, updated, always [here](https://drive.google.com/drive/folders/1v7Lf0JTcv_4Vo1_gQbYGPEKNOlUcx60a?usp=sharing)
Thanks.

**Comment by Viglino** [comment]
Make sure all the layers are printable ie. are accessed with a crossOrigin attribute set to "Anonymous". See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image for more detail.

**Comment by andreaordonselli** [comment]
I understood that the print function gave an error only in the case where a wms or xyz level was active.
I found then [this](https://github.com/Viglino/ol-ext/issues/632) issue solved which guided me to reach the goal.
Adding `crossOrigin: 'anonymous',` in the various layers the print works perfectly.
**Thanks again for the support and the wonderful work with ol-ext.**

**_Step by step instructions for qgis2web users:_**

To make ol-print-dialog work with the openlayers map produced by the qgis plugin called "qgis2web", you need to insert this in the head of the index.html file:

```
<script type="text/javascript" src="https://openlayers.org/en/latest/build/ol.js"></script>
<link rel="stylesheet" href="ol-ext-master/dist/ol-ext.css"/>
<script type="text/javascript" src="ol-ext-master/dist/ol-ext.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL,Object.assign"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/eligrey/FileSaver.js/aa9f4e0e/FileSaver.min.js"></script>
```
and comment this in the body:

`<!--<script src="./resources/ol.js"></script>-->`

Then you need to insert `crossOrigin: 'anonymous',` in each XYZ or WMS layers present in the "layers.js" file, contained in the "layers" folder, as follows:

![2022-04-05 21_42_38-G__Il mio Drive_2021 qgis2web_online_qgis2web_2022_03_16-09_56_21_086309_furlo_t](https://user-images.githubusercontent.com/89784373/161837392-be62dbe0-438c-4e8d-b069-3c4f4bc9412e.png)

**Comment by andreaordonselli** [comment]
I would like to ask for one last piece of advice. To insert a simple legend, made only of an ad hoc png file, how can I do?
I am not interested in seeing the legend on the map, but only for it to appear in print. I changed the code like this with bad results. I don't understand how to set the dimensions of the legend to those of the png and how to position the image in the lower left corner

```
// Legend
	var legend = new ol.legend.Legend({ 
	title: '', 
	margin: 5,
	items: [{
	title: '', 
	typeGeom: 'Point', 
	style: new ol.style.Style({ 
	image: new ol.style.Icon({ 
	src: './ol-ext-master/dist/legenda.png',
	//crossOrigin: 'anonymous' // Enable print
			})})
		  }		  
		  ]
		});
```

![image](https://user-images.githubusercontent.com/89784373/163230443-783b9b11-6ca6-4b36-8559-95331f0979d8.png)

**Comment by Viglino** [comment]
You have to set the dimension of the legend symbols: size options (default is 40x25) to fit your image size.
See: https://viglino.github.io/ol-ext/doc/doc-pages/ol.legend.Legend.html

**Comment by andreaordonselli** [comment]
With your suggestion I managed to reach the desired goal.
I don't understand why but I had to add a second empty item to reach the height space I needed.
Here is the result and the changes to the files:

![image](https://user-images.githubusercontent.com/89784373/163718302-8d1db44b-af15-4075-a6f0-0a38cfa32ff5.png)

**index.html** -> as reported above
**layers.js** -> as reported above
**qgis2web.js** ->

```

		map.addControl(new ol.control.CanvasAttribution({ canvas: true }));
		// Add a title control
		map.addControl(new ol.control.CanvasTitle({ 
		  title: 'my title', 
		  visible: false,
		  style: new ol.style.Style({ text: new ol.style.Text({ font: '20px "Lucida Grande",Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif'}) })
		}));
		
		// Legend
		var legend = new ol.legend.Legend({ 
		  title: 'Legenda', 
		  margin: 0,
		  //set width and height as desired
		  size: [215,155],
		  items: [{
			title: '', 
			typeGeom: 'Point',
			style: new ol.style.Style({ 
			  image: new ol.style.Icon({
			  //enter the web path of the legend
			  src: 'https://pianifterrprovpu.altervista.org/wp-content/a_pianif/ol-ext-master/dist/legenda.png',  			  
			  crossOrigin: 'anonymous' // Enable print
			})})
		  },{
			//keep this second item to correctly space the height of the legend
			title: '', 
			typeGeom: 'Point',
			style: new ol.style.Style({ 
			  image: new ol.style.Icon({ 
			  src: 'data:,',			  
			  //crossOrigin: 'anonymous' // Enable print
			})})
		  }
		  ]
		});

		// Add a legend to the print
		var legendCtrl = new ol.control.Legend({ legend: legend });
		map.addControl(legendCtrl);
		
		// Add a ScaleLine control 
		map.addControl(new ol.control.CanvasScaleLine());

		// Print control
		var printControl = new ol.control.PrintDialog();
		printControl.setSize('A4');
		printControl.setOrientation('landscape');
		map.addControl(printControl);

		/* On print > save image file */
		printControl.on(['print', 'error'], function(e) {
		  // Print success
		  if (e.image) {
			if (e.pdf) {
			  // Export pdf using the print info
			  var pdf = new jsPDF({
				orientation: e.print.orientation,
				unit: e.print.unit,
				format: e.print.size
			  });
			  pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0], e.print.imageWidth, e.print.imageHeight);
			  pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
			} else  {
			  // Save image as file
			  e.canvas.toBlob(function(blob) {
				var name = (e.print.legend ? 'legend.' : 'map.')+e.imageType.replace('image/','');
				saveAs(blob, name);
			  }, e.imageType, e.quality);
			}
		  } else {
			console.warn('No canvas to export');
		  }
		});
```

Thank you again

**Comment by serxhio31** [comment]
Can someone please help me with this ?

![image](https://github.com/Viglino/ol-ext/assets/31244402/3608789a-eca4-4787-8fc6-541ee7470899)

My map wont display in the canvas . I read your conversation but still the problem occurs.

**Comment by andreaordonselli** [comment]
Can you write what problem you have in browser console and what code are you implementing in your project?

**Comment by serxhio31** [comment]
printBtn.addEventListener("click", () => {
  const printDialog = new PrintDialog({ immediate: true });
  printDialog.setSize("A4");
  printDialog.setOrientation("landscape");
  map.addControl(printDialog);

  const saveAsPdfOption = document.querySelector(
    '.ol-saveas select option[value="3"]'
  );
  const parentSelect = saveAsPdfOption.parentElement.parentElement;

  parentSelect.addEventListener("change", function () {
    // Get the value of the selected option
    if (saveAsPdfOption) {
      printDialog.on(["print", "error"], function (e) {
        // Print success
        if (e.image) {
          if (e.pdf) {
            // Export pdf using the print info
            var pdf = new jsPDF({
              orientation: e.print.orientation,
              unit: e.print.unit,
              format: e.print.size,
            });
            pdf.addImage(
              e.image,
              "JPEG",
              e.print.position[0],
              e.print.position[0],
              e.print.imageWidth,
              e.print.imageHeight
            );
            pdf.save(e.print.legend ? "legend.pdf" : "map.pdf");
          } else {
            // Save image as file
            e.canvas.toBlob(
              function (blob) {
                var name = "title 1";
                saveAs(blob, name);
              },
              e.imageType,
              e.quality
            );
          }
        } else {
          console.warn("No canvas to export");
        }
      });
    }
  });

  const cancelButton = document.querySelector(
    ".ol-ext-buttons button[type='button']"
  );
  cancelButton.addEventListener("click", () => {
    map.removeControl(printDialog);
  });
});

This is my code. I want to display on the map map's element like north arrow , scale text etc.. + legend from wms service.
Thanks in advance

![image](https://github.com/Viglino/ol-ext/assets/31244402/ecfbc8eb-b35d-4266-8402-a8942b30f0ae)

**Comment by andreaordonselli** [comment]
Can you provide a codepen? Why don't you stick with the original code from the online [example](https://viglino.github.io/ol-ext/examples/canvas/map.control.printdialog.html)? I notice that you have created ad hoc buttons with addEventListener but I don't think they are needed


// Print control
var printControl = new ol.control.PrintDialog({ 
  // target: document.querySelector('.info'),
  // targetDialog: map.getTargetElement() 
  // save: false,
  // copy: false,
  // pdf: false
});
printControl.setSize('A4');
map.addControl(printControl);

/* On print > save image file */
printControl.on(['print', 'error'], function(e) {
  // Print success
  if (e.image) {
    if (e.pdf) {
      // Export pdf using the print info
      var pdf = new jsPDF({
        orientation: e.print.orientation,
        unit: e.print.unit,
        format: e.print.size
      });
      pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0], e.print.imageWidth, e.print.imageHeight);
      pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
    } else  {
      // Save image as file
      e.canvas.toBlob(function(blob) {
        var name = (e.print.legend ? 'legend.' : 'map.')+e.imageType.replace('image/','');
        saveAs(blob, name);
      }, e.imageType, e.quality);
    }
  } else {
    console.warn('No canvas to export');
  }
});

**Comment by serxhio31** [comment]
I saw the original example. When I remove eventListerner I dont get any map downloaded.

>map.addControl(new CanvasScaleLine());


```javascript
map.addControl(new CanvasScaleLine());

const printBtn = document.querySelector(".print-dialog");

printBtn.addEventListener("click", () => {
  const printDialog = new PrintDialog({ immediate: true });
  console.log(calculateScale());
  console.log(printDialog);
  map.addControl(printDialog);

  const saveAsPdfOption = document.querySelector(
    '.ol-saveas select option[value="3"]'
  );
  const parentSelect = saveAsPdfOption.parentElement.parentElement;

  parentSelect.addEventListener("change", function () {
    // Get the value of the selected option
    if (saveAsPdfOption) {
      printDialog.on(["print", "error"], function (e) {
        console.log(e);
        // Print success
        if (e.image) {
          if (e.pdf) {
            // Export pdf using the print info
            var pdf = new jsPDF({
              orientation: e.print.orientation,
              unit: e.print.unit,
              format: e.print.size,
            });
            pdf.addImage(
              e.image,
              "JPEG",
              e.print.position[0],
              e.print.position[0],
              e.print.imageWidth,
              e.print.imageHeight
            );
            pdf.save(e.print.legend ? "legend.pdf" : "map.pdf");
          } else {
            // Save image as file
            e.canvas.toBlob(
              function (blob) {
                var name = "title 1";
                saveAs(blob, name);
              },
              e.imageType,
              e.quality
            );
          }
        } else {
          console.warn("No canvas to export");
        }
      });
    }
  });

  const cancelButton = document.querySelector(
    ".ol-ext-buttons button[type='button']"
  );
  cancelButton.addEventListener("click", () => {
    map.removeControl(printDialog);
  });
**});**
```

**Comment by serxhio31** [comment]
I'm sorry . Please see the code below. When I remove eventListener I don't get nothing from save as pdf... 
I used your code below as well but it wont work. I don't really understand everything in the original example. If you need something else to understand the code please let me know. 


```javascript

```
