### ISSUE TITLE
Adding PrintDialog in npm / parcel project and OL v 6

### ISSUE THREAD

**Issue by karstenv** [Viglino/ol-ext#756]
I am trying to add a PrintDialog to a NPM based project .

I installed ol-ext
```
npm install ol-ext
```
that worked without any issues.
In the project, the import seems to work as well via

```
import PrintDialog from 'ol-ext/control/PrintDialog';
import 'ol-ext/control/PrintDialog.css';
```
When trying to add  print Dialog via
```
// Print control
var printControl = new ol.control.PrintDialog();
printControl.setSize('A4');
map.addControl(printControl);
```
and
```
printControl.on(['print', 'error'], function(e) {
    // Print success
    if (e.image) {
      if (e.pdf) {
        // Export pdf using the print info
        var pdf = new jsPDF({
          orientation: e.print.orientation,
          unit: e.print.unit,
          format: e.print.size
        });
        pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0], e.print.imageWidth, e.print.imageHeight);
        pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
      } else  {
        // Save image as file
        e.canvas.toBlob(function(blob) {
          var name = 'title 1'; //(e.print.legend ? 'legend.' : 'map.')+e.imageType.replace('image/','');
          saveAs(blob, name);
        }, e.imageType, e.quality);
      }
    } else {
      console.warn('No canvas to export');
    }
});
```
I keep getting an error like this: 
`Uncaught TypeError: this.labels[this.lang] is undefined`

It seems to me that I am missing probably some HTML div s to fix this - maybe related to the print dialog itself and/or the legend and canvas controls ?
Is there an example how to define that for a NPM project (vs. pure plain JS page ?)

**Comment by Viglino** [comment]
When you use the module import you have to use the module syntaxe to creat new classes (not the ol.control.xxx)

```javascript
import 'ol/src/ol.css'
import 'ol-ext/dist/ol-ext.css'

import PrintDialog from 'ol-ext/control/PrintDialog';

// Print control
var printControl = new PrintDialog();
printControl.setSize('A4');
map.addControl(printControl);
```

**Comment by karstenv** [comment]
Update I was able to fix the error above
`Uncaught TypeError: this.labels[this.lang] is undefined`
using
```
var printControl = new PrintDialog({
    lang: conf.printDialog.lang ? conf.printDialog.lang : 'en' 
});
```
Now I am getting this error
`Uncaught ReferenceError: conf is not defined`
Seems that I'm missing several basic settings. Any ideas how to fix this ?

**Comment by eldang** [comment]
Thank you @Viglino for helping us get this figured out.  I'm @karstenv's colleague and the latest issue turns out to have been a mismatch between the scopes that the two of us were trying things in - nothing to do with the extension itself.  But your earlier replies helped to get us unstuck from where we were yesterday.
