### ISSUE TITLE
Can we add US Letter to the PrintDialog page sizes?

### ISSUE THREAD

**Issue by eldang** [Viglino/ol-ext#757]
This would be convenient for users in the US & Canada, and I think it's an easy change but I don't have all the tooling installed to do it properly myself.  I think it would just involve adding one more item to the list here: https://github.com/Viglino/ol-ext/blob/c86c5e7cdfd40a2c9a2e0b9d97eef261cbdbaade/src/control/PrintDialog.js#L720-L730 with the value `'US Letter': [215.9,279.4]` (and if the size needs to be in integers I think it would be safer to round down to avoid rescaling).

**Comment by eldang** [comment]
In case this is helpful to anyone else, I've been able to add a paper size on the client side with the following hack:

```javascript
	printControl.paperSize['US LETTER'] = [200,215]; // this is actually much smaller than US Letter, but seems to be necessary to get the scale bar & N arrow to print
	printControl.setSize(conf.printDialog.paperSize ? conf.printDialog.paperSize : 'US Letter');
	map.addControl(printControl);
	$('li.ol-size select').append('<option value="US LETTER">US Letter - 8.5x11 in</option>');
```

This is good enough for my purposes!

If anyone does pick up adding the size to the basic package, I think that this line:

https://github.com/Viglino/ol-ext/blob/c86c5e7cdfd40a2c9a2e0b9d97eef261cbdbaade/src/control/PrintDialog.js#L827

might also need to be changed, because it seems to bake in the assumption that size names have no lowercase characters, which works well for ISO 216 sizes but would mean that US Letter would have to be spelled out as "US LETTER".

**Comment by Viglino** [comment]
I've added the 'US Letter' size to the PrintControl.
Line 827 has been changed to enable case insensitivity: ie you can use `printControl.setSize('US Letter');` , `printControl.setSize('us letter');` or `printControl.setSize('US LETTER');` as well.

**Comment by Viglino** [comment]
NB: you can add your own size
```javascript
// Add new size
ol.control.PrintDialog.prototype.paperSize['My size'] = [100,100];
// New control
var printControl = new ol.control.PrintDialog();
```

**Comment by eldang** [comment]
Thank you!  And this is a much tidier way to add a custom size than the sample code I posted.

**Comment by eldang** [comment]
Hooray!  Thank you for including this in https://github.com/Viglino/ol-ext/releases/tag/v3.2.24

It took me a couple of weeks to get around to testing the update, but it's all working nicely and I've removed my custom size code from my project.  Closing this issue as it's fully resolved.
