### ISSUE TITLE
ol-ext removing crop/mask 

### ISSUE THREAD

**Issue by OscarJanin** [Viglino/ol-ext#761]
so there is a way to add mask and/or crop:  layer.addFilter(mask) / layer.addFilter(crop)

But is there a way to remove the mask/crop from the layer, because i can't find it

the purpose of this is to then changing the mask/crop area with input without creating a layer (and adding it's mask) for each of the area I want to switch to.

**Comment by Viglino** [comment]
Use `addFilter` to add a filter and `removeFilter` to remove it...
and `getFilters` to get current filters on a layer...
```javascript
// Remove all filters
const filters = layer.getFilters();
for (let i=filters.length-1; i>=0; i--) layer.removeFilter(filters[i]);
```

**Comment by OscarJanin** [comment]
Ok now I see,
Couldn't find that removeFilter takes a variable.

Thank you very much !
