### ISSUE TITLE
PopupFeature + Clusters + template

### ISSUE THREAD

**Issue by luzhskij** [Viglino/ol-ext#763]
Hey!
Need help again.
I can't figure out how to display object info with Popup Feature when it comes to cluster.

I am using standard clusters (ol.source.Cluster).
The problem is with the template.
How to form a title is clear, for example:
 >title:
>function(f) {
>return "Select cluster: " +  f.get('features').length + " elements";
>},
 
When the features were single (not in a cluster), the code based on the example (popup/map.popup.feature.html) worked fine.
But when there is a click on one cluster object (i.e. a cluster in which there is only 1 object) - I don’t understand how to form a template.

With this attribute formation:
>  attributes: {
>         features: {
>             title: 'Example',
>             value: function(ft) {               
>                 return ft.get('some_key');
>             }
>         }
>     }

It turns out nonsense:
![image](https://user-images.githubusercontent.com/7203449/163979511-9b9efe84-383b-449b-a71e-4cdb58018acc.png)

**Comment by Viglino** [comment]
It seems your attribute is an object (ft.get('some_key') returns an object) that is display as [object Object]

**Comment by luzhskij** [comment]
[Viglino](https://github.com/Viglino), thanks for the reaction!

For example, it also displays "[object object]" :(
```
...
title:
function(f) {
      return "Select cluster: " + f.get('features').length + " elements";
},
attributes: {
features: {
     title: 'Example',
     value: 'test',        
     }
}
...
```


I have already seen a similar discussion (https://github.com/Viglino/ol-ext/issues/292). 
But I still can't figure out how to get the value. 

If it is not hard for you, then could you explain to me.

My cluster object f has 2 keys:

> ['geometry', 'features']

get all objects in the cluster:

> var feat_all = f.get('features')

get the desired output value:

> feat_all[0].get('some_key')

1) function in "title" operates directly on the cluster object
2) in "attributes". Is it correct to refer to the "features" key like this? 
in my first example there was a line:
 ```
value: function(ft) { return ft.get('some_key'); }
```
Is it correct that "ft" is equivalent to "ft = f.get('features')" ?

**Comment by luzhskij** [comment]
This is very curious, I changed "value:" to "format:" and finally got the attribute to display correctly!

**Comment by luzhskij** [comment]
This is very curious, I changed "value:" to "format:" and finally the attribute is displayed correctly!

The real question now is how to display multiple attributes with different titles... They have a common key ('features'), but each object has more than one property ('some_key', 'some_key1', 'some_key2' ...).
