### ISSUE TITLE
ol v5.3.3 + ol-ext + React.js => Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by Gormm1980** [Viglino/ol-ext#764]
Hi all, 
I have too many problems with ol-ext and React.js i resolved many errors but this one give me an a terrible 
headache.
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

I'm trying use the PerspectiveMap. Here part of my code:

```
import React from 'react';
import './perspective.css';
import PerspectiveMap from 'ol-ext/map/PerspectiveMap';
import ol from 'openlayers';
```

```
function MapPerspective() {

    var layer = new ol.layer.Tile({ name:"OSM", source: new ol.source.OSM() });
  
  // The map
  var map = new PerspectiveMap({
    target: 'map',
    view: new ol.View ({
      zoom: 19,
      center: [-245406, 5986536]// [-245575, 5986863], //[-244777, 5989809]
    }),
    interactions: ol.interaction.defaults(),
    layers: [ layer ]
  });

  map.on('change:perspective', function(e) {
    if (!e.animating) this('#angle').val(e.angle);
  })
```

I hope some one can help me.

**Comment by Viglino** [comment]
Are you sure you have a div with a id="map" in your html?

**Comment by Gormm1980** [comment]
Yep, i'm sure.
Here the complete component i hope that could help you


`import React from 'react';
import './perspective.css';
import PerspectiveMap from 'ol-ext/map/PerspectiveMap';
import ol from 'openlayers';


function MapPerspective() {

    var layer = new ol.layer.Tile({ name:"OSM", source: new ol.source.OSM() });
  
  // The map
  var map = new PerspectiveMap({
    target: 'map',
    view: new ol.View ({
      zoom: 19,
      center: [-245406, 5986536]// [-245575, 5986863], //[-244777, 5989809]
    }),
    interactions: ol.interaction.defaults(),
    layers: [ layer ]
  });

  map.on('change:perspective', function(e) {
    if (!e.animating) this('#angle').val(e.angle);
  })

  // Create vector layer for select
  var vectorSource = new ol.source.Vector({
    url: '../data/ignf.json',
    format: new ol.format.GeoJSON(),
    attributions: [ "&copy; <a href='http://professionnels.ign.fr/bdtopo'>ign.fr</a>" ]
  });
  var vector = new ol.layer.VectorImage({
    source: vectorSource,
    maxResolution: 2
  });
  map.addLayer(vector);

  // Select and draw interaction
  map.addInteraction(new ol.interaction.Select({ 
    layers: [vector], 
    condition: function (e) {
      return (ol.events.condition.pointerMove(e) && !ol.events.condition.altKeyOnly(e))
    }
  }));
  map.addInteraction(new ol.interaction.Draw({ type: 'LineString' }))

  // An overlay
  var place = new ol.Overlay.Placemark ({
    contentColor: '#000'
  });
  map.addOverlay(place);
  map.on('click', function(e) {
    place.show(e.coordinate);
  });

    return (
        <div>
    <a href="https://github.com/Viglino/ol-ext" class="icss-github-corner"></a>
    

  <div id="map"></div>

  <div class="options">
    <ul>
      <li>
        <label>Perspective:</label>
        <input id="angle" type="range" step="1" min="0" max="30 "onchange="map.setPerspective(this.value)" value="0"style="vertical-align: middle;" />
      </li>
      <li><i>use alt + drag to tilt the map...</i></li>
    </ul>
  </div>
</div>
    )

}

export default MapPerspective;`

**Comment by Viglino** [comment]
When you create the perspective map, the target `id=map` doesn't exists. It is included in the DOM at the end of the function.
```javascript
  // The map
  var map = new PerspectiveMap({
    target: 'map', // doesn't exists
```
