### ISSUE TITLE
Outdated build? Vite notifies about missing export in AnimatedCluster.js

### ISSUE THREAD

**Issue by Razi91** [Viglino/ol-ext#765]
```
✘ [ERROR] No matching export in "node_modules/ol-ext/util/ext.js" for import "ol_ext_olVersion"

    node_modules/ol-ext/layer/AnimatedCluster.js:15:9:
      15 │ import { ol_ext_olVersion } from '../util/ext'
         ╵          ~~~~~~~~~~~~~~~~

11:42:01 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/ol-ext/layer/AnimatedCluster.js:15:9: ERROR: No matching export in "node_modules/ol-ext/util/ext.js" for import "ol_ext_olVersion"
```
I get this error while I'm trying to use Vite for my project, but I find that this line doesn't exist in https://github.com/Viglino/ol-ext/blob/master/src/layer/AnimatedCluster.js . This line is not present even after build. Is there a missing release with this?

**Comment by Viglino** [comment]
Which version are you using?

**Comment by Razi91** [comment]
`"ol-ext": "^3.2.22",`, newest one on npm

**Comment by Viglino** [comment]
It seems there is a bug in the v3.2.22.
The line: `15 | import { ol_ext_olVersion } from '../util/ext'` is no more used and should be deleted.
You can delete it manually in the node_modules/ol-ext/layer/AnimatedCluster.js file.
I'll published a new version asap.

**Comment by Razi91** [comment]
Thanks. While I can remove this line locally, removing it manually wouldn't be comfortable

**Comment by Viglino** [comment]
I've push a new npm version olext@3.2.24

**Comment by Razi91** [comment]
Thanks, now there is no error :)
