### ISSUE TITLE
PrintDialogCtrl - Override print scales offered

### ISSUE THREAD

**Issue by NewToStuff** [Viglino/ol-ext#766]
Hi,

Is it possible to override or set the print scales offered from the drop down list. Ideally I want to be able to offer the options like those below. I am in an Angular environment (in case that limits some options)

Thanks for any help offered.

`
  this.printDialogCtrl.prototype.scales = {
      ' 100': '1/100',
      ' 200': '1/200',
      ' 500': '1/500',
      ' 1000': '1/1.000',
      ' 1250': '1/1.250',
      ' 2500': '1/2.500',
      ' 5000': '1/5.000',
      ' 10000': '1/10.000',
      ' 25000': '1/25.000',
      ' 50000': '1/50.000',
      ' 100000': '1/100.000',
      ' 250000': '1/250.000',
      ' 1000000': '1/1.000.000'
    };
`

**Comment by NewToStuff** [comment]
Hi,

Thanks for the hint. I have ran into a few issues. I am using Angular 12 with Typescript.


The following code;

ol_control_PrintDialog.prototype.scales = {
  ' 5000': '1/5.000',
  ' 10000': '1/10.000',
...
};
`
Triggers the following error TS2304: Cannot find name 'ol_control_PrintDialog'

I presume I need to declare or import it in some way. At the moment the code imports PrintDialog as follows.
`
import PrintDialog from 'ol-ext/control/PrintDialog';` 

I also tried to set the scales setting through PrintDialog.prototype.scales  but I then get the error:

error TS2739: Type '{ ' 5000': string; ' 10000': string; }' is missing the following properties from type '{ ' 
5000': string; ' 10000': string; ' 25000': string; ' 50000': string; ' 100000': string; ' 250000': string; ' 1000000': string; }': ' 25000', ' 50000', ' 100000', ' 250000', ' 1000000'

Do you have any further hints?

Many thanks.

**Comment by Viglino** [comment]
You have to use the import name:
```javascript
import PrintDialog from 'ol-ext/control/PrintDialog';

PrintDialog.prototype.scales = {
' 5000': '1/5.000',
' 10000': '1/10.000',
...
};
```

**Comment by NewToStuff** [comment]
Thanks.

I looked at it again. I continued to get the type error (as per earlier post). If I use @ts-expect-error then the compiled code works. It looks like the typings need updating but for now this workaround works.

  `
PrintDialog.prototype.scales = {
     // @ts-expect-error
      ' 100': '1/100',
      ' 200': '1/200',
      ' 500': '1/500',
      ' 1000': '1/1.000',
      ' 1250': '1/1.250',
      ' 2500': '1/2.500',
      ' 5000': '1/5.000',
      ' 10000': '1/10.000',
      ' 25000': '1/25.000',
      ' 50000': '1/50.000',
      ' 100000': '1/100.000',
      ' 250000': '1/250.000',
      ' 1000000': '1/1.000.000'
    };
`

Thanks for your help...
