### ISSUE TITLE
Unable to use WMS and WMTS capability control buttons in the same map

### ISSUE THREAD

**Issue by AlexGacon** [Viglino/ol-ext#767]
The WMTS control being implemented by inheritance of WMS control, it is currently not possible to have a button for each control in the same map : they are always overlapped, since the className for the button is the same.

It would be great to be able to have the possibility to use a different className for the button, in order to avoid overlapping.

**Comment by Viglino** [comment]
As any ol control, you can set the control className on creation:
```javascript
map.addControl(new ol.control.WMSCapabilities({ className: 'myClass' }))
```
Then you can use CSS to set the control position:
```CSS
.myClass {
  right: 5em;
}
```

**Comment by AlexGacon** [comment]
Ok I didn't see that the button reuse the className of the control for its own naming: I close the issue then.
