### ISSUE TITLE
TouchCursor

### ISSUE THREAD

**Issue by infokartasplit** [Viglino/ol-ext#769]
Hi Viglino
I am develiping an app in vue-layers by ghettovoice and i would like to use your TouchCursor.
I am having a problem with touchCursor going off map becouse i have some toolbers, header and footer. Is there a way to constrain touchCursor movement inside current extent or something like that
![touchCursor](https://user-images.githubusercontent.com/79648611/165532020-3dc6c959-a4f9-4c77-b4ef-916f40f8c0d8.png)
.

**Comment by Viglino** [comment]
There is no, you have to handle it by yourself...

**Comment by infokartasplit** [comment]
yea i did something similar. I created a buffer arround touchCursor. if i click outside buffer it recenters it on touched location
