### ISSUE TITLE
ol.RenderOrderFunction return number not boolean

### ISSUE THREAD

**Issue by ChouGary** [Viglino/ol-ext#77]
according to
https://github.com/openlayers/openlayers/pull/2251
ol.RenderOrderFunction return number not boolean

**boolean**
![image](https://user-images.githubusercontent.com/8294943/35659681-93f3b440-0742-11e8-8955-fa74671ccc20.png)
https://github.com/Viglino/ol-ext/blob/b6dc2faa9cb23473ee7b8172a0f1b0902f944bf6/utils/ol.ordering.js#L17

**number**
![image](https://user-images.githubusercontent.com/8294943/35659731-d2c4a10c-0742-11e8-8e41-2e9af6711c50.png)
ol.ordering.yOrdering = function(options)
{	return function(f0,f1)
	{	return f1.getGeometry().getExtent()[1] - f0.getGeometry().getExtent()[1] ;
	};
}

reference w3school array.sort
https://www.w3schools.com/jsref/jsref_sort.asp

**Comment by Viglino** [comment]
You're right!
I'll try to fix it asap.

**Comment by Viglino** [comment]
It should work now!
