### ISSUE TITLE
FillPattern produces disturbing visual movements when zooming / unzooming

### ISSUE THREAD

**Issue by Pigeo** [Viglino/ol-ext#770]
### Steps to reproduce:
1. Go to the [official example](https://viglino.github.io/ol-ext/examples/style/map.style.pattern.html)
2. In the options, change Pattern to "Image (PNG)" pattern (the last one, with green cubes) and increase the scale to 3 
    (NB: this is just in order to make those disturbing visual movements worse, and even more visible)
4. Zoom/unzoom the map and observe what happens within the triangle polygon
(CAUTION: I hope you're not photosensitive epileptic!)
5. Keep zooming in, until the screen is now totally covered by the pattern

### Problem vs. expected behaviour:
Each time you zoom/unzoom, the pattern is "moving", whereas it should be "stable" (taking as reference point the coordinates 0,0 of the corner of the map div), thus leading to annoying awkward visual effects.

This problem is generalised to all types of pattern available (you can try for ex. with hatches, angle 45°; spacing 20, scale 3), and seems to happen with any parameter values, though for some physico-cognitive reasons it became worse and worse at large scales (scale > 1).

**Comment by Viglino** [comment]
This is an Openlayers 'issue' (See https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html). 
The pattern origin is not the map div but the origin of the projection, that makes the pattern moving with the map while panning but shivering while zooming...
You can use a [VectorImage layer](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage.html) to prevent this effect and have a fixed image while zooming/dezooming.

**Comment by Pigeo** [comment]
Thank you for the tip! 
As you suggested, I replaced all occurrences of `ol.layer.Vector` with `ol.layer.VectorImage` and now it works like a charm :-)
Maybe you should consider putting a note about that in [ol-ext's documentation](https://viglino.github.io/ol-ext/doc/doc-pages/index.html) and/or adding an option to select between `ol.layer.Vector` and `ol.layer.VectorImage` in your [ol-ext Fill pattern demo](https://viglino.github.io/ol-ext/examples/style/map.style.pattern.html)? Because I'm probably not the only one concerned by this visual artefacts problems ;-)

**Comment by Viglino** [comment]
`ol.layer.VectorImage` has it's own drawback (point symbols are not rotated) and it depends on how you use it...

**Comment by Pigeo** [comment]
Yes, that's why I moved all my point symbols to a separate layer sharing the same `Source` ;-)
