### ISSUE TITLE
The colorization filter does not apply to a single layer but to the whole map

### ISSUE THREAD

**Issue by mbarbet** [Viglino/ol-ext#771]
Line 87 of the code below seems never call and the addToLayer function does not seem to exist for a filter.

![Capture d’écran 2022-04-28 à 12 38 20](https://user-images.githubusercontent.com/9316927/165734870-241866d5-3500-4de0-9304-f38eb5b01923.png)

**Comment by Viglino** [comment]
It depends on the filter type: `addToLayer` is a method for [`ol/filter/CSS`](https://github.com/Viglino/ol-ext/blob/master/src/filter/CSS.js#L63)
Such filter has no rendering function but applies a CSS filter to the layer element.

**Comment by Viglino** [comment]
Yes it is possible but you have to add a className on the layer at creation.
Otherwise layers will be grouped on a single element.

**Comment by mbarbet** [comment]
Thanks !!
