### ISSUE TITLE
LayerSwitcher  image layer button

### ISSUE THREAD

**Issue by fbmfbm** [Viglino/ol-ext#774]
Hello all,
I'm lookin the way to switch the button icon in layerSwitcher image to use current map Image for  the switcher button in place of the icon.
Is there a way or do i work with javascript to get hidden pictur in switcher panel to swith on the button ?

Thanlk's a lot for your help !

**Comment by Viglino** [comment]
You can change it using CSS.
See example: https://viglino.github.io/ol-ext/examples/control/map.switcher2.html

**Comment by fbmfbm** [comment]
Hi Jean Marc,
Thank's for your answer. Yes, i know, i have halready change icon and customise the panel with mapswitcherImage but how to use selected map thumbnail in place of  main icon ?
Thank's for your work.

**Comment by Viglino** [comment]
You have to do it by yourself.
You can access the controrl element using the element propertiy of the control:
```javascript
const ctrl = new LayerSwitcher();
// add an image to the button
const img = new Image();
const ctrlBt = ctrl.element.querySelector('button');
ctrlBt.appendChild(img);
// Set image
img.src = my_image_url;
```

**Comment by fbmfbm** [comment]
Ok,I understand.
Thank's.
