### ISSUE TITLE
Can't open the same pop up after clicking the "X" close button

### ISSUE THREAD

**Issue by luchontandil** [Viglino/ol-ext#775]
You can replicate it [Here](http://viglino.github.io/ol-ext/examples/popup/map.popup.html)
Tested on mozilla/chrome win10

As the tittle says, "Can't open the same pop up after clicking the "X" close button" but it does work when clicking outside the popup

Any way to make my own close button? what event should i be calling?

**Comment by Viglino** [comment]
The popup only opens on selection. When closing the popup the feature remains selected, you have to deselect it on close.
```javascript
popup.on('hide', function() { select.getFeatures().clear() }) 
```

**Comment by luchontandil** [comment]
Thxs, that was fast and on point.
you are the mvp
