### ISSUE TITLE
The DrawTouch interaction does not remove the canvas element with the ol-fixedoverlay class

### ISSUE THREAD

**Issue by bojanbizjak** [Viglino/ol-ext#778]
When I remove the DrawTouch interaction with map.removeInteraction, the canvas with the ol-fixedoverlay class remains in the map.

ol: 6.14.1
ol-ext: 3.2.24
Android 12: WebView (101.0.4951.61

The image shows the state after the call to the map.removeInteraction function.
![Screenshot 2022-05-18 at 22 14 35](https://user-images.githubusercontent.com/12731463/169148003-362508a9-8438-45cf-9b54-1ec9053e584e.png)
)

**Comment by Viglino** [comment]
DrawTouch interaction doesn't handle fixed overlay.
FixedOverlay is a canvas to display canvas control on the map...

**Comment by bojanbizjak** [comment]
The only problem is that if this canvas element is present, the classic OpenLayers popup is no longer displayed in the right location but below the bottom edge of the map. Now we simply remove the element from the DOM and it is OK.

**Comment by Viglino** [comment]
This issue should be fixed see #721 & #722
