### ISSUE TITLE
WMTS Capabilities Control not compatible with OGC norm

### ISSUE THREAD

**Issue by AlexGacon** [Viglino/ol-ext#780]
Hello,

In the OGC norm of WMTS, the legend element of a style is not mandatory:
<element ref="wmts:LegendURL" minOccurs="0" maxOccurs="unbounded">
<annotation>
<documentation>Description of an image that represents the legend of the map</documentation>
</annotation>
</element>

The WMTS Capabilities Control requires to have such an element, making it not usable with GeoServer when working with layer groups.

**Comment by AlexGacon** [comment]
@Viglino any date for the next release ?

**Comment by Viglino** [comment]
ol-ext@3.2.25 is on the rail!

**Comment by AlexGacon** [comment]
My fix is not enough. I keep the issue opened.

**Comment by AlexGacon** [comment]
@Viglino any date for the release ?

**Comment by Viglino** [comment]
ol-ext@3.2.26 is out: https://www.npmjs.com/package/ol-ext
