### ISSUE TITLE
LayerSwitcherImage Button Icon Customization

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#788]
In https://github.com/Viglino/ol-ext/issues/787 it was nicely explained how to change the icon of the LayerSwitcher to a similar look like the control bar buttons via:
`/* Reset CSS */
.ol-layerswitcher.mySwitcher > button {
  font-size: 1em;
  background-color: rgba(0,60,136,.5);
} 
.ol-layerswitcher.mySwitcher > button:before, 
.ol-layerswitcher.mySwitcher > button:after {
  all: unset;
}
/* Your own button */
.ol-layerswitcher.mySwitcher > button:before {
  content: 'A'
}`

However, I am too stupid to transfer this knowledge to the LayerSwitcherImage button.
Could someone give me an example what has to be changed (via CSS) to get the LayerSwitcherImage button to look like the other icons used in control bars?

Thanks a lot in advance.

**Comment by Viglino** [comment]
The layer switcherImage button still use a background-image as icon.
You just have to remove it in your CSS.
```CSS
.ol-layerswitcher-image button {
  background-image: none;
```
