### ISSUE TITLE
Fontawesome Icons lost in http://viglino.github.io/ol-ext/ (Examples)

### ISSUE THREAD

**Issue by darkscript** [Viglino/ol-ext#79]

**Comment by darkscript** [comment]
Am not sure if the icons are also lost in the controls

**Comment by Viglino** [comment]
Hey! Font Awesome is changing and the css is no more reachable...
I'll try to find out where we can plug to load the css and change the link in the examples...

**Comment by Viglino** [comment]
Anyway there may be an issue on loading the font definition with ES6 syntax.

**Comment by Viglino** [comment]
I've change to [cdnjs](https://cdnjs.com/libraries/font-awesome).
Examples are running
