### ISSUE TITLE
Support switcherClass option in LayerPopup

### ISSUE THREAD

**Issue by Siedlerchr** [Viglino/ol-ext#790]
Hi,

I just wanted to add a second LayerPopup control on my map. However, as I am styling them via css I noticed that I could not change the class of the layerPopup and noticed it was fixed and therefore my second LayerPopup is rendered atop the first one.

https://github.com/Viglino/ol-ext/blob/2193e6402d49991bdf33225e2b8705690ee86366/src/control/LayerPopup.js#L18

**Comment by Viglino** [comment]
I've added a `switcherClass` option in the last commit
