### ISSUE TITLE
edit.getInteraction('DrawLine') Distance (ol-ext: Measure tooltips)

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#794]
hi Viglino,

can i check with you for DrawLine in EditBar  or (ol-ext: Measure tooltips ) able to get the measuremenet  of the draw ? as base on the code

1. Measuring Tooltips 
`  drawLine.on('drawstart', tooltip.setFeature.bind(tooltip));`

2. EditBar
`tooltip.setFeature(e.feature);
      tooltip.setInfo('Click to continue drawing line...');`

can i set it into a variable?

**Comment by Viglino** [comment]
`tooltip.get('measure')` lets you get the current measure.
If you want to get the measurement of the final object use [ol/sphere](https://openlayers.org/en/latest/apidoc/module-ol_sphere.html)
```javascript
ol.sphere.getLength(feature.getGeometry())
```

**Comment by ngjiajunsg** [comment]
Hi Viglino,

i try using both, i unable to console.log or set it into any variable..

wonder where did i do wrong

https://codepen.io/ngjiajun/pen/ZErqjwV

line 84: i doing tooltip.get('measure');

`drawLine.on('drawstart', console.log('Measurement: ' + tooltip.get('measure')));`

Line 85 to 87 is i try to do ol.sphere.getLength(feature.getGeometry())

`     drawLine.on('drawstart', function(e){
       console.log('Measurement (Final): ' + ol.sphere.getLength(e.feature.getGeometry()))
     });`

**Comment by ngjiajunsg** [comment]
for Area the below code does not seem to work?

`drawPoly.on(['drawend'], function(e){
       
         var length = ol.sphere.getDistance( ol.proj.toLonLat(e.startCoordinate), ol.proj.toLonLat(e.coordinate) );
       tooltip.set('measure', tooltip.formatLength(length));
       console.log('Measurement (Final): ' +  tooltip.formatLength(length))
     });`

**Comment by ngjiajunsg** [comment]
> You have to listen to the drawend event to get the full geometry when drawn (drawstart is only the point starting point).
> 
> ```js
>      drawLine.on(['drawstart','drawend'], function(e){
>        console.log('Measurement (Final): ' + ol.sphere.getLength(e.feature.getGeometry()))
>      });
> ```

thanks i also do for my drawPoly 


```
drawPoly.on(['drawend'], function(e){
       var area = ol.sphere.getArea(e.feature.getGeometry());
       console.log('Measurement (Final): ' +  tooltip.formatArea(area));
     });
```

**Comment by Viglino** [comment]
To have something appear, you have to tell the tooltip what to display:
```javascript
 tooltip.setInfo(myInfoText)
```
In your case you should probably want to display the measurement instead of just login it line 122:
```javascript
 tooltip.setInfo('Measurement (Final): ' +  tooltip.formatArea(area));
```

**Comment by ngjiajunsg** [comment]
Hi Vilgino, can check with you the code above does the same as 

https://openlayers.org/en/latest/examples/measure.html

As I looking into multiple linestring and polygon to display the measurement reading . But seem like does not work at all

**Comment by ngjiajunsg** [comment]
Hi Viglino,

do you have any idea on how to create like this . need your advise?

**Comment by Viglino** [comment]
You have to follow the example on https://openlayers.org/en/latest/examples/measure.html
