### ISSUE TITLE
featureAnimation.hiddenStyle cannot use custom icons（.png）

### ISSUE THREAD

**Issue by starsyrt** [Viglino/ol-ext#795]
const styleTriangle = [new ol.style.Style({
			image: new ol.style.Icon({
				//   anchor: [0.5, 1],
				src: './car3.png',
			})

		})];

**Comment by Viglino** [comment]
Do you have a working example?

**Comment by starsyrt** [comment]
Thanks for your reply.I have found a solution from the previous issue.
`const iconStyle= new ol.style.Icon({
  src: url
});
iconStyle.load();
const style = new ol.style.Style({
  image: iconStyle
});
`
