### ISSUE TITLE
SearchFeature Control Search Result Sort

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#796]
i have a vectorsource that is sort by ID

for example

AA1
AA2
AA3
AA4
BB1
BB2
BB3
BB4
BB5

but when i Type AA in the search bar it return as below

AA4, AA2, AA1, AA3

instead of 

AA1, AA2, AA3, AA4

wonder is there anything can sort the search result?

**Comment by Viglino** [comment]
You have to overwrite the autocomplete function of the search to add a sort on the result.
```javascript
var search = new ol.control.SearchFeature(...);
search.autocomplete = function(s) {
  // Call default search
  var result = ol.control.SearchFeature.prototype.autocomplete.call(this, s);
  result = result.sort(function(f1, f2) {
    if (search.getSearchString(f1) < search.getSearchString(f2)) return -1;
    if (search.getSearchString(f1) > search.getSearchString(f2)) return 1;
    return 0;
  });
  return result;
}
```

**Comment by ngjiajunsg** [comment]
Hi Viglino,

can i check with you if i Search the Feature i wish to have and zoom into the feature can i remain the search result in the inputbox? if yes how should i do it?

**Comment by Viglino** [comment]
```javascript
// Set the value in the search input
search.setInput('my search value')
```
Read the doc: https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Search.html#setInput__anchor
You have to listen to `select` event to change it on select:
```javascript
// Set the search input value on select
search.on('select', (e) => search.setInput(search.getTitle(e.search)))
```

**Comment by ngjiajunsg** [comment]
Thanks
