### ISSUE TITLE
translate selected polygons programatically (New feature request)

### ISSUE THREAD

**Issue by abhijitgujar86** [Viglino/ol-ext#797]
It will be good and very handy function if we can move (translate)  the selected polygon to some location latlng . 

example :

transformInteraction.MoveTo([latitude,longitude])

notes: 
All selected features should be moved.

**Comment by Viglino** [comment]
There is a [`translate`](https://openlayers.org/en/latest/apidoc/module-ol_geom_Geometry-Geometry.html#translate) method on Openlayers geometry.  You just have to loop on selected features...
