### ISSUE TITLE
PopupFeature With Link to popup

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#798]
Hi Viglino,

there are two parts in my question.

1. My PopupFeature Information has many records resulted the Display as below can i expand it and show all the information
XXXX[...]
2. Can i have my Records in PopupFeature that has a link to open another PopupFeature to display the information of the record in more details

**Comment by Viglino** [comment]
PopupFeature is designed to display feature properties. Maybe you can design your own Popup to display what you want to.
See http://viglino.github.io/ol-ext/examples/popup/map.popup.html
