### ISSUE TITLE
Display chart in popup window?

### ISSUE THREAD

**Issue by sharseema** [Viglino/ol-ext#80]
Hi,
I saw chart [link](http://viglino.github.io/ol-ext/examples/style/map.style.chart.html) example.Is it possible to show bar chart in popup,if i clicked on any feature of layer.

I have one district boundary layer which is in json format .If i clicked on any district then show the builtup chart of district in popup.I tried with D3 but its not working,getting all district at a time.

Thanks.

**Comment by Viglino** [comment]
ol.style.Chart are intended to be used on a map.
If you want to display charts in a popup, you can use any library that create html charts (for example https://github.com/chartjs/Chart.js).
Popups are overlays in HTML that can include any information (images, charts, etc.).

**Comment by sharseema** [comment]
Hi,
I tried chart using D3.js. I don't understand how i apply ol.style.Chart using ol3 ,actually i have data in csv as well as json file format.This is code [Link](https://codepen.io/seema30fresher/pen/RQKvVP?editors=1010) chart using ol3 with D3.

**Comment by sharseema** [comment]
Hey please if you have any idea,Please help me,i stuck here.

**Comment by Viglino** [comment]
Hi,
As I said, ol.style.Chart only draw on the map, not in a popup.
In your example it seems you don't include the js in the right order: jQuery must be loaded first before bootstrap. If you do that you will see charts when moving on the map. (https://codepen.io/viglino/pen/YerbOa)
I don't know if it what you're intended to do. Perhaps you should look at the popup example to display popup on the map.
@+

**Comment by sharseema** [comment]
Hi,
I have done popup on map and working properly.I have district data but it is in two different formats (Json and CSV).So json file is used in OL3 and CSV file used in d3 to show the chart.Both files are having same attributes with same name.In this code  [Link](https://codepen.io/viglino/pen/YerbOa?editors=1010) , If user clicked on any district ,Popup chart  will appear and inside popup chart , district name will change on x-Axis but the y-Axis value(B_75,B_90,B_2000,B_14) is not changing , only taking any random values and its constant .The y-Axis value is not iterating according to District name.

Or is there any other way to i embed charts in OL3 popup.

Thanks

**Comment by Viglino** [comment]
Hi,
You can find an example using ol-ext popup with d3: https://codepen.io/viglino/pen/VQGjmJ
@+

**Comment by sharseema** [comment]
Hi,
Thanks a lot for help,its nice.Can i use your js  (ol-ext.min.js) and css file in my code.Everything is working fine but y-axis data remain same for all district.Y axis data not changing,its taking only initial column for all district,not iterating data. 
Thanks.

**Comment by Viglino** [comment]
You can use the code it is under the BSD license, free for all your project.
