### ISSUE TITLE
No Linestring display when drawend for Drawline

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#807]
Hi Viglino,

can check with you why my LineString is disappear when drawend method is trigger

 ```
   edit.getInteraction('DrawLine').on('drawend', function(e) {

      var length = ol.sphere.getLength(e.feature.getGeometry());
      console.log('Measurement (Final): ' + tooltip.formatLength(length));
      edit.getInteraction('DrawLine').setActive(false);
      var results = tooltip.formatLength(ol.sphere.getLength(e.feature.getGeometry()));
      var positions = e.feature.getGeometry().getLastCoordinate();
      e.feature.set('length', results);
   
    });
```
the code is at here [https://codepen.io/ngjiajun/pen/XWZxPGK](url)

**Comment by mike-000** [comment]
Your vector layer has no stroke style except for text stroke - either add a stroke style directly to the labelStyle
https://codepen.io/mike-000/pen/oNqvEeM or add a separate LineString style with stroke to the array.

**Comment by ngjiajunsg** [comment]
thank Mike

**Comment by ngjiajunsg** [comment]
> Your vector layer has no stroke style except for text stroke - either add a stroke style directly to the labelStyle https://codepen.io/mike-000/pen/oNqvEeM or add a separate LineString style with stroke to the array.

hi [mike-000](https://github.com/mike-000), can check with you for drawpoint i unable to create? issit due to the style?
