### ISSUE TITLE
Editbar Delete Function

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#808]
Hi viglino,

can i check if i want to restrict the delete of the feature if my function check will see whether is the feature able to delete anot?

the concept is the same as ModifySelect but this time is at delete function

```
edit.getInteraction('ModifySelect').setFilter(function(f) { 
   if (isModif(f)) return true;
   else return false;
})
```

my code for delete is this but seem like no matter what it will alway delete.

```
edit.getInteraction('Delete').on('deletestart', function(e){
 var feature = e.features.item(0);
 var name = feature.get('name'):

if (name!==""){
 //stop delete
return false;
}
});
```

**Comment by Viglino** [comment]
You have to create your own delete button... there is no way to stop deletion...

**Comment by ngjiajunsg** [comment]
ok. thanks.. i will remove the delete button and recreate my own delete button thanks
