### ISSUE TITLE
Using AnimatedCluster with olStyle.Icon svg

### ISSUE THREAD

**Issue by nerdess** [Viglino/ol-ext#809]
I am using ol-ext within my React project on a clustered source. 

When a cluster only contains one single feature an svg icon gets displayed. However, this is causing problems when using an AnimatedCluster.

This is the style definition that causes the error below when zooming in on the AnimatedCluster layer: 

```
import * as olStyle from 'ol/style';
import AnimatedCluster from 'ol-ext/layer/AnimatedCluster';

....

new olStyle.Style({
        image: new olStyle.Icon({
            src: ICONS[kate_tag || 'uncategorized'].src, //some svg image 
            scale: getScale(resolution)
        }),
})

...
```
<img width="1276" alt="Bildschirmfoto 2022-06-27 um 11 54 30" src="https://user-images.githubusercontent.com/711925/175916104-72fe0583-d878-4984-8269-ee499a4acdce.png">

PS: I can provide a proper fiddle if needed

**Comment by Viglino** [comment]
Need more code in a fiddle...

**Comment by Viglino** [comment]
This example use cluster and icons: https://viglino.github.io/ol-ext/examples/map/map.clustering.html
