### ISSUE TITLE
Is (ol-ext) version compatible with OpenLayers v6.14 

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Viglino/ol-ext#810]
Hi @Viglino 

I am considering testing that extension with my project and was wondering if there is anything that has tested it with OpenLayers v6.14 and about what minimum version it requires.

I see in[ Yarn Change log](https://yarnpkg.com/package/ol-ext#:~:text=Collapse-,changelog,-Change%20log)
Next version will be Move to ol v6, are they done, or you still work on it ?

**Comment by Viglino** [comment]
Examples are running on the last ol version https://viglino.github.io/ol-ext/

**Comment by Siedlerchr** [comment]
I can confirm that it works fine with the latest version of ol 6

**Comment by Bahaa-Fadhil** [comment]
**Hi @Siedlerchr & @Viglino, and thank you for your reply!**

I have installed the [ol-ext package from yarn](https://yarnpkg.com/package/ol-ext), but get an error message, see below

```
Could not find a declaration file for module 'ol-ext/interaction/DragOverlay'.  
 ......./node_modules/ol-ext/interaction/DragOverlay.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ol-ext` if it exists or add a new declaration (.d.ts) 
file containing `declare module 'ol-ext/interaction/DragOverlay';`
```
  
  
  also I have to install Type definitions for [types-ol-extpackage from yarn here,](https://yarnpkg.com/package/@siedlerchr/types-ol-ext) but also get an error message, see below:
  
  
```
   yarn add -D @types/ol-ext@npm:@siedlerchr/types-ol-ext
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @types/ol-ext@npm:@siedlerchr/types-ol-ext isn't supported by any available resolver
```


Do you have suggestions on how to solve that problem ?

**Comment by Siedlerchr** [comment]
Yes, the first one is correct. Because ol-ext has to type defs. 
The second one seems to be some yarn issue https://github.com/yarnpkg/berry/issues/1621 
Seems like you can try to add it this way https://github.com/yarnpkg/berry/issues/1621#issuecomment-669136172

**Comment by Bahaa-Fadhil** [comment]
OK, found out what's the problem in this case. We need to specify the package version at the end so that yarn can solve this problem.

**Exs:**
`yarn add -D @types/ol-ext@npm:@siedlerchr/types-ol-ext@^2.1.0`
or
`yarn add -D @types/ol-ext@npm:@siedlerchr/types-ol-ext@latest`
