### ISSUE TITLE
Target control behaviour is different from the example

### ISSUE THREAD

**Issue by juhakip** [Viglino/ol-ext#811]
I made a small Angular project following the ol-ext Angular example. I tried to add the target control and succeeded, but the crosshair icon is always at coordinates 0,0. So when I center the map for example to New York, the crosshair stays in the Atlantic Ocean near Africa. How to make it work like in the Javascript example, so that the crosshair follows the map when the user moves the map or zooms in and out?

**Comment by Web-Geo-Portal** [comment]
Please share code here

**Comment by juhakip** [comment]
I had copied some map code from elsewhere and it had a different projection. Removing useGeographic() call from the copied code fixed the issue.
