### ISSUE TITLE
How to import ol/source/DayNight in Angular 14

### ISSUE THREAD

**Issue by Web-Geo-Portal** [Viglino/ol-ext#814]
I am trying to import ol/source/DayNight from angular.
Its show error can't find module.
npm i ol-ext already done

**Comment by Viglino** [comment]
this should work:
```javascript
import DayNight from 'ol-ext/source/DayNight'
```

**Comment by Web-Geo-Portal** [comment]
> this should work:
> 
> ```js
> import DayNight from 'ol-ext/source/DayNight'
> ```

Thanks so much

**Comment by Web-Geo-Portal** [comment]
Can you please share DayNight code with Angular 13?

**Comment by Viglino** [comment]
Something like that:
```javascript
import DayNight from 'ol-ext/source/DayNight'
import VectorLayer from 'ol-ext/layer/Vector'

const layer = new VectorLayer ({
  source: new DayNight ({ time: new Date() })
}
map.addLayer(layer);
```

**Comment by Web-Geo-Portal** [comment]
import VectorLayer from 'ol-ext/layer/Vector' not available

**Comment by govindpal5101999** [comment]
import DayNight from 'ol-ext/source/DayNight'.
It is also not working how to import DayNight.....it is showing this error  
 Try `npm i --save-dev @types/ol-ext` if it exists or add a new declaration (.d.ts) file containing `declare module 'ol-ext/source/DayNight'

**Comment by Viglino** [comment]
> import VectorLayer from 'ol-ext/layer/Vector' not available

VectorLayer is an ol class you have import it from the right lib: import VectorLayer from 'ol/layer/Vector' 
See https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html

**Comment by Viglino** [comment]
> import DayNight from 'ol-ext/source/DayNight'. It is also not working how to import DayNight.....it is showing this error Try `npm i --save-dev @types/ol-ext` if it exists or add a new declaration (.d.ts) file containing `declare module 'ol-ext/source/DayNight'

you have to install definition type:
`npm i -D @types/ol-ext@npm:@siedlerchr/types-ol-ext`
or add a new declaration (.d.ts) file containing `declare module 'ol-ext/source/DayNight'
