### ISSUE TITLE
Property 'show'& "hiden" does not exist on type 'FixedPopup'

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Viglino/ol-ext#816]
Hi @Viglino & @Siedlerchr  ,

Several Properties are missing in the "FixedPopup" class. If you look at popup class then it has these properties but in "FixedPopup" class is missing. Here are the ones that are missing:

-  @fires show :  show(coordinate: Coordinate | string, html?: string): void;
-  @fires hide :  hide(): void;
- onclose, 
- onshow , 
- getVisible() ,
- removePopupClass(c: string): void;
- positioning: does not accept string, only typeof OverlayPositioning
- show(coordinate: Coordinate | string, html?: string): void; show method can accept HTML Element, and not only as string

The overlay/popup/fixedPopup should have ID as property also, that is missing too!

But in general it seems that fixed Popup class lacks property such as overlay and popup class

`export default **class FixedPopup** extends Overlay {
    constructor(options?: Options);

    /**
     * Set the map instance the control is associated with
     * and add its controls associated to this map.
     * @param {_ol_Map_} map The map instance.
     */
    setMap(map: _ol_Map_): void;

    /** Set pixel position
     * @param {ol.pixel} pix
     * @param {string} position top/bottom/middle-left/right/center
     */
    setPixelPosition(pix: Pixel, position: string): void;
    /** Set pixel position
     * @returns {ol.pixel}
     */
    getPixelPosition(): Pixel;
    /**
     * Set the CSS class of the popup.
     * @param {string} c class name.
     * @api stable
     */
    setPopupClass(c: string): void;
    /** Set poppup rotation
     * @param {number} angle
     * @param {booelan} update update popup, default true
     * @api
     */
    setRotation(angle: number, update: boolean): void;
    /** Set poppup scale
     * @param {number} scale
     * @param {boolean} update update popup, default true
     * @api
     */
    setScale(scale: number, update: boolean): void;
    /** Set link style
     * @param {Style} style
     */
    setLinkStyle(style: Style): void;
    /** Get link style
     * @return {Style} style
     */
    getLinkStyle(): Style
}
`

**Comment by Siedlerchr** [comment]
Hi, can you please move this issue to the repo here? https://github.com/Siedlerchr/types-ol-ext 
Type related issues are there

**Comment by Bahaa-Fadhil** [comment]
> Hi, can you please move this issue to the repo here? https://github.com/Siedlerchr/types-ol-ext Type related issues are there


This  issue has been moved to : https://github.com/Siedlerchr/types-ol-ext/issues/89

**Comment by Bahaa-Fadhil** [comment]
Thanks for fixes: https://github.com/Siedlerchr/types-ol-ext/issues/89
