### ISSUE TITLE
Customization of FontSymbol (CSS)

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#817]
Hello,

currently I'm using a FontSymbol of the form "bubble" which works fine.
However, I would like to fill the small arrow with the border color, that the result looks similar to the attached image. Is this somehow possible via CSS?

<img width="289" alt="fontsymbol" src="https://user-images.githubusercontent.com/2078784/178120632-82ca2c93-3754-456a-b55b-0ff4c779ae11.png">

PS: My main problems with using ol-ext is finding the correct CSS elements to adapt the styles to my needs. Is there any good help for this?

**Comment by Viglino** [comment]
FontSymbol doesn't use CSS, it's not an HTML element, it is drawn in a canvas...

**Comment by thn80** [comment]
Thanks for clarification.

In this case, let me ask in other words:
I have a vector layer with a lot of markers. Different groups of markers shall have different colors and based on the group, some markers shall contain a FontAwesome symbol, while others shall contain a svg image.
Furthermore, I would like to have a marker design as shown in the screenshot above (if possible....otherwise I will stay with the standard marker design).
It would be nice, if the markers would have exactly the same marker design, except the included Font symbol or svg.

How would you implement this?

**Comment by Viglino** [comment]
Just create a font with your svg and add them as FontSymbols...
You can use something like Fontello (https://fontello.com/) to generate a font with your svg.
You also have to create a font definition file to match char code and symbol name (something like: https://github.com/Viglino/ol-ext/blob/master/dist/extra/FontAwesomeDef.js)
