### ISSUE TITLE
Possible deprecated feature in use: Event.Path

### ISSUE THREAD

**Issue by gio-giu** [Viglino/ol-ext#819]
Hi, a simple question: I am using ol-ext for a project of mine. However, when I use functions like the one below:

```
        map.on('singleclick', function (event) {
            const name = map.forEachFeatureAtPixel(event.pixel, function (feature) {
                return feature.get('name');
            });
        });
```

The following warning appears in my browser's console:

![Screenshot 2022-07-13 225800](https://user-images.githubusercontent.com/103177323/178942087-7b966ece-a1ec-4cda-80e1-2c598ba5e4e0.png)

Is it safe to keep using such method? If not, will it be corrected anytime soon?

**Comment by Viglino** [comment]
The code you shared doesn't use ol-ext...
It's a pure Openlayers function.
What version of Openlayers are you using?

**Comment by gio-giu** [comment]
Hi, thank you for you kind reply, and my apologize for the mistake.
The OpenLayers version I am using is the latest, v6.15.1, as contained in this CDN:
[cdn](https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js)

This message appears among the issues in Google Chrome's console...
