### ISSUE TITLE
Map compass image on map not visible

### ISSUE THREAD

**Issue by shiva-heliware** [Viglino/ol-ext#820]
[ol-ext](https://github.com/Viglino/ol-ext)/[examples](https://github.com/Viglino/ol-ext/tree/master/examples)/[canvas](https://github.com/Viglino/ol-ext/tree/master/examples/canvas)/map.control.compass.html

I am unable to see map compass on OSM map.

**Comment by Viglino** [comment]
Can see it on the example:
![image](https://user-images.githubusercontent.com/7868217/179688332-f011731a-c064-4c86-93bb-1e61e217022c.png)

What browser are you using?

**Comment by shiva-heliware** [comment]
currently I am using chrome browser

**Comment by shiva-heliware** [comment]
I am writing my code Angular and below are my .ts file code for  compass on map

import { Component } from '@angular/core';

import Map from 'ol/Map';
import view from 'ol/View';
import { defaults } from 'ol/control';
import tilelayer from 'ol/layer/Tile';
import OSM from 'ol/source/OSM';
import Compass from 'ol-ext/control/Compass';
import { Stroke } from 'ol/style';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'olcompass';
 
  constructor() {}

  map: any
  compass: any
  compassBottom: any

  ngOnInit(): void {
    this.map = new Map({
      target: 'map',
      view: new view({
        zoom: 8,
        center: [270148, 6247782]
      }),
      controls: defaults({
        zoom: false,
        attribution: true,
        rotate: true
      }),
      layers: [new tilelayer({
        source: new OSM(),
        visible: true
      })]

    })
  }
  // Compass control

  setCompass(e: any) {
    console.log();

    console.log("uhbcshudbc", this.map);
    if (this.compass) { this.map.removeControl(this.compass) };
    if (this.compassBottom) this.map.removeControl(this.compassBottom);
    var top = document.getElementById('top')
    console.log(top, "top===>")
    var line = document.getElementById('line')
    console.log(line, "line===>")
    if (top) {
      this.compass = new Compass({
        className: "top",
        src: '/assets/images/piratecontrol.png',
        rotateWithView: $("#rotate").prop("checked"),
        style: new Stroke({ color: $("#color").val(), width: ($("#line").prop("checked") ? 1 : 0) })
      

      });
      this.compass._style.zIndex_ = 1;
      this.compass._style.opacity = 1000;
      console.log("this.compass", this.compass)
      this.map.addControl(this.compass);
    }

    else this.compass = false;
    this.compassBottom = new Compass({
      className: "bottom",
      src: '/assets/images/piratecontrol.png',
      rotateWithView: $("#rotate").prop("checked"),
      style: new Stroke({ color: $("#color").val(), width: ($("#line").prop("checked") ? 1 : 0) })
      
    });
    this.compassBottom._style.zIndex_ = 1000;
    console.log("this.compassBottom", this.compassBottom)
    this.map.addControl(this.compassBottom);
  }








}

**Comment by shiva-heliware** [comment]
I am writing my code in Angular and below are the .ts , .css , .html files

**Comment by shiva-heliware** [comment]
this is the  .ts file:----


import { Component } from '@angular/core';

import Map from 'ol/Map';
import view from 'ol/View';
import { defaults } from 'ol/control';
import tilelayer from 'ol/layer/Tile';
import OSM from 'ol/source/OSM';
import Compass from 'ol-ext/control/Compass';
import { Stroke } from 'ol/style';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'olcompass';
 
  constructor() {}

  map: any
  compass: any
  compassBottom: any

  ngOnInit(): void {
    this.map = new Map({
      target: 'map',
      view: new view({
        zoom: 8,
        center: [270148, 6247782]
      }),
      controls: defaults({
        zoom: false,
        attribution: true,
        rotate: true
      }),
      layers: [new tilelayer({
        source: new OSM(),
        visible: true
      })]

    })
  }
  // Compass control

  setCompass(e: any) {
    console.log();

    console.log("uhbcshudbc", this.map);
    if (this.compass) { this.map.removeControl(this.compass) };
    if (this.compassBottom) this.map.removeControl(this.compassBottom);
    var top = document.getElementById('top')
    console.log(top, "top===>")
    var line = document.getElementById('line')
    console.log(line, "line===>")
    if (top) {
      this.compass = new Compass({
        className: "top",
        src: '/assets/images/piratecontrol.png',
        // rotateWithView: $("#rotate").prop("checked"),
        // style: new Stroke({ color: $("#color").val(), width: ($("#line").prop("checked") ? 1 : 0) })
        style: new Stroke({ color: 'black', width: (line ? 1 : 0) })

      });
      this.compass._style.zIndex_ = 1;
      this.compass._style.opacity = 1000;
      console.log("this.compass", this.compass)
      this.map.addControl(this.compass);
    }

    else this.compass = false;
    this.compassBottom = new Compass({
      className: "bottom",
      src: '/assets/images/piratecontrol.png',
      // rotateWithView: $("#rotate").prop("checked"),
      // style: new Stroke({ color: $("#color").val(), width: ($("#line").prop("checked") ? 1 : 0) })
      style: new Stroke({ color: 'black', width: (line ? 1 : 0) })
    });
    this.compassBottom._style.zIndex_ = 1000;
    console.log("this.compassBottom", this.compassBottom)
    this.map.addControl(this.compassBottom);
  }








}

**Comment by shiva-heliware** [comment]
this is .html file:----

<div id="map" style="width:2000px; height:400px;"></div>

<div class="options">
  <h2>Options:</h2>
  <ul>
    <li>
      Color:
      <select id="color" change="setCompass();">
        <option value="#963">brown</option>
        <option value="red">red</option>
        <option value="green">green</option>
        <option value="blue">blue</option>
        <option value="gray">gray</option>
      </select>
    </li>
    <li>
      Image:
      <select id="image" change="setCompass();">
        <option value="./assets/images/piratecontrol.png" style="display: block!important;">Pirate</option>
        <option value="default">default</option>
        <option value="compact">compact</option>
      </select>
    </li>
    <li>
      <input id="line" type="checkbox" (change)="setCompass($event);"  checked/><label for="line">
        showlines</label>
    </li>
    <li>
      <input id="rotate" type="checkbox" (change)="setCompass($event);" /><label for="rotate"> rotate
        with view</label>
    </li>
    <li>
      <input id="top" type="checkbox" (change)="setCompass($event);" /><label for="top"> display 2
        controls</label>
    </li>
  </ul>
</div>


<router-outlet></router-outlet>

**Comment by shiva-heliware** [comment]
this is .css file:---

.options {
    background: #def;
    display: table;
    width: 15rem;
    padding: 0.5em;
    margin-top: 0.5em;
   
   
}


.ol-compassctrl.top {
    top: 50%;
    left: 0;
    width: 100px;
    height: 100px;

    -webkit-transform: translate(0, -50%);
    transform: translate(0, -50%);
}

.ol-compassctrl.bottom {
    top: auto;
    left: auto;
    bottom: 0;
    right: 0;
    width: 150px;
    height: 150px;

    -webkit-transform: none;
    transform: none;
}
.ol-compassctrl.ol-visible {
    display: block!important;
}
/* .ol-viewport canvas.ol-fixedoverlay {
    position: absolute;
    top: 0;
    left: 0;

    width: 100%;
    height: 100%;
} */

**Comment by shiva-heliware** [comment]
and this is my result  on chrome browser:---

![image](https://user-images.githubusercontent.com/104834374/180363246-4bfa88f0-4fee-4546-8fae-324630e46e89.png)

**Comment by Viglino** [comment]
Are you sure the CSS is applied to the control?
Have you included the ol and ol-ext CSS?

**Comment by shiva-heliware** [comment]
thank u for the help, error is solved
