### ISSUE TITLE
Apply map style pattern

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#822]
Good morning,
I ask for help in applying the fill to my project.
My project divides the code into several parts so I can't figure out where to place your code to make it all work.
Then I didn't understand how to recall the patterns in your example.
A thousand thanks

My **qgis2web.js** is:
```
var map = new ol.Map({
    .....
    layers: layersList,
    ....
});
```

My **layers.js**, one layer examples, is:
```
var lyr_BellezzeNaturaliArt136_17 = new ol.layer.Vector({
                ..... 
                style: style_BellezzeNaturaliArt136_17,
                .....
            });
```

My **style_BellezzeNaturaliArt136_17.js** for example is:
```
var size = 0;
var placement = 'point';

var style_BellezzeNaturaliArt136_17 = function(feature, resolution){
    var context = {
        feature: feature,
        variables: {}
    };
    var value = ""
    var labelText = "";
    size = 0;
    var labelFont = "10px, sans-serif";
    var labelFill = "#000000";
    var bufferColor = "";
    var bufferWidth = 0;
    var textAlign = "left";
    var offsetX = 8;
    var offsetY = 3;
    var placement = 'point';
    if ("" !== null) {
        labelText = String("");
    }
    var style = [ new ol.style.Style({
        stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}),fill: new ol.style.Fill({color: 'rgba(141,90,153,1.0)'}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })];

    return style;
};
```

**Comment by phelanHayes** [comment]
Hi @andreaordonselli 

If I understand correctly, it looks like you just need to add a fill property to the style like so:
This applies a 'hatch' pattern.

var style = [ new ol.style.Style({
       fill: new ol.style.FillPattern({	
              pattern: 'hatch',
              image: undefined,
              ratio: 1,
              icon: undefined,
              color: '#000000',
              offset: Number(8),
              scale: Number(1),
              fill: new Fill ({ color: 'rgba(141,90,153,1.0)' }),
              size: Number(1),
              spacing: Number(8),
              angle: Number(90)
            }),
        stroke: new ol.style.Stroke({color: 'rgba(35,35,35,1.0)', lineDash: null, lineCap: 'butt', lineJoin: 'miter', width: 0}),fill: new ol.style.Fill({color: 'rgba(141,90,153,1.0)'}),
        text: createTextStyle(feature, resolution, labelText, labelFont,
                              labelFill, placement, bufferColor,
                              bufferWidth)
    })]; 

reference: http://viglino.github.io/ol-ext/examples/style/map.style.pattern.html

**Comment by andreaordonselli** [comment]
Many thanks, it works perfectly and is beautiful.

I just had to edit
`fill: new Fill ({}),`
in
`fill: new ol.style.Fill ({}),`
