### ISSUE TITLE
cannot read property of null (reading 'getboundingclientrect') at ol-ext element.offsetrect

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Viglino/ol-ext#823]
Hi @Viglino 

I have issue related to **FixedPopup.**

The **error message** I get at fixedPopup is, see error message below:

![image](https://user-images.githubusercontent.com/32929383/179479232-cab199ed-eaeb-4cf7-a88e-3f4d361e7f41.png)

    
 This is a bug when the map re-rendered on emptied, and it re due to the fact that there is a bug with fixed popup when the map is to be rendered or when the map is to switch between sound and dark theme when fixed popup is open.

Do you have any suggestion/ solution for this or way you can workaround this issue?

**Comment by Viglino** [comment]
Do you have an online example?

**Comment by Viglino** [comment]
I've added a test to prevent rendering when the map in not displayed.
