### ISSUE TITLE
ol-ext Legend subTitle Display

### ISSUE THREAD

**Issue by phelanHayes** [Viglino/ol-ext#826]
Currently I am using your suggested technique of creating a div and using its innerHtml to render a '\n' and therefore create a title with 2 lines (Title/Subtitle).  

I would like style them independently so that the subTitle can be a smaller font for example.

My thoughts are to add subTitle/subTitleStyle properties to the Legend or perhaps using the text and style in ol.style.Text for the title/titleStyle therefore supporting multiple lines with a tuple.

Thank you for ol-ext!

**Comment by Viglino** [comment]
There is a `titleStyle` option to use when you create the legend (see http://viglino.github.io/ol-ext/doc/doc-pages/ol.legend.Legend.html)
You can use it to style title / subtitle, the default value is bold.
You can also use a `textStyle` when you create the legend items (see http://viglino.github.io/ol-ext/doc/doc-pages/global.html#olLegendItemOptions). The default value use the legend style / titleStyle.

**Comment by phelanHayes** [comment]
Yes, thank you!  Perhaps I am asking for to fine grain of control or maybe I'm just missing something on how to achieve my desired result.  

I have been able to produce the following using title/titleStyle and text/textStyle. I would like something closer to the first image, but with a different style applied. 

This is achieved by using the legend properties title/titleStyle and manipulating the title property adding a '\n' and providing a titleStyle.
<img width="116" alt="legendSubtitle1" src="https://user-images.githubusercontent.com/15438890/181618844-3444a867-da1e-492f-b1a0-535ad98bb759.png">

The second image is treated as a general item and therefore can apply a text style and className, however I think the control of the positioning is thrown off when it is converted to an image with ctx.textAlign = 'left';
<img width="109" alt="legendSubtitle2" src="https://user-images.githubusercontent.com/15438890/181618860-ef6b1178-bc0f-412d-b596-4c097f21add2.png">

Any advice is greatly appreciated!  Thank you.

**Comment by Viglino** [comment]
You have to use 'center' className to center the legend item.
See: https://codepen.io/viglino/pen/qBoVxxG
![image](https://user-images.githubusercontent.com/7868217/181703113-aaaf80b2-d1ac-45dd-bae9-090303b1a4cc.png)

**Comment by phelanHayes** [comment]
And just like that, perfect, thank you!
