### ISSUE TITLE
Filter/Crop works with WebGLTile?

### ISSUE THREAD

**Issue by Abl1104work** [Viglino/ol-ext#827]
Hello, first of all excellent project, I have a doubt, I am trying to implement the filter/Crop functionality to a WebGLTile layer, but when I add the layer with this filter to the map, it always gets stuck, so I wonder if it is possible to do this currently.

PS: I saw the other issues that exist to inform me more about the problem, and it seems that maybe it is something related to the type of canvas and that you have already seen a similar case before with other functionality, so I do not know if the solution can be similar.

**Comment by Viglino** [comment]
Not sure it's possible as the WebGlTile layer is not render as a standard layer...

**Comment by Abl1104work** [comment]
Ok, I'm going to look for other alternatives and options, if I find something I add it to the issue for if anyone has the same doubt, thanks

**Comment by Abl1104work** [comment]
Good morning, regarding the doubt I raise on this topic, after much research, it turns out that there is really no way to solve the crop problem, at least not currently, the most viable solution to this is not in the client, but in the API, changing the type of response image from.tiff to.png, with tiff image management libraries, such as rasterio or gdal it is possible to perform the transformation and cropping of it, in this way, it is not necessary to crop anything, it is enough to put the georeferenced image on the map.

I hope this information can give ideas or be useful if someone had the same doubt.
