### ISSUE TITLE
write a second line in the search field

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#828]
I am using https://viglino.github.io/ol-ext/examples/search/map.control.searchfeature.html
I would like the search field to be higher and write some text in a second line.
You can help me?
Thank you.

Like this:
![2022-07-28 09_34_55-Window](https://user-images.githubusercontent.com/89784373/181449398-43702a32-2fac-48d0-ae8c-b0293ccdce2d.png)

**Comment by Viglino** [comment]
Have look at the [ol.control.SelectMutil example?](https://viglino.github.io/ol-ext/examples/control/map.control.selectmulti.html)
You can also use the css to style the control...

**Comment by andreaordonselli** [comment]
Good morning,
I do not need other controls but only to send the text to the second line in the `placeholder`.
I want to advise users to turn on the right level to see the search result.

I raised `.ol-search input` with `width: 40px;`

I tried writing
`placeholder: 'first line text ... <br> second line text',`

Then I tried
`placeholder: 'first line text ... <p> </p> second line text'`

But the text doesn't go to the second line

**Comment by Viglino** [comment]
You can add a new line in the control element by yourself, then set text inside:
```javascript
// New element to add
const elt = document.createElement('DIV')
// Get control search list element
const ul = searchControl.element.querySelector('ul')
// Add element before the search list
searchControl.element.insertBefore(elt, ul)
// Set info
elt.innerHTML = 'some text...'
```

**Comment by andreaordonselli** [comment]
It works perfectly.
Many thanks for your help.
