### ISSUE TITLE
Permalink Control - automatic permalink value

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#829]
Good morning,
I am using Permalink Control
http://viglino.github.io/ol-ext/examples/control/map.control.permalink.html

Is there a way to not have to define the `permalink: "name"` value in each layer?

Is it possible that the `permalink `automatically takes the `title` value or the `source` value of the layer?
This is my example layer:
```
var lyr_Idrografia_1 = new ol.layer.Vector ({
                declutter: true,
                source: jsonSource_Idrography_1,
                style: style_Idrografia_1,
                interactive: true,
                title: '<img src = "styles/legend/Hydrography_1.png" /> **Hydrography**'
            });
```
Thanks

**Comment by Viglino** [comment]
There is no but you can set it automatically when you add the layer in your map:
```javascript
map.getLayerGroup().on('addlayer', funcion(l) {
  l.set('permalink', l.get('title'))
}
```
Be aware the whole title will be displayed in the layer list in the url... and some char may break the url...

**Comment by andreaordonselli** [comment]
It does not work.
I believe why in my project the `map.addLayer` is not called, come to one of his examples:
```
map.addLayer (new ol.layer.Vector (
{name: 'Fonds de guerre 14-18',
source: vectorSource,
style: new ol.style.Style ({image: new ol.style.Icon ({src: "../ data / camera.png", scale: 0.8})})
}));
```
Here is the [link](https://www.opengis.it/ente/demo/) to my project

**Comment by Viglino** [comment]
You can also call it when layers are added in the map:
```javascript
map.getLayerGroup().forEach(function(l) {
  l.set('permalink', l.get('title'))
});
```

**Comment by andreaordonselli** [comment]
Your code works, but you were right, my `titles` contain the instruction to make the `img src` appear in the legend and this breaks the link making it not working.
In other way, indicating for example the `source` field or the `style` field (which would be **perfect** because they are unique and without spaces or strange characters) the code does not work as these 2 fields do not have their own value in quotes `''`.
Do you have any other idea not to write in every layer `permalink : 'example',` ?

**Comment by andreaordonselli** [comment]
To insert single quotes I tried this code but it doesn't work, do you know how to fix it?

```
function setPermalink(l) {
   var contentstyle =  l.get('style');
   var quotes_content_style =  "'"+contentstyle+"'";

    l.set('permalink', quotes_content_style)
    if (l.getLayers) l.getLayers().forEach(setPermalink);
}
setPermalink(map.getLayerGroup())
```

The goal is to take the content of the style field, and create a new permalink field with this content, but in single quotes.
Thanks.

**Comment by Viglino** [comment]
You can use [encodeURIComponent()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to escape special chars.

**Comment by andreaordonselli** [comment]
I believe this method is not supported for single quotes

![image](https://user-images.githubusercontent.com/89784373/191059537-2e0c72c4-509e-44c7-8467-c1d0de8920e1.png)

**Comment by Viglino** [comment]
[encodeURIComponent()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) is the js function to encode URI componenet in an URL...

**Comment by andreaordonselli** [comment]
Thanks
