### ISSUE TITLE
Spatial query - new extension requested

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#831]
Good morning,
surfing the web I came across this [video](https://www.youtube.com/watch?v=Eozu7moovRk) by GIS Simplified entitled "Openlayers: Zero to Hero in three hours", whose code was published in the comments youtube and that I am attaching [GISSimplified_21012022.zip](https://github.com/Viglino/ol-ext/files/9240777/GISSimplified_21012022.zip)

Among the different features shown there is the Spatial Query which I think is very useful and which I have not found among your extensions. It is shown at this [minute](https://www.youtube.com/watch?v=Eozu7moovRk&t=5495s) and at this [minute](https://www.youtube.com/watch?v=Eozu7moovRk&t=6730s)

Here are some example screenshots:
![image](https://user-images.githubusercontent.com/89784373/182339467-15e160fe-89db-43b8-a94e-749ea4edb382.png)

![image](https://user-images.githubusercontent.com/89784373/182339511-3de41d69-67b0-48be-8629-c2f5ace18e15.png)

If you think you want to create this extension, I allow myself to contribute with a brief analysis, also because it is the only thing I can do since I don't mean code.

**Premise**:
In addition to the GIS Simplified video, I found another example online on the DatiOpen.it [site](http://www.datiopen.it/it/opendata/Repertorio_Nazionale_degli_interventi_per_la_Difesa_del_Suolo_ReNDiS_) whose code is not available to me.
I think the DatiOpen.it tool is worse in these things:
- during the graphic selection it does not allow to see the distances (ex: while drawing the circle I do not see its dimensions)
- it does not allow you to choose the variables "within distance of", "intersecting", "completely within"
![image](https://user-images.githubusercontent.com/89784373/182339720-7a9fe76f-d752-48ea-88c9-fdfc6fb0b598.png)

But I think it is better in showing the data in tabular form following the query, with the possibility of zooming in on the individual features queried (the ideal would have been that when the mouse hovered over the features in the table, the feature in the table would be highlighted. map)
![image](https://user-images.githubusercontent.com/89784373/182339812-198afc91-8e79-443a-9ff3-282c276eb46e.png)

**Caution**:
The ability to show data in the table after a query is also provided by GIS Simplified, but with another feature, the Attribute Query; I don't understand why it doesn't come with the Spatial Query as well. In the code that I am attaching there is also this functionality, maybe you can apply the table also to the Spatial Query?
After the query, all the features in the table are highlighted - 1 click in the single feature in the table highlights it on the map - 2 clicks in the feature in the table also zooms on it
![image](https://user-images.githubusercontent.com/89784373/182339944-0aa08e2f-fe07-45fb-8592-b0000f4b5e4c.png)

**Brief Analysis**:
- The Spatial Query should be destined only to the layers turned on at that moment in the layerswitcher (the combo box “Select feature of” should therefore show a dynamic list of the layers turned on);
- I believe it is essential that:
      - the query result is shown in the table (perhaps a table anchored at the bottom, minimizable, extensible)
- I consider it not fundamental, but beautiful:
      - highlight all features after the query;
      - passing the mouse over the individual features in the table, see the feature that lights up;
      - the possibility of zooming in on the various features in the table;

Thanks for your attention

**Comment by Viglino** [comment]
Hello,

Spatial queries are a little bit tricky as it depends on the data and may need extra lib to calculate on polygons or lines ([turf.js](https://turfjs.org/) or [jsts](http://bjornharrtell.github.io/jsts/)).

Displaying features in a table would be of interest and I probably would add such a feature in ol-ext as I could need it. But I've no time left to address it yet.

@+
