### ISSUE TITLE
Search Nominatim Control - possible violation of terms for autocomplete

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#832]
I have seen this extension:
https://viglino.github.io/ol-ext/examples/search/map.control.searchnominatim.html

At the moment I am using the similar one of jonataswalker and in [this](https://github.com/jonataswalker/ol-geocoder/issues/255) issue they replied that activating the `autocomplete` violates the provider's [terms](https://operations.osmfoundation.org/policies/nominatim/) 

How did you overcome this problem?
Thanks

**Comment by Viglino** [comment]
The use of autocomplete is border line as it use a temporization before requesting the service (so it doesn't request on each typing).
You can change it using the `typing` option (set it to -1 to prevent autocomplete). The default is 500ms.
Maybe it should be clearly stated in the doc... and `typing` should be set at -1 by default...

**Comment by Viglino** [comment]
I've updated the example/doc to reflect Nominatim terms.

**Comment by andreaordonselli** [comment]
Yes, he is right, it is border line. However, I believe that you have done well to update the example.

As per the request I made to jonataswalker, in the mobile version pressing enter to search does not work if there are other text fields in the map (such as scale control). A submit button would be ideal.
Greetings.
