### ISSUE TITLE
Is MoonLight Source is available?

### ISSUE THREAD

**Issue by vishnunossam** [Viglino/ol-ext#836]
Hi,
I am using the DayNight source to display as a DayNight Overlay which is working perfectly.
Now, i wish to add MoonLight Ovwerlay to my application.
Is there any MoonLight Source is available? 
if yes, please post the link
if no, is there any plan to develop it?

**Comment by Viglino** [comment]
There is no and I think it depends on moon phase and illumination.
But you can look at libs lilke [mourner/suncalc](https://github.com/mourner/suncalc)
