### ISSUE TITLE
How to show circle radius in a tooltip with circle as ol.control.Toggle

### ISSUE THREAD

**Issue by theGilles** [Viglino/ol-ext#838]
Hi
 i've tried many possibility to show in real time a circle radius in a tooltip but I can do it.

Please a simple example with this :

var tooltip = new ol.Overlay.Tooltip();
olmap.addOverlay(tooltip);

var editbar = new ol.control.Bar({.....
});

var circle_edit = new ol.control.Toggle({
html : '',
title : 'Cercle',
interaction :
new ol.interaction.Draw ({
type : 'Circle',
source : vector.getSource()
})
});

thanks !!

**Comment by mike-000** [comment]
`ol.geom.Circle` is not a standard geometry type, and it is a circle only in the plane of the projection.  Instead if you use a `geometryFunction` as in https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html to produce a circular polygon you can calculate the true radius on the ground from the area in the `formatArea` function then format it as a length

https://jsbin.com/nimubanice/edit?html,output

**Comment by theGilles** [comment]
@mike-000 thanks to your response.
I ended up solving my problem, it's quite simple actually.
Result :

// == Tooltip
var tooltip = new ol.Overlay.Tooltip();
olmap.addOverlay(tooltip);

// === Circle
var circle_edit = new ol.control.Toggle({
          html        : '<i class="fa fa-circle-o-notch" ></i>',
          title       : 'Cercle',
          interaction : 
            new ol.interaction.Draw ({
                type              : 'Circle',
                source            : vector.getSource()
          })
        }); 

        let circle = circle_edit.getInteraction('Draw');
        let geometry;
        circle.on('drawstart',
          function (evt) {
            tooltip.setMap(olmap);
            geometry = evt.feature.getGeometry();
            geometry.on('change', function(e)
              { 
                const radius = geometry.getRadius();
                tooltip.setInfo('Rayon : '+tooltip.formatLength(radius));
              });
          });
        circle.on(['drawend'], 
          function () {
          tooltip.setMap(null);
          geometry = null;
          circle_edit.setActive(false);
        });
        editbar.addControl ( circle_edit );

that's all.

**Comment by mike-000** [comment]
@theGilles That method will work well only if you are using a local view projection such  as UTM, 2152 or 27700.  In a web mercator view at 45 degrees north (e.g. Bordeaux) it would produce a result 1.4 times the correct value.  At 60 degrees north (e.g. Oslo) the result will be 2 times the correct value.
