### ISSUE TITLE
Layerswitcher startup "open" in desktop view, "collapsed" in smartphone view

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#843]
Is it possible to set the visibility at the start of the open/collapsed layerswitcher on the basis of the display device (desktop or smartphone)?

**Comment by Viglino** [comment]
Something like this: 
```javascript
// ol set touch on map viewport
var hasTouch = map.getViewport().classList.contains('ol-touch');
// Small screen
var isSmall = screen.width < 700;
// Show layer switcher if not too small and non touch device...
if (!isSmall && !hasTouch) {
  layerswitcher.show()
}
```

**Comment by andreaordonselli** [comment]
Can you tell me where am I wrong?
I changed the last line by writing `layerSwitcher.show()` with a capital S

![image](https://user-images.githubusercontent.com/89784373/186612423-1cb86f11-3421-49c2-b10c-c438b2b8b4ba.png)

![image](https://user-images.githubusercontent.com/89784373/186612585-dc6829d7-92a6-4e05-aff1-ce5329ddc003.png)

![image](https://user-images.githubusercontent.com/89784373/186612663-0f356bc0-9e65-483c-bd56-4df1dd6929d5.png)

I also commented `// collapsed: true,`

![image](https://user-images.githubusercontent.com/89784373/186613197-faad64db-2bab-4a12-9e2b-ef6910d09308.png)

Thank you

**Comment by Viglino** [comment]
There is a bug in the lib `self` should be replaced by `this`.
```javascript
  this.dispatchEvent({ type: 'toggle', collapsed: false });
```
I've fixed it in the last commit....
You can use `layerswitcher.toggle()` that is not buggy

**Comment by andreaordonselli** [comment]
A thousand thanks.
It works perfectly.
I had to change this part:
`var isSmall = window.innerWidth <700;`
