### ISSUE TITLE
Geobookmark Issue

### ISSUE THREAD

**Issue by vaibhavteknobuilt** [Viglino/ol-ext#846]
Whenever I add a new bookmark previous ones are saved in some sort of storage.
Though I have removed old ones from the code they still are visible in the bookmark button.
I only want to show those bookmarks that are added in the code like maybe only London andPariss.
So how to remove old bookmarks which are saved in local storage somewhere?

**Comment by Viglino** [comment]
You can get all bookmarks using `getBookmarks()` then remove them like this:
```javascript
// remove none permaent bookmarks
for (var b in bookmarkControl.getBookmarks()) {
  if (!bookmarkControl[b].permanent) bookmarkControl.removeBookmark(b)
}
```

**Comment by vaibhavteknobuilt** [comment]
Few errors are coming which are undefined.
Can you please show the complete code (right from start) here so that removing the bookmark thing will also work

Thanks

**Comment by andreaordonselli** [comment]
I use this code because I am not interested in giving the user the possibility to define their own bookmarks.
The page will always load what is defined in the code, overwriting what is on the local disk.

```
<script> 
		var bm = new ol.control.GeoBookmark({
			namespace: 'Demo',
			title: 'Zoom Località',
			editable: false,
		  });
		  bm.setBookmarks({
			  Quartiere_1: {pos:ol.proj.transform([2351142.20, 4842857.50], 'EPSG:3004', 'EPSG:25832'), zoom:16},
			  Quartiere_2: {pos:ol.proj.transform([2352404,4841605], 'EPSG:3004', 'EPSG:25832'), zoom:16},
			  Quartiere_3: {pos:ol.proj.transform([2355410,4838774], 'EPSG:3004', 'EPSG:25832'), zoom:16},
			  Quartiere_4: {pos:ol.proj.transform([2357220,4839534], 'EPSG:3004', 'EPSG:25832'), zoom:16},
			  });
		  map.addControl(bm);		  
</script>
```
