### ISSUE TITLE
SearchFeature not working 

### ISSUE THREAD

**Issue by deadpickle** [Viglino/ol-ext#847]
Im using OpenLayers 6.15.1 and I keep getting the error:
Class constructors cannot be invoked without 'new' at new ol.control.SearchFeature

codes pretty easy:

````
var search = new ol.control.SearchFeature({
      source: pointLayer
    });
    
    map.addControl(search);
````

**Comment by Viglino** [comment]
The last ol version (v7) introduce some breaking changes and ol-ext is moving to ES6 class definition to be compatible (see https://github.com/Viglino/ol-ext/issues/839)
Meanwhile some bugs may appear till all classes are moved that will be fixed asap.
Use the last stable version indeed (https://github.com/Viglino/ol-ext/releases/tag/v3.2.30).
NB: I've updated the SearchFeature control and fix the bug in the last commit.

**Comment by deadpickle** [comment]
Great it loaded!!!
I still must be missing something, I get a "cannot read properties of undefined" when I try the use the search
````
const pointLayer = new ol.layer.Vector({
      source: new ol.source.Vector({
        url: '/awdndb/monitor/geoawdndata?product=' + $('#productlist').val() + '&begin=' + getDateTimeString() + '&end=' + getDateTimeString() + '&sensor=' + $('#sensorlist').val() + '&units=' + $('#units').val(),
        format: new ol.format.GeoJSON()
      }),
      title: 'pointLayer',
      style: pointFunction
    });

const map = new ol.Map({
      target: 'map',
      overlays: [overlay],
      view: new ol.View({
        center: [-10997148, 4569099],
        zoom: 5
      })
    });

var select = new ol.interaction.Select({});
    map.addInteraction(select);
    
    var search = new ol.control.SearchFeature({
      source: pointLayer,
      getTitle: function(feature) {
        return feature.get('name');
      }
    });

map.addControl(search);
````

**Comment by Viglino** [comment]
Search control is waiting a source not a layer (pointLayer)...
Use `pointLayer.getSource()` instead:
```javascript
    var search = new ol.control.SearchFeature({
      source: pointLayer.getSource(),
      getTitle: function(feature) {
        return feature.get('name');
      }
    });
```
