### ISSUE TITLE
disable undo/redo interaction with existing objects and create button to enable/disable toolbar

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#848]
Good morning,
I introduced http://viglino.github.io/ol-ext/examples/interaction/map.interaction.undoredo.html in my project but i have some problems.

If I use selection ![image](https://user-images.githubusercontent.com/89784373/188610835-09aba443-c157-48f6-be30-f591a5eaaf41.png) the control interacts with the objects already existing on the map while I wish it didn't, the popup also comes out.

Existing geometry:
![image](https://user-images.githubusercontent.com/89784373/188612902-d80fe033-7627-440d-9909-5e08eba0c792.png)

Interaction:
![image](https://user-images.githubusercontent.com/89784373/188613024-8be0d8ff-9b86-44a2-81fc-69ea19916461.png)

the tool also allows you to modify the existing geometries in the map while I would like it not to do so and to just add / modify the new geometries drawn with this toolbar
![image](https://user-images.githubusercontent.com/89784373/188611393-5a1e6014-4b6e-433d-8cb5-4482450862dd.png)

also adding a point ![image](https://user-images.githubusercontent.com/89784373/188610652-a19b5987-6962-4713-9d05-a32a53430e66.png) above an object the map also makes the popup
![image](https://user-images.githubusercontent.com/89784373/188610351-cf5c97e5-7bf4-4164-b1e3-9c0a0e8116b4.png)

It is possible to create a button that shows / hides the toolbar and activates / deactivates its functions. I was thinking: when you activate the toolbar you deactivate the popup. Also I would like it not to interact with the objects already present.

Can you help me? Thank you very much.

**Comment by Viglino** [comment]
The example use an edit bar to edit object on the map. Maybe you don't need it...
The edit bar is a generic tool that enable you to select/edit a map.
You can set your own selection interaction to prevent selecting features you don't want to (use the `interactions` option on creation to specify your own interaction)
Look at http://viglino.github.io/ol-ext/examples/bar/map.control.editbar.html that use an external selection interaction.

You can show hide the toolbar by yourself using `editbar.setVisible(false)`. 
Just add a button to toggle it... but the edit bar has a `toggleOne` option, that means that almost one interaction is active (even when hidden). So you have to activate one at least (maybe the selection)
The `EditBar` doesn't care about popup. Look at you popup definition (it may be linked to the select interaction) to prevent showing.

**Comment by andreaordonselli** [comment]
I write this code but there are always 3 problems described below
```
var doDesign = false;

var onDesign = function(evt) {    
    if (doDesign) {
		
		//  Vector layer
    var vector = new ol.layer.Vector({ 
	source: new ol.source.Vector(),
	})
	map.addLayer(vector);
	
	var note = new ol.control.Notification();
    map.addControl(note)

    // Add the editbar
    var select = new ol.interaction.Select({ title: 'Sélection'});
    select.set('title', 'Sélection');
    var edit = new ol.control.EditBar({
      // Translate interaction title / label 
      interactions: { 
        // Use our own interaction > set the title inside
        Select: false,
        // Define button title
        DrawLine: 'Ligne',
        // Drawregular with label
        DrawRegular: { title: 'Forme régullière', ptsLabel: 'pts', circleLabel: 'cercle' }
      },
      source: vector.getSource() 
    });
    map.addControl(edit);

    // Add a tooltip
    var tooltip = new ol.Overlay.Tooltip();
    map.addOverlay(tooltip);			
}
};

	var handleDesign = function(e) {
		 if (!doDesign) {
				doDesign = true;
				map.on('click', function(evt) {
					onDesign(evt);
				});
		} else {						
				doDesign = false;				
		} 
	};
	
	var designbutton = document.createElement('button');
	designbutton.className += ' fas fa-paint-brush ';

	designbutton.addEventListener('click', handleDesign, false);
	
	var element = document.createElement('div');
	element.className = 'design ol-unselectable ol-control';
	element.appendChild(designbutton);
	
	designbutton.addEventListener("click", () => {
    designbutton.classList.toggle('clicked');
	})

	var DesignControl = new ol.control.Control({
		element: element
	});
	map.addControl(DesignControl);
```

The popup problem is overcome, I did as you said:
```
var onSingleClick = function (evt) {
if (doDesign) {
        return;
    }
```
The interaction problem is overcome, I did as you said:
```
  interactions: { 
        Select: false,
```

I still have these problems for which I ask you for help:

1) after clicking the main button I have to make a first click on the map to see the toolbar ![image](https://user-images.githubusercontent.com/89784373/189339877-fe443fb0-7740-4588-8dff-d28800515ba5.png) Not knowing how to do it I linked the event to the singleclick and this is the result, sorry but I don't know how to do better.

2) after the first click the toolbar appears, but the commands are not activated selectively, they are activated all together when i click in it (the enable/disable button on second click does not working), so if I click "line" and draw and then click "polygon" and draw, I will draw both
![image](https://user-images.githubusercontent.com/89784373/189340617-6ac8e79a-77dc-45d3-bdbb-df32062eee8f.png)
![image](https://user-images.githubusercontent.com/89784373/189340419-9ce26334-3fc5-48fa-94b5-01352225f9f9.png)

3) when I click on the main button to deactivate and delete everything that has been drawn nothing happens and the toolbar remains visible

I am sure I have complicated some simple things but I think I have made progress anyway.
Thank you.

**Comment by Viglino** [comment]
Here is an example with a button to expend/collapse the bar.
https://codepen.io/viglino/pen/JjvXbVO
The selection is always active as one need to be active at least in the editBar (but you can handle selection if you create your own select interaction).

**Comment by andreaordonselli** [comment]
Many thanks, I was able to do everything with the example code you sent me.

I have added this code read in another issue to disable startup checking:
```
var selectbar = editBar.getActiveControls()[0];
selectbar.set('autoActivate', false);
selectbar.setActive(false);
```
and this code to hidden selection because I didn't need it
```
.ol-selection{
display: none!important;
} 
```
so I eliminated the problem of the interaction of the selection
I added this code to delete the data drawn when closing the toolbar
```
var features = vector.getSource().getFeatures();
        features.forEach((feature) =>{
          vector.getSource().removeFeature(feature);
		  });
```


This is the result:
![image](https://user-images.githubusercontent.com/89784373/189395254-181554a3-0c80-43bb-92ff-56977d954810.png)
![image](https://user-images.githubusercontent.com/89784373/189395306-2aee2be9-3410-4e7a-94a5-c97ac2e9c09f.png)
![image](https://user-images.githubusercontent.com/89784373/189395399-f51fdf57-a9d0-4bb7-842a-25577b423175.png)


I still have to turn off the popup while using the extended bar, and restore its use when I close the bar, can you give me one last help? This is the current code with which the popup is already deactivated when using other 3 functions, help me write the if?

```
var onSingleClick = function (evt) {
if (doHover) { return; }
if (doHighlight) { return; }
if (sketch) { return; }
ecc....
```
Again a thousand thanks, my teacher.

**Comment by andreaordonselli** [comment]
Can you explain me how to add the **fa-marker** class to the open/close button.
I would like to apply an awesome font icon.

**Comment by andreaordonselli** [comment]
I had to replace the `!` with `:` like this

`html: '<i class = "fas fa-marker"> </i>',`

There was no need to define anything else in the css, I simply deleted

```
content: "\f03e";
font-family: FontAwesome;
```

Thanks, thanks again
