### ISSUE TITLE
Only base layers for LayerSwitcherImage())

### ISSUE THREAD

**Issue by AndyLicht** [Viglino/ol-ext#85]
Hi,
thanks for these great OL Extensions. I want to combine the LayerSwitcherImage() with the LayerSwitcher().

now, i only want to show the base layers in the image switcher and all others in the layertree, is it possible? Because "displayInLayerSwitcher: XXX" is used in both methods. If these function is not implemented, i could help to build it.
best regards 
tim

**Comment by Viglino** [comment]
Hi,
You can't have this behaviour because the test is done on the same layer attribute.
The solution would be to handle a function to test if the layer has to be drawn in the layer switcher instead of just testing a layer attribute. Thus different layer switchers could handle there own layers.
I'll try to do something asap.
@+

**Comment by AndyLicht** [comment]
Hi, thanks for the very fast answer. Maybe it would be great to give a layer a "type" attribute, which can be user for the layerswitchers.

layerA {type: base}
layerB {type: overlay}
layerC{type: custom}


shownTypes =['custom','overlay'];
switcher =  LayerSwitcher({types:shownTypes})

It is only a idea, i will build my layer attributes with your layer descriptions
Thanks a lot

**Comment by Viglino** [comment]
Hi,
I've added a new displayInLayerSwitcher option in the control. It's a function that take a layer and returns a boolean to indicate if the layer is concerned, thus you can check witch layer is displayed in the switcher.
For example to display only layers with a displayInLayerSwitcher attribute to 1:
```javascript
var switcher = new ol.control.LayerSwitcher({
  displayInLayerSwitcher: function(layer) {
    return (layer.get("displayInLayerSwitcher") === 1); 
  });
});
map.addControl(switcher);
```
The default behaviour test if displayInLayerSwitcher attribute is false as before.
@+

**Comment by AndyLicht** [comment]
Hi, i´m sorry. i don#t get it work. Can i send you a mail or a private message, with my errors. Maybe together we can build an example.
best regards
Tim (aka AndyLicht)

**Comment by AndyLicht** [comment]
Now, i´m realy sorry. It works. I´ve forgotten the css. I will implent these functions into the drupal module for openlayers https://www.drupal.org/project/openlayersd8, is it okay for you?

**Comment by Viglino** [comment]
No problem the license is open!
