### ISSUE TITLE
Possible bug in "LayerSwitcherImage" for BingMaps sources

### ISSUE THREAD

**Issue by dcifu** [Viglino/ol-ext#850]
Hi @Viglino
Firstly, congratulations on his work.

I think it's a bug in the "LayerSwitcherImage" control for layers of type source: BingMaps

The layer with the "LayerSwitcher" control works correctly, with LayerSwitcherImage the plugin breaks. I think the problem is due to generating the getPreview() of the layer. Attached error capture showing two viewers with the same list of layers. Thanks for everything.

<img width="1443" alt="BugLayerSwitcherImageWithBingMaps" src="https://user-images.githubusercontent.com/90386291/188947997-84aa7ded-e996-40ec-8417-d33818b42336.png">

_Note: The project is working in angular, It's based on ol-ext-angular repository with typescript_

**Comment by Viglino** [comment]
It seems the getPreview is not able to get the source tile grid... The tile grid is used to get a tile preview.
Thus I don't know how to solve this (except prevent crashing and return an empty preview)
The best way is to set a preview using `layer.set('preview', previewURL)` that will be used instead...

**Comment by mike-000** [comment]
That also happens with a TileJSON source - these sources need to become 'ready' before the tiles can be accessed.

**Comment by geraldo** [comment]
That works out perfectly, thanks @mike-000
