### ISSUE TITLE
this._style.getStroke(...).width is not a function at ol_Overlay_FixedPopup

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Viglino/ol-ext#851]
Hi, 

In the [documentation](https://viglino.github.io/ol-ext/doc/doc-pages/ol.Overlay.FixedPopup.html#:~:text=style%20the%20popup.-,style,a%20style%20to%20style%20the%20link%20on%20the%20map.,-minScale), it has been described that Fixed Popup Overlay options style prop type as ol/style, but here it was only ol/style/Fill as an option. This means that fixed popup can only have a style of type fill, and if you want to add more style options such as Stroke, it will throw an error that Stroke of type ol/style is not a function. thus it will not be set, and may throw an error.

`this._style.getStroke(...).width is not a function at ol_Overlay_FixedPopup`
https://github.com/Viglino/ol-ext/blob/0e1c2322000807d56b38993a7df8d57c097bb68c/src/overlay/FixedPopup.js#L60

is it possible to change the fixed popup so that it can accept ol/style object ` new style({})` or add `Stroke `type here?

**Comment by Viglino** [comment]
The style only applies to draw the link and it only uses the fill color (to fill the link triangle).
Stroke width and color are ignored...

**Comment by Bahaa-Fadhil** [comment]
> The style only applies to draw the link and it only uses the fill color (to fill the link triangle). Stroke width and color are ignored...

Yes, I understand, but why fill the link style drawn as a triangle, I thought to have strock width to have it as a straight line. And the only possibility to have it as a straight line is to have stroke style.

Example of what I mean:
![image](https://user-images.githubusercontent.com/32929383/189671910-a4a1611c-8a35-41ae-9696-f81537fdc878.png)


[`FixedPoup example: `](http://viglino.github.io/ol-ext/examples/popup/map.fixedpopup.html)

**Comment by Viglino** [comment]
The idea is to have bubble speech with link that points the bubble source...
![image](https://user-images.githubusercontent.com/7868217/189684256-d67ab51d-8226-45e4-9202-70402e8530be.png)

**Comment by Bahaa-Fadhil** [comment]
[](url)> The idea is to have speech bubble with link that points the bubble source... ![image](https://user-images.githubusercontent.com/7868217/189684256-d67ab51d-8226-45e4-9202-70402e8530be.png)


Yes, the idea is perfectly fine, but where does it not allow the user to style (bubble with link/bubble source) as the user wants?

Say you come to a case where you want a slightly different style than the default! then it is not possible with today's properties?

For example, in my situation, I don't use bubble style around the popup itself, but only for the link between the source and the popup box

![tempsnip](https://user-images.githubusercontent.com/32929383/190157871-c353d0ee-19a0-4a8e-8d26-f40f5d453787.png)
