### ISSUE TITLE
How to disable the ol.control.Button

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#852]
I would like my ol.control.Button to have disabled attribute.  How can I achieve this?

So, enabled button is like: 
<button> This is a working button </button>

And, disabled button is like:
<button disabled> This is a disabled button </button>

**Comment by Viglino** [comment]
Button control can't be disabled you have to handle it in your listener.
You can use Toggle button that can be disabled (using `setDisable()`).
