### ISSUE TITLE
Toggle with sub bar is clickable only at upper half

### ISSUE THREAD

**Issue by AlenKelemen** [Viglino/ol-ext#853]
The arrow in sub bar overlays toggle's lower half so it can't be clicked as user expects.
Arrow is created by ::before at div .ol-bar.ol-option-bar.
Replacing ::before code with:
` content: "";
    position: absolute;
    bottom: 100%;
    left: 0.3em;
    border-style: solid;
    border-width: 0 5px 6px 6px;
    border-color: transparent transparent #003c8880 transparent;`
Should correct that...

**Comment by Viglino** [comment]
I've added `pointer-events: none;` to prevent interactions
