### ISSUE TITLE
overview map - static image with map extent

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#854]
Is it possible to configure a static image (like .jpg) in the overview map and defining the maximum extension of the map?

**Comment by Viglino** [comment]
You can use a layer with an ol/source/ImageStatic.
https://openlayers.org/en/latest/apidoc/module-ol_source_ImageStatic-Static.html

**Comment by andreaordonselli** [comment]
Do you have an example?
I wrote this code but you can't see the image in the overview?
Where should I place the image? in the same folder where is the file with this code?

```
var ov = new ol.control.Overview({
			  layers: [ 
				new ol.layer.Image({
					source: new ol.source.ImageStatic({
						url: 'minimap-demo.png',
						projection: 'EPSG:25832',
						imageExtent: [2349830, 4837427, 2360580, 4844329],

					})
				})
			  ],
			  projection: 'EPSG:25832',
			  minZoom: '0',
			  maxZoom: '0',
			  rotation: true,
			  align: 'bottom-left',
			  //panAnimation: "elastic"
			});
			map.addControl(ov);
```

**Comment by andreaordonselli** [comment]
I was wrong to define some variables, here is the working code for my case.
Having written the code in the index.html file I placed the minimap.png file in the same folder.
Thank you.

```
var ov = new ol.control.Overview({
			  layers: [ 
				new ol.layer.Image({
					source: new ol.source.ImageStatic({
						url: 'minimap.png',
						imageExtent: [810790.624614, 4842254.632172, 826581.827560, 4850414.220321],
						
					})
				})
			  ],
			  minZoom: '10.5',
			  maxZoom: '12',
			  rotation: true,
			  align: 'bottom-left',
			});
			map.addControl(ov);
```
