### ISSUE TITLE
Not possible to set colorMap for IDW layers

### ISSUE THREAD

**Issue by raitisbe** [Viglino/ol-ext#859]
Colormap seems to be always hardcoded to `jet` and changing the `getColor` function on IDW source class object doesn't seem to have any effect since moving to ES6, since it's a local variable in olsourceIDW function. 

Would be good if `var getColor = function (v) {` could be exposed as a public variable in the olsourceIDW class.

**Comment by raitisbe** [comment]
Currently we managed to set the custom color map by overriding the whole computeImage function
```
  const clrMap = this.generateColormap('copper')
  const getColor = (v) => {
      const black = [0, 0, 0, 255];
      if (isNaN(v)) {
        return black;
      }
      if (v > 99) {
        v = 99;
      }
      if (v < 0) {
        v = 0;
      }
      v = Math.floor(v);
      return clrMap[v];
    };
  super.computeImage = (e) => {
      const pts = e.data.pts;
      const width = e.data.width;
      const height = e.data.height;
      const imageData = new Uint8ClampedArray(width * height * 4);
      // Compute image
      let x, y;
...
```

**Comment by Viglino** [comment]
You're right... I've encapsulated the `getColor` method to make it accessible with worker...
I'll have to find a trick to handle it as a parameter...

**Comment by Viglino** [comment]
I added a `getColor` parameter to let you override the default color function when creating IDW.
You can also add `lib` functions when using workers.
See doc http://viglino.github.io/ol-ext/doc/doc-pages/ol.source.IDW.html
and example source : https://github.com/Viglino/ol-ext/blob/master/examples/layer/map.layer.idw.html#L113

**Comment by Viglino** [comment]
If you're not using worker, you just have to set the getColor method.
```javascript
idwSource.getColor = function(v) { return [r,g,b,a] } 
```
If you're using worker it's a little bit more difficult...

**Comment by raitisbe** [comment]
Thanks, works great. I'm not using worker.
