### ISSUE TITLE
ol-ext - how to import function

### ISSUE THREAD

**Issue by eXMarty** [Viglino/ol-ext#860]
I have my project with Openlayers, I would like to add the possibility of searching for points using ol-ext - ol-ext: Search control
as shown [](http://viglino.github.io/ol-ext/examples/search/map.control.search.html)

I use
- VS Code
- Nodejs + npm
- Google Chrome

I added the ol-ext according to the instructions by entering the command `npm install ol-ext`
But I don't know how to set up the import correctly so that it works

I have tried various options but to no avail.

When I import like this: `import "ol-ext"`

It doesn't work - chrome gives an error in the console:
```
ol-ext.js:23 Uncaught ReferenceError: ol is not defined
    at node_modules/ol-ext/dist/ol-ext.js (ol-ext.js:23:1)
    at __require (chunk-J43GMYXM.js?v=3770298d:11:50)
    at dep:ol-ext:1:16
node_modules/ol-ext/dist/ol-ext.js @ ol-ext.js:23
__require @ chunk-J43GMYXM.js?v=3770298d:11
(anonymous) @ dep:ol-ext:1
```

So far the working part has these imports
index.html:
```
import "./style.css";

import Map from "ol/Map";
import View from "ol/View";
import { defaults as defaultControls, Attribution, ScaleLine } from "ol/control";

import { XYZ, OSM, Vector as SourceVector } from "ol/source";

import { Tile as LayerTile, Vector as LayerVector } from "ol/layer";

import Overlay from "ol/Overlay";

import Feature from "ol/Feature";
import { fromLonLat as LonLat, toLonLat } from "ol/proj";

import Point from "ol/geom/Point";

import GeoJSON from "ol/format/GeoJSON";

import { Icon, Circle as Circle, Fill, Stroke, Style } from "ol/style";

import LayerSwitcher from "ol-layerswitcher";
```

```
npm list
├── ol-ext@4.0.0
├── ol-layerswitcher@4.0.0
├── ol@7.1.0
└── vite@3.1.3
```

I know it will be a simple thing, but for me it is an intractable problem.

First of all, many thanks for the advice

**Comment by mike-000** [comment]
Import from `ol-ext` in the same way as you import from `ol`
https://codesandbox.io/s/ol-ext-search-7e3kr4

**Comment by Viglino** [comment]
Use the same syntax as ol: 
```
// ol import
import Point from "ol/geom/Point";
// ol-ext import 
import Search from 'ol-ext/control/Search'
```

**Comment by eXMarty** [comment]
thanks a lot for the response, thanks for the explanation
