### ISSUE TITLE
Wrong published 4 version

### ISSUE THREAD

**Issue by totpero** [Viglino/ol-ext#861]
Hi,
If you open the 4.0.0 version from https://www.jsdelivr.com/package/npm/ol-ext
 you will see is the [3.2.30 ](https://cdn.jsdelivr.net/npm/ol-ext@4.0.0/dist/ol-ext.js) version published.
The same if you open the dist folder from https://github.com/Viglino/ol-ext/releases/tag/v4.0.0
Visual studio npm and libman when install v 4.0.0 is the 3.2.30 version instead.

**Comment by Viglino** [comment]
Now publish a v4.0.1
