### ISSUE TITLE
featureAnimation.Path   stop()  start()   Continuous use problem  

### ISSUE THREAD

**Issue by holai** [Viglino/ol-ext#864]
![mmexport1664190842100](https://user-images.githubusercontent.com/36557839/192263176-58bffe80-6bc1-452e-a5be-7c1d597752a4.png)

Animation using start() after using stop() cannot continue from the stop() position

Openlayers version is 7

**Comment by Viglino** [comment]
Yes the time is not stopped...

**Comment by Viglino** [comment]
Now animation restarts where it stops...

**Comment by holai** [comment]
Cool, thank you very much
