### ISSUE TITLE
Importing Legend and legend Control

### ISSUE THREAD

**Issue by AGM-90** [Viglino/ol-ext#866]
I tried to modify https://github.com/Viglino/ol-ext/blob/master/examples/canvas/map.control.printdialog.html this example program as below
 
`import { Geolocation } from "ol";
import LineString from "ol/geom/LineString";
import { Map } from "ol";
import 'ol-ext/dist/ol-ext.css';
import OSM from 'ol/source/OSM';
import { Overlay } from "ol";
import TileLayer from "ol/layer/Tile";
import { View } from "ol";
import{fromLonLat} from'ol/proj';
import{toLonLat} from'ol/proj';
import 'ol/ol.css';
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4';
import LayerSwitcher from 'ol-ext/control/LayerSwitcher';
import CanvasAttribution from 'ol-ext/control/CanvasAttribution';
import CanvasTitle from 'ol-ext/control/CanvasTitle';
import Legend from 'ol-ext/legend/Legend';
import {Legend as LegendControl} from 'ol-ext/control/Legend';
import CanvasScaleLine from 'ol-ext/control/CanvasScaleLine';
import PrintDialog from 'ol-ext/control/PrintDialog';
import {ZoomToExtent,OverviewMap,FullScreen, defaults as defaultControls,ZoomSlider,ScaleLine} from 'ol/control';
import {
  Circle,
  Fill,
  Stroke,
  Style,
  Text,
  Icon,
  RegularShape,
} from 'ol/style';

// creating the view
const view = new View({
  center: fromLonLat([5.8713, 45.6452]),
  zoom: 19,
});

/*const tileLayer = new TileLayer({
  source: new OSM(),
});*/
var tileLayer=new TileLayer({
      title: 'Google map (m,traffic)',
      type:'base',
      source: new OSM(),
    });
// creating the map
const map = new Map({
  controls: defaultControls({attribution:false,}),
  layers: [tileLayer],
  target: 'map',
  view: view,
});
map.addControl(new LayerSwitcher());
map.addControl(new CanvasAttribution({ canvas: true }));
map.addControl(new CanvasTitle({ 
  title: 'my title', 
  visible: true,
  style: new Style({ text: new Text({ font: '20px "Lucida Grande",Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif'}) })
}));
// Legend
var legend = new Legend({ 
  title: 'Legend', 
  margin: 5,
  items: [{
    title: 'Church', 
    typeGeom: 'Point', 
    style: new Style({ 
      image: new Icon({ 
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Eglise_icone_2.svg/30px-Eglise_icone_2.svg.png',
      crossOrigin: 'anonymous' // Enable print
    })})
  }, { 
    title: 'Photo', 
    typeGeom: 'Point', 
    style: new Style({ 
      image: new Icon({ 
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Icone_appareil_photo.svg/30px-Icone_appareil_photo.svg.png',
      crossOrigin: 'anonymous' // Enable print
    })})
  }]
});
var legendCtrl = new LegendControl ({ legend: legend });
map.addControl(legendCtrl);

map.addControl(new CanvasScaleLine());
var printControl = new PrintDialog({});
printControl.setSize('A4');
printControl.setOrientation('landscape');
map.addControl(printControl);`

I am getting an error as **Uncaught TypeError: c.Legend is not a constructor**
I think the problem is at
import Legend from 'ol-ext/legend/Legend';
import {Legend as LegendControl} from 'ol-ext/control/Legend';

Can you please look into it

**Comment by Viglino** [comment]
You have to import LegendControl directly:
```javascript
import LegendControl from 'ol-ext/control/Legend';
```

**Comment by AGM-90** [comment]
> You have to import LegendControl directly:
> 
> ```js
> import LegendControl from 'ol-ext/control/Legend';
> ```

Thank you
