### ISSUE TITLE
Add scrollDiv to Overlay ?

### ISSUE THREAD

**Issue by AlenKelemen** [Viglino/ol-ext#872]
I see scrollDiv in Popup (http://viglino.github.io/ol-ext/examples/popup/map.popup.bar.html) .
Maybe it would be usefull to add minibar option to Overlay too ?

**Comment by Viglino** [comment]
[Overlay](https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html) is a core ol class and [scrollDiv](http://viglino.github.io/ol-ext/doc/doc-pages/ol.ext.element.html#.scrollDiv__anchor) is an ol-ext utility.
Overlay is a container and it's to you to know what to add in it. You can add a scrollDiv to you overlay content using ol-ext [``element.scrollDiv``](http://viglino.github.io/ol-ext/doc/doc-pages/ol.ext.element.html#.scrollDiv__anchor).
```javascript
import ol_ext_element from 'ol-ext/util/element'

ol_ext_element.scrollDiv( myContent, {
  vertical: true,
  mousewheel: true,
  minibar: true
});
```
NB: scrollDiv may have drawbacks and depends on what you want to do...
PS: scrollDiv is also used in storymap div (http://viglino.github.io/ol-ext/index.html?q=story)

**Comment by AlenKelemen** [comment]
Thank you, got it ...
Dio not pay attention to storymap, very nice work ...
