### ISSUE TITLE
Transform Interaction getCenter() / setCenter() has wrong typings.

### ISSUE THREAD

**Issue by JonnyDeates** [Viglino/ol-ext#874]
If you look below you will see that the typings for these are coordinates. Open Layer coordinates are equal to Array\<number\>. Which if you are setting the center, you would want to pass [x, y] as the center. However in the code, the setCenter, and getCenter are as Array\<Coordinate\> throwing a typing mismatch. The docs are right, the implementation is off.

Docs from https://viglino.github.io/ol-ext/doc/doc-pages/ol.interaction.Transform.html

<img width="791" alt="Screen Shot 2022-10-17 at 12 29 06 PM" src="https://user-images.githubusercontent.com/48420377/196243811-3bc8d723-13b5-4996-abea-ccf6a2bf33c6.png">
<img width="360" alt="Screen Shot 2022-10-17 at 12 30 17 PM" src="https://user-images.githubusercontent.com/48420377/196243973-c585114e-8a3c-4fe8-85c4-c1f974eb5ae7.png">

Implementation:
![Screen Shot 2022-10-17 at 12 35 40 PM](https://user-images.githubusercontent.com/48420377/196244894-c4bae800-7c22-4a9f-85a4-0c372442dd9a.png)

**Comment by Viglino** [comment]
It's a typescript error, use the types-ol-ext project issue tracker:
> https://github.com/Siedlerchr/types-ol-ext/issues

**Comment by JonnyDeates** [comment]
Didn't realize that it was a separate library, posted the issue there. Thanks
