### ISSUE TITLE
Type error with UndoRedo options

### ISSUE THREAD

**Issue by sdfricke** [Viglino/ol-ext#875]
Hello, first I would like to say thank you for putting this library together, it has been a great help to me.  I have been working to implement the UndoRedo interaction and have ran into a couple issues.  There first is a type issue when using the layers option.  My implementation is as follows:

`new UndoRedo({
      layers
    });`

Where layers is an array of vector layers.  I however get the type error: "Argument of type '{ layers: VectorLayer<VectorSource<Geometry>>[]; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'layers' does not exist in type 'Options'.

layers is one of the options for UndoRedo, so I'm wondering if the Options type needs to be added to it?

I have also noticed an issue where if I add the first feature to my layer source, hasUndo() is still returning 0.  When I add a second feature, then hasUndo() is greater than 0.

I have also seen an issue with the hasRedo(), when I add a feature, and then perform an edit on it, such as the translate interaction, and move the feature to a new spot on the map, and then I undo that translate interaction, hasRedo() returns 0, even though you should be able to redo the translate interaction that you undid.

I would greatly appreciate if you could let me know if these are issues on your side too.  Thank you for your time!

**Comment by Viglino** [comment]
The syntax should be like that:
```javascript
new UndoRedo({ layers: [layer1, layer2] });
```
I don't notice such behavior on example: http://localhost:8181/examples/interaction/map.interaction.undoredo.html
Do you have a working example?

**Comment by sdfricke** [comment]
> The syntax should be like that:
> 
> ```js
> new UndoRedo({ layers: [layer1, layer2] });
> ```
> 
> I don't notice such behavior on example: http://localhost:8181/examples/interaction/map.interaction.undoredo.html Do you have a working example?

Thank you for the reply.  Yes, I am supplying an array for vector layers such as that, I have a variable called layers, which is an array such as [layer1, layer2].
