### ISSUE TITLE
"unselectable"-attribute on Layerswitcher lable throws HTML-validation error

### ISSUE THREAD

**Issue by fcjm** [Viglino/ol-ext#877]
Hi,

I am working on a project which requires to be compliant to the WCAG 2.1 standards. 

One fundamental check to see whether a page is accessible or not is checking the page for valid HTML. The HTML Validator that I use is the "Nu Html Checker" bookmarklet (https://validator.github.io/validator/site/nu-about.html) in combination with the "WCAG parsing only" bookmarklet (https://codepen.io/stevef/pen/VRZdGJ). This validates a page and filters the results for critical HTML Validation errors according to the WCAG standard.

Now to the problem itself. In all of the examples of the Layerswitcher component there are critical errors being thrown regarding the labels of each layer. The error looks as follows:

![image](https://user-images.githubusercontent.com/22943731/196951115-c1130fc9-800a-47a0-863a-2b03986a8bc8.png)

In order for us to use this component in one of our releases we have to get rid of this validation error. This is doable by waiting for the component to be rendered and then removing the attribute manually via JS. It would be ideal though, if a solution could be found so that this problem can be fixed in this project.

It would be great if you could look into this.

**Comment by Viglino** [comment]
You're right... I don't know where this attribute come from!
I've just remove it in the last commit.
Tell me if it's ok for you.
Tell me if you have other accessibility error, I'll try to do my best.

**Comment by fcjm** [comment]
Thank you very much for the swift reply and fix. Now everything validates nicely. I am closing this issue since the problem has been solved. I will open new issues when I have other problems regarding accessibility.

Thanks again!
