### ISSUE TITLE
NPM version 2.0.0 is missing js and min.js

### ISSUE THREAD

**Issue by Cavva79** [Viglino/ol-ext#88]
It seems that npm repository library is missing .js and .min.js.

Inside https://registry.npmjs.org/ol-ext/-/ol-ext-2.0.0.tgz there is:
- package
  - CHANGELOG.md
  - composer.json
  - CONTRIBUTING.md
  - control
  - DEVELOPING.md
  - dist
    - ol-ext.css
    - ol-ext.min.css
  - doc
  - featureanimation
  - filter
  - geom
  - gulpfile.js
  - index.html
  - interaction
  - layer
  - LICENSE.md
  - overlay
  - package.json
  - README.md
  - render
  - source
  - style
  - utils

**Comment by Viglino** [comment]
ol-ext  (> 2.0) is no provided as ES2015 modules (like ol is) and the js files are no more included.
Perhaps I should consider providing a npm package with the js too.

**Comment by Cavva79** [comment]
@Viglino ,
would be great if you will

**Comment by Viglino** [comment]
I've published a new package openlayers-ext to use with the js files: https://www.npmjs.com/package/openlayers-ext

**Comment by Cavva79** [comment]
@Viglino ,
thank you
