### ISSUE TITLE
Video Recorder not working on XYZ Layer

### ISSUE THREAD

**Issue by hctan89** [Viglino/ol-ext#880]
Hi, first of all, thanks for the great library.
I am using this library in my Angular Project.
So I was testing out the video recorder and layer switcher.
The recording works well on OSM layer and stamen layer but not XYZ layer..
Once I switch to any XYZ layer, the recording button is not responding though.

I've created an example on sandbox. Please kindly have a look.
https://codesandbox.io/s/test-ol-ext-filter-angular-forked-4nte55?file=/src/app/app.component.ts

**Steps to reproduce:**

1. Click recording on OSM layer first. Works normally.
2. Stop recording
3. Switch to Stamen layer, recording works normally as well.
4. Switch to Toner, which is a XYZ layer, test recording. Not responding though.

Please kindly assist.
Thanks a lot in advance.

**Comment by Viglino** [comment]
Just catch the error event:
```javascript
this.videoRecorder.on('error', console.log)
```
to see:
```json
{
  "type": "error", 
  "error": Failed to execute 'captureStream' on 'HTMLCanvasElement': Canvas is not origin-clean.
  "target": olcontrolVideoRecorder
}
```
The `crossOrigin` option  is not set on the XYZ source (see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image for more detail).
You have to set it to `"Anonymous"`:
```javascript
const proplematicLayer = new ol.layer.Tile({
  visible: true,
  source: new ol.source.XYZ({
    url: "https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png",
   crossOrign: "Anonymous"
  })
})
```
or just use the Stamen class:
```javascript
const proplematicLayer = new ol.layer.Tile({
  source: new ol.source.Stamen({
    layer: 'toner'
  })
})
```

**Comment by hctan89** [comment]
Hi Viglino, it works like a charm.
Thanks for your swift response!
