### ISSUE TITLE
File import error on ol-ext/overlay/Tooltip.js

### ISSUE THREAD

**Issue by lanzze** [Viglino/ol-ext#881]
Look this image(version 4.0.2):
 
![image](https://user-images.githubusercontent.com/33625491/198485601-ef36e1cd-479a-40b0-a252-bff95b3f84a9.png)

**Comment by Viglino** [comment]
fix in a98ea7f00d030e3f6ec009a00fcf10aeba59619d
Just published 4.0.3 on npm
