### ISSUE TITLE
Uncaught TypeError in Transform.js

### ISSUE THREAD

**Issue by hippo1234** [Viglino/ol-ext#883]
When adding an event handler for the Transform `scale` event, the following condition fails in `Transform.js:650`:
`if (this.get('modifyCenter')(evt)) {`
The error message prints `Uncaught TypeError: this.get(...) is not a function`

Adding a logical AND (&&) in between `this.get('modifyCenter')` and `(evt)` seems to fix the issue:
`if (this.get('modifyCenter') && (evt)) {`
Not sure if this is a bug, or just something local in my setup?

**Comment by mike-000** [comment]
`this.get('modifyCenter')` should return a function.  What have you specified for `modifyCenter` the the interaction constructor?
