### ISSUE TITLE
How can I: Select a group images in the Exif2geojson tool and get an output?

### ISSUE THREAD

**Issue by growe19** [Viglino/ol-ext#884]
![map](https://user-images.githubusercontent.com/6546748/199720598-f4937d85-3f71-4954-a5bf-e6bc1fc82d5e.jpeg)

Does anyone know how I could select a group of points/markers from the Exif2geojson tool (like in the screenshot) and then have a list of the filenames of only the selected images? 

I am trying to filter out images in the group that I do not need.

**Comment by Viglino** [comment]
You have to use a third party tool to edit the GeoJSON select and save a new one...
