### ISSUE TITLE
Layer Switcher - Help with CSS

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#885]
Hi,

for playing with the Layer Switcher I created an example at [https://codepen.io/gott18/pen/eYKzWXy](https://codepen.io/gott18/pen/eYKzWXy) that is based on [https://viglino.github.io/ol-ext/examples/control/map.switcher2.html](https://viglino.github.io/ol-ext/examples/control/map.switcher2.html).

The example works, but it is very hard to understand all the CSS styling of the Layer Switcher.
Is there any documentation or further explanation on how those CSS classes fit together and how to use them?

Thanks a lot,

Thomas

**Comment by Viglino** [comment]
No, there is not.
You have to dig into DOM with the browser debugger...
including before and after style...

**Comment by Viglino** [comment]
There is also a [switcher shop example](https://viglino.github.io/ol-ext/examples/control/map.switcher.shop.html) (like a photoshop layer switcher to add more features) that can interest you...
