### ISSUE TITLE
layerswitcher extends/reduces layers legends

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#888]
Good morning,
I use your layerswitcher and I ask for help to extends/reduces the legends of the different layers that I have now placed under the layer title as in this example https://www.opengis.it/ente/demo/

Can you think of a method to recommend? Maybe a +/- which extends/reduces as for layer groups?

![image](https://user-images.githubusercontent.com/89784373/200937459-701fd625-c9e2-4312-b38c-172373f48043.png)

For now the legends are written under each layer like this:

```
var lyr_Zonizzazione = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Zonizzazione, 
                style: style_Zonizzazione,
				permalink: 'Zonizzazione',
				popuplayertitle: 'Zonizzazione',
                interactive: true,
    title: 'Zonizzazione<br />\
    <img src="styles/legend/Zonizzazione_0.png" /> A1<br />\
    <img src="styles/legend/Zonizzazione_1.png" /> A2<br />\
    <img src="styles/legend/Zonizzazione_2.png" /> A3<br />\
    <img src="styles/legend/Zonizzazione_3.png" /> A4<br />\
    <img src="styles/legend/Zonizzazione_4.png" /> B1<br />\
    <img src="styles/legend/Zonizzazione_5.png" /> B2<br />\
    <img src="styles/legend/Zonizzazione_6.png" /> B3<br />\
    <img src="styles/legend/Zonizzazione_7.png" /> B4<br />\
    <img src="styles/legend/Zonizzazione_8.png" /> B5<br />\
    <img src="styles/legend/Zonizzazione_9.png" /> B6<br />\
```

Thank you.

**Comment by Viglino** [comment]
I don't think setting the legend in the LayerSwitcher is a good practice.

Maybe you can use the LegendControl (see https://viglino.github.io/ol-ext/examples/legend/map.control.legend.layer.html)
You can also use the info button to open a dialog to display the legend.

Otherwise if you want to place it in the LayerSwitcher, use the `drawlist` event to add you own element in the list.
```javascript
switcher.on('drawlist', function(e) {
  // The current layer
  var layer = e.layer;
  // The current list element
  var elt = e.li;
  // add a button
  var myElement = document.createElement('DIV')
  myElement.innerHTML = `<img src="styles/legend/Zonizzazione_0.png" /> A1<br />\
    <img src="styles/legend/Zonizzazione_1.png" /> A2<br />\
    ...`
  elt.appendChild(myElement)
});
```

**Comment by andreaordonselli** [comment]
Hello and thanks for the reply.
I thought about the 3 solutions you proposed to me and I would like to choose the new [map.control.legend.layer](https://viglino.github.io/ol-ext/examples/legend/map.control.legend.layer.html) 
I could modify my layers by creating the `legend` property, like this:

```
var lyr_Edifici = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Edifici, 
                style: style_Edifici,
				permalink: 'Edifici',
				popuplayertitle: 'Edifici',
                interactive: true,
    title: 'Edifici',
    legend: '\
    <img src="styles/legend/Edifici_0.png" /> Edificio civile<br />\
    <img src="styles/legend/Edifici_1.png" /> Edificio industriale<br />\
    <img src="styles/legend/Edifici_2.png" /> Edificio civile in costruzione<br />\
    <img src="styles/legend/Edifici_3.png" /> Chiesa<br />'
        });
```

Can you help me to automatically compile the legend by reading the `title` and `legend` keys of the various visible layers?
Thank you.
