### ISSUE TITLE
How to use ol-ext with Angular 5 and Typecript 2.4

### ISSUE THREAD

**Issue by Abdullah0991** [Viglino/ol-ext#89]
I am sorry if my question shouldn't be here but I want to use ol-ext in my application and I didn't know how. Any sample code will be appreciated.

Thanks.

**Comment by Viglino** [comment]
You can use it as any js library (#59).
Or like any js module such as ol (https://stackoverflow.com/questions/48283679/use-openlayers-4-with-angular-5)

**Comment by Abdullah0991** [comment]
I am using ol-ext like using openlayers but I found that there is no ol-ext.js in 'dist' directory. Just css files. I think this is the problem.

**Comment by Viglino** [comment]
Look at #88.
I've published a new package openlayers-ext to use with the js files: https://www.npmjs.com/package/openlayers-ext

**Comment by Abdullah0991** [comment]
Thank you .. Is there type definitions for the library?

**Comment by Viglino** [comment]
No there isn't.
