### ISSUE TITLE
How to change autocomplete items order in searchFeature component?

### ISSUE THREAD

**Issue by borjaevo** [Viglino/ol-ext#890]
I have a searchFeature components that searchs a property containing a text and a number (address) like for example "Hazas 21"
In this case, the autocomplete select items appear in a strange order, and i would like to sort them by the number part of the string. 

Thanks

**Comment by andreaordonselli** [comment]
Test to overwrite the autocomplete function of the search to add a sort on the result.

```
var search = new ol.control.SearchFeature(...);
search.autocomplete = function(s) {
  // Call default search
  var result = ol.control.SearchFeature.prototype.autocomplete.call(this, s);
  result = result.sort(function(f1, f2) {
    if (search.getSearchString(f1) < search.getSearchString(f2)) return -1;
    if (search.getSearchString(f1) > search.getSearchString(f2)) return 1;
    return 0;
  });
  return result;
}
```

**Comment by Viglino** [comment]
💡 Great idea!
I've added a sort parameter to sort the autocomplete list (meanwhile @andreaordonselli trick makes the job):
```javascript
var search = new ol.control.SearchFeature(
  ...,
  sort: function(f1, f2) {
    if (search.getSearchString(f1) < search.getSearchString(f2)) return -1;
    if (search.getSearchString(f1) > search.getSearchString(f2)) return 1;
    return 0;
  }
}
```

**Comment by borjaevo** [comment]
Thats great!! I already did this and is specially useful you can sort the result by other property if you want, also, i added a "tolowercase()" to the property and text input. It would be great to have it asa boolean parameter as well if you want to ignore case when searching, that is most of the cases i think.

**Comment by Viglino** [comment]
> useful you can sort the result by other
Yes you can implement your own weight function (sort by distance to the center of the map or by population...).
