### ISSUE TITLE
Bugs in LayerShop example?

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#891]
Hi,

when changing the selected layer between "CORINE Land Cover" and "PCI vecteur" in the [LayerShop example](https://viglino.github.io/ol-ext/examples/control/map.switcher.shop.html) the width of the LayerShop menu also changes. It seems that there is some additional "space" added at the end of the "CORINE Land Cover" layer, whenever it is selected.
Is this a bug or as expected?

Furthermore, when I change the checkboxes to show/hide layers it happens from time to time that I click on a checkbox and it ignores the mouse click. If I click a second time it works as expected. I was not able so far to exactly reproduce this behavior. Maybe, it has something to do with selecting another layer (clicking on the layer name and not the checkbox).
Can someone reproduce this? Does someone have an idea what could cause this behavior?

Thanks.

**Comment by Viglino** [comment]
The width of the layer shop depends on its content (top/bottom bar width, layer name length ...) 
You have to define it using css if you want it fixed.
Yet there is only a max-width defined:
```CSS
.ol-control.ol-layerswitcher.ol-layer-shop {
  max-width: 16em;
}
```
