### ISSUE TITLE
Select Control - add layer choice

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#893]
I would like to use this control by adding an initial combo box to choose the layer in which to execute the query (showing only the layers visible in the map at that moment).  It's possible?
Thanks

http://viglino.github.io/ol-ext/examples/control/map.control.select.html

**Comment by Viglino** [comment]
You can access the control element and add your own select to modify the selection source:
```javascript
var selectElt = document.createElement('SELECT')
selectCtrl.element.querySelector('div').prepend(selectElt);
['layer1','layer2'].forEach(function(l) {
  ol.ext.element.create('OPTION', {
    text: l,
    parent: selectElt
  })
})
```

**Comment by andreaordonselli** [comment]
Good morning,
with this code I ask for the search in 2 layers

```
var selectCtrl = new ol.control.Select({
    // target: $(".options").get(0),
    source: [jsonSource_Edifici, jsonSource_PaiFraneagg2016],
    property: $(".options select").val()
  });
  map.addControl (selectCtrl);
  selectCtrl.on('select', function(e) {
    console.log(e);
    selecti.getFeatures().clear();
    for (var i=0, f; f=e.features[i]; i++) {
      selecti.getFeatures().push(f);
    }
  });
```

and adding the code you recommended, the layer filter combo box appears
```
// A select element
var selectElt = document.createElement('SELECT')
// Prepend select
selectCtrl.element.querySelector('div').prepend(selectElt);
// Add options
['jsonSource_Edifici','jsonSource_PaiFraneagg2016'].forEach(function(l) {
  ol.ext.element.create('OPTION', {
    text: l,
    parent: selectElt
  })
})  
```
but when I click in the "attribute" field the list shows the fields of both sources, without filtering the content.
For example, the Edifici source contains only the fields: "description" "quota1" and "quota2"
The other fields belong to the other source

![image](https://user-images.githubusercontent.com/89784373/203759024-212e682e-5289-4017-8d19-42b0812a0bc9.png)

Can you help me filter content based on layer selection?

Finally, I ask you: would it be possible not to rewrite all the sources manually but to recall the key "source" of each layer visible on the map?
Here is an example layer:
```
var lyr_Edifici = new ol.layer.Vector({
                declutter: true,
                source: jsonSource_Edifici, 
                style: style_Edifici,
                permalink: 'Edifici',
                interactive: true,
                title: 'Edifici'
                });
```

**Comment by Viglino** [comment]
You have to change the source of the control on select:
```javascript
selectElt.addEventListener('change', function() {
  if (selectElt.value === 'jsonSource_Edifici') {
    selectCtrl.setSources([jsonSource_Edifici])
  } else {
    selectCtrl.setSources([jsonSource_PaiFraneagg2016])
  }
})
```

**Comment by andreaordonselli** [comment]
It works perfectly. A thousand thanks.
