### ISSUE TITLE
print dialog -reduce print size

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#894]
Hello, I use the print dialog control without filesaver and jspdf. When I click print (setting a horizontal A4 print) I get to the browser print preview, but this comes out of the single A4 sheet, do you know how to make it fit inside?
![image](https://user-images.githubusercontent.com/89784373/204229931-c96e801b-c14c-4f6c-b5dc-f8b13491ad09.png)
Maybe I can do something to make the preview of the print dialog smaller?
I show the scale control, so if a user shrinks the preview to fit A4, the scale control value will be wrong in the final print.
Example project published [here](https://www.opengis.it/demo/) (print icon top right)
Thank you

**Comment by andreaordonselli** [comment]
It works, thank you very much.

**Comment by andreaordonselli** [comment]
In order not to let the user set other things in the browser window, I decided to decrease all the dimensions of the sheets by 25. Do you think there is a form error in this choice of mine?
I wrote like this:

```
// Print control
		var printControl = new ol.control.PrintDialog();
		printControl.setSize('A4');
		printControl.setOrientation('landscape');
		ol.control.PrintDialog.prototype.paperSize = {
		  '': null,
		  'A0': [816,1164],
		  'A1': [569,816],
		  'A2': [395,569],
		  'A3': [272,395],
		  'A4': [185,272],
		  'US Letter': [190.9,254.4],
		  'A5': [123,185],
		  'B4': [232,339],
		  'B5': [157,232]
		};		
		map.addControl(printControl);
```

**Comment by Viglino** [comment]
You can set the paper size as you want.
I think the problem is due to rounding effect when converting to printer units...

**Comment by andreaordonselli** [comment]
Thanks
