### ISSUE TITLE
Animated cluster closing on click!

### ISSUE THREAD

**Issue by Bahaa-Fadhil** [Viglino/ol-ext#895]
I have a question. Is there any way to work around so that when you click on cluster, the clustering should open and close ?

Can the cluster close if the user is clicking again inside the center of the cluster? Currently, it only opens but not close ?

**Comment by Viglino** [comment]
You have to set a toggleCondition to toggle selection (see ol doc https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html), default condition toggle when shift key is hold:
```javascript
var selectCluster = new ol.interaction.SelectCluster({
  ...
 toggleCondition: ol.events.condition.singleClick,
})
```

**Comment by Bahaa-Fadhil** [comment]
Thanks for your feedback. It was helpful :)
