### ISSUE TITLE
layerswitcher - extent - possible bug

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#898]
Good morning,
I use your layerswitcher and I activated the extent for each layer in the legend with the following example code

```
var extent_layer = jsonSource_layer.getExtent();
lyr_layer.setProperties('extent');
lyr_layer.set('extent' , extent_layer);
```

When I click on the zoom extent button in the legend, some random layers fade out. This happens in the css but I don't understand why. 

**ol-ext.css:1848**
```
.ol-layerswitcher .panel li.ol-layer-hidden {
    opacity: 0.6;
}
```

It seems that the `.ol-layer-hidden` property is randomly applied to some layers
![2022-12-12 12_39_37-Window](https://user-images.githubusercontent.com/89784373/207036727-a597d004-31be-43b8-9865-9052789ee44e.png)

![Senza titolo-1](https://user-images.githubusercontent.com/89784373/207047682-0fbf2800-028d-450a-834f-39d3634b8ba4.jpg)

If I click the zoom extent button of other layers, randomly further other layers take this property.
I posted an example [here](https://www.ordonselli.com/z_extent/ente/demo/)

**Comment by Allevo-SR** [comment]
The layerswitcher checks the extent of each layer. As soon as the extent does not intersect with the displayed map extent, the layer is grayed out in the layer tree. Great feature!
