### ISSUE TITLE
ol-ext color filter on map

### ISSUE THREAD

**Issue by shiva-heliware** [Viglino/ol-ext#899]
when i am using add color effects on map than it is showing error :-------- Property 'addFilter' does not exist on type 'TileLayer<XYZ>'

**Comment by Viglino** [comment]
Do you have a code?

**Comment by Viglino** [comment]
It's working for me: see https://codesandbox.io/s/hopeful-worker-xuf3jl
Be careful you are using both ol JS namespace and ol ES6 modules in the same project.
You have to make a choice: 
`import * as ol from 'ol';`  (namespace ol) or `import` each modules.
ie. remove `import * as ol from 'ol'` use `import Map from 'ol/Map'`
