### ISSUE TITLE
Control bar/sub-bar + my own function inside it

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#90]
Is it possible to use my own function with sub-bar control?
Eg. function zoomToExtent:
```
var extent_1 = new ol.control.ZoomToExtent({
      extent: [2568340.78262743, 7008314.88225432, 2575661.54548716, 7013226.24350724] });
var extent_2 = new ol.control.ZoomToExtent({
      extent: [2571004.70285516, 7005917.85332414, 2576412.8924989, 7011651.74585406] });


var extent-bar = new ol.control.Bar(
	{ toggleOne: true,
	  controls:
		[ 
                  new ol.control.Toggle({ html:"1", autoActivate: true, onToggle: function() {  extent_1   } }),								
		  new ol.control.Toggle({ html:"2", onToggle: function() {  extent_2   }  })
	 	]
	});
var mainbar = new ol.control.Bar(
	{	controls: [
			new ol.control.Toggle(
				{ html: 'R',
					//1-level
					bar: extent-bar ,
					onToggle: function () {  }			
				})]
		
	});
```
Thanks for this extension pack :)

**Comment by Viglino** [comment]
Hi,
[ol.conrol.Button](http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Button.html), [ol.control. TextButton](http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.TextButton.html) or [ol.control.Toggle](http://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Toggle.html) are simple controls that have there own function you can customize with the `handleClick` or `onToggle` options.
Then you just have to add this button in your bar.
````javascript
var extent-bar = new ol.control.Bar({ 
  controls: [ 
      new ol.control.Button ({ 
        html:"1", 
        // My own click function
        handleClick: function() {  
            map.getView().fitExtent(extent_1, map.getSize());
        }
     }),								
  ]
});
````

**Comment by Bear4** [comment]
Thanks for reply,
in ol 4.6.4 this works proper:
`var extent =  [2568340.78262743, 7008314.88225432, 2575661.54548716, 7013226.24350724];`

```
var extent-bar = new ol.control.Bar({ 
  controls: [ 
      new ol.control.Button ({ 
        html:"1", 
        // My own click function
        handleClick: function() {  
            map.getView().fit(extent, map.getSize());
        }
     }),								
  ]
});
```

**Comment by Bear4** [comment]
Addition question for this:
something like tip Label for button?

**Comment by Viglino** [comment]
You can also add a title to the button using the `title` option to provide a tip on the button.
