### ISSUE TITLE
Something wrong with ol-ext/Print

### ISSUE THREAD

**Issue by ltt2801** [Viglino/ol-ext#900]
The document of ol-ext/Print said me that fastPrint method doesn't have callback parameter but the file source has it
fastPrint(options, callback)
and the print method doesn't have callback paramater.
print(options) {

Refer:
https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.Print.html
https://github.com/Viglino/ol-ext/blob/master/src/control/Print.js

**Comment by Viglino** [comment]
fixed in https://github.com/Siedlerchr/types-ol-ext/issues/114

**Comment by ltt2801** [comment]
Sorry but the documentation you wrote and your source code aren't match methods
On line 174 of print.js, the print method has only one parameter options but the documentation print method has two parameters: callback and options
Please verify it

**Comment by Viglino** [comment]
Updated  : https://github.com/Viglino/ol-ext/blob/master/src/control/Print.js#L161
