### ISSUE TITLE
Animation flowline along path

### ISSUE THREAD

**Issue by lizemin5235** [Viglino/ol-ext#904]
I want to animate flowline feature along a path using ol.featureAnimation.Path, I am trying to use  linestring feature instead of point feature then apply the flowline style, but it do not work. Here is some pieces of my code, I don't know what went wrong.
` 
var flowline = new OLExtFlowLine({
    color: "#fff",
    color2: "rgba(255,255,255,0)",
    width: 100,
    width2: 100,
    lineCap: "round",
    arrow: 0,
  });
const animateFeature = () => {
    if (path) {
      path.map((item) => {
        f = new Feature(
          new LineString([
            [0, 0],
            [0.2, 0.2],
          ])
        );
        //f = new Feature(new Point([0, 0]));
        f.setStyle(recStyle);
        //f.setStyle(flowline);
        anim = new OLExtPath({
          path: item,
          rotate: true,
          // easing: ol.easing[$("#easing").val()],
          speed: 1,
          revers: true,
        });
        controler = vectorLayer.animateFeature(f, anim);
      });`

**Comment by Viglino** [comment]
There is no such animation on lines. Only point's animation features along the path...
