### ISSUE TITLE
layerswitcher - no Class change when deactivating a visible layer on startup

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#906]
Hello,
i use your layerswitcher and in the layer title i set the `layerlegend` to see below (with specific class)

```
var lyr_Edifici = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Edifici, 
                style: style_Edifici,
                permalink: 'Edifici',
                popuplayertitle: 'Edifici',
                interactive: true,
    title: 'Edifici<br />\
    <a class="layerlegend"<br />\
    <img src="styles/legend/Edifici_0.png" /> Edificio civile<br />\
    <img src="styles/legend/Edifici_1.png" /> Edificio industriale<br />\
    <img src="styles/legend/Edifici_2.png" /> Edificio civile in costruzione<br />\
    <img src="styles/legend/Edifici_3.png" /> Chiesa<br /></a>'
        });
```
Result:
![image](https://user-images.githubusercontent.com/89784373/213801014-321c4eb0-ea38-4da8-a9de-70bad805f0d2.png)

I would like the legend to appear when the level is visible on the map and disappear when the level is deactivated (unchecked)

I wrote this and it works fine except for layers visible on system startup
```
/*layerlegend before*/
.ol-layerswitcher .layerlegend {
        display: block;
	height: auto;
	max-height: 0px; 
	transition: all 1s;
}
```
```
/*layerlegend for ol-visible tile*/
.ol-layerswitcher .ol-layer-tile.ol-visible .layerlegend{
	height: auto;
	max-height: 250px;
	overflow-y: auto;
	overflow-x: auto;
	width: 100%;
}
```

For layers visible on startup it doesn't work because they have this class
![2023-01-20 21_29_03-ol-ext_ Layerswitcher](https://user-images.githubusercontent.com/89784373/213800834-f1d4d304-f065-43c6-8ec4-37b279ad0781.png)

and when you deactivate the level the first time the class remains the same
![2023-01-20 21_29_15-ol-ext_ Layerswitcher](https://user-images.githubusercontent.com/89784373/213800841-e7581113-a3c9-43b2-8881-21a951d69824.png)

then when you reactivate the layer it acquires, only now, `ol-visible`
![2023-01-20 21_29_23-ol-ext_ Layerswitcher](https://user-images.githubusercontent.com/89784373/213800855-0eb709ed-afa2-4ec3-a613-2d230b35e7af.png)

Is it possible to have these layers acquire `ol-visible` class at system startup automatically?
Thank you very much

**Comment by Viglino** [comment]
Added to the last commit

**Comment by andreaordonselli** [comment]
Thanks
