### ISSUE TITLE
Display one ore more element only when layerswitcher is open

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#907]
Hello,
for graphic convenience I have placed some buttons in this position:
![2023-01-24 12_02_39-Window](https://user-images.githubusercontent.com/89784373/214275437-4062cd22-ef0b-4091-852e-b1dc5f7affdd.jpg)

I wish I could only see them when the layerswitcher is open but I can't.
 By default I set `display: none` to the elements like
```
.ol-print{
	display: none;
	}
```	
And writing `display: unset` or `display: block` like this I thought I could see them when layerswitcher is open, instead they remain visible even when layerswitcher is closed

```
.ol-layerswitcher.ol-forceopen .ol-print{
	display:block!important;
	}
```

where am i wrong?
Thank you.

**Comment by Viglino** [comment]
Maybe you can try ol/control/LayerShop that let's you add tool bars in the layerswitcher easily (with buttons and other inputs)
https://viglino.github.io/ol-ext/examples/control/map.switcher.shop.html
![](https://viglino.github.io/ol-ext/img/map.switcher.shop.jpg)

**Comment by andreaordonselli** [comment]
Thanks, that's exactly what I was looking for.
