### ISSUE TITLE
Remove title attribute from Layerswitcher label

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#908]
Good morning,
Is it possible to remove the title attribute from the layerswitcher label so that the square with the same title doesn't appear when you hover over it with the mouse?
![2023-01-24 12_45_33-Window](https://user-images.githubusercontent.com/89784373/214284314-2123af6e-4e0b-40de-941c-cf6eb224828f.png)

By manually deleting it from the console it seems that everything still works
![2023-01-24 12_47_20-Window](https://user-images.githubusercontent.com/89784373/214284651-b4780663-23ee-42fc-a1d9-9557d0c412a2.png)

Thank you very much

**Comment by Viglino** [comment]
You can remove it by listening to drawlist event:
```javascript
// Do something when the list is drawn
switcher.on('drawlist', function(e) {
  // remove list label element title
  e.li.querySelector('label').title = ''
})
```

**Comment by Viglino** [comment]
The title is used to display long layer name (when truncated in the list)

**Comment by andreaordonselli** [comment]
thank you very much
