### ISSUE TITLE
Layerswitcher deactivate click in the label to turn on/off the layer

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#909]
In this Layerswitcher http://viglino.github.io/ol-ext/examples/control/map.switcher.filter.html the layers are activated and deactivated both by clicking on the corresponding checkbox and by clicking on the label. Is it possible to deactivate the click in the label keeping only the one in the checkbox?

Thank you

**Comment by Viglino** [comment]
Just prevent click on the span in the label by adding a listener to it on switcher `drawlist`:
```javascript
lswitcher.on('drawlist', function(e) {
    // get the span in the li
    e.li.querySelector('span').addEventListener('click', function(e) {
        // prevent click propagation
        e.stopPropagation()
    })
})
```
You can also use LayerShop control: http://viglino.github.io/ol-ext/examples/control/map.switcher.shop.html

**Comment by andreaordonselli** [comment]
I'm trying to add an arrow that expands/collapses the layer legend under the title.
Does the code you wrote allow the activation of another click inside the span?

I'm trying to write this, but click on the arrow doesn't work, maybe because `stopPropagation ` takes effect?
```
jquery
$(document).ready(function() {
  $(".arrow img").click(function() {
   $(this).parent().toggleClass("active");
    $(".arrow .layerlegend").slideToggle("slow");
     return false; 
    });
});

css
#secondImage { display: none;}
.active #firstImage { display:none;}
.active #secondImage { display: inline-block;}

```

![2023-01-27 10_57_49-SIT Demo Opengis](https://user-images.githubusercontent.com/89784373/215059329-2d9b796e-7bea-48bf-ad15-313f7cfd10ea.png)

**Comment by Viglino** [comment]
You have to listen to the `drawlist` event to insert the arrow and the `onclick` listener on it (not the document ready).
The layerswitcher is redrawn when a new layer is added/modifed and not ready when document is ready...

**Comment by andreaordonselli** [comment]
Thank you, really, thank you. You will have understood that I am not an expert but all your advice gives me a starting point to study, search and deepen.
I wrote this and it works fine:

```
layerSwitcher.on('drawlist', function (e) {	
   $(".li-content #layertitle").click(function() {
       $(this).toggleClass("active");
       e.preventDefault();
    });
});
```
The result is excellent, by clicking on the text layer or on the up/down arrow I can expand/collapse the legend:
![image](https://user-images.githubusercontent.com/89784373/216590187-33c987af-648b-4945-a3db-1459fa84821f.png)

A complex result is posted [here](https://www.opengis.it/prototipo/ballao)

One small problem still remains: when I use the + / - to expand/collapse the layer groups, everything is reset. While having an expanded visible legend, it collapses. I don't understand what happens from code, I only see this:
![image](https://user-images.githubusercontent.com/89784373/216591090-5e4f9a62-dc3d-48cf-8d57-2bd33f8ad43a.png)

**Comment by Viglino** [comment]
Actually, every thing is reset on `drawlist`... ie. when you add a new layer or when you reorder the layer list or when you modify a layer (change name etc.) 
You have to store the legend visibility to apply it on redraw...
```javascript
layerSwitcher.on('drawlist', function (e) {
   // Show if active
   var active = e.layer.get('legendActive')
   if (active) $(".li-content #layertitle").addClass('active');
   // Toggle on click
   $(".li-content #layertitle").click(function() {
       e.layer.set('legendActive', !e.layer.get('legendActive'))
       $(this).toggleClass("active");
       e.preventDefault();
    });
});
```

**Comment by andreaordonselli** [comment]
A strange thing happens, a sort of upward propagation, let me explain:
If I show the legend of one layer and then expand/reduce any group, all the legends of all layers above are shown, but not of those below . You can see the problem in this [link](https://www.opengis.it/prototipo/ballao)

**Comment by Viglino** [comment]
There is an error in the console:
```
Uncaught TypeError: e.preventDefault is not a function
    at HTMLDivElement.<anonymous> (opengis.js:1556:10)
    at HTMLDivElement.dispatch (jquery-1.11.0.min.js:3:8066)
    at r.handle (jquery-1.11.0.min.js:3:4767)
```
The argument `e` is missing in the function:
```javascript
$(".li-content #layertitle").click(function(/* e is missing */ e) {
	e.layer.set('legendActive', !e.layer.get('legendActive'))
	$(this).toggleClass("active");
	e.preventDefault(); 
});
```

**Comment by andreaordonselli** [comment]
I updated the code with the missing "e", but now I get this error in the console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'set')`
I have updated the online example
Thank you

**Comment by Viglino** [comment]
Their is 2 events `e` (one for the draw list and one for the click, just use e2 for the second one (the layer is the one of the first event:
```javascript
layerSwitcher.on('drawlist', function (e) {
   // Show if active
   var active = e.layer.get('legendActive')
   if (active) $(".li-content #layertitle").addClass('active');
var layer = e.layer;
   // Toggle on click
   $(".li-content #layertitle").click(function(e2) {
       layer.set('legendActive', !layer.get('legendActive'))
       $(this).toggleClass("active");
       e2.preventDefault();
    });
});
```

**Comment by andreaordonselli** [comment]
With your modification, the error in the console no longer exists but the problem I mentioned in previous messages remains. If I show the legend of one layer and then expand/reduce any group, all the legends of all layers above are shown, but not of those below .
You can see the problem in this [link](https://www.opengis.it/prototipo/ballao)

**Comment by Viglino** [comment]
The issue is in `$(".li-content #layertitle")` that return all li elements. You have to add the click only on the current list element (e.li)... otherwise clicking on the layertitle will set all previous layer active...
```javascript
$(".li-content #layertitle", e.li).click(function(e2) {
...
```

**Comment by andreaordonselli** [comment]
This code works perfectly.
I added `e.li` also in the first `if (active)`
```
layerSwitcher.on('drawlist', function (e) {
   // Show if active
   var active = e.layer.get('legendActive')
   if (active) $(".li-content #layertitle", e.li).addClass('active');
   var layer = e.layer;
   // Toggle on click
   $(".li-content #layertitle", e.li).click(function() {
       layer.set('legendActive', !layer.get('legendActive'))
       $(this).toggleClass("active");
       preventDefault();
    });
});
```
The only problem is the error in the console
`preventDefault is not defined at HTMLDivElement.<anonymous>`

But if I write `.click(function(e2)` and consequently `e2.preventDefault();` the toggle no longer works and the `active` class is not applied. I have updated the online [example](https://www.opengis.it/prototipo/ballao).
Thank you.

**Comment by Viglino** [comment]
`e2.preventDefault();`
```javascript
$(".li-content #layertitle", e.li).click(function(e2) {
       layer.set('legendActive', !layer.get('legendActive'))
       $(this).toggleClass("active");
       e2.preventDefault();
    });
```

**Comment by andreaordonselli** [comment]
I've already tried to write like this but the toggle doesn't work anymore.
On click the word `class ` is written, but `active` is not written

![image](https://user-images.githubusercontent.com/89784373/216960365-49403300-619b-48bc-8022-0ec516f3a7da.png)

Do you prefer that I replace the `toggleClass` with 2 different strings `addClass` and `removeClass`? In other projects it had worked and there was no need for `preventDefault`.

**Comment by andreaordonselli** [comment]
updated

**Comment by Viglino** [comment]
I don't know why but the click event is called twice.

**Comment by Viglino** [comment]
> I don't know why but the click event is called twice.
Try to add a stopPropagation to the  function.
```javascript
e2.preventDefault();
e2.stopPropagation();
```

**Comment by andreaordonselli** [comment]
I tried, it's the same thing. 
I think it's the toggle that doesn't work well. 
Maybe I could replace it with 2 separate statements: `addclass` and `removeclass`

**Comment by andreaordonselli** [comment]
Like this but making sure to remove legendactive?

```
layerSwitcher.on('drawlist', function (e) {
// Show if active
  var active = e.layer.get('legendActive')
  if (active) $(".li-content #layertitle", e.li).addClass('active');
  var layer = e.layer;
// Add class on click
  $("#layertitle #firstImage", e.li).click(function() {
  layer.set('legendActive', !layer.get('legendActive'))
  $(this).parent().addClass("active");
});
// Remove class on click
$("#layertitle #secondImage", e.li).click(function() {
   layer.set('legendActive', !layer.get('legendActive'))     // modify this line to remove "legendActive"
  $(this).parent().removeClass("active");
});
});
```
