### ISSUE TITLE
Layer switcher control -- LeafletJS version??

### ISSUE THREAD

**Issue by growe19** [Viglino/ol-ext#91]
Sorry, I know this is not an issue but is there a LeafletJS version of the 'Layer switcher control' ?

It is such a powerful plugin and would be great to add to my Leaflet project. It would be a huge problem to rebuild my maps in OL.

Thanks

**Comment by Viglino** [comment]
Sorry ol-ext are extensions for ol.
Leaflet has his own layerswitcher (L.control.layers) and you can find one here https://geoservices.ign.fr/documentation/exemples/leaflet-control-layerSwitcher.html (with reordering options).
@+
