### ISSUE TITLE
Problema with the SearchFeature Control in ol-ext

### ISSUE THREAD

**Issue by kikitoDev69** [Viglino/ol-ext#910]
I am using angular and open layers to build a map which show point in the map, that poinst are elements of GeoJSON and I want them to be filtered by the search filter tool in the ol-ext. The problem is, that as soons as I import the serach feature, it appears an error of "geolocation" and I dont know how to fix it beacuse apparently it is a problem from the library. Idk if someone can explain why.

As soon as I did this
import  SearchFeature, {Options}  from 'ol-ext/control/SearchFeature'

it appears this error

Error: node_modules/ol/Geolocation.d.ts:103:5 - error TS2416: Property 'on' in type 'Geolocation' is not assignable to the same property in base type 'BaseObject'.
  Type 'GeolocationOnSignature<EventsKey>' is not assignable to type 'ObjectOnSignature<EventsKey>'.      
    Type 'GeolocationOnSignature<EventsKey>' is not assignable to type 'OnSignature<EventTypes, BaseEvent, EventsKey>'.
      Types of parameters 'type' and 'type' are incompatible.
        Type 'EventTypes' is not assignable to type '"change"'.
          Type '"error"' is not assignable to type '"change"'.

103     on: GeolocationOnSignature<import("./events").EventsKey>;
        ~~

Error: node_modules/ol/Geolocation.d.ts:107:5 - error TS2416: Property 'once' in type 'Geolocation' is not assignable to the same property in base type 'BaseObject'.
  Type 'GeolocationOnSignature<EventsKey>' is not assignable to type 'ObjectOnSignature<EventsKey>'.      

107     once: GeolocationOnSignature<import("./events").EventsKey>;
        ~~~~


Error: node_modules/ol/Geolocation.d.ts:111:5 - error TS2416: Property 'un' in type 'Geolocation' is not assignable to the same property in base type 'BaseObject'.
  Type 'GeolocationOnSignature<void>' is not assignable to type 'ObjectOnSignature<void>'.
    Type 'GeolocationOnSignature<void>' is not assignable to type 'OnSignature<EventTypes, BaseEvent, void>'.
      Types of parameters 'type' and 'type' are incompatible.
        Type 'EventTypes' is not assignable to type '"change"'.
          Type '"error"' is not assignable to type '"change"'.

111     un: GeolocationOnSignature<void>;
        ~~

Thank u for taking time reading this and if you kind of know what it is happening I would definitely thank you more

**Comment by Viglino** [comment]
The error seems to be in the ol/Geolocation module (with is an ol module).
This module is not used by the search control (except searchGPS)...
