### ISSUE TITLE
Layer Control Panel: Toggle DIV, not map layer, possible?

### ISSUE THREAD

**Issue by growe19** [Viglino/ol-ext#912]
I have a div that appears over the top of my map that contains data that only relates to one layer. Is it possible, and how might I approach it to have a Layer in the control panel that just shows/hides that div. 
Sort of like a legend to the map layer, but it's not a legend in this case.

**Comment by Viglino** [comment]
You can add a div (or any element) in the layer switcher list when it draws.
Just listen to the `drawlist` event:
```javascript
// Do something when the list is drawn
switcher.on('drawlist', function(e) {
  // The current layer
  e.layer
  // the current list element
  e.li
  // Add a div  to the element list
  var div = document.createElement('DIV')
  div.innerHTML = 'Some div';
  e.li.appendChild(div);
})
```
