### ISSUE TITLE
Font Style - set fixed style for multiple layers and define custom glyph for each layer

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#915]
Hello, I would like to define some styles (at most 3/4 graphics) to be used for multiple layers and then, later, define the glyph for each of these layers.
I prepared this [codepen](https://codepen.io/andreaordonselli/pen/PodmQgG) with 1 example layer:
```
    var lyr_Civici = new ol.layer.Vector({
      declutter: false,
      source: jsonSource_Civici,
      style: style_Civici,
      permalink: "Civici",
      popuplayertitle: "Civici",
      interactive: true,
      title: "Civici"
    });
```
and 1 example MarkerStyle:
```
    // Style function
    function getMarkerStyle(feature) {
      var st = [];
      // Font style
      st.push(new ol.style.Style({
        image: new ol.style.FontSymbol({
          form: "marker",
          glyph: "maki-cafe",
          font: 'sans-serif',
          fontSize: 1,
          radius: 23,
          color: "black",
          fill: new ol.style.Fill({
            color: "white"
          }),
          stroke: new ol.style.Stroke({
            color: "red",
            width: 4
          })
        }),
        stroke: new ol.style.Stroke({
          width: 2,
          color: '#f80'
        }),
        fill: new ol.style.Fill({
          color: [255, 136, 0, 0.6]
        })
      }));
      return st;
    }

    function MarkerStyle(feature, resolution) {
      var s = getMarkerStyle(feature);
      return s;
    };
```

Then I replace the current style `lyr_Civici.setStyle(MarkerStyle);`
Then I would like to declare: **for lyr_Civici set the gliph value equal to "n"**

It's possible to do it?
Thank you

**Comment by Viglino** [comment]
You have to make a style associated with each glyph and return the good one in your style function depending on a parameter...
```
var mode = 'coffee';
function MarkerStyle(feature, resolution) {
  switch(mode) {
    case 'coffe': return coffeStyle;
    case 'flower': return coffeStyle;
    default: return defaultStyle;
  }
};
lyr_Civici.setStyle(MarkerStyle);
mode = 'flower';
```

**Comment by andreaordonselli** [comment]
A thousand thanks.
It works perfectly.

I would like to ask you one last thing: if I want to update font awesome to the latest version, what steps should I take?
Thanks.

**Comment by Viglino** [comment]
Here is an example that should be working : https://codepen.io/viglino/pen/QVNpzm

You have to load the Fontawesome 5 def : 
```html
<!-- Use  FontAwesome 5 defs -->
<script type="text/javascript" src="//cdn.rawgit.com/Viglino/ol-ext/master/dist/extra/FontAwesome5Def.js"></script>
```
Be aware to use the correct fontStyle
```javascrip
  var img = new ol.style.FontSymbol({
    glyph:"fa-wheelchair",
    fontStyle: '900',
    radius: 20, 
    fill: new ol.style.Fill({
      color: "#369"
    }),
    stroke: new ol.style.Stroke({
      color: "#fff",
      width: 2
    })
  })
```
Or look at #248

**Comment by andreaordonselli** [comment]
Thanks, everything works.

How do I add a glyph present in the `v6.3.0/css/all.css` but not defined in the fontdef in `FontAwesome5Def.js`?
I tried this but it doesn't work for me in the [codepen](https://codepen.io/andreaordonselli/pen/PodmQgG):

`ol.style.FontSymbol.prototype.defs.glyphs['fa-gun'] = "\e19b";`
`ol.style.FontSymbol.addDefs({ 'fa-gun': "\e19b" });`
`ol.style.FontSymbol.addDefs({},{"fa-gun": "\e19b"});`

**Comment by Viglino** [comment]
The glyph must be associated with a font:
```javascript
ol.style.FontSymbol.addDefs ({
  "font":"\"Font Awesome 5 Free\"",
  "name":"FontAwesome5",
  "copyright":"SIL OFL 1.1",
  "prefix": "fa"
},{
  "fa-gun": "\e19b",
  "other-glyph": "a",
...
 }
)
```
or if the font allready exist (loaded with `./dist/extra/FontAwesome5Def.js`)
```javascript
ol.style.FontSymbol.addDefs (
  ol.style.FontSymbol.defs.fonts['FontAwesome5'],
  {
    "fa-gun": "\e19b",
    "other-glyph": "a",
...
   }
)
```

**Comment by andreaordonselli** [comment]
Manually adding the string `"fa-gun": "\e19b"` in the `FontAwesome5Def.js` file doesn't work.
Looking at the other definitions I understood that I had to add a `"u"` in glyph value definition:
Writing `"fa-gun": "\ue19b"` all works.

The second method you mentioned with ol.style.FontSymbol.defs.fonts, which I actually prefer, doesn't work. Can you test this in your [codepen](https://codepen.io/viglino/pen/QVNpzm) ?
Thanks

**Comment by Viglino** [comment]
`\u` for unicode char

**Comment by Viglino** [comment]
The font name use `"` due to the spaces in the font name...
```javascript
// Add new definitions
ol.style.FontSymbol.addDefs (
  ol.style.FontSymbol.defs.fonts['"Font Awesome 5 Free"'],{
    "fa-gun": "\ue19b",
  }
)
```

**Comment by andreaordonselli** [comment]
Everything works perfectly, as always.
Thank you for making all this available to us.

**Comment by andreaordonselli** [comment]
> You have to make a style associated with each glyph and return the good one in your style function depending on a parameter...
> 
> ```
> var mode = 'coffee';
> function MarkerStyle(feature, resolution) {
>   switch(mode) {
>     case 'coffe': return coffeStyle;
>     case 'flower': return flowerStyle;
>     default: return defaultStyle;
>   }
> };
> lyr_Civici.setStyle(MarkerStyle);
> mode = 'flower';
> ```

If I try to configure 2 layers, the second definition `mode =` overwrites the first one, and both layers will acquire case `flower`, how can I do?

```
lyr_Civici.setStyle(MarkerStyle);
mode = 'coffe';    
lyr_EdificiSensibili.setStyle(MarkerStyle);
mode = 'flower';
```

**Comment by Viglino** [comment]
Why don't you just set the style for each layer:
```javascript
lyr_Civici.setStyle(coffeStyle);
lyr_EdificiSensibili.setStyle(flowerStyle);
```

**Comment by Viglino** [comment]
A style function takes a Feature and a number representing the view's resolution, so you can return a style depending on features attributes or view resolution.

**Comment by andreaordonselli** [comment]
I understand.  Thanks so much for everything.
