### ISSUE TITLE
mapZones control drawing images vertically

### ISSUE THREAD

**Issue by borjaevo** [Viglino/ol-ext#917]
Hello,

I had a mapZones control in the same position as the example, horizontally and in the bottom part of the page. Something is updated in the library because without changing anything, the images now are drawn vertically and i dont how can i change to be drawn as before. I cant find anything in the API docs.

**Comment by Viglino** [comment]
I think it's a css issue.
Something overwrite the style of the elements in the bar... they must have a `display: inline-block;`
```CSS
.ol-mapzone > div {
    display: inline-block;
}
```

**Comment by borjaevo** [comment]
I tried this. Its horizontally now, but each time i click in a zone, the height of the container increases... very strange behavior. Also, its not like before, zone pictures are very close to each other.
