### ISSUE TITLE
Split not work is.sources_.push is not a function  

### ISSUE THREAD

**Issue by aparzi** [Viglino/ol-ext#931]
when i use the split interaction i get an error:
Split not work is.sources_.push is not a function

Version ol-ext: 4.0.7
Version ol: 7.3.0

**Comment by aparzi** [comment]
The parameter sources is empty in Split.js

Anyone help me?

**Comment by Viglino** [comment]
What is your code ?

**Comment by Viglino** [comment]
I think there is a bug when no sources are specified but features.
Fix in the last commit

**Comment by aparzi** [comment]
@Viglino yes, I have open a MR #932

**Comment by aparzi** [comment]
@Viglino Can you release 4.0.8?

**Comment by aparzi** [comment]
> I think there is a bug when no sources are specified but features. Fix in the last commit

@Viglino Has the version containing this fix been released?

**Comment by Viglino** [comment]
ol-ext@4.0.8 is out with the fix!
