### ISSUE TITLE
FillPattern

### ISSUE THREAD

**Issue by b4l8ter** [Viglino/ol-ext#935]
How do I access FillPattern options? I tried using the getPattern_(options) method, but that didn't seem to retrieve what I expected. For example, how can I retrieve the "pattern" (name as a string) used to instantiate a FillPattern object?

**Comment by b4l8ter** [comment]
So for example there's no way to get pattern "sand" used to create a new fill pattern:
myFillPattern = new FillPattern({pattern:"sand"});

**Comment by Viglino** [comment]
No you have to set it after creation:
myFillPattern = new FillPattern({pattern:"sand"});
myFillPattern.set('pattern', "sand");

**Comment by b4l8ter** [comment]
I get an error message that "set" is not a function. It appears I can't set a property of a FillPattern object. However I can set a property using FillAttribute, so that's fine I'll use that.  Thanks for your help.
