### ISSUE TITLE
Adding PrintDialog to a ReactJS project

### ISSUE THREAD

**Issue by prosperva** [Viglino/ol-ext#936]
I am trying to convert this line
`printControl.on(['print', 'error'], function(e) {})` to `printControl.on(["print", "error"], function (e: any) {});` but I am getting this error `No overload matches this call.
  Overload 1 of 3, '(type: EventTypes, listener: (event: BaseEvent) => unknown): EventsKey',`

`change`, `error`, and `propertychange` are the only ones available but I want to check for print, then check what type of file the user is trying to print as shown in this vanilla js example

```
printControl.on(['print', 'error'], function(e) {
  // Print success
  if (e.image) {
    if (e.pdf) {
      // Export pdf using the print info
      var pdf = new jsPDF({
        orientation: e.print.orientation,
        unit: e.print.unit,
        format: e.print.size
      });
      pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0], e.print.imageWidth, e.print.imageHeight);
      pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
    } else  {
      // Save image as file
      e.canvas.toBlob(function(blob) {
        var name = (e.print.legend ? 'legend.' : 'map.')+e.imageType.replace('image/','');
        saveAs(blob, name);
      }, e.imageType, e.quality);
    }
  } else {
    console.warn('No canvas to export');
  }
});
```

**Comment by prosperva** [comment]
The npm package also is missing some options such as the include title as shown below:
![image](https://github.com/Viglino/ol-ext/assets/1531271/cafc0c86-1684-4531-8c3e-e13126a8986c)

**Comment by Viglino** [comment]
It's a typescript error, you can ask for a fix: https://github.com/Siedlerchr/types-ol-ext/issues
