### ISSUE TITLE
PrintDialog scale dropdown changes the map

### ISSUE THREAD

**Issue by prosperva** [Viglino/ol-ext#939]
When I click on the Print Dialog control and I change the scale on the popup, and then close the popup, the map has the scale from the popup. Can the popup changes not alter the map?

**Comment by Viglino** [comment]
The control print the map at the position and scale.
But you can save / restore the position / zoom: 
```javascript
var position, zoom;
printControl.on('show', () => {
  position= map.getView().getCenter()
  zoom = map.getView().getZoom()
})
printControl.on('hide', () => {
  map.getView().setCenter(position)
  map.getView().setZoom(zoom)
})
```

**Comment by prosperva** [comment]
Thanks that works
