### ISSUE TITLE
Dijkstra

### ISSUE THREAD

**Issue by aparzi** [Viglino/ol-ext#940]
Hi @Viglino,
Dijkstra works on VectorTileSource type ?

**Comment by Viglino** [comment]
No it needs to have a topology and MBT are not connected on tile's borders.
But you can use it with WFS (only on loaded features)

**Comment by aparzi** [comment]
@Viglino ok thanks.

**Comment by aparzi** [comment]
Hi @Viglino,
I implemented Dijkstra but route result is empty. Can you help me?

<img width="1382" alt="Screenshot 2023-05-15 alle 11 19 11" src="https://github.com/Viglino/ol-ext/assets/16490359/30336b76-453f-463b-94af-fb1e545c010b">

**Comment by aparzi** [comment]
@Viglino features should be just linestring or also points?

**Comment by aparzi** [comment]
I solved. Thanks
