### ISSUE TITLE
Comination of getClusterExtent with maxZoom and features with different coordinates

### ISSUE THREAD

**Issue by bierett** [Viglino/ol-ext#943]
### Summary
`getClusterExtent(feature)` return extent instead of `null` if user has configured maxZoom in ol.View.
Maybe not really an ol-ext bug, but maybe you have an idea how to solve it.

### Long version
Additional to #543 I've update the example with three clusters (see example [JSFiddle](https://jsfiddle.net/a4u862xb/1/)):
- First cluster on the left with three features and three different coordinates
- 2nd cluster between first and 3rd cluster with two features and equal coordinates
- 3rd cluster on the right with three features and three equal coordinates

ol view is configured with maxZoom = 18.

I've the following problem/question:
**Precondition:** map zoom = 17

**Expected behaviour:**
If I click on each cluster, the map is zoom to the cluster. Cluster is selected and features are visible.

**Actual behaviour:**
Only the 2nd and 3rd cluster can be zoomed and selected from map zoom-level 17.
While clicking the first cluster, map is only zoomed to the cluster. It can be selected by click twice (not desired).

**Background:**
In the implementation I check if `getClusterExtent(feature)` is null. If null, the cluster is selected manually to show all features.
The 3rd cluster has three features with different coordinates, so `getClusterExtent` return the extent of all features. Because of the implementation (checking `!extent`), the cluster isn't selected manually.
I can move `selectCluster({selected: [feature]})` outside `if (!extent)`. In this case, while each click of the cluster, the cluster is selected.

Without any maxZoom configuration, all is fine.

**Comment by Viglino** [comment]
This is not a bug, 
1. `getClusterExtent` returns null if there is only one feature in the cluster or if all features have the same coords
2. when zooming the clusters are recalculated and you can't access the old one (can't select them anymore)

When you zoom, you have to check if there is still only one cluster in the previous area and select it
See: https://jsfiddle.net/Viglino/xz5708s2/45/

**Comment by bierett** [comment]
Thanks for the explanation and for the working example. :thumbsup:
