### ISSUE TITLE
No animation in the infinite map on the x-axis.

### ISSUE THREAD

**Issue by seiyagg** [Viglino/ol-ext#944]
Example:
[ol-ext: convex hull](https://viglino.github.io/ol-ext/examples/geom/map.cluster.convexhull.html)

Step: 
Scroll left/right to another map(maybe next to the map has animation). There is no animation in it.

Could you please solve it or give me a proposal？
Thanks

**Comment by Viglino** [comment]
Animation is only on the current world...
