### ISSUE TITLE
Feature popup - capture the current feature on multiple selection

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#945]
Can you tell me how to get the current feature selected from your "popup feature" in case of multiple query of overlapping geometries? 

![image](https://github.com/Viglino/ol-ext/assets/89784373/c8f3f458-c335-4567-ae7f-4b373e144f2d)

I would like to clone the single current feature to insert it in a new layer in order to apply a dedicated style to it.

I intend to do this because I currently have this problem; in my project there are MultiPolygon geojson and if I apply a style to the main select with a border thicker than 0, visual artifacts occur (I select only one geometry but the thicker edge is randomly applied to other geometry)

![image](https://github.com/Viglino/ol-ext/assets/89784373/7fbad495-69de-4b4c-b708-dcbd313ce3a9)

So I thought I'd clone the selected feature in a new layer to apply the dedicated style. But if I act trying to capture the current feature on the main select I get an array, but I can't locate the current feature that "popup feature" is browsing.
Thank you very much

**Comment by Viglino** [comment]
The current feature is the selected one...
```javascript
const currentFeature = select.getFeatures().item(0)
```

**Comment by andreaordonselli** [comment]
Thanks a lot, very helpful as always

```javascript
// vector layer for current feature
var currentFeatureLayer = new ol.layer.Vector({
  source: new ol.source.Vector(),
  style: selectStyle,
});
map.addLayer(currentFeatureLayer);

// get the current feature from the popup
popup.on('select', function() {
  currentFeatureLayer.getSource().clear();
  const currentFeature = popupselect.getFeatures().item(0);
  currentFeatureLayer.getSource().addFeature(currentFeature);
});
```
