### ISSUE TITLE
Legend is empty but visible when no linked layers are visible

### ISSUE THREAD

**Issue by jmgomezpoveda** [Viglino/ol-ext#946]
Legends can be associated to layers, as we can see in the corresponding sample: https://viglino.github.io/ol-ext/examples/legend/map.control.legend.layer.html

If none of the layers are visible, the legend balloon and the close icon are still visible. In the above example, just unselect both layers, and the balloon stays with just "Legend" and the close icon.

Ideally, I would expect that the whole legend would be invisible if none of the associated layers are visible (and maybe the contracted legend button could be grayed out).

**Comment by jmgomezpoveda** [comment]
That looks beautiful!

**Comment by jmgomezpoveda** [comment]
I have just tried the 4.0.9 version and it is not hiding the label for me.

Now, the way I am adding or removing layers is by enabling/disabling them:

`myLayer.setVisible(false);`

Should this be triggering the new mechanism to detect empty legends? Or would I need to remove the layer from the map?

**Comment by Viglino** [comment]
The map legend collapse when there is no item in it. 
Hidding the layers remove the layer legend from the map legend.
You should not have to do something else.
Do you have an example to see what's up?

**Comment by jmgomezpoveda** [comment]
You are right. Just doing setVisible disables the legend: https://jsfiddle.net/t95u7bcp/

Let me review my code. For some reason the ol-empty class is not being added to the legend's button's parent. Maybe I did something wrong in the upgrade steps.
