### ISSUE TITLE
Legends with 2 columns use 100% width when stacked

### ISSUE THREAD

**Issue by jmgomezpoveda** [Viglino/ol-ext#948]
Following the [2-columns sample](https://viglino.github.io/ol-ext/examples/legend/map.control.legends.html). If the map is narrower than the legend, one legend appears stacked on top of the other, as expected. However, the stacked legend uses width 90%, which is more than required.

![image](https://github.com/Viglino/ol-ext/assets/3722516/8de58664-0837-443d-a934-fca11b6a0f25)

Ideally the stacked legend would be as thin as possible (as it is the case with the legends not using this 2-column approach).

**Comment by Viglino** [comment]
This is a css issue. Maybe you can try to use flex to make the columns work properly...
