### ISSUE TITLE
Snapping Guides seems don't work when useGeographic() is used

### ISSUE THREAD

**Issue by vitalus** [Viglino/ol-ext#949]
Firefox completely freezes, Chrome draws 1 horizontal line... it seems  mathematics does not work well with small numbers (decimal degrees)

**Comment by vitalus** [comment]
![image](https://github.com/Viglino/ol-ext/assets/395782/f5932039-3dee-42c3-bb5f-ddcfb43adfbb)

**Comment by vitalus** [comment]
Map's view extent is still in EPSG:3857  but coords are in EPSG:4326.

**Comment by Viglino** [comment]
Snap guides can only be calculated on the map projection.
useGeographic doesn't modify the view projection but the returned coordinates that doesn't mix with the current view projection...

**Comment by vitalus** [comment]
Because  coordinates from geometry tools are now  lat and lon (this is what globally useGeographic() does),  but  view's projection is still EPSG:3857. So, yes.

I would say   snapping guides  logic is just not compatible at the moment with useGeographic() mode...  this situation can be detected in code and some reprojection to be done, may be?

**Comment by Viglino** [comment]
Maybe it can be detected and coords converted on the fly but I 've to investigate...

**Comment by vitalus** [comment]
I do not know what was done to complete this ticket..  But guiding lines are not working in my case (I have been trying many times since 2023 with different versions of ol-ext)
