### ISSUE TITLE
[LayerswitcherImage] Not working - js error

### ISSUE THREAD

**Issue by marquetd** [Viglino/ol-ext#95]
Hi,

The layer switcher image is not working anymore.

in the example http://viglino.github.io/ol-ext/examples/control/map.switcher.image.html
I have the following error : 
<pre>
Uncaught TypeError: this.displayInLayerSwitcher is not a function
    at ol-ext.js:2986
    at B.k.forEach (ol.js:52)
    at ol.control.LayerSwitcherImage.drawList (ol-ext.js:2985)
    at ol.control.LayerSwitcherImage.ol.control.LayerSwitcher.drawPanel_ (ol-ext.js:660)
    at ol-ext.js:652
</pre>

**Comment by Viglino** [comment]
I'll try fix it asap...

**Comment by Viglino** [comment]
Fix in the last commit.
Thanks for the feedback!

**Comment by marquetd** [comment]
Thanks !
