### ISSUE TITLE
Print Dialog inside body and not shadow root

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#950]
I have a ol.map that lives in the shadow root.  Problem with the Print Dialog is that it is created in the body of the html and not the same root as where the ol.map element lives.  How can this be done?

**Comment by Viglino** [comment]
Maybe you can move it afterwards...
```javascript
map.getTargetElement().appendChild(printControl._printDialog.element)
```

**Comment by 1Map** [comment]
Thanks, I think it is more a question for vue3_openlayers.  Not sure if they create the control or ol-ext?

```
    <ol-map
    >
      <ol-view
          :center="mapSettings?.mapPosition?.olCenter"
          :rotation="mapSettings?.mapPosition?.rotation"
          :zoom="mapSettings?.mapPosition?.zoom"
          :projection="mapSettings?.projection"
      />

      <ol-control-bar>
        <ol-control-printdialog />
      </ol-control-bar>

      <ol-layerswitcher-control />

      <ol-tile-layer
        title="OSM"
        :baseLayer="true"
      >
        <ol-source-osm />
      </ol-tile-layer>
    </ol-map>
```

**Comment by Viglino** [comment]
If the control is created a new button appears on the map.
In vue3-openlayers examples it seems to use print control 😃 called `ol-printdialog-control` end not `ol-control-printdialog`
see: https://vue3openlayers.netlify.app/componentsguide/mapcontrols/
and: https://vue3openlayers.netlify.app/componentsguide/mapcontrols/printdialog/

**Comment by 1Map** [comment]
Thanks, does not make a difference, the control is still created in the body of the html and not the shadow root.  Will have to find out where exactly the control is created in the body.

In the below image I have 2 custom vue elements.  You can clearly see that the print dialog is created in the body part (at the bottom), whereas the print dialog was suppos to live in the shadow root of each custom element.

<img width="1808" alt="image" src="https://github.com/Viglino/ol-ext/assets/1152458/1910593b-f122-4e7b-804c-7c8487603bf0">

**Comment by 1Map** [comment]
Any feedback on this issue?

**Comment by 1Map** [comment]
Here, you can see an example where I have 4 vue elements "widgets" on the same page, whereby I want a print dialog to mount onto the widget and not in the body.  Print dialog should have an optional property like, appendTo whereby you can specify the parent.

<img width="1920" alt="image" src="https://github.com/Viglino/ol-ext/assets/1152458/c2040c15-d361-4b84-87ce-84fd1014c101">

**Comment by Viglino** [comment]
I've added a `targetDialog` option to let you change the dialog target.

**Comment by 1Map** [comment]
Thanks.  Have you actually tested if it can Print (As I get a blank page in my page preview - Printer Preview).

Have you updated this change to the latest version, and what version?  I am on 4.0.8, but cannot see your change.

**Comment by Viglino** [comment]
The PrintDialog uses a mediaquery to hide all element but the map from print.
See https://github.com/Viglino/ol-ext/blob/master/src/control/PrintDialog.css#L253
Il you change the location of the dialog in the DOM you may have to write a new CSS to take it into account and make it run...

**Comment by 1Map** [comment]
Thanks, I am still not having any luck.  Can you please show me sample of how this is done.  Even with the targetDialog set the code still injects the "ol-print-document" class to the body and not to the targetDialog.

**Comment by Viglino** [comment]
The code is here: https://github.com/Viglino/ol-ext/blob/master/src/control/PrintDialog.css#L253
Every DOM element in the body is hidden (not printed):
```CSS
  body.ol-print-document > * {
    display: none!important;
  }
```
Except the print dialog:
```CSS
  body.ol-print-document > .ol-ext-print-dialog {
    display: block!important;
  }
```
So you have to make it visible (and his hierarchy) if it is not at the body root...

Do you have an online example?

**Comment by 1Map** [comment]
@Viglino Thanks,

I do understand how the css handles the visibility.  The problem here is not that easy.

If you have, for example 2 divs with print previews open.  Then, in media print the css does the following:

1) Hide all components in the body
```
@media print {
  body.ol-print-document > * {
    display: none !important;
  }
}
```

2) Only show ol-print-document and ol-ext-print-dialog
```
@media print {
  body.ol-print-document,
  body.ol-print-document .ol-ext-print-dialog {
    display: block !important;
  }
}
```

But, because the print dialog does not live in the body anymore (with the use of `targetDialog`), but each one in its own div, the above will not work and you have to impliment custom css.  Now, lets take the 2 div areas with a class of, lets say "onemapwidget", then I could have something like:

```
@media print {
  body.ol-print-document {
    margin: 0 !important;
    padding: 0 !important;
  }
  body.ol-print-document > * {
    display: none !important;
  }
  body.ol-print-document,
  body.ol-print-document .onemapwidget,
  body.ol-print-document .onemapwidget .ol-ext-print-dialog {
    display: block !important;
  }
  body.ol-print-document .onemapwidget,
  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-content {
    max-height: unset !important;
    max-width: unset !important;
    width: unset !important;
    height: unset !important;
  }
  body.ol-print-document .onemapwidget .ol-ext-print-dialog > form,
  body.ol-print-document .onemapwidget .ol-ext-print-dialog {
    position: unset;
    box-shadow: none;
    background: none !important;
    border: 0;
  }
  body.ol-print-document .onemapwidget .ol-ext-print-dialog > form > *,
  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-print-param {
    display: none !important;
    background: none;
  }
  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-content {
    display: block !important;
    border: 0;
    background: none;
  }
  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-print-map {
    position: fixed;
    background: none;
    width: auto;
    overflow: visible;
  }
  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-print-map .ol-page {
    transform: none !important;
    box-shadow: none !important;
    position: unset;
  }

  body.ol-print-document .onemapwidget .ol-ext-print-dialog .ol-print-map .ol-control-title {
    visibility: visible !important;
    background-color: rgba(255, 255, 255, 0.5);
    text-align: center;
    height: auto;
  }
}

```

But this will print preview all 2 maps on top of each other with the last map on top.

That is why I said, that you have to add a custom class to the print dialog, just before window.print happens and remove it after the print preview was done (hidden or printed).  Then it will be much easier to handle css based on only the "active" print preview (in case there are more than one print dialog open).

<img width="633" alt="image" src="https://github.com/Viglino/ol-ext/assets/1152458/dac2f07f-9a51-451e-966c-74012531d44d">

<img width="746" alt="image" src="https://github.com/Viglino/ol-ext/assets/1152458/a3df02d2-9b03-4096-925f-b2b4fe908a63">
