### ISSUE TITLE
Control Bar - conditionally show control

### ISSUE THREAD

**Issue by dutchigor** [Viglino/ol-ext#951]
I would like to conditionally  show a control in a control bar. When adding the control directly to the map, I can easily do this using the addControl and removeControl methods. However, there does not seem to be any way to do this within the control bar.

Would it be possible to add a removeControl method to the Bar class to handle such a use case?

**Comment by Viglino** [comment]
If you just want to toggle the control, you can add/remove it from the map (it will be added/removed from the bar.
You can also just show/hide it using CSS (to prevent click on the control), I use this method to expend the bar at will or to gray out a control when inactive.
For clarity, I've added a `removeControl` method to the ol/control/Bar in the last commit.

**Comment by dutchigor** [comment]
I just noticed that you have fixed this very quickly. Thanks! And sorry for my late response. I was indeed using css as a workaround, but not all controls allow you to add classes. For example the layer switcher does not. In any case, I just tested the new release and it works like a charm! 😄
