### ISSUE TITLE
Font Style - apply the same style during selection and add a border

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#954]
Good morning,
I'm using your font style http://viglino.github.io/ol-ext/examples/style/map.style.font.html
When I select a feature whose style is generated with font style, this is replaced by the style programmed in the select.

Not selected
![2023-06-08 11_35_34-Window](https://github.com/Viglino/ol-ext/assets/89784373/c3497c90-f320-483b-a803-576d7c93c459)

Selected
![2023-06-08 11_35_40-Window](https://github.com/Viglino/ol-ext/assets/89784373/8c893b2f-ad7e-4a1d-9fc1-c79b9b787fc2)

Do you know a way to keep the font style and apply a blue border like the one of the standard selection? Like this:
![image](https://github.com/Viglino/ol-ext/assets/89784373/326bed05-8018-428e-bab1-e9756d864ebb)

**Comment by mike-000** [comment]
As long as the feature is styled by its layer a select interaction style function can clone that style and change its FontSymbol stroke color (or it could change the fill color if you prefer).
```
  map.addInteraction(new ol.interaction.Select({
    style: function(feature, resolution) {
      return vector.getStyleFunction()(feature, resolution)?.map(function(style) {
        const clone = style.clone();
        clone.getImage()?.getStroke()?.setColor([0, 153, 255, 1]);
        return clone;
      });
    }
  }))
```
https://jsbin.com/piwavomido/edit?html,output

**Comment by andreaordonselli** [comment]
The style clone is perfect for the ol-ext font style, thanks Mike, great as usual.

I ask you for one last help, in my project I apply two different styles to the select, one for all geometries and one for geometries with a style containing `ol.style.FontSymbol` (ol-ext font style) or `ol.style.Icon` filtered with this function

```javascript
function hasFontSymbolOrIconStyle(feature, resolution) {
  
  var allLayers = map.getAllLayers();

  var layer = allLayers.find(function (layer) {
    if (layer instanceof ol.layer.Vector) {
      return layer.getSource().getFeatures().indexOf(feature) > -1;
    }
  });

  if (layer) {
    var styles = layer.getStyleFunction()(feature, resolution);
  
    if (Array.isArray(styles)) {
      return styles.some(function(style) {
        var image = style.getImage();
        return (
          (style instanceof ol.style.Style &&
            (image instanceof ol.style.FontSymbol ||
              image instanceof ol.style.Icon)) ||
          image instanceof ol.style.FontSymbol ||
          image instanceof ol.style.Icon
        );
      });
    }
  }
  
  return false;
}
```

In case the feature has style `ol.style.FontSymbol` (ol-ext font style) your clone code work perfectly ([example style](https://www.opengis.it/a_opengis/opengis_fontsymbol.js))
In case the feature has style `ol.style.Icon` your clone code doesn't work ([example style](https://www.opengis.it/ente/demo/styles/StruttureSensibili_style.js))

Maybe the problem in the second style is changing the stroke configured in `ol.style.RegularShape`?

``` javascript
return [
  new ol.style.Style({
    image: new ol.style.RegularShape({
      points: 20,
      radius: 14,
      // displacement: [6, -5],
      fill: new ol.style.Fill({
        color: "white"
      }),
      stroke: new ol.style.Stroke({
        color: "black",
        width: 1.5
      })
    })
  }),
  new ol.style.Style({
    image: new ol.style.Icon({
      imgSize: [50, 44.445],
      scale: 0.38,
      // anchor: [9, 9],
      anchor: [25, 25],
      anchorXUnits: "pixels",
      anchorYUnits: "pixels",
      rotation: 0.0,
      src: "styles/ambulatorio.svg"
    })
  })
];
```

In this [codepen](https://codepen.io/andreaordonselli/pen/yLRwLEp) you can view all, can you fix it to show the blue outline?

Thank you.

**Comment by Viglino** [comment]
That's because Icon style has no stroke style (so you can't change it).
Maybe you can change the icon color or use an ol-ext/style/Photo that has a `stroke` property.
See https://viglino.github.io/ol-ext/examples/style/map.style.photo.html

**Comment by andreaordonselli** [comment]
Thanks, I'll consider dropping ol.style.Icon using the source .svg in favor of your style/Photo.

However I still don't understand why I can't modify the stroke style; it is true that it is not present in ol.style.Icon, but it is present in ol.style.RegularShape here

```javascript
return [
  new ol.style.Style({
    image: new ol.style.RegularShape({
      points: 20,
      radius: 14,
      // displacement: [6, -5],
      fill: new ol.style.Fill({
        color: "white"
      }),
      stroke: new ol.style.Stroke({            <------------here
        color: "black",
        width: 1.5
      })
    })
  }),
  new ol.style.Style({
    image: new ol.style.Icon({
      imgSize: [50, 44.445],
      scale: 0.38,
      // anchor: [9, 9],
      anchor: [25, 25],
      anchorXUnits: "pixels",
      anchorYUnits: "pixels",
      rotation: 0.0,
      src: "styles/ambulatorio.svg"
    })
  })
];
```

With the hasFontSymbolOrIconStyle filter function I extract only the features with these styles, then I clone the entire style in the select and then I would like to be able to modify the stroke of ol.style.RegularShape, where am I going wrong?

Maybe this code doesn't work because the clone returns with 2 ol.style.Style and I have to select the first one?

```javascript
			// vector layer for current feature
			var currentFeatureLayer = new ol.layer.Vector({
			  displayInLayerSwitcher: false,
			  source: new ol.source.Vector(),
			  style: function (feature, resolution) {
				if (hasFontSymbolOrIconStyle(feature, resolution)) {
				  var allLayers = map.getAllLayers();

				  var layer = allLayers.find(function (layer) {
					if (layer instanceof ol.layer.Vector) {
					  return layer.getSource().getFeatures().indexOf(feature) > -1;
					}
				  });

				  return layer.getStyleFunction()(feature, resolution).map(function (style) {
					const clone = style.clone();
					clone.getImage().getStroke().setColor([0, 153, 255, 1]);
					clone.getImage().getStroke().setWidth(3);;
				  return clone;
					});
				}  else {
						  // Apply the selectStyle for other geometries
						  return selectStyle;
						}
					  }
			});
			map.addLayer(currentFeatureLayer);
```

**Comment by Viglino** [comment]
There is an error in the console in https://codepen.io/andreaordonselli/pen/yLRwLEp
`Uncaught TypeError: clone.getImage(...).getStroke`
You have to use optional chaining  (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and/or test if the function getStroke exist...
if (clone.getImage()?.getStroke) clone.getImage()?.getStroke()?.setColor([0, 153, 255, 1]);

**Comment by andreaordonselli** [comment]
Thank you both so much, you are unique.
I worked, and with this code there are no errors in the console and everything works perfectly, however it's a bad code, I'm not satisfied
```javascript
       return layer.getStyleFunction()(feature, resolution).map(function (style) {
          const clone = style.clone();
          const image = clone.getImage();
            if (image instanceof ol.style.RegularShape) {
              var wa = image.wa;
              wa.strokeStyle = 'rgba(0, 153, 255, 1)';
              wa.strokeWidth = 3;
             } if (image instanceof ol.style.FontSymbol) {
            image.getStroke().setColor([0, 153, 255, 1]);
	    image.getStroke().setWidth(3);
              }          
	return clone;
	});
```
I wrote the above code because this console log
```javascript
if (image instanceof ol.style.RegularShape) {
console.log(image)
```
returns
```
// [object Object] 
{
  "ua": 1,
  "ca": false,
  "Dr": 0,
  "ha": 1,
  "fa": [
    1,
    1
  ],
  "la": [
    6,
    -5
  ],
  "Ut": {},
  "va": null,
  "da": {
    "ka": "white"
  },
  "ko": [
    0,
    0
  ],
  "Jt": 20,
  "pa": 14,
  "Kt": 0,
  "ma": {
    "ka": "black",
    "Da": null,
    "Wa": 1.5
  },
  "fs": [
    30,
    30
  ],
  "wa": {
    "strokeStyle": "black",
    "strokeWidth": 1.5,
    "size": 30,
    "lineDash": null,
    "lineJoin": "round",
    "miterLimit": 10
  }
}
```
If I write
```javascript
if (image instanceof ol.style.RegularShape) {
  const stroke = image.getStroke()
```
i get
```
// [object Object]
{
  "ka": "black",
  "From": null,
  "Wa": 1.5
}
```
but if i go to change these values ​​it doesn't change the right stroke, then i used
```javascript
var wa = image.wa;
```
to achieve the right stroke.

I still don't understand why getStroke on image/RegularShape gives wrong stroke
the [codepen ](https://codepen.io/andreaordonselli/pen/yLRwLEp)is updated on line 180
Thanks, thanks

**Comment by mike-000** [comment]
You should not use minified internal properties, they change with each version of OpenLayers.  Using the documented API methods ensures the property is set and any other internal changes are made.  ol.style.FontSymbol is a subclass of ol.style.RegularShape so `image instanceof ol.style.RegularShape` may be true for both - if you need to distinguish them use `image instanceof ol.style.FontSymbol`.  Depending on the version of OpenLayers you may also need to call `image.render()` after updating the stroke properties.

**Comment by andreaordonselli** [comment]
Thank you Mike. I fixed the code with your suggestions and it works great. Now I am satisfied.
Viglino thanks again for your library.

```javascript
return layer.getStyleFunction()(feature, resolution).map(function (style) {
  const clone = style.clone();
  const image = clone.getImage();
  if (image instanceof ol.style.FontSymbol) {
    image.getStroke().setColor([0, 153, 255, 1]);
    image.getStroke().setWidth(3);
  } else if (image instanceof ol.style.RegularShape) {
    image.getStroke().setColor([0, 153, 255, 1]);
    image.getStroke().setWidth(3);
    image.render()
  } 
return clone;
});
```
