### ISSUE TITLE
Unable to access ol objects with ol-ext

### ISSUE THREAD

**Issue by RobertVogt** [Viglino/ol-ext#96]
I opened a stack-exchange question about this too but the problem seems to be access to the underlying ol-objects.

What I'm trying to accomplish is adding a measure tool-tip to GeoLocationDraw.  I can do this using the ol.interaction.Draw object but have been unable to figure out how the ol-ext methods or properties map to these objects or if this is even possible with ol-ext.

I'm using OL-Ext and have implemented using GPS to draw polygons and lines on an OpenLayers 3 map.

I'm trying to add a measure tool-tip while "follow" is active.

I've implemented this while drawing on the map but have not been able to translate it into the OL-Ext tools.

This is how I've done it while drawing on the map...

     `webMapValues.drawObj.on('drawstart',
      function (evt) {
             if (webMapValues.activeDrawControl == "Ruler") {
                            // set sketch
                            webMapValues.sketch = evt.feature;

                            /** @type {ol.Coordinate|undefined} */
                            var tooltipCoord = evt.coordinate;

                            listener = webMapValues.sketch.getGeometry().on('change', function (evt) {
                                var geom = evt.target;
                                var output;
                                if (geom instanceof ol.geom.Polygon) {
                                    webMapValues.rulerLength = formatArea(geom);
                                    tooltipCoord = geom.getInteriorPoint().getCoordinates();
                                } else if (geom instanceof ol.geom.LineString) {
                                    webMapValues.rulerLength = rcisMapService.formatLength(geom);
                                    tooltipCoord = geom.getLastCoordinate();
                                }
                                webMapValues.measureTooltipElement.innerHTML = webMapValues.rulerLength;
                                webMapValues.measureTooltip.setPosition(tooltipCoord);
                         });
                     }

     }, this);`

I would like to do the same thing with OL-Ext and this is where I am so far.

     `webMapValues.geoTrackActive.on("tracking", function (e) {
                    $("#accuraty").width((e.geolocation.getAccuracy()));
                    webMapValues.geoGauge.val(e.geolocation.getAccuracy());
                    $("#heading").val(e.geolocation.getHeading());
                    $("#z").val(e.geolocation.getAltitude());

                   
                        // set sketch
                        webMapValues.sketch = e.target.sketch_;

                        /** @type {ol.Coordinate|undefined} */
                    var tooltipCoord = e.geolocation.getPosition();

                   
                     var geom = e.target;
                            var output;
                            if (geom instanceof ol.geom.Polygon) {
                                webMapValues.rulerLength = formatArea(geom);
                                tooltipCoord = geom.getInteriorPoint().getCoordinates();
                            } else if (geom.get("type") instanceof ol.geom.LineString) {
                                webMapValues.rulerLength = rcisMapService.formatLength(geom);
                                tooltipCoord = geom.getLastCoordinate();
                            }
                    webMapValues.measureTooltipElement.innerHTML =  webMapValues.rulerLength;
                            webMapValues.measureTooltip.setPosition(tooltipCoord);
                       
                    

                

                },this);`

**Comment by Viglino** [comment]
Hy,
The `tracking` event is an event with a `feature` object.
You have to access the current geometry through this feature:
```javascript
webMapValues.geoTrackActive.on("tracking", function (e) {
  var feature = e.feature;
  var geom = e.feature.getGeometry();
  // Do something with the geom
  if (geom) {
    ...
  }
}
```
Be aware that the geom may be null (if no point available) so you have to test (`if (geom)`).
`e.target` is the control and not a geometry.

@+

**Comment by RobertVogt** [comment]
Thank you so much this was the answer, I just couldn't see how to get there.
