### ISSUE TITLE
FillAttribute Repeat Select Behavior

### ISSUE THREAD

**Issue by b4l8ter** [Viglino/ol-ext#964]
Whenever the FillAttribute is active, re-selecting a feature (e.g. by clicking a second time) appears to trigger another different type of selection event. The initial (first) select behaves as expected and styles as defined, however a second select (and any subsequent selects) uses the default OL select styling.

**Comment by b4l8ter** [comment]
This issue is still unresolved as of version 4.0.12.

**Comment by Viglino** [comment]
Do you have a working example?
FillAttribute is a Select interaction...

**Comment by b4l8ter** [comment]
`export const fillAttrib = new FillAttribute(
  { name: "fillColor" },
  { color: [255, 0, 0] }
);`

`const toggleFillColor = new Toggle({
  html: '<i class="fas fa-fill-drip"></i>',
  // html: '<span class="mdi mdi-20px mdi-format-color-fill"></span>',
  title: "Color",
  interaction: fillAttrib,
  // onToggle: function (bln) {
  //   console.log(`\nColor fill toggled to ${bln}`);
  // },
  bar: new Bar({
    toggleOne: true,
    controls: [
      new Toggle({
        className: "red colorToggle",
        onToggle: function () {
          fillAttrib.setAttribute("fill", "#ff000099");
        },
      }),
      new Toggle({
        className: "green colorToggle",
        onToggle: function () {
          fillAttrib.setAttribute("fill", "#00800099");
        },
      }),
      new Toggle({
        className: "blue colorToggle",
        onToggle: function () {
          fillAttrib.setAttribute("fill", "#0000ff99");
        },
      }),
      new Toggle({
        className: "yellow colorToggle",
        onToggle: function () {
          fillAttrib.setAttribute("fill", "#ffff0099");
        },
      }),
      customFillColor,
    ],
  }),
});`

`toolsbar.addControl(toggleFillColor);`
