### ISSUE TITLE
Access vertexFeature property

### ISSUE THREAD

**Issue by aparzi** [Viglino/ol-ext#966]
@Viglino At runtime for the ModifyFeature Interaction I see the vertexFeature property, but it's private. It is possibile access, at this property in anyway? Otherwise can I implementing get and set for this property

Thanks.

**Comment by Viglino** [comment]
Not sure it's an ol-ext property. Maybe it's Openlayers.

**Comment by aparzi** [comment]
yes maybe it is inherited from Openlayers. Can I expect a getter method for this property? Seeing the code should we be able to insert it?

**Comment by aparzi** [comment]
okay
