### ISSUE TITLE
Allow to style the link between cluster items

### ISSUE THREAD

**Issue by d-koppenhagen** [Viglino/ol-ext#969]
Currently the `SelectCluster` interactions allows to define a style for the features that are place in spiral or circle when click on them. This works fine, but there is no easy way to modify the Style for the created `selectclusterlink` Features that are drawn from the original cluster center to the targeting markers that are place in circle or spiral.

Having a look at the implementation, there is no style passed to it: 
https://github.com/Viglino/ol-ext/blob/master/src/interaction/SelectCluster.js#L222C8-L222C8

```js
cf = new ol_Feature({ 'selectclusterfeature': true, 'features': [cluster[i]], geometry: new ol_geom_Point(p) })
cf.setStyle(cluster[i].getStyle())
features.push(cf)
lk = new ol_Feature({ 'selectclusterlink': true, geometry: new ol_geom_LineString([center, p]) })
features.push(lk)
```

Could this be implemented?

**Comment by mike-000** [comment]
If a feature does not have a style it is styled by the layer style
https://github.com/Viglino/ol-ext/blob/master/src/interaction/SelectCluster.js#L63
so you need to include a `stroke` in `featureStyle`.

The example sets a 1 pixel wide white stroke https://github.com/Viglino/ol-ext/blob/master/examples/animation/map.animatedcluster.html#L171

**Comment by d-koppenhagen** [comment]
Okay, this works fine! Thanks for pointing me in this direction.
