### ISSUE TITLE
SearchFeature - missing some records

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#97]
I have strange behavior on search feature control.
In my source have filter records:

![search_features_source](https://user-images.githubusercontent.com/8928341/38406819-4221b484-3977-11e8-8222-ab81a3f78d54.jpg)

But in search feature field  after filter "Waryńskiego 4" get only:

![search_features](https://user-images.githubusercontent.com/8928341/38406826-49e220a0-3977-11e8-8e49-3912a645894e.jpg)

Code:
```
		var select = new ol.interaction.Select({});
		map.addInteraction(select);
		
		var search = new ol.control.SearchFeature(
			{	source: vS_obiektySearch,
				property: "nazwa",
				minLength: 2,
				maxItems: 25,
				placeholder: 'Pokaż obiekt...',
				label: 'szukaj'
			});

		search.on('select', function(e)
			{	console.log('run search_on W...'+e.search);
				select.getFeatures().clear();
				select.getFeatures().push (e.search);
				console.log(e.search);
				var p = e.search.getGeometry().getFirstCoordinate();
				console.log(p);
				//e.search.setStyle(sc_ClickPoint);
				map.getView().setZoom(18);
				map.getView().animate({ center:p });
			});
```
Library:
ol-ext.min.js (dowload today) 
the same efect on ol3-ext.min and searchfeaturecontrol.js, searchcontrol.js

Ps. Enabled search control for whole surface my map so had all search-object default.

**Comment by Viglino** [comment]
What sort of source is `vS_obiektySearch` ?
If it is a WFS like, the SearchFeature control only look on features that are loaded (displayed on the screen).

**Comment by Viglino** [comment]
The search control search in the content of the source: `vS_obiektySearch.getFeatures()`
Can you list the content of the source in the `ldFe_obiektySearch` function?
```javascript
for (var i=0, f; f = fT_obiektySearch[i]; i++) {
  console.log(f.get('nazwa'));
}
```

**Comment by Bear4** [comment]
Is there limit records on serchfeatures?
My set of all object has 8946 items.

When enable search control on realy big close-up level 19 then get first features 'Waryńskiego 4 [b]' but without second 'Waryńskiego 4 (T) [w]' away a few meters from first.

**Comment by Bear4** [comment]
![console_log](https://user-images.githubusercontent.com/8928341/38420478-2122582e-39a4-11e8-9cf3-2dcb0b81ae15.jpg)

![list_search](https://user-images.githubusercontent.com/8928341/38420497-33f6291c-39a4-11e8-8944-2cc1f3dba42c.jpg)

**Comment by Viglino** [comment]
They're is a limit options (maxItems) for items in the menu.
There is no geometry filter.

**Comment by Viglino** [comment]
You can define your own autocomplete function to test what you want to be display in the menu:
```javascript
var search = new ol.control.SearchFeature({
   source: vS_obiektySearch,
  placeholder: 'Pokaż obiekt...',
  label: 'szukaj',
  autocomplete: function (s) {	
    var result = [];
    // regexp
    s = s.replace(/^\*/,'');
    var rex = new RegExp(s, 'i');
    // The source
    var features = this.source_.getFeatures();
    for (var i=0, f; f=features[i]; i++) {
      if (rex.test(f.get('nazwa'))) {	
        result.push(f);
        if ((--max)<=0) break;
      }
    }
    return result;
  }
});
```

**Comment by Bear4** [comment]
Maybe it's not case search control features but OpenLayers... In source (console.log) have all set of features but not everyone has displayed on the layer.
And if they do not display - they don't get for search too.  Why that is - I don't know.  I will try to check it.
Thanks for Your patience and help.

**Comment by bbogda** [comment]
I found out what was broken with missing some records...
Source was taken fom view not table. 
It was three table union about 8600 points.
Generating source taken over 700 - 1000 msec
so some records wasn't catch into search control.
After generating table and set table as source everything work proper.
