### ISSUE TITLE
Can't make PrintDialog target work

### ISSUE THREAD

**Issue by lokhus** [Viglino/ol-ext#971]
I'm trying to show the PrintDialog inside a div using "target" but the button is always rendered in the body.
Example code:
```
const printControl = new PrintDialog({
    target: document.querySelector('.it-goes-here'),
    className: 'toolbar-btn',
    print: false,
    copy: false,
});
```
BTW, the "print" parameter doesn't seem to work neither as the "Print..." button is displayed with "print: false".
Thanks!

**Comment by Viglino** [comment]
The `target` option was not supported...
The last commit should fix it.
You can use CSS to hide the button meanwhile...

The `print` option is an old option to handle export select input. 
You'll better use formats to handle print select options (see [example](https://viglino.github.io/ol-ext/examples/canvas/map.control.printdialog.html)) or CSS to hide options in the dialog.

**Comment by lokhus** [comment]
Thanks a lot, that's great.
