### ISSUE TITLE
Adding more controls to the print control popup

### ISSUE THREAD

**Issue by prosperva** [Viglino/ol-ext#973]
Is there a simple way to add more controls to the print popup. For example, a way for user to change title font such bold and italic?

I came across this example http://viglino.github.io/ol-ext/examples/canvas/map.canvas.control.html and would like to include the styling controls

**Comment by Viglino** [comment]
You can use the [printDialog](http://viglino.github.io/ol-ext/examples/canvas/map.control.printdialog.html)
There is a `show` event that lets you add your own controls:
```javascript
printControl.on('show', (e) => {
    const newDiv = document.createElement("div");
    newDiv.innerHTML = '<i>your own controls</i>'
    e.userElement.appendChild(newDiv)
})
```
