### ISSUE TITLE
LayerSwitcher scroll on touch mobile

### ISSUE THREAD

**Issue by anielawrzesinska** [Viglino/ol-ext#976]
Hi,
Is it possible to turn on LayerSwitcher scroll on touch on mobile devices? 
Scroll is working via PC.

great work with this extension!

**Comment by Viglino** [comment]
There is a `noScroll` options when you create it.
Visible on [LayerShop](http://viglino.github.io/ol-ext/examples/control/map.switcher.shop.html) example at least

**Comment by anielawrzesinska** [comment]
Scroll is working just fine, but "on touch" event does not work on mobile devices. I would like to "swipe down" layers list on the mobile the same way i scroll on PC.

**Comment by Viglino** [comment]
Use ol/control/LayerShop instead.

**Comment by anielawrzesinska** [comment]
Thanks, I'll try!
