### ISSUE TITLE
Question: Is it possible to only download the visible tiles of a masked/cropped layer with ol-ext?

### ISSUE THREAD

**Issue by xjeffdbx** [Viglino/ol-ext#977]
I just found ol-ext and it is awesome :) 

I found this cropping example which seems like an elegant fix for a problem I am trying to solve: https://viglino.github.io/ol-ext/examples/filter/map.filter.crop.html

However I noticed that all tiles for _both_ layers are downloaded even though the Streets map is cropped/masked.  I was hoping that any non-visible tiles for the Streets map that are cropped out would not be downloaded (essentially how an Extent would work).

Is it possible to prevent unseen tiles from being downloaded with ol-ext?

Here is my related StackOverflow question that I posted yesterday:  
https://stackoverflow.com/questions/76725742/openlayers-tilelayer-extent-issues-on-an-infinitely-panning-map?noredirect=1#comment135274161_76725742

Thanks for any info you can provide!

**Comment by Viglino** [comment]
Crop filter only prevent drawing.
You have to set the extent of the layer to the crop extent to prevent tile load.

**Comment by xjeffdbx** [comment]
No worries, thanks for the quick response!
