### ISSUE TITLE
error in Shadow.js under typescript / angular 5

### ISSUE THREAD

**Issue by dgodard** [Viglino/ol-ext#98]
I am using ol-ext in a webpack, angular 5 / typescript application.
Shadow.js prodives an error

import olext_style_Shadow from "ol-ext/style/shadow";
...
var ol_style_Shadow = function(opt_options)
{	options = opt_options || {};
...
The error is : option undefined in shadow function

Correction that worked for me : add "var" in front of "option" :
var ol_style_Shadow = function(opt_options)
{	var options = opt_options || {};

You can also redefine opt_options :
opt_options = opt_options || {};

Can you correct this point in you library ?

Best regards

**Comment by Viglino** [comment]
Fix in the last commit.
Thanks for the feedback!
