### ISSUE TITLE
upgrade from OL3 

### ISSUE THREAD

**Issue by pitommasi** [Viglino/ol-ext#980]
So, as the title suggests, I got a website that uses OL3 and openlayers-ext and I'd like to update OL# to at least OL6, in order to make use of the CloudOptimised TiFF support.

Given that I could use the standalone version (not module) of OL6, will that work with openlayers-ext?

Otherwise, what options do I have besides rewriting the whole website to use modules?

**Comment by mike-000** [comment]
The examples https://viglino.github.io/ol-ext/ use the latest standalone `ol.js`.  Just use the browser's view source option to see what code is needed.

**Comment by pitommasi** [comment]
Thanks, you're a star!!!

What I was wondering is whether there was a standalone version of ol-ext, not of ol.

Now I see from the source in the browser that there's a dist folder inside the examples with the "compiled" files!
Case solved, I'd say...
