### ISSUE TITLE
Possible to put custom names for labels

### ISSUE THREAD

**Issue by DINH-iy** [Viglino/ol-ext#987]
Im using the ol-ext layerswitcher If you create a layer you need to pass in the layername, this is the actual name of the layer from the source. When i use something custom like ol-ext to have control the name i see for each field is the layername, only thing is i dont want to use that name i want to use a different custom name, example:

I have a layer:
'Actueel_ortho25', 'https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0',

and instead of seeing ' Actueel_ortho' id like to be able to set something custom like 'Ortho laag'

how would i achieve this?

**Comment by Viglino** [comment]
You have to set the `title` property! It is used in the layerswitcher (name is used when not defined):
```javascript
layer.set('title', 'Ortho laag')
```
