### ISSUE TITLE
Videorecorder dynamic tooltip

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#988]
How can I set the Videorecorder Control tooltip (title), like in, for example the PrintDialog Control?

https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.VideoRecorder.html

https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.PrintDialog.html

**Comment by Viglino** [comment]
I've added default tooltips you can overwrite:
```javascript
ol.control.VideoRecorder.prototype.tips = {
  start: 'start video',
  stop: 'stop',
  pause: 'pause',
  resume: 'resume'
}
```
and a new method to set tips:
```javascript
ctrl.setTooltip('start', 'Start recording...');
```

**Comment by 1Map** [comment]
@Viglino Thanks, I will wait for the next release as I am on 4.0.11

**Comment by Viglino** [comment]
Meanwhile you can do: 
```javascript
ctrl.element.querySelector('button.ol-start').title = 'start recording...';
```
