### ISSUE TITLE
error in using Hexbin.js under typescript / angular 5

### ISSUE THREAD

**Issue by cuomoeugenio** [Viglino/ol-ext#99]
I am using ol-ext in a webpack, angular 5 / typescript application.
I found an error when use Hexbin.js.

import HexBin from 'ol-ext/source/Hexbin';
...
 var source  = new ol_source_Vector();
 var hexbin = new HexBin(
      {	source: source,		// source of the bin
        size: 10			// hexagon size (in map unit)
      });

ERROR:

_Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object._ol_.inherits (index.js:216)
    at eval (HexGrid.js:32)
    at Object.../../../../ol-ext/render/HexGrid.js (vendor.bundle.js:304)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (Hexbin.js:1)
    at Object.../../../../ol-ext/source/Hexbin.js (vendor.bundle.js:312)
    at __webpack_require__ (inline.bundle.js:55)_

**Comment by Viglino** [comment]
Yes, the line should be:
````
ol.inherits (ol_HexGrid, ol_Object);
````
with `ol_Object` instead of `ol.Object`

**Comment by Viglino** [comment]
Done in the last commit

**Comment by cuomoeugenio** [comment]
Thanks, It's possible to publish the upgrades in npm too?

**Comment by Viglino** [comment]
I'll try to publish this week-end

**Comment by cuomoeugenio** [comment]
Thanks

**Comment by Viglino** [comment]
ol-ext v2.0.2 is published!
