### ISSUE TITLE
Transform drag handle is not precise 

### ISSUE THREAD

**Issue by MichalK6677** [Viglino/ol-ext#993]
I want to use Transform interaction toghether with Snap. Snap works based on cursor position so cursor should always drag center of the handle. It's not the case for Transform interaction and it's even more visible with hitTolerance.

**Scenario:** 
I want to resize polygon and snap to predefined points. With hitTolerance e.g. 40, I can drag 40 pixels out of the drag handle. Hence, openlayers does not snap to drag handle but to cursor and it's 40 pixes out.
![wrongSnap](https://github.com/Viglino/ol-ext/assets/3100059/4c1c47b2-7f39-4644-a37e-ea5053575a32)

**How it should/could work:** 
When I start drag out of the handle (because of hitTolerance), the drag handle is automatically moved to cursor position.
![goodSnap](https://github.com/Viglino/ol-ext/assets/3100059/1cf9123e-9a53-46e6-953f-eaecb922f5ee)

Here is code example: 
https://codesandbox.io/s/snap-forked-kpf56q?file=/main.js

You just need to coment/uncoment this section to see the difference:
![image](https://github.com/Viglino/ol-ext/assets/3100059/5519fc40-91d6-4372-b9d7-b132407f0b80)

This is change in code:
![image](https://github.com/Viglino/ol-ext/assets/3100059/4c70ad64-ca62-4530-acbb-dc059665e932)

**Comment by MichalK6677** [comment]
There is a problem with solution `this.coordinate_ = feature.getGeometry().getCoordinates(); //evt.coordinate`
when there is `translateFeature: true`

Check it here (when you drag the rectangle then it disappears):
https://codesandbox.io/s/snap-forked-4ktwhr?file=/main.js

Maybe center or topLeft of the feature extent could be used when translateFeature: true?

**Comment by Viglino** [comment]
I fall back to the previous method when clicking on the feature to move it (i.e. use the pointer position)
