### ISSUE TITLE
Use PrintDialog to always prompt Can't save map canvas...

### ISSUE THREAD

**Issue by FED-Noob** [Viglino/ol-ext#995]
Good morning. Excuse me. I have a question to consult:
`import ol_control_PrintDialog from 'ol-ext/control/PrintDialog'
import ol_PerspectiveMap from "ol-ext/map/PerspectiveMap";
mapInstance.current.addLayer(groupCereal.current);
    var printControl = new ol_control_PrintDialog({ 
        pdf: true,
        openWindow: false
    });
    printControl.setSize('A4');
    mapInstance.current.addControl(printControl);
    printControl.on(['print', 'error'], function (e) {
      if (e.image) {
          if (e.pdf) { 
              const pdf = new jsPDF({
                  orientation: e.print.orientation,
                  unit: e.print.unit,
                  format: e.print.size
              });
              pdf.addImage(e.image, 'JPEG', e.print.position[0], e.print.position[0],  e.print.imageWidth, e.print.imageHeight);
              pdf.save(e.print.legend ? 'legend.pdf' : 'map.pdf');
          } else { 
              e.canvas.toBlob(function (blob) {
                  const name = (e.print.legend ? 'legend.' : 'map.') + e.imageType.replace('image/', '');
                  saveAs(blob, name);
              }, e.imageType, e.quality);
          }
      } else {
          console.warn('No canvas to export');
      }
  });`
![Snipaste_2023-09-07_23-37-03](https://github.com/Viglino/ol-ext/assets/53297078/a1f2dc39-b965-46c3-bcb3-2f8154613334)

**Comment by Viglino** [comment]
You have to set `crossOrigin` to "anonymous" in your images sources to access pixel data or the map canvas is tainted end cannot be copied.
see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by FED-Noob** [comment]
I see. Thank you very much
